Repository twentyhq/twenty, pull requests merged in 2023-08, with the labels that each got.

#1017 feat: persist resized column widths
  front/src/generated/graphql.tsx
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/companies/table/components/CompanyTableMockData.tsx
  front/src/modules/people/table/components/PeopleTable.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/GenericEntityTableData.tsx
  front/src/modules/ui/table/hooks/useLoadView.ts
  front/src/modules/ui/table/hooks/useSetEntityTableData.ts
  front/src/modules/views/queries/create.ts
  front/src/modules/views/queries/select.ts
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/companies.ts
  front/src/testing/mock-data/people.ts
  server/src/ability/ability.factory.ts
  server/src/ability/ability.module.ts
  server/src/ability/handlers/view-field.ability-handler.ts
  server/src/core/view/resolvers/view-field.resolver.ts
Labels: run-chromatic

#1050 Fix Avatars no centered
  front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx
  front/src/modules/users/components/Avatar.tsx
Labels: run-chromatic

#1032 Feat/filter activity inbox
  front/src/modules/activities/comment/CommentHeader.tsx
  front/src/modules/activities/components/ActivityAssigneePicker.tsx
  front/src/modules/activities/components/TaskGroups.tsx
  front/src/modules/activities/components/TaskList.tsx
  front/src/modules/activities/components/TaskRow.tsx
  front/src/modules/activities/components/__stories__/TaskList.stories.tsx
  front/src/modules/activities/hooks/useCompleteTask.ts
  front/src/modules/activities/hooks/useInitializeTasksFilters.ts
  front/src/modules/activities/hooks/useTasks.ts
  front/src/modules/activities/states/TasksContext.ts
  front/src/modules/activities/timeline/components/TimelineActivity.tsx
  front/src/modules/activities/types/TaskForList.ts
  front/src/modules/tasks/hooks/useTasks.ts
  front/src/modules/ui/filter-n-sort/components/FilterDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/GenericEntityFilterChip.tsx
  front/src/modules/ui/filter-n-sort/components/MultipleFiltersDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/SingleEntityFilterDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/types/Filter.ts
  front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  front/src/modules/users/components/FilterDropdownUserSearchSelect.tsx
  front/src/pages/companies/companies-filters.tsx
  front/src/pages/tasks/Tasks.tsx
  front/src/pages/tasks/__stories__/Tasks.stories.tsx
  front/src/pages/tasks/tasks-filters.tsx
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/activities.ts
  front/src/utils/__tests__/date-utils.test.ts
  front/src/utils/date-utils.ts
Labels: run-chromatic

#1065 Refactor: Morph strategy on `PipelineProgress`
  front/src/generated/graphql.tsx
  front/src/modules/companies/components/HooksCompanyBoard.tsx
  front/src/modules/companies/components/NewCompanyProgressButton.tsx
  front/src/modules/companies/types/CompanyProgress.ts
  front/src/modules/pipeline/queries/select.ts
  front/src/modules/pipeline/queries/update.ts
  front/src/pages/opportunities/opportunities-filters.tsx
  front/src/testing/mock-data/pipeline-progress.ts
  front/src/testing/mock-data/pipelines.ts
  server/src/database/migrations/20230803115502_add_entities_on_pipeline_progress/migration.sql
  server/src/database/migrations/20230803121208_data_migration_move_progressable_ids_to_typed_fields/migration.sql
  server/src/database/migrations/20230803141808_remove_progressable_id_from_pipeline_progress/migration.sql
  server/src/database/migrations/20230803143326_remove_progressable_type_on_pipeline_progress/migration.sql
  server/src/database/schema.prisma
  server/src/database/seeds/pipelines.ts
Labels: run-chromatic

#1061 Improve mouse tracking
  front/src/modules/activities/components/ActivityRelationPicker.tsx
  front/src/modules/companies/table/components/CompanyTableMockData.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldEditMode.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/editable-field/hooks/useRegisterCloseFieldHandlers.ts
  front/src/modules/ui/filter-n-sort/components/DropdownMenuContainer.tsx
  front/src/modules/ui/input/relation-picker/components/MultipleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/modal/components/Modal.tsx
  front/src/modules/ui/right-drawer/components/RightDrawer.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/components/EntityTableCell.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableRow.tsx
  front/src/modules/ui/table/components/GenericEntityTableData.tsx
  front/src/modules/ui/table/editable-cell/hooks/useRegisterCloseCellHandlers.ts
  front/src/modules/ui/table/editable-cell/type/components/DateCellEdit.tsx
  front/src/modules/ui/table/hooks/useLoadView.ts
  front/src/modules/ui/table/states/resizeFieldOffsetState.ts
  front/src/modules/ui/table/states/viewFieldsState.ts
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
  front/src/modules/ui/top-bar/TopBar.tsx
  front/src/modules/ui/utilities/pointer-event/hooks/__tests__/useListenClickOutsideArrayOfRef.test.tsx
  front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
  front/src/modules/ui/utilities/pointer-event/hooks/useTrackPointer.ts
  front/src/pages/tasks/Tasks.tsx
Labels: run-chromatic

#1063 Fix #1059: Replace "Inbox" by "Notifications" in navigation
  .ergomake/docker-compose.yml
  front/src/AppNavbar.tsx
  front/src/modules/ui/icon/index.ts
Labels: awaiting author

#1056 feat: add table columns
  front/src/generated/graphql.tsx
  front/src/modules/companies/table/components/CompanyTableMockData.tsx
  front/src/modules/ui/button/components/IconButtonGroup.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/components/EntityTableColumnMenu.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableRow.tsx
  front/src/modules/ui/table/hooks/useLoadView.ts
  front/src/modules/ui/table/states/viewFieldsState.ts
  front/src/modules/views/queries/create.ts
  server/src/core/view/resolvers/view-field.resolver.ts
Labels: awaiting author

#1078 feat: show/hide table columns
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/button/components/IconButtonGroup.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuHeader.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuItem.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuSubheader.tsx
  front/src/modules/ui/dropdown/components/__stories__/DropdownMenu.stories.tsx
  front/src/modules/ui/filter-n-sort/components/DropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/FilterDropdownFilterSelect.tsx
  front/src/modules/ui/filter-n-sort/components/FilterDropdownOperandButton.tsx
  front/src/modules/ui/filter-n-sort/components/SortDropdownButton.tsx
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/table/components/EntityTableColumnMenu.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableRow.tsx
  front/src/modules/ui/table/hooks/useLoadView.ts
  front/src/modules/ui/table/states/viewFieldsState.ts
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
  front/src/modules/ui/table/types/ViewField.ts
  front/src/modules/views/components/OptionsDropdownButton.tsx
  front/src/modules/views/components/OptionsDropdownSection.tsx
Labels: run-chromatic, awaiting review

#1072 [tasks] add empty state and new task button
  front/src/generated/graphql.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/components/TaskGroups.tsx
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawerForSelectedRowIds.ts
  front/src/modules/activities/hooks/useTasks.ts
  front/src/modules/activities/queries/create.ts
  front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
  front/src/modules/activities/timeline/components/Timeline.tsx
Labels: front, run-chromatic, awaiting review

#1082 Add viewFields delete in Workspace delete resolver
  server/src/core/workspace/services/workspace.service.ts
Labels: awaiting review

#1075 [Refactor] Activity morph: first phase
  front/src/generated/graphql.tsx
  front/src/modules/activities/components/ActivityRelationPicker.tsx
  front/src/modules/activities/components/TaskRow.tsx
  front/src/modules/activities/editable-fields/components/ActivityRelationEditableField.tsx
  front/src/modules/activities/editable-fields/components/ActivityRelationEditableFieldEditMode.tsx
  front/src/modules/activities/hooks/useHandleCheckableActivityTargetChange.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawerForSelectedRowIds.ts
  front/src/modules/activities/queries/create.ts
  front/src/modules/activities/queries/select.ts
  front/src/modules/activities/queries/update.ts
Labels: run-chromatic

#1064 Drag To Select Table
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/components/EntityTableBody.tsx
  front/src/modules/ui/table/components/EntityTableRow.tsx
  front/src/modules/ui/table/hooks/useSetRowSelectedState.ts
  front/src/utils/DragSelect.tsx
Labels: wip

#1066 Add support chat
  front/src/generated/graphql.tsx
  front/src/modules/client-config/components/ClientConfigProvider.tsx
  front/src/modules/client-config/queries/index.tsx
  front/src/modules/client-config/states/supportChatState.ts
  front/src/modules/types/custom.d.ts
  front/src/modules/ui/navbar/components/MainNavbar.tsx
  front/src/modules/ui/navbar/components/SupportChat.tsx
  front/src/modules/users/queries/index.ts
  front/src/testing/graphqlMocks.ts
  server/.env.example
  server/src/core/client-config/client-config.entity.ts
  server/src/core/client-config/client-config.resolver.ts
  server/src/core/user/dto/user-with-HMAC.ts
  server/src/core/user/user.module.ts
  server/src/core/user/user.resolver.spec.ts
  server/src/core/user/user.resolver.ts
  server/src/integrations/environment/environment.service.ts
Labels: awaiting review

#1010 style(urls): Updated link style to round chips
  front/src/modules/ui/chip/components/Chip.tsx
  front/src/modules/ui/editable-field/components/FieldDisplayURL.tsx
  front/src/modules/ui/input/url/components/URLTextInputDisplay.tsx
  front/src/modules/ui/link/components/RawLink.tsx
  front/src/modules/ui/link/components/RoundedLink.tsx
  front/src/modules/ui/link/components/__stories__/RoundedLink.stories.tsx
Labels: awaiting author

#1091 [Opportunities] fix overlapping borders
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/board/components/StyledBoard.tsx
Labels: awaiting review

#1090 [Tasks] Removing task list empty state
  front/src/modules/activities/components/TaskGroups.tsx
  front/src/modules/activities/components/TaskList.tsx
  front/src/modules/activities/components/__stories__/TaskGroups.stories.tsx
  front/src/modules/activities/components/__stories__/TaskGroupsWithoutTasks.stories.tsx
  front/src/modules/activities/components/__stories__/TaskList.stories.tsx
  front/src/testing/decorators/ComponentWithRecoilScopeDecorator.tsx
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/activities.ts
Labels: run-chromatic

#1074 Confirmation before deleting a member
  front/src/modules/settings/profile/components/DeleteAccount.tsx
  front/src/modules/settings/profile/components/DeleteWorkspace.tsx
  front/src/modules/ui/modal/components/ConfirmationModal.tsx
  front/src/modules/ui/modal/components/__stories__/ConfirmModal.stories.tsx
  front/src/pages/settings/SettingsWorkspaceMembers.tsx
Labels: awaiting author

#1054 Prevent indexing on docs outside of production
  docs/docusaurus.config.js
  infra/prod/docs/Dockerfile
Labels: awaiting author

#1088 fix: [#1079] adding max width to menu items and also the tooltip to show full text value
  front/src/modules/ui/filter-n-sort/components/SortDropdownButton.tsx
  front/src/pages/companies/__stories__/Companies.sortBy.stories.tsx
  front/src/pages/people/__stories__/People.sortBy.stories.tsx
Labels: run-chromatic

#1100 Add company creation from people table
  front/src/modules/companies/components/CompanyPickerCell.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableRelationCellEditMode.tsx
Labels: run-chromatic, awaiting author

#1140 Add optimistic rendering for tasks
  front/src/modules/activities/components/ActivityAssigneePicker.tsx
  front/src/modules/activities/components/ActivityBodyEditor.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/hooks/useCompleteTask.ts
  front/src/modules/activities/queries/update.ts
Labels: run-chromatic

#1102 chore: Improve design of comment bar in notes
  front/src/modules/activities/components/ActivityComments.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/right-drawer/components/RightDrawerActivity.tsx
  front/src/modules/ui/input/autosize-text/components/AutosizeTextInput.tsx
  front/src/modules/ui/input/autosize-text/components/__stories__/AutosizeTextInput.stories.tsx
Labels: awaiting review

#1104 chore: New standard fields on People
  front/package.json
  front/src/generated/graphql.tsx
  front/src/modules/people/constants/peopleViewFields.tsx
  front/src/modules/people/queries/select.ts
  front/src/modules/people/queries/show.ts
  front/src/modules/people/queries/update.ts
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/input/url/components/URLTextInputDisplay.tsx
  front/src/modules/ui/link/components/SocialLink.tsx
  front/src/modules/ui/table/editable-cell/components/EditableCell.tsx
  front/src/testing/mock-data/people.ts
  front/yarn.lock
  server/src/database/migrations/20230803175814_add_twitter_url/migration.sql
  server/src/database/migrations/20230808152343_rename_twitter_url_to_x_url/migration.sql
  server/src/database/schema.prisma
Labels: awaiting review

#1119 feat: Add team section on company show
  front/src/modules/companies/components/CompanyTeam.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/pages/companies/CompanyShow.tsx
Labels: awaiting author

#1115 Add task and note create option in comand menu
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/constants/commandMenuCommands.ts
  front/src/modules/command-menu/hooks/useCommandMenu.ts
  front/src/modules/command-menu/states/commandMenuCommandsState.ts
  front/src/modules/command-menu/types/Command.ts
  front/src/sync-hooks/AppInternalHooks.tsx
  front/src/sync-hooks/AuthAutoRouter.tsx
  front/src/sync-hooks/CommandMenuHook.tsx
Labels: run-chromatic

#1136 feat: Add the workspace logo on Twenty logo on the invited route
  front/src/generated/graphql.tsx
  front/src/modules/auth/components/Logo.tsx
  front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  front/src/modules/workspace/queries/select.ts
  front/src/sync-hooks/AuthAutoRouter.tsx
  server/src/core/auth/auth.resolver.spec.ts
  server/src/core/auth/auth.resolver.ts
Labels: awaiting review

#1145 Use dedicated EditableFieldEntityIdContext for editable fields instead of CardIds
  front/src/generated/graphql.tsx
  front/src/modules/companies/components/CompanyBoardCard.tsx
  front/src/modules/ui/editable-field/components/GenericEditableDateField.tsx
  front/src/modules/ui/editable-field/components/GenericEditableDateFieldEditMode.tsx
  front/src/modules/ui/editable-field/components/GenericEditableNumberField.tsx
  front/src/modules/ui/editable-field/components/GenericEditableNumberFieldEditMode.tsx
  front/src/modules/ui/editable-field/components/GenericEditableRelationField.tsx
  front/src/modules/ui/editable-field/components/GenericEditableRelationFieldEditMode.tsx
  front/src/modules/ui/editable-field/components/ProbabilityEditableFieldEditMode.tsx
  front/src/modules/ui/editable-field/hooks/useCurrentEntityId.ts
  front/src/modules/ui/editable-field/states/EditableFieldContext.ts
  front/src/modules/ui/editable-field/states/EditableFieldEntityIdContext.ts
  front/src/modules/ui/editable-field/states/EntityIdContext.ts
Labels: awaiting review

#1148 [opportunities] fix poc being removed after pipeline update
  front/src/generated/graphql.tsx
  front/src/modules/pipeline/queries/update.ts
  front/src/modules/ui/editable-field/components/GenericEditableDateFieldEditMode.tsx
Labels: front, run-chromatic, awaiting review

#1130 fix(882): fixes negative number submission for employees input
  front/src/modules/companies/constants/companyViewFields.tsx
  front/src/modules/ui/editable-field/types/ViewField.ts
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx
  front/src/utils/__tests__/cast-as-positive-integer-or-null.test.ts
  front/src/utils/cast-as-positive-integer-or-null.ts
Labels: awaiting author

#1131 feat: add views and viewSorts tables
  front/src/generated/graphql.tsx
  server/src/ability/ability.factory.ts
  server/src/core/view/resolvers/view-field.resolver.ts
  server/src/core/workspace/services/workspace.service.ts
  server/src/database/migrations/20230809143432_add_views_table/migration.sql
  server/src/database/migrations/20230809143836_add_view_sorts_table/migration.sql
  server/src/database/schema.prisma
  server/src/utils/prisma-select/model-select-map.ts
Labels: awaiting review

#1153 Add task to action bar
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawerForSelectedRowIds.ts
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/companies/table/components/TableActionBarButtonCreateActivityCompany.tsx
  front/src/modules/people/table/components/TableActionBarButtonCreateActivityPeople.tsx
  front/src/modules/ui/table/action-bar/components/TableActionBarButtonOpenTasks.tsx
  front/src/sync-hooks/AuthAutoRouter.tsx
Labels: run-chromatic

#1094 feat: Favorites
  front/src/AppNavbar.tsx
  front/src/generated/graphql.tsx
  front/src/modules/companies/queries/show.ts
  front/src/modules/favorites/components/Favorites.tsx
  front/src/modules/favorites/hooks/useFavorites.ts
  front/src/modules/favorites/queries/show.ts
  front/src/modules/favorites/queries/update.ts
  front/src/modules/people/queries/show.ts
  front/src/modules/ui/button/components/IconButton.tsx
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/layout/components/WithTopBarContainer.tsx
  front/src/modules/ui/layout/page-bar/components/PageBar.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
  server/src/ability/ability.factory.ts
  server/src/ability/ability.module.ts
  server/src/ability/handlers/favorite.ability-handler.ts
  server/src/core/core.module.ts
  server/src/core/favorite/favorite.module.ts
  server/src/core/favorite/resolvers/favorite.resolver.ts
  server/src/core/favorite/services/favorite.service.ts
  server/src/database/schema.prisma
  server/src/utils/prisma-select/model-select-map.ts
Labels: awaiting author

#1168 Integrate favorites into release
  front/src/AppNavbar.tsx
  front/src/modules/favorites/components/Favorites.tsx
  front/src/modules/ui/button/components/IconButton.tsx
  front/src/modules/ui/layout/components/WithTopBarContainer.tsx
  front/src/modules/ui/layout/page-bar/components/PageBar.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
  server/src/database/migrations/20230810222531_add_favorites/migration.sql
Labels: run-chromatic

#1178 [PersonShow] use fieldDefinition for editable fields
  front/src/modules/companies/components/CompanyPicker.tsx
  front/src/modules/people/components/PeopleCompanyPicker.tsx
  front/src/modules/people/components/PersonPropertyBox.tsx
  front/src/modules/people/components/__stories__/PeopleCompanyEditableField.stories.tsx
  front/src/modules/people/editable-field/components/PeopleCompanyEditableField.tsx
  front/src/modules/people/editable-field/components/PeopleCompanyEditableFieldEditMode.tsx
  front/src/modules/people/queries/show.ts
  front/src/modules/ui/editable-field/components/GenericEditableField.tsx
  front/src/modules/ui/editable-field/components/GenericEditablePhoneField.tsx
  front/src/modules/ui/editable-field/components/GenericEditablePhoneFieldEditMode.tsx
  front/src/modules/ui/editable-field/components/GenericEditableRelationFieldDisplayMode.tsx
  front/src/modules/ui/editable-field/components/GenericEditableRelationFieldEditMode.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/companies/constants/companyShowFieldDefinition.tsx
  front/src/pages/people/PersonShow.tsx
  front/src/pages/people/constants/personShowFieldDefinition.tsx
Labels: awaiting review

#1179 Remove activityType and Id
  front/src/generated/graphql.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/components/ActivityRelationPicker.tsx
  front/src/modules/activities/components/ActivityTargetChips.tsx
  front/src/modules/activities/components/TaskRow.tsx
  front/src/modules/activities/components/__stories__/ActivityRelationPicker.stories.tsx
  front/src/modules/activities/editable-fields/components/ActivityRelationEditableField.tsx
  front/src/modules/activities/editable-fields/components/ActivityRelationEditableFieldEditMode.tsx
  front/src/modules/activities/hooks/useHandleCheckableActivityTargetChange.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawerForSelectedRowIds.ts
  front/src/modules/activities/hooks/useOpenTimelineRightDrawer.ts
  front/src/modules/activities/queries/create.ts
  front/src/modules/activities/queries/select.ts
  front/src/modules/activities/queries/update.ts
  front/src/modules/activities/right-drawer/components/RightDrawerTimeline.tsx
  front/src/modules/activities/states/activityTargetableEntityArrayState.ts
  front/src/modules/activities/states/commentableEntityArrayState.ts
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/activities/types/ActivityTargetableEntity.ts
  front/src/modules/activities/types/ActivityTargetableEntityForSelect.ts
  front/src/modules/activities/types/CommentableEntity.ts
  front/src/modules/activities/types/CommentableEntityForSelect.ts
  front/src/modules/companies/queries/select.ts
  front/src/modules/companies/table/components/TableActionBarButtonCreateActivityCompany.tsx
  front/src/modules/people/queries/select.ts
  front/src/modules/people/table/components/TableActionBarButtonCreateActivityPeople.tsx
  front/src/modules/ui/input/relation-picker/types/EntityTypeForSelect.ts
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
  front/src/sync-hooks/AuthAutoRouter.tsx
  front/src/testing/mock-data/activities.ts
  server/src/core/company/company-relations.resolver.ts
  server/src/core/person/person-relations.resolver.ts
  server/src/database/migrations/20230811232332_remove_activity_commentable_type_and_commentable_id/migration.sql
  server/src/database/schema.prisma
  server/src/database/seeds/comments.ts
Labels: run-chromatic

#1180 Remove unused components
  front/src/generated/graphql.tsx
  front/src/modules/companies/queries/update.ts
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/companies/table/components/CompanyTableMockMode.tsx
  front/src/modules/people/table/components/PeopleTable.tsx
  front/src/modules/search/queries/search.ts
  front/src/modules/ui/board/card-field/components/BoardCardEditableField.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldDate.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldDateEditMode.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldDisplayMode.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldEditMode.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldInternal.tsx
  front/src/modules/ui/board/card-field/components/BoardCardEditableFieldText.tsx
  front/src/modules/ui/board/card-field/hooks/useBoardCardField.ts
  front/src/modules/ui/board/card-field/states/BoardCardFieldContext.ts
  front/src/modules/ui/board/card-field/states/isBoardCardFieldInEditModeScopedState.ts
  front/src/modules/ui/board/card-field/types/BoardCardFieldHotkeyScope.ts
  front/src/modules/ui/board/components/__tests__/Board.test.ts
  front/src/modules/ui/editable-field/components/EditableFieldEntityText.tsx
  front/src/modules/ui/editable-field/property-box/components/PropertyBoxItem.tsx
  front/src/modules/ui/editable-field/variants/components/TextEditableField.tsx
  front/src/modules/ui/editable-field/variants/components/__stories__/TextEditableField.stories.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/components/GenericEntityTableData.tsx
  front/src/modules/ui/table/editable-cell/components/HoverableMenuItem.tsx
  front/src/modules/ui/table/hooks/useInitializeEntityTable.ts
  front/src/modules/ui/table/hooks/useInitializeEntityTableFilters.ts
  front/src/modules/ui/table/hooks/useSetTableRowIds.ts
  front/src/modules/ui/table/hooks/useUpdateEntityField.ts
  front/src/modules/ui/table/hooks/useUpsertEntityTableItem.ts
  front/src/modules/ui/table/hooks/useUpsertTableRowId.ts
  front/src/modules/ui/table/states/EntityUpdateMutationHookContext.ts
  front/src/pages/companies/Companies.tsx
  front/src/pages/people/People.tsx
Labels: run-chromatic

#1173 feat: I can hide/show filter bar and add filters directly from filter bar
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/filter-n-sort/components/DropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/FilterDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/MultipleFiltersDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/SortAndFilterBar.tsx
  front/src/modules/ui/filter-n-sort/components/SortDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/states/sortAndFilterBarScopedState.ts
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
Labels: awaiting review

#1206 On Company Show, in team section, I can delete a person
  front/src/modules/people/components/PeopleCard.tsx
Labels: awaiting author

#1227 Fix tests and upgrade node_modules
  front/craco.config.js
  front/src/modules/spreadsheet-import/components/__tests__/MatchColumnsStep.test.tsx
  front/src/modules/spreadsheet-import/components/__tests__/SelectHeaderStep.test.tsx
  front/src/modules/spreadsheet-import/components/__tests__/SelectSheetStep.test.tsx
  front/src/modules/spreadsheet-import/components/__tests__/UploadStep.test.tsx
  front/src/modules/spreadsheet-import/components/__tests__/ValidationStep.test.tsx
  front/src/modules/spreadsheet-import/components/steps/SelectHeaderStep/SelectHeaderStep.tsx
  front/src/modules/spreadsheet-import/tests/ReactSpreadsheetImport.test.tsx
  front/src/modules/ui/editor/components/BlockEditor.tsx
  front/src/modules/ui/filter-n-sort/components/SortAndFilterBar.tsx
  front/tsconfig.json
  front/yarn.lock
Labels: run-chromatic

#1201 On Company Show, I can select an existing person and add it to the company
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/activities/timeline/components/TimelineActivity.tsx
  front/src/modules/companies/components/AddPersonToCompany.tsx
  front/src/modules/companies/components/CompanyTeam.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/modules/people/components/PeoplePicker.tsx
  front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  front/src/modules/ui/layout/components/ShowPageContainer.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  front/src/modules/ui/utilities/hotkey/hooks/usePreviousHotkeyScope.ts
  front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts
Labels: awaiting review

#1212 Fix: Change title strings
  front/src/modules/activities/components/ActivityTitle.tsx
  front/src/modules/activities/components/TaskRow.tsx
  front/src/modules/activities/timeline/components/TimelineActivity.tsx
  front/src/modules/activities/timeline/components/TimelineActivityTitle.tsx
Labels: awaiting author

#1238 Fix issue #1037: Task inbox small design improvements
  front/src/modules/ui/tab/components/Tab.tsx
Labels: awaiting author

#1287 remove arrows for number inputs
  front/src/modules/ui/dropdown/components/DropdownMenuInput.tsx
Labels: run-chromatic

#1284 Fix: Avoid showing confirmation dialog on closing spreadsheet import with no changes
  front/src/modules/spreadsheet-import/components/ModalCloseButton.tsx
Labels: run-chromatic

#1285 Fix: Profile picture does not appear after signin
  front/src/generated/graphql.tsx
  front/src/modules/auth/graphql/fragments/userQueryFragment.ts
Labels: run-chromatic, awaiting author

#1250 Fix: create time
  front/src/modules/activities/timeline/components/TimelineActivity.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  front/src/utils/__tests__/date-utils.test.ts
  front/src/utils/date-utils.ts
Labels: run-chromatic

#1260 Fix issue #1161: Update visible fields on person detail page
  front/src/pages/people/constants/personShowFieldDefinition.tsx
Labels: run-chromatic

#1295 Fix confirmation modal size
  front/src/modules/ui/editable-field/components/EditableFieldDisplayMode.tsx
  front/src/modules/ui/modal/components/ConfirmationModal.tsx
Labels: run-chromatic

#1276 Chore: New standard fields on Companies
  front/src/generated/graphql.tsx
  front/src/modules/companies/constants/companyViewFields.tsx
  front/src/modules/companies/graphql/fragments/companyFieldsFragment.ts
  front/src/modules/companies/graphql/queries/getCompanies.ts
  front/src/modules/companies/graphql/queries/getCompany.ts
  front/src/modules/companies/table/components/companies-mock-data.ts
  front/src/modules/ui/editable-field/types/FieldMetadata.ts
  front/src/modules/ui/editable-field/types/ViewField.ts
  front/src/modules/ui/editable-field/types/guards/isViewFieldBoolean.ts
  front/src/modules/ui/editable-field/types/guards/isViewFieldBooleanValue.ts
  front/src/modules/ui/editable-field/types/guards/isViewFieldMoney.ts
  front/src/modules/ui/editable-field/types/guards/isViewFieldMoneyValue.ts
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/table/editable-cell/components/GenericEditableCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableBooleanCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableMoneyCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableMoneyCellEditMode.tsx
  front/src/modules/ui/table/hooks/useUpdateEntityField.ts
  front/src/testing/mock-data/companies.ts
  server/src/database/migrations/20230817201132_add_new_company_fields/migration.sql
  server/src/database/schema.prisma
Labels: awaiting review

#1269 Feat: The scrollbar should fade away when the scroll is finished or not started
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/layout/components/DefaultLayout.tsx
  front/src/modules/ui/layout/components/PagePanel.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/utilities/scroll/components/StyledScrollWrapper.tsx
  front/src/modules/ui/utilities/scroll/hooks/useListenScroll.ts
  front/src/modules/ui/utilities/scroll/states/isScrollingState.ts
  front/src/pages/companies/Companies.tsx
Labels: awaiting author

#1304 Scroll behavior part 2
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/activities/timeline/components/TimelineItemsContainer.tsx
  front/src/modules/companies/components/CompanyTeam.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/layout/components/ShowPageContainer.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  front/src/modules/ui/right-drawer/components/RightDrawer.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  front/src/modules/ui/utilities/scroll/components/StyledScrollWrapper.tsx
Labels: run-chromatic

#1252 padding fix for header logo container #1216
  front/src/modules/ui/layout/page-bar/components/PageBar.tsx
  front/src/modules/ui/navbar/components/MainNavbar.tsx
  front/src/modules/ui/navbar/components/NavCollapseButton.tsx
  front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx
Labels: awaiting author

#1305 Add hotkeys to modals
  front/src/modules/ui/modal/components/ConfirmationModal.tsx
  front/src/modules/ui/modal/components/Modal.tsx
  front/src/modules/ui/modal/components/types/ModalHotkeyScope.ts
Labels: run-chromatic

#1309 Remove danger text from completed passed tasks
  front/src/modules/activities/components/TaskRow.tsx
Labels: run-chromatic

#1316 Rework tel input
  front/package.json
  front/src/modules/companies/__stories__/CompanyChip.stories.tsx
  front/src/modules/people/components/__stories__/PeopleChip.stories.tsx
  front/src/modules/ui/editable-field/variants/components/__stories__/PhoneEditableField.stories.tsx
  front/src/modules/ui/input/email/components/__stories__/EmailInputDisplay.stories.tsx
  front/src/modules/ui/input/phone/components/__stories__/PhoneInputDisplay.stories.tsx
  front/src/modules/ui/table/editable-cell/type/components/PhoneCellEdit.tsx
  front/src/modules/ui/table/editable-cell/type/components/__stories__/PhoneCellEdit.stories.tsx
  front/src/pages/people/__stories__/People.inputs.stories.tsx
  front/yarn.lock
Labels: run-chromatic

#1256 Feat: On Company Show, I can create a person and add it to the company
  front/src/modules/companies/components/AddPersonToCompany.tsx
  front/src/modules/people/components/PeoplePicker.tsx
Labels: awaiting review

#1310 Fix confirmation modal style
  front/src/modules/ui/modal/components/ConfirmationModal.tsx
Labels: run-chromatic

#1185 Unset companies and owners
  front/src/modules/companies/components/CompanyPickerCell.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/ui/table/hooks/useUpdateEntityField.ts
  front/src/modules/users/components/UserPicker.tsx
  server/src/ability/ability.util.ts
Labels: awaiting review

#1282 Show Entity task/note tabs
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/notes/components/NoteCard.tsx
  front/src/modules/activities/notes/components/NoteList.tsx
  front/src/modules/activities/notes/components/Notes.tsx
  front/src/modules/activities/notes/hooks/useNotes.ts
  front/src/modules/activities/tasks/__stories__/TaskGroups.stories.tsx
  front/src/modules/activities/tasks/__stories__/TaskGroupsWithoutTasks.stories.tsx
  front/src/modules/activities/tasks/__stories__/TaskList.stories.tsx
  front/src/modules/activities/tasks/components/AddTaskButton.tsx
  front/src/modules/activities/tasks/components/EntityTasks.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/activities/tasks/components/TaskList.tsx
  front/src/modules/activities/tasks/components/TaskRow.tsx
  front/src/modules/activities/tasks/hooks/useCompleteTask.ts
  front/src/modules/activities/tasks/hooks/useInitializeTasksFilters.ts
  front/src/modules/activities/tasks/hooks/useTasks.ts
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/activities/timeline/components/TimelineActivity.tsx
  front/src/modules/activities/types/NoteForList.ts
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
  front/src/modules/ui/layout/components/WithTopBarContainer.tsx
  front/src/modules/ui/layout/page-bar/components/PageBar.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  front/src/modules/ui/layout/states/ShowPageRecoilScopeContext.ts
  front/src/modules/ui/tab/components/Tab.tsx
  front/src/modules/ui/tab/components/TabList.tsx
  front/src/modules/ui/tab/components/__stories__/Tab.stories.tsx
  front/src/modules/ui/tab/components/__stories__/Tablist.stories.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/companies/__stories__/Company.stories.tsx
  front/src/pages/people/PersonShow.tsx
  front/src/pages/tasks/Tasks.tsx
  front/src/testing/graphqlMocks.ts
Labels: wip

#1257 Refactor buttons
  front/src/modules/activities/components/ActivityCreateButton.tsx
  front/src/modules/activities/notes/components/Notes.tsx
  front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
  front/src/modules/activities/tasks/components/AddTaskButton.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/companies/components/AddPersonToCompany.tsx
  front/src/modules/companies/table/components/CompanyTableMockData.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/modules/pipeline/components/PipelineAddButton.tsx
  front/src/modules/settings/profile/components/DeleteAccount.tsx
  front/src/modules/settings/profile/components/DeleteWorkspace.tsx
  front/src/modules/spreadsheet-import/components/ModalCloseButton.tsx
  front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  front/src/modules/ui/button/components/Button.tsx
  front/src/modules/ui/button/components/ButtonGroup.tsx
  front/src/modules/ui/button/components/DropdownButton_Deprecated.tsx
  front/src/modules/ui/button/components/FloatingButton.tsx
  front/src/modules/ui/button/components/FloatingButtonGroup.tsx
  front/src/modules/ui/button/components/FloatingIconButton.tsx
  front/src/modules/ui/button/components/FloatingIconButtonGroup.tsx
  front/src/modules/ui/button/components/IconButton.tsx
  front/src/modules/ui/button/components/IconButtonGroup.tsx
  front/src/modules/ui/button/components/LightButton.tsx
  front/src/modules/ui/button/components/LightIconButton.tsx
  front/src/modules/ui/button/components/__stories__/Button.stories.tsx
  front/src/modules/ui/button/components/__stories__/ButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingIconButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingIconButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/IconButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/IconButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/LightButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/LightIconButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/RoundedIconButton.stories.tsx
  front/src/modules/ui/dialog/components/Dialog.tsx
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuItem.tsx
  front/src/modules/ui/editable-field/components/EditableFieldEditButton.tsx
  front/src/modules/ui/input/image/components/ImageInput.tsx
  front/src/modules/ui/layout/page-bar/components/PageBar.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  front/src/modules/ui/modal/components/ConfirmationModal.tsx
  front/src/modules/ui/navbar/components/SupportChat.tsx
  front/src/modules/ui/pill/components/SoonPill.tsx
  front/src/modules/ui/right-drawer/components/RightDrawerTopBarCloseButton.tsx
  front/src/modules/ui/right-drawer/components/RightDrawerTopBarExpandButton.tsx
  front/src/modules/ui/table/components/EntityTableColumnMenu.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/editable-cell/components/EditableCell.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/table/options/components/TableUpdateViewButtonGroup.tsx
  front/src/modules/ui/theme/constants/accent.ts
  front/src/modules/ui/theme/constants/colors.ts
  front/src/modules/workspace/components/WorkspaceInviteLink.tsx
  front/src/pages/settings/SettingsWorkspaceMembers.tsx
Labels: run-chromatic

#1325 Fix tasks page
  front/src/modules/activities/tasks/hooks/useTasks.ts
Labels: run-chromatic

#1357 refactor: add ColumnDefinition type
  front/src/modules/companies/components/CompanyBoardCard.tsx
  front/src/modules/companies/components/HooksCompanyBoard.tsx
  front/src/modules/companies/constants/companiesAvailableColumnDefinitions.tsx
  front/src/modules/companies/constants/companyViewFields.tsx
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/companies/table/components/CompanyTableMockData.tsx
  front/src/modules/people/constants/peopleAvailableColumnDefinitions.tsx
  front/src/modules/people/constants/peopleViewFields.tsx
  front/src/modules/people/table/components/PeopleTable.tsx
  front/src/modules/pipeline/constants/pipelineAvailableFieldDefinitions.tsx
  front/src/modules/pipeline/constants/pipelineViewFields.tsx
  front/src/modules/ui/editable-field/types/ViewField.ts
  front/src/modules/ui/table/components/EntityTableCell.tsx
  front/src/modules/ui/table/components/EntityTableColumnMenu.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableRow.tsx
  front/src/modules/ui/table/contexts/ColumnContext.ts
  front/src/modules/ui/table/contexts/ViewFieldContext.ts
  front/src/modules/ui/table/editable-cell/components/GenericEditableCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableBooleanCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableChipCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableChipCellDisplayMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableChipCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDateCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDateCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextChipCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextChipCellDisplayMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextChipCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableEmailCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableEmailCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableMoneyCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableMoneyCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditablePhoneCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditablePhoneCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableRelationCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableRelationCellDisplayMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableRelationCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableTextCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableTextCellEditMode.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableURLCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableURLCellEditMode.tsx
  front/src/modules/ui/table/hooks/useUpdateEntityField.ts
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownSection.tsx
  front/src/modules/ui/table/states/savedTableColumnsScopedState.ts
  front/src/modules/ui/table/states/selectors/savedTableColumnsByIdScopedSelector.ts
  front/src/modules/ui/table/states/selectors/tableColumnsByIdScopedSelector.ts
  front/src/modules/ui/table/states/tableColumnsScopedState.ts
  front/src/modules/ui/table/types/ColumnDefinition.ts
  front/src/modules/views/hooks/useTableViewFields.ts
  front/src/modules/views/hooks/useTableViews.ts
  front/src/testing/mock-data/companies.ts
  front/src/testing/mock-data/people.ts
Labels: run-chromatic

#1321 feat: add page titles using React Helmet
  front/package.json
  front/src/App.tsx
  front/src/__stories__/App.stories.tsx
  front/src/index.tsx
  front/src/modules/ui/utilities/page-title/PageTitle.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
  front/src/testing/decorators/PageDecorator.tsx
  front/src/utils/title-utils.ts
  front/yarn.lock
Labels: run-chromatic

#1366 fix: do not allow removal of last table view
  front/src/modules/ui/table/options/components/TableViewsDropdownButton.tsx
  server/src/core/view/resolvers/view.resolver.ts
Labels: run-chromatic

#1303 chore(docs): Update the best practices page
  docs/docs/developer/frontend/best-practices.mdx
  docs/docs/developer/frontend/style-guide.mdx
Labels: awaiting review

#1370 chore: Make a twenty Eslint Rule to make sure that icons are imported from @/ui/icons
  front/.eslintrc.js
  front/src/modules/activities/notes/components/Notes.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/companies/components/AddPersonToCompany.tsx
  front/src/modules/companies/hooks/useCompanyTableContextMenuEntries.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/modules/people/hooks/usePeopleTableContextMenuEntries.tsx
  front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/hooks/useBoardContextMenuEntries.tsx
  front/src/modules/ui/button/components/Button.tsx
  front/src/modules/ui/button/components/FloatingButton.tsx
  front/src/modules/ui/button/components/FloatingIconButton.tsx
  front/src/modules/ui/button/components/IconButton.tsx
  front/src/modules/ui/button/components/LightButton.tsx
  front/src/modules/ui/button/components/LightIconButton.tsx
  front/src/modules/ui/editable-field/variants/components/__stories__/DateEditableField.stories.tsx
  front/src/modules/ui/editable-field/variants/components/__stories__/PhoneEditableField.stories.tsx
  front/src/modules/ui/filter-n-sort/components/FilterDropdownOperandButton.tsx
  front/src/modules/ui/filter-n-sort/components/SingleEntityFilterDropdownButton.tsx
  front/src/modules/ui/filter-n-sort/components/SortDropdownButton.tsx
  front/src/modules/ui/icon/components/IconAddressBook.tsx
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/right-drawer/components/RightDrawerTopBarExpandButton.tsx
  front/src/modules/ui/tab/components/__stories__/Tab.stories.tsx
  front/src/modules/ui/tab/components/__stories__/Tablist.stories.tsx
  front/src/modules/ui/table/editable-cell/components/EditableCell.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableBooleanCell.tsx
  front/src/pages/tasks/tasks-filters.tsx
  front/src/sync-hooks/PageChangeEffect.tsx
Labels: awaiting review

#1373 Remove unused logic on board column menu tags
  front/src/modules/ui/tag/components/Tag.tsx
  front/src/modules/ui/tag/components/__stories__/Tag.stories.tsx
Labels: run-chromatic

#1381 Fix view edit button
  front/src/modules/ui/table/options/components/TableViewsDropdownButton.tsx
Labels: run-chromatic
