Repository twentyhq/twenty, pull requests merged in 2023-11, with the labels that each got.

#2312 Fix sort delete
  front/src/modules/views/hooks/internal/useViewSorts.ts
Labels: PR: awaiting review

#2333 Fix seeds for local workspace and newly created workspaces
  server/package.json
  server/src/core/pipeline/seed-data/pipeline-stages.json
  server/src/database/typeorm-seeds/metadata/field-metadata.ts
  server/src/database/typeorm-seeds/metadata/object-metadata.ts
  server/src/database/typeorm-seeds/tenant/companies.ts
  server/src/database/typeorm-seeds/tenant/view-fields.ts
  server/src/database/typeorm-seeds/tenant/views.ts
  server/src/metadata/commands/data-seed-tenant.command.ts
  server/src/metadata/commands/metadata-command.module.ts
  server/src/metadata/commands/sync-tenant-metadata.command.ts
  server/src/metadata/data-source/data-source.service.ts
  server/src/metadata/metadata.datasource.ts
  server/src/metadata/object-metadata/services/object-metadata.service.ts
  server/src/metadata/standard-objects/companies/companies.metadata.ts
  server/src/metadata/standard-objects/standard-object-metadata.ts
  server/src/metadata/standard-objects/view-fields/view-fields.metadata.ts
  server/src/metadata/standard-objects/view-filters/view-filters.metadata.ts
  server/src/metadata/standard-objects/view-sorts/view-sorts.metadata.ts
  server/src/metadata/standard-objects/views/views.metadata.ts
  server/src/metadata/tenant-initialisation/standard-objects-prefill-data/standard-objects-prefill-data.ts
  server/src/metadata/tenant-initialisation/standard-objects/companies/companies.metadata.json
  server/src/metadata/tenant-initialisation/standard-objects/companies/companies.seeds.json
  server/src/metadata/tenant-initialisation/standard-objects/standard-object-metadata.ts
  server/src/metadata/tenant-initialisation/standard-objects/standard-object-seeds.ts
  server/src/metadata/tenant-initialisation/standard-objects/view-fields/view-fields.metadata.json
  server/src/metadata/tenant-initialisation/standard-objects/view-fields/view-fields.seeds.json
  server/src/metadata/tenant-initialisation/standard-objects/view-filters/view-filters.metadata.json
  server/src/metadata/tenant-initialisation/standard-objects/view-sorts/view-sorts.metadata.json
  server/src/metadata/tenant-initialisation/standard-objects/views/views.metadata.json
  server/src/metadata/tenant-initialisation/standard-objects/views/views.seeds.json
  server/src/metadata/tenant-initialisation/tenant-initialisation.module.ts
  server/src/metadata/tenant-initialisation/tenant-initialisation.service.ts
  server/src/tenant/entity-resolver/utils/convert-fields-to-graphql.util.ts
Labels: PR: awaiting review

#2308 Improved user guide, added CI vale for docs
  .github/SECURITY.md
  .github/styles/docs/Acronyms.yml
  .github/styles/docs/ComplexWords.yml
  .github/styles/docs/Contractions.yml
  .github/styles/docs/FirstPerson.yml
  .github/styles/docs/Foreign.yml
  .github/styles/docs/Gender.yml
  .github/styles/docs/HeadingColons.yml
  .github/styles/docs/HeadingPunctuation.yml
  .github/styles/docs/Npm2Yarn.yml
  .github/styles/docs/NpmCommands.yml
  .github/styles/docs/NpmGlobal.yml
  .github/styles/docs/Numbers.yml
  .github/styles/docs/Ordinal.yml
  .github/styles/docs/Our.yml
  .github/styles/docs/OxfordComma.yml
  .github/styles/docs/Passive.yml
  .github/styles/docs/Percentages.yml
  .github/styles/docs/SentenceLength.yml
  .github/styles/docs/Spacing.yml
  .github/styles/docs/Terms.yml
  .github/styles/docs/TypeScript.yml
  .github/styles/docs/We.yml
  .github/styles/docs/Wordiness.yml
  .github/styles/docs/WritingLevel.yml
  .github/styles/write-good/Cliches.yml
  .github/styles/write-good/E-Prime.yml
  .github/styles/write-good/Illusions.yml
  .github/styles/write-good/Passive.yml
  .github/styles/write-good/README.md
  .github/styles/write-good/So.yml
  .github/styles/write-good/ThereIs.yml
  .github/styles/write-good/TooWordy.yml
  .github/styles/write-good/Weasel.yml
  .github/styles/write-good/meta.json
  .github/workflows/ci-vale.yaml
  .vale.ini
  docs/docs/contributor/frontend/advanced/style-guide.mdx
  docs/docs/contributor/local-setup/troubleshooting.mdx
  docs/docs/developer/graphql_api.mdx
  docs/docs/others/bug-and-requests.mdx
  docs/docs/user-guide/basics/_category_.json
  docs/docs/user-guide/basics/custom objects.mdx
  docs/docs/user-guide/integrations/_category_.json
  docs/docs/user-guide/integrations/connect-zapier.mdx
  docs/docs/user-guide/integrations/generating-api-keys.mdx
  docs/docs/user-guide/others/_category_.json
  docs/docs/user-guide/others/glossary.mdx
  docs/docs/user-guide/user-guide.mdx
  docs/src/theme/DocCard/index.js
  docs/src/theme/DocCard/styles.module.css
  infra/dev/scripts/setup-postgres-macos.sh
Labels: PR: awaiting review

#2298 Feat/improve new views
  front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/metadata/components/RecordTable.tsx
  front/src/modules/people/table/components/PersonTable.tsx
  front/src/modules/ui/layout/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/object/field/states/selectors/isEntityFieldEmptyFamilySelector.ts
  front/src/modules/ui/object/record-table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/utilities/recoil-scope/types/RecoilScopedSelector.ts
  front/src/modules/ui/utilities/recoil-scope/types/RecoilScopedState.ts
  front/src/modules/ui/utilities/recoil-scope/utils/createScopedSelector.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getScopedFamilyState.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getScopedSelector.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getScopedState.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getSnapshotScopedSelector.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getSnapshotScopedValue.ts
  front/src/modules/ui/utilities/recoil-scope/utils/getSnapshotValue.ts
  front/src/modules/views/components/UpdateViewButtonGroup.tsx
  front/src/modules/views/components/ViewBar.tsx
  front/src/modules/views/components/ViewBarDetails.tsx
  front/src/modules/views/components/ViewBarEffect.tsx
  front/src/modules/views/components/ViewsDropdownButton.tsx
  front/src/modules/views/constants/index.ts
  front/src/modules/views/hooks/internal/useViewFields.ts
  front/src/modules/views/hooks/internal/useViewFilters.ts
  front/src/modules/views/hooks/internal/useViewScopedStates.ts
  front/src/modules/views/hooks/internal/useViewSorts.ts
  front/src/modules/views/hooks/internal/useViews.ts
  front/src/modules/views/hooks/useView.ts
  front/src/modules/views/hooks/useViewGetStates.ts
  front/src/modules/views/hooks/useViewSetStates.ts
  front/src/modules/views/scopes/init-effect/ViewScopeInitEffect.tsx
  front/src/modules/views/states/selectors/currentViewScopedSelector.ts
  front/src/modules/views/states/selectors/savedViewFieldByKeyScopedFamilySelector.ts
  front/src/modules/views/utils/getViewScopedStateValuesFromSnapshot.ts
  front/src/modules/views/utils/getViewScopedStatesFromSnapshot.ts
  front/src/modules/views/utils/internal/getViewScopedStates.ts
  front/src/modules/views/utils/mapColumnDefinitionToViewField.ts
  front/src/modules/views/utils/mapViewFieldsToBoardFieldDefinitions.ts
  front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  front/src/modules/views/utils/mapViewFiltersToFilters.ts
  front/src/modules/views/utils/mapViewSortsToSorts.ts
  front/src/pages/people/__stories__/People.sortBy.stories.tsx
Labels: PR: awaiting review

#2302 2299 fix(frontend): corrected tag spacing in settings object item table row
  front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  front/src/modules/ui/display/tag/components/Tag.tsx
Labels: PR: awaiting author

#2342 0.2.0 cleaning script
  server/scripts/setup-db.ts
  server/scripts/truncate-db.ts
  server/scripts/utils.ts
  server/src/command.module.ts
  server/src/core/user/user.service.ts
  server/src/core/workspace/resolvers/workspace.resolver.ts
  server/src/core/workspace/services/workspace.service.ts
  server/src/database/commands/clean-inactive-workspaces.command.ts
  server/src/database/commands/confirmation.question.ts
  server/src/database/commands/database-command.module.ts
  server/src/utils/equal.ts
Labels: PR: awaiting review

#2227 Chore: Cancel previous runs
  .github/workflows/ci-chromatic.yaml
  .github/workflows/ci-docs.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
Labels: PR: awaiting review

#2251 No console eslint
  .github/workflows/ci-front.yaml
  front/.eslintrc-ci.js
Labels: PR: awaiting author

#2353 changes as per vale warnings
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/styles/docs/Acronyms.yml
  .github/styles/docs/TypeScript.yml
  .github/styles/write-good/TooWordy.yml
  .github/styles/write-good/Weasel.yml
  docs/docs/contributor/frontend/advanced/best-practices.mdx
  docs/docs/contributor/frontend/advanced/hotkeys.mdx
  docs/docs/contributor/frontend/advanced/style-guide.mdx
  docs/docs/contributor/frontend/basics/basics.mdx
  docs/docs/contributor/frontend/basics/design-system.mdx
  docs/docs/contributor/frontend/basics/folder-architecture.mdx
  docs/docs/contributor/frontend/basics/work-with-figma.mdx
  docs/docs/contributor/frontend/frontend.mdx
  docs/docs/contributor/local-setup/docker-setup.mdx
  docs/docs/contributor/local-setup/ide-setup.mdx
  docs/docs/contributor/local-setup/local-setup.mdx
  docs/docs/contributor/local-setup/troubleshooting.mdx
  docs/docs/contributor/local-setup/yarn-setup.mdx
  docs/docs/contributor/server/basics/custom-objects.mdx
  docs/docs/contributor/server/basics/folder-architecture.mdx
  docs/docs/contributor/server/basics/overview.mdx
  docs/docs/contributor/server/others/best-practices.mdx
  docs/docs/contributor/server/others/zapier.mdx
  docs/docs/contributor/server/server.mdx
  docs/docs/developer/graphql_api.mdx
  docs/docs/index.mdx
  docs/docs/others/telemetry.mdx
  docs/docs/start/getting-started.mdx
  docs/docs/start/self-hosting.mdx
  docs/docs/user-guide/basics/custom objects.mdx
  docs/docs/user-guide/integrations/connect-zapier.mdx
  docs/docs/user-guide/integrations/generating-api-keys.mdx
  docs/docs/user-guide/others/glossary.mdx
  docs/docs/user-guide/user-guide.mdx
Labels: PR: awaiting review

#2241 chore: create a new TypeORM config using @nestjs/typeorm for public schema
  server/ormconfig.ts
  server/src/app.module.ts
  server/src/coreV2/core.module.ts
  server/src/coreV2/userv2/user.dto.ts
  server/src/coreV2/userv2/user.entity.ts
  server/src/coreV2/userv2/user.module.ts
  server/src/coreV2/userv2/user.resolver.ts
  server/src/coreV2/userv2/user.service.ts
Labels: scope: backend, PR: awaiting review

#2403 0.2.0 cleaning script
  server/src/database/commands/clean-inactive-workspaces.command.ts
  server/src/metadata/data-source/data-source.service.ts
  server/src/metadata/field-metadata/services/field-metadata.service.ts
  server/src/metadata/metadata.datasource.ts
  server/src/metadata/object-metadata/services/object-metadata.service.ts
  server/src/metadata/tenant-initialisation/tenant-initialisation.module.ts
  server/src/metadata/tenant-initialisation/tenant-initialisation.service.ts
Labels: PR: awaiting author

#2404 Remove Tenant columns anonymisation
  server/src/metadata/field-metadata/services/field-metadata.service.ts
  server/src/metadata/field-metadata/utils/field-metadata.util.spec.ts
  server/src/metadata/field-metadata/utils/field-metadata.util.ts
  server/src/metadata/object-metadata/hooks/before-create-one-object.hook.ts
Labels: PR: awaiting author

#2336 2294 feat(frontend): styling shortcut keys
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/components/CommandMenuItem.tsx
  front/src/modules/command-menu/constants/commandMenuCommands.ts
  front/src/modules/command-menu/types/Command.ts
  front/src/modules/ui/navigation/menu-item/components/MenuItemCommand.tsx
  front/src/modules/ui/navigation/menu-item/components/MenuItemCommandHotKeys.tsx
  front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  front/src/modules/ui/theme/constants/boxShadow.ts
Labels: PR: awaiting author

#2411 2385-feat(front): icon button styles added
  front/src/modules/ui/object/record-table/components/RecordTableHeader.tsx
Labels: PR: awaiting author

#2205 #2133 Add comments icon and count to Timeline card
  front/src/modules/activities/comment/CommentCounter.tsx
  front/src/modules/activities/timeline/components/TimelineActivityCardFooter.tsx
Labels: PR: awaiting author

#2417 Fix table last column not being displayed
  front/src/modules/ui/object/record-table/components/RecordTable.tsx
Labels: run-chromatic, PR: awaiting review

#2415 2363 refactor the dialog component to use the new scope architecture
  front/src/index.tsx
  front/src/modules/spreadsheet-import/components/ModalCloseButton.tsx
  front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/MatchColumns.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/SelectHeader.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/SelectSheet.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/Upload.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/Validation.stories.tsx
  front/src/modules/ui/feedback/dialog-manager/components/Dialog.tsx
  front/src/modules/ui/feedback/dialog-manager/components/DialogManager.tsx
  front/src/modules/ui/feedback/dialog-manager/components/DialogManagerEffect.tsx
  front/src/modules/ui/feedback/dialog-manager/hooks/internal/useDialogManagerScopedStates.ts
  front/src/modules/ui/feedback/dialog-manager/hooks/useDialogManager.ts
  front/src/modules/ui/feedback/dialog-manager/scopes/DialogManagerScope.tsx
  front/src/modules/ui/feedback/dialog-manager/scopes/scope-internal-context/DialogManagerScopeInternalContext.ts
  front/src/modules/ui/feedback/dialog-manager/states/dialogInternalScopedState.ts
  front/src/modules/ui/feedback/dialog-manager/types/DialogHotkeyScope.ts
  front/src/modules/ui/feedback/dialog-manager/types/DialogOptions.ts
  front/src/modules/ui/feedback/dialog/components/DialogProvider.tsx
  front/src/modules/ui/feedback/dialog/hooks/useDialog.ts
  front/src/modules/ui/feedback/dialog/states/dialogState.ts
Labels: run-chromatic, PR: awaiting review

#2387 Feat/pagination front
  front/package.json
  front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  front/src/modules/apollo/optimistic-effect/types/OptimisticEffectDefinition.ts
  front/src/modules/apollo/optimistic-effect/types/OptimisticEffectResolver.ts
  front/src/modules/apollo/optimistic-effect/types/internal/OptimisticEffect.ts
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/metadata/components/RecordTableContainer.tsx
  front/src/modules/metadata/components/RecordTableEffect.tsx
  front/src/modules/metadata/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  front/src/modules/metadata/hooks/useCreateOneObject.ts
  front/src/modules/metadata/hooks/useFindManyObjects.ts
  front/src/modules/metadata/hooks/useSetRecordTableData.ts
  front/src/modules/metadata/hooks/useTableObjects.ts
  front/src/modules/metadata/hooks/useUpdateOneObject.ts
  front/src/modules/metadata/states/cursorFamilyState.ts
  front/src/modules/metadata/states/fetchMoreObjectsFamilyState.ts
  front/src/modules/metadata/states/hasNextPageFamilyState.ts
  front/src/modules/metadata/states/isFetchingMoreObjectsFamilyState.ts
  front/src/modules/metadata/types/PaginatedObjectTypeResults.ts
  front/src/modules/metadata/utils/generateCreateOneObjectMutation.ts
  front/src/modules/metadata/utils/generateFindManyCustomObjectsQuery.ts
  front/src/modules/metadata/utils/generateUpdateOneObjectMutation.ts
  front/src/modules/people/table/components/PersonTable.tsx
  front/src/modules/ui/object/record-table/components/RecordTableBody.tsx
  front/src/modules/ui/object/record-table/components/RecordTableBodyV1.tsx
  front/src/modules/ui/object/record-table/components/RecordTableEffect.tsx
  front/src/modules/ui/object/record-table/components/RecordTableRow.tsx
  front/src/modules/ui/object/record-table/components/RecordTableV1.tsx
  front/yarn.lock
Labels: PR: awaiting review

#2429 fix-svgr-issue-with-tsup
  front/package.json
  front/src/modules/ui/display/icon/assets/address-book.svg
  front/tsup.config.js
  front/tsup.ui.index.tsx
  front/yarn.lock
Labels: PR: awaiting review

#2482 2454 update filter definition to work with new backend
  front/src/generated/graphql.tsx
  front/src/modules/object-metadata/hooks/useFindOneObjectMetadataItem.ts
  front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFilterDefinition.ts
  front/src/modules/object-metadata/utils/formatFieldMetadataItemAsSortDefinition.ts
  front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsSortDefinitions.ts
  front/src/modules/object-record/components/RecordTableEffect.tsx
  front/src/modules/ui/object/object-filter-dropdown/utils/turnFiltersIntoWhereClauseV2.ts
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#2440 Add env variable docs
  .github/workflows/ci-utils.yaml
  docs/docs/others/telemetry.mdx
  docs/docs/start/self-hosting/_category_.json
  docs/docs/start/self-hosting/enviroment-variables.mdx
  docs/docs/start/self-hosting/self-hosting.mdx
  docs/src/theme/OptionTable/index.js
  docs/src/theme/OptionTable/style.module.css
  docs/src/theme/icons.js
  packages/twenty-utils/dangerfile.ts
Labels: blocked: conflict/dependency

#2442 feat: Unfocus cells when mouse leaves the table
  front/src/modules/ui/object/record-table/components/RecordTableV1.tsx
Labels: PR: awaiting review

#2493 docs: mention prebuilt images
  docs/docs/start/self-hosting/self-hosting.mdx
Labels: PR: awaiting author

#2488 Hide System Objects
  front/src/generated-metadata/gql.ts
  front/src/generated-metadata/graphql.ts
  front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  front/src/modules/object-metadata/graphql/queries.ts
  front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
  front/src/modules/object-metadata/hooks/useObjectMetadataItemForSettings.ts
  server/src/database/typeorm-seeds/metadata/object-metadata.ts
  server/src/database/typeorm/metadata/migrations/1699890270187-setupMetadataTables.ts
  server/src/metadata/object-metadata/dtos/object-metadata.dto.ts
Labels: PR: awaiting author

#2490 2320-fix(front): IconEye icon size and font fix
  front/src/modules/companies/components/CompanyBoardCard.tsx
Labels: PR: awaiting author

#2509 Migrate v2 core models to graphql schema
  front/src/generated-metadata/graphql.ts
  front/src/generated/graphql.tsx
  front/src/index.tsx
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/tasks/hooks/useCurrentUserDueTaskCount.ts
  front/src/modules/auth/graphql/fragments/userQueryFragment.ts
  front/src/modules/auth/hooks/useAuth.ts
  front/src/modules/auth/hooks/useOnboardingStatus.ts
  front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  front/src/modules/auth/states/currentUserState.ts
  front/src/modules/auth/states/currentWorkspaceMemberState.ts
  front/src/modules/auth/states/currentWorkspaceState.ts
  front/src/modules/auth/utils/getOnboardingStatus.ts
  front/src/modules/object-record/graphql/queries/findOneWorkspaceMember.ts
  front/src/modules/settings/profile/components/NameFields.tsx
  front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
  front/src/modules/settings/profile/components/ToggleField.tsx
  front/src/modules/settings/workspace/components/NameField.tsx
  front/src/modules/settings/workspace/components/WorkspaceLogoUploader.tsx
  front/src/modules/ui/navigation/navbar/components/NavWorkspaceButton.tsx
  front/src/modules/ui/navigation/navbar/components/SupportChat.tsx
  front/src/modules/ui/theme/hooks/useColorScheme.ts
  front/src/modules/users/components/UserProvider.tsx
  front/src/modules/users/components/WorkspaceMemberProvider.tsx
  front/src/modules/users/graphql/mutations/updateUser.ts
  front/src/modules/users/graphql/queries/getCurrentUser.ts
  front/src/modules/workspace-member/types/WorkspaceMember.ts
  front/src/modules/workspace/components/WorkspaceMemberCard.tsx
  front/src/modules/workspace/graphql/fragments/workspaceMemberFieldsFragment.ts
  front/src/modules/workspace/graphql/mutations/removeWorkspaceMember.ts
  front/src/modules/workspace/graphql/mutations/updateWorkspaceMember.ts
  front/src/modules/workspace/graphql/queries/getCurrentWorkspace.ts
  front/src/modules/workspace/graphql/queries/getWorkspaceMembers.ts
  front/src/pages/auth/CreateProfile.tsx
  front/src/pages/auth/VerifyEffect.tsx
  front/src/pages/impersonate/ImpersonateEffect.tsx
  front/src/pages/settings/SettingsWorkspaceMembers.tsx
  front/src/pages/tasks/TasksEffect.tsx
  server/src/ability/ability.factory.ts
  server/src/app.module.ts
  server/src/core/auth/auth.resolver.ts
  server/src/core/auth/services/auth.service.ts
  server/src/core/auth/services/token.service.ts
  server/src/core/core.module.ts
  server/src/coreV2/core.module.ts
  server/src/coreV2/refresh-token/refresh-token.auto-resolver-opts.ts
  server/src/coreV2/refresh-token/refresh-token.entity.ts
  server/src/coreV2/refresh-token/refresh-token.module.ts
  server/src/coreV2/user/services/user.service.ts
  server/src/coreV2/user/user.auto-resolver-opts.ts
  server/src/coreV2/user/user.entity.ts
  server/src/coreV2/user/user.module.ts
  server/src/coreV2/user/user.resolver.ts
  server/src/database/migrations/20231115084929_remove_user_workspace_member_relation/migration.sql
  server/src/database/schema.prisma
  server/src/database/seeds/users.ts
  server/src/database/typeorm-seeds/metadata/field-metadata/workspace-member.ts
  server/src/database/typeorm-seeds/tenant/workspaceMember.ts
  server/src/metadata/tenant-migration/migrations/1697618026-addWorspaceMemberTable.ts
Labels: PR: awaiting review

#2520 Update favorites query and state to work with new backend
  front/src/modules/auth/hooks/useAuth.ts
  front/src/modules/companies/hooks/useCompanyTableContextMenuEntries.tsx
  front/src/modules/favorites/components/Favorites.tsx
  front/src/modules/favorites/hooks/useFavorites.ts
  front/src/modules/favorites/states/favoritesState.ts
  front/src/modules/favorites/types/Favorite.ts
  front/src/modules/favorites/utils/mapFavorites.ts
  front/src/modules/object-record/components/RecordShowPage.tsx
  front/src/modules/people/hooks/usePersonTableContextMenuEntries.tsx
  front/src/modules/ui/object/field/components/FieldDisplay.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
  server/src/database/typeorm-seeds/metadata/field-metadata/favorite.ts
  server/src/database/typeorm-seeds/metadata/field-metadata/person.ts
Labels: PR: awaiting review

#2532 2472 v2 settings workspace module
  front/src/modules/object-metadata/hooks/useMapFieldMetadataToGraphQLQuery.ts
  front/src/modules/object-record/graphql/queries/findOneWorkspaceMember.ts
  front/src/modules/object-record/hooks/useUpdateOneObjectRecord.ts
  front/src/modules/settings/profile/components/NameFields.tsx
  front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
  front/src/modules/settings/profile/components/ToggleField.tsx
  front/src/modules/ui/object/field/meta-types/display/components/RelationFieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/display/utils/getEntityChipFromFieldMetadata.ts
  front/src/modules/ui/object/field/meta-types/hooks/useRelationField.ts
Labels: PR: awaiting review

#2543 V2 onboarding
  front/src/modules/auth/hooks/useOnboardingStatus.ts
  front/src/modules/auth/states/currentWorkspaceMemberState.ts
  front/src/modules/auth/utils/getOnboardingStatus.ts
  front/src/modules/search/hooks/useFilteredSearchEntityQueryV2.ts
  front/src/modules/settings/profile/components/NameFields.tsx
  front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
  front/src/modules/settings/profile/components/ToggleField.tsx
  front/src/modules/settings/workspace/components/WorkspaceLogoUploader.tsx
  front/src/modules/ui/input/color-scheme/components/ColorSchemePicker.tsx
  front/src/modules/ui/navigation/navbar/components/NavWorkspaceButton.tsx
  front/src/modules/ui/navigation/navbar/components/SupportChat.tsx
  front/src/modules/ui/object/record-table/components/RecordTable.tsx
  front/src/modules/ui/theme/hooks/useColorScheme.ts
  front/src/modules/users/components/UserPicker.tsx
  front/src/modules/workspace-member/types/WorkspaceMember.ts
  front/src/pages/auth/CreateProfile.tsx
  front/src/pages/auth/CreateWorkspace.tsx
  server/src/tenant-manager/standard-objects/workspace-member.ts
Labels: PR: awaiting review

#2567 Add missing default values
  server/src/database/typeorm-seeds/metadata/field-metadata/view-filter.ts
  server/src/database/typeorm-seeds/metadata/field-metadata/view-sort.ts
  server/src/database/typeorm-seeds/metadata/field-metadata/view.ts
  server/src/database/typeorm-seeds/metadata/field-metadata/workspace-member.ts
  server/src/database/typeorm-seeds/workspace/workspaceMember.ts
  server/src/metadata/workspace-migration/migrations/1697618009-addCompanyTable.ts
  server/src/metadata/workspace-migration/migrations/1697618011-addViewTable.ts
  server/src/metadata/workspace-migration/migrations/1697618012-addViewFieldTable.ts
  server/src/metadata/workspace-migration/migrations/1697618013-addViewFilterTable.ts
  server/src/metadata/workspace-migration/migrations/1697618014-addViewSortTable.ts
  server/src/metadata/workspace-migration/migrations/1697618018-addAttachmentTable.ts
  server/src/metadata/workspace-migration/migrations/1697618019-addCommentTable.ts
  server/src/metadata/workspace-migration/migrations/1697618020-addFavoriteTable.ts
  server/src/metadata/workspace-migration/migrations/1697618022-addPersonTable.ts
  server/src/metadata/workspace-migration/migrations/1697618023-addPipelineStepTable.ts
  server/src/metadata/workspace-migration/migrations/1697618024-addWebhookTable.ts
  server/src/metadata/workspace-migration/migrations/1697618026-addWorspaceMemberTable.ts
  server/src/workspace/workspace-manager/standard-objects/attachment.ts
  server/src/workspace/workspace-manager/standard-objects/comment.ts
  server/src/workspace/workspace-manager/standard-objects/company.ts
  server/src/workspace/workspace-manager/standard-objects/favorite.ts
  server/src/workspace/workspace-manager/standard-objects/pipeline-step.ts
  server/src/workspace/workspace-manager/standard-objects/standard-object-metadata.ts
  server/src/workspace/workspace-manager/standard-objects/view-field.ts
  server/src/workspace/workspace-manager/standard-objects/view-filter.ts
  server/src/workspace/workspace-manager/standard-objects/view-sort.ts
  server/src/workspace/workspace-manager/standard-objects/view.ts
  server/src/workspace/workspace-manager/standard-objects/webhook.ts
  server/src/workspace/workspace-manager/standard-objects/workspace-member.ts
Labels: PR: awaiting review

#2568 Add Name defaultColumn for custom objects
  server/src/metadata/object-metadata/object-metadata.service.ts
Labels: PR: awaiting review

#2569 Add deleteOneRelation resolver
  server/src/metadata/relation-metadata/relation-metadata.module.ts
  server/src/metadata/relation-metadata/relation-metadata.service.ts
Labels: PR: awaiting review

#2530 chore(server): Migrate workspace
  server/src/core/core.module.ts
  server/src/coreV2/workspace/dtos/update-workspace-input.ts
  server/src/coreV2/workspace/services/workspace.service.spec.ts
  server/src/coreV2/workspace/services/workspace.service.ts
  server/src/coreV2/workspace/workspace.auto-resolver-opts.ts
  server/src/coreV2/workspace/workspace.entity.ts
  server/src/coreV2/workspace/workspace.module.ts
  server/src/coreV2/workspace/workspace.resolver.ts
Labels: PR: awaiting review

#2487 feat: add EnumFieldDisplay and Enum field preview
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  front/src/modules/settings/data-model/constants/dataTypes.ts
  front/src/modules/settings/data-model/types/ObjectFieldDataType.ts
  front/src/modules/ui/display/tag/components/Tag.tsx
  front/src/modules/ui/display/tag/components/__stories__/Tag.stories.tsx
  front/src/modules/ui/object/field/components/FieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/display/components/EnumFieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/display/components/__stories__/EnumFieldDisplay.stories.tsx
  front/src/modules/ui/object/field/meta-types/hooks/useEnumField.ts
  front/src/modules/ui/object/field/types/FieldMetadata.ts
  front/src/modules/ui/object/field/types/FieldType.ts
  front/src/modules/ui/object/field/types/guards/assertFieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/isFieldEnum.ts
  front/src/modules/ui/object/field/types/guards/isFieldEnumValue.ts
Labels: PR: awaiting author

#2572 feat: add Relation field form
  front/src/generated-metadata/graphql.ts
  front/src/generated/graphql.tsx
  front/src/modules/object-metadata/hooks/useObjectMetadataItemForSettings.ts
  front/src/modules/object-metadata/utils/parseFieldRelationType.ts
  front/src/modules/settings/data-model/assets/OneToMany.svg
  front/src/modules/settings/data-model/assets/OneToOne.svg
  front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldPreviewValueEffect.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeCard.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeCard.stories.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  front/src/modules/settings/data-model/constants/dataTypes.ts
  front/src/modules/settings/data-model/constants/relationTypes.ts
  front/src/modules/settings/data-model/hooks/useFieldMetadataForm.ts
  front/src/modules/settings/data-model/hooks/useFieldPreview.ts
  front/src/modules/settings/data-model/hooks/useRelationFieldPreview.ts
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  front/src/modules/ui/display/chip/components/Chip.tsx
  front/src/modules/ui/display/chip/components/EntityChip.tsx
  front/src/modules/ui/display/icon/index.ts
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/input/components/Select.tsx
  front/src/modules/ui/layout/page/PagePanel.tsx
  front/src/modules/ui/object/field/meta-types/display/utils/getEntityChipFromFieldMetadata.ts
  front/src/modules/ui/object/field/types/FieldDefinition.ts
  front/src/modules/ui/object/field/types/guards/isFieldDateValue.ts
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  front/src/testing/mock-data/metadata.ts
  server/src/coreV2/workspace/workspace.entity.ts
Labels: PR: wip

#2611 Fix avatar placeholder not displayed
  front/src/modules/ui/object/field/meta-types/hooks/useRelationField.ts
  front/src/modules/users/components/Avatar.tsx
Labels: PR: wip

#2604 feat: disable Standard field edition in Relation field form
  front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
Labels: PR: awaiting review

#2507 2311 embed keyboard shortcuts
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenuDialog.tsx
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenuGroup.tsx
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenuItem.tsx
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenuStyles.tsx
  front/src/modules/keyboard-shortcut-menu/constants/keyboardShortcuts.ts
  front/src/modules/keyboard-shortcut-menu/hooks/useKeyboardShortcutMenu.ts
  front/src/modules/keyboard-shortcut-menu/states/isKeyboardShortcutMenuOpenedState.ts
  front/src/modules/keyboard-shortcut-menu/types/Shortcut.ts
  front/src/modules/ui/layout/page/DefaultLayout.tsx
  front/src/modules/ui/utilities/hotkey/constants/index.ts
  front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts
  front/src/modules/ui/utilities/hotkey/types/AppHotkeyScope.ts
  front/src/modules/ui/utilities/hotkey/types/CustomHotkeyScope.ts
  front/src/testing/InitializeHotkeyStorybookHook.tsx
Labels: PR: awaiting author

#2578 chore(front): Refactor the SnackBar component to use the new scope architecture
  front/src/effect-components/PageChangeEffect.tsx
  front/src/index.tsx
  front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  front/src/modules/companies/components/NewCompanyProgressButton.tsx
  front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
  front/src/modules/object-metadata/hooks/useFindManyRelationMetadataItems.ts
  front/src/modules/object-record/hooks/useFindManyObjectRecords.ts
  front/src/modules/pipeline/components/PipelineAddButton.tsx
  front/src/modules/settings/developers/components/ApiKeyInput.tsx
  front/src/modules/settings/profile/components/ToggleField.tsx
  front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  front/src/modules/spreadsheet-import/steps/components/UploadFlow.tsx
  front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  front/src/modules/ui/feedback/snack-bar-manager/components/SnackBar.tsx
  front/src/modules/ui/feedback/snack-bar-manager/components/SnackBarProvider.tsx
  front/src/modules/ui/feedback/snack-bar-manager/hooks/internal/useSnackBarManagerScopedStates.ts
  front/src/modules/ui/feedback/snack-bar-manager/hooks/usePausableTimeout.ts
  front/src/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar.tsx
  front/src/modules/ui/feedback/snack-bar-manager/scopes/SnackBarProviderScope.tsx
  front/src/modules/ui/feedback/snack-bar-manager/scopes/scope-internal-context/SnackBarManagerScopeInternalContext.ts
  front/src/modules/ui/feedback/snack-bar-manager/states/snackBarInternalScopedState.ts
  front/src/modules/ui/feedback/snack-bar/hooks/useSnackBar.ts
  front/src/modules/ui/feedback/snack-bar/states/snackBarState.ts
  front/src/modules/ui/layout/board/components/BoardColumnMenu.tsx
  front/src/modules/workspace/components/WorkspaceInviteLink.tsx
  front/src/pages/auth/CreateProfile.tsx
  front/src/pages/auth/CreateWorkspace.tsx
Labels: PR: awaiting review

#2648 Fix workspace/user deletion
  server/src/core/auth/services/auth.service.ts
  server/src/core/refresh-token/refresh-token.entity.ts
  server/src/core/user/services/user.service.ts
  server/src/core/user/user.entity.ts
  server/src/core/user/user.resolver.ts
  server/src/core/workspace/services/workspace.service.ts
  server/src/database/typeorm/core/migrations/1700661180856-addCascadeDeleteOnRefreshTokenUser.ts
  server/src/database/typeorm/core/migrations/1700663611659-addWorkspaceDeleteCascadeSetNullInUser.ts
  server/src/database/typeorm/metadata/migrations/1700661538754-addCascadeDeleteOnRelationObject.ts
  server/src/metadata/object-metadata/object-metadata.entity.ts
  server/src/metadata/relation-metadata/relation-metadata.entity.ts
  server/src/workspace/workspace-manager/workspace-manager.service.ts
Labels: PR: awaiting review

#2651 Allow isActive to be updated for standard objects
  server/src/metadata/field-metadata/hooks/before-update-one-field.hook.ts
  server/src/metadata/object-metadata/hooks/before-update-one-object.hook.ts
Labels: PR: awaiting review

#2671 First generated viewField is now name
  server/src/metadata/object-metadata/object-metadata.service.ts
Labels: PR: awaiting review

#2666 fix-currency-field-input
  front/src/modules/ui/object/field/meta-types/display/content-display/components/CurrencyDisplay.tsx
  front/src/modules/ui/object/field/meta-types/hooks/useCurrencyField.ts
  front/src/modules/ui/object/field/meta-types/input/components/CurrencyFieldInput.tsx
Labels: PR: awaiting review

#2687 Fix company update with accountOwner
  server/src/workspace/workspace-manager/standard-objects-prefill-data/view.ts
  server/src/workspace/workspace-manager/standard-objects/company.ts
  server/src/workspace/workspace-manager/standard-objects/person.ts
Labels: PR: awaiting review

#2686 Fix activity creation
  server/src/workspace/workspace-manager/standard-objects/activity.ts
  server/src/workspace/workspace-manager/standard-objects/attachment.ts
Labels: PR: awaiting review

#2685 Add viewField creation to fieldMetadata creation service
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  server/src/metadata/field-metadata/field-metadata.module.ts
  server/src/metadata/field-metadata/field-metadata.service.ts
  server/src/metadata/object-metadata/object-metadata.service.ts
Labels: PR: awaiting review

#2689 Fix check identical nameSingular/namePlural
  server/src/metadata/object-metadata/object-metadata.service.ts
Labels: PR: awaiting review

#2691 fix: empty string as default value for string types
  server/src/metadata/field-metadata/utils/convert-field-metadata-to-column-action.util.ts
  server/src/metadata/workspace-migration/migrations/1697618009-addCompanyTable.ts
  server/src/metadata/workspace-migration/migrations/1697618012-addViewFieldTable.ts
  server/src/metadata/workspace-migration/migrations/1697618016-addActivityTable.ts
  server/src/metadata/workspace-migration/migrations/1697618017-addApiKeyTable.ts
  server/src/metadata/workspace-migration/migrations/1697618022-addPersonTable.ts
Labels: PR: awaiting author

#2706 Fix board animation
  front/src/modules/companies/components/CompanyBoardCard.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedEaseInOut.tsx
Labels: PR: awaiting review

#2608 Fix keyboard cmds table soft focus
  front/src/modules/ui/object/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
Labels: PR: awaiting review

#2736 2422 refactor scope components to improve dev experience
  front/src/modules/activities/tasks/components/PageAddTaskButton.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/activities/tasks/hooks/useTasks.ts
  front/src/modules/companies/board/components/CompanyBoard.tsx
  front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  front/src/modules/object-record/components/RecordTableContainer.tsx
  front/src/modules/object-record/components/RecordTableEffect.tsx
  front/src/modules/object-record/hooks/useRecordTableContextMenuEntries.tsx
  front/src/modules/object-record/hooks/useSetRecordTableData.ts
  front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/AddObjectFilterFromDetailsButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/MultipleFiltersButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/MultipleFiltersDropdownButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownDateSearchInput.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownEntitySearchInput.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownEntitySearchSelect.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownEntitySelect.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownNumberSearchInput.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownOperandButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownOperandSelect.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/ObjectFilterDropdownTextSearchInput.tsx
  front/src/modules/ui/object/object-filter-dropdown/components/SingleEntityObjectFilterDropdownButton.tsx
  front/src/modules/ui/object/object-filter-dropdown/hooks/useFilterDropdown.ts
  front/src/modules/ui/object/object-filter-dropdown/hooks/useFilterDropdownStates.ts
  front/src/modules/ui/object/object-filter-dropdown/scopes/ObjectFilterDropdownScope.tsx
  front/src/modules/ui/object/object-filter-dropdown/scopes/init-effect/ObjectFilterDropdownScopeInitEffect.tsx
  front/src/modules/ui/object/object-filter-dropdown/scopes/scope-internal-context/ObjectFilterDropdownScopeInternalContext.ts
  front/src/modules/ui/object/object-filter-dropdown/states/onFilterSelectScopedState.ts
  front/src/modules/ui/object/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  front/src/modules/ui/object/object-sort-dropdown/hooks/useSortDropdown.ts
  front/src/modules/ui/object/object-sort-dropdown/hooks/useSortDropdownStates.ts
  front/src/modules/ui/object/object-sort-dropdown/scopes/ObjectSortDropdownScope.tsx
  front/src/modules/ui/object/object-sort-dropdown/scopes/init-effect/ObjectSortDropdownScopeInitEffect.tsx
  front/src/modules/ui/object/object-sort-dropdown/states/onSortSelectScopedState.ts
  front/src/modules/ui/object/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
  front/src/modules/ui/object/record-board/options/components/BoardOptionsDropdown.tsx
  front/src/modules/ui/object/record-board/options/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/object/record-table/components/RecordTable.tsx
  front/src/modules/ui/object/record-table/hooks/useTableColumns.ts
  front/src/modules/ui/object/record-table/options/components/TableOptionsDropdown.tsx
  front/src/modules/ui/object/record-table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/object/record-table/states/savedTableColumnsFamilyState.ts
  front/src/modules/ui/object/record-table/states/selectors/savedTableColumnsByKeyFamilySelector.ts
  front/src/modules/views/components/UpdateViewButtonGroup.tsx
  front/src/modules/views/components/ViewBar.tsx
  front/src/modules/views/components/ViewBarDetails.tsx
  front/src/modules/views/components/ViewBarEffect.tsx
  front/src/modules/views/components/ViewBarFilterEffect.tsx
  front/src/modules/views/components/ViewBarSortEffect.tsx
  front/src/modules/views/components/ViewsDropdownButton.tsx
  front/src/modules/views/hooks/internal/useViewFilters.ts
  front/src/modules/views/hooks/internal/useViewScopedStates.ts
  front/src/modules/views/hooks/internal/useViewSorts.ts
  front/src/modules/views/hooks/useViewBar.ts
  front/src/pages/tasks/Tasks.tsx
  front/src/pages/tasks/TasksEffect.tsx
Labels: PR: awaiting review

#2555 Update workspace directory
  docs/docs/contributor/server/basics/folder-architecture.mdx
Labels: PR: awaiting review

#2724 2694-fix(front): Replace "Continue with Google" monochrome logo by colourful logo
  front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  front/src/modules/ui/display/icon/assets/google-icon.svg
  front/src/modules/ui/display/icon/components/IconGoogle.tsx
Labels: PR: awaiting author

#2528 2495 fix cmdk removal and added toggle functionality
  front/package.json
  front/src/AppNavbar.tsx
  front/src/effect-components/PageChangeEffect.tsx
  front/src/modules/command-menu/components/CommandGroup.tsx
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/components/CommandMenuItem.tsx
  front/src/modules/command-menu/components/CommandMenuSelectableListEffect.tsx
  front/src/modules/command-menu/components/CommandMenuStyles.tsx
  front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  front/src/modules/command-menu/constants/commandMenuCommands.ts
  front/src/modules/command-menu/states/commandMenuCommandsState.ts
  front/src/modules/command-menu/types/Command.ts
  front/src/modules/ui/layout/selectable-list/components/SelectableItem.tsx
  front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListHotKeys.tsx
  front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListScopedStates.ts
  front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
  front/src/modules/ui/layout/selectable-list/scopes/SelectableListScope.tsx
  front/src/modules/ui/layout/selectable-list/scopes/scope-internal-context/SelectableListScopeInternalContext.ts
  front/src/modules/ui/layout/selectable-list/states/isSelectedItemIdMapScopedFamilyState.ts
  front/src/modules/ui/layout/selectable-list/states/selectableItemIdsScopedState.ts
  front/src/modules/ui/layout/selectable-list/states/selectedItemIdScopedState.ts
  front/src/modules/ui/layout/selectable-list/states/selectors/isSelectedItemIdScopedFamilySelector.ts
  front/src/modules/ui/layout/selectable-list/utils/internal/getSelectableListScopedStates.ts
  front/src/modules/ui/navigation/menu-item/components/MenuItemCommand.tsx
  front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  front/yarn.lock
Labels: PR: awaiting author

#2688 Fix Frontend modules tests
  front/.storybook/preview.ts
  front/package.json
  front/public/mockServiceWorker.js
  front/src/modules/activities/tasks/__stories__/TaskGroups.stories.tsx
  front/src/modules/activities/tasks/__stories__/TaskList.stories.tsx
  front/src/modules/activities/tasks/components/TaskRow.tsx
  front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  front/src/modules/command-menu/hooks/useCommandMenu.ts
  front/src/modules/companies/__stories__/Board.stories.tsx
  front/src/modules/object-metadata/components/ObjectMetadataItemsProvider.tsx
  front/src/modules/object-metadata/components/ObjectMetadataItemsRelationPickerEffect.tsx
  front/src/modules/object-metadata/states/objectMetadataItemFamilySelector.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/MatchColumns.stories.tsx
  front/src/modules/spreadsheet-import/steps/components/__stories__/Upload.stories.tsx
  front/src/modules/ui/navigation/navbar/components/__stories__/MainNavbar.stories.tsx
  front/src/modules/ui/object/field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  front/src/modules/ui/object/field/meta-types/input/components/__stories__/PhoneFieldInput.stories.tsx
  front/src/modules/ui/object/field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  front/src/modules/ui/object/field/types/FieldType.ts
  front/src/testing/decorators/ObjectMetadataItemsDecorator.tsx
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/metadata.ts
  front/yarn.lock
Labels: PR: awaiting review

#2655 feat: add Select field preview and form
  front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/constants/settingsFieldMetadataTypes.ts
  front/src/modules/settings/data-model/hooks/useFieldMetadataForm.ts
  front/src/modules/settings/data-model/hooks/useFieldPreview.ts
  front/src/modules/settings/data-model/hooks/useFieldPreviewValue.ts
  front/src/modules/settings/data-model/hooks/useRelationFieldPreviewValue.ts
  front/src/modules/ui/object/field/components/FieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/display/components/SelectFieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/hooks/useSelectField.ts
  front/src/modules/ui/object/field/types/FieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/assertFieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/isFieldEnumValue.ts
  front/src/modules/ui/object/field/types/guards/isFieldSelect.ts
  front/src/modules/ui/object/field/types/guards/isFieldSelectValue.ts
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#2665 feat: add options to Select field
  front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeCard.tsx
Labels: PR: awaiting review

#2668 feat: remove Select field options
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectFormOptionRow.tsx
Labels: PR: awaiting review

#2725 feat: set Select field option as default option
  front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectFormOptionRow.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/hooks/useFieldMetadataForm.ts
  front/src/modules/settings/data-model/hooks/useFieldPreview.ts
  front/src/modules/settings/data-model/types/SettingsObjectFieldSelectFormOption.ts
  front/src/modules/ui/input/components/TextInput.tsx
  front/src/modules/ui/object/field/meta-types/display/components/SelectFieldDisplay.tsx
  front/src/modules/ui/object/field/meta-types/hooks/useSelectField.ts
  front/src/modules/ui/object/field/types/FieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/isFieldSelectValue.ts
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#2748 feat: pick select field option colors
  front/src/modules/companies/hooks/useUpdateCompanyBoardColumns.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldSelectFormOptionRow.tsx
  front/src/modules/settings/data-model/hooks/useFieldMetadataForm.ts
  front/src/modules/ui/display/color/components/ColorSample.tsx
  front/src/modules/ui/display/color/components/__stories__/ColorSample.stories.tsx
  front/src/modules/ui/navigation/menu-item/components/MenuItemSelectColor.tsx
  front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemSelectColor.stories.tsx
  front/src/modules/ui/object/field/types/guards/isFieldSelectValue.ts
  front/src/modules/ui/object/record-board/components/RecordBoardColumnEditTitleMenu.tsx
  front/src/modules/ui/object/record-board/components/__stories__/RecordBoardColumnEditTitleMenu.stories.tsx
  front/src/modules/ui/theme/constants/colors.ts
  front/src/modules/ui/theme/utils/castStringAsThemeColor.ts
  front/src/modules/ui/theme/utils/themeColorSchema.ts
Labels: PR: awaiting review

#2716 Attachments
  front/src/generated/graphql.tsx
  front/src/modules/activities/files/components/AttachmentDropdown.tsx
  front/src/modules/activities/files/components/AttachmentIcon.tsx
  front/src/modules/activities/files/components/AttachmentList.tsx
  front/src/modules/activities/files/components/AttachmentRow.tsx
  front/src/modules/activities/files/components/Attachments.tsx
  front/src/modules/activities/files/hooks/useAttachments.tsx
  front/src/modules/activities/files/types/Attachment.ts
  front/src/modules/activities/files/utils/downloadFile.ts
  front/src/modules/activities/files/utils/getFileType.ts
  front/src/modules/files/graphql/queries/uploadFile.ts
  front/src/modules/ui/display/icon/index.ts
  front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  server/src/database/typeorm-seeds/metadata/field-metadata/attachment.ts
  server/src/workspace/workspace-manager/standard-objects/attachment.ts
Labels: PR: awaiting review

#2660 2394-feat(front): create new record on click of plus icon
  front/src/modules/activities/files/components/AttachmentRow.tsx
  front/src/modules/activities/files/components/Attachments.tsx
  front/src/modules/activities/files/hooks/useAttachments.tsx
  front/src/modules/object-record/components/RecordTableContainer.tsx
  front/src/modules/object-record/components/RecordTablePage.tsx
  front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  front/src/modules/ui/object/record-table/components/RecordTable.tsx
  front/src/modules/ui/object/record-table/components/RecordTableHeader.tsx
  front/src/modules/ui/object/record-table/components/RecordTableHeaderCell.tsx
Labels: PR: awaiting author

#2771 Fix UI components
  docs/docs/contributor/frontend/ui-components/input/color-scheme.mdx
  docs/docs/contributor/frontend/ui-components/input/text-input.mdx
  docs/src/ui/generated/index.d.ts
  docs/src/ui/generated/index.js
  docs/src/ui/input/color-scheme/colorSchemeCardCode.js
  docs/src/ui/input/components/entityTitleDoubleTextInputCode.js
  front/src/modules/ui/input/color-scheme/components/ColorSchemeCard.tsx
  front/src/modules/ui/input/components/Radio.tsx
  front/src/modules/ui/utilities/dimensions/components/ComputeNodeDimensions.tsx
Labels: PR: awaiting author

#2758 feat: add missing updateMany and deleteMany resolvers on flexible backend
  server/src/workspace/utils/get-resolver-name.util.ts
  server/src/workspace/workspace-query-builder/factories/delete-many-query.factory.ts
  server/src/workspace/workspace-query-builder/factories/factories.ts
  server/src/workspace/workspace-query-builder/factories/update-many-query.factory.ts
  server/src/workspace/workspace-query-builder/workspace-query-builder.factory.ts
  server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  server/src/workspace/workspace-resolver-builder/factories/delete-many-resolver.factory.ts
  server/src/workspace/workspace-resolver-builder/factories/factories.ts
  server/src/workspace/workspace-resolver-builder/factories/update-many-resolver.factory.ts
  server/src/workspace/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  server/src/workspace/workspace-resolver-builder/workspace-resolver.factory.ts
  server/src/workspace/workspace-schema-builder/factories/root-type.factory.ts
  server/src/workspace/workspace-schema-builder/utils/get-resolver-args.util.ts
Labels: PR: awaiting review

#2776 Renaming "Experience" to "Appearance"
  .gitignore
  front/src/App.tsx
  front/src/modules/settings/components/SettingsNavbar.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/modules/ui/navigation/navbar/components/__stories__/SubMenuNavbar.stories.tsx
  front/src/pages/settings/SettingsAppearance.tsx
  front/src/pages/settings/__stories__/SettingsAppearance.stories.tsx
  front/src/utils/title-utils.ts
Labels: PR: awaiting author
