Repository twentyhq/twenty, pull requests merged in 2023-09, with the labels that each got.

#1390 fix: improve full name editable fields in Person Show page
  front/src/modules/people/editable-field/components/PeopleFullNameEditableField.tsx
  front/src/modules/ui/input/double-text/components/DoubleTextInputEdit.tsx
  front/src/modules/ui/utilities/dimensions/components/ComputeNodeDimensionsEffect.tsx
Labels: run-chromatic

#1386 fix: fix filter and sort position on board horizontal scroll
  front/src/modules/ui/board/components/EntityBoard.tsx
Labels: awaiting review

#1375 chore: Show my completed tasks without date categories
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/activities/tasks/components/TaskList.tsx
  front/src/modules/activities/tasks/hooks/useTasks.ts
Labels: awaiting author

#1393 unselect all cards using esc key or click
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/components/EntityBoardCard.tsx
  front/src/modules/ui/board/hooks/useCurrentCardSelected.ts
  front/src/modules/ui/board/hooks/useSetCardSelected.ts
  front/src/modules/ui/board/states/activeCardIdsState.ts
  front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
Labels: awaiting author

#1423 Fix URL validation on long/internationalized URLs
  front/src/utils/__tests__/is-url.test.ts
  front/src/utils/is-url.ts
Labels: awaiting author

#1399 feat: add board options dropdown and pipeline stage creation
  front/src/generated/graphql.tsx
  front/src/modules/pipeline/graphql/mutations/createPipelineStage.ts
  front/src/modules/pipeline/hooks/usePipelineStages.ts
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdown.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdownButton.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/types/BoardOptionsDropdownKey.ts
  front/src/modules/ui/board/types/BoardOptionsHotkeyScope.ts
  front/src/modules/ui/icon/index.ts
  front/src/pages/opportunities/Opportunities.tsx
  server/src/ability/ability.factory.ts
  server/src/core/pipeline/resolvers/pipeline-stage.resolver.ts
Labels: awaiting review

#1412 feat: delete pipeline stage
  front/src/generated/graphql.tsx
  front/src/modules/pipeline/graphql/mutations/deletePipelineStage.ts
  front/src/modules/pipeline/hooks/usePipelineStages.ts
  front/src/modules/ui/board/components/BoardColumn.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/components/EntityBoardColumn.tsx
  front/src/modules/ui/progress-bar/components/__stories__/CircularProgressBar.stories.tsx
  front/src/pages/opportunities/Opportunities.tsx
  server/src/ability/ability.factory.ts
  server/src/core/pipeline/resolvers/pipeline-stage.resolver.ts
Labels: run-chromatic, awaiting review

#1420 Unselect table rows using esc key or click outside
  front/src/modules/ui/action-bar/components/ActionBar.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/context-menu/components/ContextMenu.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
Labels: awaiting review

#1392 Refactor/modal component tests 1332
  front/src/modules/spreadsheet-import/components/ModalWrapper.tsx
  front/src/modules/ui/modal/components/Modal.tsx
  front/src/modules/ui/modal/components/__stories__/Modal.stories.tsx
  front/src/modules/ui/theme/constants/modal.ts
  front/src/modules/ui/theme/constants/theme.ts
Labels: wip, awaiting author

#1418 Add relation for Company on people show page note creation
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/types/ActivityTargetableEntity.ts
  front/src/modules/activities/utils/getRelationData.ts
  front/src/pages/people/PersonShow.tsx
Labels: awaiting author

#1506 Fix front plugin not initialize with user email, first name and last name
  front/src/modules/ui/navbar/components/SupportChat.tsx
Labels: run-chromatic

#1491 fix the tests
  front/src/pages/people/__stories__/People.filterBy.stories.tsx
  front/src/testing/graphqlMocks.ts
Labels: awaiting review

#1528 fix case HotkeyScope to hotkeyScope
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/view-bar/components/DropdownButton.tsx
  front/src/modules/ui/view-bar/components/FilterDropdownButton.tsx
  front/src/modules/ui/view-bar/components/MultipleFiltersDropdownButton.tsx
  front/src/modules/ui/view-bar/components/SingleEntityFilterDropdownButton.tsx
  front/src/modules/ui/view-bar/components/SortDropdownButton.tsx
  front/src/modules/ui/view-bar/components/UpdateViewButtonGroup.tsx
  front/src/modules/ui/view-bar/components/ViewBar.tsx
  front/src/modules/ui/view-bar/components/ViewBarDetails.tsx
  front/src/modules/ui/view-bar/components/ViewsDropdownButton.tsx
  front/src/pages/tasks/Tasks.tsx
Labels: run-chromatic

#1529 Rework tab and tab list padding and gaps to match designs
  front/src/modules/ui/tab/components/Tab.tsx
  front/src/modules/ui/tab/components/TabList.tsx
  front/src/modules/ui/tab/components/__stories__/Tab.stories.tsx
  front/src/modules/ui/top-bar/TopBar.tsx
  front/src/modules/ui/view-bar/components/ViewBarDetails.tsx
  front/src/pages/tasks/Tasks.tsx
Labels: run-chromatic

#1443 fix: POC assigning in opportunities
  front/src/modules/people/components/PeoplePicker.tsx
  front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  front/src/modules/ui/editable-field/components/GenericEditableRelationFieldEditMode.tsx
Labels: awaiting author

#1531 Complete useFilteredSearchQuery refactoring
  front/src/modules/activities/components/ActivityAssigneePicker.tsx
  front/src/modules/companies/hooks/useFilteredSearchCompanyQuery.ts
  front/src/modules/people/components/PeoplePicker.tsx
  front/src/modules/people/hooks/useFilteredSearchPeopleQuery.ts
  front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  front/src/modules/users/components/FilterDropdownUserSearchSelect.tsx
  front/src/modules/users/components/UserPicker.tsx
Labels: run-chromatic

#1493 Fixed bug for refectch activities and create activity on the currently filtered user.
  front/src/generated/graphql.tsx
  front/src/modules/activities/components/ActivityAssigneePicker.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawerForSelectedRowIds.ts
  front/src/modules/activities/notes/components/Notes.tsx
  front/src/modules/activities/tasks/components/AddTaskButton.tsx
  front/src/modules/activities/tasks/components/PageAddTaskButton.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/activities/timeline/components/Timeline.tsx
  front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  front/src/modules/apollo/optimistic-effect/states/optimisticEffectState.ts
  front/src/modules/apollo/optimistic-effect/types/OptimisticEffect.ts
  front/src/modules/apollo/optimistic-effect/types/OptimisticEffectDefinition.ts
  front/src/modules/apollo/optimistic-effect/types/OptimisticEffectResolver.ts
  front/src/modules/apollo/optimistic-effect/types/internal/OptimisticEffect.ts
  front/src/modules/companies/graphql/fragments/companyFieldsFragment.ts
  front/src/modules/companies/graphql/mutations/insertOneCompany.ts
  front/src/modules/companies/graphql/mutations/updateOneCompany.ts
  front/src/modules/companies/graphql/optimistic-effect-definitions/getCompaniesOptimisticEffectDefinition.ts
  front/src/modules/companies/graphql/optimistic-effects/getCompaniesOptimisticEffect.ts
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/people/graphql/fragments/insertOnePersonFragment.ts
  front/src/modules/people/graphql/fragments/personFieldsFragment.ts
  front/src/modules/people/graphql/mutations/insertOnePerson.ts
  front/src/modules/people/graphql/optimistic-effect-callback/getPeopleOptimisticEffect.ts
  front/src/modules/people/graphql/optimistic-effect-definitions/getPeopleOptimisticEffectDefinition.ts
  front/src/modules/people/table/components/PeopleTable.tsx
  front/src/modules/search/graphql/queries/searchCompanyQuery.ts
  front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  front/src/modules/ui/navbar/components/NavCollapseButton.tsx
  front/src/modules/ui/table/components/GenericEntityTableData.tsx
  front/src/pages/companies/Companies.tsx
  front/src/pages/people/People.tsx
  front/src/pages/tasks/Tasks.tsx
  front/src/sync-hooks/PageChangeEffect.tsx
Labels: awaiting author

#1403 Add Sentry for Backend
  server/.env.example
  server/package.json
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/interfaces/logger.interface.ts
  server/src/integrations/integrations.module.ts
  server/src/integrations/logger/drivers/sentry.driver.ts
  server/src/integrations/logger/interfaces/index.ts
  server/src/integrations/logger/interfaces/logger.interface.ts
  server/src/integrations/logger/logger.constants.ts
  server/src/integrations/logger/logger.module-definition.ts
  server/src/integrations/logger/logger.module.ts
  server/src/integrations/logger/logger.service.spec.ts
  server/src/integrations/logger/logger.service.ts
  server/src/main.ts
  server/yarn.lock
Labels: awaiting review

#1543 refactor: improve SingleEntitySelect empty option
  front/src/modules/activities/components/ActivityAssigneePicker.tsx
  front/src/modules/companies/components/CompanyPicker.tsx
  front/src/modules/companies/components/CompanyPickerCell.tsx
  front/src/modules/companies/components/CompanyProgressPicker.tsx
  front/src/modules/companies/components/NewCompanyProgressButton.tsx
  front/src/modules/people/components/PeoplePicker.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/editable-field/hooks/useUpdateGenericEntityField.ts
  front/src/modules/ui/editable-field/types/guards/isFieldRelationValue.ts
  front/src/modules/ui/editable-field/types/guards/isViewFieldRelationValue.ts
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/ui/input/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableRelationCellEditMode.tsx
  front/src/modules/ui/table/hooks/useUpdateEntityField.ts
  front/src/modules/ui/view-bar/components/FilterDropdownEntitySearchSelect.tsx
  front/src/modules/users/components/UserPicker.tsx
Labels: awaiting author

#1545 fix: Icon size stroke in MenuItem
  front/src/modules/ui/icon/types/IconComponent.ts
  front/src/modules/ui/menu-item/internals/components/MenuItemLeftContent.tsx
Labels: awaiting author

#1489 Add a notification for "tasks" in the navigation
  front/src/AppNavbar.tsx
  front/src/modules/activities/tasks/components/TaskGroups.tsx
  front/src/modules/activities/tasks/hooks/useCurrentUserDueTaskCount.ts
  front/src/modules/activities/tasks/hooks/useInitializeTasksFilters.ts
  front/src/modules/activities/tasks/hooks/useTasks.ts
  front/src/modules/companies/table/components/companies-mock-data.ts
  front/src/modules/ui/navbar/components/NavItem.tsx
  front/src/pages/tasks/Tasks.tsx
  front/src/pages/tasks/TasksEffect.tsx
  front/src/testing/mock-data/activities.ts
  front/src/testing/mock-data/companies.ts
  play.md
Labels: run-chromatic

#1556 Number display formatting
  front/src/modules/ui/content-display/components/MoneyDisplay.tsx
  front/src/modules/ui/content-display/components/NumberDisplay.tsx
  front/src/modules/ui/editable-field/components/GenericEditableNumberField.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCell.tsx
  front/src/utils/format/__tests__/number.test.ts
  front/src/utils/format/number.ts
  front/src/utils/formatNumber.ts
Labels: awaiting author

#1547 feat: toggle board field visibilities
  front/src/modules/companies/__stories__/CompanyBoardCard.stories.tsx
  front/src/modules/companies/board/components/CompanyBoard.tsx
  front/src/modules/companies/components/CompanyBoardCard.tsx
  front/src/modules/companies/components/HooksCompanyBoard.tsx
  front/src/modules/pipeline/constants/pipelineAvailableFieldDefinitions.tsx
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/components/EntityBoardCard.tsx
  front/src/modules/ui/board/components/EntityBoardColumn.tsx
  front/src/modules/ui/board/hooks/useBoardCardFields.ts
  front/src/modules/ui/board/states/availableBoardCardFieldsScopedState.ts
  front/src/modules/ui/board/states/boardCardFieldsScopedState.ts
  front/src/modules/ui/board/states/selectors/boardCardFieldsByKeyScopedSelector.ts
  front/src/modules/ui/board/states/selectors/hiddenBoardCardFieldsScopedSelector.ts
  front/src/modules/ui/board/states/selectors/visibleBoardCardFieldsScopedSelector.ts
  front/src/modules/ui/board/states/viewFieldsDefinitionsState.ts
  front/src/modules/ui/board/types/BoardOptions.ts
  front/src/modules/ui/button/components/FloatingIconButtonGroup.tsx
  front/src/modules/ui/editable-field/types/ViewField.ts
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownSection.tsx
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
  front/src/modules/ui/table/types/ColumnDefinition.ts
  front/src/modules/ui/view-bar/components/ViewBar.tsx
  front/src/modules/ui/view-bar/components/ViewFieldsVisibilityDropdownSection.tsx
  front/src/modules/views/hooks/useBoardViewFields.ts
  front/src/modules/views/hooks/useBoardViews.ts
  front/src/pages/opportunities/opportunitiesBoardOptions.tsx
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/companies.ts
Labels: awaiting author

#1569 multi tenant schemas poc
  server/package.json
  server/src/core/core.module.ts
  server/src/core/tenant/datasource/datasource.module.ts
  server/src/core/tenant/datasource/entities/base.entity.ts
  server/src/core/tenant/datasource/entities/data-source-metadata.entity.ts
  server/src/core/tenant/datasource/entities/field-metadata.entity.ts
  server/src/core/tenant/datasource/entities/object-metadata.ts
  server/src/core/tenant/datasource/entities/relation-medata.ts
  server/src/core/tenant/datasource/services/datasource.service.ts
  server/src/core/tenant/datasource/utils/datasource.util.ts
  server/src/core/tenant/metadata/metadata.controller.ts
  server/src/core/tenant/metadata/metadata.module.ts
  server/src/core/tenant/metadata/metadata.service.ts
  server/src/core/tenant/tenant.module.ts
  server/yarn.lock
Labels: PR: wip

#1566 feat: persist board card fields
  front/src/modules/companies/board/components/CompanyBoard.tsx
  front/src/modules/companies/table/components/CompanyTable.tsx
  front/src/modules/companies/table/components/CompanyTableMockMode.tsx
  front/src/modules/people/table/components/PeopleTable.tsx
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdown.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/states/savedBoardCardFieldsFamilyState.ts
  front/src/modules/ui/board/states/selectors/canPersistBoardCardFieldsScopedFamilySelector.ts
  front/src/modules/ui/board/states/selectors/savedBoardCardFieldsByKeyFamilySelector.ts
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdown.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
  front/src/modules/ui/top-bar/TopBar.tsx
  front/src/modules/ui/view-bar/components/UpdateViewButtonGroup.tsx
  front/src/modules/ui/view-bar/components/ViewBar.tsx
  front/src/modules/ui/view-bar/components/ViewBarDetails.tsx
  front/src/modules/ui/view-bar/components/ViewsDropdownButton.tsx
  front/src/modules/ui/view-bar/contexts/ViewBarContext.ts
  front/src/modules/ui/view-bar/hooks/useRemoveView.ts
  front/src/modules/ui/view-bar/hooks/useUpsertView.ts
  front/src/modules/views/hooks/useBoardViewFields.ts
  front/src/modules/views/hooks/useBoardViews.ts
  front/src/modules/views/hooks/useTableViews.ts
  front/src/modules/views/hooks/useViews.ts
Labels: PR: awaiting review

#1578 Feat/sidecar components
  front/.eslintrc.js
  front/package.json
  front/src/App.tsx
  front/src/effect-components/CommandMenuEffect.tsx
  front/src/effect-components/GotoHotkeysEffect.tsx
  front/src/effect-components/PageChangeEffect.tsx
  front/src/index.tsx
  front/src/modules/companies/__stories__/Board.stories.tsx
  front/src/modules/companies/__stories__/CompanyBoardCard.stories.tsx
  front/src/modules/companies/board/components/CompanyBoard.tsx
  front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  front/src/modules/companies/table/components/CompanyTableMockDataEffect.tsx
  front/src/modules/companies/table/components/CompanyTableMockMode.tsx
  front/src/modules/debug/components/RecoilDebugObserver.tsx
  front/src/modules/people/components/PeopleEntityTableDataEffect.tsx
  front/src/modules/ui/layout/components/PageHotkeysEffect.tsx
  front/src/pages/auth/VerifyEffect.tsx
  front/src/pages/companies/Companies.tsx
  front/src/pages/impersonate/ImpersonateEffect.tsx
  front/src/pages/people/People.tsx
  front/src/sync-hooks/AppInternalHooks.tsx
  front/src/testing/InitializeHotkeyStorybookHook.tsx
  front/src/testing/decorators/RootDecorator.tsx
  front/yarn.lock
  packages/eslint-plugin-twenty-ts/.gitignore
  packages/eslint-plugin-twenty-ts/index.ts
  packages/eslint-plugin-twenty-ts/jest.config.js
  packages/eslint-plugin-twenty-ts/package.json
  packages/eslint-plugin-twenty-ts/src/rules/effect-components.ts
  packages/eslint-plugin-twenty-ts/src/tests/all.spec.ts
  packages/eslint-plugin-twenty-ts/src/tests/file.ts
  packages/eslint-plugin-twenty-ts/src/tests/react.tsx
  packages/eslint-plugin-twenty-ts/src/tests/tsconfig.json
  packages/eslint-plugin-twenty-ts/tsconfig.json
  packages/eslint-plugin-twenty-ts/yarn.lock
Labels: PR: awaiting author

#1588 fix menu-item floating buttons that should only be displayed on hover
  front/src/modules/ui/menu-item/components/MenuItem.tsx
Labels: PR: awaiting review

#1599 Fix: Bug with auto scroll
  front/src/modules/ui/table/editable-cell/components/EditableCellSoftFocusMode.tsx
Labels: PR: awaiting review

#1629 Introduce useOptimisticEvict
  front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEvict.ts
  front/src/modules/companies/hooks/useDeleteCompanies.ts
Labels: blocked: false

#1621 feat: added a dropDownCloseEffect component
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
  front/src/modules/ui/dropdown/components/DropdownCloseEffect.tsx
Labels: PR: awaiting author

#1618 fix: Migrate all rules from eslint-plugin-twenty to eslint-plugin-twenty-ts
  front/.eslintrc.js
  packages/eslint-plugin-twenty-ts/src/rules/matching-state-variable.ts
  packages/eslint-plugin-twenty-ts/src/rules/no-hardcoded-colors.ts
  packages/eslint-plugin-twenty-ts/src/rules/sort-css-properties-alphabetically.ts
  packages/eslint-plugin-twenty-ts/src/rules/styled-components-prefixed-with-styled.ts
  packages/eslint-plugin-twenty-ts/src/tests/matching-state-variable.spec.ts
  packages/eslint-plugin-twenty-ts/src/tests/no-hardcoded-colors.spec.ts
  packages/eslint-plugin-twenty-ts/src/tests/sort-css-properties-alphabetically.spec.ts
  packages/eslint-plugin-twenty-ts/src/tests/styled-components-prefixed-with-styled.spec.ts
  packages/eslint-plugin-twenty/index.js
  packages/eslint-plugin-twenty/package.json
  packages/eslint-plugin-twenty/rules/matching-state-variable.js
  packages/eslint-plugin-twenty/rules/no-hardcoded-colors.js
  packages/eslint-plugin-twenty/rules/sort-css-properties-alphabetically.js
  packages/eslint-plugin-twenty/rules/styled-components-prefixed-with-styled.js
  packages/eslint-plugin-twenty/yarn.lock
  server/.eslintrc.js
  server/package.json
  server/yarn.lock
Labels: PR: awaiting author

#1632 Write Storybook test for @/ui/navbar
  front/src/modules/ui/navbar/__stories__/MainNavbar.stories.tsx
  front/src/modules/ui/navbar/__stories__/NavCollapseButton.stories.tsx
  front/src/modules/ui/navbar/__stories__/NavItem.stories.tsx
  front/src/modules/ui/navbar/__stories__/SubMenuNavbar.stories.tsx
Labels: scope: front, PR: awaiting review

#1616 feat: Column title menus
  front/src/generated/graphql.tsx
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/table/components/ColumnHead.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableHeaderOptions.tsx
  front/src/modules/ui/table/constants/ColumnHeaderDropdownId.ts
  front/src/modules/ui/table/hooks/useTableColumns.ts
  front/src/modules/views/hooks/useTableViewFields.ts
  front/src/modules/views/hooks/useTableViews.ts
  server/package.json
  server/src/database/schema.prisma
  server/yarn.lock
Labels: PR: awaiting author

#1636 feat: reorder columns from table options
  front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/menu-item/components/MenuItem.tsx
  front/src/modules/ui/menu-item/internals/components/MenuItemLeftContent.tsx
  front/src/modules/ui/table/components/EntityTable.tsx
  front/src/modules/ui/table/hooks/useTableColumns.ts
  front/src/modules/ui/table/options/components/TableOptionsDropdownButton.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/table/states/isDraggingAndSelectingState.ts
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
  front/src/modules/ui/view-bar/components/ViewBarDetails.tsx
  front/src/modules/ui/view-bar/components/ViewFieldsVisibilityDropdownSection.tsx
  packages/eslint-plugin-twenty-ts/dist/index.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/effect-components.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/matching-state-variable.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/no-hardcoded-colors.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/sort-css-properties-alphabetically.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/styled-components-prefixed-with-styled.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/effect-components.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/file.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/matching-state-variable.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/no-hardcoded-colors.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/react.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/sort-css-properties-alphabetically.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/styled-components-prefixed-with-styled.spec.js
Labels: PR: awaiting author

#1648 fix: fix some views dropdown design issues
  front/src/modules/ui/button/components/FloatingIconButton.tsx
  front/src/modules/ui/button/components/FloatingIconButtonGroup.tsx
  front/src/modules/ui/menu-item/components/MenuItem.tsx
  front/src/modules/ui/view-bar/components/ViewsDropdownButton.tsx
Labels: run-chromatic

#1622 Add 'Esc' hotkey behavior on Filter and Sorts dropdown
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
  front/src/modules/ui/view-bar/components/SortDropdownButton.tsx
  front/src/modules/ui/view-bar/components/ViewBar.tsx
  front/src/modules/ui/view-bar/types/FiltersHotkeyScope.ts
Labels: PR: awaiting author

#1675 feat: reset Recoil state on logout
  front/src/modules/auth/hooks/useAuth.ts
  front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  front/src/modules/views/hooks/useViews.ts
Labels: PR: awaiting review

#1678 Fix front end
  front/.storybook/test-runner-jest.js
  front/src/modules/ui/dropdown/hooks/useDropdownButton.ts
  front/src/modules/ui/table/components/ColumnHead.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableHeaderOptions.tsx
  front/src/modules/ui/table/options/components/__stories__/TableOptionsDropdown.stories.tsx
Labels: PR: awaiting author

#1676 Fix tasks filters
  front/src/modules/ui/view-bar/components/FilterDropdownEntitySearchSelect.tsx
Labels: PR: awaiting review

#1628 fix: Update company picker keyboard navigation
  front/src/modules/ui/input/relation-picker/components/CreateNewButton.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/ui/input/relation-picker/constants/index.ts
  front/src/modules/ui/input/relation-picker/hooks/useEntitySelectScroll.ts
  front/src/modules/ui/input/relation-picker/hooks/useEntitySelectSearch.ts
  front/src/modules/ui/input/relation-picker/states/recoil-scope-contexts/RelationPickerRecoilScopeContext.ts
  front/src/modules/ui/input/relation-picker/states/relationPickerHoverIndexScopedState.ts
  front/src/modules/ui/input/relation-picker/states/relationPickerPreselectedIdScopedState.ts
  front/src/modules/ui/input/relation-picker/utils/getPreselectedIdIndex.ts
Labels: PR: awaiting author

#1706 Fix command menu keyboard input & refactor group
  front/src/modules/command-menu/components/CommandGroup.tsx
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/components/CommandMenuItem.tsx
  front/src/modules/command-menu/components/CommandMenuStyles.tsx
  front/src/modules/ui/menu-item/components/MenuItemCommand.tsx
Labels: PR: awaiting author

#1711 Chore: First table column should not be hideable
  front/src/modules/ui/table/components/ColumnHead.tsx
  front/src/modules/ui/table/components/EntityTableHeader.tsx
  front/src/modules/ui/table/components/EntityTableHeaderOptions.tsx
  front/src/modules/ui/table/components/TableColumnDropdownMenu.tsx
  front/src/modules/ui/table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/view-bar/components/ViewFieldsVisibilityDropdownSection.tsx
Labels: PR: awaiting review

#1733 Remove the {...props} pattern and props coupling, and create an eslint rule for that
  docs/docs/developer/frontend/style-guide.mdx
  front/.eslintrc.js
  front/src/modules/activities/table/components/CellCommentChip.tsx
  front/src/modules/auth/components/Logo.tsx
  front/src/modules/auth/components/Modal.tsx
  front/src/modules/auth/sign-in-up/components/FooterNote.tsx
  front/src/modules/spreadsheet-import/components/Heading.tsx
  front/src/modules/spreadsheet-import/components/Table.tsx
  front/src/modules/ui/button/components/MainButton.tsx
  front/src/modules/ui/button/components/RoundedIconButton.tsx
  front/src/modules/ui/checkmark/components/AnimatedCheckmark.tsx
  front/src/modules/ui/checkmark/components/Checkmark.tsx
  front/src/modules/ui/color-scheme/components/ColorSchemeCard.tsx
  front/src/modules/ui/dialog/components/Dialog.tsx
  front/src/modules/ui/dialog/components/DialogProvider.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuContainer.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuHeader.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx
  front/src/modules/ui/input/components/Radio.tsx
  front/src/modules/ui/input/image/components/ImageInput.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx
  front/src/modules/ui/input/text/components/TextInputSettings.tsx
  front/src/modules/ui/input/text/components/__stories__/TextInput.stories.tsx
  front/src/modules/ui/layout/components/PageHeader.tsx
  front/src/modules/ui/modal/components/Modal.tsx
  front/src/modules/ui/snack-bar/components/SnackBar.tsx
  front/src/modules/ui/snack-bar/components/SnackBarProvider.tsx
  front/src/modules/ui/step-bar/components/StepBar.tsx
  front/src/modules/ui/table/components/EntityTableColumnMenu.tsx
  front/src/modules/ui/tooltip/AppTooltip.tsx
  front/src/modules/ui/tooltip/__stories__/Tooltip.stories.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedEaseIn.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedTextWord.tsx
  packages/eslint-plugin-twenty-ts/dist/index.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/no-spread-props.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/no-spread-props.spec.js
  packages/eslint-plugin-twenty/index.ts
  packages/eslint-plugin-twenty/src/rules/no-spread-props.ts
  packages/eslint-plugin-twenty/src/tests/no-spread-props.spec.ts
Labels: PR: awaiting review

#1726 Chore(backend): Enable attaching attachments to companies and people (backend)
  front/src/generated/graphql.tsx
  front/src/modules/activities/graphql/mutations/uploadAttachment.ts
  server/src/core/attachment/resolvers/attachment.resolver.ts
  server/src/database/migrations/20230925153619_add_company_and_person_to_attachment/migration.sql
  server/src/database/schema.prisma
Labels: PR: awaiting review

#1724 Chore(server): I should be able to define deal amount's currency
  server/src/database/migrations/20230925151034_add_currency_column/migration.sql
  server/src/database/schema.prisma
Labels: PR: awaiting review

#1739 Fix cmd menu tests
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  front/src/modules/ui/navbar/__stories__/NavItem.stories.tsx
  front/src/modules/ui/table/editable-cell/type/components/GenericEditableDoubleTextChipCellDisplayMode.tsx
Labels: run-chromatic, PR: awaiting author

#1631 Add a hover on Show Person Avatar
  front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  front/src/modules/ui/view-bar/components/UpdateViewButtonGroup.tsx
  front/src/modules/users/components/Avatar.tsx
Labels: PR: awaiting author

#1699 feat: reorder kanban columns
  front/src/generated/graphql.tsx
  front/src/modules/companies/components/NewCompanyProgressButton.tsx
  front/src/modules/companies/hooks/useUpdateCompanyBoardColumns.ts
  front/src/modules/ui/board/components/BoardColumn.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/board/components/EntityBoard.tsx
  front/src/modules/ui/board/components/EntityBoardColumn.tsx
  front/src/modules/ui/board/contexts/BoardColumnContext.ts
  front/src/modules/ui/board/contexts/BoardColumnIdContext.ts
  front/src/modules/ui/board/hooks/useBoardColumns.ts
  front/src/modules/ui/board/states/savedBoardColumnsState.ts
  front/src/modules/ui/board/states/selectors/canPersistBoardColumnsSelector.ts
  front/src/modules/ui/table/components/TableColumnDropdownMenu.tsx
  front/src/modules/ui/table/hooks/useTableColumns.ts
  front/src/modules/views/hooks/useBoardViewFields.ts
  front/src/modules/views/hooks/useBoardViews.ts
  front/src/modules/views/hooks/useMoveViewColumns.ts
Labels: PR: awaiting author

#1737 Delete Opportunities column + Improving design of BoardColumnEditTitleMenu
  front/src/modules/ui/board/components/BoardColumnEditTitleMenu.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
Labels: PR: awaiting review

#1742 Add a type on CatalogDecorator
  front/src/modules/ui/button/components/__stories__/Button.stories.tsx
  front/src/modules/ui/button/components/__stories__/ButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingIconButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/FloatingIconButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/IconButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/IconButtonGroup.stories.tsx
  front/src/modules/ui/button/components/__stories__/LightButton.stories.tsx
  front/src/modules/ui/button/components/__stories__/LightIconButton.stories.tsx
  front/src/modules/ui/chip/components/__stories__/Chip.stories.tsx
  front/src/modules/ui/input/components/__stories__/AutosizeTextInput.stories.tsx
  front/src/modules/ui/input/components/__stories__/Checkbox.stories.tsx
  front/src/modules/ui/input/components/__stories__/Radio.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItem.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemMultiSelect.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemNavigate.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemSelect.stories.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemToggle.stories.tsx
  front/src/modules/ui/navbar/__stories__/NavItem.stories.tsx
  front/src/modules/ui/progress-bar/components/__stories__/CircularProgressBar.stories.tsx
  front/src/modules/ui/progress-bar/components/__stories__/ProgressBar.stories.tsx
  front/src/modules/ui/tab/components/__stories__/Tab.stories.tsx
  front/src/modules/ui/tag/components/__stories__/Tag.stories.tsx
  front/src/modules/ui/tooltip/__stories__/Tooltip.stories.tsx
  front/src/modules/ui/typography/components/__stories__/H1Title.stories.tsx
  front/src/testing/decorators/CatalogDecorator.tsx
  front/src/testing/types.ts
Labels: PR: awaiting review

#1710 POC: Save view as url param
  front/src/modules/companies/__stories__/Board.stories.tsx
  front/src/modules/companies/__stories__/CompanyBoardCard.stories.tsx
  front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  front/src/modules/ui/action-bar/components/__stories__/ActionBar.stories.tsx
  front/src/modules/ui/board/components/BoardHeader.tsx
  front/src/modules/ui/context-menu/components/__stories__/ContextMenu.stories.tsx
  front/src/modules/ui/table/components/EntityTableEffect.tsx
  front/src/modules/ui/table/table-header/components/TableHeader.tsx
Labels: PR: awaiting author

#1776 Fix: Consistent avatars for show pages
  front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  front/src/pages/companies/CompanyShow.tsx
  front/src/pages/people/PersonShow.tsx
Labels: run-chromatic

#1780 Fix board column title edit optimistic rendering #1745
  front/src/modules/ui/board/components/BoardColumnEditTitleMenu.tsx
Labels: PR: awaiting author
