Repository twentyhq/twenty, pull requests merged in 2023-10, with the labels that each got.

#1783 Fix docker setup with bcrypt
  infra/dev/Makefile
  infra/dev/docker-compose.yml
Labels: PR: awaiting review

#1804 eslint prettier error on windows #1798
  .vscode/settings.json
  front/.prettierrc
Labels: PR: awaiting author

#1862 Adding storybook tests on meta-types/display/components
  front/src/modules/ui/field/contexts/FieldContext.ts
  front/src/modules/ui/field/meta-types/display/components/__stories__/FieldDisplayContextProvider.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/MoneyFieldDisplay.stories.tsx
  front/src/testing/ComponentStorybookLayout.tsx
  front/src/testing/decorators/CatalogDecorator.tsx
  front/src/testing/decorators/ComponentDecorator.tsx
Labels: run-chromatic

#1874 Refactor draggable list
  front/src/modules/ui/draggable-list/__stories__/DraggableItem.stories.tsx
  front/src/modules/ui/draggable-list/__stories__/DraggableList.stories.tsx
  front/src/modules/ui/draggable-list/components/DraggableItem.tsx
  front/src/modules/ui/draggable-list/components/DraggableList.tsx
  front/src/modules/ui/menu-item/components/MenuItemDraggable.tsx
  front/src/modules/ui/menu-item/components/__stories__/MenuItemDraggable.stories.tsx
  front/src/modules/ui/view-bar/components/ViewFieldsVisibilityDropdownSection.tsx
Labels: run-chromatic

#1781 Fix overlay positioning for 'Sort,' 'Filter,' and 'Options' menus #1521
  front/src/modules/ui/dropdown/components/DropdownButton.tsx
Labels: run-chromatic

#1869 feat: add custom object create and update
  server/src/tenant/entity-resolver/entity-resolver.service.ts
  server/src/tenant/schema-generation/graphql-types/object.graphql-type.ts
  server/src/tenant/schema-generation/schema-generation.service.ts
Labels: PR: awaiting review

#1860 fix:Menus go back button style fix
  front/src/modules/ui/dropdown/components/DropdownMenuHeader.tsx
Labels: PR: awaiting author

#1897 chore: drop findMany and findUnique resolvers for custom objects
  server/src/tenant/universal/args/find-many-universal.args.ts
  server/src/tenant/universal/args/find-unique-universal.args.ts
  server/src/tenant/universal/universal.module.ts
  server/src/tenant/universal/universal.resolver.spec.ts
  server/src/tenant/universal/universal.resolver.ts
  server/src/tenant/universal/universal.service.spec.ts
  server/src/tenant/universal/universal.service.ts
Labels: PR: awaiting review

#1875 Added Overview page & edited Getting Started page
  .devcontainer/devcontainer.json
  .devcontainer/init.sh
  .ergomake/docker-compose.yml
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  README.md
  docs/docs/developer/_category_.json
  docs/docs/developer/additional/glossary.mdx
  docs/docs/developer/frontend/_category_.json
  docs/docs/developer/local-setup.mdx
  docs/docs/hosting/_category_.json
  docs/docs/hosting/self-hosting.mdx
  docs/docs/index.mdx
  docs/docs/start/getting-started.mdx
  docs/docs/start/overview.mdx
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/src/theme/icons.js
  docs/static/img/create-tasks-dark.png
  docs/static/img/create-tasks-light.png
  docs/yarn.lock
  sweep.yaml
Labels: PR: awaiting author

#1917 feat: add Object Detail page
  front/src/App.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/pages/settings/SettingsObjectDetail.tsx
  front/src/pages/settings/SettingsObjects.tsx
  front/src/pages/settings/__stories__/SettingsObjectDetail.stories.tsx
  front/src/pages/settings/constants/objectSettings.ts
Labels: run-chromatic

#1950 1584/fix/dropdown item width not correct
  front/src/modules/companies/components/CompanyProgressPicker.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
  front/src/modules/ui/board/components/BoardColumnEditTitleMenu.tsx
  front/src/modules/ui/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/context-menu/components/ContextMenu.tsx
  front/src/modules/ui/data-table/components/DataTableColumnDropdownMenu.tsx
  front/src/modules/ui/data-table/components/DataTableHeaderPlusButton.tsx
  front/src/modules/ui/data-table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuItemsContainer.tsx
  front/src/modules/ui/dropdown/components/StyledDropdownMenuItemsContainer.tsx
  front/src/modules/ui/dropdown/components/__stories__/DropdownMenu.stories.tsx
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/input/relation-picker/components/MultipleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  front/src/modules/ui/menu-item/internals/components/StyledMenuItemBase.tsx
  front/src/modules/ui/view-bar/components/FilterDropdownFilterSelect.tsx
  front/src/modules/ui/view-bar/components/FilterDropdownOperandSelect.tsx
  front/src/modules/ui/view-bar/components/SortDropdownButton.tsx
  front/src/modules/ui/view-bar/components/UpdateViewButtonGroup.tsx
  front/src/modules/ui/view-bar/components/ViewFieldsVisibilityDropdownSection.tsx
  front/src/modules/ui/view-bar/components/ViewsDropdownButton.tsx
Labels: run-chromatic

#1928 Objects Settings - Add the "New object" button
  front/src/modules/ui/typography/components/H1Title.tsx
  front/src/pages/settings/SettingsObjects.tsx
Labels: run-chromatic

#1876 Feat: Adjust the overlay style for changing the phone number's country
  front/src/modules/ui/input/Types/CountryPickerHotkeyScope.ts
  front/src/modules/ui/input/components/CountryPickerDropdownButton.tsx
  front/src/modules/ui/input/components/CountryPickerDropdownSelect.tsx
  front/src/modules/ui/input/components/PhoneInput.tsx
Labels: PR: awaiting author

#1932 Write Storybook tests for front/src/modules/ui/field/meta-types/display components
  front/src/modules/ui/field/meta-types/display/components/__stories__/DateFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/DoubleTextFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/EmailFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/NumberFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/URLFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/DateDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/EllipsisDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/EmailDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/MoneyDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/NumberDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/PhoneDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/TextDisplay.tsx
  front/src/modules/ui/field/meta-types/display/content-display/components/URLDisplay.tsx
  front/src/modules/ui/link/components/ContactLink.tsx
  front/src/modules/ui/link/components/PrimaryLink.tsx
  front/src/modules/ui/link/components/RawLink.tsx
  front/src/modules/ui/link/components/RoundedLink.tsx
  front/src/testing/ComponentStorybookLayout.tsx
  yarn.lock
Labels: run-chromatic

#1958 Update the frontend to adhere to the custom eslint rule `twenty/no-spread-props`
  front/src/modules/activities/table/components/CellCommentChip.tsx
  front/src/modules/auth/components/Logo.tsx
  front/src/modules/auth/components/Modal.tsx
  front/src/modules/auth/sign-in-up/components/FooterNote.tsx
  front/src/modules/companies/components/CompanyProgressPicker.tsx
  front/src/modules/spreadsheet-import/components/Heading.tsx
  front/src/modules/spreadsheet-import/components/Table.tsx
  front/src/modules/ui/button/components/MainButton.tsx
  front/src/modules/ui/button/components/RoundedIconButton.tsx
  front/src/modules/ui/checkmark/components/AnimatedCheckmark.tsx
  front/src/modules/ui/checkmark/components/Checkmark.tsx
  front/src/modules/ui/color-scheme/components/ColorSchemeCard.tsx
  front/src/modules/ui/data-table/components/DataTableHeaderPlusButton.tsx
  front/src/modules/ui/dialog/components/Dialog.tsx
  front/src/modules/ui/dialog/components/DialogProvider.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuContainer.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuHeader.tsx
  front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx
  front/src/modules/ui/input/components/Radio.tsx
  front/src/modules/ui/input/image/components/ImageInput.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx
  front/src/modules/ui/input/text/components/TextInputSettings.tsx
  front/src/modules/ui/input/text/components/__stories__/TextInput.stories.tsx
  front/src/modules/ui/layout/components/PageHeader.tsx
  front/src/modules/ui/modal/components/Modal.tsx
  front/src/modules/ui/snack-bar/components/SnackBar.tsx
  front/src/modules/ui/snack-bar/components/SnackBarProvider.tsx
  front/src/modules/ui/step-bar/components/StepBar.tsx
  front/src/modules/ui/tooltip/AppTooltip.tsx
  front/src/modules/ui/tooltip/__stories__/Tooltip.stories.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedEaseIn.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedTextWord.tsx
Labels: PR: awaiting review

#1968 feat: add Object Edit page
  front/src/App.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/pages/settings/SettingsObjectEdit.tsx
  front/src/pages/settings/__stories__/SettingsObjectEdit.stories.tsx
Labels: run-chromatic

#1970 feat: add New Object page
  front/src/App.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/pages/settings/SettingsNewObject.tsx
  front/src/pages/settings/__stories__/SettingsNewObject.stories.tsx
Labels: run-chromatic

#1972 1867 timebox add storybook tests on meta typesinputcomponents
  front/src/modules/ui/field/meta-types/__stories__/FieldContextProvider.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/DateFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/DoubleTextFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/EmailFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/MoneyFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/NumberFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/TextFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/display/components/__stories__/URLFieldDisplay.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/BooleanFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/DateFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/BooleanFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/DateFieldInput.stories.tsx
  front/src/modules/ui/input/components/BooleanInput.tsx
Labels: run-chromatic

#1988 feat: add Fields table to Object Detail page
  front/src/modules/settings/objects/components/ObjectFieldDataType.tsx
  front/src/modules/settings/objects/components/ObjectFieldItemTableRow.tsx
  front/src/modules/settings/objects/constants/mockObjects.ts
  front/src/modules/settings/objects/constants/objectSettings.ts
  front/src/modules/settings/objects/types/ObjectFieldItem.ts
  front/src/modules/ui/icon/index.ts
  front/src/modules/ui/layout/components/PagePanel.tsx
  front/src/modules/ui/table/components/TableSection.tsx
  front/src/pages/settings/SettingsNewObject.tsx
  front/src/pages/settings/SettingsObjectDetail.tsx
  front/src/pages/settings/SettingsObjectEdit.tsx
  front/src/pages/settings/SettingsObjects.tsx
  front/src/pages/settings/SettingsWorkspaceMembers.tsx
  front/src/pages/settings/constants/mockObjects.ts
Labels: run-chromatic

#1995 1909 object edit add icon section
  front/src/modules/settings/assets/ArrowRight.svg
  front/src/modules/settings/components/IconWithLabel.tsx
  front/src/modules/settings/components/SettingsIconSection.tsx
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/input/components/__stories__/IconPicker.stories.tsx
  front/src/modules/ui/input/hooks/useIconPicker.ts
  front/src/modules/ui/input/states/iconPickerState.ts
  front/src/modules/ui/input/types/IconPickerHotkeyScope.ts
  front/src/pages/settings/SettingsNewObject.tsx
Labels: run-chromatic, PR: awaiting author

#1866 Two cells can be focused at the same time in the tables Fixes #1826
  front/src/modules/ui/data-table/hooks/useGetIsSomeCellInEditMode.ts
  front/src/modules/ui/data-table/hooks/useMoveSoftFocusToCurrentCellOnHover.ts
  front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx
  front/src/modules/ui/data-table/table-cell/components/TableCellDisplayContainer.tsx
  front/src/modules/ui/data-table/table-cell/components/TableCellDisplayMode.tsx
  front/src/modules/ui/utilities/drag-select/hooks/useDragSelect.ts
Labels: PR: awaiting author

#1976 Replaced eslint rule twenty/no-spread-props to react/jsx-props-no-spreading
  front/.eslintrc.js
  front/src/modules/spreadsheet-import/provider/components/SpreadsheetImportProvider.tsx
  front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  front/src/modules/ui/board/components/EntityBoardCard.tsx
  front/src/modules/ui/board/components/EntityBoardColumn.tsx
  front/src/modules/ui/draggable-list/components/DraggableItem.tsx
  front/src/modules/ui/draggable-list/components/DraggableList.tsx
  packages/eslint-plugin-twenty-ts/dist/index.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/no-spread-props.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/no-spread-props.spec.js
  packages/eslint-plugin-twenty/index.ts
  packages/eslint-plugin-twenty/src/rules/no-spread-props.ts
  packages/eslint-plugin-twenty/src/tests/no-spread-props.spec.ts
Labels: PR: awaiting review

#1987 Chore(front): Add storybook tests on meta-types/input/components
  front/src/modules/ui/field/meta-types/input/components/ChipFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/DoubleTextChipFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/DoubleTextFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/EmailFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/MoneyFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/NumberFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/PhoneFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/ProbabilityFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/RelationFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/TextFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/URLFieldInput.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/ChipFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/DoubleTextChipFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/DoubleTextFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/EmailFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/MoneyFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/PhoneFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/ProbabilityFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  front/src/modules/ui/field/meta-types/input/components/__stories__/URLFieldInput.stories.tsx
  front/src/testing/mock-data/users.ts
  front/yarn.lock
Labels: PR: awaiting review

#2014 Add an ESLint rule to prevent the usage of useRef other than for HTML elements.
  front/.eslintrc.js
  front/package.json
  front/src/hooks/useFirstMountState.ts
  front/src/modules/apollo/hooks/useApolloFactory.ts
  front/src/modules/ui/data/field/meta-types/input/components/internal/DateInput.tsx
  front/src/modules/ui/data/field/meta-types/input/components/internal/PhoneInput.tsx
  front/src/modules/ui/data/field/meta-types/input/components/internal/TextInput.tsx
  front/src/modules/ui/feedback/progress-bar/components/ProgressBar.tsx
  front/src/modules/ui/feedback/snack-bar/components/SnackBar.tsx
  front/src/modules/ui/feedback/snack-bar/hooks/usePausableTimeout.ts
  front/src/modules/ui/layout/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenuContainer.tsx
  front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
  front/src/modules/ui/navigation/action-bar/components/ActionBar.tsx
  front/src/modules/ui/navigation/context-menu/components/ContextMenu.tsx
  front/src/modules/ui/utilities/pointer-event/hooks/__tests__/useListenClickOutsideArrayOfRef.test.tsx
  front/src/modules/ui/utilities/recoil-scope/components/RecoilScope.tsx
  front/yarn.lock
  packages/eslint-plugin-twenty-ts/dist/index.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/component-props-naming.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/effect-components.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/matching-state-variable.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/no-hardcoded-colors.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/sort-css-properties-alphabetically.js
  packages/eslint-plugin-twenty-ts/dist/src/rules/styled-components-prefixed-with-styled.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/component-props-naming.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/effect-components.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/file.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/matching-state-variable.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/no-hardcoded-colors.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/react.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/sort-css-properties-alphabetically.spec.js
  packages/eslint-plugin-twenty-ts/dist/src/tests/styled-components-prefixed-with-styled.spec.js
  packages/eslint-plugin-twenty/index.ts
  packages/eslint-plugin-twenty/src/rules/no-state-useref.ts
  packages/eslint-plugin-twenty/src/tests/no-state-useref.spec.ts
Labels: PR: awaiting author

#2017 Add S3 endpoint env variable
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/file-storage/drivers/s3.driver.ts
  server/src/integrations/integrations.module.ts
Labels: PR: wip

#1985 feat: New Object - Add Object type section #1918
  front/src/modules/settings/objects/components/NewObjectType.tsx
  front/src/modules/settings/objects/components/ObjectTypeCard.tsx
  front/src/modules/ui/display/icon/index.ts
  front/src/pages/settings/SettingsNewObject.tsx
Labels: PR: awaiting author

#2057 Chore(server): Enable local database installation on MacOS
  docs/docs/contributor/local-setup/yarn-setup.mdx
  infra/dev/scripts/setup-postgres-linux.sh
  infra/dev/scripts/setup-postgres-macos.sh
Labels: PR: awaiting author

#2081 1809 new object add cancel and save buttons
  front/src/modules/settings/components/SaveAndCancelButtons/CancelButton.tsx
  front/src/modules/settings/components/SaveAndCancelButtons/SaveAndCancelButtons.tsx
  front/src/modules/settings/components/SaveAndCancelButtons/SaveButton.tsx
  front/src/modules/settings/components/__stories__/CancelButton.stories.tsx
  front/src/modules/settings/components/__stories__/SaveButton.stories.tsx
  front/src/pages/settings/data-model/SettingsNewObject.tsx
Labels: run-chromatic, PR: awaiting review

#2088 Use SaveAndCancelButtons in SettingsObjectNewFieldStep1
  front/src/modules/settings/components/SettingsHeaderContainer.tsx
  front/src/pages/settings/data-model/SettingsNewObject.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: run-chromatic, PR: awaiting review

#2071 feat: created new Developers Page in Settings
  front/src/App.tsx
  front/src/modules/settings/components/SettingsNavbar.tsx
  front/src/modules/settings/developers/components/SettingsApisFieldItemTableRow.tsx
  front/src/modules/settings/developers/constants/mockObjects.ts
  front/src/modules/settings/developers/types/ApisFieldItem.ts
  front/src/modules/types/SettingsPath.ts
  front/src/modules/ui/display/icon/index.ts
  front/src/modules/ui/layout/table/components/TableCell.tsx
  front/src/pages/settings/SettingsApis.tsx
Labels: PR: awaiting author

#2087 feat: add default filter types
  server/src/tenant/schema-builder/graphql-types/input/big-float-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/big-int-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/date-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/datetime-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/filter-is-enum-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/float-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/int-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/money-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/string-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/time-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/url-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/input/uuid-filter.type.ts
  server/src/tenant/schema-builder/graphql-types/object/page-into.type.ts
  server/src/tenant/schema-builder/graphql-types/scalars/big-float.scalar.ts
  server/src/tenant/schema-builder/graphql-types/scalars/big-int.scalar.ts
  server/src/tenant/schema-builder/graphql-types/scalars/date.scalar.ts
  server/src/tenant/schema-builder/graphql-types/scalars/datetime.scalar.ts
  server/src/tenant/schema-builder/graphql-types/scalars/time.scalar.ts
  server/src/tenant/schema-builder/graphql-types/scalars/uuid.scalar.ts
  server/src/tenant/schema-builder/utils/__tests__/generate-connection-type.spec.ts
  server/src/tenant/schema-builder/utils/__tests__/map-column-type-to-filter-type.spec.ts
  server/src/tenant/schema-builder/utils/generate-connection-type.util.ts
  server/src/tenant/schema-builder/utils/map-column-type-to-filter-type.util.ts
Labels: PR: awaiting author

#2086 Added metadata creation
  front/src/App.tsx
  front/src/generated-metadata/gql.ts
  front/src/generated-metadata/graphql.ts
  front/src/index.tsx
  front/src/modules/metadata/components/ApolloClientMetadataProvider.tsx
  front/src/modules/metadata/components/FetchMetadataEffect.tsx
  front/src/modules/metadata/components/ObjectDataTableEffect.tsx
  front/src/modules/metadata/components/ObjectTable.tsx
  front/src/modules/metadata/context/ApolloClientMetadataContext.ts
  front/src/modules/metadata/graphql/queries.ts
  front/src/modules/metadata/hooks/useApolloClientMetadata.ts
  front/src/modules/metadata/hooks/useCreateOneCustomObject.ts
  front/src/modules/metadata/hooks/useCreateOneMetadataField.ts
  front/src/modules/metadata/hooks/useCreateOneMetadataObject.ts
  front/src/modules/metadata/hooks/useFindAllMetadata.ts
  front/src/modules/metadata/hooks/useFindManyCustomObjects.ts
  front/src/modules/metadata/hooks/useSeedCustomObjectsTemp.ts
  front/src/modules/metadata/hooks/useSetDataTableData.ts
  front/src/modules/metadata/types/PaginatedObjectType.ts
  front/src/modules/metadata/utils/formatPagedMetadataObjectsToMetadataObjects.ts
  front/src/modules/metadata/utils/formatPagedObjectsToObjects.ts
  front/src/modules/metadata/utils/generateFindManyCustomObjectsQuery.ts
  front/src/modules/ui/data/data-table/components/DataTableBody.tsx
  front/src/pages/companies/ObjectsTable.tsx
Labels: PR: awaiting author

#2089 2038 zapier integration 1 initialize a zapier app with a twenty related account
  docs/docs/contributor/server/basics/zapier.mdx
  docs/src/theme/icons.js
  packages/twenty-zapier/.env.example
  packages/twenty-zapier/.gitignore
  packages/twenty-zapier/.prettierrc
  packages/twenty-zapier/.zapierapprc
  packages/twenty-zapier/index.js
  packages/twenty-zapier/package.json
  packages/twenty-zapier/src/authentication.ts
  packages/twenty-zapier/src/creates/create_person.ts
  packages/twenty-zapier/src/index.ts
  packages/twenty-zapier/src/test/authentication.test.ts
  packages/twenty-zapier/src/test/creates/create_person.test.ts
  packages/twenty-zapier/tsconfig.json
  packages/twenty-zapier/yarn.lock
Labels: PR: awaiting author

#2034 Fix(front): notes relation picker
  front/src/modules/activities/notes/components/NoteCard.tsx
Labels: scope: front, PR: awaiting review

#2096 1761 objects settings add a cover image
  front/src/modules/settings/data-model/assets/build-your-business-logic.jpg
  front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx
  front/src/modules/ui/theme/constants/animation.ts
  front/src/modules/ui/utilities/animation/components/AnimatedEaseIn.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedFadeOut.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting review

#2098 Chore: Deploy to Render updated (#2033)
  infra/prod/postgres/Dockerfile
  infra/prod/postgres/init.sql
  render.yaml
Labels: PR: awaiting review

#2102 Feat/metadata add update and delete on frontend
  front/src/generated-metadata/gql.ts
  front/src/generated-metadata/graphql.ts
  front/src/index.tsx
  front/src/modules/metadata/components/ApolloMetadataClientProvider.tsx
  front/src/modules/metadata/components/FetchMetadataEffect.tsx
  front/src/modules/metadata/components/ObjectDataTableEffect.tsx
  front/src/modules/metadata/components/ObjectTable.tsx
  front/src/modules/metadata/graphql/mutations.ts
  front/src/modules/metadata/graphql/queries.ts
  front/src/modules/metadata/hooks/useApolloMetadataClient.ts
  front/src/modules/metadata/hooks/useCreateOneMetadataField.ts
  front/src/modules/metadata/hooks/useCreateOneMetadataObject.ts
  front/src/modules/metadata/hooks/useCreateOneObject.ts
  front/src/modules/metadata/hooks/useFindManyMetadataObjects.ts
  front/src/modules/metadata/hooks/useFindManyObjects.ts
  front/src/modules/metadata/hooks/useSeedCustomObjectsTemp.ts
  front/src/modules/metadata/hooks/useUpdateOneMetadataField.ts
  front/src/modules/metadata/hooks/useUpdateOneMetadataObject.ts
  front/src/modules/metadata/utils/formatPagedObjectsToObjects.ts
  front/src/modules/metadata/utils/generateCreateOneObjectMutation.ts
  front/src/pages/companies/ObjectsTable.tsx
  front/src/utils/isNonEmptyArray.ts
  front/src/utils/string/capitalize.ts
Labels: PR: awaiting author

#2104 1801 objects settings add activate option to disabled menu
  front/src/modules/settings/data-model/objects/SettingsObjectDisabledMenuDropDown.tsx
  front/src/modules/settings/data-model/objects/__stories__/SettingsObjectDisabledMenuDropDown.stories.tsx
  front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: run-chromatic, PR: awaiting review

#2103 add clicking on dropdown menu test
  front/src/modules/ui/layout/dropdown/components/__stories__/DropdownMenu.stories.tsx
Labels: PR: awaiting author

#2094 Fix: hotkey scope not correctly set
  front/src/modules/companies/editable-field/components/CompanyNameEditableField.tsx
  front/src/modules/companies/editable-field/types/EditableFieldHotkeyScope.ts
  front/src/modules/ui/input/components/EntityTitleDoubleTextInput.tsx
Labels: PR: awaiting review

#2116 Fix api keys
  render.yaml
  server/.env.example
  server/.env.test
  server/src/core/api-key/api-key.service.ts
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/environment.validation.ts
Labels: PR: wip

#2120 Created two new env variables
  front/src/generated/graphql.tsx
  front/src/modules/client-config/components/ClientConfigProvider.tsx
  front/src/modules/client-config/graphql/queries/getClientConfig.ts
  front/src/modules/client-config/states/isDataModelSettingsEnabled.ts
  front/src/modules/client-config/states/isDevelopersSettingsEnabled.ts
  front/src/modules/settings/components/SettingsNavbar.tsx
  front/src/testing/graphqlMocks.ts
  server/.env.example
  server/.env.test
  server/src/core/client-config/client-config.entity.ts
  server/src/core/client-config/client-config.resolver.ts
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/environment.validation.ts
Labels: PR: awaiting author

#2119 feat: get active and disabled objects from backend in Objects Setting…
  front/src/modules/metadata/hooks/useObjectMetadata.ts
  front/src/modules/metadata/states/selectors/activeMetadataObjectsSelector.ts
  front/src/modules/metadata/states/selectors/disabledMetadataObjectsSelector.ts
  front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting review

#2122 feat: get object metadata from backend in Object Detail and New Field…
  front/src/modules/settings/data-model/object-details/components/SettingsObjectAboutSection.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  front/src/modules/settings/data-model/types/ObjectFieldDataType.ts
  front/src/modules/settings/data-model/types/ObjectFieldItem.ts
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/input/hooks/useLazyLoadIcon.ts
  front/src/modules/ui/input/hooks/useLazyLoadIcons.ts
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting review

#2125 feat: get object metadata from backend in Object Edit
  front/src/modules/settings/data-model/object-edit/SettingsObjectIconSection.tsx
  front/src/modules/settings/data-model/object-edit/SettingsObjectIconWithLabel.tsx
  front/src/modules/ui/display/icon/index.ts
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
Labels: PR: awaiting review

#2157 Chore(front): Create Storybook tests for the DropdownMenu component
  front/.storybook/preview-head.html
  front/package.json
  front/src/modules/companies/components/CompanyProgressPicker.tsx
  front/src/modules/people/components/PeopleCard.tsx
  front/src/modules/pipeline/components/PipelineAddButton.tsx
  front/src/modules/settings/data-model/objects/SettingsObjectDisabledMenuDropDown.tsx
  front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
  front/src/modules/ui/data/data-table/components/ColumnHeadWithDropdown.tsx
  front/src/modules/ui/data/data-table/components/DataTableColumnDropdownMenu.tsx
  front/src/modules/ui/data/data-table/components/DataTableHeaderPlusButton.tsx
  front/src/modules/ui/data/data-table/options/components/TableOptionsDropdown.tsx
  front/src/modules/ui/data/data-table/options/components/TableOptionsDropdownContent.tsx
  front/src/modules/ui/data/view-bar/components/FilterDropdownEntitySelect.tsx
  front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownButton.tsx
  front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx
  front/src/modules/ui/data/view-bar/components/SingleEntityFilterDropdownButton.tsx
  front/src/modules/ui/data/view-bar/components/SortDropdownButton.tsx
  front/src/modules/ui/data/view-bar/components/UpdateViewButtonGroup.tsx
  front/src/modules/ui/data/view-bar/components/ViewBarDropdownButton.tsx
  front/src/modules/ui/data/view-bar/components/ViewsDropdownButton.tsx
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/input/components/internal/phone/components/CountryPickerDropdownButton.tsx
  front/src/modules/ui/input/components/internal/phone/components/CountryPickerDropdownSelect.tsx
  front/src/modules/ui/input/relation-picker/components/MultipleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/ui/layout/board/components/BoardColumnEditTitleMenu.tsx
  front/src/modules/ui/layout/board/components/BoardColumnMenu.tsx
  front/src/modules/ui/layout/board/components/BoardOptionsDropdown.tsx
  front/src/modules/ui/layout/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenuContainer.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenuInputContainer.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownMenuSeparator.tsx
  front/src/modules/ui/layout/dropdown/components/StyledDropdownMenu.tsx
  front/src/modules/ui/layout/dropdown/components/__stories__/DropdownMenu.stories.tsx
  front/src/modules/ui/layout/dropdown/components/__stories__/DropdownMenuInput.stories.tsx
  front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  front/src/modules/ui/navigation/context-menu/components/ContextMenu.tsx
Labels: scope: front, PR: awaiting review

#2115 fix: value changes every render
  front/src/modules/activities/editable-fields/components/ActivityAssigneeEditableField.tsx
Labels: PR: awaiting author

#2111 feat: add new object standard available section
  front/src/modules/settings/data-model/constants/mockObjects.ts
  front/src/modules/settings/data-model/new-object/components/SettingsNewObjectType.tsx
  front/src/modules/settings/data-model/new-object/components/SettingsStandardObjects.tsx
  front/src/modules/ui/display/icon/index.ts
Labels: PR: awaiting review

#2186 #2133 added comments icon and count on notes tab
  front/src/generated/graphql.tsx
  front/src/modules/activities/notes/components/NoteCard.tsx
  front/src/testing/mock-data/activities.ts
Labels: PR: awaiting review

#2067 Fix Boolean field for hotkey
  front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx
  front/src/modules/ui/data/field/hooks/useToggleEditOnlyInput.ts
Labels: PR: awaiting review

#2194 feat: activate and disable objects
  front/src/modules/metadata/hooks/useObjectMetadata.ts
  front/src/modules/settings/data-model/object-details/components/SettingsObjectAboutSection.tsx
  front/src/modules/settings/data-model/objects/SettingsObjectDisabledMenuDropDown.tsx
  front/src/modules/settings/data-model/objects/__stories__/SettingsObjectDisabledMenuDropDown.stories.tsx
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting review

#2136 Chore(front): Add more typeguards
  front/.env.example
  front/package.json
  front/src/hooks/useCombinedRefs.ts
  front/src/modules/activities/components/ActivityComments.tsx
  front/src/modules/ui/data/field/types/guards/isFieldBooleanValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldChipValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldDateValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldEmailValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldMoneyValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldNumberValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldPhoneValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldProbabilityValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldRelationValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldTextValue.ts
  front/src/modules/ui/data/field/types/guards/isFieldURLValue.ts
  front/src/modules/ui/display/chip/components/EntityChip.tsx
  front/src/modules/ui/input/relation-picker/components/MultipleEntitySelect.tsx
  front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx
  front/src/modules/users/components/Avatar.tsx
  front/src/pages/auth/VerifyEffect.tsx
  front/src/pages/impersonate/ImpersonateEffect.tsx
  front/src/pages/people/__stories__/People.inputs.stories.tsx
  front/src/testing/decorators/CatalogDecorator.tsx
  front/src/testing/mock-data/index.ts
  front/src/utils/cast-as-integer-or-null.ts
  front/src/utils/cast-as-positive-integer-or-null.ts
  front/src/utils/date-utils.ts
  front/src/utils/isNonEmptyString.ts
  front/yarn.lock
Labels: scope: front, PR: awaiting review

#2209 Changes to documentation
  docs/docs/developer/graphql_api.mdx
  docs/docs/developer/overview.mdx
  docs/docs/developer/rest_api.mdx
  docs/docs/user-guide/_category_.json
  docs/docs/user-guide/custom objects.mdx
  docs/docs/user-guide/glossary.mdx
  docs/docs/user-guide/user-guide.mdx
  docs/docs/user-guide/zapier integration.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/theme/icons.js
Labels: PR: awaiting author

#2181 fix: update dropdown width
  front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx
  front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx
  front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  front/src/modules/ui/layout/dropdown/components/DropdownOnToggleEffect.tsx
  front/src/modules/ui/layout/dropdown/hooks/useDropdown.ts
  front/src/modules/ui/layout/dropdown/hooks/useDropdownStates.ts
  front/src/modules/ui/layout/dropdown/states/dropdownWidthScopedState.ts
Labels: PR: awaiting author

#2182 1259/add compact view in opportunities
  front/src/modules/companies/components/CompanyBoardCard.tsx
  front/src/modules/ui/display/icon/index.ts
  front/src/modules/ui/input/components/Toggle.tsx
  front/src/modules/ui/layout/board/components/BoardOptionsDropdown.tsx
  front/src/modules/ui/layout/board/components/BoardOptionsDropdownContent.tsx
  front/src/modules/ui/layout/board/states/isCardInCompactViewState.ts
  front/src/modules/ui/layout/board/states/isCompactViewEnabledState.ts
  front/src/modules/ui/navigation/menu-item/components/MenuItemToggle.tsx
  front/src/modules/ui/utilities/animation/components/AnimatedEaseInOut.tsx
Labels: PR: awaiting author

#2220 feat: create custom object and update edited object names
  front/package.json
  front/src/generated-metadata/graphql.ts
  front/src/modules/metadata/hooks/useObjectMetadata.ts
  front/src/modules/metadata/hooks/useUpdateOneMetadataObject.ts
  front/src/modules/metadata/utils/formatMetadataObjectInput.ts
  front/src/modules/metadata/utils/getObjectSlug.ts
  front/src/modules/metadata/utils/validateMetadataObjectLabel.ts
  front/src/modules/settings/data-model/components/SettingsObjectFormSection.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/pages/settings/data-model/SettingsNewObject.tsx
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
  front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
  front/src/pages/settings/data-model/__stories__/SettingsObjectEdit.stories.tsx
  front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep1.stories.tsx
  front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep2.stories.tsx
  front/yarn.lock
  server/src/metadata/object-metadata/dtos/update-object.input.ts
Labels: PR: awaiting review

#2231 2062 view edit an api key
  front/nyc.config.js
  front/src/generated/graphql.tsx
  front/src/modules/activities/notes/components/NoteCard.tsx
  front/src/modules/settings/developers/components/ApiKeyInput.tsx
  front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx
  front/src/modules/settings/developers/components/__stories__/ApiKeyInput.stories.tsx
  front/src/modules/settings/developers/constants/expirationDates.ts
  front/src/modules/settings/developers/constants/mockObjects.ts
  front/src/modules/settings/developers/graphql/queries/getApiKey.ts
  front/src/modules/settings/developers/graphql/queries/getApiKeys.ts
  front/src/modules/settings/developers/hooks/useGeneratedApiKeys.ts
  front/src/modules/settings/developers/states/generatedApiKeyFamilyState.ts
  front/src/modules/settings/developers/states/generatedApiKeyState.ts
  front/src/modules/settings/developers/types/ApiFieldItem.ts
  front/src/modules/settings/developers/utils/__tests__/compute-new-expiration-date.test.ts
  front/src/modules/settings/developers/utils/__tests__/format-expiration.test.ts
  front/src/modules/settings/developers/utils/compute-new-expiration-date.ts
  front/src/modules/settings/developers/utils/format-expiration.ts
  front/src/modules/ui/display/icon/index.ts
  front/src/modules/ui/input/components/Select.tsx
  front/src/modules/ui/input/components/TextInput.tsx
  front/src/modules/ui/input/components/__stories__/Select.stories.tsx
  front/src/modules/ui/input/components/__stories__/TextInput.stories.tsx
  front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeys.tsx
  front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  front/src/pages/settings/developers/api-keys/__stories__/SettingsDevelopersApiKeysDetail.stories.tsx
  front/src/testing/decorators/PageDecorator.tsx
  front/src/testing/graphqlMocks.ts
  front/src/testing/mock-data/api-keys.ts
  front/src/utils/__tests__/date-utils.test.ts
  front/src/utils/date-utils.ts
  server/.env.example
  server/src/integrations/environment/environment.service.ts
Labels: PR: awaiting author

#2225 feat: create custom object field
  front/src/modules/metadata/hooks/useFieldMetadata.ts
  front/src/modules/metadata/utils/formatMetadataFieldInput.ts
  front/src/modules/metadata/utils/validateMetadataLabel.ts
  front/src/modules/metadata/utils/validateMetadataObjectLabel.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldFormSection.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFormSection.tsx
  front/src/modules/settings/data-model/constants/dataTypes.ts
  front/src/modules/settings/data-model/constants/mockObjects.ts
  front/src/modules/settings/data-model/types/ObjectFieldDataType.ts
  front/src/modules/settings/data-model/types/ObjectFieldItem.ts
  front/src/modules/ui/display/icon/index.ts
  front/src/pages/settings/data-model/SettingsNewObject.tsx
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#2250 fix: generate metadata object and field names in camel case
  front/package.json
  front/src/modules/metadata/utils/formatMetadataFieldInput.ts
  front/src/modules/metadata/utils/formatMetadataObjectInput.ts
  front/yarn.lock
Labels: PR: awaiting review

#2237 Remove Metadata SoftDelete and page limit size
  server/src/metadata/data-source/data-source.service.ts
  server/src/metadata/field-metadata/field-metadata.entity.ts
  server/src/metadata/field-metadata/services/field-metadata.service.ts
  server/src/metadata/metadata.datasource.ts
  server/src/metadata/migrations/1698328717102-removeMetadataSoftDelete.ts
  server/src/metadata/object-metadata/object-metadata.entity.ts
  server/src/metadata/object-metadata/services/object-metadata.service.ts
Labels: PR: awaiting review

#2247 feat: remove disabled custom objects
  front/src/modules/metadata/hooks/useObjectMetadata.ts
  front/src/modules/settings/data-model/objects/SettingsObjectDisabledMenuDropDown.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting review

#2243 feat: add Object Field Edit page sections
  front/src/modules/metadata/hooks/useObjectMetadata.ts
  front/src/modules/metadata/utils/getFieldSlug.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/modules/ui/display/icon/types/IconComponent.ts
  front/src/modules/ui/input/components/Select.tsx
  front/src/modules/ui/input/components/__stories__/Select.stories.tsx
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#2232 feat: activate standard objects in New Object page
  front/src/modules/metadata/graphql/queries.ts
  front/src/modules/metadata/hooks/useFindManyMetadataObjects.ts
  front/src/modules/metadata/hooks/useFindManyObjects.ts
  front/src/modules/metadata/hooks/useMetadataField.ts
  front/src/modules/metadata/hooks/useMetadataObjectForSettings.ts
  front/src/modules/metadata/utils/formatMetadataFieldInput.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/constants/dataTypes.ts
  front/src/modules/settings/data-model/new-object/components/SettingsAvailableStandardObjectItemTableRow.tsx
  front/src/modules/settings/data-model/new-object/components/SettingsAvailableStandardObjectsSection.tsx
  front/src/modules/settings/data-model/new-object/components/SettingsNewObjectType.tsx
  front/src/modules/settings/data-model/new-object/components/SettingsStandardObjects.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  front/src/modules/settings/data-model/types/ObjectFieldDataType.ts
  front/src/modules/ui/layout/table/components/TableBody.tsx
  front/src/modules/ui/layout/table/components/TableRow.tsx
  front/src/modules/ui/layout/table/components/TableSection.tsx
  front/src/pages/settings/data-model/SettingsNewObject.tsx
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  front/src/pages/settings/data-model/SettingsObjects.tsx
  infra/dev/Makefile
  server/src/database/seeds/metadata.ts
  server/src/metadata/field-metadata/field-metadata.entity.ts
  server/src/metadata/object-metadata/object-metadata.entity.ts
Labels: PR: awaiting review

#2226 feat: save activated/disabled fields in New Field - Step 1 page
  front/src/modules/ui/data/data-table/options/components/TableOptionsDropdownContent.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
Labels: PR: awaiting review

#2245 feat: save edited custom field
  front/src/generated-metadata/graphql.ts
  front/src/modules/metadata/hooks/useMetadataField.ts
  front/src/modules/metadata/hooks/useUpdateOneMetadataField.ts
  front/src/modules/metadata/utils/formatMetadataFieldInput.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldFormSection.tsx
  front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  server/src/metadata/field-metadata/dtos/update-field.input.ts
Labels: PR: awaiting review

#2278 feat: custom objects delete one
  server/src/tenant/entity-resolver/entity-resolver.service.ts
  server/src/tenant/entity-resolver/pg-graphql/pg-graphql-query-builder.util.ts
  server/src/tenant/entity-resolver/pg-graphql/pg-graphql-query-runner.util.ts
  server/src/tenant/schema-builder/schema-builder.service.ts
Labels: scope: backend
