Repository twentyhq/twenty, pull requests merged in 2023-12, with the labels that each got.

#2770 feat: rename Probability field type to Rating and update preview
  front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  front/src/modules/settings/data-model/constants/settingsFieldMetadataTypes.ts
  front/src/modules/ui/display/icon/assets/twenty-star-filled.svg
  front/src/modules/ui/display/icon/assets/twenty-star.svg
  front/src/modules/ui/display/icon/components/IconTwentyStar.tsx
  front/src/modules/ui/display/icon/components/IconTwentyStarFilled.tsx
  front/src/modules/ui/object/field/components/FieldInput.tsx
  front/src/modules/ui/object/field/hooks/useIsFieldInputOnly.ts
  front/src/modules/ui/object/field/hooks/usePersistField.ts
  front/src/modules/ui/object/field/meta-types/hooks/useRatingField.ts
  front/src/modules/ui/object/field/meta-types/input/components/ProbabilityFieldInput.tsx
  front/src/modules/ui/object/field/meta-types/input/components/RatingFieldInput.tsx
  front/src/modules/ui/object/field/meta-types/input/components/__stories__/RatingFieldInput.stories.tsx
  front/src/modules/ui/object/field/meta-types/input/components/internal/ProbabilityInput.tsx
  front/src/modules/ui/object/field/meta-types/input/components/internal/RatingInput.tsx
  front/src/modules/ui/object/field/states/selectors/isEntityFieldEmptyFamilySelector.ts
  front/src/modules/ui/object/field/types/FieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/assertFieldMetadata.ts
  front/src/modules/ui/object/field/types/guards/isFieldProbability.ts
  front/src/modules/ui/object/field/types/guards/isFieldProbabilityValue.ts
  front/src/modules/ui/object/field/types/guards/isFieldRating.ts
  front/src/modules/ui/object/field/types/guards/isFieldRatingValue.ts
Labels: PR: awaiting review

#2491 add message queue integration
  docs/docs/contributor/server/basics/queue.mdx
  docs/docs/start/self-hosting/enviroment-variables.mdx
  server/.env.example
  server/package.json
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/interfaces/message-queue.interface.ts
  server/src/integrations/integrations.module.ts
  server/src/integrations/message-queue/drivers/bullmq.driver.ts
  server/src/integrations/message-queue/drivers/interfaces/job-options.interface.ts
  server/src/integrations/message-queue/drivers/interfaces/message-queue-driver.interface.ts
  server/src/integrations/message-queue/drivers/pg-boss.driver.ts
  server/src/integrations/message-queue/interfaces/index.ts
  server/src/integrations/message-queue/interfaces/message-queue.interface.ts
  server/src/integrations/message-queue/message-queue.constants.ts
  server/src/integrations/message-queue/message-queue.module.ts
  server/src/integrations/message-queue/services/message-queue-task-assigned.service.spec.ts
  server/src/integrations/message-queue/services/message-queue.service.ts
  server/yarn.lock
Labels: PR: awaiting author

#2757 Add rest api
  server/.env.example
  server/src/core/api-rest/api-rest.controller.ts
  server/src/core/api-rest/api-rest.module.ts
  server/src/core/api-rest/api-rest.service.spec.ts
  server/src/core/api-rest/api-rest.service.ts
  server/src/core/core.module.ts
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/environment.validation.ts
  server/src/utils/capitalize.ts
Labels: PR: wip, PR: awaiting author

#2622 2503-feat(front): hover icons added; commandmenu open added
  front/src/modules/ui/object/record-board/components/RecordBoardColumn.tsx
Labels: PR: awaiting author

#2683 [FEAT-2496] Add Customize fields button in new column menu
  front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  front/src/modules/ui/object/record-table/components/RecordTableHeaderPlusButtonContent.tsx
Labels: PR: awaiting author

#2549 fix: Remove "pen icon" on Team member field #2384
  front/src/modules/ui/object/field/hooks/useGetButtonIcon.ts
Labels: PR: awaiting review

#2304 feat: improve mobile display by tab bar and other changes
  front/src/AppNavbar.tsx
  front/src/modules/favorites/components/Favorites.tsx
  front/src/modules/navigation/components/DesktopNavigationDrawer.tsx
  front/src/modules/navigation/components/MobileNavigationBar.tsx
  front/src/modules/navigation/components/MobileNavigationDrawer.tsx
  front/src/modules/navigation/components/WorkspaceNavItems.tsx
  front/src/modules/navigation/components/__stories__/DesktopNavigationDrawer.stories.tsx
  front/src/modules/navigation/components/__stories__/MobileNavigationDrawer.stories.tsx
  front/src/modules/navigation/hooks/useIsSettingsPage.ts
  front/src/modules/navigation/hooks/useIsTasksPage.ts
  front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  front/src/modules/object-record/components/RecordTableContainer.tsx
  front/src/modules/settings/components/SettingsNavbar.tsx
  front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDisabledActionDropdown.tsx
  front/src/modules/settings/data-model/objects/SettingsObjectDisabledMenuDropDown.tsx
  front/src/modules/ui/layout/hooks/useIsMenuNavbarDisplayed.ts
  front/src/modules/ui/layout/hooks/useIsSubMenuNavbarDisplayed.ts
  front/src/modules/ui/layout/page/DefaultLayout.tsx
  front/src/modules/ui/layout/page/PageBody.tsx
  front/src/modules/ui/layout/page/PageContainer.tsx
  front/src/modules/ui/layout/page/PageHeader.tsx
  front/src/modules/ui/layout/page/RightDrawerContainer.tsx
  front/src/modules/ui/layout/page/SubMenuTopBarContainer.tsx
  front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
  front/src/modules/ui/layout/states/isNavbarOpenedState.ts
  front/src/modules/ui/layout/states/isNavbarSwitchingSizeState.ts
  front/src/modules/ui/navigation/navbar/components/NavbarAnimatedContainer.tsx
  front/src/modules/ui/navigation/navbar/constants/index.ts
  front/src/modules/ui/navigation/navigation-bar/components/NavigationBar.tsx
  front/src/modules/ui/navigation/navigation-bar/components/NavigationBarItem.tsx
  front/src/modules/ui/navigation/navigation-bar/components/__stories__/NavigationBar.stories.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/MainNavbar.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavBackButton.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavCollapseButton.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavItem.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavItemsContainer.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavTitle.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavWorkspaceButton.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavbarAnimatedContainer.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/SubMenuNavbar.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/SupportChat.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/__stories__/MainNavbar.stories.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavCollapseButton.stories.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavItem.stories.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/__stories__/SubMenuNavbar.stories.tsx
  front/src/modules/ui/navigation/navigation-drawer/constants/index.ts
  front/src/modules/ui/navigation/states/navigationDrawerState.ts
  front/src/modules/ui/navigation/states/navigationMemorizedUrlState.ts
  front/src/modules/ui/object/record-table/components/RecordTableBody.tsx
  front/src/utils/measureTotalFrameLoad.ts
Labels: PR: awaiting review

#2783 2727-fix(front): CommandMenu and KeyboardMenu invoke handled
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx
  front/src/modules/object-metadata/components/ObjectMetadataItemsLoadEffect.tsx
  front/src/modules/object-metadata/components/ObjectMetadataItemsProvider.tsx
  front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
Labels: PR: awaiting author

#2837 feat: create Settings/Accounts page
  front/src/App.tsx
  front/src/modules/settings/components/SettingsNavbar.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/modules/ui/display/icon/index.ts
  front/src/pages/settings/accounts/SettingsAccounts.tsx
Labels: PR: awaiting review

#2840 Bug Fix: Allows user to press 'Enter' to navigate through forms
  front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  front/src/modules/ui/input/components/TextInput.tsx
  front/src/pages/auth/CreateWorkspace.tsx
Labels: PR: awaiting review

#2791 fix: avoid create custom entities with the same name
  server/src/metadata/object-metadata/hooks/before-create-one-object.hook.ts
Labels: PR: awaiting review

#2849 fix: fix Pipeline Step title and color update in board
  front/src/modules/ui/object/record-board/components/RecordBoard.tsx
  front/src/modules/ui/object/record-board/components/RecordBoardColumn.tsx
  front/src/modules/ui/object/record-board/components/RecordBoardColumnDropdownMenu.tsx
  front/src/modules/ui/object/record-board/components/RecordBoardColumnEditTitleMenu.tsx
  front/src/modules/ui/object/record-board/components/RecordBoardColumnHeader.tsx
  front/src/modules/ui/object/record-board/contexts/BoardColumnContext.ts
  front/src/pages/opportunities/Opportunities.tsx
Labels: PR: awaiting review

#2839 Implement table record virtualizer back
  front/src/modules/ui/object/record-table/components/RecordTableBody.tsx
  front/src/modules/ui/utilities/virtualizer/RenderIfVisible.tsx
Labels: PR: awaiting review

#2844 Rest api updates
  server/.env.example
  server/.eslintrc.js
  server/src/core/api-rest/api-rest-query-builder/api-rest-query-builder.factory.spec.ts
  server/src/core/api-rest/api-rest-query-builder/api-rest-query-builder.factory.ts
  server/src/core/api-rest/api-rest-query-builder/api-rest-query-builder.module.ts
  server/src/core/api-rest/api-rest-query-builder/factories/create-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/create-variables.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/delete-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/delete-variables.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/factories.ts
  server/src/core/api-rest/api-rest-query-builder/factories/find-many-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/find-one-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/get-variables.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/__tests__/filter-input.factory.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/__tests__/last-cursor-input.factory.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/__tests__/limit-input.factory.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/__tests__/order-by-input.factory.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-input.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/add-default-conjunction.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/check-filter-query.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/format-field-values.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/parse-base-filter.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/parse-filter-content.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/parse-filter.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/add-default-conjunction.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/check-filter-query.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/format-field-values.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/parse-base-filter.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/parse-filter-content.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/filter-utils/parse-filter.utils.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/last-cursor-input.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/limit-input.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/input-factories/order-by-input.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/update-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/update-variables.factory.ts
  server/src/core/api-rest/api-rest-query-builder/utils/__tests__/compute-depth.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/utils/__tests__/fields.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/utils/__tests__/map-field-metadata-to-graphql-query.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/utils/__tests__/parse-path.utils.spec.ts
  server/src/core/api-rest/api-rest-query-builder/utils/__tests__/utils.ts
  server/src/core/api-rest/api-rest-query-builder/utils/compute-depth.utils.ts
  server/src/core/api-rest/api-rest-query-builder/utils/fields.utils.ts
  server/src/core/api-rest/api-rest-query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  server/src/core/api-rest/api-rest-query-builder/utils/parse-path.utils.ts
  server/src/core/api-rest/api-rest.controller.ts
  server/src/core/api-rest/api-rest.module.ts
  server/src/core/api-rest/api-rest.service.spec.ts
  server/src/core/api-rest/api-rest.service.ts
  server/src/core/api-rest/types/api-rest-field-value.type.ts
  server/src/core/api-rest/types/api-rest-query-variables.type.ts
  server/src/core/api-rest/types/api-rest-query.type.ts
  server/src/core/api-rest/types/api-rest-response.type.ts
  server/src/core/auth/auth.module.ts
  server/src/core/auth/services/token.service.ts
  server/src/integrations/environment/environment.service.ts
  server/src/integrations/environment/environment.validation.ts
  server/src/workspace/workspace-query-builder/interfaces/record.interface.ts
Labels: PR: awaiting author

#2856 2809 create connected account data model
  server/src/metadata/workspace-migration/migrations/1697618035-addConnectedAccount.ts
  server/src/metadata/workspace-migration/standard-migrations.ts
  server/src/workspace/workspace-manager/standard-objects/connected-account.ts
  server/src/workspace/workspace-manager/standard-objects/standard-object-metadata.ts
Labels: PR: awaiting review

#2866 Fix Infinite loop on invite route
  front/src/effect-components/PageChangeEffect.tsx
  front/src/hooks/useIsMatchingLocation.ts
  front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  front/src/modules/command-menu/hooks/useCommandMenu.ts
  front/src/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar.tsx
Labels: PR: awaiting review

#2841 Feature: Add Empty State Display for Tables
  front/src/modules/object-record/record-table/components/RecordTable.tsx
Labels: PR: awaiting review

#2867 feat: add Settings/Accounts/Emails page
  front/src/App.tsx
  front/src/modules/favorites/components/Favorites.tsx
  front/src/modules/navigation/components/MainNavigationDrawerItems.tsx
  front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  front/src/modules/types/SettingsPath.ts
  front/src/modules/ui/layout/page/RightDrawerContainer.tsx
  front/src/modules/ui/layout/page/SubMenuTopBarContainer.tsx
  front/src/modules/ui/navigation/bread-crumb/components/Breadcrumb.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerBackButton.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerHeader.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemGroup.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSectionTitle.tsx
  front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawer.stories.tsx
  front/src/modules/ui/theme/constants/theme.ts
  front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
  front/src/pages/settings/accounts/__stories__/SettingsAccounts.stories.tsx
  front/src/pages/settings/accounts/__stories__/SettingsAccountsEmails.stories.tsx
Labels: PR: awaiting review

#2869 feat: save Select field options
  front/package.json
  front/src/generated-metadata/gql.ts
  front/src/generated-metadata/graphql.ts
  front/src/generated/graphql.tsx
  front/src/modules/object-metadata/graphql/mutations.ts
  front/src/modules/object-metadata/graphql/queries.ts
  front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  front/src/modules/object-metadata/types/FieldMetadataItem.ts
  front/src/modules/object-metadata/types/FieldMetadataOption.ts
  front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  front/src/modules/object-record/field/meta-types/hooks/useRatingField.ts
  front/src/modules/object-record/field/meta-types/hooks/useSelectField.ts
  front/src/modules/object-record/field/meta-types/input/components/__stories__/RatingFieldInput.stories.tsx
  front/src/modules/object-record/field/states/selectors/isEntityFieldEmptyFamilySelector.ts
  front/src/modules/object-record/field/types/FieldType.ts
  front/src/modules/object-record/field/types/guards/assertFieldMetadata.ts
  front/src/modules/object-record/field/types/guards/isFieldRating.ts
  front/src/modules/object-record/field/types/guards/isFieldSelect.ts
  front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  front/src/modules/settings/data-model/constants/settingsFieldMetadataTypes.ts
  front/src/modules/settings/data-model/hooks/useFieldMetadataForm.ts
  front/src/modules/settings/data-model/hooks/useFieldPreview.ts
  front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  front/yarn.lock
Labels: PR: awaiting review

#2854 Add postgres_fdw to database
  infra/build/postgres/Dockerfile
  infra/dev/postgres/Dockerfile
  server/scripts/setup-db.ts
  server/scripts/utils.ts
Labels: PR: awaiting author

#2878 Fix relation between standard objects
  front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  server/src/metadata/relation-metadata/relation-metadata.service.ts
Labels: PR: awaiting author

#2889 Update token verification and fix typo
  server/src/app.module.ts
  server/src/core/api-rest/api-rest-query-builder/api-rest-query-builder.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/create-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/delete-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/find-many-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/find-one-query.factory.ts
  server/src/core/api-rest/api-rest-query-builder/factories/update-query.factory.ts
  server/src/core/auth/services/token.service.spec.ts
  server/src/core/auth/services/token.service.ts
  server/src/core/auth/strategies/jwt.auth.strategy.ts
Labels: PR: awaiting author

#2883 Picker and MultiSelect fixes
  front/src/modules/activities/notes/hooks/useNotes.ts
  front/src/modules/object-metadata/hooks/useGetObjectOrderByField.ts
  front/src/modules/object-metadata/hooks/useMapToObjectRecordIdentifier.ts
  front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  front/src/modules/object-metadata/types/OrderBy.ts
  front/src/modules/object-metadata/types/OrderByField.ts
  front/src/modules/object-metadata/utils/getObjectOrderByField.ts
  front/src/modules/object-record/hooks/useFindManyRecords.ts
  front/src/modules/object-record/hooks/useObjectRecordBoard.1.ts
  front/src/modules/object-record/hooks/useObjectRecordBoard.ts
  front/src/modules/object-record/hooks/useObjectRecordTable.ts
  front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordSelect.tsx
  front/src/modules/object-record/relation-picker/hooks/useEntitySelectSearch.ts
  front/src/modules/object-record/select/hooks/useRecordsForSelect.ts
  front/src/modules/object-record/select/utils/getObjectOrderByField.ts
  front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
Labels: PR: awaiting author

#2873 input component ui docs
  docs/docs/contributor/frontend/ui-components/input/select.mdx
  docs/docs/contributor/frontend/ui-components/input/text-input.mdx
  docs/docs/contributor/frontend/ui-components/input/toggle.mdx
  docs/src/theme/icons.js
  docs/src/ui/SandpackEditor.js
  docs/src/ui/generated/index.d.ts
  docs/src/ui/generated/index.js
  docs/src/ui/input/components/selectCode.js
  docs/src/ui/input/components/textAreaCode.js
  docs/src/ui/input/components/textInputCode.js
  docs/src/ui/input/components/toggleCode.js
  front/src/modules/ui/input/components/Select.tsx
  front/src/modules/ui/input/components/TextInput.tsx
  front/tsup.ui.index.tsx
Labels: PR: awaiting author

#2872 Update Blocknote
  front/package.json
  front/src/modules/activities/components/ActivityBodyEditor.tsx
  front/src/modules/activities/components/ActivityEditor.tsx
  front/src/modules/activities/notes/components/NoteCard.tsx
  front/src/modules/ui/input/editor/components/BlockEditor.tsx
  front/yarn.lock
  server/src/database/typeorm-seeds/core/feature-flags.ts
Labels: PR: awaiting author

#2778 Add Keyboard navigation on IconPicker
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/command-menu/components/CommandMenuItem.tsx
  front/src/modules/command-menu/components/CommandMenuSelectableListEffect.tsx
  front/src/modules/command-menu/hooks/useCommandMenu.ts
  front/src/modules/ui/input/components/IconPicker.tsx
  front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListHotKeys.tsx
  front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListScopedStates.ts
  front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
  front/src/modules/ui/layout/selectable-list/states/selectableItemIdsScopedState.ts
  front/src/modules/ui/layout/selectable-list/states/selectableListOnEnterScopedState.ts
  front/src/modules/ui/layout/selectable-list/utils/internal/getSelectableListScopedStates.ts
  front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts
  front/src/utils/array/array-to-chunks.ts
Labels: PR: awaiting author

#2862 Spreadsheet import front module
  front/package.json
  front/src/modules/command-menu/components/CommandMenu.tsx
  front/src/modules/companies/hooks/useSpreadsheetCompanyImport.ts
  front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  front/src/modules/object-record/components/RecordTableContainer.tsx
  front/src/modules/object-record/hooks/useCreateManyRecords.ts
  front/src/modules/object-record/hooks/useGenerateCreateManyRecordMutation.ts
  front/src/modules/people/hooks/useSpreadsheetPersonImport.ts
  front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts
Labels: PR: awaiting review

#2940 feat: save Relation field description on creation
  packages/twenty-front/src/modules/object-metadata/utils/formatRelationMetadataInput.ts
Labels: PR: awaiting review

#2941 feat: add Settings/Accounts/Emails Emails Sync section with empty state
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsSyncSection.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
Labels: PR: awaiting review

#2953 feat: add Settings/Accounts Connected Accounts section accounts list
  packages/twenty-front/src/modules/accounts/types/account.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/AddObjectFilterFromDetailsButton.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmptyStateCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRow.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationCard.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldTypeCard.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectAboutSection.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx
  packages/twenty-front/src/modules/ui/input/button/components/LightButton.tsx
  packages/twenty-front/src/modules/ui/input/button/components/__stories__/LightButton.stories.tsx
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/Card.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/CardContent.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/CardFooter.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/CardHeader.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/__stories__/Card.stories.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
Labels: PR: awaiting review

#2908 Fix command menu keyboard navigation
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
Labels: PR: awaiting review

#2978 Fix Tsup setup to fuel docs with twenty-ui components
  packages/twenty-docs/src/ui/SandpackEditor.js
  packages/twenty-docs/src/ui/generated/index.cjs
  packages/twenty-docs/src/ui/generated/index.d.cts
  packages/twenty-docs/src/ui/generated/index.js
  packages/twenty-front/package.json
  packages/twenty-front/tsup.config.ts
  yarn.lock
Labels: PR: awaiting review

#2957 feat: add Settings/Accounts/Emails Emails Sync section accounts list
  packages/twenty-front/src/modules/accounts/types/Account.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsSyncSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRow.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRowDropdownMenu.tsx
  packages/twenty-front/src/modules/ui/display/icon/assets/gmail.svg
  packages/twenty-front/src/modules/ui/display/icon/assets/google-icon.svg
  packages/twenty-front/src/modules/ui/display/icon/assets/google.svg
  packages/twenty-front/src/modules/ui/display/icon/components/IconGmail.tsx
  packages/twenty-front/src/modules/ui/display/icon/components/IconGoogle.tsx
  packages/twenty-front/src/modules/ui/display/status/components/Status.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/__stories__/Card.stories.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
Labels: PR: awaiting review

#2954 2951-fix: Editing view filters button fix
  packages/twenty-front/src/modules/views/components/UpdateViewButtonGroup.tsx
Labels: PR: awaiting review

#2949 Use SelectableList in RelationPicker, SingleEntitySelectBase and MultipleEntitySelect
  packages/twenty-front/.eslintrc.cjs
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultipleEntitySelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectBase.tsx
  packages/twenty-front/src/modules/object-record/utils/turnFiltersIntoWhereClause.ts
  packages/twenty-front/src/modules/ui/layout/card/components/__stories__/Card.stories.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListHotKeys.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemMultiSelectAvatar.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  yarn.lock
Labels: PR: awaiting author

#2981 feat: redirect to Plan Required page if subscription status is not active
  packages/twenty-front/package.json
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/components/SubTitle.tsx
  packages/twenty-front/src/modules/auth/hooks/useOnboardingStatus.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/states/currentWorkspaceState.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProvider.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/billingState.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRow.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRowDropdownMenu.tsx
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/modules/types/PageHotkeyScope.ts
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemMultiSelectAvatar.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUser.ts
  packages/twenty-front/src/modules/workspace/graphql/mutations/updateWorkspace.ts
  packages/twenty-front/src/pages/auth/CreateWorkspace.tsx
  packages/twenty-front/src/pages/auth/PlanRequired.tsx
  packages/twenty-front/src/pages/auth/__stories__/PlanRequired.stories.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/client-config/client-config.entity.ts
  packages/twenty-server/src/core/client-config/client-config.resolver.ts
  packages/twenty-server/src/core/workspace/workspace.entity.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/workspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/core/workspaces.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1702479005171-addSubscriptionStatusOnWorkspace.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
Labels: PR: awaiting review

#2960 feat:added an empty page with the route: /settings/accounts/new.
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsNewAccount.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsNewAccount.stories.tsx
Labels: PR: awaiting review

#2911 On RecordTable, if I have no records, the Record Table Layout is not broken
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeader.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultipleEntitySelect.tsx
Labels: PR: awaiting author

#2997 Remaining UI docs
  packages/twenty-docs/docs/contributor/frontend/ui-components/input/block-editor.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/input/button.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/input/color-scheme.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/input/text.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/_category_.json
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/bread-crumb.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/link.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/menu-item.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/navigation-bar.mdx
  packages/twenty-docs/docs/contributor/frontend/ui-components/navigation/step-bar.mdx
  packages/twenty-docs/src/theme/icons.js
  packages/twenty-docs/src/ui/SandpackEditor.js
  packages/twenty-docs/src/ui/generated/index.cjs
  packages/twenty-docs/src/ui/generated/index.d.cts
  packages/twenty-docs/src/ui/input/blockEditorCode.js
  packages/twenty-docs/src/ui/navigation/breadCrumbCode.js
  packages/twenty-docs/src/ui/navigation/link/contactLinkCode.js
  packages/twenty-docs/src/ui/navigation/link/rawLinkCode.js
  packages/twenty-docs/src/ui/navigation/link/roundedLinkCode.js
  packages/twenty-docs/src/ui/navigation/link/socialLinkCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemCommandCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemDraggableCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemMultiSelectAvatarCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemMultiSelectCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemNavigateCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemSelectAvatarCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemSelectCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemSelectColorCode.js
  packages/twenty-docs/src/ui/navigation/menu-item/menuItemToggleCode.js
  packages/twenty-docs/src/ui/navigation/navBarCode.js
  packages/twenty-docs/src/ui/navigation/stepBarCode.js
  packages/twenty-front/tsup.ui.index.tsx
Labels: PR: awaiting review

#3004 Fix CIs
  .github/workflows/ci-docs.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  .github/workflows/ci-utils.yaml
  package.json
  packages/eslint-plugin-twenty/eslint-plugin-twenty.tgz
  packages/eslint-plugin-twenty/package.json
  packages/twenty-docs/docs/contributor/local-setup/yarn-setup.mdx
  packages/twenty-docs/src/ui/navigation/breadcrumbCode.js
  packages/twenty-front/package.json
  packages/twenty-server/src/core/open-api/open-api.service.spec.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/views.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/full-name.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/link.composite-type.ts
  packages/twenty-server/src/metadata/workspace-migration/standard-migrations.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.factory.ts
  packages/twenty-server/src/workspace/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/sync-metadata.util.ts
  packages/twenty-server/src/workspace/workspace.factory.ts
  packages/twenty-utils/yarn.lock
  packages/twenty-zapier/package.json
  packages/twenty-zapier/yarn.lock
  yarn.lock
Labels: PR: wip, PR: awaiting author

#3024 Disable Danger CI on push trigger
  .github/workflows/ci-utils.yaml
Labels: PR: awaiting review

#2962 feat: add Show Page Emails tab
  packages/twenty-front/src/modules/activities/emails/components/Emails.tsx
  packages/twenty-front/src/modules/ui/display/typography/components/H1Title.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/modules/workspace/hooks/useIsFeatureEnabled.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
Labels: PR: awaiting review

#2993 2880 timebox create a poc to fetch emails from the gmail api
  packages/twenty-server/src/core/auth/services/google-gmail.service.ts
  packages/twenty-server/src/workspace/messaging/commands/fetch-workspace-messages-commands.module.ts
  packages/twenty-server/src/workspace/messaging/commands/fetch-workspace-messages.command.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-batch-messages.service.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-workspace-messages.module.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-workspace-messages.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel.object-metadata.ts
Labels: PR: awaiting author

#2964 feat: add Show Page Emails preview
  packages/twenty-front/src/modules/activities/emails/components/EmailPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/Emails.tsx
  packages/twenty-front/src/modules/activities/emails/components/__stories__/Emails.stories.tsx
  packages/twenty-front/src/modules/activities/emails/types/email.ts
  packages/twenty-front/src/modules/users/components/Avatar.tsx
  packages/twenty-front/src/testing/mock-data/activities.ts
Labels: PR: awaiting review

#3020 2915 rest api documentation
  packages/twenty-docs/docs/developer/rest_api.mdx
  packages/twenty-docs/docs/user-guide/integrations/connect-zapier.mdx
  packages/twenty-docs/docusaurus.config.js
  packages/twenty-docs/package.json
  packages/twenty-docs/src/pages/graphql.tsx
  packages/twenty-docs/src/pages/rest-api.css
  packages/twenty-docs/src/pages/rest-api.tsx
  packages/twenty-docs/tsconfig.json
  packages/twenty-server/src/core/open-api/utils/base-schema.utils.ts
  yarn.lock
Labels: PR: awaiting author

#2987 2982-feat: Clear SelectableList reset scoped state
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
Labels: PR: awaiting author

#2986 Fix: keep the filter edition open if it is empty
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewFilters.ts
Labels: PR: awaiting review

#3045 GH-3028 Update filter key and JSON parse assignee selected filter on tasks page
  packages/twenty-front/src/modules/activities/tasks/hooks/useTasks.ts
  packages/twenty-front/src/pages/tasks/TasksEffect.tsx
Labels: PR: awaiting review

#3043 Fix documentation layout broken because of mixed rest api doc styles
  packages/twenty-docs/src/pages/rest-api.tsx
Labels: PR: awaiting review

#3037 feat: Add feature flags to Select & Rating custom fields
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/demo/feature-flags.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
Labels: PR: awaiting review

#3034 Fix tag border color Relations
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-front/src/modules/ui/theme/constants/tag.ts
Labels: PR: awaiting review

#3047 3035 improve rest api syntax
  packages/twenty-docs/docs/developer/rest_api.mdx
  packages/twenty-server/src/core/api-rest/api-rest-query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/core/api-rest/api-rest.controller.ts
  packages/twenty-server/src/core/api-rest/api-rest.controller.utils.spec.ts
  packages/twenty-server/src/core/api-rest/api-rest.controller.utils.ts
  packages/twenty-server/src/core/open-api/utils/responses.utils.ts
Labels: PR: awaiting review

#3023 Basic data enrichment
  packages/twenty-docs/docs/start/self-hosting/enviroment-variables.mdx
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-record/hooks/useExecuteQuickActionOnOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateExecuteQuickActionOnOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useRecordTableContextMenuEntries.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-server/package.json
  packages/twenty-server/src/core/analytics/analytics.module.ts
  packages/twenty-server/src/core/analytics/analytics.resolver.spec.ts
  packages/twenty-server/src/core/analytics/analytics.service.spec.ts
  packages/twenty-server/src/core/analytics/analytics.service.ts
  packages/twenty-server/src/core/api-rest/api-rest.module.ts
  packages/twenty-server/src/core/api-rest/api-rest.service.spec.ts
  packages/twenty-server/src/core/api-rest/api-rest.service.ts
  packages/twenty-server/src/core/auth/auth.module.ts
  packages/twenty-server/src/core/auth/services/auth.service.spec.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/quick-actions/intelligence.service.ts
  packages/twenty-server/src/core/quick-actions/interfaces/company.interface.ts
  packages/twenty-server/src/core/quick-actions/quick-actions.module.ts
  packages/twenty-server/src/core/quick-actions/quick-actions.service.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/utils/email-providers.ts
  packages/twenty-server/src/utils/image.ts
  packages/twenty-server/src/utils/is-work-email.ts
  packages/twenty-server/src/workspace/utils/__tests__/get-resolver-name.spec.ts
  packages/twenty-server/src/workspace/utils/get-resolver-name.util.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/people-demo.ts
  packages/twenty-server/src/workspace/workspace-query-builder/workspace-query-builder.module.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/execute-quick-action-on-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/factories.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/workspace-resolver-builder.module.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/workspace-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/utils/__tests__/get-resolver-args.spec.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/utils/get-resolver-args.util.ts
  yarn.lock
Labels: PR: wip, PR: awaiting author

#2985 2980-Fix: CommandGroup background
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemCommand.tsx
  packages/twenty-front/src/modules/ui/theme/constants/boxShadow.ts
Labels: PR: awaiting review

#3000 feat: add Settings/Accounts/New section with empty state
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmptyStateCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsNewAccountSection.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsNewAccount.tsx
Labels: PR: awaiting review

#3079 fix: add dark mode version of Settings Object cover image
  packages/twenty-front/src/modules/settings/data-model/assets/cover-dark.png
  packages/twenty-front/src/modules/settings/data-model/assets/cover-light.png
  packages/twenty-front/src/modules/settings/data-model/assets/cover.png
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx
Labels: PR: awaiting review

#3081 fix: fix Relation field form select labels display
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
Labels: PR: awaiting review

#3062 fix: hide disabled fields in Show Page
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/object-record/utils/filterAvailableFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/utils/isFieldMetadataItemAvailable.ts
Labels: PR: awaiting review

#2988 2973-feat: Skeleton Loading Added
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/ui/layout/page/ShowPageContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: PR: awaiting author

#3065 2914 graphql api documentation
  packages/twenty-docs/src/components/playground.tsx
  packages/twenty-docs/src/components/token-form.css
  packages/twenty-docs/src/components/token-form.tsx
  packages/twenty-docs/src/pages/graphql.tsx
  packages/twenty-docs/src/pages/rest-api.tsx
  packages/twenty-server/src/core/open-api/open-api.service.ts
  packages/twenty-server/src/core/open-api/utils/base-schema.utils.ts
  packages/twenty-server/src/core/open-api/utils/components.utils.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
Labels: PR: awaiting review

#3074 fix: sentry doesn't catch exceptions from flexible backend
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/filters/global-exception.filter.ts
  packages/twenty-server/src/filters/http-exception.filter.ts
  packages/twenty-server/src/filters/typeorm-exception.filter.ts
  packages/twenty-server/src/filters/utils/global-exception-handler.util.ts
  packages/twenty-server/src/graphql-config.service.ts
Labels: PR: awaiting review

#3040 fix: empty state should not appear during table loading
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBodyFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/states/isFetchingRecordTableDataState.ts
  packages/twenty-front/src/modules/object-record/record-table/states/isRecordTableInitialLoadingState.ts
Labels: PR: awaiting review

#3068 feat(workspace-resolver): prevent deletion of demo workspaces (#2207)
  packages/twenty-server/src/core/user/user.resolver.ts
  packages/twenty-server/src/core/workspace/workspace.resolver.ts
Labels: PR: awaiting review

#3044 Upload image for use in blocknote editor
  packages/twenty-front/src/modules/activities/components/ActivityBodyEditor.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/files/utils/downloadFile.ts
  packages/twenty-front/src/modules/activities/notes/components/NoteCard.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/activities/utils/__tests__/getActivityPreview.test.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/getActivitySummary.test.ts
  packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts
  packages/twenty-front/src/modules/activities/utils/getActivitySummary.ts
  packages/twenty-server/.gitignore
Labels: PR: awaiting review

#3064 feat: add Settings/Accounts/Emails/Inbox Settings page
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
Labels: PR: awaiting review

#3071 feat: add Settings/Accounts/Emails/Inbox Settings synchronization sec…
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsCardMedia.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsSynchronizationSection.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
Labels: blocked: conflict/dependency

#3077 feat: add Settings/Accounts/Emails/Inbox Settings visibility section
  packages/twenty-front/src/modules/accounts/types/Account.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsCardMedia.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsVisibilitySection.tsx
  packages/twenty-front/src/modules/ui/input/components/Radio.tsx
  packages/twenty-front/src/modules/ui/input/components/__stories__/Radio.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
Labels: PR: awaiting review, blocked: conflict/dependency

#3085 Fix and enhance storybook:pages tests
  .github/workflows/ci-front.yaml
  Users/v1b3m/Dev/GitStart/client-twenty/packages/twenty-front/src/testing/decorators/ObjectMetadataItemsDecorator.tsx
  packages/twenty-front/src/__stories__/App.stories.tsx
  packages/twenty-front/src/modules/activities/types/Activity.ts
  packages/twenty-front/src/modules/auth/states/currentWorkspaceMemberState.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/companies/types/Company.ts
  packages/twenty-front/src/modules/pipeline/types/PipelineStep.ts
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  packages/twenty-front/src/modules/workspace-member/types/WorkspaceMember.ts
  packages/twenty-front/src/pages/auth/PlanRequired.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateProfile.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateWorkspace.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PlanRequired.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/pages/opportunities/__stories__/Opportunities.stories.tsx
  packages/twenty-front/src/testing/decorators/ObjectMetadataItemsDecorator.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/activities.ts
  packages/twenty-front/src/testing/mock-data/companies.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/testing/mock-data/pipeline-steps.ts
  packages/twenty-front/src/testing/mock-data/users.ts
Labels: PR: awaiting review

#3063 fix: display label identifier field input in Show Page
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/isLabelIdentifierField.ts
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/object-record/components/RecordTableEffect.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/input/components/FullNameFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldActiveActionDropdown.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
Labels: PR: awaiting review

#3076 Feat/record optimistic effect
  packages/twenty-front/src/modules/activities/tasks/hooks/useCompleteTask.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/states/optimisticEffectState.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/OptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/OptimisticEffectResolver.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/internal/OptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/computeOptimisticEffectKey.ts
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateEmptyRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordBoard.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordTable.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-filter/types/ObjectRecordQueryFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingBooleanFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingBooleanFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingDateFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingDateFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingFloatFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingFloatFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingUUIDFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingUUIDFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordQueryVariables.ts
  packages/twenty-front/src/modules/views/components/ViewBarFilterEffect.tsx
  packages/twenty-front/src/testing/mock-data/objectMetadataItems.ts
  packages/twenty-front/src/utils/isAnObject.ts
  packages/twenty-front/src/utils/isEmptyObject.ts
Labels: PR: awaiting review

#3093 Update new/edit object according to figma
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFormSection.tsx
  packages/twenty-front/src/modules/settings/data-model/new-object/components/SettingsNewObjectType.tsx
  packages/twenty-front/src/modules/settings/data-model/new-object/components/SettingsObjectTypeCard.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsNewObject.stories.tsx
Labels: PR: awaiting review

#3097 Refactor recoil scope states
  packages/twenty-front/src/modules/command-menu/components/CommandMenuItem.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/getRecordBoardScopedStates.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/utils/getRecordTableScopedStates.ts
  packages/twenty-front/src/modules/object-record/relation-picker/components/SelectableMenuItemSelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/utils/getRelationPickerScopedStates.ts
  packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableItem.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListHotKeys.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListScopedState.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListScopedStates.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/states/selectors/isSelectedItemIdScopedFamilySelector.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/utils/internal/getSelectableListScopeInjectors.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/utils/internal/getSelectableListScopedStates.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/scopes-internal/hooks/useScopedState.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/createScopedFamilySelector.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getFamilyScopeInjector.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getScopeInjector.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getScopedFamilyStateDeprecated.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getScopedSelectorDeprecated.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getScopedStateDeprecated.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getSnapshotScopedSelector.ts
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/utils/getSnapshotScopedValue.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViewScopedStates.ts
  packages/twenty-front/src/modules/views/utils/getViewScopedStateValuesFromSnapshot.ts
  packages/twenty-front/src/modules/views/utils/getViewScopedStatesFromSnapshot.ts
  packages/twenty-front/src/modules/views/utils/internal/getViewScopedStates.ts
Labels: PR: awaiting review

#3092 2929 fetch emails from backend and display them in the UI
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/emails/components/Emails.tsx
  packages/twenty-front/src/modules/activities/emails/components/ThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/Threads.tsx
  packages/twenty-front/src/modules/activities/emails/components/__stories__/Emails.stories.tsx
  packages/twenty-front/src/modules/activities/emails/components/__stories__/Threads.stories.tsx
  packages/twenty-front/src/modules/activities/emails/queries/getTimelineThreadsFromCompanyId.ts
  packages/twenty-front/src/modules/activities/emails/queries/getTimelineThreadsFromPersonId.ts
  packages/twenty-front/src/modules/activities/emails/types/email.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/testing/mock-data/activities.ts
  packages/twenty-server/src/core/core.module.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.module.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.resolver.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.service.ts
Labels: PR: awaiting review

#3088 fix: composite type migrations not well formatted
  packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/full-name.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/link.composite-type.ts
Labels: PR: awaiting author

#3041 fix: On Sign Out > Sign In, States are not loaded properly
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
Labels: PR: awaiting author

#3111 GH-2829 Add Sentry on frontend
  packages/twenty-front/package.json
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProvider.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/sentryConfigState.ts
  packages/twenty-front/src/modules/error-handler/components/ExceptionHandlerProvider.tsx
  packages/twenty-front/src/modules/error-handler/components/SentryInitiEffect.tsx
  packages/twenty-server/src/core/client-config/client-config.entity.ts
  packages/twenty-server/src/core/client-config/client-config.resolver.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/integrations/message-queue/utils/get-job-class-name.util.ts
  yarn.lock
Labels: PR: awaiting review

#3112 3019 timebox add typing and checks in workspacemessagingservices
  packages/twenty-server/src/workspace/messaging/commands/fetch-workspace-messages.command.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-batch-messages.service.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-workspace-messages.service.ts
  packages/twenty-server/src/workspace/messaging/types/gmailMessage.ts
  packages/twenty-server/src/workspace/messaging/types/gmailParsedResponse.ts
  packages/twenty-server/src/workspace/messaging/types/messageQuery.ts
Labels: PR: awaiting review

#3145 feat: add email blocklist section with mocked data
  packages/twenty-front/src/modules/accounts/types/BlockedEmail.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistInput.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistTable.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistTableRow.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
  packages/twenty-front/src/utils/date-utils.ts
Labels: PR: awaiting author

#3165 fix: fix disabled Button and IconButton primary accents background co…
  packages/twenty-front/src/modules/ui/input/button/components/Button.tsx
  packages/twenty-front/src/modules/ui/input/button/components/IconButton.tsx
Labels: PR: awaiting review

#3170 Replace all hardcoded core object name by enum
  packages/twenty-front/src/modules/activities/components/ActivityBodyEditor.tsx
  packages/twenty-front/src/modules/activities/components/ActivityComments.tsx
  packages/twenty-front/src/modules/activities/components/ActivityEditor.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/files/components/Attachments.tsx
  packages/twenty-front/src/modules/activities/files/hooks/useAttachments.tsx
  packages/twenty-front/src/modules/activities/hooks/useHandleCheckableActivityTargetChange.ts
  packages/twenty-front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditMode.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/activities/notes/hooks/useNotes.ts
  packages/twenty-front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
  packages/twenty-front/src/modules/activities/right-drawer/components/RightDrawerActivity.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/activities/tasks/hooks/useCompleteTask.ts
  packages/twenty-front/src/modules/activities/tasks/hooks/useCurrentUserDueTaskCount.ts
  packages/twenty-front/src/modules/activities/tasks/hooks/useTasks.ts
  packages/twenty-front/src/modules/activities/timeline/components/Timeline.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/companies/components/AddPersonToCompany.tsx
  packages/twenty-front/src/modules/companies/components/CompanyBoardCard.tsx
  packages/twenty-front/src/modules/companies/components/CompanyTeam.tsx
  packages/twenty-front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  packages/twenty-front/src/modules/companies/components/NewOpportunityButton.tsx
  packages/twenty-front/src/modules/companies/components/OpportunityPicker.tsx
  packages/twenty-front/src/modules/companies/hooks/useSpreadsheetCompanyImport.ts
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordBoard.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/useCreateOpportunity.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/useDeleteSelectedRecordBoardCardsInternal.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/useRecordBoardColumnsInternal.ts
  packages/twenty-front/src/modules/people/components/PeopleCard.tsx
  packages/twenty-front/src/modules/people/hooks/useSpreadsheetPersonImport.ts
  packages/twenty-front/src/modules/pipeline/hooks/usePipelineSteps.ts
  packages/twenty-front/src/modules/settings/data-model/hooks/useRelationFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/profile/components/NameFields.tsx
  packages/twenty-front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
  packages/twenty-front/src/modules/ui/theme/hooks/useColorScheme.ts
  packages/twenty-front/src/modules/views/components/ViewBarEffect.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewFields.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViewFilters.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViewSorts.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViews.ts
  packages/twenty-front/src/pages/auth/CreateProfile.tsx
  packages/twenty-front/src/pages/opportunities/Opportunities.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeys.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
Labels: PR: awaiting author

#3154 Added a clear/reset button in InternalDateInput to reset/unschedule events
  packages/twenty-front/src/modules/activities/components/ActivityEditor.tsx
  packages/twenty-front/src/modules/object-record/field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/field/contexts/FieldContext.ts
  packages/twenty-front/src/modules/object-record/field/meta-types/hooks/useDateTimeField.ts
  packages/twenty-front/src/modules/object-record/field/meta-types/input/components/DateFieldInput.tsx
  packages/twenty-front/src/modules/object-record/field/types/guards/isFieldDateTimeValue.ts
  packages/twenty-front/src/modules/object-record/hooks/useFieldContext.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownDateSearchInput.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
Labels: PR: awaiting author
