Repository twentyhq/twenty, pull requests merged in 2024-04, with the labels that each got.

#4722 fix: fix Settings/Developers page error
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/Table.tsx
Labels: PR: awaiting review

#4706 chore: upgrade Nx to v18.1.3
  .eslintrc.js
  .github/workflows/ci-front.yaml
  .nx/nxw.js
  nx.json
  package.json
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/apollo/utils/index.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSectionHeader.tsx
  packages/twenty-front/src/modules/settings/developers/utils/format-expiration.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
  packages/twenty-front/src/utils/date-utils.ts
  packages/twenty-server/package.json
  tools/eslint-rules/project.json
  yarn.lock
Labels: PR: awaiting review

#4570 feat: expand relation record cards on click in Record Show page
  packages/twenty-front/src/modules/object-record/hooks/useLazyFindOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRecordsList.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsList.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/utils/isFieldCellSupported.ts
  packages/twenty-front/src/modules/object-record/utils/isFieldMetadataItemAvailable.ts
Labels: PR: awaiting review

#4740 Add JsDom to server dependencies
  packages/twenty-front/nyc.config.cjs
  packages/twenty-server/package.json
  yarn.lock
Labels: PR: awaiting review

#4338 New field currency
  packages/twenty-front/src/modules/apollo/components/ApolloProvider.tsx
  packages/twenty-front/src/modules/object-metadata/components/ApolloMetadataClientProvider.tsx
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordNodeFromRecord.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/CurrencyFieldDisplay.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldCurrencyForm.tsx
  packages/twenty-front/src/modules/ui/field/display/components/CurrencyDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/EllipsisDisplay.tsx
  packages/twenty-front/src/modules/views/hooks/useGetViewFromCache.ts
  packages/twenty-front/src/utils/format/__tests__/amountFormat.test.ts
  packages/twenty-front/src/utils/format/amountFormat.ts
  packages/twenty-front/src/utils/format/formatAmount.ts
  packages/twenty-front/src/utils/string/lowerAndCapitalize.ts
Labels: PR: awaiting review

#4780 [feat] Enable deletion of custom fields in workspace
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/delete-field.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/before-delete-one-field.hook.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/dtos/relation-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/hooks/before-delete-one-relation.hook.ts
Labels: PR: awaiting review

#4730 feat: init docker compose test
  .github/workflows/ci-chromatic.yaml
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-docs.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  .github/workflows/ci-test-docker-compose.yaml
Labels: PR: awaiting author

#3901 3886 - Shortcut Sort/Filter
  packages/twenty-front/src/modules/object-metadata/hooks/useColumnDefinitionsFromFieldMetadata.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/constants/ObjectSortDropdownId.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/hooks/useObjectSortDropdown.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/states/isSortDirectionMenuUnfoldedState.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/states/selectedSortDirectionState.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleColumnFilter.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleColumnSort.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableColumnDropdownMenu.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useRecordTableStates.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/states/onToggleColumnFilterComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/states/onToggleColumnSortComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/types/ColumnDefinition.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useDropdownV2.ts
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting author

#4787 feat: add Settings/Integrations/Database/New Connection form
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionForm.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
Labels: PR: awaiting review

#4312 fix: linked records redirection
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/views/components/UpdateViewButtonGroup.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewFromQueryParams.ts
Labels: PR: awaiting author

#4705 chore: use common eslint config for most packages
  .eslintrc.cjs
  .eslintrc.react.cjs
  .gitignore
  package.json
  packages/twenty-chrome-extension/.eslintrc.cjs
  packages/twenty-chrome-extension/src/utils/requestDb.ts
  packages/twenty-emails/.eslintrc.cjs
  packages/twenty-emails/.eslintrc.json
  packages/twenty-front/.eslintrc.cjs
  packages/twenty-front/public/manifest.json
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchSelectedItemsQuery.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/__tests__/settingsCreateObjectInputSchema.test.ts
  packages/twenty-front/src/modules/ui/input/states/iconPickerState.ts
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/AnimatedPlaceholder.tsx
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar.test.tsx
  packages/twenty-front/src/modules/views/hooks/useHandleViews.ts
  packages/twenty-front/tsconfig.json
  packages/twenty-ui/.eslintrc.cjs
  packages/twenty-ui/.eslintrc.json
  packages/twenty-ui/.gitignore
  packages/twenty-ui/project.json
  packages/twenty-ui/tsconfig.lib.json
  packages/twenty-ui/tsconfig.spec.json
  packages/twenty-ui/tsconfig.storybook.json
  packages/twenty-website/.eslintrc.js
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebarSection.tsx
  yarn.lock
Labels: PR: awaiting review

#4707 chore: add script to generate twenty-ui barrels before build
  packages/twenty-ui/package.json
  packages/twenty-ui/project.json
  packages/twenty-ui/scripts/generateBarrels.ts
  packages/twenty-ui/src/components/index.ts
  packages/twenty-ui/src/index.ts
  packages/twenty-ui/src/testing/index.ts
  packages/twenty-ui/src/theme/index.ts
  packages/twenty-ui/src/theme/types/ThemeType.ts
  packages/twenty-ui/tsconfig.json
Labels: PR: awaiting review

#4800 Fix View creation, view fields re-ordering, view filters and view sorts erratic behaviors
  packages/twenty-front/src/modules/views/hooks/useGetViewFromCache.ts
Labels: PR: awaiting review

#4676 fix: Add `isIconStatic` prop item to allow the icons to be always rendered statically ignoring hover behaviour
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
Labels: PR: awaiting author

#4784 Remote objects: Fix comment override - id typing - label
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/create-object.input.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-workspace-migrations-for-custom-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-workspace-migrations-for-remote-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/utils/camel-to-title-case.ts
Labels: PR: awaiting review

#4804 Prevent remote object updates
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFilteredObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPageHeader.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/assert-mutation-not-on-remote-object.util.ts
Labels: PR: awaiting review

#4792 adjust window size for scroll
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
Labels: PR: awaiting review

#4791 feat: add Database Connection Summary Card to Settings/Integrations/D…
  packages/twenty-front/src/modules/settings/components/SettingsSummaryCard.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectSummaryCard.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectedTablesStatus.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionsListCard.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnectionSummaryCard.tsx
Labels: PR: awaiting author

#4812 Gracefully close Redis connection when cacheStorageModule is destroyed
  packages/twenty-server/src/engine/integrations/cache-storage/cache-storage.module.ts
Labels: PR: awaiting review

#4813 feat: fetch database connections
  packages/twenty-front/codegen-metadata.cjs
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/databases/graphql/queries/findManyDatabaseConnections.ts
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnections.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionForm.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionsListCard.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabase.tsx
  packages/twenty-front/src/testing/mock-data/objectMetadataItems.ts
Labels: PR: awaiting review

#4816 chore: enable no-console eslint rule for tests and stories
  packages/twenty-chrome-extension/.eslintrc-ci.cjs
  packages/twenty-front/.eslintrc-ci.cjs
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/favorites/hooks/__tests__/useFavorites.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/__tests__/useFilterDropdown.test.tsx
  packages/twenty-front/src/modules/ui/layout/draggable-list/__stories__/DraggableList.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItem.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemDraggable.stories.tsx
  packages/twenty-front/src/modules/ui/utilities/recoil-scope/scopes-internal/hooks/__tests__/useAvailableScopeId.test.tsx
Labels: PR: awaiting review

#4697 feat: traditional Oauth alongside PKCE
  packages/twenty-server/src/engine/core-modules/app-token/app-token.entity.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/authorize-app.input.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/exchange-auth-code.input.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.ts
Labels: PR: awaiting author

#4837 Add new database connection
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/databases/graphql/mutations/createOneDatabaseConnection.ts
  packages/twenty-front/src/modules/databases/hooks/useCreateOneDatabaseConnection.ts
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnections.ts
  packages/twenty-front/src/modules/databases/utils/getForeignDataWrapperType.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionForm.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
Labels: PR: awaiting review

#4851 feat: add Tables settings to Settings/Integrations/Database/Connectio…
  packages/twenty-front/src/modules/settings/components/SettingsListCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListItemCardContent.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseTablesListCard.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnection.tsx
  packages/twenty-front/src/testing/mock-data/remoteObjectDatabases.ts
Labels: PR: awaiting review

#4814 refactor(chore):3896-replace-lodash-debounce-to-useDebounce
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultipleObjectRecordSelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useEntitySelectSearch.ts
  packages/twenty-front/src/modules/settings/profile/components/NameFields.tsx
  packages/twenty-front/src/modules/settings/workspace/components/NameField.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx
Labels: PR: awaiting review

#4874 feat: add Remove menu option to Settings/Integrations/Database/Connec…
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnectionSummaryCard.tsx
Labels: PR: awaiting review

#4877 Use migrations for remote tables
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table-input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-postgres-table/remote-postgres-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-postgres-table/remote-postgres-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/types/remote-table-column.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/types/remote-table.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: PR: awaiting author

#4819 feat: sync command missing ability to rename standard object
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-workspace-migrations-for-custom-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-workspace-migrations-for-remote-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-field.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-object.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-relation.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/comparator.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/storage/workspace-sync.storage.ts
Labels: PR: awaiting author

#4822 4710 implement google calendar incremental sync
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/modules/calendar/commands/google-calendar-sync.command.ts
  packages/twenty-server/src/modules/calendar/commands/start-google-calendar-sync.cron.command.ts
  packages/twenty-server/src/modules/calendar/commands/workspace-calendar-sync-commands.module.ts
  packages/twenty-server/src/modules/calendar/jobs/crons/google-calendar-sync.cron.job.ts
  packages/twenty-server/src/modules/calendar/jobs/crons/pattern/google-calendar-sync.cron.pattern.ts
  packages/twenty-server/src/modules/calendar/jobs/google-calendar-sync.job.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-channel.repository.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-event-participant.repository.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-event.repository.ts
  packages/twenty-server/src/modules/calendar/services/google-calendar-sync.module.ts
  packages/twenty-server/src/modules/calendar/services/google-calendar-sync.service.ts
  packages/twenty-server/src/modules/calendar/utils/format-google-calendar-event.util.ts
  packages/twenty-server/src/modules/calendar/utils/google-calendar-search-filter.util.ts
  packages/twenty-server/src/modules/messaging/commands/messaging-command.module.ts
  packages/twenty-server/src/modules/messaging/jobs/crons/fetch-all-messages-from-cache.cron.job.ts
  packages/twenty-server/src/modules/messaging/jobs/crons/gmail-fetch-messages-from-cache.cron.command.ts
  packages/twenty-server/src/modules/messaging/jobs/crons/gmail-partial-sync.cron.command.ts
  packages/twenty-server/src/modules/messaging/jobs/crons/patterns/fetch-all-workspaces-messages.cron.pattern.ts
Labels: PR: awaiting review

#4909 4902 bug fix fix api filter for enum
  packages/twenty-server/src/engine/api/__mocks__/object-metadata-item.mock.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/factories/input-factories/filter-utils/__tests__/check-filter-enum-values.spec.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/factories/input-factories/filter-utils/check-filter-enum-values.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/factories/input-factories/filter-utils/parse-filter.utils.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/utils/fields.utils.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
Labels: PR: awaiting author

#4853 [feat][FE] Stop persisting new empty records
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/DateFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/EmailFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/NumberFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/TextFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/AddressFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/BooleanFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RatingFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTablePendingRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useRecordTableStates.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useUpsertRecord.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useCloseRecordTableCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useUpsertRecord.ts
  packages/twenty-front/src/modules/object-record/record-table/states/recordTablePendingRecordIdComponentState.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: PR: awaiting review

#4894 Sync table from frontend
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/databases/graphql/fragments/remoteTableFragment.ts
  packages/twenty-front/src/modules/databases/graphql/mutations/syncRemoteTable.ts
  packages/twenty-front/src/modules/databases/graphql/mutations/unsyncRemoteTable.ts
  packages/twenty-front/src/modules/databases/graphql/queries/findManyDatabaseConnectionTables.ts
  packages/twenty-front/src/modules/databases/graphql/queries/findManyRemoteTables.ts
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnectionTables.ts
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTable.ts
  packages/twenty-front/src/modules/databases/hooks/useUnsyncRemoteTable.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseTablesListCard.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationRemoteTableSyncStatusToggle.tsx
  packages/twenty-front/src/modules/ui/input/components/Toggle.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabaseConnection.tsx
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table-input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-postgres-table/remote-postgres-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
Labels: PR: awaiting author

#4887 4778 multi select field front implement multi select type
  packages/twenty-front/src/modules/auth/services/AuthService.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/formatFieldMetadataItemInput.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatRelationMetadataInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordFromRecordNode.ts
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordNodeFromRecord.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/FilterType.ts
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/MultiSelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useMultiSelectField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldMultiSelect.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldMultiSelectValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/multiSelectFieldValueSchema.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemMultiSelectTag.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/workspace-migration-enum.service.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting author

#4911 Use defaultValue in currency input
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-metadata/utils/getDefaultValueForBackend.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useCurrencyField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/CurrencyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockColumnDefinitions.ts
  packages/twenty-front/src/modules/ui/field/input/components/CurrencyInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/currency/components/CurrencyPickerDropdownButton.tsx
  packages/twenty-front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/validate-default-value-based-on-type.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-default-value-for-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-field-metadata-default-value.validator.ts
Labels: PR: awaiting author

#4912 feat: add SENTRY_RELEASE env
  .github/workflows/ci-test-docker-compose.yaml
  packages/twenty-docker/twenty/Dockerfile
  packages/twenty-front/scripts/inject-runtime-env.sh
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/error-handler/components/SentryInitiEffect.tsx
  packages/twenty-front/vite.config.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/exception-handler/drivers/sentry.driver.ts
  packages/twenty-server/src/engine/integrations/exception-handler/exception-handler.module-factory.ts
  packages/twenty-server/src/engine/integrations/exception-handler/interfaces/exception-handler.interface.ts
Labels: PR: awaiting author

#4920 [calendar/messaging] fix connected account auth failed should skip sync
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/save-connected-account.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/update-connected-account.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-channel.repository.ts
  packages/twenty-server/src/modules/connected-account/repositories/connected-account.repository.ts
  packages/twenty-server/src/modules/connected-account/services/google-api-refresh-access-token/google-api-refresh-access-token.service.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/modules/messaging/repositories/message-channel.repository.ts
  packages/twenty-server/src/modules/messaging/services/gmail-fetch-message-content-from-cache/gmail-fetch-message-content-from-cache.service.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message-channel.object-metadata.ts
Labels: PR: awaiting author

#4921 Fix remote object read-only + remove relations
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTable.ts
  packages/twenty-front/src/modules/databases/hooks/useUnsyncRemoteTable.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-record/record-action-bar/hooks/useRecordActionBar.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCell.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectSummaryCard.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelIsCustomTag.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelObjectSummary.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelObjectTypeTag.tsx
  packages/twenty-front/src/modules/settings/data-model/utils/getObjectTypeLabel.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseTablesListCard.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-workspace-migrations-for-custom-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-workspace-migrations-for-remote-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
Labels: PR: awaiting author

#4767 Make <Background /> component responsive
  packages/twenty-website/src/app/_components/contributors/AvatarGrid.tsx
  packages/twenty-website/src/app/_components/oss-friends/Background.tsx
  packages/twenty-website/src/app/contributors/[slug]/page.tsx
  packages/twenty-website/src/app/contributors/page.tsx
  packages/twenty-website/src/app/oss-friends/page.tsx
Labels: PR: awaiting author, website

#4919 fixed react-error with mdx on mobile
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/releases/get-releases.tsx
  packages/twenty-website/src/app/releases/page.tsx
Labels: PR: awaiting review, website

#4931 Added loader and counter animations
  packages/twenty-website/src/app/_components/contributors/AnimatedFigures.tsx
  packages/twenty-website/src/app/_components/contributors/AvatarGrid.tsx
  packages/twenty-website/src/app/_components/contributors/ContentContainer.tsx
  packages/twenty-website/src/app/_components/contributors/ProfileInfo.tsx
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/_components/ui/layout/LoaderAnimation.tsx
Labels: website

#4896 4810 display participants in the right drawer of the calendar event
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventDetails.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventParticipantsResponseStatus.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventParticipantsResponseStatusField.tsx
  packages/twenty-front/src/modules/activities/calendar/right-drawer/components/RightDrawerCalendarEvent.tsx
  packages/twenty-front/src/modules/activities/calendar/types/CalendarEvent.ts
  packages/twenty-front/src/modules/activities/calendar/types/CalendarEventParticipant.ts
  packages/twenty-front/src/modules/activities/components/ParticipantChip.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageSender.tsx
  packages/twenty-front/src/modules/ui/display/expandable-list/ExpandableList.tsx
  packages/twenty-front/src/modules/ui/display/expandable-list/IntersectionObserverWrapper.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/testing/mock-data/calendar.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/modules/calendar/types/calendar-event.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting review

#4933 Fix cron module structure
  packages/twenty-server/src/command/command.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/modules/calendar/commands/calendar-commands.module.ts
  packages/twenty-server/src/modules/calendar/crons/commands/calendar-cron-commands.module.ts
  packages/twenty-server/src/modules/calendar/crons/commands/google-calendar-sync.cron.command.ts
  packages/twenty-server/src/modules/calendar/crons/jobs/google-calendar-sync.cron.job.ts
  packages/twenty-server/src/modules/calendar/jobs/crons/pattern/google-calendar-sync.cron.pattern.ts
  packages/twenty-server/src/modules/messaging/crons/commands/gmail-fetch-messages-from-cache.cron.command.ts
  packages/twenty-server/src/modules/messaging/crons/commands/gmail-partial-sync.cron.command.ts
  packages/twenty-server/src/modules/messaging/crons/commands/messaging-cron-commands.module.ts
  packages/twenty-server/src/modules/messaging/crons/jobs/gmail-fetch-messages-from-cache.cron.job.ts
  packages/twenty-server/src/modules/messaging/crons/jobs/gmail-partial-sync.cron.job.ts
  packages/twenty-server/src/modules/messaging/jobs/crons/patterns/fetch-all-workspaces-messages.cron.pattern.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-full-sync.job.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-partial-sync.job.ts
  packages/twenty-server/src/modules/messaging/services/gmail-fetch-message-content-from-cache/gmail-fetch-message-content-from-cache.service.ts
  packages/twenty-server/src/modules/messaging/services/gmail-partial-sync-v2/gmail-partial-sync-v2.service.ts
Labels: PR: awaiting review

#4898 Added isAuditLogged column to object-metadata-entity
  packages/twenty-server/src/database/typeorm/metadata/migrations/1712923480448-addIsAuditLogged.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/object-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/decorators/is-not-audit-logged.decorator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/decorators/object-metadata.decorator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/reflect-object-metadata.interface.ts
  packages/twenty-server/src/modules/event/standard-objects/event.object-metadata.ts
  packages/twenty-server/src/utils/typed-reflect.ts
Labels: PR: awaiting author

#4863 Compile with swc on twenty-server
  package.json
  packages/twenty-server/.swcrc
  packages/twenty-server/@types/common.d.ts
  packages/twenty-server/nest-cli.json
  packages/twenty-server/project.json
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/relation-field-alias.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/input-type-definition.factory.ts
  packages/twenty-server/src/engine/core-modules/app-token/app-token.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/relation-definition.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/companies-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/company.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/people-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/person.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/relation.interface.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity-target.object-metadata.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity.object-metadata.ts
  packages/twenty-server/src/modules/activity/standard-objects/comment.object-metadata.ts
  packages/twenty-server/src/modules/attachment/standard-objects/attachment.object-metadata.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-channel-event-association.object-metadata.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-event-participant.object-metadata.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/modules/company/standard-objects/company.object-metadata.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/blocklist.object-metadata.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/modules/event/standard-objects/event.object-metadata.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.object-metadata.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message-channel-message-association.object-metadata.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message-channel.object-metadata.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message-participant.object-metadata.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message-thread.object-metadata.ts
  packages/twenty-server/src/modules/messaging/standard-objects/message.object-metadata.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.object-metadata.ts
  packages/twenty-server/src/modules/person/standard-objects/person.object-metadata.ts
  packages/twenty-server/src/modules/view/standard-objects/view-filter.object-metadata.ts
  packages/twenty-server/src/modules/view/standard-objects/view-sort.object-metadata.ts
  packages/twenty-server/src/modules/view/standard-objects/view.object-metadata.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.object-metadata.ts
  packages/twenty-server/src/utils/generate-front-config.ts
  yarn.lock
Labels: PR: awaiting review

#4949 feat: add sourcemap generation for front
  packages/twenty-front/package.json
  packages/twenty-front/vite.config.ts
Labels: PR: awaiting author

#4947 chore: add incremental typecheck to twenty-ui
  .github/workflows/ci-front.yaml
  .gitignore
  packages/twenty-ui/project.json
  packages/twenty-ui/tsconfig.json
  packages/twenty-ui/tsconfig.lib.json
  packages/twenty-ui/tsconfig.spec.json
  packages/twenty-ui/tsconfig.storybook.json
Labels: PR: awaiting review

#4939 Add connection failed status
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnectionTables.ts
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseConnectionSyncStatus.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPageHeader.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/get-remote-table-local-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/validate-remote-server-input.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-ui/src/display/chip/components/EntityChip.tsx
Labels: PR: awaiting review

#4908 feat: Improved Page and History names
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/pages/not-found/NotFound.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/utils/__tests__/title-utils.test.ts
  packages/twenty-front/src/utils/title-utils.ts
Labels: PR: awaiting review

#4662 fix: record object chip background color when idle (not hovered)
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
Labels: PR: awaiting review

#4966 4501 improve filters for emails imports
  packages/twenty-server/src/modules/messaging/utils/gmail-search-filter.util.ts
  packages/twenty-server/src/modules/messaging/utils/is-person-email.util.ts
Labels: PR: awaiting review

#4967 Seed calendar events
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-channel-event-association.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-channel.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-event-participants.ts
Labels: PR: awaiting review

#4973 [message-queue] Add job auto-removal
  packages/twenty-server/src/engine/integrations/message-queue/drivers/bullmq.driver.ts
Labels: PR: awaiting review

#4965 Fix Never api key expiration dates
  packages/twenty-front/src/modules/settings/developers/constants/ExpirationDates.ts
  packages/twenty-front/src/modules/settings/developers/constants/NeverExpireDeltaInYears.ts
  packages/twenty-front/src/modules/settings/developers/utils/__tests__/format-expiration.test.ts
  packages/twenty-front/src/modules/settings/developers/utils/format-expiration.ts
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/utils/__tests__/date-utils.test.ts
Labels: PR: awaiting author

#4984 [calendar] enabled calendar scope if feature flag enabled
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis.auth.strategy.ts
Labels: PR: awaiting review

#4972 [messaging] Add message deletion during partial sync
  packages/twenty-server/src/engine/core-modules/messaging/timeline-messaging.service.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-full-sync.job.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-partial-sync.job.ts
  packages/twenty-server/src/modules/messaging/services/gmail-full-sync/gmail-full-sync.module.ts
  packages/twenty-server/src/modules/messaging/services/gmail-full-sync/gmail-full-sync.service.ts
  packages/twenty-server/src/modules/messaging/services/gmail-partial-sync/gmail-partial-sync.module.ts
  packages/twenty-server/src/modules/messaging/services/gmail-partial-sync/gmail-partial-sync.service.ts
Labels: PR: awaiting review

#4961 Modify UI website and fix navbar issue on small devices
  packages/twenty-website/src/app/_components/oss-friends/Background.tsx
  packages/twenty-website/src/app/_components/releases/StyledTitle.tsx
  packages/twenty-website/src/app/_components/ui/layout/ContentContainer.tsx
  packages/twenty-website/src/app/_components/ui/layout/LoaderAnimation.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/styled.ts
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMain.tsx
  packages/twenty-website/src/app/layout.css
Labels: PR: awaiting review, website

#4978 fix: I should be able to use "enter" key to create profile
  packages/twenty-front/src/modules/auth/components/Modal.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/ModalLayout.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/__stories__/ModalLayout.stories.tsx
  packages/twenty-front/src/pages/auth/CreateProfile.tsx
Labels: PR: awaiting author

#4994 Introduce remote table entity
  package.json
  packages/twenty-server/src/database/typeorm/metadata/migrations/1713270565699-createRemoteTable.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/get-remote-table-local-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  yarn.lock
Labels: PR: awaiting review

#4951 fix: Auto Reset Opportunity Creation Search Field
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewOpportunityButton.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useEntitySelectSearch.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useRelationPicker.ts
Labels: PR: awaiting author

#5006 Fix invite link sign-up with workspace without subcription and billing not enabled
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
Labels: PR: awaiting review

#4885 Increase storybook pages coverage
  packages/twenty-front/.eslintrc.cjs
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/__stories__/App.stories.tsx
  packages/twenty-front/src/modules/auth/states/currentWorkspaceMemberState.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/companies/types/Company.ts
  packages/twenty-front/src/modules/navigation/components/__stories__/AppNavigationDrawer.stories.tsx
  packages/twenty-front/src/modules/object-metadata/components/__stories__/ObjectMetadataNavItems.stories.tsx
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/objectMetadataItemSchema.test.ts
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateTimeFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/__stories__/RecordDetailRelationSection.stories.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useEntitySelectSearch.test.tsx
  packages/twenty-front/src/modules/people/types/Person.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/__stories__/SettingsDataModelFieldPreviewCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/__tests__/useFieldPreview.test.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/__stories__/SettingsDataModelObjectAboutForm.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldDefaultPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldPreviewValueFromRecord.test.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/MonthAndYearDropdown.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/__stories__/DatePicker.stories.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar.test.tsx
  packages/twenty-front/src/modules/workspace-member/types/WorkspaceMember.ts
  packages/twenty-front/src/pages/auth/__stories__/ChooseYourPlan.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PasswordReset.stories.tsx
  packages/twenty-front/src/pages/not-found/__stories__/NotFound.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsBilling.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendars.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendarsSettings.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectEdit.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopers.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationDatabase.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationNewDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/tasks/__stories__/Tasks.stories.tsx
  packages/twenty-front/src/testing/decorators/HelmetProviderDecorator.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/activities.ts
  packages/twenty-front/src/testing/mock-data/companies.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/testing/mock-data/users.ts
Labels: PR: wip, PR: awaiting author

#5012 Fix chromatic tests
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateTimeFieldInput.stories.tsx
Labels: run-chromatic

#5007 UpdateSubscriptionJob should not be enqueued if billing is not enabled
  packages/twenty-server/src/engine/core-modules/billing/listeners/billing-workspace-member.listener.ts
Labels: PR: awaiting review

#5003 Make id available in remote table output
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/databases/graphql/fragments/remoteTableFragment.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabaseTablesListCard.tsx
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
Labels: PR: awaiting review

#5009 Fix explicit boolean predicates rule not working with boolean constants
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/usePreviousHotkeyScope.ts
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useScopedHotkeyCallback.ts
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts
  packages/twenty-front/src/utils/cast-as-integer-or-null.ts
  tools/eslint-rules/rules/explicit-boolean-predicates-in-if.ts
Labels: PR: awaiting review

#4667 Update `twenty-front` commands
  .eslintrc.react.cjs
  .github/workflows/ci-front.yaml
  .gitignore
  nx.json
  package.json
  packages/twenty-docs/docs/start/local-setup/yarn-setup.mdx
  packages/twenty-front/.prettierignore
  packages/twenty-front/jest.config.ts
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/activities/emails/utils/__tests__/getDisplayNameFromParticipant.test.ts
  packages/twenty-front/src/modules/activities/events/utils/__tests__/groupEventsByMonth.test.ts
  packages/twenty-front/src/modules/activities/hooks/__tests__/useCreateActivityInCache.test.tsx
  packages/twenty-front/src/modules/auth/hooks/__test__/useOnboardingStatus.test.ts
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneRelationMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFieldMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useExecuteQuickActionOnOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/__tests__/isFieldValueEmpty.test.ts
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__mocks__/cell.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useLimitPerMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useMultiObjectSearch.test.tsx
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchEntityQuery.test.tsx
  packages/twenty-front/src/modules/ui/input/button/components/__stories__/Button.docs.mdx
  packages/twenty-front/src/modules/ui/theme/hooks/__tests__/useColorScheme.test.tsx
  packages/twenty-front/src/modules/views/utils/__tests__/mapBoardFieldDefinitionsToViewFields.test.ts
  packages/twenty-front/src/modules/views/utils/__tests__/viewMapFunctions.test.ts
  packages/twenty-front/tsup.config.ts
  packages/twenty-front/tsup.ui.index.tsx
  packages/twenty-front/vite.config.ts
  packages/twenty-ui/project.json
  project.json
  yarn.lock
Labels: PR: awaiting review

#4950 GH-4362 Add syncing status
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSynchronizationStatus.tsx
  packages/twenty-front/src/modules/settings/accounts/hooks/useGetSyncStatusOptions.ts
Labels: PR: awaiting author

#5020 fix: attempt to fix Dockerfile front build
  packages/twenty-docker/twenty/Dockerfile
  packages/twenty-docs/docs/start/local-setup/yarn-setup.mdx
  packages/twenty-front/package.json
  packages/twenty-ui/README.md
Labels: PR: awaiting review

#4936 New Timeline
  packages/twenty-front/src/modules/activities/events/components/EventRow.tsx
  packages/twenty-front/src/modules/activities/timeline/hooks/useLinkedObject.ts
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventList.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventRow.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventUpdateProperty.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventsGroup.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/TimelineActivities.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/hooks/__tests__/useTimelineActivities.test.ts
  packages/twenty-front/src/modules/activities/timelineActivities/hooks/useTimelineActivities.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/types/TimelineActivity.ts
  packages/twenty-front/src/modules/activities/timelineActivities/utils/__tests__/groupEventsByMonth.test.ts
  packages/twenty-front/src/modules/activities/timelineActivities/utils/groupEventsByMonth.ts
  packages/twenty-front/src/modules/object-metadata/states/objectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/testing/mock-data/timeline-activities.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/record-position.listener.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace-workspace-member.listener.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record-create.event.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record-delete.event.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record-job-data.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record-update.event.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record.base.event.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/__tests__/object-record-changed-values.spec.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/object-record-changed-values.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/object-record-diff-merge.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/object-metadata-repository/metadata-to-repository.mapping.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/custom-objects/custom.object-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/listeners/participant-person.listener.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/listeners/participant-workspace-member.listener.ts
  packages/twenty-server/src/modules/calendar/listeners/calendar-channel.listener.ts
  packages/twenty-server/src/modules/company/standard-objects/company.object-metadata.ts
  packages/twenty-server/src/modules/messaging/listeners/messaging-message-channel.listener.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.object-metadata.ts
  packages/twenty-server/src/modules/person/standard-objects/person.object-metadata.ts
  packages/twenty-server/src/modules/timeline/jobs/create-audit-log-from-internal-event.ts
  packages/twenty-server/src/modules/timeline/jobs/upsert-timeline-activity-from-behavioral-event.ts
  packages/twenty-server/src/modules/timeline/jobs/upsert-timeline-activity-from-internal-event.job.ts
  packages/twenty-server/src/modules/timeline/repositiories/audit-log.repository.ts
  packages/twenty-server/src/modules/timeline/repositiories/timeline-activity.repository.ts
  packages/twenty-server/src/modules/timeline/services/timeline-activity.service.ts
  packages/twenty-server/src/modules/timeline/standard-objects/audit-log.object-metadata.ts
  packages/twenty-server/src/modules/timeline/standard-objects/behavioral-event.object-metadata.ts
  packages/twenty-server/src/modules/timeline/standard-objects/timeline-activity.object-metadata.ts
  packages/twenty-server/src/modules/timeline/timeline-activity.module.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.object-metadata.ts
Labels: PR: awaiting author

#5032 fix: fix root start script
  .github/workflows/ci-chromatic.yaml
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-docs.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  .github/workflows/ci-utils.yaml
  .github/workflows/ci-website.yaml
  package.json
  packages/twenty-chrome-extension/README.md
  packages/twenty-chrome-extension/package.json
  packages/twenty-docker/twenty-docs/Dockerfile
  packages/twenty-docker/twenty-website/Dockerfile
  packages/twenty-docs/docs/contributor/server/server.mdx
  packages/twenty-docs/docs/start/local-setup/troubleshooting.mdx
  packages/twenty-docs/docs/start/local-setup/yarn-setup.mdx
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
  packages/twenty-docs/package.json
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/src/emotion.d.ts
  packages/twenty-front/src/index.tsx
  packages/twenty-front/tsconfig.app.json
  packages/twenty-front/tsconfig.json
  packages/twenty-front/tsconfig.spec.json
  packages/twenty-front/tsconfig.storybook.json
  packages/twenty-server/scripts/run-integration.sh
  packages/twenty-website/package.json
  project.json
Labels: PR: awaiting review

#5016 User guide layout
  packages/twenty-website/public/images/user-guide/github/github-edit-content.png
  packages/twenty-website/public/images/user-guide/home/create-a-workspace.png
  packages/twenty-website/public/images/user-guide/home/custom-objects.png
  packages/twenty-website/public/images/user-guide/home/import-your-data.png
  packages/twenty-website/public/images/user-guide/home/what-is-twenty.png
  packages/twenty-website/public/images/user-guide/what-is-twenty/20.png
  packages/twenty-website/src/app/_components/oss-friends/Background.tsx
  packages/twenty-website/src/app/_components/releases/Line.tsx
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/_components/releases/StyledTitle.tsx
  packages/twenty-website/src/app/_components/ui/layout/Breadcrumbs.tsx
  packages/twenty-website/src/app/_components/ui/layout/ContentContainer.tsx
  packages/twenty-website/src/app/_components/ui/layout/FooterDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleContent.tsx
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleEditContent.tsx
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleLink.tsx
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleWarning.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/styled.ts
  packages/twenty-website/src/app/_components/user-guide/UserGuideCard.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMain.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebar.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebarSection.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideTableContents.tsx
  packages/twenty-website/src/app/_server-utils/get-posts.tsx
  packages/twenty-website/src/app/layout.css
  packages/twenty-website/src/app/releases/get-releases.tsx
  packages/twenty-website/src/content/user-guide/api-webhooks.mdx
  packages/twenty-website/src/content/user-guide/constants/UserGuideHomeCards.ts
  packages/twenty-website/src/content/user-guide/create-workspace.mdx
  packages/twenty-website/src/content/user-guide/emails.mdx
  packages/twenty-website/src/content/user-guide/fields.mdx
  packages/twenty-website/src/content/user-guide/github.mdx
  packages/twenty-website/src/content/user-guide/glossary.mdx
  packages/twenty-website/src/content/user-guide/import-export-data.mdx
  packages/twenty-website/src/content/user-guide/integrations.mdx
  packages/twenty-website/src/content/user-guide/kanban-views.mdx
  packages/twenty-website/src/content/user-guide/notes.mdx
  packages/twenty-website/src/content/user-guide/objects.mdx
  packages/twenty-website/src/content/user-guide/table-views.mdx
  packages/twenty-website/src/content/user-guide/tasks.mdx
  packages/twenty-website/src/content/user-guide/tips.mdx
  packages/twenty-website/src/content/user-guide/views-sort-filter.mdx
  packages/twenty-website/src/content/user-guide/what-is-twenty.mdx
Labels: PR: awaiting review, website

#5063 [fix] Support non latin characters in schema names
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/validateMetadataLabel.ts
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsCreateObjectInputSchema.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsUpdateObjectInputSchema.ts
  packages/twenty-front/src/pages/settings/data-model/utils/__tests__/format-metadata-label-to-name.spec.ts
  packages/twenty-front/src/pages/settings/data-model/utils/format-metadata-label-to-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/errors/InvalidStringException.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name.utils.ts
  yarn.lock
Labels: PR: awaiting review

#5124 Added releases to navbar
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderMobile.tsx
Labels: PR: awaiting review, website

#5039 Fixed date picker UI that was too overloaded
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateTimeFieldInput.stories.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/input/button/components/LightIconButton.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/MonthAndYearDropdown.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/TimeInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/__stories__/DatePicker.stories.tsx
Labels: PR: awaiting review

#5108 Update oss friends
  packages/twenty-website/src/app/_components/oss-friends/Background.tsx
  packages/twenty-website/src/app/_components/oss-friends/Card.tsx
  packages/twenty-website/src/app/_components/oss-friends/CardContainer.tsx
  packages/twenty-website/src/app/_components/oss-friends/ContentContainer.tsx
  packages/twenty-website/src/app/_components/oss-friends/Header.tsx
Labels: PR: awaiting review, website

#5106 Added SEO to website pages
  packages/twenty-website/src/app/contributors/[slug]/page.tsx
  packages/twenty-website/src/app/contributors/page.tsx
  packages/twenty-website/src/app/oss-friends/page.tsx
  packages/twenty-website/src/app/releases/page.tsx
  packages/twenty-website/src/app/user-guide/[slug]/page.tsx
  packages/twenty-website/src/app/user-guide/page.tsx
  packages/twenty-website/src/shared-utils/fetchArticleFromSlug.ts
  packages/twenty-website/src/shared-utils/formatSlug.ts
Labels: PR: awaiting review, website

#5000 Make Github stars dynamic and improve database init
  package.json
  packages/twenty-website/package.json
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderMobile.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/index.tsx
  packages/twenty-website/src/app/api/github-stars/route.tsx
  packages/twenty-website/src/app/contributors/api/init/route.tsx
  packages/twenty-website/src/app/contributors/api/update/route.tsx
  packages/twenty-website/src/database/migrate-database.ts
  packages/twenty-website/src/database/model.ts
  packages/twenty-website/src/database/postgres/migrations/0000_absent_giant_man.sql
  packages/twenty-website/src/database/postgres/migrations/0001_marvelous_eddie_brock.sql
  packages/twenty-website/src/database/postgres/migrations/meta/0000_snapshot.json
  packages/twenty-website/src/database/postgres/migrations/meta/_journal.json
  packages/twenty-website/src/database/postgres/schema-postgres.ts
  packages/twenty-website/src/database/sqlite/migrations/meta/_journal.json
  packages/twenty-website/src/github-sync/contributors/fetch-assignable-users.tsx
  packages/twenty-website/src/github-sync/contributors/fetch-issues-prs.tsx
  packages/twenty-website/src/github-sync/contributors/save-issues-to-db.tsx
  packages/twenty-website/src/github-sync/contributors/save-prs-to-db.tsx
  packages/twenty-website/src/github-sync/contributors/search-issues-prs.tsx
  packages/twenty-website/src/github-sync/contributors/types.tsx
  packages/twenty-website/src/github-sync/fetch-and-save-github-data.ts
  packages/twenty-website/src/github-sync/github-stars/fetch-and-save-github-stars.tsx
  packages/twenty-website/src/github-sync/github-sync.ts
  packages/twenty-website/src/shared-utils/formatNumberOfStars.ts
  yarn.lock
Labels: PR: awaiting review, website

#5142 Remove SQLite from twenty-website
  .github/workflows/ci-website.yaml
  package.json
  packages/twenty-website/.env.example
  packages/twenty-website/package.json
  packages/twenty-website/src/database/database.ts
  packages/twenty-website/src/database/drizzle-posgres.config.ts
  packages/twenty-website/src/database/migrations/0000_absent_giant_man.sql
  packages/twenty-website/src/database/migrations/0001_marvelous_eddie_brock.sql
  packages/twenty-website/src/database/migrations/meta/0000_snapshot.json
  packages/twenty-website/src/database/migrations/meta/_journal.json
  packages/twenty-website/src/database/model.ts
  packages/twenty-website/src/database/schema-postgres.ts
  packages/twenty-website/src/database/sqlite/drizzle-sqlite.config.ts
  packages/twenty-website/src/database/sqlite/migrations/0000_small_karma.sql
  packages/twenty-website/src/database/sqlite/migrations/meta/0000_snapshot.json
  packages/twenty-website/src/database/sqlite/migrations/meta/_journal.json
  packages/twenty-website/src/database/sqlite/schema-sqlite.ts
  yarn.lock
Labels: website

#5143 feat: allow self signed certificates with postgres connections
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-server/.env.example
  packages/twenty-server/src/database/typeorm/core/core.datasource.ts
  packages/twenty-server/src/database/typeorm/metadata/metadata.datasource.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
Labels: PR: awaiting author

#5174 fixed twenty website build
  packages/twenty-website/src/app/contributors/api/update/route.tsx
  packages/twenty-website/src/app/layout.tsx
  packages/twenty-website/src/app/oss-friends/page.tsx
  packages/twenty-website/src/app/page.tsx
  packages/twenty-website/src/app/releases/api/route.tsx
  packages/twenty-website/src/app/releases/page.tsx
  packages/twenty-website/src/app/user-guide/[slug]/page.tsx
  packages/twenty-website/src/app/user-guide/page.tsx
  packages/twenty-website/src/database/database.ts
Labels: website

#5145 4748 create updated listener on blocklist
  packages/twenty-server/src/modules/calendar/listeners/calendar-blocklist.listener.ts
  packages/twenty-server/src/modules/messaging/listeners/messaging-blocklist.listener.ts
Labels: PR: awaiting review

#4626 GH-3546 Recaptcha on login form
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/index.css
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/challenge.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/signUp.ts
  packages/twenty-front/src/modules/auth/graphql/queries/checkUserExists.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUpForm.ts
  packages/twenty-front/src/modules/captcha/components/CaptchaProvider.tsx
  packages/twenty-front/src/modules/captcha/components/CaptchaProviderScriptLoaderEffect.tsx
  packages/twenty-front/src/modules/captcha/hooks/useReadCaptchaToken.ts
  packages/twenty-front/src/modules/captcha/hooks/useRequestFreshCaptchaToken.ts
  packages/twenty-front/src/modules/captcha/states/captchaTokenState.ts
  packages/twenty-front/src/modules/captcha/states/isCaptchaScriptLoadedState.ts
  packages/twenty-front/src/modules/captcha/states/isRequestingCaptchaTokenState.ts
  packages/twenty-front/src/modules/captcha/utils/getCaptchaUrlByProvider.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/captchaProviderState.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/challenge.input.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/sign-up.input.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/user-exists.input.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/integrations/captcha/captcha.constants.ts
  packages/twenty-server/src/engine/integrations/captcha/captcha.guard.ts
  packages/twenty-server/src/engine/integrations/captcha/captcha.module-factory.ts
  packages/twenty-server/src/engine/integrations/captcha/captcha.module.ts
  packages/twenty-server/src/engine/integrations/captcha/captcha.service.ts
  packages/twenty-server/src/engine/integrations/captcha/drivers/google-recaptcha.driver.ts
  packages/twenty-server/src/engine/integrations/captcha/drivers/interfaces/captcha-driver.interface.ts
  packages/twenty-server/src/engine/integrations/captcha/drivers/interfaces/captcha-server-response.ts
  packages/twenty-server/src/engine/integrations/captcha/drivers/turnstile.driver.ts
  packages/twenty-server/src/engine/integrations/captcha/interfaces/captcha.interface.ts
  packages/twenty-server/src/engine/integrations/captcha/interfaces/index.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/integrations.module.ts
Labels: PR: awaiting author

#5185 fix: fix SignInUpForm Continue button being disabled
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInput.tsx
Labels: PR: awaiting review

#5194 Add redis to useMetadataCache yoga plugin
  packages/twenty-server/src/engine/api/graphql/graphql-config/hooks/use-cached-metadata.ts
  packages/twenty-server/src/engine/api/graphql/metadata-graphql-api.module.ts
  packages/twenty-server/src/engine/api/graphql/metadata.module-factory.ts
Labels: PR: awaiting review

#5198 chore: add sentry captureException for global error logging
  packages/twenty-front/src/modules/error-handler/components/AppErrorBoundary.tsx
Labels: PR: awaiting review

#5153 Feat/twenty orm
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/index.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/compute-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.entity.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/inject-workspace-datasource.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/inject-workspace-repository.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-field.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-gate.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-not-audit-logged.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-nullable.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-primary-field.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-system.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-object.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-relation.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-column.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-relation.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/index.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/flatten-composite-types.interface.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/gate.interface.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/twenty-orm-options.interface.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-field-metadata-args.interface.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-object-metadata-args.interface.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-relation-metadata-args.interface.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/engine/twenty-orm/storage/data-source.storage.ts
  packages/twenty-server/src/engine/twenty-orm/storage/metadata-args.storage.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm-core.module.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.constants.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.module-definition.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.module.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.providers.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.service.ts
  packages/twenty-server/src/engine/twenty-orm/utils/get-workspace-repository-token.util.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-object-tests/attachment.object-metadata.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-object-tests/base.object-metadata.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-object-tests/company.object-metadata.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-object-tests/workspace-member.object-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/decorators/field-metadata.decorator.ts
  packages/twenty-server/src/utils/typed-reflect.ts
Labels: PR: awaiting author

#5049 Feat/add postgres spilo
  packages/twenty-docker/twenty-postgres-spilo/Dockerfile
Labels: PR: awaiting author

#5068 Implemented Search Feature in Filter Menu
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
Labels: PR: awaiting author

#5215 Remove debounce on filter search bar
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
Labels: PR: awaiting review

#5214 Flush cache when reset db
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/engine/integrations/cache-storage/cache-storage.service.ts
Labels: PR: awaiting review

#5110 chore: use Nx affected tasks in CI
  .eslintrc.cjs
  .github/workflows/actions/nx-affected/action.yaml
  .github/workflows/actions/task-cache/action.yaml
  .github/workflows/actions/yarn-install/action.yaml
  .github/workflows/ci-chromatic.yaml
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-docs.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  .github/workflows/ci-utils.yaml
  .github/workflows/ci-website.yaml
  .gitignore
  nx.json
  package.json
  packages/twenty-chrome-extension/package.json
  packages/twenty-chrome-extension/tsconfig.app.json
  packages/twenty-chrome-extension/tsconfig.spec.json
  packages/twenty-emails/package.json
  packages/twenty-emails/project.json
  packages/twenty-emails/src/common-style.ts
  packages/twenty-emails/src/components/BaseEmail.tsx
  packages/twenty-emails/src/components/BaseHead.tsx
  packages/twenty-emails/src/components/CallToAction.tsx
  packages/twenty-emails/src/components/HighlightedText.tsx
  packages/twenty-emails/src/components/Link.tsx
  packages/twenty-emails/src/components/MainText.tsx
  packages/twenty-emails/src/emails/clean-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/delete-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/tsconfig.lib.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/tsconfig.json
  packages/twenty-server/nest-cli.json
  packages/twenty-server/project.json
  packages/twenty-server/test/company.e2e-spec.ts
  packages/twenty-server/test/utils/create-app.ts
  packages/twenty-ui/project.json
  packages/twenty-ui/tsconfig.json
  tools/eslint-rules/project.json
  tools/eslint-rules/tsconfig.json
  tools/eslint-rules/tsconfig.lint.json
  tools/eslint-rules/tsconfig.spec.json
Labels: PR: awaiting review

#5186 Favorites should be user-level not workspace-level
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts
Labels: PR: awaiting review
