Repository twentyhq/twenty, pull requests merged in 2024-03, with the labels that each got.

#4252 41 update subscription when workspace member changes 2
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useNavigateAfterSignInUp.ts
  packages/twenty-front/src/pages/auth/ChooseYourPlan.tsx
  packages/twenty-server/src/core/billing/billing.controller.ts
  packages/twenty-server/src/core/billing/billing.module.ts
  packages/twenty-server/src/core/billing/billing.service.ts
  packages/twenty-server/src/core/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/core/billing/jobs/update-subscription.job.ts
  packages/twenty-server/src/core/billing/listeners/billing-workspace-member.listener.ts
  packages/twenty-server/src/core/billing/stripe/stripe.service.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.module.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/core/user/services/user.service.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.ts
  packages/twenty-server/src/core/workspace/workspace.entity.ts
  packages/twenty-server/src/core/workspace/workspace.module.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1708535112230-addBillingCoreTables.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1709233666080-updateBillingCoreTables.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/workspace/messaging/listeners/messaging-workspace-member.listener.ts
Labels: PR: awaiting review

#4278 Fix Internal Server Error when removing profile picture (#4257)
  packages/twenty-front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
Labels: PR: awaiting review

#4256 [messaging] add more details in exceptions
  packages/twenty-server/src/metadata/data-source/data-source.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message/message.service.ts
  packages/twenty-server/src/workspace/workspace-datasource/workspace-datasource.service.ts
Labels: PR: awaiting author

#4175 Update SettingsObjectAboutSection.tsx changed "Disable" CTA to "Deact…
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItemForSettings.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectAboutSection.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldActiveActionDropdown.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDisabledActionDropdown.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectInactiveMenuDropDown.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/__stories__/SettingsObjectInactiveMenuDropDown.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: PR: awaiting author

#4197 feat: multi-workspace followup
  .vscode/settings.json
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUser.ts
  packages/twenty-server/src/core/auth/auth.resolver.spec.ts
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/auth/dto/generate-jwt.input.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/auth/services/token.service.spec.ts
  packages/twenty-server/src/core/auth/services/token.service.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/core/user/services/user.service.ts
  packages/twenty-server/src/core/user/user.entity.ts
  packages/twenty-server/src/core/user/user.module.ts
  packages/twenty-server/src/core/user/user.resolver.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.ts
  packages/twenty-server/src/core/workspace/workspace.entity.ts
  packages/twenty-server/src/core/workspace/workspace.module.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/index.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/userWorkspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/core/index.ts
  packages/twenty-server/src/database/typeorm-seeds/core/userWorkspaces.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1709314035408-updateUserWorkspace.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
Labels: PR: awaiting review

#4279 Add sentry tracing
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindOneRecordQuery.ts
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmailsInboxSettings.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersApiKeysDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-server/src/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/integrations/exception-handler/drivers/sentry.driver.ts
  packages/twenty-server/src/integrations/exception-handler/interfaces/exception-handler-user.interface.ts
  packages/twenty-server/src/integrations/tracing/useSentryTracing.ts
  packages/twenty-server/src/main.ts
Labels: PR: awaiting review

#4206 Fixed index column stickiness mobile
  packages/twenty-front/src/modules/object-record/record-table/components/CheckboxCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/ColumnHead.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableFirstColumnScrollObserver.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/SelectAllCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableContext.ts
Labels: PR: awaiting author

#4177 Update .env.example
  packages/twenty-docs/docs/start/local-setup/docker-setup.mdx
  packages/twenty-server/.env.example
Labels: PR: awaiting author

#4297 Fix domain name parsing on company creation
  packages/twenty-server/package.json
  packages/twenty-server/src/workspace/messaging/services/create-companies-and-contacts/create-companies-and-contacts.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-company/create-company.service.ts
  packages/twenty-server/src/workspace/messaging/utils/get-company-name-from-domain-name.util.ts
  packages/twenty-server/src/workspace/messaging/utils/get-domain-name-from-handle.util.ts
  yarn.lock
Labels: PR: awaiting review

#4274 4030 website header for tablet
  packages/twenty-website/src/app/_components/ui/layout/HeaderDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/HeaderMobile.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/callToAction.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/index.tsx
  packages/twenty-website/src/app/_components/ui/layout/header/styled.ts
  packages/twenty-website/src/app/layout.tsx
Labels: PR: awaiting review

#4270 refactor: validate objectMetadataItem with Zod on creation and update…
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneObjectMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectMetadataItemForSettings.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItemForSettings.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useUpdateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatObjectMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/objectMetadataItemSchema.test.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/__tests__/settingsCreateObjectInputSchema.test.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/__tests__/settingsUpdateObjectInputSchema.test.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsCreateObjectInputSchema.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsUpdateObjectInputSchema.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/utils/validation-schemas/__tests__/camelCaseStringSchema.test.ts
  packages/twenty-front/src/utils/validation-schemas/camelCaseStringSchema.ts
Labels: PR: awaiting review

#4170 feat: adding metadata open-api endpoints and updating docs
  packages/twenty-docs/sidebars.js
  packages/twenty-docs/src/pages/rest-api/metadata.tsx
  packages/twenty-server/src/core/api-rest/api-rest.module.ts
  packages/twenty-server/src/core/open-api/open-api.service.ts
  packages/twenty-server/src/core/open-api/utils/base-schema.utils.ts
  packages/twenty-server/src/core/open-api/utils/components.utils.ts
  packages/twenty-server/src/core/open-api/utils/path.utils.ts
  packages/twenty-server/src/core/open-api/utils/request-body.utils.ts
  packages/twenty-server/src/core/open-api/utils/responses.utils.ts
Labels: PR: awaiting review

#4271 refactor: use react-hook-form in Settings Data Model Object pages
  package.json
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFormSection.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFormSection.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/__stories__/SettingsDataModelObjectAboutForm.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/testing/decorators/FormProviderDecorator.tsx
  yarn.lock
Labels: PR: awaiting author

#4273 feat: change condition of duplicate check
  packages/twenty-server/src/constants/settings/index.ts
  packages/twenty-server/src/constants/settings/interfaces/settings.interface.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/__tests__/find-duplicates-query.factory.spec.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/find-duplicates-query.factory.ts
Labels: PR: awaiting review

#4309 feat: add Calendar tab to Show Page Activities panel
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: PR: awaiting review

#4310 feat: remove Color setting from Calendars Settings
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsColorSettingCard.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
Labels: PR: awaiting review

#4314 4282 create calendarchannel data model
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
Labels: PR: awaiting author

#4220 Add a concise test report with just the errors
  packages/twenty-front/jest.config.ts
  packages/twenty-front/package.json
  packages/twenty-server/jest.config.ts
Labels: PR: awaiting review

#4317 4281 create calendarevent data model
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
Labels: PR: awaiting review

#4333 4283 create calendareventattendee data model
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event-attendee.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/workspace-member.object-metadata.ts
Labels: PR: awaiting review

#4319 feat: add event rows to Show Page Calendar tab
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarDayCardContent.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarMonthCard.tsx
  packages/twenty-front/src/modules/activities/calendar/components/__stories__/Calendar.stories.tsx
  packages/twenty-front/src/modules/activities/calendar/types/CalendarEvent.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/sortCalendarEvents.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/sortCalendarEvents.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/testing/mock-data/calendar.ts
  packages/twenty-front/src/utils/array/groupArrayItemsBy.ts
Labels: PR: awaiting review

#4325 Chore: Only show 2 relations in ActivityTargetChips
  packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
Labels: PR: awaiting review

#4355 Fix fetchAllMessages cronJob when deleted datasource
  packages/twenty-server/src/workspace/messaging/commands/crons/fetch-all-workspaces-messages.job.ts
Labels: PR: awaiting review

#4320 [backend] add cache storage module
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-server/package.json
  packages/twenty-server/src/integrations/cache-storage/__tests__/cache-storage.service.spec.ts
  packages/twenty-server/src/integrations/cache-storage/cache-storage.module-factory.ts
  packages/twenty-server/src/integrations/cache-storage/cache-storage.module.ts
  packages/twenty-server/src/integrations/cache-storage/cache-storage.service.ts
  packages/twenty-server/src/integrations/cache-storage/types/cache-storage-namespace.enum.ts
  packages/twenty-server/src/integrations/cache-storage/types/cache-storage-type.enum.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/integrations.module.ts
  packages/twenty-server/tsconfig.json
  yarn.lock
Labels: PR: awaiting review

#4327 TextInput height fix
  packages/twenty-front/src/modules/ui/input/components/TextInput.tsx
Labels: PR: awaiting review

#4353 feat: sync all workspaces
  packages/twenty-server/src/commands/command-logger.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/services/sync-workspace-logger.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/workspace-sync-metadata-commands.module.ts
Labels: PR: awaiting review

#4339 44 add blocking middleware payment failed
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/auth/hooks/__test__/useOnboardingStatus.test.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/billing/components/ManageYourSubscription.tsx
  packages/twenty-front/src/modules/ui/display/info/components/Info.tsx
  packages/twenty-front/src/modules/ui/display/info/components/__stories__/Info.stories.tsx
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-server/src/core/billing/billing.controller.ts
  packages/twenty-server/src/core/billing/billing.service.ts
  packages/twenty-server/src/core/billing/stripe/stripe.service.ts
Labels: PR: awaiting author

#4277 Fix: design improvement for release page
  packages/twenty-server/src/integrations/exception-handler/drivers/sentry.driver.ts
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/_components/releases/StyledTitle.tsx
Labels: PR: awaiting review

#4326 feat: add Month headers to Show Page Calendar tab
  package.json
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/ui/display/typography/components/H3Title.tsx
  packages/twenty-front/src/modules/ui/display/typography/components/__stories__/H3Title.stories.tsx
  yarn.lock
Labels: PR: awaiting author

#4371 [messaging] remove partial sync retry and fix missing datasource error
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/workspace/messaging/commands/crons/fetch-all-workspaces-messages.job.ts
  packages/twenty-server/src/workspace/messaging/commands/gmail-partial-sync.command.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-messages-by-batches.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
Labels: PR: awaiting review

#4350 4284 create calendarchanneleventassociation data model
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel-event-association.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
Labels: PR: awaiting review

#4254 Added CurrencyFieldInput design
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/CurrencyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/utils/computeDraftValueFromFieldValue.ts
  packages/twenty-front/src/modules/ui/field/input/components/CurrencyInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/currency/components/CurrencyPickerDropdownButton.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/currency/components/CurrencyPickerDropdownSelect.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/currency/types/CurrencyPickerHotkeyScope.ts
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemSelectAvatar.tsx
Labels: PR: awaiting review

#4300 feat: add Settings Object Edit identifiers form
  packages/twenty-front/src/modules/object-metadata/constants/LabelIdentifierFieldMetadataTypes.ts
  packages/twenty-front/src/modules/object-metadata/utils/getActiveFieldMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/utils/getDisabledFieldMetadataItems.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelCardTitle.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectSettingsFormCard.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
Labels: PR: awaiting review

#4378 Added a RelationFromOneSide ResolveField in FieldMetadata GraphQL Resolver
  packages/twenty-server/src/metadata/field-metadata/dtos/relation-definition.dto.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/metadata/object-metadata/dtos/object-metadata.dto.ts
Labels: PR: awaiting review

#4299 Use backspace for clearing record table cell.
  packages/twenty-front/src/modules/object-record/record-field/hooks/useClearField.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldClearable.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldType.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
Labels: PR: awaiting review

#4388 fix: Standardize labels casing
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInput.tsx
Labels: PR: awaiting review

#4342 [backend] use cache storage service for workspace schema cache
  packages/twenty-server/src/integrations/cache-storage/cache-storage.service.ts
  packages/twenty-server/src/integrations/cache-storage/types/cache-storage-namespace.enum.ts
  packages/twenty-server/src/integrations/memory-storage/decorators/inject-memory-storage.decorator.ts
  packages/twenty-server/src/integrations/memory-storage/drivers/interfaces/memory-storage-driver.interface.ts
  packages/twenty-server/src/integrations/memory-storage/drivers/local.driver.ts
  packages/twenty-server/src/integrations/memory-storage/interfaces/index.ts
  packages/twenty-server/src/integrations/memory-storage/interfaces/memory-storage.interface.ts
  packages/twenty-server/src/integrations/memory-storage/memory-storage.constants.ts
  packages/twenty-server/src/integrations/memory-storage/memory-storage.module.ts
  packages/twenty-server/src/integrations/memory-storage/memory-storage.service.spec.ts
  packages/twenty-server/src/integrations/memory-storage/memory-storage.service.ts
  packages/twenty-server/src/integrations/memory-storage/memory-storage.util.ts
  packages/twenty-server/src/integrations/memory-storage/serializers/default.serializer.ts
  packages/twenty-server/src/integrations/memory-storage/serializers/interfaces/memory-storage-serializer.interface.ts
  packages/twenty-server/src/integrations/memory-storage/serializers/json.serializer.ts
  packages/twenty-server/src/workspace/workspace-schema-storage/workspace-schema-storage.module.ts
  packages/twenty-server/src/workspace/workspace-schema-storage/workspace-schema-storage.service.ts
  packages/twenty-server/src/workspace/workspace.factory.ts
Labels: PR: awaiting author

#4348 feat: add next event indicator to Show Page Calendar tab
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarCurrentEventCursor.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarDayCardContent.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarMonthCard.tsx
  packages/twenty-front/src/modules/activities/calendar/contexts/CalendarContext.ts
  packages/twenty-front/src/modules/activities/calendar/hooks/useCalendarEvents.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/findUpcomingCalendarEvent.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/hasCalendarEventEnded.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/hasCalendarEventStarted.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/sortCalendarEvents.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/findUpcomingCalendarEvent.ts
  packages/twenty-front/src/modules/activities/calendar/utils/getCalendarEventEndDate.ts
  packages/twenty-front/src/modules/activities/calendar/utils/hasCalendarEventEnded.ts
  packages/twenty-front/src/modules/activities/calendar/utils/hasCalendarEventStarted.ts
  packages/twenty-front/src/modules/activities/calendar/utils/sortCalendarEvents.ts
  packages/twenty-front/src/modules/ui/layout/card/components/CardContent.tsx
Labels: PR: awaiting review

#4420 feat: add Color code section to Calendar Settings
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/calendar/contexts/CalendarContext.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
Labels: PR: awaiting review

#4426 Fix activity creation
  packages/twenty-server/src/workspace/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/workspace/workspace-query-runner/factories/query-runner-args.factory.ts
Labels: before-backend-freeze

#4416 [messaging] Fix thread cleaner service subqueries
  packages/twenty-server/src/core/auth/services/google-gmail.service.ts
  packages/twenty-server/src/workspace/messaging/jobs/gmail-full-sync.job.ts
  packages/twenty-server/src/workspace/messaging/jobs/gmail-partial-sync.job.ts
  packages/twenty-server/src/workspace/messaging/repositories/connected-account/connected-account.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-channel-message-association/message-channel-message-association.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-channel/message-channel.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-thread/message-thread.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-thread/message-thread.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message/message.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/message/message.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-full-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-refresh-access-token.service.ts
  packages/twenty-server/src/workspace/messaging/services/save-messages-and-create-contacts.service.ts
  packages/twenty-server/src/workspace/messaging/services/thread-cleaner/thread-cleaner.service.ts
  packages/twenty-server/src/workspace/messaging/services/thread-cleaner/utils/delete-using-pagination.util.spec.ts
  packages/twenty-server/src/workspace/messaging/services/thread-cleaner/utils/delete-using-pagination.util.ts
Labels: PR: awaiting review, before-backend-freeze

#4379 40 remove self billing feature flag
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/hooks/__test__/useOnboardingStatus.test.ts
  packages/twenty-front/src/modules/auth/states/currentWorkspaceState.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUser.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/auth/PlanRequired.tsx
  packages/twenty-front/src/pages/auth/__stories__/PlanRequired.stories.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-server/src/core/billing/billing.module.ts
  packages/twenty-server/src/core/billing/billing.service.ts
  packages/twenty-server/src/core/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/core/billing/jobs/update-subscription.job.ts
  packages/twenty-server/src/core/billing/listeners/billing-workspace-member.listener.ts
  packages/twenty-server/src/core/billing/stripe/stripe.service.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/core/workspace/workspace.entity.ts
  packages/twenty-server/src/core/workspace/workspace.resolver.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1709914564361-updateBillingSubscription.ts
Labels: PR: awaiting review, before-backend-freeze

#4432 Build listener to backfill position
  packages/twenty-server/src/integrations/event-emitter/types/object-record-create.event.ts
  packages/twenty-server/src/integrations/integrations.module.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/__tests__/record-position-query.factory.spec.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/record-position-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/workspace/workspace-query-runner/factories/index.ts
  packages/twenty-server/src/workspace/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/workspace/workspace-query-runner/factories/record-position.factory.ts
  packages/twenty-server/src/workspace/workspace-query-runner/jobs/record-position-backfill.job.ts
  packages/twenty-server/src/workspace/workspace-query-runner/listeners/record-position.listener.ts
  packages/twenty-server/src/workspace/workspace-query-runner/services/record-position-backfill-module.ts
  packages/twenty-server/src/workspace/workspace-query-runner/services/record-position-backfill-service.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
Labels: before-backend-freeze

#4373 feat: wip sync standard id
  packages/twenty-server/src/database/typeorm/metadata/migrations/1709894431938-addStandardId.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/add-standard-id.command.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/workspace-sync-metadata-commands.module.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-field.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-object.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/custom-objects/custom.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/decorators/field-metadata.decorator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/partial-object-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/reflect-computed-relation-field-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/reflect-field-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/reflect-object-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-relation-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/activity-target.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/activity.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/api-key.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/attachment.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/base.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/blocklist.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel-event-association.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event-attendee.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/comment.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/company.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/favorite.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel-message-association.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-participant.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-thread.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/opportunity.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/pipeline-step.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/view-field.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/view-filter.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/view-sort.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/view.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/webhook.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/workspace-member.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/compute-standard-object.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/create-deterministic-uuid.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/sync-metadata.util.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/sync-metadata.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync-metadata.module.ts
Labels: PR: awaiting review, before-backend-freeze

#4390 fix serverurl in openapi docs for self hosted instance
  packages/twenty-docs/src/components/token-form.tsx
  packages/twenty-server/src/core/api-rest/api-rest.service.ts
  packages/twenty-server/src/core/api-rest/metadata-rest.service.ts
  packages/twenty-server/src/core/open-api/open-api.controller.ts
  packages/twenty-server/src/core/open-api/open-api.service.ts
  packages/twenty-server/src/core/open-api/utils/base-schema.utils.ts
  packages/twenty-server/src/core/open-api/utils/path.utils.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
Labels: before-backend-freeze

#4415 Fix: Added grab cursor on hover over favorite icon
  packages/twenty-front/src/modules/favorites/components/Favorites.tsx
Labels: PR: awaiting author

#4419 4364-feat(front): Display tags in multi-select picker
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOptionSelect.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemMultiSelect.tsx
Labels: PR: awaiting review

#4433 Added info about SERVER_URL to docs
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
Labels: PR: awaiting author

#4374 Adding new one-click deploy option to 1-click-deploy.mdx
  packages/twenty-docs/docs/start/self-hosting/1-click-deploy.mdx
Labels: PR: awaiting author

#4481 Update add account button style
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRow.tsx
Labels: PR: awaiting author

#4480 Add command to stop demo seed cron
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/start-data-seed-demo-workspace.cron.command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/stop-data-seed-demo-workspace.cron.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
Labels: PR: awaiting author

#4446 First batch of `modules/activities` tests
  packages/twenty-front/src/modules/activities/emails/hooks/__tests__/useEmailThread.test.ts
  packages/twenty-front/src/modules/activities/emails/hooks/internal/__tests__/useEmailThreadStates.test.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/__tests__/useOpenEmailThreadRightDrawer.test.ts
  packages/twenty-front/src/modules/activities/files/hooks/__tests__/useAttachments.test.ts
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityById.test.ts
  packages/twenty-front/src/modules/activities/inline-cell/hooks/__tests__/useInjectIntoActivityTargetInlineCellCache.test.ts
  packages/twenty-front/src/modules/activities/notes/hooks/__tests__/useNotes.test.ts
  packages/twenty-front/src/modules/activities/tasks/hooks/__tests__/useCompleteTask.test.ts
  packages/twenty-front/src/modules/activities/timeline/hooks/__tests__/useInjectIntoTimelineActivitiesQueries.test.ts
Labels: PR: awaiting review

#4436 Update backdrop-filter in OverlayBackground.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/BackgroundDark.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/BackgroundLight.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/OverlayBackground.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-front/src/modules/ui/theme/constants/BackgroundDark.ts
  packages/twenty-front/src/modules/ui/theme/constants/BackgroundLight.ts
  packages/twenty-front/src/modules/ui/theme/constants/OverlayBackground.ts
  packages/twenty-ui/src/theme/constants/BackgroundDark.ts
  packages/twenty-ui/src/theme/constants/BackgroundLight.ts
  packages/twenty-ui/src/theme/constants/OverlayBackground.ts
Labels: PR: awaiting author

#4421 Prefetching views and favorites
  packages/twenty-front/src/hooks/useDefaultHomePagePath.tsx
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  packages/twenty-front/src/modules/object-metadata/utils/mapObjectMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useCachedRootQuery.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useUpsertFindManyRecordsQueryInCache.ts
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordEdgeFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindManyRecordsForMultipleMetadataItemsQuery.ts
  packages/twenty-front/src/modules/object-record/query-keys/types/QueryKey.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useMultiObjectSearch.test.tsx
  packages/twenty-front/src/modules/prefetch/components/PrefetchDataProvider.tsx
  packages/twenty-front/src/modules/prefetch/components/PrefetchRunQueriesEffect.tsx
  packages/twenty-front/src/modules/prefetch/constants/PrefetchConfig.ts
  packages/twenty-front/src/modules/prefetch/hooks/internal/usePrefetchRunQuery.ts
  packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts
  packages/twenty-front/src/modules/prefetch/query-keys/AllFavoritesQueryKey.ts
  packages/twenty-front/src/modules/prefetch/query-keys/AllViewsQueryKey.ts
  packages/twenty-front/src/modules/prefetch/states/prefetchIsLoadedFamilyState.ts
  packages/twenty-front/src/modules/prefetch/types/PrefetchKey.ts
  packages/twenty-front/src/modules/views/components/ViewBarEffect.tsx
Labels: PR: awaiting author

#4567 Add getters factory for attachements
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/index.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/environment/environment.default.ts
  packages/twenty-server/src/engine/modules/auth/auth.module.ts
  packages/twenty-server/src/engine/modules/auth/services/sign-up.service.spec.ts
  packages/twenty-server/src/engine/modules/auth/services/sign-up.service.ts
  packages/twenty-server/src/engine/modules/auth/services/token.service.spec.ts
  packages/twenty-server/src/engine/modules/auth/services/token.service.ts
  packages/twenty-server/src/engine/modules/file/controllers/file.controller.spec.ts
  packages/twenty-server/src/engine/modules/file/controllers/file.controller.ts
  packages/twenty-server/src/engine/modules/file/file-upload/file-upload.module.ts
  packages/twenty-server/src/engine/modules/file/file-upload/resolvers/file-upload.resolver.spec.ts
  packages/twenty-server/src/engine/modules/file/file-upload/resolvers/file-upload.resolver.ts
  packages/twenty-server/src/engine/modules/file/file-upload/services/file-upload.service.spec.ts
  packages/twenty-server/src/engine/modules/file/file-upload/services/file-upload.service.ts
  packages/twenty-server/src/engine/modules/file/file.module.ts
  packages/twenty-server/src/engine/modules/file/guards/file-path-guard.ts
  packages/twenty-server/src/engine/modules/user/user.module.ts
  packages/twenty-server/src/engine/modules/user/user.resolver.ts
  packages/twenty-server/src/engine/modules/workspace/workspace.module.ts
  packages/twenty-server/src/engine/modules/workspace/workspace.resolver.ts
Labels: PR: awaiting review

#4568 4485 create a custom resolver for calendar events
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/attendeeFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/calendarEventFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/calendarEventFragmentWithTotalFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/getCalendarEventsFromCompanyId.ts
  packages/twenty-front/src/modules/activities/calendar/queries/getCalendarEventsFromPersonId.ts
  packages/twenty-server/src/engine/modules/calendar/constants/calendar.constants.ts
  packages/twenty-server/src/engine/modules/calendar/dtos/timeline-calendar-event-attendee.dto.ts
  packages/twenty-server/src/engine/modules/calendar/dtos/timeline-calendar-event.dto.ts
  packages/twenty-server/src/engine/modules/calendar/dtos/timeline-calendar-events-with-total.dto.ts
  packages/twenty-server/src/engine/modules/calendar/timeline-calendar-event.module.ts
  packages/twenty-server/src/engine/modules/calendar/timeline-calendar-event.resolver.ts
  packages/twenty-server/src/engine/modules/calendar/timeline-calendar-event.service.ts
  packages/twenty-server/src/engine/modules/engine-modules.module.ts
  packages/twenty-server/src/engine/modules/messaging/dtos/timeline-thread.dto.ts
Labels: PR: awaiting author

#4455 Delete auth/file front variables
  packages/twenty-docker/prod/twenty-front/Dockerfile
  packages/twenty-docs/docs/start/self-hosting/cloud-providers.mdx
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-front/.env.example
  packages/twenty-front/src/config/index.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
  packages/twenty-front/src/modules/users/utils/getProfilePictureAbsoluteURI.ts
Labels: PR: awaiting author

#4572 fix: fix typings in calendar utils tests
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/findUpcomingCalendarEvent.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/hasCalendarEventEnded.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/hasCalendarEventStarted.test.ts
  packages/twenty-front/src/modules/activities/calendar/utils/__tests__/sortCalendarEvents.test.ts
Labels: PR: awaiting review

#4232 feat: multi-workspace (frontend)
  package.json
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/generateJWT.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/states/workspaces.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/DefaultWorkspaceLogo.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/DefaultWorkspaceName.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/MulitWorkspaceDropdownId.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useWorkspaceSwitching.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/types/NavigationDrawerHotKeyScope.ts
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/typeorm-seeds/core/userWorkspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/core/workspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/workspaceMember.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1707778127558-addUserWorkspaces.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1709680520888-updateUserWorkspaceColumnConstraints.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/utils/__tests__/fields.utils.spec.ts
  packages/twenty-server/src/engine/modules/user/services/user.service.spec.ts
  packages/twenty-server/src/engine/modules/user/services/user.service.ts
  packages/twenty-server/src/engine/modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/modules/workspace/workspace.module.ts
  yarn.lock
Labels: PR: awaiting review

#4491 update example docker-compose to bitnami postgres path
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
Labels: PR: awaiting author

#4615 4489 timebox finish google calendar full sync
  packages/twenty-server/package.json
  packages/twenty-server/src/modules/calendar/commands/google-calendar-full-sync.command.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-channel.repository.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-event-attendee.repository.ts
  packages/twenty-server/src/modules/calendar/services/google-calendar-full-sync.service.ts
  packages/twenty-server/src/modules/messaging/services/gmail-full-sync/gmail-full-sync.service.ts
  yarn.lock
Labels: PR: awaiting author

#4496 refactor: improve Settings supported field types validation
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/types/SettingsSupportedFieldType.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getSettingsFieldTypeConfig.ts
  packages/twenty-front/src/modules/settings/data-model/utils/isFieldTypeSupportedInSettings.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting author

#4644 Update yarn commands
  .github/workflows/ci-server.yaml
  .vscode/launch.json
  package.json
  packages/twenty-docs/docs/contributor/server/server.mdx
  packages/twenty-docs/docs/start/local-setup/docker-setup.mdx
  packages/twenty-docs/docs/start/local-setup/yarn-setup.mdx
  packages/twenty-docs/docs/start/self-hosting/cloud-providers.mdx
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
  packages/twenty-front/src/modules/ui/display/icon/constants/index.ts
  packages/twenty-server/package.json
  packages/twenty-server/project.json
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/scripts/run-integration.sh
  packages/twenty-server/src/utils/generate-front-config.ts
Labels: PR: awaiting review

#4504 refactor: merge FieldType and FieldMetadataType
  packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-metadata/utils/parseFieldType.ts
  packages/twenty-front/src/modules/object-metadata/utils/shouldFieldBeQueried.ts
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/ChipFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/DateFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/EmailFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/NumberFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/TextFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useBooleanField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useCurrencyField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useDateTimeField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useEmailField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useFullNameField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useLinkField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useNumberField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/usePhoneField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useTextField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useUuidField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/BooleanFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhoneFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldType.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__mocks__/cell.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/types/SettingsSupportedFieldType.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockColumnDefinitions.ts
Labels: PR: awaiting author

#4507 fix: fix Select field preview
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldSelectValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/selectFieldValueSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldDefaultPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldPreviewValueFromRecord.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldPreviewValueFromRecord.ts
Labels: PR: awaiting author

#4574 feat: create Integrations/IntegrationDetail page
  packages/twenty-front/public/images/integrations/airtable-logo.png
  packages/twenty-front/public/images/integrations/postgresql-logo.png
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountLoader.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysTable.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsReadDocumentationButton.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsWebhooksTable.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationComponent.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationGroup.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/__stories__/SettingsBilling.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx
  packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeys.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooks.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDetail.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrations.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationDetail.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrations.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationAll.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationCategories.ts
  packages/twenty-front/src/pages/settings/integrations/types/SettingsIntegration.ts
  packages/twenty-front/src/pages/settings/integrations/types/SettingsIntegrationCategory.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
Labels: PR: awaiting author

#4591 feat: add Active and Add integration card displays
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/DefaultPageTitle.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationComponent.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationGroup.tsx
  packages/twenty-front/src/modules/settings/integrations/constants/MockRemoteDatabases.ts
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationRequest.ts
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationWindmill.ts
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationZapier.ts
  packages/twenty-front/src/modules/settings/integrations/hooks/useSettingsIntegrationCategories.ts
  packages/twenty-front/src/modules/settings/integrations/types/SettingsIntegration.ts
  packages/twenty-front/src/modules/settings/integrations/types/SettingsIntegrationCategory.ts
  packages/twenty-front/src/modules/settings/integrations/utils/getSettingsIntegrationAll.ts
  packages/twenty-front/src/pages/auth/__stories__/PasswordReset.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PaymentSuccess.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDetail.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrations.tsx
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationAll.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationCategories.ts
Labels: PR: awaiting author

#4513 #4298 Add emails seed data for demo and dev seeds
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/connectedAccount.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/message.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messageChannel.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messageChannelMessageAssociation.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messageParticipant.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messageThread.ts
Labels: PR: awaiting author

#4608 feat: use ApolloFactory for metadata client
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/object-metadata/components/ApolloMetadataClientProvider.tsx
Labels: PR: awaiting review

#4614 feat: add remote object integration preview
  packages/twenty-front/src/modules/settings/integrations/assets/preview-background.svg
  packages/twenty-front/src/modules/settings/integrations/assets/sync.svg
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationPreview.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDetail.tsx
Labels: PR: awaiting author

#4665 Fetch available remote tables
  packages/twenty-server/src/engine/core-modules/auth/auth.util.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/remote-table-postgres.util.ts
Labels: PR: awaiting author

#4659 Fix/enum bug
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-options-for-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-field-metadata-options.validator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/workspace-migration-enum.service.ts
Labels: PR: awaiting review

#4672 Fix encryption logic
  packages/twenty-server/src/engine/core-modules/auth/auth.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/remote-table-postgres.util.ts
Labels: PR: awaiting review

#4600 feat: add date format calendar setting
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarDateFormatSelect.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarDisplaySettings.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarTimeFormatSelect.tsx
  packages/twenty-front/src/modules/settings/accounts/constants/DateFormat.ts
  packages/twenty-front/src/modules/settings/accounts/constants/TimeFormat.ts
Labels: PR: awaiting review

#4679 4506 change field labels and field type for calendarevent object metadata to match figma
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventDetails.tsx
  packages/twenty-front/src/modules/activities/calendar/types/CalendarEvent.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-events.ts
  packages/twenty-server/src/engine/core-modules/calendar/dtos/timeline-calendar-event.dto.ts
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/calendar/repositories/calendar-event.repository.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-event.object-metadata.ts
  packages/twenty-server/src/modules/calendar/types/calendar-event.ts
  packages/twenty-server/src/modules/calendar/utils/format-google-calendar-event.util.ts
Labels: PR: awaiting author

#4593 feat: add Integrations/Integration Details/New Database page
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabase.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationNewDatabase.stories.tsx
Labels: PR: awaiting review

#4621 feat: add remote object integration databases list card
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsListCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListItemCardContent.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListSkeletonCard.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationDatabasesListCard.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/CardFooter.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDetail.tsx
  packages/twenty-front/src/testing/mock-data/remoteObjectDatabases.ts
Labels: PR: awaiting review

#4666 4643 create a pre hook for calendar events
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/calendarEventFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/timelineCalendarEventAttendeeFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/timelineCalendarEventFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/fragments/timelineCalendarEventWithTotalFragment.ts
  packages/twenty-front/src/modules/activities/calendar/queries/getTimelineCalendarEventsFromCompanyId.ts
  packages/twenty-front/src/modules/activities/calendar/queries/getTimelineCalendarEventsFromPersonId.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-pre-query-hook/workspace-pre-query-hook.config.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-pre-query-hook/workspace-pre-query-hook.module.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/calendar-event-find-many.pre-query.hook.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/calendar-event-find-one.pre-query-hook.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/services/can-access-calendar-event.service.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-query-hook.module.ts
Labels: PR: awaiting author

#4613 feat: add one liner install command
  install.sh
  packages/twenty-docker/prod/.env.example
  packages/twenty-docker/prod/docker-compose.yml
  packages/twenty-docker/prod/twenty/entrypoint.sh
  packages/twenty-docs/docs/start/self-hosting/docker-compose.mdx
Labels: PR: awaiting author

#4678 Fix: Save view by clicking outside popup while editing
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContent.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/hooks/useViewPickerPersistView.ts
Labels: PR: awaiting author

#4492 feat: address composite field
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/FilterType.ts
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/AddressFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useAddressField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/AddressFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/AddressFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldAddress.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldAddressValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-filter/types/ObjectRecordQueryFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/ui/display/icon/types/IconComponent.ts
  packages/twenty-front/src/modules/ui/field/input/components/AddressInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DoubleTextInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/PhoneInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/EntityTitleDoubleTextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/country/components/CountrySelect.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/country/constants/SelectCountryDropdownId.ts
  packages/twenty-front/src/modules/ui/input/components/internal/hooks/useCountries.ts
  packages/twenty-front/src/modules/ui/input/components/internal/phone/components/PhoneCountryPickerDropdownButton.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/phone/components/PhoneCountryPickerDropdownSelect.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/types/Country.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/type-definitions.generator.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/address.composite-type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/index.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-default-value.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-target-column-map.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/generate-default-value.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/generate-target-column-map.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/is-composite-field-metadata-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-default-value-for-type.util.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/companies-demo.json
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/company.ts
  packages/twenty-server/src/modules/company/standard-objects/company.object-metadata.ts
  packages/twenty-zapier/src/utils/computeInputFields.ts
  packages/twenty-zapier/src/utils/data.types.ts
Labels: PR: awaiting author

#4680 4586 fix workspace member feature
  packages/twenty-server/src/database/typeorm/core/migrations/1711557405330-addMissingMigration.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1711624086253-updateRefreshTokenTable.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/handle-workspace-member-deleted.job.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace-workspace-member.listener.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.module.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/delete-incomplete-workspaces.command.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.object-metadata.ts
  packages/twenty-server/tsconfig.json
Labels: PR: awaiting author

#4696 Switch timestamp to timestamptz
  packages/twenty-server/src/database/typeorm/core/migrations/1711633823798-useTimestampWithTZ.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1711619086385-useTimestampWithTZ.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/__tests__/get-field-metadata-type.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-field-metadata-type.util.ts
  packages/twenty-server/src/engine/core-modules/app-token/app-token.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/metadata-modules/data-source/data-source.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-cache-version/workspace-cache-version.entity.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/utils/field-metadata-type-to-column-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-health/utils/map-field-metadata-type-to-data-type.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/custom-table-default-column.util.ts
Labels: PR: awaiting review

#4471 fix: impossible to unselect all check box
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/SelectAllCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useRecordTableStates.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetAllRowSelectedState.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/states/hasUserSelectedAllRowsFamilyState.ts
Labels: PR: awaiting review

#4514 4410-feat(front): Implement Confirmation Prompt for Multiple Record Deletion
  packages/twenty-front/src/modules/object-record/record-action-bar/hooks/useRecordActionBar.tsx
  packages/twenty-front/src/modules/object-record/record-board/action-bar/components/RecordBoardActionBar.tsx
  packages/twenty-front/src/modules/object-record/record-table/action-bar/components/RecordTableActionBar.tsx
  packages/twenty-front/src/modules/ui/navigation/action-bar/components/ActionBar.tsx
  packages/twenty-front/src/modules/ui/navigation/action-bar/types/ActionBarEntry.ts
Labels: PR: awaiting author

#4468 Fix display empty value if boolean instead of false on show page
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelDefaultValue.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
Labels: PR: awaiting author

#4512 Fix overlay scroll gaps
  package.json
  packages/twenty-front/__mocks__/styleMock.js
  packages/twenty-front/jest.config.ts
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSection.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/__tests__/useListenScroll.test.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useListenScroll.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/isScrollingState.ts
  yarn.lock
Labels: PR: awaiting review

#4687 feat: authorize screen
  packages/twenty-front/public/images/integrations/chrome-icon.svg
  packages/twenty-front/public/images/integrations/link-apps.svg
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/authorizeApp.ts
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/modules/ui/layout/page/BlankLayout.tsx
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/pages/auth/Authorize.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
Labels: PR: awaiting author
