Repository twentyhq/twenty, pull requests merged in 2024-10, with the labels that each got.

#7320 Fix cursor should not be pointer when record image identifier is not Editable
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
Labels: -PR: awaiting author

#7337 minor fix - fixed forwardRef and unique key console errors
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx
Labels: -PR: awaiting review

#7373 Delete workflow step
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowEditStepContent.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramStepNode.tsx
  packages/twenty-front/src/modules/workflow/hooks/useDeleteOneStep.tsx
  packages/twenty-front/src/modules/workflow/utils/__tests__/removeStep.test.ts
  packages/twenty-front/src/modules/workflow/utils/findStepPosition.ts
  packages/twenty-front/src/modules/workflow/utils/findStepPositionOrThrow.ts
  packages/twenty-front/src/modules/workflow/utils/removeStep.ts
Labels: -PR: awaiting review

#7362 Changed condition on which 'Add task' button is displayed (#7333)
  packages/twenty-front/src/modules/activities/tasks/components/ObjectTasks.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskGroups.tsx
Labels: -PR: awaiting CI

#7328 Adjust Floating Input Padding and Border Color
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
Labels: -PR: awaiting author

#7200 Delete button in right drawer / side pannel
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapSoftDeleteFieldsToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerRecord.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/ui/layout/page/ShowPageContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageMoreButton.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: -PR: wip

#7245 fix: validate emails in record-fields
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/emailSchema.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
Labels: -PR: awaiting review

#7420 minor fix - reset single entity search
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAddNewCard.ts
  packages/twenty-front/src/modules/settings/data-model/constants/RelationTypes.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
Labels: -PR: awaiting review

#7423 fix: New Relation Design hot fix
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
Labels: -PR: awaiting review

#7428 Fix 'name' column wrongly added in standard objects
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-migrations-for-custom-object-relations.util.ts
  packages/twenty-server/src/engine/twenty-orm/base.workspace-entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/custom-table-default-column.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/table-default-column.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/modules/calendar/common/types/calendar-event.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/types/message.ts
Labels: -PR: awaiting review

#7436 Fix syncStageStartedAt not correctly set
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
Labels: -PR: awaiting author

#7396 Feat : Toggle Eye Icon to Expand/Collapse Kanban Card
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
Labels: -PR: awaiting review

#7307 Tab design improvements
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: -PR: awaiting review

#7448 fix: Minor bug in column scroll in mobile viewport
  packages/twenty-front/src/loading/components/__stories__/PrefetchLoading.stories.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/__stories__/EventRowMainObjectUpdated.stories.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx
Labels: -PR: awaiting author

#7441 Add missing currencies
  packages/twenty-front/src/modules/object-record/record-field/types/CurrencyCode.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldCurrencyCodes.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting author

#7470 Add delete name column from standard object tables
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-delete-name-column-standard-object-tables.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-upgrade-version.module.ts
Labels: -PR: awaiting review

#7463 0.31 changelog
  package.json
  packages/twenty-website/public/images/releases/0.31/0.31-advanced-settings.png
  packages/twenty-website/public/images/releases/0.31/0.31-search.png
  packages/twenty-website/src/content/releases/0.31.0.mdx
Labels: -PR: awaiting author

#7101 6694 remove raw queries from connected account
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/object-metadata-repository/metadata-to-repository.mapping.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/jobs/calendar-event-list-fetch.job.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-access-calendar-event.service.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-query-hook.module.ts
  packages/twenty-server/src/modules/connected-account/email-alias-manager/email-alias-manager.module.ts
  packages/twenty-server/src/modules/connected-account/email-alias-manager/services/email-alias-manager.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-access-token-manager/drivers/google/google-api-refresh-access-token.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-access-token-manager/services/refresh-access-token.service.ts
  packages/twenty-server/src/modules/connected-account/repositories/connected-account.repository.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/can-access-message-thread.service.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/messaging-query-hook.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/messaging-gmail-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-messages-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/messaging-create-company-and-contact-after-sync.job.ts
Labels: -PR: awaiting review

#7485 Fixes on messaging and calendar
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-channel-event-association.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-events.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-save-events.service.ts
  packages/twenty-server/src/modules/calendar/common/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel-event-association.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/types/calendar-event.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
Labels: -PR: awaiting author

#7438 Fix: Adjust chevron alignment to the right edge
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysTable.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsDevelopersWebhookTableRow.tsx
Labels: -PR: awaiting author

#7273 fix: Invite by email table overflows in mobile viewport
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
Labels: -PR: awaiting review

#7025 fix: Filter chips lacks width for longer values
  packages/twenty-front/src/modules/views/components/SortOrFilterChip.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
Labels: -PR: awaiting CI

#7016 fix: fixed shortcuts population
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/__stories__/AppRouter.stories.tsx
  packages/twenty-front/src/effect-components/GotoHotkeysEffect.tsx
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/app/components/App.tsx
  packages/twenty-front/src/modules/app/components/AppRouter.tsx
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/app/effect-components/CommandMenuEffect.tsx
  packages/twenty-front/src/modules/app/effect-components/GoToHotkeyItemEffect.tsx
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffect.tsx
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/app/utils/createAppRouter.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuCommands.ts
  packages/twenty-front/src/modules/command-menu/hooks/__test__/useCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useNonSystemActiveObjectMetadataItems.ts
  packages/twenty-front/src/utils/array/sortByProperty.ts
Labels: -PR: awaiting CI

#7374 7336 create contextstore
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentObjectMetadataIdState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentViewIdState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreTargetedRecordIdsState.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx
  packages/twenty-front/src/modules/views/hooks/useChangeView.ts
  packages/twenty-front/src/modules/views/hooks/useSetViewInUrl.ts
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageContextStoreEffect.tsx
Labels: -PR: awaiting review

#7377 fix: overflow issue in tableSection
  packages/twenty-front/src/modules/ui/layout/table/components/TableSection.tsx
Labels: -PR: awaiting author

#7431 7417 workflows i can send emails using the email account
  packages/twenty-emails/src/emails/workflow-action.email.tsx
  packages/twenty-emails/src/index.ts
  packages/twenty-front/src/modules/accounts/constants/GmailSendScope.ts
  packages/twenty-front/src/modules/accounts/types/ConnectedAccount.ts
  packages/twenty-front/src/modules/settings/accounts/hooks/useTriggerGoogleApisOAuth.ts
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/input/components/__stories__/Select.stories.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/utils/getStepDefaultDefinition.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/onboarding/SyncEmails.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis-oauth-common.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis-oauth-exchange-code-for-token.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis-oauth-request-code.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/utils/get-google-apis-oauth-scopes.ts
  packages/twenty-server/src/engine/core-modules/auth/utils/google-apis-set-request-extra-params.util.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.workspace-entity.ts
  packages/twenty-server/src/modules/mail-sender/exceptions/mail-sender.exception.ts
  packages/twenty-server/src/modules/mail-sender/workflow-actions/send-email.workflow-action.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/messaging-gmail-driver.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/types/workflow-step-settings.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-executor.module.ts
Labels: -PR: wip, -PR: awaiting author

#7397 Remove step 1 of new object field
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getDisabledFieldMetadataItems.ts
  packages/twenty-front/src/modules/settings/components/SettingsSkeletonLoader.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelNewFieldBreadcrumbDropDown.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsObjectNewFieldSelector.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldTypeSelect.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/ui/layout/page/SubMenuTopBarContainer.tsx
  packages/twenty-front/src/modules/views/view-picker/hooks/useGetAvailableFieldsForKanban.ts
  packages/twenty-front/src/pages/settings/Releases.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/SettingsProfile.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspace.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsNewAccount.tsx
  packages/twenty-front/src/pages/settings/crm-migration/SettingsCRMMigration.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPageContent.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldSelect.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectOverview.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldConfigure.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldSelect.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep1.stories.tsx
  packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabase.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationEditDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationShowDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrations.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/SettingsAppearance.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctions.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionsNew.tsx
Labels: -PR: awaiting review

#7487 Add webhook response graph from the last 5 days
  package.json
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookUsageGraph.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookUsageGraphEffect.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/states/webhookGraphDataState.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/call-webhook.job.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/workspace-query-runner-job.module.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  yarn.lock
Labels: -PR: awaiting author

#7274 Enhance date and time format settings to reflect system preferences
  packages/twenty-front/src/modules/localization/utils/detectTimeFormat.ts
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettingsDateFormatSelect.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettingsTimeFormatSelect.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettingsTimeZoneSelect.tsx
Labels: -PR: awaiting CI

#7292 fix: Relation picker UX improvements
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultiRecordSelect.tsx
Labels: -PR: awaiting CI

#7546 Breadcrumb DropDown improvement
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelNewFieldBreadcrumbDropDown.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsObjectNewFieldSelector.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
Labels: -PR: awaiting review

#7493 fix: Developers page is not optimised for mobile viewport
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysTable.tsx
  packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#7465 Fix hide calender icon if no deadline on task
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
Labels: -PR: awaiting review

#7364 fix: Handling filename overflow in mobile viewports
  packages/twenty-front/src/modules/activities/components/ActivityList.tsx
  packages/twenty-front/src/modules/activities/components/ActivityRow.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskList.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsNewObject.stories.tsx
Labels: -PR: awaiting CI

#7561 [search] simplify tsvector generated expression and remove deletedAt condition
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/__tests__/get-ts-vectors-column-expression.utils.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/get-ts-vector-column-expression.util.ts
Labels: -PR: awaiting review

#7555 Fix workflow statuses
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/timeline/standard-objects/timeline-activity.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-many.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-one.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-query-hook.module.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-event-listener.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
Labels: -PR: awaiting author

#7553 Add cache-flush step in Twenty upgrade command #7521
  packages/twenty-server/src/engine/core-modules/cache-storage/commands/flush-cache.command.ts
  packages/twenty-server/src/engine/core-modules/cache-storage/services/cache-storage.service.ts
Labels: -PR: awaiting review

#7566 Remove all mentions of papermark from oss.gg/twenty-side-quest directory and fix inconsistency with the notion document
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
  oss-gg/twenty-side-quest/2-tweet-about-fav-twenty-feature.md
  oss-gg/twenty-side-quest/3-bug-report.md
  oss-gg/twenty-side-quest/4-meme-magic.md
  oss-gg/twenty-side-quest/5-gif-magic.md
  oss-gg/twenty-side-quest/6-quest-wizard.md
Labels: -PR: awaiting review

#7366 docs: enhance REST API OpenAPI spec with nested filter example
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/parameters.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/parameters.utils.ts
Labels: -PR: awaiting review

#7451 Fix focused cell view
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
Labels: -PR: awaiting review

#7392 fix: filter and sort options to match order of table columns
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelectCompositeFieldSubMenu.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelectMenuItem.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/__stories__/MultipleFiltersDropdownButton.stories.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useFilterDropdown.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/contexts/ObjectFilterDropdownComponentInstanceContext.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/objectFilterDropdownFilterIsSelectedComponentState.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/objectFilterDropdownFirstLevelFilterDefinitionComponentState.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/objectFilterDropdownIsSelectingCompositeFieldComponentState.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/objectFilterDropdownSubMenuFieldTypeComponentState.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
Labels: -PR: awaiting CI

#7572 Solved two oss.gg side quests
  oss-gg/twenty-side-quest/4-meme-magic.md
  oss-gg/twenty-side-quest/5-gif-magic.md
Labels: -PR: awaiting review

#7571 Completed two more side quests and added them into their respective files
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
  oss-gg/twenty-side-quest/2-tweet-about-fav-twenty-feature.md
Labels: -PR: awaiting review

#7557 fix: Settings Navigation drawer crops elements
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
Labels: -PR: awaiting review

#7582 Oss.gg Side-Quest submission [Multiple]
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
  oss-gg/twenty-side-quest/2-tweet-about-fav-twenty-feature.md
  oss-gg/twenty-side-quest/4-meme-magic.md
  oss-gg/twenty-side-quest/5-gif-magic.md
Labels: 🕹️ oss.gg, :joystick: 400 points

#7591 Liked & Re-Tweeted oss.gg Launch Tweet. tagged @twentycrm and said I'll be contributing
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
Labels: -PR: awaiting review

#7586 Refactor action menu
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ExportRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/MultipleRecordsActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/SingleRecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuConfirmationModals.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuEntriesProvider.tsx
  packages/twenty-front/src/modules/action-menu/components/EmptyActionMenuEntriesEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/NonEmptyActionMenuEntriesEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/ActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/ActionMenuBarEntry.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/ActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/hooks/useActionMenuEntries.ts
  packages/twenty-front/src/modules/action-menu/hooks/useComputeActionsBasedOnContextStore.tsx
  packages/twenty-front/src/modules/action-menu/hooks/useHandleFavoriteButton.ts
  packages/twenty-front/src/modules/action-menu/states/actionMenuEntriesComponentSelector.ts
  packages/twenty-front/src/modules/action-menu/states/actionMenuEntriesComponentState.ts
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectMetadataItemById.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItemById.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useDeleteTableData.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useRecoilComponentValueV2.ts
Labels: -PR: awaiting review

#7569 Fix issues with Apollo cache in workflow module
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowHeader.tsx
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowVersionHeader.tsx
  packages/twenty-front/src/modules/workflow/hooks/useActivateWorkflowVersion.tsx
  packages/twenty-front/src/modules/workflow/hooks/useDeactivateWorkflowVersion.tsx
  packages/twenty-front/src/modules/workflow/hooks/useDeleteOneWorkflowVersion.tsx
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowWithCurrentVersion.tsx
Labels: -PR: wip, -PR: awaiting author

#7590 OSS.GG Submission for design challenge
  oss-gg/twenty-design-challenges/1-design-promotional-poster-20-share.md
  oss-gg/twenty-design-challenges/2-design-new-logo-twenty.md
Labels: -PR: awaiting review

#7579 fix: Set field type icon as the default icon for new fields (#7352)
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-front/src/pages/settings/data-model/constants/DefaultIconsByFieldType.ts
Labels: -PR: awaiting CI

#7589 Like & Re-Tweet oss.gg Launch Tweet (50 Points): Complete
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
Labels: -PR: awaiting review

#7603 Fix DropdownMenuInput border
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
Labels: -PR: awaiting review

#7602 Fix GraphQL Api Setters not being applied
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts
Labels: -PR: awaiting review

#7607 Fix icon button disabled border
  packages/twenty-front/src/modules/ui/input/button/components/IconButton.tsx
Labels: -PR: awaiting review

#7595 Fix field forms
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
Labels: -PR: awaiting review

#7587 minor fix - dropdown doesnt close onClick in configure step
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelNewFieldBreadcrumbDropDown.tsx
Labels: -PR: awaiting review

#7625 Design a poster promoting Twenty
  oss-gg/twenty-design-challenges/1-design-promotional-poster-20-share.md
Labels: 🕹️ oss.gg, :joystick: 300 points

#7622 Quest Gif Magic Submission
  oss-gg/twenty-side-quest/5-gif-magic.md
Labels: 🕹️ oss.gg, :joystick: 150 points

#7619 Quest meme magic submission
  oss-gg/twenty-side-quest/4-meme-magic.md
Labels: 🕹️ oss.gg, :joystick: 150 points

#7628 Fix: Nav Item Api & Webhook and Functions stay selected
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
Labels: -PR: awaiting CI

#7641 [oss.gg] Like & Retweet side quest
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#7600 fix: droppable-placeholder
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
Labels: -PR: awaiting review, 🕹️ oss.gg, :joystick: 100 points

#7644 [OSS.GG] Gif Magic Side Quest
  oss-gg/twenty-side-quest/5-gif-magic.md
Labels: 🕹️ oss.gg, :joystick: 150 points

#7642 Submission for new logo design side quest
  oss-gg/twenty-design-challenges/2-design-new-logo-twenty.md
Labels: 🕹️ oss.gg, :joystick: 300 points

#7645 Like & Re-Tweet oss.gg Launch Tweet
  oss-gg/twenty-side-quest/1-quote-tweet-20-oss-gg-launch.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#7637 Enhance postgre sql setup script and documentation for various distros 7636
  packages/twenty-postgres/linux/provision-postgres-linux.sh
Labels: -PR: awaiting author

#7525 [Fix] - Trim Names in Settings > Members table #7509
  packages/twenty-front/src/modules/ui/layout/table/components/TableRow.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
Labels: -PR: awaiting review

#7614 fix: API ObjectMetadata labelSingular and labelPlural which eventually solves typo in dropdown
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-server/src/modules/api-key/standard-objects/api-key.workspace-entity.ts
Labels: -PR: awaiting review

#7596 [Fix] - Issue with Email Validation and API Call Trigger on Login #7510
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
Labels: -PR: awaiting review

#7609 Use `<label>` HTML element when possible
  packages/twenty-chrome-extension/src/options/modules/ui/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/Checkbox.tsx
  packages/twenty-front/src/modules/ui/input/components/Radio.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/ui/input/components/Toggle.tsx
Labels: -PR: awaiting review

#7658 OSS.GG Tweet about fav feature
  oss-gg/twenty-side-quest/2-tweet-about-fav-twenty-feature.md
Labels: 🕹️ oss.gg, :joystick: 50 points

#7655 Docker cleanup
  packages/twenty-docker/Makefile
  packages/twenty-docker/twenty-website/Dockerfile
  packages/twenty-website/src/content/developers/local-setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
Labels: -PR: awaiting author, 🕹️ oss.gg, :joystick: 300 points

#7592 fix: prevent flashing of search results during input
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/object-record/hooks/useSearchRecords.ts
Labels: -PR: awaiting author

#7682 [Fix] : Horizontal scroll issue in dropdown
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageKanbanAddMenuItem.tsx
Labels: -PR: awaiting author

#7414 feat - Compact sidebar
  packages/twenty-front/src/loading/components/LeftPanelSkeletonLoader.tsx
  packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx
  packages/twenty-front/src/modules/navigation/components/MainNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/navigation/components/MobileNavigationBar.tsx
  packages/twenty-front/src/modules/navigation/components/__stories__/AppNavigationDrawer.stories.tsx
  packages/twenty-front/src/modules/navigation/hooks/useIsSettingsDrawer.ts
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerAnimatedCollapseWrapper.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerBackButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerCollapseButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemBreadcrumb.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemsCollapsedContainer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSectionTitle.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawer.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/DesktopNavDrawerWidths.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/NavDrawerWidths.ts
  packages/twenty-front/src/modules/ui/navigation/states/isNavigationDrawerExpanded.ts
  packages/twenty-front/src/modules/ui/navigation/states/navigationDrawerExpandedMemorizedState.ts
Labels: -PR: wip, -PR: awaiting author

#7588 Update searchVector at label identifier update for custom fields
  packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-32/0-32-simplify-search-vector-expression.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-32/0-32-simplify-search-vector-expression.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1728999374151-addConstraintOnIndexMetadata.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-search-resolver.service.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/search/search.module.ts
  packages/twenty-server/src/engine/metadata-modules/search/search.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/ts-vector-column-action.factory.ts
  packages/twenty-server/src/engine/twenty-orm/custom.workspace-entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/default-feature-flags.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-field-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-index-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/__tests__/get-ts-vectors-column-expression.utils.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/get-ts-vector-column-expression.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/is-searchable-field.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.service.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
Labels: -PR: awaiting review

#7747 update makefile rules to use docker run
  Makefile
  packages/twenty-website/src/content/developers/local-setup.mdx
Labels: -PR: awaiting CI

#7263 Fixes #7105: Fixed column header on Kanban boards
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardStickyHeaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/contexts/RecordBoardContext.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumn.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/contexts/RecordBoardColumnContext.ts
  packages/twenty-front/src/modules/object-record/record-board/scopes/RecordBoardScope.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/contexts/RecordIndexRootPropsContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCheckboxColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/isRecordTableScrolledTopComponentState.ts
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: -PR: awaiting author

#7736 Refactor Redis connections to use Redis URL - closes #7421
  packages/twenty-docker/.env.example
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/manifests/deployment-worker.yaml
  packages/twenty-docker/k8s/terraform/deployment-server.tf
  packages/twenty-docker/k8s/terraform/deployment-worker.tf
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/src/engine/core-modules/cache-storage/cache-storage.module-factory.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/message-queue/drivers/bullmq.driver.ts
  packages/twenty-server/src/engine/core-modules/message-queue/message-queue.module-factory.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting author

#7785 fix(front): move "Add to favorites" btn to start of action menu
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/SingleRecordActionMenuEntriesSetter.tsx
Labels: -PR: awaiting review

#7800 added left padding in filter chip
  packages/twenty-front/src/modules/views/components/SortOrFilterChip.tsx
Labels: -PR: awaiting CI

#7618 fix: Blocklist table optimised for all viewports
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsBlocklistTable.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsBlocklistTableRow.tsx
Labels: -PR: awaiting CI

#7805 Improve error message for Graphql API
  packages/twenty-server/src/engine/decorators/auth/auth-user.decorator.ts
Labels: -PR: awaiting author

#7581 Bug Fix: created new div and p tag styles and wrap it on the workspace member as container
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreviewCard.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelObjectSummary.tsx
Labels: -PR: awaiting author

#7659 Fix Google Auth displays Status: 401 on screen
  packages/twenty-server/src/engine/core-modules/auth/auth.exception.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/filters/auth-oauth-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts
  packages/twenty-server/src/utils/apply-cors-to-exceptions.ts
Labels: blocked: product specs needed

#7795 [FIX] fix navigation overflow
  packages/twenty-front/src/modules/favorites/components/WorkspaceFavorites.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerOpenedSection.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItemsWrapper.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerAnimatedCollapseWrapper.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/contexts/ScrollWrapperContexts.tsx
Labels: -PR: awaiting CI

#7720 add dynamic dates for webhookGraphDataUsage
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/isAnalyticsEnabledState.ts
  packages/twenty-front/src/modules/localization/constants/DateFormatWithoutYear.ts
  packages/twenty-front/src/modules/localization/utils/__tests__/detectDateFormat.test.ts
  packages/twenty-front/src/modules/localization/utils/__tests__/detectTimeFormat.test.ts
  packages/twenty-front/src/modules/localization/utils/__tests__/formatDateISOStringToDateTimeSimplified.test.js
  packages/twenty-front/src/modules/localization/utils/detectDateFormat.ts
  packages/twenty-front/src/modules/localization/utils/detectTimeFormat.ts
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToDateTimeSimplified.ts
  packages/twenty-front/src/modules/localization/utils/getDateFormatFromWorkspaceDateFormat.ts
  packages/twenty-front/src/modules/localization/utils/getTimeFormatFromWorkspaceTimeFormat.ts
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookTooltip.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookUsageGraph.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookUsageGraphEffect.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/constants/WebhookGraphApiOptionsMap.ts
  packages/twenty-front/src/modules/settings/developers/webhook/hooks/useGraphData.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/utils/__tests__/fetchGraphDataOrThrow.test.js
  packages/twenty-front/src/modules/settings/developers/webhook/utils/fetchGraphDataOrThrow.ts
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettings.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettingsDateFormatSelect.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/DateTimeSettingsTimeFormatSelect.tsx
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
Labels: -PR: awaiting review

#7798 Use search instead of findMany in relation pickers
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffect.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsRelationPickerEffect.tsx
  packages/twenty-front/src/modules/object-record/hooks/useSearchRecords.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationFromManyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useRelationPickerEntitiesOptions.ts
  packages/twenty-front/src/modules/object-record/utils/generateSearchRecordsQuery.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchEntityQuery.test.tsx
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-search-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-resolver-args.util.ts
Labels: -PR: awaiting review

#7832 Fix custom index creation missing indexFieldMetadatas
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/search/search.service.ts
Labels: -PR: awaiting review

#7742 7665 handle the select all case inside the action menu
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ExportRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/MultipleRecordsActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/SingleRecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenuEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/ActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/hooks/__tests__/useExportRecordData.test.ts
  packages/twenty-front/src/modules/action-menu/hooks/useExportRecordData.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreNumberOfSelectedRecordsState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreTargetedRecordIdsState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreTargetedRecordsRuleState.ts
  packages/twenty-front/src/modules/context-store/utils/__tests__/computeContextStoreFilters.test.ts
  packages/twenty-front/src/modules/context-store/utils/computeContextStoreFilters.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectMetadataItemById.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItemById.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/turnFiltersIntoQueryFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnFiltersIntoQueryFilter.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreNumberOfSelectedRecordsEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreObjectMetadataEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoard.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useRecordData.test.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useDeleteTableData.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordData.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableInternalEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useLeaveTableFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useRecordTableStates.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCheckboxColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/unselectedRowIdsComponentSelector.ts
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  packages/twenty-front/src/modules/views/utils/getQueryVariablesFromView.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageContextStoreEffect.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageEffect.tsx
  packages/twenty-front/src/testing/jest/JestContextStoreSetter.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksAndContextStoreWrapper.tsx
Labels: -PR: awaiting review

#7797 fix: use <button> tag for buttons
  packages/twenty-front/src/modules/ui/layout/dropdown/components/StyledHeaderDropdownButton.tsx
Labels: -PR: awaiting review

#7925 Add simplify-search-vector-expression to upgrade 0-32 command
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-32/0-32-simplify-search-vector-expression.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-simplify-search-vector-expression.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.module.ts
Labels: -PR: awaiting review

#7913 Secure connexion between TinyBird and webhookResponseGraph
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-server.yaml
  .vscode/settings.json
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/states/currentUserState.ts
  packages/twenty-front/src/modules/settings/developers/webhook/components/SettingsDevelopersWebhookUsageGraphEffect.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/hooks/__tests__/useAnalyticsTinybirdJwt.test.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/hooks/useAnalyticsTinybirdJwt.ts
  packages/twenty-front/src/modules/settings/developers/webhook/hooks/useGraphData.tsx
  packages/twenty-front/src/modules/settings/developers/webhook/utils/fetchGraphDataOrThrow.ts
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.module.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.resolver.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.service.spec.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/user/user.module.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
Labels: -PR: awaiting author

#7594 Add the role=button to search
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerAnimatedCollapseWrapper.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
Labels: -PR: awaiting review

#7769 fix: hidden settings menu affects settings layout
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
  packages/twenty-front/src/modules/app/effect-components/GoToHotkeyItemEffect.tsx
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffect.tsx
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffectsProvider.tsx
  packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/__tests__/useGoToHotkeys.test.tsx
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts
Labels: -PR: awaiting author

#7730 Left Padding removed in Settings Page Tabs
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
Labels: -PR: awaiting review

#7939 7415 serverless functions update environment variables in a dedicated tab in settings functions not a env file
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/SettingsServerlessFunctionCodeEditor.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionSettingsTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTabEnvironmentVariableTableRow.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTabEnvironmentVariablesSection.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/fragments/serverlessFunctionFragment.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/mutations/deleteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/queries/findManyServerlessFunctions.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/queries/findOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useDeleteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useGetManyServerlessFunctions.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useGetOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useServerlessFunctionUpdateFormState.ts
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-server/src/database/typeorm/metadata/migrations/1729162426186-updateServerlessFunctionColumns.ts
  packages/twenty-server/src/engine/core-modules/session-storage/session-storage.module-factory.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function-id.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.entity.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.module.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/serverless-functions.integration-spec.ts
Labels: -PR: awaiting review

#7956 Fix redis connection
  packages/twenty-server/src/engine/core-modules/cache-storage/cache-storage.module-factory.ts
  packages/twenty-server/src/engine/core-modules/cache-storage/cache-storage.module.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/message-queue/message-queue.module-factory.ts
  packages/twenty-server/src/engine/core-modules/redis-client/redis-client.module.ts
  packages/twenty-server/src/engine/core-modules/redis-client/redis-client.service.ts
Labels: -PR: awaiting review

#7954 7499 refactor right drawer to have contextual actions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/MultipleRecordsActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/SingleRecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/components/ActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBarEntry.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenuBarEntry.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/ActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBarEntry.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordShowActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/states/recordIndexActionMenuDropdownPositionComponentState.ts
  packages/twenty-front/src/modules/action-menu/types/ActionMenuType.ts
  packages/twenty-front/src/modules/context-store/components/SetMainContextStoreComponentInstanceIdEffect.tsx
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentObjectMetadataIdComponentState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentObjectMetadataIdState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentViewIdComponentState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreCurrentViewIdState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreNumberOfSelectedRecordsComponentState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreNumberOfSelectedRecordsState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreTargetedRecordsRuleComponentState.ts
  packages/twenty-front/src/modules/context-store/states/contexts/ContextStoreComponentInstanceContext.tsx
  packages/twenty-front/src/modules/context-store/states/mainContextStoreComponentInstanceId.ts
  packages/twenty-front/src/modules/context-store/utils/__tests__/computeContextStoreFilters.test.ts
  packages/twenty-front/src/modules/context-store/utils/computeContextStoreFilters.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreNumberOfSelectedRecordsEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreObjectMetadataEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useRecordData.test.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordData.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainerContextStoreEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useTriggerActionMenuDropdown.ts
  packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/RightDrawerContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageContextStoreEffect.tsx
  packages/twenty-front/src/testing/jest/JestContextStoreSetter.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksAndContextStoreWrapper.tsx
  packages/twenty-ui/src/theme/constants/BackgroundDark.ts
  packages/twenty-ui/src/theme/constants/BackgroundLight.ts
Labels: -PR: awaiting review

#7940 fix: Default View Font Color and Reordering
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
Labels: -PR: awaiting review

#7953 Implement search for rich text fields and use it for notes
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-field.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/get-ts-vector-column-expression.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/is-searchable-field.util.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
Labels: -PR: awaiting review

#7807 Multiple operations on webhooks
  packages/twenty-front/src/modules/settings/developers/types/webhook/Webhook.ts
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/constants/WebhookEmptyOperation.ts
  packages/twenty-front/src/pages/settings/developers/webhooks/types/WebhookOperationsType.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-copy-webhook-operation-into-operations-command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/call-webhook-jobs.job.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-default-value.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-webhooks.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/webhooks.integration-spec.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: wip, -PR: awaiting author

#7976 Chip right height according to view
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-ui/src/display/chip/components/AvatarChip.tsx
  packages/twenty-ui/src/display/chip/components/Chip.tsx
Labels: -PR: awaiting author

#7909 Use search in multi object pickers
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchMatchesSearchFilterAndSelectedItemsQuery.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchMatchesSearchFilterAndToSelectQuery.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useSearchFilterPerMetadataItem.ts
  packages/twenty-front/src/modules/object-record/utils/isObjectMetadataItemSearchable.ts
  packages/twenty-front/src/modules/object-record/utils/isObjectMetadataItemSearchableInCombinedRequest.ts
Labels: -PR: awaiting review

#8011 Use 'role' = button for chip navigation
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-index/contexts/RecordIndexRootPropsContext.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-ui/src/display/chip/components/AvatarChip.tsx
Labels: -PR: awaiting review

#8028 Prevent workflow right drawer flickering when selecting an action type
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/utils/addCreateStepNodes.ts
Labels: -PR: awaiting review

#8024 Add Manual Triggers
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageIcons.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageTitles.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowSelectTriggerType.tsx
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditGenericFormBase.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditTriggerDatabaseEventForm.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditTriggerManualForm.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/constants/CreateStepStepId.ts
  packages/twenty-front/src/modules/workflow/constants/EmptyTriggerStepId.ts
  packages/twenty-front/src/modules/workflow/constants/ManualTriggerAvailabilityOptions.ts
  packages/twenty-front/src/modules/workflow/constants/TriggerTypes.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getManualTriggerDefaultSettings.ts
  packages/twenty-front/src/modules/workflow/utils/getStepDefaultDefinition.ts
  packages/twenty-front/src/modules/workflow/utils/getTriggerDefaultDefinition.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/types/workflow-trigger.type.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-version-can-be-activated.util.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
  packages/twenty-server/src/utils/assert.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#8034 Text area using variables
  package.json
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvasReadonlyEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/hooks/useStartNodeCreation.ts
  packages/twenty-front/src/modules/workflow/search-variables/components/VariableTagInput.tsx
  packages/twenty-front/src/modules/workflow/search-variables/utils/__tests__/initializeEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/__tests__/parseEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/initializeEditorContent.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/parseEditorContent.ts
  yarn.lock
Labels: -PR: awaiting review

#8139 Update 3-create-custom-interfact-theme-20.md
  oss-gg/twenty-design-challenges/3-create-custom-interfact-theme-20.md
Labels: -PR: awaiting review

#8123 Refactor object metadata service
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-migration.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-related-records.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-default-fields-for-custom-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-migrations-for-custom-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-sync-label-name.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-inactive-workspace.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-icons.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity-target.workspace-entity.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity.workspace-entity.ts
  packages/twenty-server/src/modules/activity/standard-objects/comment.workspace-entity.ts
  packages/twenty-server/src/modules/api-key/standard-objects/api-key.workspace-entity.ts
  packages/twenty-server/src/modules/attachment/standard-objects/attachment.workspace-entity.ts
  packages/twenty-server/src/modules/blocklist/standard-objects/blocklist.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel-event-association.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event-participant.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event.workspace-entity.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.workspace-entity.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-participant.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-thread-subscriber.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-thread.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note-target.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task-target.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
  packages/twenty-server/src/modules/timeline/standard-objects/audit-log.workspace-entity.ts
  packages/twenty-server/src/modules/timeline/standard-objects/behavioral-event.workspace-entity.ts
  packages/twenty-server/src/modules/timeline/standard-objects/timeline-activity.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-field.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-group.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-sort.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-event-listener.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#8148 Handle NBSP in tiptap parsing
  packages/twenty-front/src/modules/workflow/search-variables/utils/__tests__/parseEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/parseEditorContent.ts
Labels: -PR: awaiting author

#8125 Fix country selector text overflow issue
  packages/twenty-front/src/modules/ui/field/input/components/AddressInput.tsx
  packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx
Labels: -PR: awaiting review

#8073 fix for horizontal bar while login in
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
Labels: -PR: awaiting author

#8147 fix: Country Dropdown not closing with AddressInput
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useDropdown.ts
Labels: -PR: awaiting review

#8030 add twenty-tinybird package
  .github/workflows/ci-tinybird.yaml
  .gitignore
  packages/twenty-tinybird/.gitignore
  packages/twenty-tinybird/.tinyenv
  packages/twenty-tinybird/README.md
  packages/twenty-tinybird/datasources/event.datasource
  packages/twenty-tinybird/datasources/fixtures/event.csv
  packages/twenty-tinybird/datasources/fixtures/pageview.csv
  packages/twenty-tinybird/datasources/pageview.datasource
  packages/twenty-tinybird/datasources/serverlessFunctionEventMV.datasource
  packages/twenty-tinybird/datasources/webhookEventMV.datasource
  packages/twenty-tinybird/includes/timeSeries.incl
  packages/twenty-tinybird/pipes/getServerlessFunctionDuration.pipe
  packages/twenty-tinybird/pipes/getServerlessFunctionErrors.pipe
  packages/twenty-tinybird/pipes/getWebhookAnalytics.pipe
  packages/twenty-tinybird/pipes/materializeServerlessFunctionEvent.pipe
  packages/twenty-tinybird/pipes/materializeWebhookEvent.pipe
  packages/twenty-tinybird/requirements.txt
  packages/twenty-tinybird/scripts/append_fixtures.sh
  packages/twenty-tinybird/scripts/exec_test.sh
  packages/twenty-tinybird/tests/example.yml
  packages/twenty-tinybird/tests/regression.yaml
Labels: -PR: awaiting author

#8166 8130 creating a new company in twenty doesnt activate on zapier
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-copy-webhook-operation-into-operations-command.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/call-webhook-jobs.job.ts
  packages/twenty-zapier/src/triggers/trigger_record.ts
  packages/twenty-zapier/src/utils/triggers/triggers.utils.ts
Labels: -PR: awaiting author

#8194 Added feature flag for advanced filter
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelect.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting CI

#7823 Delete unused objects
  packages/twenty-front/src/modules/activities/files/types/Attachment.ts
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivities.test.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useCreateActivityInDB.test.tsx
  packages/twenty-front/src/modules/activities/tasks/hooks/__tests__/useCompleteTask.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapSoftDeleteFieldsToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/personFragments.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecordMutation.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreasheetImportDialog.test.ts
  packages/twenty-front/src/modules/search/hooks/__mocks__/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockCompanies.ts
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/remote-table-relations.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/utils/build-migrations-to-remove-remote-table-relations.util.ts
  packages/twenty-server/src/engine/twenty-orm/custom.workspace-entity.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/notes-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-object.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity-target.workspace-entity.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity.workspace-entity.ts
  packages/twenty-server/src/modules/activity/standard-objects/comment.workspace-entity.ts
  packages/twenty-server/src/modules/attachment/standard-objects/attachment.workspace-entity.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/query-hooks/workspace-member-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/activities.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/activity-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/attachments.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/comments.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-activities.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-activity-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-attachments.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-comments.integration-spec.ts
Labels: -PR: awaiting review

#8178 Update action menu bar
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBarAllActionsButton.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBarEntry.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
Labels: -PR: awaiting author

#8218 Fix SimplifySearchVectorExpressionCommand
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-simplify-search-vector-expression.ts
Labels: -PR: awaiting review

#8208 Fix empty option selected in single entity select
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
Labels: -PR: awaiting review

#8236 Fix context store filters
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
Labels: -PR: awaiting review

#8238 Ensure the text of select control is aligned on the left
  packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx
Labels: type: bug, scope: front

#8250 Fix logged out scopeId error
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
Labels: -PR: awaiting review

#7419 fix #7085 breadcrumb fix for mobile viewport
  packages/twenty-front/src/modules/navigation/components/MobileNavigationBar.tsx
  packages/twenty-front/src/modules/navigation/hooks/useOpenSettings.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionShowContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationEditDatabaseConnectionContent.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/SubMenuTopBarContainer.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/Breadcrumb.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/MobileBreadcrumb.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/__stories__/Breadcrumb.stories.tsx
  packages/twenty-ui/src/navigation/index.ts
Labels: -PR: awaiting author
