Repository twentyhq/twenty, pull requests merged in 2024-08, with the labels that each got.

#6230 file storage workspace id prefix
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-update-file-folder-structure.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/index.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/attachment-query-result-getter.handler.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/interfaces/query-result-getter-handler.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/resolvers/file-upload.resolver.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/services/file-upload.service.ts
  packages/twenty-server/src/engine/core-modules/file/file.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/file/file.utils.ts
  packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts
  packages/twenty-server/src/engine/core-modules/file/resolvers/file-upload.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/file/resolvers/file-upload.resolver.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/interfaces/storage-driver.interface.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/local.driver.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/s3.driver.ts
  packages/twenty-server/src/engine/integrations/file-storage/file-storage.service.ts
  packages/twenty-server/src/engine/integrations/file-storage/interfaces/file-storage-exception.ts
Labels: PR: awaiting review

#6494 Fix timelineActivity updated fields
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/integrations/event-emitter/types/object-record-update.event.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/__tests__/object-record-changed-values.spec.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/object-record-changed-values.ts
Labels: PR: awaiting review

#6473 Make api name editable and add expiry
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/useCleanRecoilState.ts
  packages/twenty-front/src/modules/settings/developers/components/ApiKeyNameInput.tsx
  packages/twenty-front/src/modules/settings/developers/hooks/__tests__/useGeneratedApiKeys.test.ts
  packages/twenty-front/src/modules/settings/developers/hooks/useGeneratedApiKeys.ts
  packages/twenty-front/src/modules/settings/developers/states/generatedApiKeyFamilyState.ts
  packages/twenty-front/src/modules/settings/developers/states/generatedApiKeyTokenState.ts
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/testing/constants/UntestedAppPaths.ts
Labels: PR: awaiting author

#6495 Add skip option at sign-up
  packages/twenty-front/src/pages/onboarding/InviteTeam.tsx
Labels: PR: awaiting review

#6542 Timeline log displays empty when field value deleted
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiff.tsx
Labels: PR: awaiting review

#6545 6446 improve information banner component to make it scale better
  packages/twenty-front/src/modules/information-banner/InformationBanner.tsx
  packages/twenty-front/src/modules/information-banner/InformationBannerReconnectAccount.tsx
  packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx
  packages/twenty-front/src/modules/information-banner/components/InformationBannerWrapper.tsx
  packages/twenty-front/src/modules/information-banner/components/reconnect-account/InformationBannerReconnectAccountEmailAliases.tsx
  packages/twenty-front/src/modules/information-banner/components/reconnect-account/InformationBannerReconnectAccountInsufficientPermissions.tsx
  packages/twenty-front/src/modules/information-banner/enums/InformationBannerKeys.enum.ts
  packages/twenty-front/src/modules/information-banner/hooks/useAccountToReconnect.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/ui/layout/page/SubMenuTopBarContainer.tsx
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/connected-account/services/accounts-to-reconnect.service.ts
  packages/twenty-server/src/modules/connected-account/types/accounts-to-reconnect-key-value.type.ts
  packages/twenty-server/src/modules/connected-account/types/connected-account-key-value.type.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
Labels: PR: awaiting review

#6505 Add custom field types on seed
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/typeorm-seeds/metadata/fieldsMetadata.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/people.ts
Labels: PR: awaiting author

#6371 Webhook wip
  packages/twenty-front/src/modules/activities/timelineActivities/utils/__tests__/filterOutInvalidTimelineActivities.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useIsFieldInputOnly.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/ui/navigation/link/components/UndecoratedLink.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: PR: awaiting review

#6558 Remove fileService getFileStream fallback after completed migration
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
Labels: PR: awaiting review

#6500 Remove message thread id from mcma and update scripts
  packages/twenty-server/src/database/typeorm-seeds/workspace/message-channel-message-associations.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/message-find-many.pre-query.hook.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/message-find-one.pre-query-hook.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel-message-association.repository.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-thread.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message-thread.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
Labels: PR: awaiting review

#6557 Force order in navigation panel for notes and tasks
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
Labels: PR: awaiting review

#6459 Build exceptions and handler
  packages/twenty-server/src/engine/core-modules/auth/auth.exception.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/verify-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/filters/auth-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/auth/filters/auth-rest-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/jwt.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/microsoft.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/utils/google-apis-set-request-extra-params.util.ts
Labels: PR: awaiting review

#6553 6382 create a command to add a uservar in the key value pair table for every account which needs to reconnect
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-set-user-vars-accounts-to-reconnect.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-set-workspace-activation-status.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/connected-account/services/accounts-to-reconnect.service.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
Labels: PR: awaiting review

#6550 Fix images in note rich text
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/activity-query-result-getter.handler.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/attachment-query-result-getter.handler.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/person-query-result-getter.handler.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/workspace-member-query-result-getter.handler.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/file-upload.module.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/services/file-upload.service.spec.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/services/file-upload.service.ts
  packages/twenty-server/src/engine/core-modules/file/file.module.ts
Labels: PR: awaiting review

#6482 [Fix] URL inputs to not submit numeric hostnames and url without domain
  packages/twenty-front/src/utils/validation-schemas/absoluteUrlSchema.ts
Labels: PR: awaiting review

#6590 Fix auth exceptions
  packages/twenty-server/src/engine/core-modules/auth/auth.exception.ts
  packages/twenty-server/src/engine/core-modules/auth/filters/auth-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.ts
  packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
Labels: PR: awaiting review

#6593 Fix query runner exceptions not being handled properly
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/create-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/create-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/delete-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/delete-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-duplicates-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/update-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/update-one-resolver.factory.ts
Labels: PR: awaiting review

#6591 Improve QueryFailedError message in sync-metadata
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.service.ts
Labels: PR: awaiting review

#6575 Fixed restrictive URL sanity check #6570
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/utils/__tests__/is-url.test.ts
  packages/twenty-front/src/utils/is-url.ts
Labels: PR: awaiting review

#6537 Issue6335: RecordInlineCell tree refactor with RecordInlineCellContext
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContext.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellValue.tsx
Labels: PR: awaiting review

#6065 Fixed: Drag and Drop Causes Flashing and Disappearing Cards
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
Labels: PR: awaiting review

#6572 6430 Part 1: remove all raw queries from the messaging and calendar modules
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/object-metadata-repository/metadata-to-repository.mapping.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company.service.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/jobs/messaging-blocklist-item-delete-messages.job.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/listeners/messaging-blocklist.listener.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/can-access-message-thread.service.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/messaging-query-hook.module.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel-message-association.repository.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel.repository.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-participant.repository.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-thread.repository.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message.repository.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-message-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-messages-import.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/messaging-gmail-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-messages-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-ongoing-stale.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-error-handling.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/messaging-create-company-and-contact-after-sync.job.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.ts
Labels: PR: awaiting review

#5787 [Issue-5772] Add sort feature on settings tables
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/sortCachedObjectEdges.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useGetObjectOrderByField.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectOrderByField.ts
  packages/twenty-front/src/modules/object-metadata/utils/getOrderByForFieldMetadataType.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationOrderBy.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useCombinedGetTotalCount.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
  packages/twenty-front/src/modules/object-record/select/hooks/useRecordsForSelect.ts
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/states/settingsObjectFieldsFamilyState.ts
  packages/twenty-front/src/modules/spreadsheet-import/components/SpreadsheetImportTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/ExampleTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/types/OrderBy.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/table/components/SortableTableHeader.tsx
  packages/twenty-front/src/modules/ui/layout/table/components/TableHeader.tsx
  packages/twenty-front/src/modules/ui/layout/table/hooks/__tests__/useSortedArray.test.tsx
  packages/twenty-front/src/modules/ui/layout/table/hooks/useSortedArray.ts
  packages/twenty-front/src/modules/ui/layout/table/states/sortedFieldByTableFamilyState.ts
  packages/twenty-front/src/modules/ui/layout/table/types/TableFieldMetadata.ts
  packages/twenty-front/src/modules/ui/layout/table/types/TableMetadata.ts
  packages/twenty-front/src/modules/ui/layout/table/types/TableSortValue.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPage.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPageContent.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldTable.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/constants/SettingsObjectTableMetadata.ts
  packages/twenty-front/src/pages/settings/data-model/hooks/useMapFieldMetadataItemToSettingsObjectDetailTableItem.ts
  packages/twenty-front/src/pages/settings/data-model/types/SettingsObjectDetailTableItem.ts
  packages/twenty-front/src/pages/settings/data-model/types/SettingsObjectTableItem.ts
  packages/twenty-front/src/pages/settings/data-model/utils/getSettingsObjectFieldType.ts
  packages/twenty-front/src/testing/mock-data/tableData.ts
Labels: PR: awaiting review

#6539 feat(e2e): twenty-e2e-testing with playwright
  package.json
  packages/twenty-e2e-testing/.env.example
  packages/twenty-e2e-testing/.gitignore
  packages/twenty-e2e-testing/README.md
  packages/twenty-e2e-testing/e2e/companies.spec.ts
  packages/twenty-e2e-testing/package.json
  packages/twenty-e2e-testing/playwright.config.ts
  yarn.lock
Labels: PR: awaiting author

#6622 Add workflow run entity
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/actor.composite-type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.service.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.module.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/jobs/workflow-event-trigger.job.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/jobs/workflow-trigger-job.module.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.service.ts
Labels: PR: awaiting review

#6595 Use twentyORM in Timeline messaging
  packages/twenty-front/src/hooks/useIsMatchingLocation.ts
  packages/twenty-front/src/modules/activities/emails/components/MessageThreadSubscribersChip.tsx
  packages/twenty-front/src/modules/object-metadata/utils/generateDefaultRecordChipData.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/spreadsheet-import/utils/findUnmatchedRequiredFields.ts
  packages/twenty-front/src/modules/ui/input/components/Toggle.tsx
  packages/twenty-server/src/engine/core-modules/messaging/dtos/timeline-thread-participant.dto.ts
  packages/twenty-server/src/engine/core-modules/messaging/services/get-messages.service.ts
  packages/twenty-server/src/engine/core-modules/messaging/services/timeline-messaging.service.ts
  packages/twenty-server/src/engine/core-modules/messaging/timeline-messaging.module.ts
  packages/twenty-server/src/engine/core-modules/messaging/timeline-messaging.resolver.ts
  packages/twenty-server/src/engine/core-modules/messaging/timeline-messaging.service.ts
  packages/twenty-server/src/engine/core-modules/messaging/utils/extract-participant-summary.util.ts
  packages/twenty-server/src/engine/core-modules/messaging/utils/filter-active-participants.util.ts
  packages/twenty-server/src/engine/core-modules/messaging/utils/format-thread-participant.util.ts
  packages/twenty-server/src/engine/core-modules/messaging/utils/format-threads.util.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
Labels: PR: awaiting review

#6466 added typechecking for all ts files
  nx.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/ui/display/status/components/__stories__/Status.stories.tsx
  packages/twenty-front/src/utils/__tests__/title-utils.test.ts
  packages/twenty-front/tsconfig.build.json
  packages/twenty-front/tsconfig.dev.json
  packages/twenty-front/tsconfig.json
  packages/twenty-front/vite.config.ts
  packages/twenty-ui/.storybook/main.ts
  packages/twenty-ui/src/display/banner/components/__stories__/Banner.stories.tsx
  packages/twenty-ui/src/utilities/config/index.ts
  packages/twenty-ui/tsconfig.build.json
  packages/twenty-ui/tsconfig.dev.json
  packages/twenty-ui/tsconfig.json
  packages/twenty-ui/vite.config.ts
Labels: PR: awaiting author

#6635 corrected targetableobject being undefined when clicked on create task in command menu
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
Labels: PR: awaiting author

#6702 Check workflow version is valid before publishing
  packages/twenty-server/src/engine/core-modules/workflow/filters/workflow-trigger-graphql-api-exception.filter.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-workflow-version-is-valid.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.workspace-service.ts
Labels: PR: awaiting review

#6704 6687 change messaging import cron job to run every minute
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/commands/messaging-messages-import.cron.command.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-messages-import.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/constants/messaging-gmail-users-messages-get-batch-size.constant.ts
Labels: PR: awaiting review

#6716 Update workflow version struct
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-action.type.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-settings.type.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-step.type.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-trigger.type.ts
  packages/twenty-server/src/modules/workflow/workflow-action-executor/workflow-action-executor.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-action-executor/workflow-action-executor.factory.ts
  packages/twenty-server/src/modules/workflow/workflow-action-executor/workflow-action-executor.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-executor.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-executor.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executor.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executor.factory.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executor.interface.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executor.module.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executors/code-action-executor.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-workflow-version-is-valid.ts
Labels: PR: awaiting author

#6645 Created a specific scroll wrapper context per scroll wrapper and made ScrollTop and ScrollLeft componentStates
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventList.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/settings/components/SettingsPageContainer.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
  packages/twenty-front/src/modules/ui/layout/page/ShowPageContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/contexts/ScrollWrapperContexts.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/__tests__/useScrollWrapperScopedRef.test.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/internal/useScrollStates.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useScrollLeftValue.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useScrollTopValue.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useScrollWrapperScopedRef.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollLeftComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollLeftState.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollTopComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollTopState.ts
  packages/twenty-front/src/pages/settings/Releases.tsx
Labels: PR: awaiting review

#6705 6686 Add try catch on every cron job, and send exception to exceptionHandler
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-event-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-message-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-messages-import.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-ongoing-stale.cron.job.ts
Labels: PR: awaiting review

#6715 6654 serverless functions add a deploy button disable deploy when autosave
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/object-record/hooks/useRestoreManyRecords.ts
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTabEffect.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/fragments/serverlessFunctionFragment.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/mutations/executeOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/mutations/publishOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/queries/findOneServerlessFunctionSourceCode.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/__tests__/useServerlessFunctionUpdateFormState.test.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useDeleteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useExecuteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useGetOneServerlessFunctionSourceCode.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/usePublishOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useServerlessFunctionUpdateFormState.ts
  packages/twenty-front/src/modules/ui/input/code-editor/components/CodeEditor.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/ResetServerlessFunctionStatesEffect.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-server/src/database/typeorm/metadata/migrations/1724171584314-updateServerlessFunction.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/interfaces/storage-driver.interface.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/local.driver.ts
  packages/twenty-server/src/engine/integrations/file-storage/drivers/s3.driver.ts
  packages/twenty-server/src/engine/integrations/file-storage/file-storage.service.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/base-serverless.driver.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/interfaces/serverless-driver.interface.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/lambda.driver.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/local.driver.ts
  packages/twenty-server/src/engine/integrations/serverless/serverless.service.ts
  packages/twenty-server/src/engine/integrations/serverless/utils/serverless-get-folder.utils.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/execute-serverless-function.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/get-serverless-function-source-code.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/publish-serverless-function.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.entity.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.exception.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.interceptor.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.module.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/utils/serverless-function-graphql-api-exception-handler.utils.ts
  packages/twenty-server/src/modules/workflow/workflow-step-executor/workflow-step-executors/code-action-executor.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting author

#6693 chore: upgrade aws-sdk v2 to v3 (#6643)
  package.json
  yarn.lock
Labels: PR: awaiting review

#6718 Fix addition of new option in select field if there are no existing options
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/generateNewSelectOption.ts
  packages/twenty-ui/src/theme/utils/__tests__/getNextThemeColor.test.ts
  packages/twenty-ui/src/theme/utils/getNextThemeColor.ts
Labels: PR: awaiting author

#6713 [Fix] Prevent fields name conflicts with composite subfields names
  packages/twenty-server/src/engine/api/__mocks__/object-metadata-item.mock.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/args-alias.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/field-alias.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/type-definitions.generator.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/__tests__/map-field-metadata-to-graphql-query.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/check-fields.utils.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/check-order-by.utils.ts
  packages/twenty-server/src/engine/api/rest/input-factories/__tests__/order-by-input.factory.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/index.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-field-name-availability.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name-validity.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/invalid-string.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/name-not-available.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/name-too-long.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-field-name-availability.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-validity.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name.utils.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/composite-column-action.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-column.factory.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-health/services/field-metadata-health.service.ts
Labels: PR: awaiting author

#6710 Added hotkeyScopes to serverless functions in settings
  packages/twenty-front/src/hooks/useHotkeyScopeOnMount.ts
  packages/twenty-front/src/modules/settings/serverless-functions/components/SettingsServerlessFunctionsTable.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionSettingsTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/types/SettingsServerlessFunctionHotKeyScope.ts
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionsNew.tsx
Labels: PR: awaiting review

#6697 Visualize Workflows
  packages/twenty-front/package.json
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageIcons.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageTitles.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflow.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagram.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagramCreateStepNode.tsx.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagramStepNode.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageHeader.tsx
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowDiagramState.ts
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowErrorState.ts
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowLoadingState.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/addCreateStepNodes.test.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/generateWorkflowDiagram.test.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/getWorkflowLastDiagramVersion.test.ts
  packages/twenty-front/src/modules/workflow/utils/addCreateStepNodes.ts
  packages/twenty-front/src/modules/workflow/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getOrganizedDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getWorkflowLastDiagramVersion.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/workflows/WorkflowShowPage.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  yarn.lock
Labels: PR: awaiting author

#6722 Fix table re-renders on update field
  packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx
  packages/twenty-front/src/modules/ui/field/display/components/EmailDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/NumberDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/PhoneDisplay.tsx
Labels: PR: awaiting review

#6717 E2E tests
  .github/workflows/playwright.yml.bak
  .gitignore
  package.json
  packages/twenty-e2e-testing/.env.example
  packages/twenty-e2e-testing/.gitignore
  packages/twenty-e2e-testing/README.md
  packages/twenty-e2e-testing/config/customreporter.ts
  packages/twenty-e2e-testing/drivers/shell_driver.ts
  packages/twenty-e2e-testing/e2e/companies.spec.ts
  packages/twenty-e2e-testing/lib/fixtures/screenshot.ts
  packages/twenty-e2e-testing/playwright.config.ts
  packages/twenty-e2e-testing/tests/companies.spec.ts
  packages/twenty-e2e-testing/tests/login.setup.ts
  packages/twenty-e2e-testing/tests/workspaces.spec.ts
  yarn.lock
Labels: PR: awaiting author

#6730 Added sync status on the FE
  packages/twenty-front/src/modules/accounts/types/CalendarChannel.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsRowRightContainer.tsx
Labels: PR: awaiting author

#6743 6655 remove field direction in message and add it in mcma
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-backfill-new-onboarding-user-vars.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-domain-to-links.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-link-fields-to-links.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-message-channel-sync-status-enum.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-set-user-vars-accounts-to-reconnect.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-set-workspace-activation-status.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-update-activities.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-update-file-folder-structure.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-set-message-direction.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messages.ts
  packages/twenty-server/src/modules/messaging/common/enums/message-direction.enum.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/compute-message-direction.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/types/message.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/messaging-create-company-and-contact-after-sync.job.ts
Labels: PR: awaiting review

#6748 5617 Create CalendarOngoingStaleCron Job
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/constants/calendar-import-ongoing-sync-timeout.constant.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/commands/calendar-ongoing-stale.cron.command.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-ongoing-stale.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/jobs/calendar-ongoing-stale.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/utils/is-sync-stale.util.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-ongoing-stale.job.ts
Labels: PR: awaiting review

#6760 Fix message direction seeds
  packages/twenty-server/src/database/typeorm-seeds/workspace/message-channel-message-associations.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/messages.ts
Labels: PR: awaiting review

#6649 Added "Add record" button in kanban view column headers dropdown
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnDropdownMenu.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewOpportunityButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAddNewCard.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAddNewOpportunity.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/utils/computeRecordBoardColumnDefinitionsFromObjectMetadata.ts
  packages/twenty-front/vite.config.ts
Labels: PR: awaiting author

#6767 Fix participant listeners
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/listeners/calendar-event-participant-person.listener.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/listeners/calendar-event-participant-workspace-member.listener.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/listeners/message-participant-person.listener.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/listeners/message-participant-workspace-member.listener.ts
Labels: PR: awaiting review

#6754 added "reply in gmail" button
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/__tests__/useRightDrawerEmailThread.test.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/types/MessageChannelMessageAssociation.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
Labels: PR: awaiting review

#6629 fix: defaultHomePagePath to be last visited page or alphatically first active object with the name
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/useDefaultHomePagePath.tsx
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useDefaultHomePagePath.test.ts
  packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts
  packages/twenty-front/src/modules/navigation/hooks/useLastVisitedObjectMetadataItem.ts
  packages/twenty-front/src/modules/navigation/hooks/useLastVisitedView.ts
  packages/twenty-front/src/modules/navigation/states/lastVisitedObjectMetadataItemIdState.ts
  packages/twenty-front/src/modules/navigation/states/lastVisitedViewPerObjectMetadataItemState.ts
  packages/twenty-front/src/modules/navigation/states/selectors/lastVisitedObjectMetadataItemIdStateSelector.ts
  packages/twenty-front/src/modules/navigation/states/selectors/lastVisitedViewPerObjectMetadataItemStateSelector.ts
  packages/twenty-front/src/modules/navigation/types/ObjectPathInfo.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsLoadEffect.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectSummaryCard.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSubItem.tsx
  packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
Labels: PR: awaiting author

#6650 Removed drag grip and accent is now tertiary in hidden fields
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-front/src/modules/views/components/ViewFieldsVisibilityDropdownSection.tsx
Labels: PR: awaiting author

#6758 fix: relation and record chip height
  packages/twenty-ui/src/display/chip/components/Chip.tsx
Labels: PR: awaiting author

#6762 Created a breadcrumb for left nav menu sub items
  packages/twenty-front/src/modules/navigation/components/MainNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItemsSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItemsSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-metadata/components/__stories__/ObjectMetadataNavItems.stories.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleTrashColumnFilter.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemBreadcrumb.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemGroup.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSubItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawer.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawerItem.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/types/NavigationDrawerSubItemState.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/utils/getNavigationSubItemState.ts
Labels: PR: awaiting CI

#6764 Create new steps in workflow editor
  packages/twenty-front/setupTests.ts
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageIcons.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageTitles.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflow.tsx
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowEditStep.tsx
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowSelectAction.tsx
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagram.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageEffect.tsx
  packages/twenty-front/src/modules/workflow/hooks/useCreateNode.tsx
  packages/twenty-front/src/modules/workflow/hooks/useRightDrawerWorkflowSelectAction.tsx
  packages/twenty-front/src/modules/workflow/hooks/useStartNodeCreation.tsx
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowDiagramTriggerNodeSelectionState.ts
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowIdState.ts
  packages/twenty-front/src/modules/workflow/states/showPageWorkflowSelectedNodeState.ts
  packages/twenty-front/src/modules/workflow/states/workflowCreateStepFromParentStepIdState.ts
  packages/twenty-front/src/modules/workflow/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/generateWorkflowDiagram.test.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/insertStep.test.ts
  packages/twenty-front/src/modules/workflow/utils/addCreateStepNodes.ts
  packages/twenty-front/src/modules/workflow/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getOrganizedDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getWorkflowLastDiagramVersion.ts
  packages/twenty-front/src/modules/workflow/utils/getWorkflowLastVersion.ts
  packages/twenty-front/src/modules/workflow/utils/insertStep.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting review

#6792 Set statuses on workflows
  packages/twenty-server/src/engine/core-modules/workflow/workflow-trigger.resolver.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/__tests__/workflow-statuses-update.job.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/workflow-statuses-update.job.ts
  packages/twenty-server/src/modules/workflow/workflow-status/listeners/workflow-version-status.listener.ts
  packages/twenty-server/src/modules/workflow/workflow-status/utils/get-status-combination-from-array.util.ts
  packages/twenty-server/src/modules/workflow/workflow-status/utils/get-status-combination-from-update.util.ts
  packages/twenty-server/src/modules/workflow/workflow-status/utils/get-statuses-from-combination.util.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.constants.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.enums.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.module.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow.module.ts
Labels: PR: awaiting review

#6796 fix: Deactivate & Activate icons should be swapped UI improvements
  packages/twenty-front/src/modules/settings/profile/components/DeleteWorkspace.tsx
Labels: PR: awaiting author

#6788 Add set custom object is soft deletable command
  packages/twenty-server/src/database/commands/active-workspaces.command.ts
  packages/twenty-server/src/database/commands/base.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-set-custom-object-is-soft-deletable.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-24/0-24-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm/metadata/metadata.datasource.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-selected-fields/graphql-selected-fields-relation.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts
Labels: PR: awaiting review

#6779 fix: Fixed API typo and webhook checkerror
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/utils/url/__tests__/isValidUrl.test.ts
  packages/twenty-front/src/utils/url/isValidUrl.ts
Labels: PR: awaiting review
