Repository twentyhq/twenty, pull requests merged in 2024-12, with the labels that each got.

#8614 Default address country 🗺️ & Phone prefix ☎️
  packages/twenty-front/src/modules/object-record/constants/FieldsNotOverwrittenAtDraft.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useNumberField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldAddressValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldPhonesValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/computeDraftValueFromFieldValue.ts
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/address/components/SettingsDataModelFieldAddressForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/address/components/SettingsDataModelFieldAddressSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getAddressFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getPhonesFieldPreviewValue.ts
  packages/twenty-front/src/modules/ui/field/display/components/PhoneDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/PhonesDisplay.tsx
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/country/components/CountrySelect.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/types/Country.ts
  packages/twenty-front/src/utils/string/stripSimpleQuotesFromString.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/field-metadata-validation.service.spec.ts
  packages/twenty-zapier/src/utils/computeInputFields.ts
Labels: -PR: wip, -PR: awaiting author

#8836 Update best-practices-front.mdx
  packages/twenty-website/src/content/developers/frontend-development/best-practices-front.mdx
Labels: -PR: awaiting review

#8814 Implement contextual actions for the workflows
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDeleteMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useExportMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useExportMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useMultipleRecordsActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/__tests__/useExportViewNoSelectionRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useExportViewNoSelectionRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useNoSelectionRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/components/SingleRecordActionMenuEntrySetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/constants/NumberOfStandardSingleRecordActionsOnAllObjects.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useDeleteSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useManageFavoritesSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDeleteSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useManageFavoritesSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useSingleRecordActions.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/components/WorkflowSingleRecordActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateWorkflowDraftWorkflowSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateWorkflowLastPublishedVersionWorkflowSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useDeactivateWorkflowWorkflowSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useDiscardDraftWorkflowSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useActivateWorkflowDraftWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useActivateWorkflowLastPublishedVersionWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useDeactivateWorkflowWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useDiscardDraftWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useSeeWorkflowActiveVersionWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useSeeWorkflowRunsWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useSeeWorkflowVersionsHistoryWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useTestWorkflowWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useWorkflowSingleRecordActions.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/components/WorkflowVersionsSingleRecordActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useSeeWorkflowExecutionsWorkflowVersionSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useSeeWorkflowVersionsHistoryWorkflowVersionSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useUseAsDraftWorkflowVersionSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useWorkflowVersionsSingleRecordActions.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/workflow-run-record-actions/hooks/useWorkflowRunRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/workflow-run-actions/hooks/useWorkflowRunActions.tsx
  packages/twenty-front/src/modules/workflow/components/OverrideWorkflowDraftConfirmationModal.tsx
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowHeader.tsx
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowVersionHeader.tsx
  packages/twenty-front/src/modules/workflow/hooks/useActiveWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowVersion.tsx
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowWithCurrentVersion.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/icon/providers/internal/AllIcons.ts
Labels: -PR: awaiting review

#8835 Better errors handling
  packages/twenty-server/src/engine/api/graphql/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/sso-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/login-token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/login-token.service.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/transient-token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/transient-token.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment.exception.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/drivers/console.driver.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/drivers/sentry.driver.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/interfaces/exception-handler-driver.interface.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/interfaces/exception-handler-options.interface.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/interfaces/exception-handler-user.interface.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/interfaces/exception-handler-workspace.interface.ts
  packages/twenty-server/src/engine/core-modules/graphql/hooks/use-graphql-error-handler.hook.ts
  packages/twenty-server/src/engine/utils/global-exception-handler.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-event-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-events-import.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-ongoing-stale.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-message-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-messages-import.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-ongoing-stale.cron.job.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.job.ts
Labels: scope: backend, -PR: wip, type: chore, prio: high

#8829 Add field isLabelSyncedWithName
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts
  packages/twenty-front/src/modules/object-metadata/graphql/queries.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneRelationMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneRelationMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFieldMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useUpdateOneFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/formatFieldMetadataItemInput.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatRelationMetadataInput.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1733153195498-addIsLabelSyncedWithNameToFieldMetadata.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/workspace-migration-enum.service.ts
Labels: -PR: awaiting review

#8769 Remove the heart icon button to add the view as a favorite from the top bar
  packages/twenty-front/src/modules/favorites/components/PageFavoriteFolderDropdown.tsx
  packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPicker.tsx
  packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPickerFooter.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemWithOptionDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerFavoriteFoldersDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerOptionDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/types/ViewPickerMode.ts
Labels: -PR: awaiting author

#8815 Add Select form field
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/SelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/SelectFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/display/components/SelectDisplay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/SelectInput.tsx
  packages/twenty-front/src/modules/views/components/EditableFilterChip.tsx
  packages/twenty-front/src/modules/views/components/SortOrFilterChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormRecordCreate.tsx
Labels: -PR: wip

#8854 fix: record group issues
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts
  packages/twenty-front/src/modules/views/types/GraphQLView.ts
  packages/twenty-front/src/modules/views/types/View.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
Labels: -PR: awaiting review

#8869 Update messaging and calendar doc
  packages/twenty-website/src/content/developers/constants/DocsIndex.ts
  packages/twenty-website/src/content/developers/local-setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#8849 Select all fields even those not loaded yet when doing Ctrl+A or Cmd+A on Record Table
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
Labels: -PR: awaiting review

#8870 review(): from PR #8656
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpPasswordField.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWithCredentials.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeFormEffect.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUpForm.ts
  packages/twenty-front/src/modules/auth/states/signInUpModeState.ts
  packages/twenty-front/src/modules/auth/types/signInUpMode.ts
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCard.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCardWrapper.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentityProviderRowRightContainer.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSecurityOptionsList.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSecuritySSORowDropdownMenu.tsx
  packages/twenty-front/src/modules/settings/security/hooks/useCreateSSOIdentityProvider.ts
  packages/twenty-front/src/modules/settings/security/hooks/useDeleteSSOIdentityProvider.ts
  packages/twenty-front/src/modules/settings/security/hooks/useUpdateSSOIdentityProvider.ts
  packages/twenty-front/src/modules/settings/security/states/SSOIdentitiesProvidersState.ts
  packages/twenty-front/src/modules/settings/security/types/AuthProviders.type.ts
  packages/twenty-front/src/modules/ui/utilities/page-favicon/components/PageFavicon.tsx
  packages/twenty-front/src/modules/workspace/components/WorkspaceProviderEffect.tsx
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/switch-workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/switch-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/user/user.validate.ts
  packages/twenty-server/src/engine/core-modules/workspace/types/workspace.type.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.validate.ts
Labels: -PR: awaiting author

#8851 Select full record in variable dropdown
  packages/twenty-front/src/modules/workflow/components/WorkflowSingleRecordFieldChip.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowSingleRecordPicker.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdown.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownFieldItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownObjectItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownStepItem.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownStepSubItem.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownWorkflowStepItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/hooks/useAvailableVariablesInWorkflowStep.ts
  packages/twenty-front/src/modules/workflow/search-variables/types/StepOutputSchema.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/__tests__/filterOutputSchema.test.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/filterOutputSchema.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/isBaseOutputSchema.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/isRecordOutputSchema.ts
  packages/twenty-server/src/engine/utils/generate-fake-value.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/types/output-schema.type.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/utils/generate-fake-object-record-event.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/utils/generate-fake-object-record.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/utils/should-generate-field-fake-value.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-builder.workspace-service.ts
  packages/twenty-ui/src/display/text/components/HorizontalSeparator.tsx
Labels: -PR: awaiting review

#8868 feat: record group fetch more
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useObjectRecordTable.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts
  packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/visibleRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-group/utils/__tests__/recordGroupSortedInsert.test.ts
  packages/twenty-front/src/modules/object-record/record-group/utils/recordGroupSortedInsert.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreNumberOfSelectedRecordsEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/useExportFetchRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useFindManyRecordIndexTableParams.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLazyLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexHasFetchedAllRecordsByGroupComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableNoRecordGroupBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionLoadMore.tsx
Labels: -PR: awaiting review

#8861 review(front): refacto url-manager
  packages/twenty-front/.env.example
  packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useHandleResetPassword.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSSO.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSignInWithGoogle.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSignInWithMicrosoft.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.ts
  packages/twenty-front/src/modules/auth/states/lastAuthenticateWorkspaceState.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/domain-manager/hooks/useBuildWorkspaceUrl.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useGetPublicWorkspaceDataBySubdomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useIsCurrentLocationOnAWorkspaceSubdomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useIsCurrentLocationOnDefaultDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useLastAuthenticatedWorkspaceDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useReadDefaultDomainFromConfiguration.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useReadWorkspaceSubdomainFromCurrentLocation.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToDefaultDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts
  packages/twenty-front/src/modules/domain-manager/states/domainConfigurationState.ts
  packages/twenty-front/src/modules/domain-manager/states/lastAuthenticatedWorkspaceDomainState.ts
  packages/twenty-front/src/modules/settings/security/components/SettingsSecurityOptionsList.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useWorkspaceSwitching.ts
  packages/twenty-front/src/modules/url-manager/hooks/useUrlManager.ts
  packages/twenty-front/src/modules/workspace/components/WorkspaceProviderEffect.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
  packages/twenty-front/src/pages/onboarding/CreateWorkspace.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspace.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
  packages/twenty-front/src/utils/recoil-effects.ts
  packages/twenty-front/vite.config.ts
Labels: -PR: awaiting author

#8856 8839 workflow follow up code step
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowHeader.tsx
  packages/twenty-front/src/modules/workflow/hooks/useUpdateStep.ts
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-server/src/engine/core-modules/serverless/drivers/lambda.driver.ts
  packages/twenty-server/src/engine/core-modules/workflow/dtos/update-workflow-version-step-input.dto.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts
  packages/twenty-server/src/engine/workspace-event-emitter/workspace-event-emitter.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-builder.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/code/code.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/__tests__/workflow-statuses-update.job.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/workflow-statuses-update.job.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.module.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
Labels: -PR: awaiting author

#8895 Fix wrapping text side effects
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldContext.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/SummaryCard.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: -PR: awaiting review

#8875 Settings Form Select refacto
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentSelect.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/__stories__/SettingsOptionCardContentSelect.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/address/components/SettingsDataModelFieldAddressForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/components/SettingsDataModelFieldBooleanForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/currency/components/SettingsDataModelFieldCurrencyForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesForm.tsx
Labels: -PR: awaiting author

#8885 Refetch aggregate queries on record creation/update/deletion of record
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFieldsAggregate.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useAggregateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useAggregateRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useAggregateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useRefetchAggregateQueries.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useUpdateOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useAggregateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useAggregateRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDestroyManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useRefetchAggregateQueries.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAggregateRecordsForRecordBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/buildRecordGqlFieldsAggregate.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/buildRecordGqlFieldsAggregate.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/generateAggregateQuery.test.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/getAggregateQueryName.test.ts
  packages/twenty-front/src/modules/object-record/utils/generateAggregateQuery.ts
  packages/twenty-front/src/modules/object-record/utils/getAggregateQueryName.ts
Labels: -PR: awaiting author

#8901 8733 refactor gmailhandleerrorservice
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/mocks/gaxios-error-mocks.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/mocks/gmail-api-error-mocks.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-history.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/__tests__/parse-gaxios-error.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/__tests__/parse-gmail-message-list-fetch-error.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/__tests__/parse-gmail-messages-import-error.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/parse-gaxios-error.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/parse-gmail-message-list-fetch-error.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/parse-gmail-messages-import-error.util.ts
Labels: -PR: awaiting review

#8824 CSV importing and exporting fixes
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useExportProcessRecordsForCSV.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/types/index.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/generateExampleRow.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/getFieldOptions.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/normalizeTableData.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/setColumn.ts
Labels: -PR: awaiting author

#8911 Dropdown in dropdown
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
Labels: -PR: awaiting review

#8871 Remove duplicate plus sign for phone numbers
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getPhonesFieldPreviewValue.ts
  packages/twenty-front/src/modules/ui/field/display/components/PhonesDisplay.tsx
Labels: -PR: wip, -PR: awaiting review

#8916 8725 workflow avoid serverless function autosave errors
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
  packages/twenty-server/src/engine/core-modules/message-queue/drivers/bullmq.driver.ts
  packages/twenty-server/src/engine/core-modules/message-queue/drivers/pg-boss.driver.ts
  packages/twenty-server/src/engine/core-modules/serverless/drivers/lambda.driver.ts
  packages/twenty-server/src/engine/core-modules/serverless/drivers/utils/get-last-layer-dependencies.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/jobs/build-serverless-function.job.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/jobs/delete-serverless-function.job.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.module.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
Labels: -PR: awaiting review

#8910 Fix advanced settings icon tool and right bar alignment
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
Labels: -PR: awaiting review

#8932 Fix SingleRecordSelectMenuItemsWithSearch
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleRecordSelectMenuItemsWithSearch.tsx
Labels: -PR: awaiting review

#8934 Settings Icon CSS update
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentBase.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentToggle.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionIconCustomizer.tsx
Labels: scope: front, -PR: awaiting review, size: short, type: design improvement, prio: med, prio: high

#8894 Fix bug reoder on table in view groups mode
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useComputeNewRowPosition.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDragDropContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyRecordGroupDragDropContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTablePendingRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useRecoilCallbackState.ts
Labels: -PR: awaiting review

#8931 More fixes
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSectionHeader.tsx
Labels: -PR: wip, -PR: awaiting author

#8963 fix
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/NumberFieldDisplay.tsx
Labels: -PR: awaiting review

#8867 Add migration ci check
  .github/workflows/ci-server.yaml
  packages/twenty-server/src/database/typeorm/core/core.datasource.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1733753649142-removeBillingFKWithCore.ts
  packages/twenty-server/src/database/typeorm/core/migrations/common/1733318043626-sso-missing-migration.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1733318004066-missing-shortcut-migration.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-customer.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-entitlement.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/key-value-pair/key-value-pair.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
Labels: -PR: awaiting review

#8982 better label for toggle input that will improve UX
  packages/twenty-ui/src/navigation/link/components/AdvancedSettingsToggle.tsx
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemToggle.tsx
Labels: scope: front, -PR: awaiting review, prio: med

#8940 update: Replace reactflow with @xyflow/react and Update Dependencies
  package.json
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverview.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewField.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectOverview.tsx
  packages/twenty-ui/src/input/button/components/IconButtonGroup.tsx
  yarn.lock
Labels: -PR: awaiting review

#9009 Title overflow
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-ui/src/display/chip/components/AvatarChip.tsx
  packages/twenty-ui/src/display/chip/components/Chip.tsx
Labels: -PR: awaiting review

#9017 Thomas request
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelPreviewFormCard.tsx
Labels: -PR: awaiting review, prio: high

#9012 Fix login issue
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/auth/components/Logo.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsLoadEffect.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useLoadMockedObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useRefreshObjectMetadataItem.ts
  packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts
  packages/twenty-front/vite.config.ts
  packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting author

#8818 Add a confirmation modal for relation object deletion
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
Labels: -PR: awaiting review

#9004 add info to customer table and stripe customer data
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/jobs/update-subscription-quantity.job.ts
  packages/twenty-server/src/engine/core-modules/billing/listeners/billing-workspace-member.listener.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-entitlement.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.service.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-entitlement-updated-event-to-entitlement-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-customer-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-subscription-item-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-subscription-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
Labels: -PR: awaiting review

#9038 fix: group by sort options should have a checkmark when selected
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupSortContent.tsx
Labels: -PR: awaiting author

#9039 fix: can't properly drag and drop in empty record group
  packages/twenty-front/src/hooks/useCombinedRefs.ts
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/RecordTableCell.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableCellContext.ts
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowContext.ts
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowDraggableContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyLoading.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContextWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellGrip.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableLastEmptyCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__mocks__/cell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useCurrentCellPosition.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useIsSoftFocusOnCurrentTableCell.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useMoveSoftFocusToCurrentCellOnHover.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/internal/__tests__/useCloseRecordTableCellInGroup.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/internal/__tests__/useCloseRecordTableCellNoGroup.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellFromCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCells.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCellsEmpty.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCellsVisible.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/hooks/useSetCurrentRowSelected.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionAddNew.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionLoadMore.tsx
  packages/twenty-front/src/utils/combineRefs.ts
Labels: -PR: awaiting review

#8975 In navigation drawer, cursor should not be drag on hover and some enhancements
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavoritesFolders.tsx
  packages/twenty-front/src/modules/ui/layout/draggable-list/components/DraggableList.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSubItem.tsx
Labels: -PR: awaiting review

#9055 add product table data in real time
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/types/billing-product-metadata.type.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-product-event-to-product-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-subscription-repository-data.util.ts
Labels: -PR: awaiting review

#9068 Fix Tasks/Notes created with null position
  packages/twenty-front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  packages/twenty-server/src/command/command.module.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-record-position-backfill.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.module.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/record-position-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/commands/0-20-record-position-backfill.command.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/record-position.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/record-position-backfill.job.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/workspace-query-runner-job.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/services/__tests__/record-position-backfill-service.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/services/record-position-backfill-module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/services/record-position-backfill-service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/workspace-query-runner-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/create-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/create-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/delete-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/delete-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/destroy-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/destroy-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-duplicates-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/find-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/restore-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/restore-one-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/search-resolver-factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/update-many-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/update-one-resolver.factory.ts
  packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-many.pre-query-hook.ts
  packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-one.pre-query-hook.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/has-position-field.util.ts
  packages/twenty-server/src/engine/twenty-orm/custom.workspace-entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/commands/workspace-migration-runner-commands.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/favorite-folder/standard-objects/favorite-folder.workspace-entity.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-field.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-group.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
Labels: -PR: awaiting review

#9079 fix(): sleep before redirect
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useGetPublicWorkspaceDataBySubdomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirect.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToDefaultDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts
  packages/twenty-front/src/modules/settings/accounts/hooks/useTriggerApiOAuth.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonate.ts
  packages/twenty-front/src/pages/auth/Authorize.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
  packages/twenty-server/src/engine/core-modules/sso/services/sso.service.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#9087 fix demo seed conflicting with dev seed
  packages/twenty-server/src/database/typeorm-seeds/core/demo/users.ts
Labels: -PR: awaiting review

#9077 Change default behavior of ENABLE DB MIGRATION
  packages/twenty-docker/.env.example
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/manifests/deployment-worker.yaml
  packages/twenty-docker/k8s/terraform/deployment-server.tf
  packages/twenty-docker/k8s/terraform/deployment-worker.tf
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review

#9080 fix(twenty-front): allow to connect available provider only
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
Labels: -PR: awaiting review

#9084 feat(database): add unique constraint on workspace subdomain
  packages/twenty-server/src/database/typeorm/core/migrations/common/1734355945585-add-unique-index-on-subdomain.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
Labels: -PR: awaiting author

#9096 fix advanced mode settings navigation animations
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
Labels: -PR: awaiting review

#9066 9024 workflow test serverless function follow up
  packages/twenty-front/src/modules/serverless-functions/utils/__tests__/getFunctionOutputSchema.test.ts
  packages/twenty-front/src/modules/serverless-functions/utils/getFunctionOutputSchema.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/workflow/hooks/__tests__/useTriggerNodeSelection.test.tsx
  packages/twenty-front/src/modules/workflow/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/hooks/useTriggerNodeSelection.ts
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdown.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownFieldItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownObjectItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownWorkflowStepItems.tsx
  packages/twenty-front/src/modules/workflow/search-variables/hooks/useAvailableVariablesInWorkflowStep.ts
  packages/twenty-front/src/modules/workflow/search-variables/types/StepOutputSchema.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/filterOutputSchema.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/isLinkOutputSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/constants/WorkflowServerlessFunctionTabListComponentId.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPage.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-server/src/engine/metadata-modules/serverless-function/jobs/build-serverless-function.job.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/types/output-schema.type.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#9021 Add date form field
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/AbsoluteDatePickerHeader.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/DateTimeInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/constants/DateParserFormat.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/constants/DateTimeParserFormat.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/utils/parseDateToString.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/utils/parseStringToDate.ts
Labels: -PR: wip

#9090 feat: hide empty record group default true
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupVisibility.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/visibleRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoader.tsx
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexRecordGroupHideComponentState.ts
Labels: -PR: awaiting author

#9086 fix: add create cursor util
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/utils/__tests__/encodeCursor.test.ts
  packages/twenty-front/src/modules/apollo/utils/encodeCursor.ts
Labels: -PR: awaiting author

#9070 Fixed Custom Icon Persistance Across New View Creations
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentCreateMode.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentEffect.tsx
Labels: -PR: awaiting review

#9098 Fix re render view groups
  packages/twenty-front/src/modules/object-record/record-group/hooks/useSetRecordGroup.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyRecordGroupDragDropContextProvider.tsx
  packages/twenty-front/src/modules/views/utils/mapViewGroupsToRecordGroupDefinitions.ts
Labels: blocked: conflict/dependency

#8442 Basic test verifying if demo account is working properly
  .github/workflows/ci-demo-check.yml
  packages/twenty-e2e-testing/playwright.config.ts
  packages/twenty-e2e-testing/tests/all/companies.spec.ts
  packages/twenty-e2e-testing/tests/all/workspaces.spec.ts
  packages/twenty-e2e-testing/tests/demo/demo_basic.spec.ts
Labels: -PR: awaiting review

#8488 fix - add new button on opportunity board company picker doesnt work
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewOpportunity.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleRecordSelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleRecordSelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchRecordQuery.ts
Labels: -PR: awaiting author

#9100 add price and meter dynamically add foreign keys in billing
  packages/twenty-server/src/database/typeorm/core/migrations/billing/1734450749954-addConstraintsOnBillingTables.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-customer.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-entitlement.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-price.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.service.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-meter-data-to-meter-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-price-event-to-price-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-product-event-to-product-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-subscription-item-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-subscription-event-to-subscription-repository-data.util.ts
Labels: -PR: awaiting review

#8946 fix: recordBoard sticky header + scrollThumb
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: -PR: awaiting CI

#9111 minor fix -- missing margin bottom for orphan favorites
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberOrphanFavorites.tsx
Labels: -PR: awaiting review

#9078 Add Raw JSON Form Field Input
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormRawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRawJsonFieldInput.stories.tsx
  packages/twenty-front/src/modules/workflow/search-variables/utils/initializeEditorContent.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/variableTag.ts
Labels: -PR: awaiting review

#9110 feat: NoValue is bot properly created the backend
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts
  packages/twenty-front/src/modules/views/utils/mapViewGroupsToRecordGroupDefinitions.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-view-group-no-value-backfill.command.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts
Labels: -PR: awaiting review

#9108 Add fields to update in update record action
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormMultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/display/components/MultiSelectDisplay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/MultiSelectInput.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormUpdateRecord.tsx
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/types/workflow-record-crud-action-input.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/update-record.workflow-action.ts
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemMultiSelectTag.tsx
Labels: -PR: awaiting review

#9082 feat(workspace): expand forbidden subdomain validation
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
  packages/twenty-server/src/engine/core-modules/workspace/dtos/update-workspace-input.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/utils/__tests__/forbidden-words-custom-class-validator.spec.ts
  packages/twenty-server/src/engine/utils/custom-class-validator/ForbiddenWords.ts
  packages/twenty-server/src/filters/graphql-validation-exception.filter.ts
  packages/twenty-server/src/filters/unhandled-exception.filter.ts
  packages/twenty-server/src/main.ts
Labels: -PR: wip

#9115 Remove buggy dependencies
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFetchAllRecordIds.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyFetchAllRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFetchAllRecordIds.ts
  packages/twenty-front/src/modules/object-record/hooks/useLazyFetchAllRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/__tests__/useExportFetchRecords.test.ts
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/useExportFetchRecords.ts
Labels: -PR: awaiting CI

#9076 Fixes person navigation after image upload
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts
Labels: -PR: awaiting author

#9117 fix icon shrink and use avatar for logo and icons
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
Labels: -PR: awaiting review

#9130 Remove react hook form in send email action
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormCreateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormDeleteRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/workflow-actions/components/WorkflowEditActionFormUpdateRecord.tsx
Labels: -PR: awaiting author

#8663 Reactive form preview
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberSettingsFormCard.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
Labels: -PR: wip

#9133 Add date time form field
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateTimeFieldInputBase.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateTimeFieldInputBase.stories.tsx
Labels: -PR: awaiting review

#8785 add: objectName in fav folder
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberOrphanFavorites.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSubItem.tsx
Labels: -PR: awaiting review

#9124 Improve aggregate footer cell display
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAggregateRecordsForRecordBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexRecordGroupHideComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDroppable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooterCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterWithDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupStickyEffect.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/contexts/ScrollWrapperContexts.tsx
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/object-records-to-graphql-connection.helper.ts
Labels: -PR: awaiting review

#9035 Phone country code unique
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/__tests__/useRightDrawerEmailThread.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapFieldMetadataToGraphQLQuery.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapObjectMetadataToGraphQLQuery.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/personFragments.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/usePersistField.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/__tests__/phonesUtils.test.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/phonesUtils.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldPhonesValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/computeDraftValueFromFieldValue.ts
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/__tests__/useExportFetchRecords.test.ts
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/mock.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getPhonesFieldPreviewValue.ts
  packages/twenty-front/src/modules/ui/field/display/components/PhonesDisplay.tsx
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-server/src/database/commands/active-workspaces.command.ts
  packages/twenty-server/src/database/commands/base.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/logger.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-phone-calling-code-create-column.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-phone-calling-code-migrate-data.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm-seeds/metadata/fieldsMetadata.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/people.ts
  packages/twenty-server/src/engine/api/__mocks__/object-metadata-item.mock.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/phones.composite-type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/generate-default-value.ts
  packages/twenty-zapier/src/test/creates/crud_record.test.ts
  packages/twenty-zapier/src/test/utils/handleQueryParams.test.ts
Labels: -PR: wip, -PR: awaiting author

#9149 9018 fix batch delete
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDeleteSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDestroySingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuButtons.tsx
  packages/twenty-front/src/modules/action-menu/contexts/ActionMenuContext.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffectByBatch.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/object-record/record-index/states/isRecordIndexLoadMoreLockedComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionLoadMore.tsx
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/core-modules/message-queue/message-queue.constants.ts
  packages/twenty-server/src/modules/favorite/constants/favorite-deletion-batch-size.ts
  packages/twenty-server/src/modules/favorite/favorite.module.ts
  packages/twenty-server/src/modules/favorite/jobs/favorite-deletion.job.ts
  packages/twenty-server/src/modules/favorite/listeners/favorite-deletion.listener.ts
  packages/twenty-server/src/modules/favorite/services/favorite-deletion.service.ts
  packages/twenty-server/src/modules/modules.module.ts
Labels: -PR: awaiting author

#9168 minor fix -- datamodel multiselect edit form dropdowns
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx
Labels: -PR: awaiting review

#9170 Don't register delete multiple records action when deleted filter is active
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
Labels: -PR: awaiting review

#9174 Workspace logo is not visible
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
Labels: scope: front, -PR: awaiting review, prio: high

#9202 Fix position calculations -- favorites
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/useHandleFavoriteDragAndDrop.ts
  packages/twenty-front/src/modules/favorites/utils/calculateNewPosition.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
Labels: -PR: awaiting review

#9203 Make the workflow's visualizer layout more stable
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvasEditable.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvasReadonly.tsx
Labels: -PR: awaiting review

#9218 Ensure step is selected after creation when a new version has to be created
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/states/workflowLastCreatedStepIdState.ts
Labels: -PR: awaiting review

#8695 Refactored and improved seeds
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RichTextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRichTextField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRichTextFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RichTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRichTextValue.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCellsVisible.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionIconCustomizer.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditor.tsx
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditorDropdownFocusEffect.tsx
  packages/twenty-front/src/modules/ui/input/editor/contexts/BlockEditorCompoponeInstanceContext.ts
  packages/twenty-front/src/modules/ui/input/editor/states/isSlashMenuOpenComponentState.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useSetFocusedDropdownIdAndMemorizePrevious.ts
  packages/twenty-front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-front/src/utils/parseJson.ts
  packages/twenty-server/.eslintrc.cjs
  packages/twenty-server/src/command/command.module.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/options.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-field-metadata-default-value.validator.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-field-metadata-options.validator.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/hooks/before-delete-one-relation.hook.ts
  packages/twenty-server/src/engine/seeder/data-seeds/pets-data-seeds.ts
  packages/twenty-server/src/engine/seeder/data-seeds/survey-results-data-seeds.ts
  packages/twenty-server/src/engine/seeder/interfaces/object-metadata-seed.ts
  packages/twenty-server/src/engine/seeder/metadata-seeds/pets-metadata-seeds.ts
  packages/twenty-server/src/engine/seeder/metadata-seeds/survey-results-metadata-seeds.ts
  packages/twenty-server/src/engine/seeder/seeder.module.ts
  packages/twenty-server/src/engine/seeder/seeder.service.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/companies-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/people-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/seed-company-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/seed-opportunity-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/seed-person-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/seed-workspace-member-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/seed-workspace-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/seed-view-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/standard-objects-prefill-data.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
  packages/twenty-ui/src/display/tag/components/Tag.tsx
  packages/twenty-ui/src/theme/constants/IllustrationIconDark.ts
  packages/twenty-ui/src/theme/constants/IllustrationIconLight.ts
Labels: -PR: wip, -PR: awaiting author

#9220 Restore "Fix "Create profile" page not supporting dark mode (#8110)" & Fix string defaultValues during sync-metadata
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#9237 Floating inputs border radius fix
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
  packages/twenty-front/src/modules/ui/layout/overlay/components/OverlayContainer.tsx
Labels: -PR: awaiting review

#9221 Scroll vertical-horizontal visibility seperation
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: -PR: awaiting review

#9233 Aggregate fast follows (1)
  packages/twenty-front/src/modules/dropdown/hooks/useDropdown.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownContext.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMoreOptionsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-board/types/AggregateContentId.ts
  packages/twenty-front/src/modules/object-record/record-board/types/RecordBoardColumnHeaderAggregateContentId.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterAggregateOperationMenuItems.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownMoreOptionsContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterWithDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/constants/standardAggregateOperationOptions.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useViewFieldAggregateOperation.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/states/viewFieldAggregateOperationState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/types/RecordTableFooterAggregateContentId.tsx
  packages/twenty-front/src/modules/views/hooks/useUpdateViewAggregate.ts
  packages/twenty-ui/src/navigation/menu-item/components/MenuItem.tsx
Labels: -PR: awaiting review

#9242 Allow multiple folder to be open at once
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/favorites/hooks/useHandleFavoriteDragAndDrop.ts
  packages/twenty-front/src/modules/favorites/states/activeFavoriteFolderIdState.ts
  packages/twenty-front/src/modules/favorites/states/openFavoriteFolderIdsState.ts
Labels: blocked: design needed

#8510 fix: last field overflow
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
Labels: -PR: awaiting review

#9248 Added all field types on pet custom object
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-event-participants.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/message-participants.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunities.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/seedPeople.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/service/domain-manager.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/interfaces/object-metadata-standard-id-to-id-map.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/seeder/data-seeds/pets-data-seeds.ts
  packages/twenty-server/src/engine/seeder/data-seeds/survey-results-data-seeds.ts
  packages/twenty-server/src/engine/seeder/metadata-seeds/pets-metadata-seeds.ts
  packages/twenty-server/src/engine/seeder/seeder.service.ts
  packages/twenty-server/src/engine/utils/compute-table-name.util.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/seed-view-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/companies-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/notes-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/opportunities-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/opportunity-by-stage.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/people-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/tasks-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/tasks-by-status.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/workflow-runs-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/workflow-versions-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/workflows-all.view.ts
Labels: -PR: awaiting review

#9255 fix(spreadsheet-import): add background and border styles to DropdownMenu in`MatchColumnSelect`
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
Labels: -PR: awaiting review

#9261 Remove delete action from workflow versions and runs
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/utils/getActionConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-run-actions/constants/WorkflowRunsSingleRecordActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/constants/WorkflowVersionsSingleRecordActionsConfig.ts
Labels: -PR: awaiting review

#9037 Fix: Make DropdownMenuSeparator background transparent based on theme
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSeparator.tsx
Labels: -PR: awaiting review

#9219 Webhook Secret Field Implementation and Security Enhancements (#9187)
  packages/twenty-front/src/modules/settings/developers/types/webhook/Webhook.ts
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/components/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-server/src/engine/core-modules/open-api/utils/computeWebhooks.utils.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/webhook/jobs/call-webhook-jobs.job.ts
  packages/twenty-server/src/modules/webhook/jobs/call-webhook.job.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
  packages/twenty-server/src/utils/remove-secret-from-webhook-record.ts
Labels: -PR: awaiting author

#9069 Clicking a phone number should copy its value
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/PhonesFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/PhonesFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBar.tsx
  packages/twenty-front/src/modules/ui/field/display/components/PhonesDisplay.tsx
Labels: -PR: awaiting author

#9257 Command menu refactoring
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/components/SingleRecordActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/constants/DefaultSingleRecordActionsConfigV1.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/constants/DefaultSingleRecordActionsConfigV2.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/constants/WorkflowSingleRecordActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-run-actions/constants/WorkflowRunsSingleRecordActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/constants/WorkflowVersionsSingleRecordActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/types/ActionViewType.ts
  packages/twenty-front/src/modules/action-menu/hooks/useActionMenuEntriesWithCallbacks.ts
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuDefaultSelectionEffect.tsx
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuCommands.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHotKeys.ts
  packages/twenty-front/src/modules/command-menu/hooks/useMatchCommands.ts
  packages/twenty-front/src/modules/command-menu/hooks/useMatchingCommandMenuCommands.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuCommandsSelector.ts
  packages/twenty-front/src/modules/command-menu/utils/computeCommandMenuCommands.ts
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
Labels: -PR: awaiting review

#9192 Fix shrinked horizontal separator
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeForm.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOSAMLForm.tsx
  packages/twenty-ui/src/display/text/components/HorizontalSeparator.tsx
Labels: -PR: awaiting review

#9292 forget defaultworkspace update
  packages/twenty-front/src/modules/object-metadata/hooks/useUpdateOneFieldMetadataItem.ts
Labels: -PR: awaiting review, prio: CRITICAL 🚨

#9177 add command to sync plan data from stripe, doing testing
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-plans-data.command.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-plan-key.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.service.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-price-data-to-price-repository-data.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/transform-stripe-product-data-to-product-repository-data.util.ts
Labels: -PR: awaiting review
