Repository twentyhq/twenty, pull requests merged in 2024-11, with the labels that each got.

#8259 Fix disabled + focus button
  packages/twenty-ui/src/input/button/components/Button.tsx
Labels: -PR: awaiting review

#8258 Fix hotkey scope when opening command menu
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuEffect.tsx
Labels: -PR: awaiting review

#7674 fix: settings error layout
  packages/twenty-front/src/modules/error-handler/components/AppErrorBoundary.tsx
  packages/twenty-front/src/modules/error-handler/components/GenericErrorFallback.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/PageHeader.tsx
Labels: -PR: awaiting author

#8263 Fix actions setter when opening the command menu
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
  packages/twenty-front/src/modules/app/effect-components/CommandMenuEffect.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
Labels: -PR: awaiting review

#8315 8191 command k workflow trigger for selected record
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ExportRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/workflow-run-record-actions/components/WorkflowRunRecordActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBarEntry.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordShowActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/hooks/__tests__/useExportRecordData.test.ts
  packages/twenty-front/src/modules/action-menu/hooks/useExportRecordData.ts
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/types/Command.ts
  packages/twenty-front/src/modules/databases/hooks/useCreateOneDatabaseConnection.ts
  packages/twenty-front/src/modules/databases/hooks/useDeleteOneDatabaseConnection.ts
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTable.ts
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTableSchemaChanges.ts
  packages/twenty-front/src/modules/databases/hooks/useUnsyncRemoteTable.ts
  packages/twenty-front/src/modules/databases/hooks/useUpdateOneDatabaseConnection.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useApolloMetadataClient.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneRelationMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useDeleteOneFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useDeleteOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useDeleteOneRelationMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useCreateOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useDeleteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useExecuteOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/usePublishOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
  packages/twenty-front/src/modules/workflow/graphql/mutations/runWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useActivateWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useAllActiveWorkflowVersionsForObject.ts
  packages/twenty-front/src/modules/workflow/hooks/useComputeStepOutputSchema.ts
  packages/twenty-front/src/modules/workflow/hooks/useDeactivateWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowVersion.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/icon/providers/internal/AllIcons.ts
Labels: -PR: awaiting review

#8339 Refactor kanban new card creation
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewOpportunity.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewOpportunityButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewRecord.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewRecordButton.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useColumnNewCardActions.ts
Labels: -PR: awaiting review

#7621 fix: content getting hide on drag and drop in stage view cards
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCellsEmpty.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableCellsVisible.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/tableCellWidthsComponentState.ts
Labels: -PR: awaiting review

#8348 8304 - Fix Action Menu Buttons Alignment
  packages/twenty-front/src/modules/action-menu/components/ActionMenuConfirmationModals.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
Labels: -PR: awaiting review

#7729 fix: RightDrawer doesn't save context values when clickedOutside
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerTitleRecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/SummaryCard.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
Labels: -PR: awaiting author

#8343 Add blue focus on text inputs
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/__tests__/useDropdown.test.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/states/dropdownWidthComponentState.ts
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentCreateMode.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentEditMode.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
Labels: -PR: wip, -PR: awaiting author

#8338 Fix of broken API Auth
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/auth/services/api-key.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/api-key.service.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/jwt.auth.strategy.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/jwt.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.ts
  packages/twenty-server/src/engine/core-modules/auth/types/auth-context.type.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/jwt/services/jwt-wrapper.service.ts
  packages/twenty-server/src/engine/strategies/aggregate-by-workspace-context-id.strategy.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
Labels: -PR: awaiting review

#8368 Fix action menu dropdown
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/hooks/__tests__/useActionMenu.test.ts
  packages/twenty-front/src/modules/action-menu/hooks/useActionMenu.ts
  packages/twenty-front/src/modules/action-menu/utils/__tests__/getActionBarIdFromActionMenuId.test.ts
  packages/twenty-front/src/modules/action-menu/utils/__tests__/getActionMenuDropdownIdFromActionMenuId.test.ts
  packages/twenty-front/src/modules/action-menu/utils/__tests__/getActionMenuIdFromRecordIndexId.test.ts
  packages/twenty-front/src/modules/action-menu/utils/getActionBarIdFromActionMenuId.ts
  packages/twenty-front/src/modules/action-menu/utils/getActionMenuDropdownIdFromActionMenuId.ts
  packages/twenty-front/src/modules/action-menu/utils/getActionMenuIdFromRecordIndexId.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardSelection.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useLeaveTableFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyUnselectEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useTriggerActionMenuDropdown.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: -PR: awaiting review

#8370 fix: don't use previous view group state when creating a new view
  packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts
Labels: -PR: awaiting review

#8384 Fix npx nx run start (twenty:server:worker was not triggered)
  package.json
Labels: -PR: awaiting review

#8376 Integration test : Sync mode + db reset option + cleaning
  .github/workflows/ci-server.yaml
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/project.json
  packages/twenty-server/src/engine/core-modules/auth/strategies/jwt.auth.strategy.spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-api-keys-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-attachments-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-audit-logs-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-calendar-channel-event-associations-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-calendar-event-participants-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-connected-accounts-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-favorites-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-message-channel-message-associations-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-message-participants-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-message-threads-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-note-targets-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-notes-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-opportunities-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-task-targets-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-tasks-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-timeline-activities.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-view-fields.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-view-filters.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-view-sorts.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-views.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/all-webhooks.integration-spec.ts
  packages/twenty-website/src/content/developers/backend-development/server-commands.mdx
Labels: scope: backend, -PR: awaiting review

#8385 Fix CalendarOngoingStaleJob being in wrong queue
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/jobs/calendar-ongoing-stale.job.ts
Labels: -PR: awaiting review

#8388 Update CanAccessMessageThreadService
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/can-access-message-thread.service.ts
Labels: -PR: awaiting review

#8383 Fix noninteractive toggle
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelDetails.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelDetails.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptionCardContent.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSecurityOptionsList.tsx
  packages/twenty-ui/src/input/components/Toggle.tsx
Labels: -PR: awaiting review

#8389 Make filters work on export csv action
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/context-store/states/contextStoreFiltersComponentState.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreTargetedRecordsRuleComponentState.ts
  packages/twenty-front/src/modules/context-store/utils/__tests__/computeContextStoreFilters.test.ts
  packages/twenty-front/src/modules/context-store/utils/computeContextStoreFilters.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreNumberOfSelectedRecordsEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useRecordData.test.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordData.ts
Labels: -PR: awaiting review

#8375 8172 update the right drawer action menu to open with command o
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenuBarEntry.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerActionMenuBar.tsx
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordShowActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/types/RightDrawerActionMenuDropdownHotkeyScope.ts
  packages/twenty-front/src/modules/action-menu/utils/__tests__/getRightDrawerActionMenuDropdownIdFromActionMenuId.test.ts
  packages/twenty-front/src/modules/action-menu/utils/getRightDrawerActionMenuDropdownIdFromActionMenuId.ts
  packages/twenty-front/src/modules/activities/components/RichTextEditor.tsx
  packages/twenty-ui/src/input/button/components/Button.tsx
  packages/twenty-ui/src/input/button/components/__stories__/Button.stories.tsx
Labels: -PR: awaiting author

#7841 Hide tabs
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/constants/BaseRecordLayout.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts
  packages/twenty-front/src/modules/object-record/record-show/types/RecordLayout.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/tab/types/LayoutCard.ts
  packages/twenty-front/src/modules/ui/layout/tab/types/RecordLayoutTab.ts
  packages/twenty-front/src/modules/ui/layout/tab/types/TabVisibilityConfig.ts
Labels: -PR: awaiting author

#8334 Data settings new layout - anchor navigation
  .github/workflows/ci-tinybird.yaml
  .github/workflows/ci-website.yaml
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelsContainer.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsContainer.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabListFromUrlOptionalEffect.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/__stories__/Tablist.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPage.tsx
  packages/twenty-front/src/pages/settings/data-model/constants/SettingsObjectDetailTabs.ts
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
Labels: -PR: awaiting review

#8486 Fix BullMQ deprecation warning
  packages/twenty-server/src/engine/core-modules/redis-client/redis-client.service.ts
Labels: -PR: awaiting review

#8479 [Workflow] Add search in variable dropdown
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuHeader.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/StyledDropdownButtonContainer.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdown.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdownStepSubItem.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: wip, -PR: awaiting author

#8481 Feature : Adding percentage option to Input Number
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/NumberFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useNumberField.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/computeDraftValueFromFieldValue.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/numberFieldDefaultValueSchema.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useRecordData.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberForm.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/ui/field/display/components/NumberDisplay.tsx
  packages/twenty-front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting author

#8507 Set cache metadata version to infinite TTL
  packages/twenty-server/src/engine/workspace-cache-storage/workspace-cache-storage.service.ts
Labels: -PR: awaiting review

#8309 Begin moving to postgres spilo + adding pgvector
  .github/workflows/ci-server.yaml
  .github/workflows/ci-test-docker-compose.yaml
  .github/workflows/ci-website.yaml
  .vscode/twenty.code-workspace
  Makefile
  install.sh
  packages/twenty-docker/.env.example
  packages/twenty-docker/Makefile
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-db.yaml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/manifests/deployment-worker.yaml
  packages/twenty-docker/k8s/terraform/README.md
  packages/twenty-docker/k8s/terraform/variables.tf
  packages/twenty-docker/twenty-postgres-spilo/Dockerfile
  packages/twenty-docker/twenty-postgres/Dockerfile
  packages/twenty-docker/twenty-postgres/init.sql
  packages/twenty-docker/twenty/Dockerfile
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-e2e-testing/drivers/env_variables.ts
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/scripts/render-worker.sh
  packages/twenty-server/scripts/setup-db.ts
  packages/twenty-server/scripts/truncate-db.ts
  packages/twenty-website/src/content/developers/self-hosting/cloud-providers.mdx
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
  render.yaml
Labels: -PR: awaiting author

#8500 Add crud actions
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query.parser.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-builder.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/exceptions/record-crud-action.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/record-crud-action.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/record-crud.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/types/workflow-record-crud-action-input.type.ts
Labels: -PR: awaiting review

#8266 Improve phone input UI
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/phone/components/PhoneCountryPickerDropdownButton.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
  packages/twenty-ui/src/input/button/components/LightIconButton.tsx
Labels: -PR: awaiting CI

#8282 fix: Added keyboard functionality for esc and Ctrl + a
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/useRecordBoardStates.ts
  packages/twenty-front/src/modules/object-record/record-board/states/selectors/recordBoardAllRecordIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/ui/utilities/drag-select/components/DragSelect.tsx
Labels: -PR: awaiting review

#8452 Fix multi select filtering (#5358)
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useColumnDefinitionsFromFieldMetadata.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandsForFilterType.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/isMatchingStringFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/getEmptyRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingArrayFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingMultiSelectFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingRatingFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingSelectFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/views/components/ViewBarFilterEffect.tsx
  packages/twenty-front/src/modules/views/view-filter-value/utils/resolveFilterValue.ts
  packages/twenty-front/src/modules/views/view-filter-value/utils/resolveSelectViewFilterValue.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-filter/graphql-query-filter-field.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/compute-where-condition-parts.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/input-type.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/input/array-filter.input-type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/input/multi-select-filter.input-type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/input/select-filter.input-type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/generate-fields.utils.ts
Labels: -PR: awaiting author

#8287 fix: Dropdown Overlapping Sidebar on Column Header Click in Horizontal Table When Scrolling
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadWithDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/isScrollEnabledForRecordTableState.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: -PR: awaiting author

#8555 feat(env-vars): Add warning validation decorator
  packages/twenty-server/src/engine/core-modules/environment/decorators/__tests__/assert-or-warn.decorator.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/decorators/assert-or-warn.decorator.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
Labels: -PR: awaiting author

#8557 Wrap Long text fields (textarea)
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/TextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useTextFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DoubleTextDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/TextDisplay.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: -PR: awaiting author

#8551 Stories and SSL Configuration docs update
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentCounter.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/__stories__/SettingsOptionCardContentCounter.stories.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/__stories__/SettingsOptionCardContentSelect.stories.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/__stories__/SettingsOptionCardContentToggle.stories.tsx
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
Labels: -PR: awaiting author

#8565 Update ShowPageMoreButton to open the command menu when clicked
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageMoreButton.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageBaseHeader.tsx
Labels: -PR: awaiting review

#8567 Fix active navigation tab + quick workflows fixes
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerOpenedSection.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx
Labels: -PR: awaiting review

#8277 Background Blur added across multiple Input Fields in Edit Popups
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/AddressInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/DateTimeInput.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx
Labels: -PR: awaiting author

#8574 Feature 7552 patch
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextForm.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#8564 Add custom objects to command menu search + use ilike for notes search
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/types/Command.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNamePlural.ts
  packages/twenty-front/src/modules/object-record/relation-picker/components/ActivityTargetInlineCellEditModeMultiRecordsSearchFilterEffect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useMultiObjectSearchQueryResultFormattedAsObjectRecordsMap.test.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearch.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchQueryResultFormattedAsObjectRecordsMap.ts
  packages/twenty-front/src/testing/graphqlMocks.ts
Labels: -PR: awaiting review

#8536 fix: uncontrolled input to controlled in SigninUpForm
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUpForm.ts
Labels: -PR: awaiting review

#8594 Fix select filter eq
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingSelectFilter.ts
Labels: -PR: awaiting CI

#8590 Fail entrypoint if migration fails
  packages/twenty-docker/twenty/entrypoint.sh
Labels: -PR: awaiting CI

#8592 Fix composite subfields format
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-website/src/content/developers/backend-development/queue.mdx
Labels: -PR: awaiting author

#8575 Remove "When no records are selected" actions on record page ⌘O
  packages/twenty-front/src/modules/action-menu/actions/global-actions/workflow-run-actions/components/WorkflowRunActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ExportRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/workflow-run-record-actions/components/WorkflowRunRecordActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBarEntry.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordShowActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
Labels: -PR: awaiting author

#8615 Hide the "Expand to Full Page" button on Email and Calendar pages
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerTopBar.tsx
Labels: -PR: awaiting review

#8635 Improve object metadata maps size
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/object-records-to-graphql-connection.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-duplicates-resolver.service.ts
  packages/twenty-server/src/engine/metadata-modules/types/object-metadata-maps.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/get-object-metadata-map-item-by-name-singular.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/generate-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/get-object-metadata-map-item-by-name-singular.util.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/record-crud.workflow-action.ts
Labels: -PR: awaiting author

#8637 Improve docker compose
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/scripts/1-click.sh
  packages/twenty-docker/scripts/install.sh
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
Labels: -PR: awaiting author

#8198 fix: soft deleted records are read only
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useIsFieldReadOnly.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useIsFieldValueReadOnly.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldValueReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/__tests__/isFieldValueReadOnly.test.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldMetadataReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordBoardRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordTableRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/SummaryCard.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/RecordTableCell.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRowContext.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__mocks__/cell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellFromCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/testing/jest/JestRecordStoreSetter.tsx
Labels: -PR: awaiting review

#8652 Fix action menu padding
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuHeader.tsx
Labels: -PR: awaiting review

#8645 Enforce unique constraints for 0.33
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-enforce-unique-constraints.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-update-rich-text-search-vector-expression.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-upgrade-version.module.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-index.decorator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-field.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view-sort.workspace-entity.ts
Labels: -PR: awaiting review

#8610 8414 add records selection context inside the command menu
  packages/twenty-front/src/modules/action-menu/actions/global-actions/workflow-run-actions/components/WorkflowRunActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/DeleteRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ExportRecordsActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/ManageFavoritesActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/workflow-run-record-actions/components/WorkflowRunRecordActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuEffect.tsx
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBarEntry.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordShowActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuCommandsEffect.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuSearchBarHeight.ts
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuSearchBarPadding.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/types/Command.ts
  packages/twenty-front/src/modules/command-menu/utils/computeCommandMenuCommands.ts
  packages/twenty-front/src/modules/context-store/components/MainContextStoreComponentInstanceIdSetterEffect.tsx
  packages/twenty-front/src/modules/context-store/hooks/useContextStoreCurrentObjectMetadataIdOrThrow.ts
  packages/twenty-front/src/modules/context-store/hooks/useContextStoreSelectedRecords.ts
  packages/twenty-front/src/modules/context-store/states/mainContextStoreComponentInstanceId.ts
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
Labels: -PR: awaiting review

#8674 Update self-hosting upgrade guide for 0.33
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review

#8675 Bump 0.34.0-canary
  packages/twenty-emails/package.json
  packages/twenty-front/package.json
  packages/twenty-server/package.json
  packages/twenty-ui/package.json
  packages/twenty-website/package.json
Labels: -PR: awaiting review

#8676 Fix RICH_TEXT display on cell
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/TextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useTextFieldDisplay.ts
Labels: -PR: awaiting review

#8682 Fix filter multi select
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterViewFilterValueInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownDateInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterOperandSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandButton.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandDropdown.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterOperandSelectAndInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/__tests__/useFilterDropdown.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useFilterDropdown.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useFilterDropdownStates.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/FiltersHotkeyScope.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuHeader.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownUnmountEffect.tsx
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
Labels: -PR: awaiting review

#8684 fix-percentage
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberForm.tsx
Labels: -PR: wip

#8611 refactor(workspaces): Rename SEED_TWENTY_WORKSPACE_ID to SEED_ACME_WO…
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/typeorm-seeds/core/userWorkspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/core/workspaces.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/workspace-members.ts
Labels: -PR: awaiting review

#8312 Docs troubleshooting page
  packages/twenty-website/src/content/developers/constants/DocsIndex.ts
  packages/twenty-website/src/content/developers/local-setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/cloud-providers.mdx
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
  packages/twenty-website/src/content/developers/self-hosting/troubleshooting.mdx
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
  packages/twenty-website/src/content/user-guide/functions/notes.mdx
  packages/twenty-website/src/content/user-guide/objects/fields.mdx
  packages/twenty-website/src/content/user-guide/objects/import-export-data.mdx
  packages/twenty-website/src/content/user-guide/objects/views-sort-filter.mdx
  packages/twenty-website/src/content/user-guide/other/glossary.mdx
Labels: -PR: awaiting review

#8712 Website - Readme update
  packages/twenty-website/README.md
  packages/twenty-website/src/content/developers/local-setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/troubleshooting.mdx
Labels: -PR: wip

#8619 fix: navigation drawer clip while making folder in favorites
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavoritesFolders.tsx
  packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPickerFooter.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerInput.tsx
Labels: -PR: awaiting review

#8559 Allow standard field default value and settings editing (#7104)
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/components/SettingsDataModelFieldBooleanForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-field.comparator.ts
Labels: -PR: awaiting author

#8740 Fix mutations with camelCase table names
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
Labels: -PR: awaiting review

#8729 Fix labelIdentifierFieldMetadata creation for custom objects
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
Labels: -PR: awaiting review

#8732 Gmail error handling fixes
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/message-import-exception-handler.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
Labels: -PR: awaiting review

#8653 refactor(auth): clean up and enhance sign-in-up logic
  packages/twenty-server/src/database/typeorm/core/migrations/1730298416367-addAuthProvidersColumnsToWorkspace.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/utils/cast-appToken-to-workspaceInvitation.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/utils/cast-appToken-to-workspaceInvitation.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/workspace-invitation.exception.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/workspace-invitation.module.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.module.ts
Labels: -PR: awaiting review

#8722 feat(server): allow to use ssl on server
  packages/twenty-server/.env.example
  packages/twenty-server/scripts/ssl-generation/README.md
  packages/twenty-server/scripts/ssl-generation/script.sh
  packages/twenty-server/src/engine/core-modules/auth/controllers/sso-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/sso/services/sso.service.ts
  packages/twenty-server/src/main.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
Labels: -PR: awaiting review

#8613 Treat no value view group as normal & enable hide/dnd for no value
  packages/twenty-front/src/modules/object-record/record-group/components/RecordGroupMenuItemDraggable.tsx
  packages/twenty-front/src/modules/object-record/record-group/components/RecordGroupsVisibilityDropdownSection.tsx
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/views/utils/mapViewGroupsToRecordGroupDefinitions.ts
Labels: -PR: awaiting review

#8761 Refactor actions
  packages/twenty-front/src/modules/action-menu/actions/global-actions/components/GlobalActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/components/MultipleRecordsActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useExportMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useMultipleRecordsActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/components/NoSelectionActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useExportMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useNoSelectionRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/components/SingleRecordActionMenuEntrySetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDeleteSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useManageFavoritesSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useSingleRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/workflow-run-record-actions/hooks/useWorkflowRunRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/components/RecordAgnosticActionsSetterEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/hooks/useGlobalActions.ts
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/workflow-run-actions/hooks/useWorkflowRunActions.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerActionMenu.tsx
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuCommandsEffect.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChipAvatars.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuNavigateCommands.ts
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuCommandsSelector.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuCommandsState.ts
  packages/twenty-front/src/modules/command-menu/utils/computeCommandMenuCommands.ts
  packages/twenty-front/src/modules/context-store/components/MainContextStoreComponentInstanceIdSetterEffect.tsx
  packages/twenty-front/src/modules/context-store/constants/ContextStoreInstanceIdDefaultValue.tsx
  packages/twenty-front/src/modules/context-store/hooks/useContextStoreCurrentObjectMetadataIdOrThrow.ts
  packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts
  packages/twenty-front/src/modules/context-store/states/mainContextStoreComponentInstanceId.ts
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
Labels: -PR: awaiting review

#8720 feat(front): improve logo component
  packages/twenty-front/src/modules/auth/components/Logo.tsx
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/utils/image/getImageAbsoluteURI.ts
Labels: -PR: awaiting review

#8771 Fix index renaming
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-migration.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-relation.service.ts
Labels: -PR: awaiting review

#8742 Admin panel init
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/modules/app/components/AppRouter.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/app/hooks/useCreateAppRouter.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminImpersonateUsers.tsx
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminFeatureFlagsTabs.ts
  packages/twenty-front/src/modules/settings/admin-panel/graphql/mutations/updateWorkspaceFeatureFlag.ts
  packages/twenty-front/src/modules/settings/admin-panel/graphql/mutations/userLookupAdminPanel.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useFeatureFlagsManagement.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonate.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/FeatureFlag.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/UserLookup.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/WorkspaceInfo.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useWorkspaceSwitching.ts
  packages/twenty-front/src/pages/impersonate/ImpersonateEffect.tsx
  packages/twenty-front/src/pages/impersonate/__stories__/ImpersonateEffect.stories.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdmin.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminFeatureFlags.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.module.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/impersonate.input.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/update-workspace-feature-flag.input.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/user-lookup.entity.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/user-lookup.input.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting author

#8783 line breaks in tooltips & text
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
  packages/twenty-front/src/modules/ui/field/display/components/TextDisplay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: -PR: awaiting review

#8794 Rename enum types when tables are renamed
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-migration.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.exception.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/__tests__/workspace-migration-enum.service.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/workspace-migration-enum.service.ts
Labels: -PR: awaiting review

#8776 Add ongoing stale crons commands to doc
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
Labels: -PR: awaiting review

#8634 Create form field number
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormBooleanFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormNumberFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/StyledFormFieldInputContainer.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/StyledFormFieldInputInputContainer.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/StyledFormFieldInputRowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/TextVariableEditor.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/VariableChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormBooleanFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormNumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormTextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/hooks/useTextVariableEditor.ts
  packages/twenty-front/src/modules/object-record/record-field/form-types/types/EditingMode.ts
  packages/twenty-front/src/modules/object-record/record-field/form-types/types/VariablePickerComponent.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/hooks/useRegisterInputEvents.ts
  packages/twenty-front/src/modules/ui/field/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/InputLabel.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormRecordCreate.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunctionInner.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowVariablePicker.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/SearchVariablesDropdown.tsx
  packages/twenty-front/src/modules/workflow/search-variables/components/VariableTagInput.tsx
  packages/twenty-front/src/modules/workflow/search-variables/utils/__tests__/extractVariableLabel.test.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/extractVariableLabel.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/initializeEditorContent.ts
  packages/twenty-front/src/modules/workflow/search-variables/utils/variableTag.ts
  packages/twenty-front/src/modules/workflow/utils/__tests__/isStandaloneVariableString.test.ts
  packages/twenty-front/src/modules/workflow/utils/isStandaloneVariableString.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/types/workflow-record-crud-action-input.type.ts
Labels: -PR: awaiting review

#8808 Do not mount the command menu when the user is logged out
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
Labels: -PR: awaiting review

#8781 feat: table record group
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/useSetRecordBoardRecordIds.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useSetRecordIdsForColumn.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumn.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-board/states/selectors/recordBoardSelectedRecordIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupVisibility.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useSetRecordGroup.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/hiddenRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/visibleRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-group/utils/sortRecordGroupDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexAllRowIdsComponentState.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexRecordIdsByGroupComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-index/states/selectors/recordIndexAllRecordIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-index/states/selectors/recordIndexRecordGroupIsDraggableSortComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyHandler.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSelectAllRows.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTableMoveFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDragDropContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDroppable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyRecordGroupDragDropContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableNoRecordGroupBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useUpsertRecord.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useUpsertRecord.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/states/isRecordGroupTableSectionToggledComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/allRowsSelectedStatusComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/selectedRowIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/unselectedRowIdsComponentSelector.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/utils/createComponentSelectorV2.ts
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemSelect.tsx
Labels: -PR: awaiting CI

#8806 Fix delete trigger node
  packages/twenty-front/src/modules/workflow/hooks/useDeleteOneStep.ts
Labels: -PR: awaiting review

#8801 Updated website docs and /twenty-server/.env
  .github/workflows/ci-server.yaml
  .github/workflows/ci-website.yaml
  Makefile
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-db.yaml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/manifests/deployment-worker.yaml
  packages/twenty-e2e-testing/drivers/env_variables.ts
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/scripts/render-worker.sh
  packages/twenty-website/src/content/developers/local-setup.mdx
Labels: -PR: awaiting review

#8804 Don't show summary/fields on workflow record pages
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/constants/BaseRecordLayout.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/types/RecordLayout.ts
  packages/twenty-front/src/modules/object-record/record-show/types/RecordLayoutMap.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
Labels: -PR: awaiting review
