Repository twentyhq/twenty, pull requests merged in 2024-09, with the labels that each got.

#6745 fix(6423): add username and password for redis connection
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/integrations/cache-storage/cache-storage.module-factory.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/message-queue/message-queue.module-factory.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
Labels: PR: awaiting review

#6892 multiselect for onetomany relations
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultipleObjectRecordSelectItem.tsx
Labels: PR: awaiting review

#6700 Added new view to select types for objects
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelNewFieldBreadcrumbDropDown.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeCategories.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeCategoryDescriptions.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldDescriptionForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldDescriptionForm.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldIconLabelForm.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldTypeSelect.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/modules/settings/data-model/types/SettingsFieldTypeCategoryType.ts
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/Breadcrumb.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#6725 added timeout to avoid appending of blocks
  packages/twenty-front/src/modules/activities/components/RichTextEditor.tsx
Labels: PR: awaiting review

#6908 Fix/object detail recordcell tooltip
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
Labels: PR: awaiting author

#6829 added button in nav bar for kanban view
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageKanbanAddButton.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageKanbanAddMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordIndexPageKanbanAddButton.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordIndexPageKanbanAddMenuItem.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: PR: awaiting author

#6971 Add relations to notes/tasks list view
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityTargetObjectRecords.test.tsx
  packages/twenty-front/src/modules/activities/hooks/useActivityTargetObjectRecords.ts
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getLabelIdentifierFieldValue.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/RelationFromManyFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordTableRecordGqlFields.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/notes-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/tasks-all.view.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
  packages/twenty-server/src/modules/view/services/view.service.ts
Labels: -PR: awaiting CI

#6998 add contibuting_example.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
Labels: -PR: awaiting review

#7006 Set all standard objects soft deletable
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-object.factory.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note-target.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task-target.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
Labels: -PR: awaiting review

#6926 Scaffold empty workflow
  packages/twenty-front/src/modules/workflow/components/RightDrawerWorkflowEditStepContent.tsx
  packages/twenty-front/src/modules/workflow/components/Workflow.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramStepNode.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditActionForm.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEditTriggerForm.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowShowPageHeader.tsx
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowWithCurrentVersion.tsx
  packages/twenty-front/src/modules/workflow/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/utils/getWorkflowVersionDiagram.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/interfaces/workspace-query-hook.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/storage/workspace-query-hook.storage.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-many.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-one.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-query-hook.module.ts
  packages/twenty-server/src/modules/workflow/common/utils/assert-workflow-version-is-draft.util.ts
  packages/twenty-server/src/modules/workflow/common/utils/assert-workflow-version-trigger-is-defined.util.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-version-can-be-activated.util.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
Labels: -PR: awaiting review

#6972 Display tag for workflow version status
  packages/twenty-front/src/modules/workflow/components/Workflow.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowEffect.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowVersionStatusTag.tsx
  packages/twenty-front/src/modules/workflow/components/__stories__/WorkflowVersionStatusTag.stories.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
Labels: -PR: awaiting author

#6996 add field config new icons
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-ui/src/display/icon/assets/illustration-calendar-event.svg
  packages/twenty-ui/src/display/icon/assets/illustration-calendar-time.svg
  packages/twenty-ui/src/display/icon/assets/illustration-currency.svg
  packages/twenty-ui/src/display/icon/assets/illustration-json.svg
  packages/twenty-ui/src/display/icon/assets/illustration-link.svg
  packages/twenty-ui/src/display/icon/assets/illustration-mail.svg
  packages/twenty-ui/src/display/icon/assets/illustration-map.svg
  packages/twenty-ui/src/display/icon/assets/illustration-numbers.svg
  packages/twenty-ui/src/display/icon/assets/illustration-one-to-many.svg
  packages/twenty-ui/src/display/icon/assets/illustration-phone.svg
  packages/twenty-ui/src/display/icon/assets/illustration-setting.svg
  packages/twenty-ui/src/display/icon/assets/illustration-star.svg
  packages/twenty-ui/src/display/icon/assets/illustration-tag.svg
  packages/twenty-ui/src/display/icon/assets/illustration-tags.svg
  packages/twenty-ui/src/display/icon/assets/illustration-text.svg
  packages/twenty-ui/src/display/icon/assets/illustration-toggle.svg
  packages/twenty-ui/src/display/icon/assets/illustration-uid.svg
  packages/twenty-ui/src/display/icon/assets/illustration-user.svg
  packages/twenty-ui/src/display/icon/components/IllustrationIconCalendarEvent.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconCalendarTime.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconCurrency.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconJson.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconMail.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconMap.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconNumbers.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconOneToMany.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconPhone.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconSetting.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconStar.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconTag.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconTags.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconText.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconToggle.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconUid.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconUser.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconWrapper.tsx
  packages/twenty-ui/src/display/icon/components/llustrationIconLink.tsx
  packages/twenty-ui/src/display/index.ts
  packages/twenty-ui/src/theme/constants/IllustrationIconDark.ts
  packages/twenty-ui/src/theme/constants/IllustrationIconLight.ts
  packages/twenty-ui/src/theme/constants/ThemeDark.ts
  packages/twenty-ui/src/theme/constants/ThemeLight.ts
  packages/twenty-ui/src/theme/index.ts
  packages/twenty-ui/tsconfig.dev.json
Labels: -PR: awaiting author

#7004 removed @chakra-ui dependencies
  package.json
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UnmatchColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UnmatchColumnBanner.tsx
  packages/twenty-front/vite.config.ts
  packages/twenty-ui/src/display/banner/components/Banner.tsx
  packages/twenty-ui/src/index.ts
  packages/twenty-ui/src/layout/expandableContainer/components/ExpandableContainer.tsx
  packages/twenty-ui/src/layout/expandableContainer/components/__stories__/ExpandableContainer.stories.tsx
  packages/twenty-ui/src/layout/index.ts
  yarn.lock
Labels: -PR: awaiting author

#7041 [flexible-schema] Add createOne/createMany with upsert to graphql query runner
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
Labels: -PR: awaiting review

#7046 Fix: Set sync stage started at when starting sync
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
Labels: -PR: awaiting review

#6985 fix: page header accessible when deleting webhook
  packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx
Labels: -PR: awaiting review

#6906 Fixes resetting of scroll position in RecordShowPage due to opening of some dropdowns (#6890)
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-index/contexts/RecordIndexEventContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx
  packages/twenty-front/src/modules/ui/input/hooks/useInputFocusWithoutScrollOnMount.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx
Labels: -PR: awaiting CI

#6953 Twnty-#6797 view/edit inactive feature
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFilteredObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDisabledActionDropdown.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
Labels: -PR: awaiting CI

#6970 fix: Tasks page overflows with large title and body
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
Labels: -PR: awaiting review

#7116 7059 Fix email loading in the timeline
  packages/twenty-front/src/modules/activities/timelineActivities/rows/message/components/EventCardMessage.tsx
Labels: -PR: awaiting review

#6974 enhance picture uploader, change justify content
  packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx
Labels: -PR: awaiting CI

#7122 Backfill workspace favorites
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-backfill-workspace-favorites.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-31/0-31-upgrade-version.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/demo-objects-prefill-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/standard-objects-prefill-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/workflows-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
Labels: -PR: awaiting review

#7093 Add SettingsCard for Config Data Type and Accounts Settings
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/components/SettingsCard.tsx
  packages/twenty-front/src/modules/settings/components/__stories__/SettingsCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/RelationTypes.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-ui/src/display/icon/assets/illustration-array.svg
  packages/twenty-ui/src/display/icon/assets/illustration-many-to-many.svg
  packages/twenty-ui/src/display/icon/assets/illustration-one-to-many.svg
  packages/twenty-ui/src/display/icon/assets/illustration-one-to-one.svg
  packages/twenty-ui/src/display/icon/components/IllustrationIconArray.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconManyToMany.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconOneToOne.tsx
  packages/twenty-ui/src/display/icon/components/IllustrationIconWrapper.tsx
  packages/twenty-ui/src/display/index.ts
  packages/twenty-ui/src/theme/constants/Icon.ts
Labels: run-chromatic, -PR: awaiting review

#7117 Fix sync statuses on the fe
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/accounts/types/CalendarChannel.ts
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsRowRightContainer.tsx
  packages/twenty-front/src/modules/settings/accounts/constants/SyncStatus.ts
  packages/twenty-front/src/modules/settings/accounts/utils/__tests__/computeSyncStatus.test.ts
  packages/twenty-front/src/modules/settings/accounts/utils/computeSyncStatus.ts
  packages/twenty-server/src/engine/core-modules/calendar/dtos/timeline-calendar-event.dto.ts
  packages/twenty-server/src/engine/core-modules/messaging/dtos/timeline-thread.dto.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
Labels: -PR: awaiting review

#7129 Improved note cards design
  packages/twenty-front/src/modules/activities/notes/components/NoteCard.tsx
Labels: -PR: awaiting review

#7133 Add deletedAt to foreignKey indexes
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-index.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-column.factory.ts
Labels: -PR: awaiting review

#7148 7142 make messaging full message list fetch idempotent
  packages/twenty-server/src/modules/calendar/common/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-add-single-message-to-cache-for-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-clean-cache.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
Labels: -PR: awaiting author

#6736 fix: Input fields to have expected behaviour in case of empty / only whitespaces string
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/FullNameFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/NumberFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/TextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/isDoubleTextFieldEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx
  packages/twenty-front/src/modules/settings/workspace/components/NameField.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DoubleTextInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/TextArea.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx
  packages/twenty-front/src/modules/workspace/components/WorkspaceInviteTeam.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionsNew.tsx
  packages/twenty-front/src/utils/format/spiltFullName.ts
  packages/twenty-front/src/utils/string/turnIntoEmptyStringIfWhitespacesOnly.ts
  packages/twenty-front/src/utils/string/turnIntoUndefinedIfWhitespacesOnly.ts
Labels: -PR: awaiting CI

#7185 7182 person avatar is not the same color in emails and calendar
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.ts
Labels: -PR: awaiting review

#7184 Set a unique constraint on email table in users #7180
  packages/twenty-server/src/database/typeorm/core/migrations/1726849473832-addUniqueConstraintOnUsers.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
Labels: -PR: awaiting author

#7168 minor fix - email thread reply button stylings/corrections
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
Labels: -PR: awaiting author

#7187 Fix paginated order by with composite fields
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/compute-cursor-arg-filter.ts
Labels: -PR: awaiting review

#7202 Fix IN filter with empty array
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsContainer.tsx
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-filter/graphql-query-filter-field.parser.ts
Labels: -PR: awaiting review

#6997 Introduced Specific Icons image identifier for Notes and Tasks
  packages/twenty-front/src/modules/object-metadata/hooks/useGetStandardObjectIcon.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  packages/twenty-ui/src/display/avatar/components/Avatar.tsx
  packages/twenty-ui/src/display/avatar/types/AvatarType.ts
  packages/twenty-ui/src/display/chip/components/AvatarChip.tsx
Labels: -PR: awaiting CI

#7232 fix: Appearance Settings Cropped Card
  packages/twenty-front/src/modules/ui/input/color-scheme/components/ColorSchemePicker.tsx
Labels: -PR: awaiting review

#7234 fix: #7226 - Improve photo uploader design
  packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#7208 Remove shouldUseEmailsField
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-contact.service.ts
Labels: -PR: awaiting review

#7207 Add try catch around messaging monitoring cron and fix decorators
  packages/twenty-server/src/modules/messaging/monitoring/crons/commands/messaging-message-channel-sync-status-monitoring.cron.command.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.job.ts
  packages/twenty-server/src/modules/messaging/monitoring/messaging-monitoring.module.ts
Labels: -PR: awaiting review

#6866 fix: Phone dropdown field has extra width
  packages/twenty-front/src/modules/ui/input/components/internal/phone/components/PhoneCountryPickerDropdownSelect.tsx
Labels: -PR: awaiting review

#6945 'Display as relative date' field formatting option for dateTime and date fields #5398
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToRelativeDate.ts
  packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts
  packages/twenty-front/src/modules/object-metadata/graphql/queries.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/DateFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/DateTimeFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useDateFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useDateTimeFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelPreviewFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/components/StyledFormCardTitle.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldToggle.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/components/SettingsDataModelFieldDateForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/components/SettingsDataModelFieldDateSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/hooks/useDateSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateTimeDisplay.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/twenty-orm/base.workspace-entity.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-field.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-field-metadata-args.interface.ts
  packages/twenty-server/src/engine/twenty-orm/storage/metadata-args.storage.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-field.factory.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#7251 7242 error when displaying message threads with a large number of participants
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx
  packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/IntermediaryMessages.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/types/EmailThreadMessageParticipant.ts
  packages/twenty-front/src/modules/activities/emails/types/EmailThreadMessageWithSender.ts
  packages/twenty-front/src/modules/activities/emails/utils/__tests__/getDisplayNameFromParticipant.test.ts
Labels: -PR: awaiting review

#7248 fix: Values field card lacks width in mobile viewports
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
Labels: -PR: awaiting review

#7258 Fixing last column width in table-view
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastColumn.tsx
Labels: -PR: awaiting review

#7249 Fix LinkedIn URL special character formatting
  packages/twenty-front/src/utils/getDisplayValueByUrlType.ts
Labels: -PR: awaiting review

#7259 Fix: Remove 'Soon' integrations from Settings when disabled
  packages/twenty-front/src/modules/settings/integrations/hooks/useSettingsIntegrationCategories.ts
  packages/twenty-front/src/modules/settings/integrations/utils/getSettingsIntegrationAll.ts
Labels: -PR: awaiting review

#7270 5922 - UI Overlap and State Persistence in Filter Menus
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandButton.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
Labels: -PR: awaiting review

#7196 Date filter improvements (#5917)
  package.json
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownDateInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useSelectFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/Filter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/__tests__/getOperandsForFilterType.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getInitialFilterValue.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandLabel.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandsForFilterType.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getRelativeDateDisplayValue.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/AbsoluteDatePickerHeader.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/constants/RelativeDateDirectionSelectOptions.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/constants/RelativeDateUnitSelectOptions.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/utils/getHighlightedDates.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/utils/getMonthSelectOptions.ts
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/types/ViewFilterOperand.ts
  packages/twenty-front/src/modules/views/utils/view-filter-value/computeVariableDateViewFilterValue.ts
  packages/twenty-front/src/modules/views/utils/view-filter-value/resolveDateViewFilterValue.ts
  packages/twenty-front/src/modules/views/utils/view-filter-value/resolveFilterValue.ts
  packages/twenty-front/src/modules/views/utils/view-filter-value/resolveNumberViewFilterValue.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query.parser.ts
  packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts
  yarn.lock
Labels: -PR: awaiting author

#7311 fix: Title overflows in mobile viewport for right drawer
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
Labels: -PR: awaiting author
