Repository twentyhq/twenty, pull requests merged in 2024-02, with the labels that each got.

#3622 fix: grapQL errors are not detailed enough
  packages/twenty-server/src/filters/utils/global-exception-handler.util.ts
Labels: PR: awaiting review

#3731 3706 add email loader
  packages/twenty-front/public/images/placeholders/background/loading_messages_bg.png
  packages/twenty-front/public/images/placeholders/moving-image/loading_messages.png
  packages/twenty-front/src/modules/activities/emails/components/EmailLoader.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/ui/feedback/loader/components/Loader.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/constants/AnimatedImages.ts
Labels: PR: awaiting review

#3688 Fix zapier
  packages/twenty-zapier/package.json
  packages/twenty-zapier/src/test/authentication.test.ts
  packages/twenty-zapier/src/triggers/trigger_record.ts
  packages/twenty-zapier/src/utils/creates/creates.utils.ts
  packages/twenty-zapier/src/utils/triggers/triggers.utils.ts
  yarn.lock
Labels: PR: awaiting review

#3751 feat: delete favorite in cache on related record deletion
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRelationsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/types/coreObjectNamesToDeleteOnRelationDetach.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useGenerateCachedObjectRecord.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useGenerateObjectRecordOptimisticResponse.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecordsInCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecordInCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
  packages/twenty-front/src/modules/pipeline/hooks/__mocks__/usePipelineSteps.ts
Labels: PR: awaiting review

#3467 feat: add user to sentry
  packages/twenty-server/package.json
  packages/twenty-server/src/command.ts
  packages/twenty-server/src/core/api-rest/api-rest-query-builder/api-rest-query-builder.factory.ts
  packages/twenty-server/src/core/auth/services/token.service.ts
  packages/twenty-server/src/core/open-api/open-api.service.ts
  packages/twenty-server/src/filters/utils/global-exception-handler.util.ts
  packages/twenty-server/src/graphql-config.service.ts
  packages/twenty-server/src/integrations/exception-handler/drivers/console.driver.ts
  packages/twenty-server/src/integrations/exception-handler/drivers/sentry.driver.ts
  packages/twenty-server/src/integrations/exception-handler/exception-handler.service.ts
  packages/twenty-server/src/integrations/exception-handler/hooks/use-exception-handler.hook.ts
  packages/twenty-server/src/integrations/exception-handler/interfaces/exception-handler-driver.interface.ts
  packages/twenty-server/src/integrations/exception-handler/interfaces/exception-handler-options.interface.ts
  packages/twenty-server/src/integrations/exception-handler/interfaces/exception-handler-user.interface.ts
  packages/twenty-server/src/main.ts
  packages/twenty-server/src/metadata/metadata.module-factory.ts
  packages/twenty-server/src/metadata/metadata.module.ts
  packages/twenty-server/src/queue-worker.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  yarn.lock
Labels: PR: awaiting review

#3739 Create record position field
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunity.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/opportunity.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/person.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/company.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/opportunity.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
Labels: PR: awaiting review

#3774 Add animation during email message opening
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageBody.tsx
Labels: PR: awaiting review

#3783 Fetch viewable thread from apollo cache
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/state/viewableEmailThreadIdState.ts
  packages/twenty-front/src/modules/activities/emails/state/viewableEmailThreadState.ts
Labels: PR: awaiting review

#3782 [messaging] add fallback if lastHistoryId has been invalidated
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
Labels: PR: awaiting review

#3752 Hide default selected icon from search
  packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx
Labels: PR: awaiting author

#3738 fix: options value can't contain special characters
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/formatFieldMetadataItemInput.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
Labels: PR: awaiting review

#3800 [messaging] add cronjob for workspaces messages partial sync
  packages/twenty-server/src/command.module.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/queue-worker.module.ts
  packages/twenty-server/src/workspace/cron/fetch-all-workspaces-messages/commands/start-fetch-all-workspaces-messages.cron.command.ts
  packages/twenty-server/src/workspace/cron/fetch-all-workspaces-messages/commands/stop-fetch-all-workspaces-messages.cron.command.ts
  packages/twenty-server/src/workspace/cron/fetch-all-workspaces-messages/fetch-all-workspaces-messages.cron.pattern.ts
  packages/twenty-server/src/workspace/cron/fetch-all-workspaces-messages/fetch-all-workspaces-messages.job.ts
  packages/twenty-server/src/workspace/messaging/jobs/gmail-full-sync.job.ts
  packages/twenty-server/src/workspace/messaging/jobs/gmail-partial-sync.job.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-full-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
Labels: PR: awaiting author

#3756 Custom object import csv
  packages/twenty-front/src/modules/companies/hooks/useSpreadsheetCompanyImport.ts
  packages/twenty-front/src/modules/companies/utils/fieldsForCompany.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordIndexOptionsImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/__tests__/useSpreadsheetRecordImport.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/useSpreadsheetRecordImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/util/getSpreadSheetValidation.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/util/isValidUuid.ts
  packages/twenty-front/src/modules/people/hooks/__mocks__/useSpreadsheetPersonImport.ts
  packages/twenty-front/src/modules/people/hooks/__tests__/useSpreadsheetPersonImport.test.tsx
  packages/twenty-front/src/modules/people/hooks/useSpreadsheetPersonImport.ts
  packages/twenty-front/src/modules/people/utils/fieldsForPerson.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelect.tsx
Labels: PR: awaiting review

#3864 Rename recordPosition into position
  packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunity.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/people.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/company.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/opportunity.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/person.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/company.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/opportunity.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
Labels: PR: awaiting author

#3543 Added sanitize funtion to normalize the link input
  packages/twenty-front/src/modules/object-record/utils/sanitizeLinkRecordInput.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
Labels: PR: awaiting author

#3826 feat: add deletion support on sync metadata command
  packages/twenty-server/src/metadata/workspace-migration/utils/generate-migration-name.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/field-workspace-migration.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/object-workspace-migration.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/relation-workspace-migration.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/standard-object.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/standard-relation.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/workspace-sync.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-relation-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync-metadata.service.ts
Labels: PR: awaiting review

#3566 Add rate limiting in the server using built in Nest.js capability
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/package.json
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/graphql-config/factories/create-context.factory.ts
  packages/twenty-server/src/graphql-config/factories/index.ts
  packages/twenty-server/src/graphql-config/graphql-config.module.ts
  packages/twenty-server/src/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/graphql-config/interfaces/graphql-context.interface.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/exception-handler/hooks/use-exception-handler.hook.ts
  packages/twenty-server/src/integrations/throttler/hooks/use-throttler.ts
  packages/twenty-server/src/metadata/metadata.module-factory.ts
  packages/twenty-server/src/metadata/metadata.module.ts
  yarn.lock
Labels: PR: awaiting review

#3863 Feat/workspace health core fix
  packages/twenty-server/src/metadata/workspace-migration/utils/generate-migration-name.util.ts
  packages/twenty-server/src/workspace/workspace-health/commands/workspace-health.command.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-fix-kind.interface.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-issue.interface.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-nullable.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix.service.ts
  packages/twenty-server/src/workspace/workspace-health/utils/is-workspace-health-issue-type.util.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.module.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.service.ts
  packages/twenty-server/src/workspace/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/factories/index.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/factories/workspace-migration-field.factory.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/factories/workspace-migration-object.factory.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/factories/workspace-migration-relation.factory.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/interfaces/workspace-migration-builder-action.interface.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/workspace-migration-builder.module.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-relation-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync-metadata.module.ts
Labels: PR: awaiting review

#3872 3491 launch cleaning cron
  packages/twenty-server/src/command.module.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/utils/get-dry-run-log-header.ts
  packages/twenty-server/src/workspace/messaging/commands/fetch-workspace-messages-commands.module.ts
  packages/twenty-server/src/workspace/messaging/commands/start-fetch-all-workspaces-messages.cron.command.ts
  packages/twenty-server/src/workspace/messaging/commands/stop-fetch-all-workspaces-messages.cron.command.ts
  packages/twenty-server/src/workspace/messaging/crons/fetch-all-workspaces-messages.cron.pattern.ts
  packages/twenty-server/src/workspace/messaging/crons/fetch-all-workspaces-messages.job.ts
  packages/twenty-server/src/workspace/workspace-cleaner/commands/clean-inactive-workspaces.command.ts
  packages/twenty-server/src/workspace/workspace-cleaner/commands/delete-incomplete-workspaces.command.ts
  packages/twenty-server/src/workspace/workspace-cleaner/commands/start-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/workspace/workspace-cleaner/commands/stop-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/workspace/workspace-cleaner/crons/clean-inactive-workspace.cron.pattern.ts
  packages/twenty-server/src/workspace/workspace-cleaner/crons/clean-inactive-workspace.job.ts
  packages/twenty-server/src/workspace/workspace-cleaner/workspace-cleaner.module.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/opportunity.ts
Labels: PR: awaiting author

#3740 Added skeleton loader on page load
  packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
Labels: PR: awaiting review

#3859 3272 add a page to create and edit webhook
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/developers/components/SettingsDevelopersWebhookTableRow.tsx
  packages/twenty-front/src/modules/settings/developers/types/api-key/ApiFieldItem.ts
  packages/twenty-front/src/modules/settings/developers/types/api-key/ApiKey.ts
  packages/twenty-front/src/modules/settings/developers/types/webhook/Webhook.ts
  packages/twenty-front/src/modules/settings/developers/types/webhook/WebhookFieldItem.ts
  packages/twenty-front/src/modules/settings/developers/utils/format-expiration.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersApiKeys.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersApiKeysDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersApiKeysNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopersWebhooks.stories.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeys.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooks.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/testing/mock-data/api-keys.ts
Labels: PR: awaiting review

#3867 Fixed drawer not closing on task creation on Show Page
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageAddButton.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/constants/ShowPageAddButtonDropdownId.ts
Labels: PR: awaiting review

#3866 Add one to many relation between opportunity and attachment
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/attachment.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/opportunity.object-metadata.ts
Labels: PR: awaiting author

#3850 Store compact view status
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoard.ts
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordIndexOptionsForBoard.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexIsCompactModeActiveState.ts
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewScopedStates.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViews.ts
  packages/twenty-front/src/modules/views/hooks/useViewBar.ts
  packages/twenty-front/src/modules/views/scopes/ViewScope.tsx
  packages/twenty-front/src/modules/views/scopes/init-effect/ViewScopeInitEffect.tsx
  packages/twenty-front/src/modules/views/states/onViewCompactModeChangeScopeState.ts
  packages/twenty-front/src/modules/views/types/GraphQLView.ts
  packages/twenty-front/src/modules/views/utils/getViewScopedStateValuesFromSnapshot.ts
  packages/twenty-front/src/modules/views/utils/internal/getViewScopedStates.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/view.object-metadata.ts
Labels: PR: awaiting review

#3875 3804 use email visibility to display only the shared information frontend
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadNotShared.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
Labels: PR: awaiting review

#3596 feat: change RecordShowPage Relation Card field display for TO_ONE_OB…
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
Labels: PR: awaiting review

#3890 feat: workspace health type fix
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-type.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix.service.ts
  packages/twenty-server/src/workspace/workspace-health/utils/is-workspace-health-issue-type.util.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.module.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/services/workspace-migration-type.service.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.module.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: PR: awaiting review

#3737 3628 timebox separate user creation from workspace creation
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/hooks/__test__/useOnboardingStatus.test.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/states/selectors/isCurrentWorkspaceActiveSelector.ts
  packages/twenty-front/src/modules/auth/utils/__test__/getOnboardingStatus.test.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/navigation/components/MobileNavigationBar.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsProvider.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItemOnly.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectNamePluralFromSingular.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectNameSingularFromPlural.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/states/isCreateModeScopedState.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchEntityQuery.test.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUser.ts
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUserAndViews.ts
  packages/twenty-front/src/modules/workspace/graphql/mutations/activateWorkspace.ts
  packages/twenty-front/src/pages/auth/CreateProfile.tsx
  packages/twenty-front/src/pages/auth/CreateWorkspace.tsx
  packages/twenty-front/src/pages/auth/VerifyEffect.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateProfile.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateWorkspace.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PlanRequired.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/pages/impersonate/ImpersonateEffect.tsx
  packages/twenty-front/src/pages/not-found/NotFound.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/user/services/user.service.ts
  packages/twenty-server/src/core/user/user.entity.ts
  packages/twenty-server/src/core/user/user.resolver.ts
  packages/twenty-server/src/core/workspace/dtos/activate-workspace-input.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/core/workspace/services/workspace.service.ts
  packages/twenty-server/src/core/workspace/workspace.module.ts
  packages/twenty-server/src/core/workspace/workspace.resolver.ts
Labels: PR: wip, PR: awaiting author

#3893 Fix delete incomplete workspaces
  packages/twenty-server/src/workspace/workspace-cleaner/commands/delete-incomplete-workspaces.command.ts
  packages/twenty-server/src/workspace/workspace-cleaner/workspace-cleaner.module.ts
Labels: PR: wip, PR: awaiting author

#3788 feat: display record identifier field as first column in table
  packages/twenty-front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  packages/twenty-front/src/modules/companies/utils/mapBoardFieldDefinitionsToViewFields.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useColumnDefinitionsFromFieldMetadata.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts
  packages/twenty-front/src/modules/object-metadata/utils/getLabelIdentifierFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-board-deprecated/options/components/RecordBoardDeprecatedOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordIndexOptionsForBoard.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordIndexOptionsForTable.ts
  packages/twenty-front/src/modules/object-record/record-table/components/ColumnHeadWithDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableColumnDropdownMenu.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useRecordTableStates.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/hiddenTableColumnsSelectorScopeMap.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/tableColumnsByKeySelectorScopeMap.ts
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/visibleTableColumnsSelectorScopeMap.ts
  packages/twenty-front/src/modules/object-record/record-table/types/ColumnDefinition.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/constants/signInBackgroundMockDefinitions.ts
  packages/twenty-front/src/modules/views/components/ViewFieldsVisibilityDropdownSection.tsx
  packages/twenty-front/src/modules/views/utils/__tests__/viewMapFunctions.test.ts
  packages/twenty-front/src/modules/views/utils/mapViewFieldsToColumnDefinitions.ts
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/utils/array/groupArrayItemsBy.ts
  packages/twenty-front/src/utils/array/mapArrayToObject.ts
  packages/twenty-front/src/utils/array/moveArrayItem.ts
Labels: PR: awaiting review

#3894 feat: workspace health default-value fix
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-default-value.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix.service.ts
  packages/twenty-server/src/workspace/workspace-health/utils/is-workspace-health-issue-type.util.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.module.ts
Labels: PR: awaiting review

#3838 Set opportunity stage as editable
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectFormOptionRow.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunity.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/pipeline-step.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/opportunity.ts
  packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/pipeline-step.ts
  packages/twenty-server/src/workspace/workspace-manager/standard-objects-prefill-data/pipeline-step.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/services/workspace-migration-enum.service.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/opportunity.object-metadata.ts
Labels: PR: awaiting review

#3847 Press enter to add to blocklist
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistInput.tsx
Labels: PR: awaiting review

#3881 3808 auto creation of company when importing emails
  packages/twenty-server/src/workspace/messaging/messaging.module.ts
  packages/twenty-server/src/workspace/messaging/services/create-company.service.ts
  packages/twenty-server/src/workspace/messaging/services/messaging-utils.service.ts
Labels: PR: awaiting author

#3789 GH-3652 Add forgot password on sign-in page
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/emailPasswordResetLink.ts
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResetPassword.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUpForm.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInWithGoogle.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useWorkspaceFromInviteHash.ts
  packages/twenty-front/src/modules/settings/profile/components/ChangePassword.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/ActionLink.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/GithubVersionLink.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/__stories__/ActionLink.stories.tsx
  packages/twenty-front/tsup.ui.index.tsx
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/auth/dto/email-password-reset-link.input.ts
Labels: PR: awaiting author

#3903 Added create an activity from open activity
  packages/twenty-front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
Labels: PR: awaiting review

#3902 feat: order board cards by record position
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunity.ts
Labels: PR: awaiting review

#3430 Closes #2413 - Building a chrome extension for twenty to store person/company data into a workspace.
  .github/workflows/ci-chrome-extension.yaml
  .vscode/twenty.code-workspace
  package.json
  packages/twenty-chrome-extension/.env.example
  packages/twenty-chrome-extension/.eslintrc.cjs
  packages/twenty-chrome-extension/.gitignore
  packages/twenty-chrome-extension/README.md
  packages/twenty-chrome-extension/options.html
  packages/twenty-chrome-extension/package.json
  packages/twenty-chrome-extension/public/logo/32-32.png
  packages/twenty-chrome-extension/public/readme-images/01-img-one.png
  packages/twenty-chrome-extension/public/readme-images/02-img-two.png
  packages/twenty-chrome-extension/public/readme-images/03-img-three.png
  packages/twenty-chrome-extension/public/readme-images/04-img-four.png
  packages/twenty-chrome-extension/public/readme-images/05-img-five.png
  packages/twenty-chrome-extension/public/vite.svg
  packages/twenty-chrome-extension/src/background/index.ts
  packages/twenty-chrome-extension/src/background/utils/openOptionsPage.ts
  packages/twenty-chrome-extension/src/contentScript/createButton.ts
  packages/twenty-chrome-extension/src/contentScript/extractCompanyProfile.ts
  packages/twenty-chrome-extension/src/contentScript/extractPersonProfile.ts
  packages/twenty-chrome-extension/src/contentScript/index.ts
  packages/twenty-chrome-extension/src/contentScript/utils/extractCompanyLinkedinLink.ts
  packages/twenty-chrome-extension/src/contentScript/utils/extractDomain.ts
  packages/twenty-chrome-extension/src/contentScript/utils/extractFirstAndLastName.ts
  packages/twenty-chrome-extension/src/global.d.ts
  packages/twenty-chrome-extension/src/index.css
  packages/twenty-chrome-extension/src/manifest.ts
  packages/twenty-chrome-extension/src/options/Options.tsx
  packages/twenty-chrome-extension/src/options/index.tsx
  packages/twenty-chrome-extension/src/options/modules/api-key/components/ApiKeyForm.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/display/typography/components/H2Title.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/input/button/Button.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/input/components/TextInput.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/input/components/Toggle.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/theme/assets/dark-noise.jpg
  packages/twenty-chrome-extension/src/options/modules/ui/theme/assets/light-noise.png
  packages/twenty-chrome-extension/src/options/modules/ui/theme/components/AppThemeProvider.tsx
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/accent.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/animation.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/background.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/blur.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/border.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/boxShadow.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/colors.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/effects.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/font.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/icon.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/modal.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/tag.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/text.ts
  packages/twenty-chrome-extension/src/options/modules/ui/theme/constants/theme.ts
  packages/twenty-chrome-extension/src/utils/handleQueryParams.ts
  packages/twenty-chrome-extension/src/utils/requestDb.ts
  packages/twenty-chrome-extension/src/vite-env.d.ts
  packages/twenty-chrome-extension/tsconfig.json
  packages/twenty-chrome-extension/tsconfig.node.json
  packages/twenty-chrome-extension/vite.config.ts
  yarn.lock
Labels: PR: awaiting review

#3916 fix: workspace health
  packages/twenty-server/src/workspace/workspace-health/commands/workspace-health.command.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-default-value.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-nullable.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/workspace-fix-type.service.ts
Labels: PR: awaiting author

#3913 feat: health check enum
  packages/twenty-server/src/metadata/field-metadata/utils/is-enum-field-metadata-type.util.ts
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/field-metadata-health.service.ts
Labels: PR: awaiting review

#3917 BUG FIX: Create workspace member if inviteHash exists
  packages/twenty-server/src/core/auth/services/auth.service.ts
Labels: type: bug

#3909 Added Single Command for Frontend + Backend
  package.json
  yarn.lock
Labels: PR: awaiting author

#3906 Added the dark mode version of empty states
  packages/twenty-front/public/images/placeholders/background/no_match_record_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/404_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/500_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/empty_inbox_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/empty_timeline_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/error_index_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/no_file_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/no_match_record_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/no_note_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/no_record_bg.png
  packages/twenty-front/public/images/placeholders/dark-background/no_task_bg.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/404.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/500.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/empty_inbox.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/empty_timeline.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/error_index.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/no_file.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/no_match_record.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/no_note.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/no_record.png
  packages/twenty-front/public/images/placeholders/dark-moving-image/no_task.png
  packages/twenty-front/public/images/placeholders/moving-image/no_match_record.png
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/AnimatedPlaceholder.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/constants/AnimatedImages.ts
Labels: PR: awaiting review

#3888 3807 auto creation of contact when importing emails
  packages/twenty-server/src/workspace/messaging/create-company/create-company.module.ts
  packages/twenty-server/src/workspace/messaging/create-company/create-company.service.ts
  packages/twenty-server/src/workspace/messaging/create-contact/create-contact.module.ts
  packages/twenty-server/src/workspace/messaging/create-contact/create-contact.service.ts
  packages/twenty-server/src/workspace/messaging/message-participant/message-participant.module.ts
  packages/twenty-server/src/workspace/messaging/message-participant/message-participant.service.ts
  packages/twenty-server/src/workspace/messaging/message-thread/message-thread.module.ts
  packages/twenty-server/src/workspace/messaging/message-thread/message-thread.service.ts
  packages/twenty-server/src/workspace/messaging/message/message.module.ts
  packages/twenty-server/src/workspace/messaging/message/message.service.ts
  packages/twenty-server/src/workspace/messaging/messaging.module.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-messages-by-batches.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-full-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/is-person-email.service.ts
  packages/twenty-server/src/workspace/messaging/services/messaging-utils.service.ts
  packages/twenty-server/src/workspace/messaging/services/utils/create-queries-from-message-ids.service.ts
Labels: PR: awaiting author

#3892 Disable buffered logs
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-server/.env.example
  packages/twenty-server/src/command.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/main.ts
  packages/twenty-server/src/queue-worker.ts
Labels: PR: awaiting author

#3944 feat: sync metadata can alter and update a field
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/storage/workspace-sync.storage.ts
Labels: PR: awaiting review

#3654 POC: generate twenty-server package.json with Nx
  nx.json
  package.json
  packages/twenty-docker/prod/twenty-server/Dockerfile
  packages/twenty-emails/package.json
  packages/twenty-server/package.json
  packages/twenty-server/project.json
  yarn.lock
Labels: PR: awaiting review

#3787 Zapier add description to labels
  packages/twenty-zapier/src/creates/crud_record.ts
  packages/twenty-zapier/src/test/utils/computeInputFields.test.ts
  packages/twenty-zapier/src/test/utils/labelize.test.ts
  packages/twenty-zapier/src/triggers/find_object_names_singular.ts
  packages/twenty-zapier/src/triggers/trigger_record.ts
  packages/twenty-zapier/src/utils/computeInputFields.ts
  packages/twenty-zapier/src/utils/creates/creates.utils.ts
  packages/twenty-zapier/src/utils/data.types.ts
  packages/twenty-zapier/src/utils/labelling.ts
  packages/twenty-zapier/src/utils/requestDb.ts
  packages/twenty-zapier/src/utils/triggers/triggers.utils.ts
Labels: PR: awaiting review

#3870 3865-Add-Integrations
  packages/twenty-front/public/images/integrations/Cal.png
  packages/twenty-front/public/images/integrations/Github.png
  packages/twenty-front/public/images/integrations/MailChimp.png
  packages/twenty-front/public/images/integrations/Slack.png
  packages/twenty-front/public/images/integrations/Tally.png
  packages/twenty-front/public/images/integrations/Twenty.svg
  packages/twenty-front/public/images/integrations/Windmill.png
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationComponent.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationGroup.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrations.tsx
  packages/twenty-front/src/pages/settings/integrations/constants/IntegrationTypes.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Integrations.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Request.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Windmill.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Zapier.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
Labels: PR: awaiting review

#3927 3814 create blocklist data model
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/blocklist.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/workspace-member.object-metadata.ts
Labels: PR: awaiting review

#3962 3889 activate settingsaccountsemailsinboxsettings
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsContactAutoCreationSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsVisibilitySection.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
  packages/twenty-server/src/core/auth/services/google-gmail.service.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/workspace/messaging/jobs/create-companies-and-contacts-after-sync.job.ts
  packages/twenty-server/src/workspace/messaging/listeners/is-contact-auto-creation-enabled-listener.ts
  packages/twenty-server/src/workspace/messaging/messaging.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/company/company.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/company/company.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-channel/message-channel.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-participant/message-participant.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/message-participant/message-participant.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/message/message.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/message/message.service.ts
  packages/twenty-server/src/workspace/messaging/repositories/person/person.module.ts
  packages/twenty-server/src/workspace/messaging/repositories/person/person.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-companies-and-contacts/create-companies-and-contacts.module.ts
  packages/twenty-server/src/workspace/messaging/services/create-companies-and-contacts/create-companies-and-contacts.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-company/create-company.module.ts
  packages/twenty-server/src/workspace/messaging/services/create-company/create-company.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-contact/create-contact.module.ts
  packages/twenty-server/src/workspace/messaging/services/create-contact/create-contact.service.ts
  packages/twenty-server/src/workspace/messaging/types/gmail-message.ts
  packages/twenty-server/src/workspace/messaging/utils/get-domain-name-from-handle.util.ts
  packages/twenty-server/src/workspace/messaging/utils/get-first-name-and-last-name-from-handle-and-display-name.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel.object-metadata.ts
Labels: PR: awaiting review

#3975 3129 show page relation field add delete menu item
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardContent.tsx
Labels: PR: awaiting review

#3930 3815 blocklist connect frontend
  packages/twenty-front/src/modules/accounts/types/BlockedEmail.ts
  packages/twenty-front/src/modules/accounts/types/BlocklistItem.ts
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistInput.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistTable.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistTableRow.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/blocklist.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/connected-account.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel-message-association.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-participant.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-thread.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/person.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/workspace-member.object-metadata.ts
Labels: PR: awaiting review

#3991 feat: add default value for some type of fields
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
Labels: PR: awaiting review

#3996 Fix update on delete record
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
Labels: PR: awaiting review

#4003 Integrations: design fixes and remove feature flag
  packages/twenty-front/public/images/integrations/Github.png
  packages/twenty-front/public/images/integrations/cal-logo.png
  packages/twenty-front/public/images/integrations/github-logo.png
  packages/twenty-front/public/images/integrations/mailchimp-logo.png
  packages/twenty-front/public/images/integrations/slack-logo.png
  packages/twenty-front/public/images/integrations/tally-logo.png
  packages/twenty-front/public/images/integrations/twenty-logo.svg
  packages/twenty-front/public/images/integrations/windmill-logo.png
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationComponent.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationGroup.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrations.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrations.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/constants/IntegrationTypes.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Integrations.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Request.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationCategories.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationRequest.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationWindmill.ts
  packages/twenty-front/src/pages/settings/integrations/constants/SettingsIntegrationZapier.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Windmill.ts
  packages/twenty-front/src/pages/settings/integrations/constants/Zapier.ts
  packages/twenty-front/src/pages/settings/integrations/types/SettingsIntegration.ts
  packages/twenty-front/src/pages/settings/integrations/types/SettingsIntegrationCategory.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
Labels: PR: awaiting review

#3967 3757 update frontend to show correct view count
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useMapConnectionToRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindManyRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoard.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordConnection.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
Labels: PR: awaiting review

#4000 Uploading img assets in view of read-me visual update
  packages/twenty-docs/static/img/api-dark.png
  packages/twenty-docs/static/img/api-light.png
  packages/twenty-docs/static/img/data-dark.png
  packages/twenty-docs/static/img/data-light.png
  packages/twenty-docs/static/img/emails-dark.png
  packages/twenty-docs/static/img/emails-light.png
  packages/twenty-docs/static/img/index-dark.png
  packages/twenty-docs/static/img/index-light.png
  packages/twenty-docs/static/img/kanban-dark.png
  packages/twenty-docs/static/img/kanban-light.png
  packages/twenty-docs/static/img/keyboard-dark.png
  packages/twenty-docs/static/img/keyboard-light.png
  packages/twenty-docs/static/img/notes-dark.png
  packages/twenty-docs/static/img/notes-light.png
  packages/twenty-docs/static/img/preview-light.png
  packages/twenty-docs/static/img/tasks-dark.png
  packages/twenty-docs/static/img/tasks-light.png
Labels: PR: awaiting author

#4011 Resolve bugs tied to record creations on table
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexViewTypeState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useCloseRecordTableCell.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useCloseRecordTableCell.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPageHeader.tsx
  packages/twenty-server/src/workspace/workspace-manager/standard-objects-prefill-data/company.ts
  packages/twenty-server/src/workspace/workspace-manager/standard-objects-prefill-data/person.ts
Labels: PR: awaiting author

#3955 [Enter] key autosave for new API key and webhook
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
Labels: PR: awaiting author

#3953 fix: Fixed LinkedIn links with unicode
  packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/URLDisplay.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/SocialLink.tsx
  packages/twenty-front/src/utils/__tests__/checkUrlType.test.ts
  packages/twenty-front/src/utils/__tests__/getDisplayValueByUrlType.test.ts
  packages/twenty-front/src/utils/checkUrlType.ts
  packages/twenty-front/src/utils/getDisplayValueByUrlType.ts
Labels: PR: awaiting review

#4055 chore: make twenty-server nest command scripts depend on twenty-email…
  package.json
  packages/twenty-server/package.json
  packages/twenty-server/project.json
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/tsconfig.json
  yarn.lock
Labels: PR: awaiting review

#3912 feat: REST endpoints for metadata API
  packages/twenty-server/src/core/api-rest/api-rest-query-builder/utils/parse-path.utils.ts
  packages/twenty-server/src/core/api-rest/api-rest.module.ts
  packages/twenty-server/src/core/api-rest/metadata-rest.controller.ts
  packages/twenty-server/src/core/api-rest/metadata-rest.service.ts
Labels: PR: awaiting review

#4091 Fix delete with no result should not throw
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
Labels: PR: awaiting author

#4090 feat: create Settings/Accounts/Calendars page
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/utils/getSettingsPagePath.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawer.stories.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendars.stories.tsx
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
Labels: PR: awaiting review

#4092 feat: create Settings/Accounts/Calendars/Calendar Settings page
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/mockObjects.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendarsSettings.stories.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
Labels: PR: awaiting review

#4120 Fix developers url and remove webhook url error
  packages/twenty-front/src/App.tsx
  packages/twenty-server/src/workspace/workspace-query-runner/jobs/call-webhook.job.ts
Labels: PR: awaiting review

#4098 Added beta tag in email
  packages/twenty-front/src/modules/settings/components/SettingsNavigationCard.tsx
  packages/twenty-front/src/modules/ui/display/pill/components/Pill.tsx
  packages/twenty-front/src/modules/ui/display/pill/components/__stories__/Pill.stories.tsx
  packages/twenty-front/src/modules/ui/input/button/components/Button.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationComponent.tsx
  packages/twenty-front/tsup.ui.index.tsx
Labels: PR: awaiting author

#4104 feat: add Calendar Settings section to Settings/Accounts/Calendars page
  packages/twenty-front/src/modules/object-metadata/types/CoreObjectNameSingular.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarSettingsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsSyncSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListSkeletonCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsNewAccountSection.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
Labels: PR: awaiting review

#4096 45 create billing core tables
  package.json
  packages/twenty-server/src/core/billing/billing.module.ts
  packages/twenty-server/src/core/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/core/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/core/core.module.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/core/workspace/workspace.entity.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1708535112230-addBillingCoreTables.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  yarn.lock
Labels: PR: awaiting author

#4035 Add confirmation modal when deleting/ regenerating api keys, deleting webhook
  packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
Labels: PR: awaiting author

#4106 Refactor/finish activities optimistic
  packages/twenty-front/src/modules/activities/comment/__stories__/CommentHeader.stories.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityConnectionUtils.test.tsx
  packages/twenty-front/src/modules/activities/hooks/useActivities.ts
  packages/twenty-front/src/modules/activities/hooks/useActivityById.ts
  packages/twenty-front/src/modules/activities/hooks/useActivityConnectionUtils.ts
  packages/twenty-front/src/modules/activities/hooks/useCreateActivityInDB.ts
  packages/twenty-front/src/modules/activities/hooks/useDeleteActivityFromCache.ts
  packages/twenty-front/src/modules/activities/hooks/useInjectIntoActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/hooks/useInjectIntoActivitiesQuery.ts
  packages/twenty-front/src/modules/activities/hooks/useInjectIntoActivityTargetsQueries.ts
  packages/twenty-front/src/modules/activities/hooks/useRemoveFromActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/hooks/useRemoveFromActivityTargetsQueries.ts
  packages/twenty-front/src/modules/activities/hooks/useUpsertActivity.ts
  packages/twenty-front/src/modules/activities/notes/hooks/useNotes.ts
  packages/twenty-front/src/modules/activities/notes/states/currentNotesQueryVariablesState.ts
  packages/twenty-front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
  packages/twenty-front/src/modules/activities/right-drawer/components/__stories__/RightDrawerActivityTopBar.stories.tsx
  packages/twenty-front/src/modules/activities/tasks/hooks/useTasks.ts
  packages/twenty-front/src/modules/activities/tasks/states/currentCompletedTaskQueryVariablesState.ts
  packages/twenty-front/src/modules/activities/tasks/states/currentIncompleteTaskQueryVariablesState.ts
  packages/twenty-front/src/modules/activities/timeline/components/Timeline.tsx
  packages/twenty-front/src/modules/activities/timeline/hooks/useInjectIntoTimelineActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/timeline/hooks/useRemoveFromTimelineActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/timeline/hooks/useTimelineActivities.ts
  packages/twenty-front/src/modules/activities/timeline/states/objectShowPageTargetableObjectState.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
Labels: PR: awaiting author

#4097 feat: allow backend to rename field of custom object
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldFormSection.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
Labels: PR: awaiting author

#4100 Add onDeleteAction to RelationMetadata
  packages/twenty-server/src/database/typeorm/metadata/migrations/1708449210922-addOnDeleteActionToRelationMetadata.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/relation-metadata.entity.ts
  packages/twenty-server/src/metadata/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-issue.interface.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-table-definition.interface.ts
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/relation-metadata.health.service.ts
  packages/twenty-server/src/workspace/workspace-migration-builder/factories/workspace-migration-relation.factory.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-relation.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-relation.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/decorators/relation-metadata.decorator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/standard-relation.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/comparator.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/partial-relation-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/reflect-relation-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-relation-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/storage/workspace-sync.storage.ts
Labels: PR: awaiting review

#4131 3933 filter non work email from auto contact creation
  packages/twenty-server/src/workspace/messaging/repositories/person/person.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-companies-and-contacts/create-companies-and-contacts.service.ts
  packages/twenty-server/src/workspace/messaging/services/create-contact/create-contact.service.ts
  packages/twenty-server/src/workspace/messaging/utils/get-unique-participants-and-handles.util.ts
Labels: PR: awaiting review

#4132 feat: add Contact Auto-Creation calendar settings
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsContactAutoCreationSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSynchronizationSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsToggleSettingCard.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
Labels: PR: awaiting review

#4138 feat: add Event Visibility calendar settings
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarVisibilitySettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsVisibilitySection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxVisibilitySettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRadioSettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsToggleSettingCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsVisibilitySettingCardMedia.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
Labels: PR: awaiting review

#4133 46 add stripe product endpoint
  packages/twenty-server/src/core/billing/billing.module.ts
  packages/twenty-server/src/core/billing/billing.service.ts
  packages/twenty-server/src/core/billing/controllers/product-price.controller.ts
  packages/twenty-server/src/core/billing/stripe/stripe.module.ts
  packages/twenty-server/src/core/billing/stripe/stripe.service.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
Labels: PR: awaiting author

#4137 Handle relations between same objects
  packages/twenty-server/src/workspace/utils/__tests__/deduce-relation-direction.spec.ts
  packages/twenty-server/src/workspace/utils/deduce-relation-direction.util.ts
  packages/twenty-server/src/workspace/workspace-health/services/relation-metadata.health.service.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/relation-field-alias.factory.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/factories/extend-object-type-definition.factory.ts
Labels: PR: awaiting review

#4140 4020 timebox improve performances on messages read
  packages/twenty-server/src/core/messaging/timeline-messaging.module.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.service.ts
Labels: PR: awaiting review

#4168 Remove usage of toSorted as it is not fully supported
  packages/twenty-front/src/modules/activities/hooks/useActivities.ts
  packages/twenty-front/src/modules/activities/hooks/useInjectIntoActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/hooks/useRemoveFromActivitiesQueries.ts
  packages/twenty-front/src/modules/activities/timeline/components/TimelineQueryEffect.tsx
  packages/twenty-front/src/modules/activities/timeline/hooks/useTimelineActivities.ts
  packages/twenty-front/src/modules/activities/timeline/utils/makeTimelineActivitiesQueryVariables.ts
Labels: run-chromatic

#4146 Website: markdown to release
  packages/twenty-website/src/app/_components/releases/Line.tsx
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/_components/releases/StyledTitle.tsx
  packages/twenty-website/src/app/get-releases.tsx
  packages/twenty-website/src/app/releases/page.tsx
  packages/twenty-website/src/content/releases/CompactView.mdx
  packages/twenty-website/src/content/releases/Inbox.mdx
Labels: PR: awaiting review

#4142 Build cron for data seed demo
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/data-seed-demo-workspace-cron-pattern.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/data-seed-demo-workspace.cron.command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/data-seed-demo-workspace-command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/data-seed-demo-workspace.module.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/jobs/data-seed-demo-workspace.job.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/services/data-seed-demo-workspace.service.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
Labels: PR: awaiting review

#3957 fix: forbid creation of objects or fields with certain characters or with forbidden keywords that clashes with pg_graphql
  packages/twenty-server/src/metadata/decorators/is-valid-name.decorator.ts
  packages/twenty-server/src/metadata/field-metadata/dtos/field-metadata.dto.ts
  packages/twenty-server/src/metadata/object-metadata/dtos/create-object.input.ts
  packages/twenty-server/src/metadata/object-metadata/dtos/update-object.input.ts
Labels: PR: awaiting author

#4141 feat: add Color calendar setting
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsColorSettingCard.tsx
  packages/twenty-front/src/modules/ui/display/color/components/ColorSample.tsx
  packages/twenty-front/src/modules/ui/input/button/components/ColorPickerButton.tsx
  packages/twenty-front/src/modules/ui/input/button/components/__stories__/ColorPickerButton.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
Labels: PR: awaiting author

#4147 47 add stripe checkout endpoint
  packages/twenty-server/src/core/billing/billing.controller.ts
  packages/twenty-server/src/core/billing/billing.module.ts
  packages/twenty-server/src/core/billing/billing.service.ts
  packages/twenty-server/src/core/billing/controllers/product-price.controller.ts
Labels: PR: wip, PR: awaiting author

#4038 feat: find duplicate objects init
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindDuplicateRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSectionHeader.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDuplicatesFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  packages/twenty-front/src/utils/array/__tests__/arrayToCunks.test.ts
  packages/twenty-front/src/utils/array/__tests__/moveArrayItem.test.ts
  packages/twenty-front/src/utils/array/arrayToChunks.ts
  packages/twenty-server/src/workspace/utils/get-resolver-name.util.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/__tests__/find-duplicates-query.factory.spec.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/factories.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/find-duplicates-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/interfaces/record.interface.ts
  packages/twenty-server/src/workspace/workspace-query-builder/utils-test/workspace-query-builder-options.ts
  packages/twenty-server/src/workspace/workspace-query-builder/workspace-query-builder.factory.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-pre-query-hook/types/workspace-query-hook.type.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/constants/duplicate-criteria.constants.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/factories.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/find-duplicates-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/workspace-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/factories/root-type.factory.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/utils/get-resolver-args.util.ts
Labels: PR: awaiting author

#4169 MQ Facepaint introduced
  package.json
  packages/twenty-website/src/app/_components/client-utils/useDeviceType.ts
  packages/twenty-website/src/app/_components/ui/layout/Breadcrumbs.tsx
  packages/twenty-website/src/app/_components/ui/theme/mq.ts
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMain.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebar.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideTableContents.tsx
  packages/twenty-website/src/app/layout.css
  packages/twenty-website/src/app/user-guide/layout.tsx
  yarn.lock
Labels: PR: awaiting review

#4144 feat: validate webhook URL
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
Labels: PR: awaiting author

#4036 feat: user can have multiple workspaces (backend)
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-server/src/core/auth/auth.module.ts
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/auth/services/auth.service.spec.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.module.ts
  packages/twenty-server/src/core/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/core/user/services/user.service.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1707778127558-addUserWorkspaces.ts
Labels: PR: awaiting review

#3965 3961-Notes-Relation-Field
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
Labels: PR: awaiting author

#3990 fix: prevent scroll to softfocus cell when hover
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/isSoftFocusUsingMouseState.ts
Labels: PR: awaiting author

#4032 Removed the boxes around fields on shows and side panel
  packages/twenty-front/src/modules/activities/components/ActivityEditor.tsx
  packages/twenty-front/src/modules/activities/components/ActivityEditorFields.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/property-box/components/PropertyBox.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSectionHeader.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
Labels: PR: awaiting review

#3919 fix: set a specifc date to date field input on the story
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-store/states/selectors/recordStoreFamilySelector.ts
Labels: run-chromatic, PR: awaiting review

#3907 Feat currency type optimistic cache
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingCurrencyFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingCurrencyFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
Labels: PR: awaiting review

#4185 4026 create storybook tests for blocklist components
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsEmailsBlocklistInput.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsEmailsBlocklistSection.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsEmailsBlocklistTable.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsEmailsBlocklistTableRow.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/mockedBlocklist.ts
Labels: run-chromatic, PR: awaiting review

#4191 Fixed favicon requests for empty domain names
  packages/twenty-front/src/utils/__tests__/utils.test.ts
  packages/twenty-front/src/utils/index.ts
Labels: PR: awaiting author

#4198 fix: Extend regex in Linkedin Field to support LinkedIn school URL
  packages/twenty-front/src/utils/getDisplayValueByUrlType.ts
Labels: PR: awaiting review

#4218 [messaging] fix empty history
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
Labels: type: bug

#4239 Fix nullable being set to null for text field
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/metadata/field-metadata/utils/__tests__/generate-nullable.spec.ts
  packages/twenty-server/src/metadata/field-metadata/utils/generate-nullable.ts
Labels: PR: awaiting review

#4229 Remove html from messages
  packages/twenty-server/src/workspace/messaging/repositories/message/message.service.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-messages-by-batches.service.ts
  packages/twenty-server/src/workspace/messaging/types/gmail-message.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message.object-metadata.ts
Labels: PR: awaiting review

#4241 feat: apply RecordDetailSection style on RecordDuplicatesSection and …
  packages/twenty-front/src/__stories__/App.stories.tsx
  packages/twenty-front/src/modules/activities/tasks/__stories__/TaskList.stories.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindDuplicateRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/ChipFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/EmailFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailDuplicatesSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRecordsList.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsList.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListEmptyState.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDuplicatesFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/__stories__/RecordDetailDuplicatesSection.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/__stories__/RecordDetailRelationSection.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/action-bar/components/__stories__/ActionBar.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/context-menu/components/__stories__/ContextMenu.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawerItem.stories.tsx
  packages/twenty-front/src/testing/decorators/MemoryRouterDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/companies.ts
Labels: PR: awaiting review

#4216 feat: add Object Edit Settings section with Object preview
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelPreviewFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldTypeSelectSection.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldMetadataTypes.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldTypeSelect.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreviewCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelSetFieldValueEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelSetRecordEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/__stories__/SettingsDataModelFieldPreviewCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/__tests__/useFieldPreview.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/hooks/__tests__/useFieldPreview.test.tsx
  packages/twenty-front/src/modules/settings/data-model/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/hooks/useRelationFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectAboutSection.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelIsCustomTag.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsDataModelObjectSummary.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldDefaultPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldPreviewValueFromRecord.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldPreviewValueFromRecord.ts
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/layout/card/components/Card.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/testing/decorators/ObjectMetadataItemsDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/testing/mock-data/workspace-members.ts
Labels: PR: awaiting author

#4242 feat: adjust navigation drawer design
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawer.stories.tsx
Labels: PR: awaiting review

#4034 Add export as csv
  package.json
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useExportTableData.test.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useExportTableData.ts
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  yarn.lock
Labels: PR: awaiting author, ⚔️ Quest

#4243 Enable new record board and messaging for all workspaces except demo
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-server/src/core/auth/controllers/google-gmail-auth.controller.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/feature-flags.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/index.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/workspace/messaging/commands/crons/fetch-all-workspaces-messages.job.ts
  packages/twenty-server/src/workspace/messaging/commands/gmail-full-sync.command.ts
  packages/twenty-server/src/workspace/messaging/commands/gmail-partial-sync.command.ts
  packages/twenty-server/src/workspace/messaging/listeners/messaging-person.listener.ts
  packages/twenty-server/src/workspace/messaging/listeners/messaging-workspace-member.listener.ts
  packages/twenty-server/src/workspace/workspace-cleaner/crons/clean-inactive-workspace.job.ts
Labels: PR: awaiting review
