Repository twentyhq/twenty, pull requests merged in 2024-05, with the labels that each got.

#5205 Smart changelog
  packages/twenty-website/src/app/_components/releases/Release.tsx
  packages/twenty-website/src/app/api/releases/route.tsx
  packages/twenty-website/src/app/releases/api/route.tsx
  packages/twenty-website/src/app/releases/page.tsx
  packages/twenty-website/src/app/releases/utils/get-formatted-release-number.ts
  packages/twenty-website/src/app/releases/utils/get-github-release-date-from-release-note.ts
  packages/twenty-website/src/app/releases/utils/get-releases.tsx
  packages/twenty-website/src/app/releases/utils/get-visible-releases.ts
  packages/twenty-website/src/database/database.ts
  packages/twenty-website/src/database/init-database.ts
  packages/twenty-website/src/database/migrations/0002_demonic_matthew_murdock.sql
  packages/twenty-website/src/database/migrations/meta/_journal.json
  packages/twenty-website/src/database/model.ts
  packages/twenty-website/src/database/schema-postgres.ts
  packages/twenty-website/src/github-sync/contributors/types.tsx
  packages/twenty-website/src/github-sync/fetch-and-save-github-data.ts
  packages/twenty-website/src/github-sync/github-releases/fetch-and-save-github-releases.tsx
Labels: PR: awaiting review, website

#5207 Modifications user guide
  packages/twenty-website/src/app/_components/contributors/Header.tsx
  packages/twenty-website/src/app/_components/oss-friends/Header.tsx
  packages/twenty-website/src/app/_components/releases/StyledTitle.tsx
  packages/twenty-website/src/app/_components/ui/layout/FooterDesktop.tsx
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleEditContent.tsx
  packages/twenty-website/src/app/_components/user-guide/TableContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideCard.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMain.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMainLayout.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebar.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebarSection.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideTableContents.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideTocComponent.tsx
  packages/twenty-website/src/app/_server-utils/get-posts.tsx
  packages/twenty-website/src/app/user-guide/hooks/useHeadsObserver.tsx
  packages/twenty-website/src/app/user-guide/layout.tsx
  packages/twenty-website/src/app/user-guide/page.tsx
  packages/twenty-website/src/content/user-guide/constants/UserGuideHomeCards.ts
  packages/twenty-website/src/content/user-guide/constants/UserGuideIndex.ts
  packages/twenty-website/src/content/user-guide/constants/getUserGuideArticles.tsx
  packages/twenty-website/src/content/user-guide/constants/groupArticlesByTopic.tsx
Labels: PR: awaiting review, website

#5230 Rename types for UserMappingOptions
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneRelationMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/parseFieldRelationType.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationEditDatabaseConnectionContent.tsx
  packages/twenty-front/src/testing/mock-data/remote-servers.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/foreign-data-wrapper-query.factory.ts
  packages/twenty-server/src/engine/integrations/exception-handler/drivers/console.driver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/create-remote-server.input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/remote-server.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/update-remote-server.input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/user-mapping-dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/build-update-remote-server-raw-query.utils.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/user-mapping-options.utils.ts
Labels: PR: awaiting author

#5176 feat: add Links field type
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/LinksFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useLinksField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinkValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinks.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinksValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeLinkRecordInput.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/utils/url/__tests__/getUrlHostName.test.ts
  packages/twenty-front/src/utils/url/getUrlHostName.ts
  packages/twenty-front/src/utils/validation-schemas/__tests__/absoluteUrlSchema.test.ts
  packages/twenty-front/src/utils/validation-schemas/absoluteUrlSchema.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/composite-input-type-definition.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/composite-object-type-definition.factory.ts
  packages/twenty-server/src/engine/api/rest/api-rest-query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/index.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/links.composite-type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/composite-type.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-default-value.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/generate-default-value.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/is-composite-field-metadata-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-default-value-for-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/composite-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
Labels: PR: awaiting review

#5212 feat: update links field
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinksValue.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/index.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/json.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/raw-json.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/links.composite-type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/default-value.input.ts
Labels: PR: awaiting review

#5245 User workspace middleware throws 401 if token is invalid
  packages/twenty-server/src/engine/middlewares/user-workspace.middleware.ts
Labels: PR: awaiting review

#5235 fix: fix storybook build script not found by Chromatic
  .github/workflows/actions/task-cache/action.yaml
  .github/workflows/ci-chromatic.yaml
  .github/workflows/ci-front.yaml
  .gitignore
  nx.json
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/hooks/usePrepareFindManyActivitiesQuery.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/PhoneFieldDisplay.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhoneFieldInput.stories.tsx
  packages/twenty-front/src/modules/ui/input/button/components/FloatingIconButton.tsx
Labels: PR: wip, PR: awaiting author

#5246 Build stripe integration on backend side
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/databases/graphql/fragments/databaseConnectionFragment.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionForm.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/utils/editDatabaseConnection.ts
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-front/src/testing/mock-data/remote-servers.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/factories.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/foreign-data-wrapper-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/foreign-data-wrapper-server-query.factory.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/create-remote-server.input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/update-remote-server.input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/dtos/user-mapping-dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/util/stripe-distant-tables.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/remote-table.dto.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/udt-name-mapper.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/types/user-mapping-options.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/build-update-remote-server-raw-query.utils.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/validate-remote-server-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
Labels: PR: awaiting author

#5255 Fix token validation on graphql IntrospectionQuery
  packages/twenty-server/src/engine/middlewares/user-workspace.middleware.ts
Labels: PR: awaiting review

#5256 fix: fix storybook coverage task
  .github/workflows/actions/task-cache/action.yaml
  .github/workflows/ci-front.yaml
  nx.json
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useExportTableData.test.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useExportTableData.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionShowContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionSummaryCard.tsx
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-ui/project.json
Labels: PR: awaiting author

#5151 4900 multi select field front implement expanded cells
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventParticipantsResponseStatusField.tsx
  packages/twenty-front/src/modules/activities/components/ActivityEditorFields.tsx
  packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
  packages/twenty-front/src/modules/activities/components/ParticipantChip.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/activities/notes/components/NoteCard.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventsGroup.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResetPassword.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useNavigateAfterSignInUp.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInWithMicrosoft.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useWorkspaceFromInviteHash.ts
  packages/twenty-front/src/modules/billing/components/SubscriptionCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useGetButtonIcon.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/MultiSelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useMultiSelectField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/AnimatedContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-front/src/modules/ui/display/expandable-list/ExpandableList.tsx
  packages/twenty-front/src/modules/ui/display/expandable-list/IntersectionObserverWrapper.tsx
  packages/twenty-front/src/modules/ui/display/info/components/Info.tsx
  packages/twenty-front/src/modules/ui/input/components/CardPicker.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/ChildrenContainer.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/ExpandableList.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/__stories__/ExpandableList.stories.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/__tests__/getChildProperties.test.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/__tests__/getChipContentWidth.test.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/getChildProperties.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/getChipContentWidth.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/states/isRightDrawerAnimationCompleted.ts
  packages/twenty-front/src/modules/ui/navigation/link/components/GithubVersionLink.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/__stories__/ActionLink.stories.tsx
  packages/twenty-front/src/pages/auth/ChooseYourPlan.tsx
  packages/twenty-front/src/pages/auth/CreateWorkspace.tsx
  packages/twenty-front/src/pages/auth/PaymentSuccess.tsx
  packages/twenty-front/tsconfig.json
  packages/twenty-front/tsup.ui.index.tsx
  packages/twenty-ui/src/display/chip/components/Chip.tsx
Labels: PR: awaiting author

#5251 Added OG Image
  packages/twenty-website/.env.example
  packages/twenty-website/src/app/_components/contributors/ProfileSharing.tsx
  packages/twenty-website/src/app/api/contributors/og-image/[slug]/route.tsx
  packages/twenty-website/src/app/api/contributors/og-image/[slug]/style.ts
  packages/twenty-website/src/app/contributors/[slug]/page.tsx
  packages/twenty-website/src/app/contributors/utils/get-contributor-activity.ts
Labels: PR: awaiting review, website

#5287 Create convert record positions to integers command
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/convert-record-positions-to-integers.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/workspace-sync-metadata-commands.module.ts
Labels: PR: awaiting review

#5284 fix: fix storybook:build memory allocation error in CI
  .eslintrc.react.cjs
  .github/workflows/ci-front.yaml
  package.json
  packages/twenty-front/src/modules/activities/hooks/__tests__/useCreateActivityInDB.test.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/utils/editDatabaseConnection.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/uniqueEntries.ts
  packages/twenty-server/.eslintrc.cjs
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/messaging/query-hooks/message/message-find-many.pre-query.hook.ts
  packages/twenty-ui/.eslintrc.cjs
  yarn.lock
Labels: PR: wip, PR: awaiting author

#5217 chore: add nx/project.json to twenty-chrome-extension
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  package.json
  packages/twenty-chrome-extension/.eslintrc.cjs
  packages/twenty-chrome-extension/.prettierignore
  packages/twenty-chrome-extension/package.json
  packages/twenty-chrome-extension/project.json
  packages/twenty-chrome-extension/tsconfig.app.json
  packages/twenty-chrome-extension/tsconfig.json
  packages/twenty-chrome-extension/tsconfig.spec.json
  packages/twenty-chrome-extension/vite.config.ts
  yarn.lock
Labels: PR: awaiting review

#5303 [flexible-schema] Add reserved keyword check on object creation
  packages/twenty-server/src/engine/metadata-modules/object-metadata/hooks/before-create-one-object.hook.ts
Labels: PR: awaiting review

#5238 feat: extend twenty orm
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/inject-workspace-datasource.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/inject-workspace-repository.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/entity.manager.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/index.ts
  packages/twenty-server/src/engine/twenty-orm/factories/scoped-workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/engine/twenty-orm/storage/data-source.storage.ts
  packages/twenty-server/src/engine/twenty-orm/storage/object-literal.storage.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm-core.module.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.manager.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.providers.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.service.ts
Labels: PR: awaiting review

#5051 Feat/migrate password reset token to app token table
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/project.json
  packages/twenty-server/src/engine/core-modules/app-token/app-token.entity.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
Labels: PR: awaiting review

#5299 fix: fix Chromatic script memory allocation in CI
  .github/workflows/ci-front.yaml
Labels: run-chromatic, PR: awaiting review

#5301 Fix github stars endpoint
  packages/twenty-website/src/app/api/github-stars/route.tsx
  packages/twenty-website/src/middleware.ts
  packages/twenty-website/src/shared-utils/formatNumberOfStars.ts
Labels: PR: awaiting review, Website

#5315 Fix convertRecordPositionsToIntegers command for camelCase tables
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/convert-record-positions-to-integers.command.ts
Labels: PR: awaiting review

#4916 refactor: use react-hook-form to validate Settings/DataModel/Field
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneRelationMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatRelationMetadataInput.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/objectMetadataItemSchema.test.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/metadataLabelSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldFormSection.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldFormSection.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldAboutForm.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
Labels: PR: awaiting review

#5014 Add unit tests on object record mutation and query hooks
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecordsMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateOneRecordMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecordsMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecordMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useExecuteQuickActionOnOneRecordMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindDuplicateRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindDuplicateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindOneRecordQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyFindOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useUpdateOneRecordMutation.test.tsx
Labels: PR: awaiting review

#5318 Split job modules
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/call-webhook-jobs.job.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/jobs/workspace-query-runner-job.module.ts
  packages/twenty-server/src/engine/integrations/message-queue/drivers/sync.driver.ts
  packages/twenty-server/src/engine/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/jobs/calendar-messaging-participant-job.module.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/jobs/match-participant.job.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/jobs/unmatch-participant.job.ts
  packages/twenty-server/src/modules/calendar/crons/jobs/calendar-cron-job.module.ts
  packages/twenty-server/src/modules/calendar/crons/jobs/google-calendar-sync.cron.job.ts
  packages/twenty-server/src/modules/calendar/jobs/calendar-job.module.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/jobs/auto-companies-and-contacts-creation-job.module.ts
  packages/twenty-server/src/modules/messaging/crons/jobs/messaging-cron-job.module.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-full-sync.job.ts
  packages/twenty-server/src/modules/messaging/jobs/gmail-partial-sync.job.ts
  packages/twenty-server/src/modules/messaging/jobs/messaging-job.module.ts
  packages/twenty-server/src/modules/timeline/jobs/timeline-job.module.ts
  packages/twenty-server/src/queue-worker/queue-worker.ts
Labels: PR: awaiting review

#5223 feat: add links to Links field
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useGetButtonIcon.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinkFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/RoundedLink.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-front/src/utils/url/getAbsoluteUrl.ts
  packages/twenty-front/src/utils/url/getUrlHostName.ts
Labels: PR: awaiting review

#5316 [fix] Increment cache version after object/field/relation update
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useUpdateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/__tests__/settingsUpdateObjectInputSchema.test.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsUpdateObjectInputSchema.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/update-object.input.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/hooks/before-update-one-object.hook.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/dtos/delete-relation.input.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.service.ts
Labels: PR: wip, PR: awaiting author

#5322 Fix 400 yoga errors being sent to exception handlers
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/integrations/exception-handler/hooks/use-exception-handler.hook.ts
Labels: PR: awaiting review

#5323 Fix query runner throwing 500 when pg_graphql detects unique constraint
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/compute-pg-graphql-error.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
Labels: PR: awaiting review

#5319 fix: fix storybook pages tests coverage
  .github/workflows/ci-front.yaml
  nx.json
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldActiveActionDropdown.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectSummaryCard.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordIndexPage.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
Labels: run-chromatic, PR: awaiting author

#5326 refactor: use react-hook-form for Field type config forms
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFieldMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useGetRelationMetadata.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/formatFieldMetadataItemInput.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/validateMetadataLabel.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatRelationMetadataInput.ts
  packages/twenty-front/src/modules/object-metadata/utils/getDefaultValueForBackend.ts
  packages/twenty-front/src/modules/object-metadata/utils/validateMetadataLabel.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/MultiSelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/SelectFieldDisplay.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelDefaultValue.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldCurrencyForm.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldTypeSelect.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useFieldMetadataForm.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldDefaultPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldPreviewValueFromRecord.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldPreviewValueFromRecord.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#5336 fix: fix storybook:build cache output path
  .github/workflows/actions/task-cache/action.yaml
  nx.json
Labels: PR: awaiting review

#5339 fix: fix several field bugs
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordFromRecordNode.ts
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useGetButtonIcon.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/JsonFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useJsonField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/usePhoneField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldDisplayedAsPhone.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRawJsonValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/computeDraftValueFromFieldValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/computeEmptyDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueJson.ts
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelDefaultValue.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/__stories__/SettingsDataModelFieldSettingsFormCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useRelationSettingsFormInitialValues.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#5352 Disable save button while submitting form in settings
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#5350 fix: fix field select options positions after option removal
  packages/twenty-front/src/modules/settings/data-model/components/SettingsObjectFieldSelectForm.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useClickOutsideListener.ts
  packages/twenty-front/src/utils/array/__tests__/toSpliced.test.ts
  packages/twenty-front/src/utils/array/moveArrayItem.ts
  packages/twenty-front/src/utils/array/toSpliced.ts
Labels: PR: awaiting review

#5345 Update README.md
  README.md
Labels: PR: awaiting author

#5317 Added GitHub init
  packages/twenty-website/package.json
  packages/twenty-website/src/github-sync/github-sync.ts
  packages/twenty-website/src/github/contributors/fetch-assignable-users.tsx
  packages/twenty-website/src/github/contributors/fetch-issues-prs.tsx
  packages/twenty-website/src/github/contributors/save-issues-to-db.tsx
  packages/twenty-website/src/github/contributors/save-prs-to-db.tsx
  packages/twenty-website/src/github/contributors/search-issues-prs.tsx
  packages/twenty-website/src/github/contributors/types.tsx
  packages/twenty-website/src/github/fetch-and-save-github-data.ts
  packages/twenty-website/src/github/github-releases/fetch-and-save-github-releases.tsx
  packages/twenty-website/src/github/github-stars/fetch-and-save-github-stars.tsx
  packages/twenty-website/src/github/github-sync.ts
Labels: PR: awaiting review, Website

#4789 4599-feat(front): Add Copy Button to Floating Inputs
  packages/twenty-front/src/modules/object-record/record-field/components/LightCopyIconButton.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhoneFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/hooks/useRegisterInputEvents.ts
  packages/twenty-front/src/modules/ui/field/input/components/FieldInputOverlay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/FieldTextAreaOverlay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/PhoneInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextInput.tsx
  packages/twenty-front/src/modules/ui/input/button/components/LightIconButton.tsx
Labels: PR: awaiting author

#5410 User guide images
  packages/twenty-website/public/images/user-guide/notes/notes_header.png
  packages/twenty-website/public/images/user-guide/tasks/tasks_header.png
  packages/twenty-website/public/images/user-guide/views/filter.png
Labels: PR: awaiting author

#5407 Added loader to Download Image + modified GitHub stars
  packages/twenty-website/src/app/_components/contributors/ProfileSharing.tsx
  packages/twenty-website/src/app/_components/contributors/Spinner.tsx
  packages/twenty-website/src/shared-utils/formatNumberOfStars.ts
Labels: PR: awaiting review, Website

#4963 Fixed left padding for switcher icon on the table checkboxes #4351
  packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx
Labels: PR: awaiting author

#5422 Fixed user guide layout
  packages/twenty-website/src/app/_components/user-guide/UserGuideCard.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideMain.tsx
Labels: PR: awaiting review, Website

#5341 Generic Profiling story to wrap any component
  .github/workflows/ci-front.yaml
  nx.json
  packages/twenty-front/.storybook/main.ts
  packages/twenty-front/.storybook/test-runner-jest.config.js
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/EllipsisDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/EllipsisDisplay.stories.tsx
  packages/twenty-front/src/testing/decorators/ProfilerDecorator.tsx
  packages/twenty-front/src/testing/profiling/components/ProfilerWrapper.tsx
  packages/twenty-front/src/testing/profiling/components/ProfilingQueueEffect.tsx
  packages/twenty-front/src/testing/profiling/components/ProfilingReporter.tsx
  packages/twenty-front/src/testing/profiling/constants/ProfilingReporterDivId.ts
  packages/twenty-front/src/testing/profiling/constants/TimeBetweenTestRunsInMs.ts
  packages/twenty-front/src/testing/profiling/states/currentProfilingRunState.ts
  packages/twenty-front/src/testing/profiling/states/profilingQueueState.ts
  packages/twenty-front/src/testing/profiling/states/profilingSessionDataPointsState.ts
  packages/twenty-front/src/testing/profiling/states/profilingSessionRunsState.ts
  packages/twenty-front/src/testing/profiling/states/profilingSessionState.ts
  packages/twenty-front/src/testing/profiling/states/profilingSessionStatusState.ts
  packages/twenty-front/src/testing/profiling/types/ProfilingDataPoint.ts
  packages/twenty-front/src/testing/profiling/types/ProfilingReportByComponent.ts
  packages/twenty-front/src/testing/profiling/types/ProfilingReportByRun.ts
  packages/twenty-front/src/testing/profiling/utils/computeProfilingReport.ts
  packages/twenty-front/src/testing/profiling/utils/computeProfilingReportByComponent.ts
  packages/twenty-front/src/testing/profiling/utils/getProfilingQueueIdentifier.ts
  packages/twenty-front/src/testing/profiling/utils/getProfilingReportFromDocument.ts
  packages/twenty-front/src/testing/profiling/utils/getProfilingStory.ts
  packages/twenty-front/src/testing/profiling/utils/getTestArray.ts
  packages/twenty-front/src/testing/profiling/utils/parseProfilingReportString.ts
Labels: PR: awaiting author

#5418 Added infinite scroll
  packages/twenty-website/src/app/_components/releases/ReleaseContainer.tsx
  packages/twenty-website/src/app/releases/page.tsx
Labels: PR: awaiting review, Website

#5374 feat: display Links field as Expandable List
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventParticipantsResponseStatusField.tsx
  packages/twenty-front/src/modules/activities/components/ActivityTargetChips.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/LinksFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/MultiSelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/ui/display/tag/components/Tag.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/ChildrenContainer.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/ExpandableList.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/ExpandedListDropdown.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/components/__stories__/ExpandableList.stories.tsx
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/__tests__/getChildProperties.test.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/__tests__/getChipContentWidth.test.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/getChildProperties.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/getChipContentWidth.ts
  packages/twenty-front/src/modules/ui/layout/expandable-list/utils/isFirstOverflowingChildElement.ts
  packages/twenty-front/src/modules/ui/navigation/link/components/RoundedLink.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: PR: awaiting review

#5406 Alter comment on foreign key deletion
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/create-migration-for-foreign-key-comment-alteration.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-migration-for-foreign-key-comment-alteration.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-migrations-for-custom-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-workspace-migrations-for-remote-object-relations.util.ts
Labels: PR: awaiting review

#5002 AAU I want to re-order my views with drag & drop
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
Labels: PR: awaiting review

#5414 Fix missing team member images in calendar event
  packages/twenty-front/src/modules/activities/calendar/graphql/operation-signatures/FindOneCalendarEventOperationSignature.ts
  packages/twenty-front/src/modules/activities/calendar/right-drawer/components/RightDrawerCalendarEvent.tsx
Labels: PR: awaiting review

#5430 Fix transliteration for metadata + transliterate select options
  packages/twenty-front/src/modules/activities/calendar/right-drawer/components/RightDrawerCalendarEvent.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/metadataLabelSchema.test.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/metadataLabelSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/selectOptionsSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/utils/getOptionValueFromLabel.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsCreateObjectInputSchema.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/settingsUpdateObjectInputSchema.ts
  packages/twenty-front/src/pages/settings/data-model/constants/MetadataLabelValidPattern.ts
  packages/twenty-front/src/pages/settings/data-model/constants/MetadataNameValidPattern.ts
  packages/twenty-front/src/pages/settings/data-model/constants/OptionValueValidPattern.ts
  packages/twenty-front/src/pages/settings/data-model/utils/__tests__/compute-metadata-name-from-label.test.ts
  packages/twenty-front/src/pages/settings/data-model/utils/__tests__/compute-option-value-from-label.test.ts
  packages/twenty-front/src/pages/settings/data-model/utils/__tests__/format-metadata-label-to-name.spec.ts
  packages/twenty-front/src/pages/settings/data-model/utils/compute-metadata-name-from-label.utils.ts
  packages/twenty-front/src/pages/settings/data-model/utils/compute-option-value-from-label.utils.ts
  packages/twenty-front/src/pages/settings/data-model/utils/transliterate-and-format.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-valid-graphql-enum-name.validator.ts
Labels: PR: awaiting review

#5431 Try fix tests
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  nx.json
  packages/twenty-front/.storybook/main.ts
  packages/twenty-front/src/modules/activities/comment/Comment.tsx
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/perf/EllipsisDisplay.perf.stories.tsx
Labels: run-chromatic

#5200 feat: add renew token query for apollo client (chrome-extension)
  packages/twenty-chrome-extension/src/db/auth.db.ts
  packages/twenty-chrome-extension/src/db/token.db.ts
  packages/twenty-chrome-extension/src/graphql/auth/mutations.ts
  packages/twenty-chrome-extension/src/graphql/auth/queries.ts
  packages/twenty-chrome-extension/src/utils/apolloClient.ts
  packages/twenty-server/src/engine/core-modules/auth/services/token.service.ts
  packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
Labels: PR: awaiting author

#5441 Modified HTML for Algolia Crawler
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideContent.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebarSection.tsx
  packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx
Labels: PR: awaiting review, Website

#5434 Fix missing name validation on object names at update
  packages/twenty-server/src/engine/metadata-modules/object-metadata/hooks/before-create-one-object.hook.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/validate-object-metadata-input.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
Labels: PR: awaiting review

#5433 Enable remotes with existing name
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/get-remote-table-local-name.util.ts
Labels: PR: awaiting review

#5451 fix: fix storybook build cache not being used by tests in CI
  .github/workflows/ci-front.yaml
  nx.json
  packages/twenty-front/.storybook/main.ts
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx
  packages/twenty-front/src/modules/ui/input/components/__stories__/IconPicker.stories.tsx
  packages/twenty-ui/.storybook/main.ts
  packages/twenty-ui/project.json
Labels: run-chromatic, PR: awaiting review

#5460 Add more details to mutation limit exception message and fix update many query
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/compute-pg-graphql-error.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
Labels: PR: awaiting review

#5454 4689 multi workspace i should be able to accept an invite if im already logged in
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useWorkspaceFromInviteHash.ts
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useWorkspaceSwitching.ts
  packages/twenty-front/src/modules/workspace-member/grapqhql/mutations/addUserToWorkspace.ts
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.module.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.resolver.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.module.ts
Labels: PR: awaiting author

#5478 Fix graphql prep query
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
Labels: PR: awaiting author

#5455 Remove relations for remotes
  package.json
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchMatchesSearchFilterAndToSelectQuery.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/input/big-int-filter.input-type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-number-filter-type.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-number-scalar-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-migrations-for-custom-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-workspace-migrations-for-remote-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/udt-name-mapper.util.ts
  yarn.lock
Labels: PR: awaiting review

#5344 Fix: danger font color values & acc. to design specs
  packages/twenty-front/src/modules/ui/input/button/components/Button.tsx
Labels: PR: awaiting review

#5160 feat: fetch and parse full gmail message
  package.json
  packages/twenty-server/src/modules/messaging/constants/gmail-users-messages-get-batch-size.constant.ts
  packages/twenty-server/src/modules/messaging/services/fetch-messages-by-batches/fetch-messages-by-batches.service.ts
  packages/twenty-server/src/modules/messaging/services/gmail-fetch-message-content-from-cache/gmail-fetch-message-content-from-cache.service.ts
  packages/twenty-server/src/modules/messaging/services/utils/format-address-object-as-participants.util.ts
  packages/twenty-server/src/modules/messaging/types/gmail-message-parsed-response.ts
  packages/twenty-server/src/modules/messaging/types/gmail-message.ts
  packages/twenty-server/src/modules/messaging/utils/create-queries-from-message-ids.util.ts
  yarn.lock
Labels: PR: awaiting author

#5487 Fix storybook tests
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/__stories__/App.stories.tsx
  packages/twenty-front/src/modules/activities/calendar/components/__stories__/Calendar.stories.tsx
  packages/twenty-front/src/modules/activities/tasks/__stories__/TaskGroups.stories.tsx
  packages/twenty-front/src/modules/navigation/utils/indexAppPath.ts
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/pages/not-found/__stories__/NotFound.stories.tsx
  packages/twenty-front/src/testing/decorators/ComponentWithRouterDecorator.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/testing/mock-data/timeline-calendar-events.ts
  packages/twenty-server/src/modules/messaging/services/utils/__tests__/format-address-object-as-participants.util.spec.ts
Labels: PR: awaiting review

#5508 Update foreign table to distant table schema
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnectionTables.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionSummaryCard.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionSyncStatus.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/hooks/useDatabaseConnection.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1716310822694-removeAvailableTables.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.entity.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/types/distant-table.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/dtos/find-many-remote-tables-input.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/foreign-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/foreign-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/utils/get-foreign-table-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-schema-update/remote-table-schema-update.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-schema-update/remote-table-schema-update.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/fetch-table-columns.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: PR: awaiting author

#5313 feat: remove a link from a Links field
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldMenuItem.tsx
  packages/twenty-front/src/modules/ui/input/button/components/LightIconButtonGroup.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useDropdown.ts
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting review

#5429 feat: set primary link in Links field
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldMenuItem.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting review

#5447 feat: edit link in Links field
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldMenuItem.tsx
Labels: PR: awaiting review

#5466 Extract typography components from twenty-front to twenty-ui.
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsBlocklistSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsNewAccountSection.tsx
  packages/twenty-front/src/modules/settings/data-model/new-object/components/SettingsAvailableStandardObjectsSection.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationGroup.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionShowContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationEditDatabaseConnectionContent.tsx
  packages/twenty-front/src/modules/settings/profile/components/ChangePassword.tsx
  packages/twenty-front/src/modules/settings/profile/components/DeleteAccount.tsx
  packages/twenty-front/src/modules/settings/profile/components/DeleteWorkspace.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx
  packages/twenty-front/src/pages/auth/CreateProfile.tsx
  packages/twenty-front/src/pages/auth/CreateWorkspace.tsx
  packages/twenty-front/src/pages/settings/Releases.tsx
  packages/twenty-front/src/pages/settings/SettingsAppearance.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/SettingsProfile.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspace.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendars.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsCalendarsSettings.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmails.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep1.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationDatabase.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-ui/src/display/index.ts
  packages/twenty-ui/src/display/typography/components/H1Title.tsx
  packages/twenty-ui/src/display/typography/components/H2Title.tsx
  packages/twenty-ui/src/display/typography/components/H3Title.tsx
  packages/twenty-ui/src/display/typography/components/__stories__/H1Title.stories.tsx
  packages/twenty-ui/src/display/typography/components/__stories__/H2Title.stories.tsx
  packages/twenty-ui/src/display/typography/components/__stories__/H3Title.stories.tsx
Labels: PR: awaiting review

#5473 fix: fix Apollo client cache update error for Links field
  packages/twenty-front/src/modules/object-record/cache/utils/__tests__/getRecordNodeFromRecord.test.ts
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordNodeFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-front/src/utils/string/__tests__/pascalCase.test.ts
  packages/twenty-front/src/utils/string/lowerAndCapitalize.ts
  packages/twenty-front/src/utils/string/pascalCase.ts
Labels: PR: awaiting review

#5457 perf: use Nx cache for Chromatic script
  nx.json
  packages/twenty-front/package.json
Labels: run-chromatic, PR: awaiting review

#5524 Added Algolia Search
  packages/twenty-docs/docusaurus.config.js
  packages/twenty-website/.env.example
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleEditContent.tsx
  packages/twenty-website/src/app/_components/user-guide/AlgoliaDocSearch.tsx
  packages/twenty-website/src/app/_components/user-guide/UserGuideSidebar.tsx
  packages/twenty-website/src/app/user-guide/algolia.css
  packages/twenty-website/src/content/user-guide/api-webhooks.mdx
  packages/twenty-website/src/content/user-guide/create-workspace.mdx
  packages/twenty-website/src/content/user-guide/fields.mdx
  packages/twenty-website/src/content/user-guide/import-export-data.mdx
  packages/twenty-website/src/content/user-guide/integrations.mdx
  packages/twenty-website/src/content/user-guide/kanban-views.mdx
  packages/twenty-website/src/content/user-guide/notes.mdx
  packages/twenty-website/src/content/user-guide/objects.mdx
  packages/twenty-website/src/content/user-guide/table-views.mdx
  packages/twenty-website/src/content/user-guide/tasks.mdx
  packages/twenty-website/src/content/user-guide/tips.mdx
  packages/twenty-website/src/content/user-guide/views-sort-filter.mdx
  packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx
Labels: PR: awaiting review, Website

#5532 Fixed congratulations bot
  packages/twenty-utils/congratulate-dangerfile.ts
  packages/twenty-website/src/app/contributors/page.tsx
  packages/twenty-website/src/app/contributors/utils/get-contributor-activity.ts
  packages/twenty-website/src/shared-utils/listTeamMembers.ts
Labels: PR: awaiting review, Website

#5535 feat: add feature flag to activate Links field creation
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
Labels: PR: awaiting review

#5547 fix: workspace health showing error for multi select
  packages/twenty-server/src/engine/workspace-manager/workspace-health/interfaces/workspace-table-definition.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-health/services/database-structure.service.ts
Labels: PR: awaiting author

#5515 feat: implement new SnackBar design
  packages/twenty-front/.storybook/preview.tsx
  packages/twenty-front/src/modules/activities/hooks/useCustomResolver.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResetPassword.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/error-handler/components/PromiseRejectionEffect.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-field/components/LightCopyIconButton.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/useSpreadsheetRecordImport.ts
  packages/twenty-front/src/modules/settings/developers/components/ApiKeyInput.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationEditDatabaseConnectionContent.tsx
  packages/twenty-front/src/modules/settings/profile/components/ChangePassword.tsx
  packages/twenty-front/src/modules/settings/workspace/components/ToggleImpersonate.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadFlow.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  packages/twenty-front/src/modules/ui/feedback/progress-bar/components/ProgressBar.tsx
  packages/twenty-front/src/modules/ui/feedback/progress-bar/components/__stories__/ProgressBar.stories.tsx
  packages/twenty-front/src/modules/ui/feedback/progress-bar/hooks/useProgressAnimation.ts
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBar.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBarProvider.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/__stories__/SnackBar.stories.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/hooks/__tests__/usePausableTimeout.test.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/hooks/usePausableTimeout.ts
  packages/twenty-front/src/modules/ui/theme/constants/Colors.ts
  packages/twenty-front/src/modules/ui/theme/constants/MainColorNames.ts
  packages/twenty-front/src/modules/ui/theme/constants/MainColors.ts
  packages/twenty-front/src/modules/ui/theme/constants/OverlayBackground.ts
  packages/twenty-front/src/modules/ui/theme/constants/TextInputStyle.ts
  packages/twenty-front/src/modules/ui/theme/constants/ThemeDark.ts
  packages/twenty-front/src/modules/ui/theme/constants/ThemeLight.ts
  packages/twenty-front/src/modules/workspace/components/WorkspaceInviteLink.tsx
  packages/twenty-front/src/pages/auth/ChooseYourPlan.tsx
  packages/twenty-front/src/pages/auth/CreateProfile.tsx
  packages/twenty-front/src/pages/auth/CreateWorkspace.tsx
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/pages/auth/PasswordReset.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-front/tsup.ui.index.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/theme/constants/SnackBarCommon.ts
  packages/twenty-ui/src/theme/constants/SnackBarDark.ts
  packages/twenty-ui/src/theme/constants/SnackBarLight.ts
  packages/twenty-ui/src/theme/constants/ThemeCommon.ts
  packages/twenty-ui/src/theme/constants/ThemeDark.ts
  packages/twenty-ui/src/theme/constants/ThemeLight.ts
  packages/twenty-ui/src/theme/index.ts
Labels: PR: awaiting review

#5538 Handle relations separately for remotes
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/create-migration-for-foreign-key-comment-alteration.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-migrations-for-custom-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-migration-for-foreign-key-comment-alteration.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/create-workspace-migrations-for-remote-object-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/remote-table-relations.module.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/remote-table-relations.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/utils/build-migrations-to-create-remote-table-relations.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-relations/utils/build-migrations-to-remove-remote-table-relations.util.ts
Labels: PR: awaiting author

#5546 Add sorter for distant tables
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/utils/__tests__/sort-distant-tables.spec.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/utils/sort-distant-tables.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/utils/stripe-distant-tables.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table-schema-update/remote-table-schema-update.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
Labels: PR: awaiting review

#5553 [fix] Update remote table sync status in cache after schema update
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTableSchemaChanges.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
Labels: PR: awaiting review

#5534 refactor: reset field default value on type change in Settings
  packages/twenty-front/src/modules/object-metadata/validation-schemas/selectOptionsSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/components/SettingsDataModelFieldBooleanForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/components/SettingsDataModelFieldBooleanSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/hooks/useBooleanSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldTypeSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/currency/components/SettingsDataModelFieldCurrencyForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/currency/components/SettingsDataModelFieldCurrencySettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/currency/hooks/useCurrencySettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/hooks/useSelectSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/hooks/useSelectSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/__tests__/generateNewSelectOptionLabel.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/__tests__/getOptionValueFromLabel.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/generateNewSelectOption.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/generateNewSelectOptionLabel.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/utils/getOptionValueFromLabel.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#5517 Fixed sync between record value context selector and record store
  package.json
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldFocusContext.ts
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldFocusContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useFieldFocus.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useGetButtonIcon.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/LinksFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/MultiSelectFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/RelationFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/mock.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/getFieldButtonIcon.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellValue.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-store/components/RecordValueSetterEffect.tsx
  packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/RecordTableCell.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/mock.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useCloseCurrentTableCellInEditMode.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useMoveEditModeToCellPosition.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetSoftFocusPosition.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellDisplayMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/constants/FieldEditButtonWidth.ts
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/testing/decorators/ProfilerDecorator.tsx
  packages/twenty-front/src/testing/profiling/components/ProfilingQueueEffect.tsx
  packages/twenty-front/src/testing/profiling/components/ProfilingReporter.tsx
  packages/twenty-front/src/testing/profiling/states/currentProfilingRunIndexState.ts
  packages/twenty-front/src/testing/profiling/types/ProfilingReportByRun.ts
  packages/twenty-front/src/testing/profiling/utils/computeProfilingReport.ts
  packages/twenty-front/src/testing/profiling/utils/getProfilingStory.ts
  yarn.lock
Labels: PR: awaiting author

#5567 feat: move Snackbar to top of screen on mobile
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBar.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBarProvider.tsx
  packages/twenty-ui/src/theme/constants/Blur.ts
Labels: PR: awaiting review

#5541 feat: simplify field preview logic in Settings
  package.json
  packages/twenty-chrome-extension/src/manifest.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/currencyFieldDefaultValueSchema.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/multiSelectFieldDefaultValueSchema.ts
  packages/twenty-front/src/modules/object-record/record-field/validation-schemas/selectFieldDefaultValueSchema.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/currency/components/SettingsDataModelFieldCurrencyForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/__stories__/SettingsDataModelFieldPreviewCard.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/__tests__/useFieldPreview.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/__tests__/useFieldPreviewValue.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreview.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/usePreviewRecord.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useRelationFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getCurrencyFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getMultiSelectFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getSelectFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getCurrencyFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getMultiSelectFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getSelectFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/__tests__/getFieldDefaultPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldDefaultPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getSettingsFieldTypeConfig.ts
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/src/utils/date-utils.ts
  yarn.lock
Labels: PR: awaiting review

#5563 Fix sync token is no longer valid in calendar sync
  packages/twenty-server/src/modules/calendar/repositories/calendar-channel.repository.ts
  packages/twenty-server/src/modules/calendar/services/google-calendar-sync/google-calendar-sync.service.ts
Labels: PR: awaiting author

#5516 Feat/performance-refactor-styled-component
  package.json
  packages/twenty-front/.storybook/preview.tsx
  packages/twenty-front/.storybook/test-runner-jest.config.js
  packages/twenty-front/src/modules/object-metadata/utils/getAvatarType.ts
  packages/twenty-front/src/modules/object-metadata/utils/getAvatarUrl.ts
  packages/twenty-front/src/modules/object-metadata/utils/getImageIdentifierFieldValue.ts
  packages/twenty-front/src/modules/object-metadata/utils/getLabelIdentifierFieldValue.ts
  packages/twenty-front/src/modules/object-metadata/utils/getLinkToShowPage.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/RelationFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/types/RecordChipData.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/RecordTableCell.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/mock.ts
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableContext.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordChipDataGenerator.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.module.css
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellDisplayContainer.module.css
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellDisplayContainer.tsx
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldCurrencyCodes.ts
  packages/twenty-front/src/modules/ui/theme/components/AppThemeProvider.tsx
  packages/twenty-front/vite.config.ts
  packages/twenty-ui/.storybook/preview.tsx
  packages/twenty-ui/src/display/avatar/components/Avatar.module.css
  packages/twenty-ui/src/display/avatar/components/Avatar.tsx
  packages/twenty-ui/src/display/chip/components/Chip.module.css
  packages/twenty-ui/src/display/chip/components/Chip.tsx
  packages/twenty-ui/src/display/chip/components/EntityChip.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.module.css
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
  packages/twenty-ui/src/theme/constants/BorderCommon.ts
  packages/twenty-ui/src/theme/constants/FontCommon.ts
  packages/twenty-ui/src/theme/provider/ThemeProvider.tsx
  packages/twenty-ui/src/theme/provider/theme.css
  yarn.lock
Labels: PR: awaiting author

#5560 0.12 changelog
  packages/twenty-website/public/images/releases/0.12/0.12-link-field.png
  packages/twenty-website/public/images/releases/0.12/0.12-loader.png
  packages/twenty-website/public/images/releases/0.12/0.12-notifications.png
  packages/twenty-website/src/content/releases/0.12.0.mdx
Labels: PR: awaiting author

#5526 5509 remove flash on intermediate verify step when sign in with sso
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/hooks/__tests__/useDefaultHomePagePath.test.ts
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/useDefaultHomePagePath.tsx
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
  packages/twenty-front/src/modules/auth/hooks/useOnboardingStatus.ts
  packages/twenty-front/src/modules/auth/hooks/useSignOutAndRedirect.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useNavigateAfterSignInUp.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useWorkspaceFromInviteHash.ts
  packages/twenty-front/src/modules/auth/utils/__test__/getOnboardingStatus.test.ts
  packages/twenty-front/src/modules/auth/utils/getOnboardingStatus.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/profile/components/DeleteAccount.tsx
  packages/twenty-front/src/modules/settings/profile/components/DeleteWorkspace.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/layout/states/isDefaultLayoutAuthModalVisibleState.ts
  packages/twenty-front/src/pages/DefaultHomePage.tsx
  packages/twenty-front/src/pages/auth/ChooseYourPlan.tsx
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/pages/auth/PasswordReset.tsx
Labels: PR: wip, PR: awaiting author

#5356 Add Object Alternative view
  package.json
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverview.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewField.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewObject.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewRelationMarkers.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/util/__tests__/calculateHandlePosition.test.ts
  packages/twenty-front/src/modules/settings/data-model/graph-overview/util/calculateHandlePosition.ts
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectOverview.tsx
  yarn.lock
Labels: PR: awaiting author

#5545 Prefetch Skeleton Loading on Indexes and Shows
  packages/twenty-front/src/modules/activities/timeline/components/Timeline.tsx
  packages/twenty-front/src/modules/activities/timeline/components/TimelineSkeletonLoader.tsx
  packages/twenty-front/src/modules/favorites/components/Favorites.tsx
  packages/twenty-front/src/modules/favorites/components/FavoritesSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItemsSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-metadata/components/__stories__/ObjectMetadataNavItems.stories.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/property-box/components/PropertyBoxSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSectionSkeletonLoader.tsx
  packages/twenty-front/src/modules/prefetch/hooks/useIsPrefetchLoading.ts
  packages/twenty-front/src/modules/support/components/SupportChat.tsx
  packages/twenty-front/src/modules/support/components/SupportChatSkeletonLoader.tsx
  packages/twenty-front/src/modules/support/components/__stories__/SupportChat.stories.tsx
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/perf/EllipsisDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSectionTitle.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSectionTitleSkeletonLoader.tsx
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarSkeletonLoader.tsx
  packages/twenty-front/src/pages/auth/__stories__/ChooseYourPlan.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateProfile.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateWorkspace.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PasswordReset.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PaymentSuccess.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/pages/impersonate/__stories__/ImpersonateEffect.stories.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordIndexPage.stories.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsAppearance.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsBilling.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsProfile.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsWorkspace.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsWorkspaceMembers.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccounts.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendars.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendarsSettings.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmails.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmailsInboxSettings.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsNewAccount.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsNewObject.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectEdit.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectFieldEdit.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep1.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep2.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjects.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopers.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksNew.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationDatabase.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationEditDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationNewDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationShowDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrations.stories.tsx
  packages/twenty-front/src/pages/tasks/__stories__/Tasks.stories.tsx
  packages/twenty-front/src/testing/decorators/PrefetchLoadingDecorator.tsx
Labels: PR: awaiting author

#5347 User & Metadata Loading
  packages/twenty-front/src/loading/components/LeftPanelSkeletonLoader.tsx
  packages/twenty-front/src/loading/components/MainNavigationDrawerItemsSkeletonLoader.tsx
  packages/twenty-front/src/loading/components/RightPanelSkeletonLoader.tsx
  packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx
  packages/twenty-front/src/loading/hooks/useUserOrMetadataLoading.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsProvider.tsx
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
Labels: PR: awaiting review

#5569 Fix SnackBar visual
  packages/twenty-front/src/modules/activities/table/components/CommentChip.tsx
  packages/twenty-front/src/modules/ui/feedback/snack-bar-manager/components/SnackBar.tsx
  packages/twenty-front/src/modules/ui/field/input/components/FieldTextAreaOverlay.tsx
  packages/twenty-front/src/modules/ui/input/button/components/FloatingIconButton.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx
  packages/twenty-ui/src/theme/constants/Blur.ts
  packages/twenty-ui/src/theme/constants/BlurDark.ts
  packages/twenty-ui/src/theme/constants/BlurLight.ts
  packages/twenty-ui/src/theme/constants/OverlayBackground.ts
  packages/twenty-ui/src/theme/constants/ThemeCommon.ts
  packages/twenty-ui/src/theme/constants/ThemeDark.ts
  packages/twenty-ui/src/theme/constants/ThemeLight.ts
  packages/twenty-ui/src/theme/index.ts
Labels: PR: awaiting review

#5572 Updated Past Events Font-Color to Primary for Visibility
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
Labels: PR: awaiting author

#5621 Add missing stripe tables
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/utils/stripe-distant-tables.util.ts
Labels: PR: awaiting review

#5638 Fix update remote field metadata
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnection.ts
  packages/twenty-front/src/modules/databases/hooks/useGetDatabaseConnectionTables.ts
  packages/twenty-front/src/modules/databases/hooks/useSyncRemoteTableSchemaChanges.ts
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionShowContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationEditDatabaseConnectionContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/hooks/useDatabaseConnection.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/foreign-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
Labels: PR: awaiting review

#5625 Fixed: In CSV import now users are able to come back to the previous step.
  packages/twenty-front/src/modules/spreadsheet-import/components/StepNavigationButton.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/SelectHeaderStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectSheetStep/SelectSheetStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/Steps.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadFlow.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/MatchColumns.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/SelectHeader.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/SelectSheet.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/Validation.stories.tsx
Labels: PR: awaiting review

#5684 After createOneDbConnection mutation, update cache manually instead of using refetchQuery
  packages/twenty-front/src/modules/databases/hooks/useCreateOneDatabaseConnection.ts
Labels: PR: awaiting review

#5680 Catch query timeout exceptions
  packages/twenty-server/src/command/command.ts
  packages/twenty-server/src/database/typeorm/metadata/metadata.datasource.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/assert-is-valid-uuid.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/integrations/exception-handler/hooks/use-exception-handler.hook.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/utils/global-exception-handler.util.ts
  packages/twenty-server/src/engine/utils/graphql-errors.util.ts
  packages/twenty-server/src/engine/utils/query-timeout.util.ts
  packages/twenty-server/src/queue-worker/queue-worker.ts
Labels: PR: awaiting review

#5652 Build empty state for remote tables
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableEmptyState.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/RecordTableEmptyState.stories.tsx
Labels: PR: awaiting review
