Repository twentyhq/twenty, pull requests merged in 2024-06, with the labels that each got.

#5714 Fix exception handler capturing graphql errors
  packages/twenty-server/src/engine/utils/global-exception-handler.util.ts
Labels: PR: awaiting review

#5703 Fixed: Fields Disappear on Drag and Drop
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
Labels: PR: awaiting author

#5696 Backfill position when not input
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/__tests__/record-position-query.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/record-position-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/record-position.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/record-position.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/services/record-position-backfill-service.ts
Labels: PR: awaiting review

#5337 Fix 4363 modify kanban menu
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemSelectTag.stories.tsx
  packages/twenty-front/src/modules/views/components/ViewFieldsVisibilityDropdownSection.tsx
Labels: PR: awaiting review

#5704 Change Navigation Font Weight
  packages/twenty-ui/src/theme/constants/FontCommon.ts
Labels: PR: awaiting author

#5718 5620 implement throttle logic for message and calendar sync
  packages/twenty-docs/docs/start/self-hosting/self-hosting.mdx
  packages/twenty-server/src/modules/connected-account/services/google-api-refresh-access-token/google-api-refresh-access-token.service.ts
  packages/twenty-server/src/modules/messaging/common/constants/messaging-throttle-duration.ts
  packages/twenty-server/src/modules/messaging/common/constants/messaging-throttle-max-attempts.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel.repository.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-error-handling.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/constants/messaging-gmail-excluded-categories.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-partial-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-messages-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/utils/filter-emails.util.ts
Labels: PR: awaiting author

#5650 Add storybook tests for User & Metadata loading
  packages/twenty-front/src/loading/components/__stories__/PrefetchLoading.stories.tsx
  packages/twenty-front/src/loading/components/__stories__/UserOrMetadataLoader.stories.tsx
  packages/twenty-front/src/modules/object-metadata/components/__stories__/ObjectMetadataNavItems.stories.tsx
  packages/twenty-front/src/modules/support/components/__stories__/SupportChat.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/ChooseYourPlan.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateProfile.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateWorkspace.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PasswordReset.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PaymentSuccess.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/pages/impersonate/__stories__/ImpersonateEffect.stories.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordIndexPage.stories.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsAppearance.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsBilling.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsProfile.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsWorkspace.stories.tsx
  packages/twenty-front/src/pages/settings/__stories__/SettingsWorkspaceMembers.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccounts.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendars.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendarsSettings.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmails.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmailsInboxSettings.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsNewAccount.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsNewObject.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectEdit.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectFieldEdit.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep1.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldStep2.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjects.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/SettingsDevelopers.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/api-keys/SettingsDevelopersApiKeysNew.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksNew.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationDatabase.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationEditDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationNewDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrationShowDatabaseConnection.stories.tsx
  packages/twenty-front/src/pages/settings/integrations/__stories__/SettingsIntegrations.stories.tsx
  packages/twenty-front/src/pages/tasks/__stories__/Tasks.stories.tsx
  packages/twenty-front/src/testing/decorators/PrefetchLoadingDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
Labels: PR: awaiting review

#5642 Create ESLint rule to discourage usage of navigate() and prefer Link
  .eslintrc.react.cjs
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionShowContainer.tsx
  packages/twenty-front/src/modules/settings/integrations/database-connection/components/SettingsIntegrationDatabaseConnectionSummaryCard.tsx
  packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/UndecoratedLink.tsx
  packages/twenty-front/src/modules/ui/navigation/link/components/__stories__/UndecoratedLink.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerBackButton.tsx
  packages/twenty-front/src/pages/auth/Authorize.tsx
  packages/twenty-front/src/pages/auth/PaymentSuccess.tsx
  packages/twenty-front/src/pages/not-found/NotFound.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  tools/eslint-rules/index.ts
  tools/eslint-rules/rules/no-navigate-prefer-link.spec.ts
  tools/eslint-rules/rules/no-navigate-prefer-link.ts
Labels: PR: awaiting review

#5757 Fix edit button missing in activity editor
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getAvatarUrl.ts
Labels: PR: awaiting review

#5767 Add endpoint to create postgres credentials
  packages/twenty-server/src/database/typeorm/core/migrations/1717751631669-addPostgresCredentials.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/postgres-credentials/dtos/postgres-credentials.dto.ts
  packages/twenty-server/src/engine/core-modules/postgres-credentials/postgres-credentials.entity.ts
  packages/twenty-server/src/engine/core-modules/postgres-credentials/postgres-credentials.module.ts
  packages/twenty-server/src/engine/core-modules/postgres-credentials/postgres-credentials.resolver.ts
  packages/twenty-server/src/engine/core-modules/postgres-credentials/postgres-credentials.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
Labels: PR: awaiting review

#5646 Fix the "Delete" action on the Kaban view
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardSelection.ts
  packages/twenty-front/src/modules/ui/navigation/action-bar/components/ActionBar.tsx
  packages/twenty-front/src/modules/ui/navigation/context-menu/components/ContextMenu.tsx
  packages/twenty-front/src/modules/ui/navigation/shared/__stories__/NavigationModal.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/shared/components/NavigationModal.tsx
Labels: PR: awaiting review

#5639 Fixed soft focus stuck
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useHandleContainerMouseEnter.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
Labels: PR: awaiting author

#5576 Fixed: Select fields now selects on pressing the enter key
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/SelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableCellFieldContextWrapper.tsx
  packages/twenty-front/src/modules/object-record/select/types/SelectFieldHotkeyScope.tsx
Labels: PR: awaiting review

#5785 Added support for Links filtering
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/FilterType.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/__tests__/getOperandsForFilterType.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandsForFilterType.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/links.composite-type.ts
Labels: PR: awaiting author

#5835 Activity timeline refactoring followup
  packages/twenty-front/src/modules/activities/calendar/components/Calendar.tsx
  packages/twenty-front/src/modules/activities/components/CustomResolverFetchMoreLoader.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventRow.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/components/TimelineActivities.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/activity/components/EventRowActivity.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/calendar/components/EventCardCalendarEvent.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/calendar/components/EventRowCalendarEvent.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/calendar/components/__stories__/EventCardCalendarEvent.stories.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/components/EventCard.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/components/EventCardToggleButton.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/components/EventIconDynamicComponent.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/components/EventRowDynamicComponent.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiff.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiffContainer.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiffLabel.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiffValue.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventFieldDiffValueEffect.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventRowMainObject.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/EventRowMainObjectUpdated.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/__stories__/EventRowMainObjectUpdated.stories.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/message/components/EventCardMessage.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/message/components/EventRowMessage.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/rows/message/components/__stories__/EventCardMessage.stories.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/utils/__tests__/getTimelineActivityAuthorFullName.test.ts
  packages/twenty-front/src/modules/activities/timelineActivities/utils/getTimelineActivityAuthorFullName.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/utils/format/__tests__/formatDate.test.ts
  packages/twenty-front/src/utils/format/formatDate.ts
  packages/twenty-front/src/utils/index.ts
Labels: PR: awaiting review

#5836 feat: add resolve absolute path util
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-server/src/engine/integrations/file-storage/file-storage.module-factory.ts
  packages/twenty-server/src/utils/resolve-absolute-path.ts
Labels: PR: awaiting author

#5844 Refacto rest api, fix graphl playground, improve analytics
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/telemetry.listener.ts
  packages/twenty-server/src/engine/api/rest/controllers/rest-api-core.controller.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/factories.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/find-many-query.factory.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/get-variables.factory.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/__tests__/ending-before-input.factory.spec.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/__tests__/last-cursor-input.factory.spec.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/__tests__/starting-before-input.factory.spec.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/ending-before-input.factory.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/starting-after-input.factory.ts
  packages/twenty-server/src/engine/api/rest/types/query-variables.type.ts
  packages/twenty-server/src/engine/api/rest/utils/__tests__/clean-graphql-response.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/utils/clean-graphql-response.utils.ts
  packages/twenty-server/src/engine/core-modules/analytics/analytics.resolver.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/parameters.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/parameters.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/path.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/responses.utils.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-telemetry.service.ts
  packages/twenty-website/src/app/_components/playground/graphql-playground.tsx
  packages/twenty-website/src/app/_components/playground/token-form.tsx
Labels: PR: awaiting review

#5756 5629 update blocklist for messaging v2
  packages/twenty-server/src/modules/calendar-messaging-participant/utils/__tests__/is-email-blocklisted.util.spec.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/utils/is-email-blocklisted.util.ts
  packages/twenty-server/src/modules/calendar/services/google-calendar-sync/google-calendar-sync.service.ts
  packages/twenty-server/src/modules/calendar/utils/filter-out-blocklisted-events.util.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/jobs/messaging-blocklist-item-delete-messages.job.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/jobs/messaging-blocklist-reimport-messages.job.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/listeners/messaging-blocklist.listener.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/messaging-blocklist-manager.module.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel-message-association.repository.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/utils/filter-emails.util.ts
Labels: PR: awaiting review

#5838 #5761 Add "No XXX found" title to filtered empty state
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableEmptyState.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/RecordTableEmptyState.stories.tsx
Labels: PR: awaiting author

#5580 feat: implement row re-ordering via drag and drop (#4846)
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/GripCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeader.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RemoveSortingModal.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useComputeNewRowPosition.ts
  packages/twenty-front/src/modules/object-record/record-table/states/isRemoveSortingModalOpenState.ts
  packages/twenty-front/src/modules/ui/input/components/IconListViewGrip.tsx
  packages/twenty-front/src/modules/ui/input/components/list-view-grip.svg
  packages/twenty-front/src/modules/ui/layout/draggable-list/components/DraggableTableBody.tsx
Labels: PR: awaiting review

#5681 Support orderBy as array
  packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts
  packages/twenty-front/src/modules/activities/files/hooks/useAttachments.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivities.test.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityTargetsForTargetableObject.test.tsx
  packages/twenty-front/src/modules/activities/hooks/usePrepareFindManyActivitiesQuery.ts
  packages/twenty-front/src/modules/activities/notes/hooks/useNotes.ts
  packages/twenty-front/src/modules/activities/tasks/hooks/useTasks.ts
  packages/twenty-front/src/modules/activities/timeline/constants/FindManyTimelineActivitiesOrderBy.ts
  packages/twenty-front/src/modules/activities/timeline/utils/makeTimelineActivitiesQueryVariables.ts
  packages/twenty-front/src/modules/activities/timelineActivities/hooks/useTimelineActivities.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/sortCachedObjectEdges.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useGetObjectOrderByField.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getObjectOrderByField.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectOrderByField.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationOrderBy.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useMultiObjectSearch.test.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useOrderByFieldPerMetadataItem.ts
  packages/twenty-front/src/modules/object-record/utils/generateFindManyRecordsQuery.ts
  packages/twenty-front/src/modules/search/hooks/__mocks__/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/__tests__/args-string.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/args-string.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/interfaces/record.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/__tests__/get-resolver-args.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-resolver-args.util.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/find-many-query.factory.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/__tests__/order-by-input.factory.spec.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/factories/input-factories/order-by-input.factory.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/utils/__tests__/check-fields.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/rest-api-core-query-builder/utils/check-order-by.utils.ts
Labels: PR: awaiting author

#5834 fix: text field overflow beyond cell limits
  packages/twenty-front/src/modules/ui/field/input/components/FieldTextAreaOverlay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/TextAreaInput.tsx
Labels: PR: awaiting review

#5865 Fix workspaceLogo in invite-email
  packages/twenty-emails/src/emails/send-invite-link.email.tsx
  packages/twenty-emails/src/utils/getImageAbsoluteURIOrBase64.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
Labels: type: bug

#5853 Fix overflow on notes
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
Labels: PR: awaiting author

#5843 Record horizontal scrolling mobile
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/ui/layout/page/ShowPageContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: PR: awaiting review

#5890 5236 expandable list leave options when editing
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
Labels: PR: awaiting review

#5849 Favicons are being re-rendered on hover
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-ui/src/display/avatar/components/Avatar.tsx
  packages/twenty-ui/src/display/avatar/components/states/isInvalidAvatarUrlState.ts
  packages/twenty-ui/src/display/index.ts
Labels: PR: awaiting author

#5641 Add a ⏎ shortcut on Select options
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx
Labels: PR: awaiting author

#5828 Data Skeleton Loading on Indexes
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardContainerSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/getNumberOfCardsPerColumnForSkeletonLoading.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardColumnLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBodyLoading.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellLoading.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSkeletonLoader.tsx
  packages/twenty-front/src/modules/object-record/states/isRecordBoardColumnLoadingFamilyState.ts
Labels: PR: awaiting review

#5905 Fix reconnect google account bug
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel.repository.ts
Labels: PR: awaiting review

#5933 5898 Create a cron to monitor messageChannelSyncStatus
  packages/twenty-server/src/modules/messaging/common/services/messaging-telemetry.service.ts
  packages/twenty-server/src/modules/messaging/messaging.module.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/commands/messaging-message-channel-sync-status-monitoring.cron.command.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.ts
  packages/twenty-server/src/modules/messaging/monitoring/messaging-monitoring.module.ts
Labels: PR: awaiting review

#5972 Fix date picker wrong on certain timezones
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateTimeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/DateTimeInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
Labels: PR: awaiting author

#5773 Add the support of Empty and Non-Empty filter
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/__tests__/getOperandsForFilterType.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandLabel.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandsForFilterType.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/__tests__/useExportTableData.test.ts
  packages/twenty-front/src/modules/views/types/ViewFilterOperand.ts
  packages/twenty-front/src/utils/array/generateILikeFiltersForCompositeFields.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
Labels: PR: awaiting author

#5974 Add disabled style on non-draggable menu items
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/__stories__/MenuItemDraggable.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-front/src/modules/views/components/ViewFieldsVisibilityDropdownSection.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerListContent.tsx
Labels: PR: awaiting review

#5998 Create feature flag for calendar V2
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
Labels: PR: awaiting review

#5988 Add update chevron
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/ui/input/button/components/LightIconButton.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemNavigate.tsx
Labels: PR: awaiting review

#5985 Fix(view): Show Kanban View Creation
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContentEffect.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx
  packages/twenty-front/src/modules/views/view-picker/hooks/useGetAvailableFieldsForKanban.ts
Labels: PR: awaiting review

#5997 Create new sync statuses and stages for calendar
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-channel.workspace-entity.ts
Labels: PR: awaiting review

#5962 5951 create a command to trigger the import of a single message
  packages/twenty-server/src/modules/messaging/common/services/messaging-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/commands/messaging-single-message-import.command.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-fetch-messages-by-batches.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-add-single-message-to-cache-for-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
Labels: PR: awaiting author

#6010 Remove useless api position parameter
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/create-variables.factory.ts
Labels: type: bug

#6008 feat: Dynamic hook registration for WorkspaceQueryHooks
  packages/twenty-server/src/engine/api/graphql/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-pre-query-hook/workspace-pre-query-hook.config.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-pre-query-hook/workspace-pre-query-hook.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-pre-query-hook/workspace-pre-query-hook.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/decorators/workspace-query-hook.decorator.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/interfaces/workspace-query-hook.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/storage/workspace-query-hook.storage.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/types/workspace-query-hook.type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook-metadata.accessor.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.constants.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.explorer.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/integrations/message-queue/drivers/pg-boss.driver.ts
  packages/twenty-server/src/engine/twenty-orm/factories/scoped-workspace-datasource.factory.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/calendar-event-find-many.pre-query.hook.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/calendar-event-find-one.pre-query-hook.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-event/services/can-access-calendar-event.service.ts
  packages/twenty-server/src/modules/calendar/query-hooks/calendar-query-hook.module.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/blocklist/blocklist-create-many.pre-query.hook.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/blocklist/blocklist-update-many.pre-query.hook.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/blocklist/blocklist-update-one.pre-query.hook.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/connected-account-query-hook.module.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/message-find-many.pre-query.hook.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/message/message-find-one.pre-query-hook.ts
  packages/twenty-server/src/modules/messaging/common/query-hooks/messaging-query-hook.module.ts
  packages/twenty-server/src/modules/workspace-member/query-hooks/workspace-member-delete-many.pre-query.hook.ts
  packages/twenty-server/src/modules/workspace-member/query-hooks/workspace-member-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workspace-member/query-hooks/workspace-member-query-hook.module.ts
Labels: PR: awaiting review

#6021 Remove message-import cache when connectedAccount is removed
  packages/twenty-server/src/modules/connected-account/query-hooks/connected-account-query-hook.module.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/connected-account/connected-account-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-clean-cache.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/listeners/messaging-import-manager-message-channel.listener.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
Labels: PR: awaiting review

#5970 Upsert endpoint and CSV import upsert
  packages/twenty-front/codegen-metadata.cjs
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFindDuplicatesResults.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecordsMutation.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindDuplicateRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindDuplicateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecordsMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindDuplicatesRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailDuplicatesSection.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/__tests__/useSpreadsheetRecordImport.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/useSpreadsheetRecordImport.ts
  packages/twenty-front/src/utils/format/__tests__/formatDate.test.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/__tests__/find-duplicates-query.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/create-many-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/fields-string.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/find-duplicates-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/update-many-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/factories/update-one-query.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/workspace-query-builder.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/workspace-query-builder.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/root-type.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/__tests__/get-resolver-args.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-resolver-args.util.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/check-order-by.utils.ts
  packages/twenty-server/src/engine/core-modules/duplicate/constants/duplicate-criteria.constants.ts
  packages/twenty-server/src/engine/core-modules/duplicate/duplicate.module.ts
  packages/twenty-server/src/engine/core-modules/duplicate/duplicate.service.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/__tests__/object-record-changed-values.spec.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/object-record-changed-properties.util.ts
  packages/twenty-server/src/engine/integrations/event-emitter/utils/object-record-changed-values.ts
  packages/twenty-server/src/engine/integrations/message-queue/drivers/sync.driver.ts
  packages/twenty-server/src/modules/calendar-messaging-participant/listeners/participant-workspace-member.listener.ts
  packages/twenty-server/src/modules/timeline/repositiories/timeline-activity.repository.ts
Labels: PR: wip, PR: awaiting author

#6024 Fix cache flush in messaging-channel-sync-status.service
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
Labels: PR: awaiting review

#6049 Create fields for calendar and messaging settings v2
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/calendar/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
Labels: PR: awaiting review

#6063 Change messaging batch size and cron pattern
  packages/twenty-server/src/modules/messaging/common/services/messaging-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/commands/messaging-messages-import.cron.command.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/constants/messaging-gmail-users-messages-get-batch-size.constant.ts
Labels: PR: awaiting review

#6038 5901 refactor email and calendar auto contact creation to create them by batch
  package.json
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/auto-companies-and-contacts-creation.module.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/constants/contacts-creation-batch-size.constant.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/listeners/auto-companies-and-contacts-creation-message-channel.listener.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/types/contact.type.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/utils/__tests__/get-unique-contacts-and-handles.spec.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/utils/filter-out-contacts-from-company-or-workspace.util.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/utils/get-unique-contacts-and-handles.util.ts
  yarn.lock
Labels: PR: awaiting review

#6034 Refactor messaging refresh access token
  packages/twenty-server/src/modules/connected-account/services/google-api-refresh-access-token/google-api-refresh-access-token.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-fetch-messages-by-batches.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
Labels: PR: awaiting review

#6066 Allow s3 credentials via env
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/file-storage/file-storage.module-factory.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
Labels: PR: awaiting review
