Repository twentyhq/twenty, pull requests merged in 2024-01, with the labels that each got.

#3147 first column of objects table fixed
  packages/twenty-front/src/modules/object-record/components/RecordTableContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableFirstColumnScrollObserver.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRefContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/contexts/RecordTableRefContext.ts
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  packages/twenty-front/src/modules/ui/theme/constants/theme.ts
Labels: PR: awaiting author

#3138 Fix favorites
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  packages/twenty-front/src/modules/favorites/components/Favorites.tsx
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useGetObjectRecordIdentifierByNameSingular.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useMapToObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-metadata/types/StandardObjectNameSingular.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-metadata/utils/isStandardObject.ts
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/object-record/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateEmptyRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useRecordTableContextMenuEntries.tsx
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
Labels: PR: awaiting review

#3214 3202 fetch emails by threads
  packages/twenty-server/src/workspace/messaging/services/fetch-batch-messages.service.ts
  packages/twenty-server/src/workspace/messaging/services/fetch-workspace-messages.service.ts
  packages/twenty-server/src/workspace/messaging/types/gmailMessageParsedResponse.ts
  packages/twenty-server/src/workspace/messaging/types/gmailThread.ts
  packages/twenty-server/src/workspace/messaging/types/gmailThreadParsedResponse.ts
  packages/twenty-server/src/workspace/messaging/types/messageOrThreadQuery.ts
  packages/twenty-server/src/workspace/messaging/types/messageQuery.ts
Labels: PR: awaiting review

#3122 2248 zapier integration implement typeorm eventsubscribers
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/integrations/message-queue/message-queue.module.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-query-runner/jobs/call-webhook-jobs.job.ts
  packages/twenty-server/src/workspace/workspace-query-runner/jobs/call-webhook.job.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-zapier/src/creates/create_record.ts
  packages/twenty-zapier/src/index.ts
  packages/twenty-zapier/src/test/authentication.test.ts
  packages/twenty-zapier/src/test/creates/create_record.test.ts
  packages/twenty-zapier/src/test/triggers/find_object_names_plural.test.ts
  packages/twenty-zapier/src/test/triggers/find_object_names_singular.test.ts
  packages/twenty-zapier/src/test/triggers/find_objects.spec.ts
  packages/twenty-zapier/src/test/triggers/trigger_record_created.test.ts
  packages/twenty-zapier/src/test/triggers/trigger_record_deleted.test.ts
  packages/twenty-zapier/src/test/triggers/trigger_record_updated.test.ts
  packages/twenty-zapier/src/test/utils/capitalize.spec.ts
  packages/twenty-zapier/src/test/utils/capitalize.test.ts
  packages/twenty-zapier/src/test/utils/computeInputFields.spec.ts
  packages/twenty-zapier/src/test/utils/computeInputFields.test.ts
  packages/twenty-zapier/src/test/utils/handleQueryParams.test.ts
  packages/twenty-zapier/src/test/utils/labelize.spec.ts
  packages/twenty-zapier/src/test/utils/labelize.test.ts
  packages/twenty-zapier/src/triggers/find_object_names_plural.ts
  packages/twenty-zapier/src/triggers/find_object_names_singular.ts
  packages/twenty-zapier/src/triggers/find_objects.ts
  packages/twenty-zapier/src/triggers/trigger_record_created.ts
  packages/twenty-zapier/src/triggers/trigger_record_deleted.ts
  packages/twenty-zapier/src/triggers/trigger_record_updated.ts
  packages/twenty-zapier/src/utils/capitalize.ts
  packages/twenty-zapier/src/utils/computeInputFields.ts
  packages/twenty-zapier/src/utils/handleQueryParams.ts
  packages/twenty-zapier/src/utils/labelling.ts
  packages/twenty-zapier/src/utils/requestDb.ts
  packages/twenty-zapier/src/utils/triggers.utils.ts
Labels: PR: awaiting author

#3192 OSS Friends list is out of date
  packages/twenty-website/src/app/components/oss-friends/Background.tsx
  packages/twenty-website/src/app/components/oss-friends/Card.tsx
  packages/twenty-website/src/app/components/oss-friends/CardContainer.tsx
  packages/twenty-website/src/app/components/oss-friends/ContentContainer.tsx
  packages/twenty-website/src/app/components/oss-friends/Header.tsx
  packages/twenty-website/src/app/oss-friends/page.tsx
Labels: PR: awaiting review, website

#3152 feat: improve menuitem btn design
  packages/twenty-front/src/modules/ui/input/button/components/LightIconButtonGroup.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx
Labels: PR: awaiting review

#3230 3218 make the function fetchworkspacememberthreads idempotent
  packages/twenty-server/src/workspace/messaging/services/fetch-workspace-messages.service.ts
Labels: PR: awaiting review

#3232 Fix Event core object
  packages/twenty-server/src/metadata/object-metadata/hooks/before-create-one-object.hook.ts
Labels: PR: awaiting review

#3211 Increase test coverage for `/modules/views`
  packages/twenty-front/src/modules/views/hooks/__tests__/useMoveViewColumns.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewFields.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewSorts.test.tsx
  packages/twenty-front/src/modules/views/utils/__tests__/viewMapFunctions.test.ts
Labels: scope: front, PR: awaiting review

#3176 feat: add RecordRelationFieldCardSection
  packages/twenty-front/src/modules/companies/components/AddPersonToCompany.tsx
  packages/twenty-front/src/modules/companies/components/CompanyTeam.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/hooks/useRelationField.ts
  packages/twenty-front/src/modules/object-record/field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/hooks/useFieldContext.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFindOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpsertRecordFromState.ts
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/utils/isFieldMetadataItemAvailable.ts
  packages/twenty-front/src/modules/people/components/PeopleCard.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
  packages/twenty-server/src/workspace/workspace-schema-builder/factories/extend-object-type-definition.factory.ts
Labels: PR: awaiting review

#3198 Loading more UI updated
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBodyFetchMoreLoader.tsx
Labels: PR: awaiting author

#3205 Add mail driver
  .github/workflows/ci-utils.yaml
  package.json
  packages/twenty-docs/docs/start/self-hosting/enviroment-variables.mdx
  packages/twenty-server/.env.example
  packages/twenty-server/src/integrations/email/drivers/interfaces/email-driver.interface.ts
  packages/twenty-server/src/integrations/email/drivers/logger.driver.ts
  packages/twenty-server/src/integrations/email/drivers/smtp.driver.ts
  packages/twenty-server/src/integrations/email/email.constants.ts
  packages/twenty-server/src/integrations/email/email.module-factory.ts
  packages/twenty-server/src/integrations/email/email.module.ts
  packages/twenty-server/src/integrations/email/email.service.ts
  packages/twenty-server/src/integrations/email/interfaces/email.interface.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/integrations.module.ts
  packages/twenty-utils/package.json
  yarn.lock
Labels: PR: awaiting author

#3146 Activity editor add File block
  packages/twenty-front/src/modules/activities/blocks/FileBlock.tsx
  packages/twenty-front/src/modules/activities/blocks/schema.ts
  packages/twenty-front/src/modules/activities/blocks/slashMenu.tsx
  packages/twenty-front/src/modules/activities/blocks/spec.ts
  packages/twenty-front/src/modules/activities/components/ActivityBodyEditor.tsx
  packages/twenty-front/src/modules/activities/components/ActivityComments.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentIcon.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
Labels: PR: awaiting review

#3229 feat: add Relation Field Card plus button in Show Page
  packages/twenty-front/src/modules/companies/components/NewOpportunityButton.tsx
  packages/twenty-front/src/modules/companies/components/OpportunityPicker.tsx
  packages/twenty-front/src/modules/object-record/field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpsertRecordFieldFromState.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpsertRecordFromState.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownEntitySearchSelect.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/RelationPicker.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
Labels: PR: awaiting review

#3311 feat: add Relation field card feature flag
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/feature-flags.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
Labels: PR: awaiting review

#3254 Sort Metadata Fields by Custom Status and Creation Date
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
  packages/twenty-front/src/utils/__tests__/sortFieldMetadataItem.test.ts
  packages/twenty-front/src/utils/sortFieldMetadataItem.ts
Labels: PR: awaiting review

#3361 Add tests for `modules/object-record/hooks`
  packages/twenty-front/jest.config.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useExecuteQuickActionOnOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useExecuteQuickActionOnOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useGenerateFindManyRecordsForMultipleMetadataItemsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useModifyRecordFromCache.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useObjectRecordBoard.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useObjectRecordTable.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useUpdateOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
Labels: PR: awaiting review

#3366 Add tests for `modules/object-record/object-sort-dropdown`
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/hooks/__tests__/useSortDropdown.test.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.tsx
Labels: PR: awaiting review

#3209 feat(signup): allow to block signup
  packages/twenty-docs/docs/start/self-hosting/environment-variables.mdx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProvider.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/isSignUpDisabledState.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/core/auth/services/auth.service.spec.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/client-config/client-config.entity.ts
  packages/twenty-server/src/core/client-config/client-config.resolver.ts
  packages/twenty-server/src/filters/utils/global-exception-handler.util.ts
  packages/twenty-server/src/filters/utils/graphql-errors.util.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
Labels: PR: awaiting review

#3226 Finish Implementing Select/MultiSelect #3166
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
Labels: PR: awaiting review

#3339 GH-3183 Add sub actions to quick actions in ActionBar
  packages/twenty-front/src/modules/object-record/hooks/useRecordTableContextMenuEntries.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/modules/ui/navigation/action-bar/components/ActionBar.tsx
  packages/twenty-front/src/modules/ui/navigation/action-bar/components/ActionBarItem.tsx
  packages/twenty-front/src/modules/ui/navigation/action-bar/types/ActionBarEntry.ts
Labels: PR: awaiting review

#3344 feat: workspace health
  packages/twenty-server/src/command.module.ts
  packages/twenty-server/src/core/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/full-name.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/index.ts
  packages/twenty-server/src/metadata/field-metadata/composite-types/link.composite-type.ts
  packages/twenty-server/src/metadata/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/metadata/field-metadata/utils/__tests__/validate-default-value-based-on-type.spec.ts
  packages/twenty-server/src/metadata/field-metadata/utils/serialize-default-value.ts
  packages/twenty-server/src/metadata/field-metadata/utils/serialize-type-default-value.util.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.factory.ts
  packages/twenty-server/src/workspace/workspace-health/commands/workspace-health-command.module.ts
  packages/twenty-server/src/workspace/workspace-health/commands/workspace-health.command.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-issue.interface.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-options.interface.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-table-definition.interface.ts
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/field-metadata-health.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/object-metadata-health.service.ts
  packages/twenty-server/src/workspace/workspace-health/utils/map-field-metadata-type-to-data-type.util.ts
  packages/twenty-server/src/workspace/workspace-health/utils/valid-name.util.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.module.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.service.ts
Labels: PR: awaiting review

#3191 Filter the opportunities "Point of contact" field
  packages/twenty-front/src/modules/companies/components/AddPersonToCompany.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/RelationPicker.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/types/RelationPickerHotkeyScope.ts
Labels: PR: awaiting review

#3334 Recursively turn relation connection into records
  package.json
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/object-record/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useMapConnectionToRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useMapConnectionToRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useMapConnectionToRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordBoard.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordConnection.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordEdge.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordQueryResult.ts
  packages/twenty-front/src/modules/object-record/types/PaginatedRecordType.ts
  packages/twenty-front/src/modules/object-record/types/PaginatedRecordTypeResults.ts
  packages/twenty-front/src/modules/object-record/utils/filterUniqueRecordEdgesByCursor.ts
  packages/twenty-front/src/modules/views/components/ViewBarEffect.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewFields.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar_ViewSorts.test.tsx
  packages/twenty-front/src/modules/views/hooks/useViewBar.ts
  packages/twenty-front/src/modules/views/types/GraphQLView.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/testing/jest/getJestHookWrapper.tsx
  yarn.lock
Labels: PR: awaiting author

#3355 Enforce email templating
  package.json
  packages/twenty-server/src/emails/common-style.ts
  packages/twenty-server/src/emails/components/BaseEmail.tsx
  packages/twenty-server/src/emails/components/BaseHead.tsx
  packages/twenty-server/src/emails/components/CallToAction.tsx
  packages/twenty-server/src/emails/components/HighlightedText.tsx
  packages/twenty-server/src/emails/components/Logo.tsx
  packages/twenty-server/src/emails/components/MainText.tsx
  packages/twenty-server/src/emails/components/Title.tsx
  packages/twenty-server/src/integrations/email/email-sender.job.ts
  packages/twenty-server/src/integrations/email/email-sender.service.ts
  packages/twenty-server/src/integrations/email/email.module.ts
  packages/twenty-server/src/integrations/email/email.service.ts
  packages/twenty-server/src/integrations/integrations.module.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/queue-worker.module.ts
  packages/twenty-server/tsconfig.json
  yarn.lock
Labels: PR: awaiting author

#3261 feat: add link to relation filtered table in Record Show Page
  package.json
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindManyRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindOneRecordQuery.ts
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/views/components/FilterQueryParamsEffect.tsx
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterEffect.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useFiltersFromQueryParams.ts
  packages/twenty-front/src/modules/views/hooks/internal/useViewFilters.ts
  packages/twenty-front/src/modules/views/hooks/useViewBar.ts
  yarn.lock
Labels: PR: awaiting author

#3332 fixed Object settings font weight fixes
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectItemTableRow.tsx
Labels: PR: awaiting author

#3384 feat: pagination with total count
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/workspace-add-total-count.command.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/factories/connection-type-definition.factory.ts
Labels: PR: awaiting review

#3350 feat: detach records from Relation field card in Show Page
  packages/twenty-front/.eslintrc.cjs
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
Labels: PR: awaiting review, blocked: conflict/dependency

#3329 feat: display identifier field in Object Detail page for custom objects
  packages/twenty-front/src/modules/object-metadata/utils/isLabelIdentifierField.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/types/FieldIdentifierType.ts
  packages/twenty-front/src/modules/settings/data-model/utils/getFieldIdentifierType.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx
Labels: PR: awaiting CI

#3394 fix: auth user decorator cannot destruct property of undefined
  packages/twenty-server/src/core/analytics/analytics.resolver.ts
  packages/twenty-server/src/decorators/auth-user.decorator.ts
Labels: PR: awaiting review

#3395 Add tests for `modules/people`, `modules/pipeline`, `modules/search` and `modules/settings`
  packages/twenty-front/jest.config.ts
  packages/twenty-front/src/modules/people/hooks/__mocks__/useSpreadsheetPersonImport.ts
  packages/twenty-front/src/modules/people/hooks/__tests__/useSpreadsheetPersonImport.test.tsx
  packages/twenty-front/src/modules/pipeline/hooks/__mocks__/usePipelineSteps.ts
  packages/twenty-front/src/modules/pipeline/hooks/__tests__/usePipelineSteps.test.tsx
  packages/twenty-front/src/modules/search/hooks/__mocks__/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchEntityQuery.test.tsx
  packages/twenty-front/src/modules/settings/data-model/hooks/__tests__/useFieldMetadataForm.test.ts
  packages/twenty-front/src/modules/settings/data-model/hooks/__tests__/useFieldPreview.test.tsx
  packages/twenty-front/src/modules/settings/developers/hooks/__tests__/useGeneratedApiKeys.test.ts
Labels: PR: awaiting review

#3398 Add tests for `modules/object-record/object-sort-dropdown`
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/hooks/__tests__/useSortDropdown.test.tsx
Labels: PR: awaiting review

#3399 Add tests for `modules/object-record/object-filter-dropdown`
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/__tests__/useFilterDropdown.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/__tests__/getOperandLabel.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/__tests__/getOperandsForFilterType.test.tsx
Labels: PR: awaiting review

#3421 Add tests for `modules/object-record/record-board`
  packages/twenty-front/src/modules/object-record/record-board/hooks/__tests__/useRecordBoard.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useCreateOpportunity.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useCurrentRecordBoardCardSelectedInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useDeleteSelectedRecordBoardCardsInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useRecordBoardActionBarEntriesInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useRecordBoardCardFieldsInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useRecordBoardColumnsInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useRecordBoardContextMenuEntriesInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useSetRecordBoardCardSelectedInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/__tests__/useUpdateCompanyBoardColumnsInternal.test.tsx
Labels: PR: awaiting review

#3307 2252 build a script to cleanup inactive workspaces
  packages/twenty-docs/docs/start/self-hosting/environment-variables.mdx
  packages/twenty-server/.env.example
  packages/twenty-server/src/command.module.ts
  packages/twenty-server/src/command.ts
  packages/twenty-server/src/core/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/core/user/services/user.service.ts
  packages/twenty-server/src/database/typeorm-seeds/core/demo/feature-flags.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/integrations/email/email-sender.job.ts
  packages/twenty-server/src/integrations/environment/decorators/is-strictly-lower-than.decorator.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
  packages/twenty-server/src/integrations/logger/interfaces/logger.interface.ts
  packages/twenty-server/src/integrations/logger/logger.module-factory.ts
  packages/twenty-server/src/integrations/logger/logger.module.ts
  packages/twenty-server/src/integrations/message-queue/interfaces/message-queue-job.interface.ts
  packages/twenty-server/src/integrations/message-queue/jobs.module.ts
  packages/twenty-server/src/metadata/data-source/data-source.service.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/clean-inactive-workspace.cron.pattern.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/clean-inactive-workspace.job.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/clean-inactive-workspaces.email.tsx
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/commands/clean-inactive-workspaces.command.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/commands/start-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/commands/stop-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/delete-inactive-workspaces.email.tsx
  packages/twenty-server/src/workspace/messaging/commands/gmail-full-sync.command.ts
Labels: PR: awaiting review

#3352 fix: fix Relation field optimistic effect on Record update
  packages/twenty-front/.eslintrc-ci.cjs
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/__tests__/useFilterDropdown.test.tsx
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/utils/parseApolloStoreFieldName.ts
Labels: PR: awaiting review

#3425 Stop switching to a different datasource per workspace
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/create-many-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/delete-many-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/delete-one-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/fields-string.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/find-many-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/find-one-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/relation-field-alias.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/update-many-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/update-one-query.factory.ts
  packages/twenty-server/src/workspace/workspace-query-builder/interfaces/workspace-query-builder-options.interface.ts
  packages/twenty-server/src/workspace/workspace-query-runner/interfaces/query-runner-optionts.interface.ts
  packages/twenty-server/src/workspace/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/create-many-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/create-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/delete-many-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/delete-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/execute-quick-action-on-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/find-many-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/find-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/update-many-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/factories/update-one-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-resolver-builder/workspace-resolver.factory.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/interfaces/workspace-schema-builder-context.interface.ts
Labels: PR: wip, PR: awaiting author

#3428 Improved Floating Button Icon style
  packages/twenty-front/src/modules/ui/input/button/components/FloatingIconButton.tsx
Labels: PR: awaiting author

#3337 UI Fixes for Dark Mode
  packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx
Labels: PR: awaiting author

#3265 Center InternalDatePicker Clear button
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
Labels: PR: awaiting author

#3427 fixed issue Display field name on Kanbans & Shows
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
  packages/twenty-front/src/modules/object-record/field/types/FieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
Labels: PR: awaiting review

#3485 Add tests for `modules/object-metadata/hooks`
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/ApolloMetadataClientProvider.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectRecordMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneRelationMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useDeleteOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useObjectMetadataItemForSettings.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useColumnDefinitionsFromFieldMetadata.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneObjectRecordMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useCreateOneRelationMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useDeleteOneObjectMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFieldMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFilterOutUnexistingObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFindManyObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useGetObjectOrderByField.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useGetObjectRecordIdentifierByNameSingular.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useMapFieldMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useMapToObjectRecordIdentifier.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectMetadataItemForSettings.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectNamePluralFromSingular.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useObjectNameSingularFromPlural.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useRecordOptimisticEffect.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useRelationMetadata.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getFieldSlug.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getObjectOrderByField.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getObjectSlug.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/isLabelIdentifierField.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/isObjectMetadataAvailableForRelation.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/validateMetadataLabel.test.ts
Labels: PR: awaiting review

#3462 Add tests for `modules/analytics`
  packages/twenty-front/src/modules/analytics/hooks/__tests__/useEventTracker.test.tsx
  packages/twenty-front/src/modules/analytics/hooks/__tests__/useTrackEvent.test.tsx
Labels: PR: awaiting review

#3461 Add tests for `modules/navigation` and `modules/keyboard-shortcut-menu`
  packages/twenty-front/src/modules/keyboard-shortcut-menu/hooks/__tests__/useKeyboardShortcutMenu.test.tsx
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useIsSettingsPage.test.tsx
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useIsTasksPage.test.tsx
Labels: PR: awaiting review

#3507 Implemented useListenClickOutside V2
  packages/twenty-front/src/modules/object-record/relation-picker/components/MultipleObjectRecordOnClickOutsideEffect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/constants/MultiObjectRecordClickOutsideListenerId.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerClickOutsideListener.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useClickOustideListenerStates.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useClickOutsideListener.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutsideV2.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerIsActivatedStateScopeMap.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerIsMouseDownInsideStateScopeMap.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/lockedListenerIdState.ts
Labels: PR: awaiting review

#3463 Add performance logs to object metadata query
  packages/twenty-server/src/metadata/field-metadata/dtos/default-value.input.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-query-builder/factories/find-many-query.factory.ts
Labels: PR: awaiting review

#3466 feat: workspace health relation
  packages/twenty-server/src/metadata/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/utils/create-relation-metadata-foreign-key.util.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-health-issue.interface.ts
  packages/twenty-server/src/workspace/workspace-health/interfaces/workspace-table-definition.interface.ts
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/field-metadata-health.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/relation-metadata.health.service.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.module.ts
  packages/twenty-server/src/workspace/workspace-health/workspace-health.service.ts
Labels: PR: awaiting review

#3503 feat: display label identifier table cell as chip with link to Record…
  packages/twenty-front/src/modules/activities/utils/__tests__/flatMapAndSortEntityForSelectArrayOfArrayByName.test.ts
  packages/twenty-front/src/modules/activities/utils/flatMapAndSortEntityForSelectArrayByName.ts
  packages/twenty-front/src/modules/companies/components/AddPersonToCompany.tsx
  packages/twenty-front/src/modules/companies/components/NewOpportunityButton.tsx
  packages/twenty-front/src/modules/companies/components/OpportunityPicker.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsRelationPickerEffect.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useMapToObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/display/components/RelationFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/hooks/useChipField.ts
  packages/twenty-front/src/modules/object-record/field/meta-types/input/components/__stories__/BooleanFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/field/states/entityFieldsFamilyState.ts
  packages/twenty-front/src/modules/object-record/field/states/selectors/entityFieldsFamilySelector.ts
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCell.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/RelationPicker.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/internal/useRelationPickerScopedStates.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useRelationPicker.ts
  packages/twenty-front/src/modules/object-record/relation-picker/states/identifiersMapperScopedState.ts
  packages/twenty-front/src/modules/object-record/relation-picker/types/EntityForSelect.ts
  packages/twenty-front/src/modules/object-record/relation-picker/types/IdentifiersMapper.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/utils/getRelationPickerScopedStates.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchEntityQuery.test.tsx
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx
Labels: PR: awaiting review

#3474 feat: Create a ThreadBottomBar component
  packages/twenty-front/src/modules/activities/emails/components/ThreadBottomBar.tsx
  packages/twenty-front/src/modules/ui/display/icon/index.ts
Labels: PR: awaiting review

#3464 Show page - disable click for workspace member relation
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/field/meta-types/display/components/__stories__/ChipFieldDisplay.stories.tsx
Labels: PR: awaiting review

#3553 Improve health check command
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/utils/create-relation-foreign-key-column-name.util.ts
  packages/twenty-server/src/metadata/relation-metadata/utils/create-relation-foreign-key-field-metadata-name.util.ts
  packages/twenty-server/src/workspace/workspace-health/services/database-structure.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/field-metadata-health.service.ts
  packages/twenty-server/src/workspace/workspace-health/services/relation-metadata.health.service.ts
Labels: PR: wip, PR: awaiting author

#3557 Update company board card link to opportunity show page
  packages/twenty-front/src/modules/companies/__stories__/CompanyChip.stories.tsx
  packages/twenty-front/src/modules/companies/components/CompanyBoardCard.tsx
  packages/twenty-front/src/modules/companies/components/CompanyChip.tsx
Labels: PR: awaiting review

#3552 Load views on user load and read in cache
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/hooks/useDefaultHomePagePath.tsx
  packages/twenty-front/src/index.tsx
  packages/twenty-front/src/modules/apollo/hooks/useCachedRootQuery.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataNavItems.tsx
  packages/twenty-front/src/modules/object-metadata/types/QueryMethodName.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateFindManyRecordsQuery.ts
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUser.ts
  packages/twenty-front/src/modules/users/graphql/queries/getCurrentUserAndViews.ts
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/pages/auth/__stories__/CreateProfile.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/PlanRequired.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-server/src/core/auth/services/token.service.ts
  packages/twenty-server/src/graphql-config.service.ts
Labels: PR: awaiting author

#3536 Update logging for smtp emails
  packages/twenty-server/src/integrations/email/drivers/smtp.driver.ts
  packages/twenty-server/src/integrations/email/email-sender.job.ts
Labels: PR: awaiting review

#3542 Move emails to dedicated package
  package.json
  packages/twenty-emails/.gitignore
  packages/twenty-emails/package.json
  packages/twenty-emails/src/common-style.ts
  packages/twenty-emails/src/components/BaseEmail.tsx
  packages/twenty-emails/src/components/BaseHead.tsx
  packages/twenty-emails/src/components/CallToAction.tsx
  packages/twenty-emails/src/components/HighlightedText.tsx
  packages/twenty-emails/src/components/Logo.tsx
  packages/twenty-emails/src/components/MainText.tsx
  packages/twenty-emails/src/components/Title.tsx
  packages/twenty-emails/src/emails/clean-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/delete-inactive-workspaces.email.tsx
  packages/twenty-emails/tsconfig.json
  packages/twenty-emails/tsup.config.ts
  packages/twenty-emails/tsup.index.tsx
  packages/twenty-server/package.json
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/clean-inactive-workspace.job.ts
  packages/twenty-server/tsconfig.json
  yarn.lock
Labels: blocked: conflict/dependency

#3584 3434 connect settingsaccountsemails to the backend
  packages/twenty-front/src/modules/accounts/types/ConnectedAccount.ts
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEmailsSyncSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsContactAutoCreationSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsSynchronizationSection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsInboxSettingsVisibilitySection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRow.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRowDropdownMenu.tsx
  packages/twenty-front/src/pages/settings/accounts/SettingsAccountsEmailsInboxSettings.tsx
  packages/twenty-front/src/testing/mock-data/accounts.ts
Labels: PR: awaiting review

#3586 Add tests for `modules/ui/utilities/pointer-event`
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/__tests__/useClickOutsideListener.test.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/__tests__/useListenClickOutsideV2.test.tsx
Labels: PR: awaiting review

#3585 Build message thread empty right drawer
  packages/twenty-front/src/modules/activities/comment/__stories__/Comment.stories.tsx
  packages/twenty-front/src/modules/activities/comment/__stories__/CommentHeader.stories.tsx
  packages/twenty-front/src/modules/activities/emails/components/ThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerThreadTopBar.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/__stories__/RightDrawerThreadTopBar.stories.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useOpenThreadRightDrawer.ts
  packages/twenty-front/src/modules/activities/right-drawer/components/ActivityActionBar.tsx
  packages/twenty-front/src/modules/activities/right-drawer/components/RightDrawerActivityTopBar.tsx
  packages/twenty-front/src/modules/activities/right-drawer/components/__stories__/RightDrawerActivityTopBar.stories.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerTopBar.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/StyledRightDrawerTopBar.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
Labels: PR: awaiting review

#3539 header component added
  packages/twenty-front/src/modules/activities/emails/components/ThreadHeader.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerThread.tsx
  packages/twenty-front/src/modules/ui/display/tag/components/Tag.tsx
Labels: PR: awaiting review

#3469 Fixed filter dropdown on task page
  packages/twenty-front/src/modules/object-metadata/utils/getObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordRemoveFilterMenuItem.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/SingleEntityObjectFilterDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/__tests__/useFilterDropdown.test.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useFilterDropdown.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/onFilterSelectScopedState.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/selectedFilterScopedState.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordIdentifier.ts
  packages/twenty-front/src/modules/ui/display/icon/index.ts
  packages/twenty-front/src/pages/tasks/TasksEffect.tsx
Labels: PR: awaiting review

#3590 Update contributing guidelines with PR precendence
  .github/CONTRIBUTING.md
Labels: PR: awaiting review

#3521 Leave table focus on show page click
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useTableCell.ts
Labels: PR: awaiting review

#3540 perf: apply record optimistic effects with cache.modify on mutation
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/files/hooks/useUploadAttachmentFile.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/__tests__/useOptimisticEffect.test.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/states/optimisticEffectState.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/OptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/OptimisticEffectResolver.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/types/internal/OptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/computeOptimisticEffectKey.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/isCachedObjectConnection.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/sortCachedObjectEdges.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/types/CachedObjectRecord.ts
  packages/twenty-front/src/modules/apollo/types/CachedObjectRecordConnection.ts
  packages/twenty-front/src/modules/apollo/types/CachedObjectRecordEdge.ts
  packages/twenty-front/src/modules/apollo/types/CachedObjectRecordQueryVariables.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useRecordOptimisticEffect.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/graphql/optimistic-effect-definition/getRecordOptimisticEffectDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateCachedObjectRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateCreateManyRecordMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateCreateOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateDeleteManyRecordMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateEmptyRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGenerateUpdateOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/hooks/useGetRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useModifyRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordBoard.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/internal/useDeleteSelectedRecordBoardCardsInternal.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useMultiObjectSearch.test.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchMatchesSearchFilterAndSelectedItemsQuery.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useMultiObjectSearchMatchesSearchFilterAndToSelectQuery.ts
  packages/twenty-front/src/modules/object-record/select/hooks/useRecordsForSelect.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecordEdge.ts
  packages/twenty-front/src/modules/object-record/utils/andFilterVariables.ts
  packages/twenty-front/src/modules/object-record/utils/generateDeleteOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/utils/orFilterVariables.ts
  packages/twenty-front/src/modules/pipeline/hooks/__mocks__/usePipelineSteps.ts
  packages/twenty-front/src/modules/pipeline/hooks/usePipelineSteps.ts
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/settings/developers/types/ApiKey.ts
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/utils/parseApolloStoreFieldName.ts
  packages/twenty-front/src/utils/sort.ts
Labels: PR: awaiting author

#3524 Fix FloatingButton to behave like FloatingIconButton in a group.
  packages/twenty-front/src/modules/ui/input/button/components/FloatingButton.tsx
Labels: run-chromatic, PR: awaiting review

#3504 fixed overflowing text for select on card #3494
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/display/components/RelationFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/field/meta-types/hooks/useRelationField.ts
  packages/twenty-front/src/modules/ui/display/chip/components/Chip.tsx
  packages/twenty-front/src/modules/ui/display/chip/components/EntityChip.tsx
  packages/twenty-front/src/modules/ui/display/chip/components/__stories__/Chip.stories.tsx
Labels: PR: awaiting review

#3525 Broken calendar component
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx
Labels: PR: awaiting review

#3594 Store HTML message
  packages/twenty-server/src/workspace/messaging/services/messaging-utils.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message.object-metadata.ts
Labels: PR: awaiting review

#3529 Tooltip on icons
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
Labels: PR: awaiting review

#3558 Fixed Max lenght in Label , #3515
  packages/twenty-front/src/modules/object-record/components/RecordShowPage.tsx
Labels: PR: awaiting review

#3522 Use scroll left instead of intersection observer
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableFirstColumnScrollObserver.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useListenScroll.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollLeftState.ts
  packages/twenty-front/src/modules/ui/utilities/scroll/states/scrollTopState.ts
Labels: PR: awaiting review

#3593 Build message threads
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadBottomBar.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadHeader.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageBody.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageBodyPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageSender.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/mocks/mockedEmailThreads.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThreadTopBar.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/__stories__/RightDrawerEmailThreadTopBar.stories.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useOpenEmailThreadRightDrawer.ts
  packages/twenty-front/src/modules/activities/emails/state/viewableEmailThreadState.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
  packages/twenty-front/src/testing/mock-data/activities.ts
Labels: PR: awaiting review

#3605 Load empty board if view type is kanban
  packages/twenty-front/src/modules/companies/components/HooksCompanyBoardEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexViewInitEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordTableEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarEffect.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useViewBar.test.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewScopedStates.ts
  packages/twenty-front/src/modules/views/hooks/useViewBar.ts
  packages/twenty-front/src/modules/views/scopes/ViewScope.tsx
  packages/twenty-front/src/modules/views/scopes/init-effect/ViewScopeInitEffect.tsx
  packages/twenty-front/src/modules/views/states/onViewTypeChangeScopedState.ts
  packages/twenty-front/src/modules/views/types/GraphQLView.ts
  packages/twenty-front/src/modules/views/types/View.ts
  packages/twenty-front/src/modules/views/utils/getViewScopedStateValuesFromSnapshot.ts
  packages/twenty-front/src/modules/views/utils/internal/getViewScopedStates.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: run-chromatic

#3561 Scroll tab list on record show
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageLeftContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
Labels: PR: awaiting review

#3538 GH-3245 Change password from settings page
  packages/twenty-docs/docs/start/self-hosting/environment-variables.mdx
  packages/twenty-emails/src/common-style.ts
  packages/twenty-emails/src/components/Link.tsx
  packages/twenty-emails/src/emails/password-reset-link.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/tsup.index.tsx
  packages/twenty-front/src/App.tsx
  packages/twenty-front/src/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/emailPasswordResetLink.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/updatePasswordViaResetToken.ts
  packages/twenty-front/src/modules/auth/graphql/queries/validatePasswordResetToken.ts
  packages/twenty-front/src/modules/settings/profile/components/ChangePassword.tsx
  packages/twenty-front/src/modules/types/AppPath.ts
  packages/twenty-front/src/pages/auth/PasswordReset.tsx
  packages/twenty-front/src/pages/settings/SettingsProfile.tsx
  packages/twenty-server/.env.example
  packages/twenty-server/package.json
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/auth/dto/email-password-reset-link.entity.ts
  packages/twenty-server/src/core/auth/dto/invalidate-password.entity.ts
  packages/twenty-server/src/core/auth/dto/password-reset-token.input.ts
  packages/twenty-server/src/core/auth/dto/token.entity.ts
  packages/twenty-server/src/core/auth/dto/update-password-via-reset-token.input.ts
  packages/twenty-server/src/core/auth/dto/update-password.entity.ts
  packages/twenty-server/src/core/auth/dto/validate-password-reset-token.entity.ts
  packages/twenty-server/src/core/auth/dto/validate-password-reset-token.input.ts
  packages/twenty-server/src/core/auth/services/auth.service.spec.ts
  packages/twenty-server/src/core/auth/services/auth.service.ts
  packages/twenty-server/src/core/auth/services/token.service.spec.ts
  packages/twenty-server/src/core/auth/services/token.service.ts
  packages/twenty-server/src/core/user/user.entity.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1704825571702-addPasswordResetToken.ts
  packages/twenty-server/src/integrations/environment/environment.service.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
Labels: PR: awaiting author

#3613 Fetch messages with hard coded thread id
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx
  packages/twenty-front/src/modules/activities/emails/mocks/mockedEmailThreads.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/types/EmailThreadMessage.ts
  packages/twenty-front/src/modules/activities/emails/types/EmailThreadMessageParticipant.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useMapFieldMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useMapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts
Labels: PR: awaiting author

#3616 [Messaging] Fix duplicate messageChannelMessage
  packages/twenty-server/src/core/auth/services/google-gmail.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-full-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/gmail-partial-sync.service.ts
  packages/twenty-server/src/workspace/messaging/services/messaging-utils.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel-message-association.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-thread.object-metadata.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message.object-metadata.ts
Labels: PR: awaiting review

#3611 3263 modify timeline messagingservice to allow the frontend to get multiple participants in a thread
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/constants/messaging.constants.ts
  packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/mocks/mockedEmailThreads.ts
  packages/twenty-front/src/modules/activities/emails/queries/fragments/participantFragment.ts
  packages/twenty-front/src/modules/activities/emails/queries/fragments/timelineThreadFragment.ts
  packages/twenty-front/src/modules/activities/emails/queries/getTimelineThreadsFromCompanyId.ts
  packages/twenty-front/src/modules/activities/emails/queries/getTimelineThreadsFromPersonId.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/state/viewableEmailThreadState.ts
  packages/twenty-front/src/testing/mock-data/activities.ts
  packages/twenty-server/src/core/messaging/constants/messaging.constants.ts
  packages/twenty-server/src/core/messaging/dtos/timeline-thread-participant.dto.ts
  packages/twenty-server/src/core/messaging/dtos/timeline-thread.dto.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.resolver.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.service.ts
Labels: PR: awaiting review

#3625 Reset workspaces to delete between executions
  packages/twenty-server/src/workspace/cron/clean-inactive-workspaces/clean-inactive-workspace.job.ts
Labels: PR: awaiting author

#3629 Add record chip for sender and add receivers
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageReceivers.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageSender.tsx
  packages/twenty-front/src/modules/activities/emails/types/EmailParticipantRole.ts
  packages/twenty-front/src/modules/activities/emails/types/EmailThreadMessageParticipant.ts
  packages/twenty-front/src/modules/activities/emails/utils/getDisplayNameFromParticipant.ts
Labels: PR: awaiting review

#3653 [Messaging] Fix gmail connected account creation redirect url
  packages/twenty-server/src/core/auth/controllers/google-gmail-auth.controller.ts
Labels: PR: awaiting review

#3619 chore: set up twenty-emails config so build isn't needed in development
  .gitignore
  nx.json
  package.json
  packages/twenty-docker/prod/twenty-server/Dockerfile
  packages/twenty-emails/.babelrc
  packages/twenty-emails/.eslintrc.json
  packages/twenty-emails/package.json
  packages/twenty-emails/src/components/BaseEmail.tsx
  packages/twenty-emails/src/components/BaseHead.tsx
  packages/twenty-emails/src/components/CallToAction.tsx
  packages/twenty-emails/src/components/HighlightedText.tsx
  packages/twenty-emails/src/components/Link.tsx
  packages/twenty-emails/src/components/MainText.tsx
  packages/twenty-emails/src/components/Title.tsx
  packages/twenty-emails/src/emails/clean-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/delete-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/password-reset-link.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/src/index.ts
  packages/twenty-emails/tsconfig.json
  packages/twenty-emails/tsconfig.lib.json
  packages/twenty-emails/tsup.config.ts
  packages/twenty-emails/tsup.index.tsx
  packages/twenty-emails/vite.config.ts
  packages/twenty-server/package.json
  packages/twenty-server/tsconfig.build.json
  packages/twenty-server/tsconfig.json
  tsconfig.base.json
  yarn.lock
Labels: PR: awaiting review

#3556 refactor: apply relation optimistic effects on record update
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useGetRelationFieldsToOptimisticallyUpdate.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRelationFieldOptimisticEffect.ts
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/companies/components/NewOpportunityButton.tsx
  packages/twenty-front/src/modules/companies/components/OpportunityPicker.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/__tests__/useFavorites.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsProvider.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsRelationPickerEffect.tsx
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/types/ObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useGetRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useModifyRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/record-board-deprecated/hooks/internal/__tests__/useDeleteSelectedRecordBoardCardsInternal.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/usePersistField.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RelationFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardContent.tsx
  packages/twenty-front/src/modules/object-record/record-relation-card/components/RecordRelationFieldCardSection.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/RelationPicker.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useEntitySelectSearch.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldPreview.stories.tsx
  packages/twenty-front/src/modules/settings/data-model/components/__stories__/SettingsObjectFieldTypeSelectSection.stories.tsx
  packages/twenty-front/src/testing/decorators/ObjectMetadataItemsDecorator.tsx
  packages/twenty-front/src/testing/mock-data/metadata.ts
  packages/twenty-front/tsconfig.json
  packages/twenty-front/tsconfig.node.json
  packages/twenty-front/tsconfig.node.tsbuildinfo
  packages/twenty-front/tsconfig.spec.json
Labels: PR: awaiting review

#3666 Build infinite scroll for email threads
  packages/twenty-emails/package.json
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThreadFetchMoreLoader.tsx
  packages/twenty-front/src/modules/activities/emails/state/emailThreadsPageState.ts
Labels: PR: awaiting review

#3676 Put back timeline thread page size const
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
Labels: PR: awaiting review

#3683 fix: fix record deletion optimistic effect
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/useSearchFilterPerMetadataItem.ts
Labels: PR: awaiting review

#3682 Add deleteOneObject mutation
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/src/metadata/object-metadata/dtos/delete-object.input.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/types/relation-to-delete.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/workspace/utils/compute-object-target-table.util.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: PR: awaiting review

#3638 fix: rating type issues
  packages/twenty-front/src/modules/object-metadata/hooks/useMapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRatingField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RatingFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRatingValue.ts
  packages/twenty-front/src/modules/ui/field/input/components/RatingInput.tsx
  packages/twenty-server/src/metadata/field-metadata/dtos/options.input.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/metadata/field-metadata/interfaces/field-metadata-options.interface.ts
  packages/twenty-server/src/metadata/field-metadata/utils/generate-rating-optionts.util.ts
  packages/twenty-server/src/metadata/field-metadata/utils/validate-options-for-type.util.ts
  packages/twenty-server/src/metadata/field-metadata/validators/is-valid-graphql-enum-name.validator.ts
  packages/twenty-server/src/workspace/workspace-schema-builder/factories/enum-type-definition.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync.metadata.service.ts
Labels: PR: awaiting review

#3641 Removed border bottom on task list
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
Labels: PR: awaiting review

#3679 Add participant avatars + remove tbody from fetchMore loader
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/ui/utilities/loading-state/components/FetchMoreLoader.tsx
Labels: PR: awaiting review

#3465 New Empty States
  packages/twenty-front/public/images/placeholders/background/404_bg.png
  packages/twenty-front/public/images/placeholders/background/500_bg.png
  packages/twenty-front/public/images/placeholders/background/empty_timeline_bg.png
  packages/twenty-front/public/images/placeholders/background/error_index_bg.png
  packages/twenty-front/public/images/placeholders/background/no_file_bg.png
  packages/twenty-front/public/images/placeholders/background/no_note_bg.png
  packages/twenty-front/public/images/placeholders/background/no_record_bg.png
  packages/twenty-front/public/images/placeholders/background/no_task_bg.png
  packages/twenty-front/public/images/placeholders/moving-image/404.png
  packages/twenty-front/public/images/placeholders/moving-image/500.png
  packages/twenty-front/public/images/placeholders/moving-image/empty_timeline.png
  packages/twenty-front/public/images/placeholders/moving-image/error_index.png
  packages/twenty-front/public/images/placeholders/moving-image/no_file.png
  packages/twenty-front/public/images/placeholders/moving-image/no_note.png
  packages/twenty-front/public/images/placeholders/moving-image/no_record.png
  packages/twenty-front/public/images/placeholders/moving-image/no_task.png
  packages/twenty-front/src/modules/activities/files/components/Attachments.tsx
  packages/twenty-front/src/modules/activities/notes/components/Notes.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskGroups.tsx
  packages/twenty-front/src/modules/activities/timeline/components/Timeline.tsx
  packages/twenty-front/src/modules/error-handler/components/GenericErrorFallback.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/AnimatedPlaceholder.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/EmptyPlaceholderStyled.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/ErrorPlaceholderStyled.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/constants/AnimatedImages.ts
  packages/twenty-front/src/pages/not-found/NotFound.tsx
Labels: PR: awaiting review

#3690 fix: fix delete records optimistic effect not re-rendering queries af…
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
Labels: PR: awaiting review

#3505 feat: workspace sync
  packages/twenty-server/package.json
  packages/twenty-server/src/core/analytics/analytics.resolver.ts
  packages/twenty-server/src/core/auth/auth.resolver.ts
  packages/twenty-server/src/core/feature-flag/interfaces/feature-flag-map.interface.ts
  packages/twenty-server/src/core/messaging/timeline-messaging.resolver.ts
  packages/twenty-server/src/core/user/user.resolver.ts
  packages/twenty-server/src/core/workspace/workspace.resolver.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/decorators/ability/user-ability.decorator.ts
  packages/twenty-server/src/decorators/auth/auth-user.decorator.ts
  packages/twenty-server/src/decorators/auth/auth-workspace.decorator.ts
  packages/twenty-server/src/integrations/environment/environment.validation.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/metadata/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/metadata/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/metadata/relation-metadata/types/relation-to-delete.ts
  packages/twenty-server/src/metadata/workspace-migration/utils/generate-migration-name.util.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/metadata/workspace-migration/workspace-migration.service.ts
  packages/twenty-server/src/utils/typed-reflect.ts
  packages/twenty-server/src/workspace/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/src/workspace/workspace-migration-runner/workspace-migration-runner.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-field.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-object.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/__tests__/workspace-relation.comparator.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/utils/__tests__/order-object-properties.util.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/utils/__tests__/transform-metadata-for-comparison.util.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/utils/order-object-properties.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/utils/transform-metadata-for-comparison.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-object.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/comparators/workspace-relation.comparator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/decorators/field-metadata.decorator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/decorators/relation-metadata.decorator.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/feature-flags.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/index.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/standard-object.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/standard-relation.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/factories/workspace-sync.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/comparator.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/partial-object-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/reflect-field-metadata.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/interfaces/workspace-sync-context.interface.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/reflective-metadata.factory.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/services/workspace-sync-relation-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/storage/workspace-sync.storage.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/is-gate-and-not-enabled.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/sync-metadata.util.spec.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/utils/sync-metadata.util.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync-metadata.module.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync-metadata.service.ts
  packages/twenty-server/src/workspace/workspace-sync-metadata/workspace-sync.metadata.service.ts
  yarn.lock
Labels: PR: awaiting review

#3699 Use scoped recoil state for email thread page
  packages/twenty-front/src/modules/activities/emails/components/EmailThreads.tsx
  packages/twenty-front/src/modules/activities/emails/hooks/internal/useEmailThreadStates.ts
  packages/twenty-front/src/modules/activities/emails/state/emailThreadsPageState.ts
  packages/twenty-front/src/modules/activities/emails/state/emailThreadsPageStateScopeMap.ts
Labels: PR: awaiting review

#3684 chore: create security.txt
  packages/twenty-website/public/.well-known/security.txt
Labels: PR: awaiting review

#3707 fix: detach relation records in cache on record deletion
  packages/twenty-front/src/modules/apollo/optimistic-effect/hooks/useGetRelationFieldsToOptimisticallyUpdate.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/isCachedObjectRecordConnection.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/isObjectRecordConnection.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerAttachRelationOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDeleteRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerDetachRelationOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRecordOptimisticEffect.ts
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRelationFieldOptimisticEffect.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useGetRelationMetadata.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useRelationMetadata.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useGetRelationMetadata.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useRelationMetadata.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useGetRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
Labels: PR: awaiting review

#3705 fix: columns overlapping with checkbox column when horizantally scrolling
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
Labels: PR: awaiting review

#3703 Minor fixes empty state
  packages/twenty-front/src/modules/activities/components/ActivityCreateButton.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskGroups.tsx
  packages/twenty-front/src/modules/activities/timeline/components/Timeline.tsx
  packages/twenty-front/src/modules/activities/timeline/components/TimelineCreateButtonGroup.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/ui/layout/animated-placeholder/components/EmptyPlaceholderStyled.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: PR: awaiting review

#3720 Design fixes + hide email tab if not a company or a person
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadHeader.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageBodyPreview.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessageSender.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/ui/input/button/components/IconButton.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageRightContainer.tsx
Labels: PR: awaiting review

#3730 Fix new board bugs
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useRecordIndexOptionsForBoard.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRow.tsx
Labels: PR: awaiting review
