Repository twentyhq/twenty, pull requests merged in 2024-07, with the labels that each got.

#6080 fix: message cleaner find operator
  packages/twenty-server/src/modules/messaging/message-cleaner/services/messaging-message-cleaner.service.ts
Labels: PR: awaiting review

#6077 Fix: Tasks-List-page-Person-Switcher
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/SingleEntityObjectFilterDropdownButton.tsx
Labels: PR: awaiting review

#6070 Add exceptions for metadata modules
  packages/twenty-server/src/engine/metadata-modules/data-source/data-source.exception.ts
  packages/twenty-server/src/engine/metadata-modules/data-source/data-source.service.ts
  packages/twenty-server/src/engine/metadata-modules/errors/InvalidStringException.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/serialize-default-value.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/compute-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/field-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/serialize-default-value.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-options-for-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/assert-mutation-not-on-remote-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/object-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/utils/relation-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.exception.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.exception.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/distant-table/distant-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/foreign-table.exception.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/foreign-table/foreign-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.exception.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/get-remote-table-local-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/utils/remote-table-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/build-update-remote-server-raw-query.utils.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/remote-server-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/validate-remote-server-input.utils.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/utils/validate-remote-server-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name.utils.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/basic-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/column-action-abstract.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/composite-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/enum-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/utils/field-metadata-type-to-column-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.exception.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.factory.ts
  packages/twenty-server/src/engine/utils/graphql-errors.util.ts
  packages/twenty-server/src/utils/custom-exception.ts
Labels: PR: awaiting review

#6067 feature to reset value in select field
  packages/twenty-front/src/modules/object-record/record-field/hooks/useClearField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/SelectFieldInput.tsx
  packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemSelectTag.tsx
  packages/twenty-ui/src/display/tag/components/Tag.tsx
Labels: PR: awaiting CI

#6096 Fix calendar import cron job
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-events-import.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/jobs/calendar-events-import.job.ts
Labels: PR: awaiting review

#6069 feat: refactor workspace sync fields
  .vscode/twenty.code-workspace
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/__tests__/workspace-field.comparator.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-object.comparator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-field.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-object.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/comparator.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-field-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/storage/workspace-sync.storage.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/compute-standard-fields.util.ts
Labels: PR: awaiting review

#6110 Fix rating field not editable if null
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
Labels: PR: awaiting review

#6107 fix: small PR fixes workspace-sync-fields
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-field-metadata.service.ts
Labels: PR: awaiting review

#5788 Text-to-SQL proof of concept
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/copilot/right-drawer/components/RightDrawerAIChat.tsx
  packages/twenty-front/src/modules/activities/copilot/right-drawer/hooks/useOpenCopilotRightDrawer.ts
  packages/twenty-front/src/modules/activities/copilot/right-drawer/states/copilotQueryState.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/search/queries/getTextToSQL.ts
  packages/twenty-front/src/modules/ui/input/components/AutosizeTextInput.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageIcons.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageTitles.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/workspace/types/FeatureFlagKey.ts
  packages/twenty-server/.env.example
  packages/twenty-server/package.json
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.service.ts
  packages/twenty-server/src/engine/core-modules/ai-sql-query/ai-sql-query.module.ts
  packages/twenty-server/src/engine/core-modules/ai-sql-query/ai-sql-query.prompt-templates.ts
  packages/twenty-server/src/engine/core-modules/ai-sql-query/ai-sql-query.resolver.ts
  packages/twenty-server/src/engine/core-modules/ai-sql-query/ai-sql-query.service.ts
  packages/twenty-server/src/engine/core-modules/ai-sql-query/dtos/ai-sql-query-result.dto.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/integrations/environment/environment-variables.ts
  packages/twenty-server/src/engine/integrations/integrations.module.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/drivers/interfaces/llm-prompt-template-driver.interface.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/drivers/openai.driver.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/interfaces/llm-chat-model.interface.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/llm-chat-model.constants.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/llm-chat-model.module-factory.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/llm-chat-model.module.ts
  packages/twenty-server/src/engine/integrations/llm-chat-model/llm-chat-model.service.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/drivers/console.driver.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/drivers/interfaces/llm-tracing-driver.interface.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/drivers/langfuse.driver.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/interfaces/llm-tracing.interface.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/llm-tracing.constants.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/llm-tracing.module-factory.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/llm-tracing.module.ts
  packages/twenty-server/src/engine/integrations/llm-tracing/llm-tracing.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.constants.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-website/src/content/developers/self-hosting/self-hosting-var.mdx
  yarn.lock
Labels: PR: awaiting author

#6113 Add command to update boolean fields null values
  packages/twenty-server/src/database/commands/0-22-update-boolean-fields-null-default-values-and-null-values.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event.workspace-entity.ts
Labels: PR: awaiting author

#6154 Add new Settings to front-end
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/onboarding/components/onboardingSyncEmailsOptions.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelDetails.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarVisibilitySettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageAutoCreationCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageAutoCreationIcon.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelDetails.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageVisibilityCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsSynchronizationStatus.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsToggleSettingCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsVisibilityIcon.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsMessageChannelDetails.stories.tsx
Labels: PR: awaiting review

#6156 Add message import granulary on non-pro emails, group emails and received contact creation
  packages/twenty-front/src/modules/onboarding/components/OnboardingSyncEmailsSettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarVisibilitySettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageAutoCreationCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageVisibilityCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRadioSettingsCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsRowDropdownMenu.tsx
  packages/twenty-front/src/modules/ui/input/components/Radio.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/add-standard-id.command.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/utils/filter-emails.util.ts
  packages/twenty-server/src/modules/messaging/message-participants-manager/jobs/messaging-create-company-and-contact-after-sync.job.ts
  packages/twenty-server/src/utils/is-group-email.ts
Labels: PR: awaiting review

#6164 Add missing objectMetadataId column in auditLog
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/timeline/standard-objects/audit-log.workspace-entity.ts
Labels: PR: awaiting review

#6173 Modify messaging message channel sync status monitoring cron pattern
  packages/twenty-server/src/modules/messaging/monitoring/crons/commands/messaging-message-channel-sync-status-monitoring.cron.command.ts
Labels: PR: awaiting review

#6165 [Flexible Schema] Create indexes for join columns
  packages/twenty-server/src/database/typeorm/metadata/migrations/1720524654925-addDateColumnsToIndexMetadata.ts
  packages/twenty-server/src/engine/metadata-modules/index-field-metadata/index-field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.entity.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-index.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-join-column.decorator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-index.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/partial-index-metadata.interface.ts
Labels: PR: awaiting review

#6171 Authorize 0 depth
  packages/twenty-server/src/engine/api/__mocks__/object-metadata-item.mock.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/__tests__/compute-depth.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/compute-depth.utils.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/parameters.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/parameters.utils.ts
Labels: PR: awaiting author

#6180 Fix wrong standard id for objectMetadataId in auditLog
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-22/0-22-fix-object-metadata-id-standard-id.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-22/0-22-update-boolean-fields-null-default-values-and-null-values.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-22/0-22-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-22/0-22-upgrade-version.module.ts
Labels: PR: awaiting review

#6176 Fix contact creation and rename email aliases to handle aliases
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsCalendars.stories.tsx
  packages/twenty-front/src/pages/settings/accounts/__stories__/SettingsAccountsEmails.stories.tsx
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/connected-account/auto-companies-and-contacts-creation/utils/filter-out-contacts-from-company-or-workspace.util.ts
  packages/twenty-server/src/modules/connected-account/email-alias-manager/drivers/google/google-email-alias-manager.service.ts
  packages/twenty-server/src/modules/connected-account/email-alias-manager/services/email-alias-manager.service.ts
  packages/twenty-server/src/modules/connected-account/repositories/connected-account.repository.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-message.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
Labels: PR: awaiting review

#5721 Support for Kubernetes via Terraform and Manifests
  packages/twenty-docker/k8s/README.md
  packages/twenty-docker/k8s/manifests/deployment-db.yaml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/manifests/ingress.yaml
  packages/twenty-docker/k8s/manifests/pv-db.yaml
  packages/twenty-docker/k8s/manifests/pv-server.yaml
  packages/twenty-docker/k8s/manifests/pvc-db.yaml
  packages/twenty-docker/k8s/manifests/pvc-server.yaml
  packages/twenty-docker/k8s/manifests/service-db.yaml
  packages/twenty-docker/k8s/manifests/service-server.yaml
  packages/twenty-docker/k8s/terraform/deployment-db.tf
  packages/twenty-docker/k8s/terraform/deployment-server.tf
  packages/twenty-docker/k8s/terraform/ingress.tf
  packages/twenty-docker/k8s/terraform/main.tf
  packages/twenty-docker/k8s/terraform/namespace.tf
  packages/twenty-docker/k8s/terraform/pv-db.tf
  packages/twenty-docker/k8s/terraform/pv-server.tf
  packages/twenty-docker/k8s/terraform/pvc-db.tf
  packages/twenty-docker/k8s/terraform/pvc-server.tf
  packages/twenty-docker/k8s/terraform/secret.tf
  packages/twenty-docker/k8s/terraform/service-db.tf
  packages/twenty-docker/k8s/terraform/service-server.tf
  packages/twenty-docker/k8s/terraform/variables.tf
  packages/twenty-website/src/content/developers/self-hosting/cloud-providers.mdx
Labels: PR: awaiting review

#6087 Deprecate address standard field
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapFieldMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapObjectMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/mock.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/__tests__/useSpreadsheetRecordImport.test.tsx
  packages/twenty-front/src/modules/search/hooks/__mocks__/useFilteredSearchEntityQuery.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockColumnDefinitions.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockCompanies.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockFilterDefinitions.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-field.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-deprecated.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-field-metadata-args.interface.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/company.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/comparators/workspace-field.comparator.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-field.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-metadata-updater.service.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/utils/typed-reflect.ts
  packages/twenty-server/test/company.e2e-spec.ts
  packages/twenty-zapier/src/test/creates/crud_record.test.ts
  packages/twenty-zapier/src/test/triggers/trigger_record.test.ts
  packages/twenty-zapier/src/test/utils/handleQueryParams.test.ts
Labels: PR: awaiting review

#6177 Remove old message channel sync statuses and create migration command
  packages/twenty-server/src/database/commands/0-22-update-message-channel-sync-status-enum.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
Labels: PR: awaiting review

#6203 Add error handling service for calendar import
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/constants/calendar-throttle-duration.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/constants/calendar-throttle-max-attempts.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/services/google-calendar-get-events.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/types/google-calendar-error.type.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/parse-gaxios-error.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/parse-google-calendar-error.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-error-handling.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-events-import.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/types/calendar-event-error.type.ts
Labels: PR: awaiting review

#6234 Fixes 6223 graph button indistinguishable (#6223). Replaces Button with FloatingButton
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverview.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx
  packages/twenty-front/src/modules/ui/input/button/components/FloatingButton.tsx
Labels: PR: awaiting author

#6201 Improve performance of demo workspace
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/companies-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/company.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/people-demo.json.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/person.ts
Labels: PR: awaiting review

#6252 Add no value column on Kanban
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsFieldDefinition.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/types/RecordBoardColumnDefinition.ts
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/SelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardColumnLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoader.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/utils/computeRecordBoardColumnDefinitionsFromObjectMetadata.ts
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarEffect.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/view-fields.ts
  packages/twenty-front/src/testing/mock-data/views.ts
  packages/twenty-ui/src/display/tag/components/Tag.tsx
Labels: PR: awaiting review

#6250 Add box shadow on frozen first column on table
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDroppable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx
Labels: PR: awaiting review

#5877 fix: remove usage of probability field
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsFieldTypeConfigs.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
  packages/twenty-server/src/engine/api/__mocks__/object-metadata-item.mock.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-default-value.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/validate-default-value-based-on-type.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-default-value-for-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/basic-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/utils/field-metadata-type-to-column-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.factory.ts
Labels: PR: awaiting author

#6269 6254 double creation of contacts when updating calendar event participants
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/format-google-calendar-event.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-save-events.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/services/calendar-event-participant.service.ts
  packages/twenty-server/src/modules/calendar/common/types/calendar-event.ts
Labels: PR: awaiting review

#6270 Add interceptors for auto-resolvers
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interceptors/field-metadata-graphql-api-exception.interceptor.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/interceptors/object-metadata-graphql-api-exception.interceptor.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/interceptors/relation-metadata-graphql-api-exception.interceptor.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.module.ts
Labels: PR: awaiting review

#6280 Create command to migrate message channel sync stage enum
  packages/twenty-server/src/database/commands/0-22-update-message-channel-sync-stage-enum.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
Labels: PR: awaiting review

#6274 fix: conditionally rendered Tablist only if there are multiple accounts.
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelDetails.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelsContainer.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelDetails.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsContainer.tsx
Labels: PR: awaiting author

#6294 Add upgrade guide section to webiste
  packages/twenty-website/src/content/developers/constants/DocsIndex.ts
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: PR: wip, PR: awaiting author

#6100 #6094 Prevent creating a custom field with an existing name
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/metadataLabelSchema.test.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/fieldMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/metadataLabelSchema.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/utils/errorMessages.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/validation-schemas/settingsFieldFormSchema.ts
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldStep2.tsx
Labels: PR: awaiting review

#6310 Add rating filter/sort + fix isEmpty/isNotEmpty + fix combinedViewFilters
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsSortDefinitions.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/MultipleFiltersDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRatingInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/FilterType.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getOperandsForFilterType.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/hooks/useCombinedViewFilters.ts
  packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFiltersAndSorts.ts
  packages/twenty-front/src/modules/views/utils/combinedViewFilters.ts
Labels: PR: awaiting review

#6323 Fix Metadata GQL server hook
  packages/twenty-server/src/engine/api/graphql/graphql-config/hooks/use-cached-metadata.ts
Labels: PR: awaiting review

#6227 Add label identifier to object decorator
  packages/twenty-server/src/database/typeorm/metadata/migrations/1721057142509-fixIdentifierTypes.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/object-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/object-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-entity.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-entity-metadata-args.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/interfaces/partial-object-metadata.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-object-metadata-identifiers.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.service.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity.workspace-entity.ts
  packages/twenty-server/src/modules/api-key/standard-objects/api-key.workspace-entity.ts
  packages/twenty-server/src/modules/attachment/standard-objects/attachment.workspace-entity.ts
  packages/twenty-server/src/modules/blocklist/standard-objects/blocklist.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-channel.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event-participant.workspace-entity.ts
  packages/twenty-server/src/modules/calendar/common/standard-objects/calendar-event.workspace-entity.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/connected-account/standard-objects/connected-account.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-participant.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/timeline/standard-objects/audit-log.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: PR: awaiting review

#6297 Fix post merge revamp navigation bar
  packages/twenty-front/src/hooks/useScrollRestoration.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useActiveFieldMetadataItems.ts
  packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/utils/isFieldIdentifierDisplay.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexRecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts
  packages/twenty-front/src/modules/object-record/record-show/graphql/operations/factories/findOneRecordForShowPageOperationSignatureFactory.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPage.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts
  packages/twenty-front/src/modules/object-record/record-show/utils/buildShowPageURL.ts
  packages/twenty-front/src/modules/object-record/record-table/constants/RowHeight.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/scopes/scope-internal-context/RecordTableScopeInternalContext.ts
  packages/twenty-front/src/modules/object-record/record-table/utils/buildIndexTableURL.ts
  packages/twenty-front/src/modules/object-record/utils/getRecordChipGenerators.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useExtractedComponentFamilyStateV2.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useRecoilComponentFamilyValue.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useScopeIdFromStateContext.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/types/ComponentFamilyState.ts
  packages/twenty-front/src/modules/ui/utilities/state/component-state/utils/createComponentFamilyStateV2.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromActiveFieldsOfViewOrDefaultView.ts
  packages/twenty-front/src/modules/views/hooks/useViewOrDefaultViewFromPrefetchedViews.ts
  packages/twenty-front/src/modules/views/utils/getQueryVariablesFromView.ts
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/testing/mock-data/views.ts
  packages/twenty-front/src/utils/getRelayCursorFromRecordId.ts
Labels: PR: awaiting author

#6166 truncate the string if overlow the text
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/FullNameFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/TextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useTextFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellValue.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowContainer.tsx
  packages/twenty-front/src/modules/ui/field/display/components/TextDisplay.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DoubleTextInput.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSummaryCard.tsx
Labels: PR: awaiting CI

#5815 mod: entrypoint for docker to setup db even in server with less memory
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
Labels: PR: awaiting review

#6081 feat: bump yarn to last stable version
  .yarn/releases/yarn-4.0.2.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  package.json
Labels: PR: awaiting review

#6340 Cannot delete label identifier associated field
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
Labels: PR: awaiting review

#6357 Add Confirmation Modal for Deletion Action and Map All Action Bar Entries
  packages/twenty-front/src/modules/object-record/record-action-bar/hooks/useRecordActionBar.tsx
  packages/twenty-front/src/modules/ui/navigation/shared/components/NavigationModal.tsx
Labels: PR: awaiting review

#6352 Datamodel overview show other fields
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewField.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewFieldWithoutRelation.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewObject.tsx
Labels: PR: awaiting author

#6332 Migrate fields of deprecated type LINK to type LINKS
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-link-fields-to-links.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm-core.module.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm-global.manager.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/modules.module.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/view/services/view.service.ts
  packages/twenty-server/src/modules/view/view.module.ts
Labels: PR: awaiting author

#5470 5425 - Introducing support for all Composite Fields Import
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useCurrencyField.ts
  packages/twenty-front/src/modules/object-record/record-index/options/components/RecordIndexOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useExportTableData.ts
  packages/twenty-front/src/modules/object-record/record-index/options/hooks/useProcessRecordsForCSVExport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/__tests__/useOpenObjectRecordsSpreasheetImportDialog.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreasheetImportDialog.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/types/AvailableFieldForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/types/CompositeFieldLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/types/KeyOfCompositeField.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/useSpreadsheetRecordImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/util/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/util/getSpreadSheetFieldValidationDefinitions.ts
  packages/twenty-front/src/modules/spreadsheet-import/components/Providers.tsx
  packages/twenty-front/src/modules/spreadsheet-import/hooks/__tests__/useSpreadsheetImport.test.tsx
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useOpenSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useSpreadsheetImport.ts
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useSpreadsheetImportInternal.ts
  packages/twenty-front/src/modules/spreadsheet-import/provider/components/SpreadsheetImport.tsx
  packages/twenty-front/src/modules/spreadsheet-import/provider/components/SpreadsheetImportProvider.tsx
  packages/twenty-front/src/modules/spreadsheet-import/states/spreadsheetImportDialogState.ts
  packages/twenty-front/src/modules/spreadsheet-import/states/spreadsheetImportState.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UserTableColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/SelectHeaderStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadFlow.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/components/columns.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/types.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/SelectHeader.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/tests/mockRsiValues.ts
  packages/twenty-front/src/modules/spreadsheet-import/types/index.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/dataMutations.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/findUnmatchedRequiredFields.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/dataMutations.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/findUnmatchedRequiredFields.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/normalizeTableData.ts
  packages/twenty-front/src/utils/__tests__/convert-currency-amount.test.ts
  packages/twenty-front/src/utils/castToString.ts
  packages/twenty-front/src/utils/convert-currency-amount.ts
  packages/twenty-front/src/utils/convertCurrencyToCurrencyMicros.ts
  packages/twenty-front/src/utils/isValidUuid.ts
Labels: PR: awaiting CI

#6351 Fix task text overflow
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
Labels: PR: awaiting author

#6411 Fix participant chip
  packages/twenty-front/src/modules/activities/components/ParticipantChip.tsx
  packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts
Labels: PR: awaiting review

#5965 Updated MessageChannelSyncStatus enum: changed COMPLETED to ACTIVE
  packages/twenty-chrome-extension/src/generated/graphql.tsx
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-message-channel-sync-status-enum.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/modules/messaging/common/repositories/message-channel.repository.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
Labels: PR: awaiting review

#6426 Delete cache version on reset db
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-cache-version/workspace-cache-version.service.ts
Labels: PR: awaiting review

#6409 6255 move services from messaging common module into the correct module and refactor them
  packages/twenty-server/src/modules/blocklist/utils/__tests__/is-email-blocklisted.util.spec.ts
  packages/twenty-server/src/modules/blocklist/utils/is-email-blocklisted.util.ts
  packages/twenty-server/src/modules/calendar-messaging-participant-manager/services/add-person-id-and-workspace-member-id/add-person-id-and-workspace-member-id.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/utils/filter-out-blocklisted-events.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/calendar-event-participant-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/jobs/calendar-event-participant-match-participant.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/jobs/calendar-event-participant-unmatch-participant.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/listeners/calendar-event-participant.listener.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/services/calendar-event-participant.service.ts
  packages/twenty-server/src/modules/calendar/calendar.module.ts
  packages/twenty-server/src/modules/calendar/common/calendar-common.module.ts
  packages/twenty-server/src/modules/connected-account/utils/is-throttled.ts
  packages/twenty-server/src/modules/match-participant/match-participant.module.ts
  packages/twenty-server/src/modules/match-participant/match-participant.service.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/constants/messaging-throttle-duration.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/constants/messaging-throttle-max-attempts.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/messaging-gmail-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-fetch-messages-by-batches.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/messaging-gmail-history.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-messages-import.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-error-handling.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message-thread.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/utils/filter-emails.util.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/message-participant-match-participant.job.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/message-participant-unmatch-participant.job.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/jobs/messaging-create-company-and-contact-after-sync.job.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/listeners/message-participant.listener.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/message-participant-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/services/messaging-message-participant.service.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.ts
  packages/twenty-server/src/modules/messaging/monitoring/messaging-monitoring.module.ts
  packages/twenty-server/src/modules/messaging/monitoring/services/messaging-telemetry.service.ts
Labels: PR: awaiting review

#6301 5899 display a banner to alert users which need to reconnect their account
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/calendar/types/CalendarEvent.ts
  packages/twenty-front/src/modules/auth/states/currentUserState.ts
  packages/twenty-front/src/modules/information-banner/InformationBanner.tsx
  packages/twenty-front/src/modules/information-banner/InformationBannerReconnectAccount.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelsGeneral.tsx
  packages/twenty-front/src/modules/ui/layout/page/SubMenuTopBarContainer.tsx
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/pages/settings/Releases.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/crm-migration/SettingsCRMMigration.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationEditDatabaseConnection.tsx
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationNewDatabaseConnection.tsx
  packages/twenty-front/src/testing/mock-data/timeline-calendar-events.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1721139150487-addKeyValuePairType.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1721656106498-migrateKeyValueTypeToJsonb.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/core-modules/key-value-pair/key-value-pair.entity.ts
  packages/twenty-server/src/engine/core-modules/key-value-pair/key-value-pair.service.ts
  packages/twenty-server/src/engine/core-modules/onboarding/onboarding.module.ts
  packages/twenty-server/src/engine/core-modules/onboarding/onboarding.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
  packages/twenty-server/src/engine/core-modules/user/user-vars/services/user-vars.service.ts
  packages/twenty-server/src/engine/core-modules/user/user-vars/user-vars.module.ts
  packages/twenty-server/src/engine/core-modules/user/user-vars/utils/__tests__/merge-user-vars.spec.ts
  packages/twenty-server/src/engine/core-modules/user/user-vars/utils/merge-user-vars.util.ts
  packages/twenty-server/src/engine/core-modules/user/user.module.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/connected-account/connected-account.module.ts
  packages/twenty-server/src/modules/connected-account/listeners/connected-account.listener.ts
  packages/twenty-server/src/modules/connected-account/services/accounts-to-reconnect.service.ts
  packages/twenty-server/src/modules/connected-account/types/connected-account-key-value.type.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/common/services/messaging-channel-sync-status.service.ts
  packages/twenty-server/src/modules/modules.module.ts
  packages/twenty-ui/src/display/banner/components/Banner.tsx
  packages/twenty-ui/src/display/banner/components/__stories__/Banner.stories.tsx
  packages/twenty-ui/src/display/index.ts
Labels: PR: awaiting author

#6422 fix #6127 updated support button
  packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx
  packages/twenty-front/src/modules/support/components/SupportButton.tsx
  packages/twenty-front/src/modules/support/components/SupportButtonSkeletonLoader.tsx
  packages/twenty-front/src/modules/support/components/SupportDropdown.tsx
  packages/twenty-front/src/modules/support/components/__stories__/SupportButton.stories.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: PR: awaiting author

#6415 Update UI to Match Figma Specs: Labels, Buttons, Gaps
  packages/twenty-front/src/modules/command-menu/components/CommandGroup.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
Labels: PR: awaiting author

#6433 fix timeline activity deleted field
  packages/twenty-front/src/modules/activities/timelineActivities/components/EventList.tsx
  packages/twenty-front/src/modules/activities/timelineActivities/utils/__tests__/filterOutInvalidTimelineActivities.test.ts
  packages/twenty-front/src/modules/activities/timelineActivities/utils/filterOutInvalidTimelineActivities.ts
Labels: PR: awaiting review

#6410 Migrate domainName field from text type to links type
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityTargetObjectRecords.test.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/companies/types/Company.ts
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/favorites/utils/mapFavorites.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapFieldMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapObjectMetadataToGraphQLQuery.test.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getAvatarUrl.ts
  packages/twenty-front/src/modules/object-metadata/utils/getCompanyDomainName.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemsMock.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/relationFromManyFieldDisplayMock.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/__tests__/useOpenObjectRecordsSpreasheetImportDialog.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/util/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockColumnDefinitions.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockCompanies.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockFilterDefinitions.ts
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/testing/mock-data/activities.ts
  packages/twenty-front/src/testing/mock-data/companies.ts
  packages/twenty-front/src/testing/mock-data/generated/standard-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-domain-to-links.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts
  packages/twenty-server/src/engine/core-modules/quick-actions/quick-actions.service.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-field.decorator.ts
  packages/twenty-server/src/engine/workspace-manager/demo-objects-prefill-data/company.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/company.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/modules/company/repositories/company.repository.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/contact-creation-manager/contact-creation-manager.module.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company.service.ts
  packages/twenty-server/src/modules/view/services/view.service.ts
  packages/twenty-server/src/utils/getCompanyDomainName.ts
Labels: PR: awaiting review

#6439 6431 create new field activationStatus inside workspace table
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsLoadEffect.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectNamePluralFromSingular.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useObjectNameSingularFromPlural.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexTable.ts
  packages/twenty-front/src/modules/workspace/hooks/__tests__/useSubscriptionStatus.test.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-set-workspace-activation-status.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm/core/migrations/1722256203539-addActivationStatus.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: PR: awaiting review

#6463 Fix background mock
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockColumnDefinitions.ts
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockCompanies.ts
Labels: PR: awaiting review

#6462 Fix total count in show page
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts
Labels: PR: awaiting author

#6327 Add description for Developers/webhook page
  packages/twenty-front/src/modules/settings/developers/types/webhook/Webhook.ts
  packages/twenty-front/src/pages/settings/developers/__stories__/webhooks/SettingsDevelopersWebhooksDetail.stories.tsx
  packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhookDetail.tsx
  packages/twenty-server/src/engine/core-modules/open-api/utils/computeWebhooks.utils.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
Labels: PR: awaiting author

#6458 Add workflow runner
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/settings/serverless-functions/components/SettingsServerlessFunctionsOutputMetadataInfo.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTabEffect.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/mutations/executeOneServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/states/settingsServerlessFunctionOutputState.ts
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-server/src/engine/core-modules/workflow/dtos/workflow-trigger-result.dto.ts
  packages/twenty-server/src/engine/core-modules/workflow/utils/workflow-trigger-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/workflow/workflow-trigger.module.ts
  packages/twenty-server/src/engine/core-modules/workflow/workflow-trigger.resolver.ts
  packages/twenty-server/src/engine/integrations/message-queue/message-queue.constants.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/interfaces/serverless-driver.interface.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/lambda.driver.ts
  packages/twenty-server/src/engine/integrations/serverless/drivers/local.driver.ts
  packages/twenty-server/src/engine/integrations/serverless/serverless.service.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function-execution-result.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.module.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/activity/standard-objects/activity-target.workspace-entity.ts
  packages/twenty-server/src/modules/attachment/standard-objects/attachment.workspace-entity.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/modules.module.ts
  packages/twenty-server/src/modules/timeline/standard-objects/timeline-activity.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-event-listener.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-version.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-action.type.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-settings.type.ts
  packages/twenty-server/src/modules/workflow/common/types/workflow-trigger.type.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.module.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.services.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workflow-trigger.service.ts
  packages/twenty-server/src/modules/workflow/workflow.module.ts
Labels: PR: wip, PR: awaiting author
