Repository twentyhq/twenty, pull requests merged in 2025-08, with the labels that each got.

#13363 [admin-panel] - add scroll restoration and filter persistence on config variables
  packages/twenty-front/src/modules/settings/admin-panel/config-variables/components/SettingsAdminConfigVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/config-variables/states/configVariableGroupFilterState.ts
  packages/twenty-front/src/modules/settings/admin-panel/config-variables/states/configVariableSourceFilterState.ts
  packages/twenty-front/src/modules/settings/admin-panel/config-variables/states/showHiddenGroupVariablesState.ts
  packages/twenty-front/src/modules/settings/components/SettingsPageContainer.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/hooks/useScrollRestoration.ts
Labels: -PR: wip, -PR: awaiting author

#13053 [POC] multi select drag and drop on record board
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/useBoardCardDragState.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useEndBoardCardDrag.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useMultiDragState.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardDragOperations.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useStartBoardCardDrag.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardDraggableContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardMultiDragPreview.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/states/draggedRecordIdsComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/isMultiDragActiveComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/originalSelectionComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/primaryDraggedRecordIdComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/types/DragOperationType.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/__tests__/calculateRecordPositions.test.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/__tests__/getDragOperationType.test.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/__tests__/processMultiDrag.test.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/__tests__/processSingleDrag.test.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/calculateRecordPositions.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/getDragOperationType.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/processMultiDrag.ts
  packages/twenty-front/src/modules/object-record/record-board/utils/processSingleDrag.ts
  packages/twenty-ui/src/navigation/index.ts
  packages/twenty-ui/src/navigation/notification-counter/components/NotificationCounter.tsx
Labels: -PR: awaiting review

#13496 AI settings tab
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/ai/graphql/fragments/agentFragment.ts
  packages/twenty-front/src/modules/ai/graphql/mutations/createAgentHandoff.ts
  packages/twenty-front/src/modules/ai/graphql/mutations/createOneAgent.ts
  packages/twenty-front/src/modules/ai/graphql/mutations/deleteOneAgent.ts
  packages/twenty-front/src/modules/ai/graphql/mutations/removeAgentHandoff.ts
  packages/twenty-front/src/modules/ai/graphql/mutations/updateOneAgent.ts
  packages/twenty-front/src/modules/ai/graphql/queries/findAgentHandoffTargets.ts
  packages/twenty-front/src/modules/ai/graphql/queries/findAgentHandoffs.ts
  packages/twenty-front/src/modules/ai/graphql/queries/findManyAgents.ts
  packages/twenty-front/src/modules/ai/graphql/queries/findOneAgent.ts
  packages/twenty-front/src/modules/ai/hooks/useAgentRoleAssignment.ts
  packages/twenty-front/src/modules/ai/hooks/useAgentUpdateFormState.ts
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/hooks/useSettingsNavigationItems.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/__stories__/NavigationDrawerItem.stories.tsx
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/components/WorkflowEditActionAiAgent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/constants/workflow-ai-agent-tabs.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/states/workflowAiAgentSelectedRoleState.ts
  packages/twenty-front/src/pages/settings/ai/SettingsAI.tsx
  packages/twenty-front/src/pages/settings/ai/SettingsAgentForm.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAIAgentTableRow.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAIAgentsTable.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAgentDeleteConfirmationModal.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAgentDetailSkeletonLoader.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAgentHandoffForm.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAgentHandoffSection.tsx
  packages/twenty-front/src/pages/settings/ai/components/SettingsAgentHandoffTable.tsx
  packages/twenty-front/src/pages/settings/ai/constants/SettingsAIAgentTableMetadata.ts
  packages/twenty-front/src/pages/settings/ai/forms/components/SettingsAIAgentForm.tsx
  packages/twenty-front/src/pages/settings/ai/hooks/useSettingsAgentFormState.ts
  packages/twenty-front/src/pages/settings/ai/validation-schemas/settingsAIAgentFormSchema.ts
  packages/twenty-server/src/engine/metadata-modules/agent-role/agent-role.module.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-execution.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-handoff-executor.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-handoff.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-tool.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.module.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/constants/agent-handoff-description.const.ts
  packages/twenty-server/src/engine/metadata-modules/agent/constants/agent-handoff-prompt.const.ts
  packages/twenty-server/src/engine/metadata-modules/agent/constants/agent-system-prompts.const.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/agent-handoff.dto.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/agent.dto.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/create-agent-handoff.input.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/create-agent.input.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/remove-agent-handoff.input.ts
  packages/twenty-server/src/engine/metadata-modules/agent/dtos/update-agent.input.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/ai-agent/ai-agent.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/ai-agent/types/workflow-ai-agent-action-input.type.ts
  packages/twenty-server/test/integration/graphql/suites/agent/agent.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/agent/utils/agent-tool-test-utils.ts
Labels: -PR: awaiting review

#13529 Fix `flatFieldMetadata` transpiler to fit real `cache` typing
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-relation-target-field-metadata.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-create-field-input-to-flat-field-and-its-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-field-metadata-entity-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-relation-create-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-cached-field-metadata-entity-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-object-metadata-item-with-field-maps-to-flat-object-metadata-without-fields.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-object-metadata-item-with-field-maps-to-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-object-metadata-maps-to-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/types/cached-field-metadata-entity.ts
  packages/twenty-server/src/engine/metadata-modules/types/field-metadata-map.ts
  packages/twenty-server/src/engine/metadata-modules/utils/get-field-metadata-entity-from-cached-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-cache/exceptions/workspace-metadata-cache.exception.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-cache/services/workspace-metadata-cache.service.ts
  packages/twenty-server/src/engine/utils/is-cached-field-metadata-of-type.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/from-object-metadata-entity-to-flat-object-metadata-without-fields.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-object-actions-builder.ts
  packages/twenty-shared/src/types/RelationAndMorphRelationFieldMetadataType.ts
  packages/twenty-shared/src/types/index.ts
Labels: -PR: awaiting review

#13560 Fix eventEmitter emitting when diff is empty
  packages/twenty-server/src/engine/workspace-event-emitter/workspace-event-emitter.ts
Labels: -PR: awaiting review

#13601 Fix seed workspace
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/constants/workflow-data-seeds.constants.ts
Labels: prio: high

#13608 Add snackbar on CSV exports
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/components/ExportMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/useRecordIndexExportRecords.ts
Labels: -PR: awaiting review

#13590 `FlatObjectMetadataMaps` and non FP style refactor
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-create-field-input-to-flat-field-and-its-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-relation-create-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/merge-flat-field-metadatas-in-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/types/flat-object-metadata-maps.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/types/flat-object-metadata-with-flat-field-metadata-maps.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/from-flat-field-metadata-to-flat-field-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/from-flat-object-metadata-to-flat-object-metadata-with-flat-field-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/dispatch-and-merge-flat-field-metadatas-in-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-flat-object-metadata-with-flat-field-maps-to-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-object-metadata-maps-to-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-cache/services/workspace-metadata-cache.service.ts
  packages/twenty-shared/src/utils/fromArrayToValuesByKeyRecord.util.ts
  packages/twenty-shared/src/utils/index.ts
Labels: -PR: awaiting author

#13524 Field permission CRUD front-end implementation
  packages/twenty-front/jest.config.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/object-metadata/utils/filterUserFacingFieldMetadataItems.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/graphql/fragments/fieldPermissionFragment.ts
  packages/twenty-front/src/modules/settings/roles/graphql/mutations/upsertFieldPermissionsMutation.ts
  packages/twenty-front/src/modules/settings/roles/graphql/queries/getRolesQuery.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelObjectPicker.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelOverrideCell.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelOverrideCellContainer.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSeeFieldsValueForObject.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelUpdateFieldsValueForObject.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/constants/ObjectLevelPermissionTableGridAutoColumns.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTable.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableAllHeaderRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/constants/FieldLevelPermissionTableGridTemplateColumns.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/tests/useGetObjectPermissionDerivedStates.test.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useGetObjectPermissionDerivedStates.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useObjectPermissionDerivedStates.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useRemoveFieldPermissionInDraftRole.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useRemoveReadOverrideOnAllFieldsOfObject.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useRemoveUpdateOverrideOnAllFieldsOfObject.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useRestrictReadOnAllFieldsOfObject.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useRestrictUpdateOnAllFieldsOfObject.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useUpsertFieldPermissionInDraftRole.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/utils/getRoleWithRemovedFieldPermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/utils/getRoleWithUpsertedFieldPermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/utils/tests/getRoleWithRemovedFieldPermission.spec.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/utils/tests/getRoleWithUpsertedFieldPermission.spec.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/getRoleWithUpsertedObjectPermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useFilterObjectWithPermissionOverride.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useObjectMetadataItemsThatCanHavePermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermissionInDraftRole.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/SettingsRolePermissionsObjectLevelObjectForm.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/SettingsRolePermissionsObjectLevelObjectFormObjectLevel.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/SettingsRolePermissionsObjectLevelObjectFormObjectLevelTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/utils/hasPermissionOverride.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/types/SettingsRolePermissionsObjectPermission.ts
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRole.tsx
  packages/twenty-front/src/modules/settings/roles/role/hooks/useSaveDraftRoleToDB.ts
  packages/twenty-front/src/modules/settings/roles/states/settingsDraftRoleFamilyState.ts
  packages/twenty-front/src/modules/ui/layout/table/components/SortableTableHeader.tsx
  packages/twenty-front/src/modules/ui/layout/table/components/TableHeader.tsx
  packages/twenty-front/src/modules/ui/layout/table/components/TableHeaderText.tsx
  packages/twenty-front/src/testing/mock-data/roles/roles-mock.ts
  packages/twenty-front/src/utils/__tests__/turnOrderByIntoSort.test.ts
  packages/twenty-front/src/utils/turnOrderByIntoSort.ts
  packages/twenty-server/src/engine/metadata-modules/object-permission/field-permission/__tests__/field-permissions.service.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-permission/field-permission/field-permission.service.ts
  packages/twenty-server/src/engine/metadata-modules/role/dtos/role.dto.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.service.ts
Labels: -PR: awaiting review

#13604 Handle types that are not field metadata
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/filter/utils/__tests__/evaluate-filter-conditions.util.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/filter/utils/evaluate-filter-conditions.util.ts
Labels: -PR: awaiting author

#13594 Add ADD NEW cta as the last row
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableAddNew.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
Labels: -PR: awaiting review

#13686 [Need metadatada sync] - add user email unique on workspace member
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#13719 Refactor `FieldMetadataService` and validation to consume `FlatObjectMetadataMaps`
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-relation-flat-field-metadata.validator.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/__tests__/utils/expect-flat-field-metadata-to-be-in-flat-object-metadata-maps.util.test.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/__snapshots__/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps-or-throw.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/add-flat-field-metadata-in-flat-object-metadata-maps.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/add-flat-object-metadata-to-flat-object-metadata-maps-or-throw.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps-or-throw.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/find-flat-object-metadata-in-flat-object-metadata-maps.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/add-flat-field-metadata-in-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/add-flat-field-metadata-in-flat-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/add-flat-field-metadata-to-flat-object-metadata-with-flat-field-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/add-flat-object-metadata-with-field-maps-to-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-flat-object-metadata-maps-to-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-flat-object-metadata-to-flat-object-metadata-with-flat-field-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-object-metadata-maps-to-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
Labels: -PR: awaiting review

#13720 fix rest api metadata
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/utils/fetch-metadata-fields.utils.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/utils/has-select-all-fields-selector.util.ts
  packages/twenty-server/src/engine/api/rest/metadata/rest-api-metadata.service.ts
Labels: -PR: awaiting review

#13746 Improve messaging behavior
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/google/services/google-api-refresh-access-token.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/microsoft/services/microsoft-api-refresh-tokens.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/services/connected-account-refresh-tokens.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-account-authentication.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message-list-fetch.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
Labels: -PR: awaiting review

#13761 Import - Unique value check optimization
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerCreateRecordsOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/hooks/useBatchCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/__tests__/spreadsheetImportGetUnicityTableHook.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/spreadsheetImportGetUnicityTableHook.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
Labels: -PR: awaiting review

#13774 Multiple errors on field input transpilation improvement
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-relation-creation-payload-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/field-input-transpilation-result.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-create-field-input-to-flat-field-metadatas-to-create.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-relation-create-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/throw-on-field-input-transpilations-error.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/__snapshots__/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps-or-throw.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/__snapshots__/get-sub-flat-object-metadata-maps-or-throw.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/get-sub-flat-object-metadata-maps-or-throw.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/__tests__/get-sub-flat-object-metadata-maps.spec.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/extract-flat-object-metadata-maps-out-of-flat-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/get-sub-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/get-sub-flat-object-metadata-maps.util.ts
Labels: -PR: awaiting review

#13592 Unique fields - add unicity toggle on data model settings
  packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIsUniqueForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/components/SettingsDataModelFieldDateSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/phones/components/SettingsDataModelFieldPhonesSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/utils/canBeUnique.util.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getPhonesFieldPreviewValue.ts
  packages/twenty-front/src/modules/ui/field/display/components/PhonesDisplay.tsx
  packages/twenty-server/src/engine/metadata-modules/index-metadata/utils/__tests__/validate-can-create-unique-index.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/utils/validate-can-create-unique-index.util.ts
Labels: -PR: awaiting author

#13745 Add destroy for core view resolvers
  packages/twenty-server/src/engine/core-modules/view/controllers/view-field.controller.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view-filter-group.controller.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view-filter.controller.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view-group.controller.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view-sort.controller.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view.controller.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-field.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-filter-group.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-filter.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-group.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-sort.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-field.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-filter-group.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-filter.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-group.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-sort.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-field.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-filter-group.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-filter.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-group.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-sort.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view.service.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-field-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-filter-group-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-filter-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-group-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-sort-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-field-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-filter-group-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-filter-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-group-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-view-sort-operation-factory.util.ts
Labels: -PR: awaiting review

#13835 chore: scope package.json deps to packages
  package.json
  packages/twenty-front/.storybook/main.ts
  packages/twenty-front/package.json
  packages/twenty-server/package.json
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/remove-empty-links.ts
  packages/twenty-ui/.storybook/main.ts
  packages/twenty-website/package.json
  yarn.lock
Labels: -PR: wip, run-e2e

#13831 Add positions on company and person seeds
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/constants/company-data-seeds.constant.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/constants/person-data-seeds.constant.ts
Labels: -PR: awaiting review

#13784 `FieldMetadataServiceV2.updateOne`
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-standard-overrides.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-type-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/compare-two-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-update-field-input-to-flat-field-metadata-to-update.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-flat-field-metadata-name-availability.validator.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-or-throw.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name.utils.ts
Labels: -PR: awaiting review

#13847 fix IMAP breadcrumb
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectionForm.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEditImapSmtpCaldavConnection.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsNewImapSmtpCaldavConnection.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/hooks/useSettingsNavigationItems.tsx
Labels: -PR: awaiting review

#13853 Run yarn dedupe and upgrade TS
  .vscode/settings.json
  package.json
  packages/twenty-front/src/emotion.d.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx
  packages/twenty-server/package.json
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/utils/get-field-arguments-by-key.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/input-type-definition.factory.ts
  packages/twenty-server/src/engine/api/rest/utils/clean-graphql-response.utils.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/services/file-upload.service.ts
  packages/twenty-server/src/engine/core-modules/tool/tools/send-email-tool/send-email-tool.ts
  packages/twenty-server/tsconfig.json
  packages/twenty-ui/tsconfig.dev.json
  packages/twenty-ui/tsconfig.storybook.json
  tsconfig.base.json
  yarn.lock
Labels: -PR: awaiting author

#13889 Only allow deleting branches when branches are enabled
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramDefaultEdgeEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramFilterEdgeEditable.tsx
Labels: -PR: ready to merge

#13897 Allow deleting any branch via keyboard
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowRunOpeningInCommandMenuSideEffects.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/transformFilterNodesAsEdges.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowVersionDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/transformFilterNodesAsEdges.ts
Labels: -PR: awaiting review

#13909 Implement proper arrows between nodes for workflows and workflow versions
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCustomMarkers.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramBaseEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeBranchArrowMarkerId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeGrayCircleMarkedId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeDefaultConfiguration.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
Labels: -PR: awaiting review

#13891 `ObjectMetadataServiceV2.updateOne`
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsUpdateDataModelObjectAboutForm.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/constants/field-metadata-standard-overrides-properties.constant.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-standard-overrides.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/types/field-metadata-standard-overrides-properties.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/constants/flat-field-metadata-jsonb-properties.constant.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/constants/flat-field-metadata-properties-to-compare.constant.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/constants/flat-field-metadata-relation-properties-to-compare.constant.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-type-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata-jsonb-properties.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata-properties-to-compare.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata-relation-properties-to-compare.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/compare-two-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-update-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-flat-field-metadata-name-synced-with-label.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-enum-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-flat-field-metadata-name-availability.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-flat-field-metadata-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-relation-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/constants/flat-object-metadata-jsonb-properties.constant.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/constants/flat-object-metadata-properties-to-compare.constant.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/services/flat-object-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/types/flat-object-metadata-jsonb-properties.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/types/flat-object-metadata-properties-to-compare.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/are-flat-object-metadata-names-synced-with-labels.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/compare-two-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-update-object-input-to-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/validators/utils/validate-flat-object-metadata-identifiers.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/validators/utils/validate-flat-object-metadata-label.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/validators/utils/validate-flat-object-metadata-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/constants/object-metadata-standard-overrides-properties.constant.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/types/object-metadata-standard-overrides-properties.types.ts
  packages/twenty-server/src/engine/metadata-modules/utils/is-standard-metadata.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/__snapshots__/workspace-migration-builder.spec.ts.snap
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-field-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-object-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/types/workspace-migration-field-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/types/workspace-migration-object-action-v2.ts
Labels: -PR: awaiting review

#13709 [fast follows] - improve rest api documentation, fix add new button being considered in drag, fix grip color
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableAddNew.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellGrip.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionAddNew.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionLoadMore.tsx
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
Labels: -PR: awaiting review

#13899 Workspace schema migration runner v2
  packages/twenty-server/src/engine/metadata-modules/field-metadata/types/composite-field-metadata-type.type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/types/enum-field-metadata-type.type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/types/relation-field-metadata-type.type.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/get-composite-type-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/unserialize-default-value.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-composite-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-enum-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-falt-field-metadata-of-types.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-relation-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/find-flat-field-metadata-in-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/find-flat-object-metadata-in-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/find-flat-object-metadata-in-flat-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/find-flat-object-metadata-with-flat-field-maps-in-flat-object-metadata-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/find-flat-object-metadata-with-flat-field-maps-in-flat-object-metadata-maps.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/composite-column-action.factory.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/__tests__/workspace-schema-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/exceptions/workspace-schema-manager.exception.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/__tests__/workspace-schema-column-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/__tests__/workspace-schema-enum-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/__tests__/workspace-schema-foreign-key-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/__tests__/workspace-schema-index-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/__tests__/workspace-schema-table-manager.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-column-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-enum-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-foreign-key-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-index-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-table-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/types/workspace-schema-column-definition.type.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/utils/build-sql-column-definition.util.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/utils/sanitize-default-value.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/types/workspace-migration-action-runner-args.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-metadata-migration-runner/workspace-metadata-migration-runner-service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-metadata-migration-runner/workspace-metadata-object-action-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-migration-runner-v2.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/__tests__/workspace-schema-field-action-runner.service.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/__tests__/workspace-schema-object-action-runner.service.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/exceptions/workspace-schema-migration.exception.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/__tests__/generate-column-definitions.util.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/__tests__/workspace-schema-enum-operations.util.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/generate-column-definitions.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/get-workspace-schema-context-for-migration.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/workspace-schema-context.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/utils/workspace-schema-enum-operations.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-field-action-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-index-action-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-object-action-runner.service.ts
Labels: -PR: awaiting review

#13972 Fix website navigation
  packages/twenty-website/src/content/user-guide/collaboration.mdx
  packages/twenty-website/src/content/user-guide/constants/UserGuideIndex.ts
  packages/twenty-website/src/content/user-guide/objects.mdx
  packages/twenty-website/src/content/user-guide/settings.mdx
  packages/twenty-website/src/content/user-guide/views.mdx
Labels: -PR: awaiting review

#13948 fix(design-system): fix menu item selection & focus state (#13807)
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemSelect.tsx
  packages/twenty-ui/src/navigation/menu-item/components/__stories__/MenuItemSelect.stories.tsx
Labels: -PR: awaiting CI

#13946 fix: remove unnecessary spacing in search node's conditional operator field
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterLogicalOperatorDropdown.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/filter-action/components/WorkflowStepFilterLogicalOperatorCell.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/find-records-action/components/WorkflowAdvancedFilterLogicalOperatorCell.tsx
Labels: -PR: awaiting review

#13973 IMAP FIxes
  packages/twenty-server/@types/planer.d.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/parse-and-format-gmail-message.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/messaging-imap-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/services/imap-find-sent-folder.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/services/imap-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/services/imap-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/services/imap-message-locator.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/services/imap-message-processor.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/utils/__tests__/extract-message-text.util.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/utils/extract-message-text.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/imap/utils/find-sent-mailbox.util.ts
Labels: -PR: awaiting author

#13977 Fix enum deletion during migration v2
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/utils/build-sql-column-definition.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-migration-runner-v2.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-object-action-runner.service.ts
Labels: -PR: awaiting review

#13984 [Dashboards] Graph number chart component
  packages/twenty-front/src/modules/dashboards/graphs/components/GraphWidgetNumberChart.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/__stories__/GraphWidgetNumberChart.stories.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/index.ts
Labels: -PR: awaiting CI

#13945 fix: workflow node classification
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/WorkflowActionMenuItems.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/trigger-type/components/CommandMenuWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-nodes/components/WorkflowDiagramStepNodeIcon.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/AiActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/CoreActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/HumanInputActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/__tests__/useFilteredOtherActions.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/useFilteredOtherActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/__tests__/getActionIcon.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/__tests__/getActionIconColorOrThrow.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionIconColorOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerCronForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerDatabaseEventForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerManualForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerWebhookForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getTriggerIconColor.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerIconColor.ts
Labels: -PR: awaiting review

#13912 Perform renaming fixes and implement full access card
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsTableHeader.tsx
Labels: -PR: awaiting review

#14007 fix: prevent selection clicking outside the table
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldDataType.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableRow.tsx
Labels: -PR: awaiting review

#14035 [Dashboards] Graph gauge chart component
  packages/twenty-front/package.json
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/dashboards/graphs/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/__stories__/GraphWidgetGaugeChart.stories.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerMetricsTooltip.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-worker-queue-health.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/queue-metrics-series.dto.ts
  yarn.lock
Labels: -PR: awaiting review

#14033 fix(ai): MCPCore findRecord tool
  packages/twenty-server/src/engine/core-modules/ai/ai.module.ts
  packages/twenty-server/src/engine/core-modules/ai/services/__tests__/ai-billing.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/__tests__/mcp.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/__tests__/tool-adapter.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/__tests__/tool.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/tool.service.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/__tests__/find-records-filters.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/find-records-filters.utils.ts
  packages/twenty-server/test/integration/metadata/suites/agent/utils/agent-tool-test-utils.ts
Labels: -PR: awaiting review

#14014 Add separated types + build a search for records
  packages/twenty-front/src/modules/object-record/record-field/ui/form-types/components/VariableChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/hooks/useSearchVariable.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/types/RecordOutputSchemaV2.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/__tests__/searchVariableThroughRecordEventOutputSchema.test.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/__tests__/searchVariableThroughRecordOutputSchema.test.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/getOutputSchemaType.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/isRecordOutputSchemaV2.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/searchVariableThroughOutputSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/searchVariableThroughRecordEventOutputSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/searchVariableThroughRecordOutputSchema.ts
Labels: -PR: awaiting author

#14034 Add coreView state in FE
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchIndexViewIdFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewFromViewIdFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewLengthFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/views/components/__stories__/ViewBarFilterDropdown.stories.tsx
  packages/twenty-front/src/modules/views/graphql/fragments/viewFragment.ts
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFilterGroupsToCurrentRecordFilterGroups.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewSortsToCurrentRecordSorts.test.tsx
  packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useMapViewFiltersToFilters.ts
  packages/twenty-front/src/modules/views/states/coreViewState.ts
  packages/twenty-front/src/modules/views/utils/mapViewFiltersToFilters.ts
  packages/twenty-front/src/modules/views/view-picker/hooks/useCreateViewFromCurrentState.ts
  packages/twenty-front/src/testing/mock-data/views.ts
  packages/twenty-ui/package.json
Labels: -PR: awaiting author

#14068 Create related records after object creation with migration v2 (view, view filters, favorite)
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-related-records.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-view-field.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-view.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/__snapshots__/workspace-migration-builder.spec.ts.snap
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-object-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/builders/field/services/workspace-migration-v2-field-actions-builder.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/builders/index/workspace-migration-v2-index-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/builders/object/services/workspace-migration-v2-object-actions-builder.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/builders/view/workspace-migration-v2-view-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/services/workspace-migration-builder-v2.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/types/workspace-migration-action-common-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/types/workspace-migration-view-action-v2.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/object/services/create-object-action-handler.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/view/services/create-view-action-handler.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/workspace-schema-migration-runner-action-handlers.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/utils/apply-workspace-migration-action-on-flat-object-metadata-maps.ts
Labels: -PR: wip, -PR: awaiting author

#14086 Remove view FK on workspace favorite entity
  packages/twenty-server/src/database/commands/upgrade-version-command/1-5/1-5-remove-favorite-view-relation.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/1-5/1-5-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
Labels: -PR: awaiting review

#14084 Add missing FK on view tables
  packages/twenty-server/src/database/commands/views-migration/migrate-views-to-core.command.ts
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756209145695-addMissingFkOnViewTables.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view-field.controller.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-field.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-filter-group.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-filter.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-group.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-sort.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view.entity.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view-field.resolver.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-field.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-filter-group.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-filter.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-group.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view-sort.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/tests/view.service.spec.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-field.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-filter-group.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-filter.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-group.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view-sort.service.ts
  packages/twenty-server/src/engine/core-modules/view/services/view.service.ts
  packages/twenty-server/src/engine/core-modules/view/view.module.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/prefill-core-views.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-view-field.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-view.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/view/services/create-view-action-handler.service.ts
  packages/twenty-server/src/modules/view/services/view-field-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-filter-group-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-filter-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-group-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-sort-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-sync.service.ts
  packages/twenty-server/src/modules/view/view.module.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-field-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-filter-group-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-filter-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-group-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/view/view-sort-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-field-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-filter-group-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-filter-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-group-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/create-view-sort-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/view-data-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/view-graphql.util.ts
  packages/twenty-server/test/integration/rest/suites/view-field.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/view-filter-group.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/view-filter.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/view-group.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/view-sort.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/view.integration-spec.ts
  packages/twenty-server/test/integration/rest/utils/view-rest-api.util.ts
  packages/twenty-server/test/integration/utils/view-test.util.ts
Labels: -PR: awaiting review

#14099 Create PageLayoutEntity
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756289507594-createPageLayoutEntity.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/page-layout/entities/page-layout.entity.ts
  packages/twenty-server/src/engine/core-modules/page-layout/enums/page-layout-type.enum.ts
  packages/twenty-server/src/engine/core-modules/page-layout/page-layout.module.ts
Labels: -PR: awaiting review

#14106 Create PageLayoutWidgetEntity
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756302117195-createPageWidgetLayoutEntity.ts
  packages/twenty-server/src/engine/core-modules/page-layout/entities/page-layout-tab.entity.ts
  packages/twenty-server/src/engine/core-modules/page-layout/entities/page-layout-widget.entity.ts
  packages/twenty-server/src/engine/core-modules/page-layout/enums/widget-type.enum.ts
  packages/twenty-server/src/engine/core-modules/page-layout/page-layout.module.ts
  packages/twenty-server/src/engine/core-modules/page-layout/types/grid-position.type.ts
Labels: -PR: awaiting review

#14112 Create Dashboard Workspace Entity
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/prefill-core-views.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/prefill-views.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/standard-objects-prefill-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/dashboards-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-icons.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/dashboard/standard-objects/dashboard.workspace-entity.ts
Labels: -PR: awaiting review

#14139 Add universal identifier to view tables
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756393721720-addUniversalIdentifierToViewTables.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-field.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-filter-group.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-filter.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-group.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view-sort.entity.ts
  packages/twenty-server/src/engine/core-modules/view/entities/view.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync/interfaces/syncable-entity.interface.ts
Labels: -PR: awaiting author

#14141 Morph relation validation v2
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__tests__/__snapshots__/morph-relation-from-create-field-input-to-flat-field-metadatas-to-create.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-type-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-morph-relation-create-field-input-to-flat-field-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-enum-validate-one-field-metadata-args.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-morph-relation-creation-payload.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-relation-or-morph-relation-flat-field-metadata.util.ts
Labels: -PR: awaiting author

#14052 [Dashboards] Graph bar chart component
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/dashboards/graphs/components/GraphWidgetBarChart.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/GraphWidgetPieChart.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/__stories__/GraphWidgetBarChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/__stories__/GraphWidgetGaugeChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/graphs/components/__stories__/GraphWidgetPieChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/graphs/types/GraphColor.ts
  packages/twenty-front/src/modules/dashboards/graphs/utils/createGradientDef.ts
  packages/twenty-front/src/modules/dashboards/graphs/utils/getColorScheme.ts
  yarn.lock
Labels: -PR: awaiting review

#14113 Morph-picker-MultiSelect-picker
  packages/twenty-front/src/modules/object-metadata/hooks/useDoObjectMetadataItemsExist.ts
  packages/twenty-front/src/modules/object-metadata/states/objectMetadataItemsBySingularNameSelector.ts
  packages/twenty-front/src/modules/object-record/hooks/useAttachMorphRelatedRecordFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDetachMorphRelatedRecordFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordSearchRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateMultipleRecordsFromManyObjects.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/generateUpdateOneRecordMutation.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/getTargetFieldMetadataName.ts
  packages/twenty-front/src/modules/object-record/record-field/ui/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/ui/hooks/useOpenFieldInputEditMode.ts
  packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/hooks/useMorphRelationField.ts
  packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/input/components/MorphRelationOneToManyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/input/hooks/useOpenMorphRelationFromManyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/input/hooks/useUpdateMorphRelationManyToOneFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItemsWithSearch.tsx
  packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/hooks/useSingleRecordPickerRecords.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchRecordQuery.test.tsx
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchRecordQuery.ts
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentWorkspaceMemberPickerDropdown.tsx
Labels: -PR: awaiting author

#14148 Compute Filter DisplayValue at runtime on FE
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/components/EditableRelationFilterChip.tsx
  packages/twenty-front/src/modules/views/components/SortOrFilterChip.tsx
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFieldRecords.ts
  packages/twenty-front/src/modules/views/hooks/useComputeRecordRelationFilterLabelValue.tsx
  packages/twenty-ui/package.json
  packages/twenty-ui/scripts/generateBarrels.ts
Labels: -PR: awaiting review

#14153 Update object handle morph join col rename
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/types/field-metadata-entity-test.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/compare-two-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-flat-field-metadatas-related-to-morph-relation-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-relation-flat-field-metadatas-target-flat-field-metadata-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-relation-flat-field-metadatas-target-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-update-object-input-to-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/get-flat-object-metadata-many-to-one-target-morph-relation-flat-field-metadatas-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/rename-flat-object-metadata-morph-relation-flat-field-metadatas-settings-join-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
Labels: -PR: awaiting review

#14132 feat(billing): improve billing page - milestone 3
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/billing/components/SettingsBillingSubscriptionInfo.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/index.ts
Labels: -PR: wip, -PR: awaiting author

#14166 Core view migration fixes
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useSetViewTypeFromLayoutOptionsMenu.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupReorderConfirmationModal.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useReorderRecordGroups.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
  packages/twenty-front/src/modules/views/hooks/useDeleteView.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateCurrentView.ts
Labels: -PR: awaiting review

#14188 Fix workspace deletion broken
  packages/twenty-front/src/modules/settings/components/SettingsProtectedRouteWrapper.tsx
  packages/twenty-server/src/engine/workspace-datasource/workspace-datasource.service.ts
Labels: -PR: awaiting review
