Repository twentyhq/twenty, pull requests merged in 2025-09, with the labels that each got.

#14189 Remove old view implementation step 1
  packages/twenty-front/src/modules/favorites/hooks/__tests__/useFavorites.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/useFavoritesByFolder.ts
  packages/twenty-front/src/modules/favorites/hooks/useSortedFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts
  packages/twenty-front/src/modules/favorites/states/selectors/favoriteViewsWithMinimalDataSelector.ts
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useDefaultHomePagePath.test.ts
  packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts
  packages/twenty-front/src/modules/navigation/hooks/useSetLastVisitedViewForObjectMetadataNamePlural.ts
  packages/twenty-front/src/modules/prefetch/components/PrefetchDataProvider.tsx
  packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx
  packages/twenty-front/src/modules/prefetch/states/arePrefetchViewsLoaded.ts
  packages/twenty-front/src/modules/prefetch/states/prefetchViewsState.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchIndexViewIdFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewFromViewIdFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewLengthFamilySelector.ts
  packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/views/components/__stories__/ViewBarFilterDropdown.stories.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFilterGroupsToCurrentRecordFilterGroups.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewSortsToCurrentRecordSorts.test.tsx
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFieldRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterGroupRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewSortRecords.ts
  packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useDeleteView.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateView.ts
Labels: -PR: awaiting review

#14195 Morph relation v2 schema runner
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/types/flat-field-metadata-property-update.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/field/services/update-field-action-handler.service.ts
Labels: -PR: awaiting review

#14223 Render `WorkflowActionMenuItems` as a proper component
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/WorkflowActionMenuItems.tsx
Labels: -PR: awaiting review

#14228 V2 integ test sequential operations testing
  packages/twenty-server/test/integration/metadata/suites/object-metadata/create-delete-and-create-object-metadata-v2.integration-spec.ts
Labels: -PR: awaiting review

#14208 fix - use createMany service in createOne one
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
Labels: -PR: awaiting review

#14248 Fix dataloader service not provided in core graphql config
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/engine/api/graphql/graphql-config/graphql-config.service.ts
Labels: -PR: awaiting review

#14207 Translations - FIX - views not being refreshed on locale change
  packages/twenty-front/src/modules/object-metadata/hooks/useUpdateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/views/components/UpdateViewButtonGroup.tsx
  packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useDeleteView.ts
  packages/twenty-front/src/modules/views/hooks/useRefreshAllCoreViews.ts
  packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateView.ts
  packages/twenty-front/src/pages/settings/profile/appearance/components/LocalePicker.tsx
Labels: -PR: awaiting review

#14203 fix - update error message and ease importable format for multi select
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/spreadsheetImportParseMultiSelectOptionsOrThrow.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/normalizeTableData.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/setColumn.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/spreadsheetImportParseMultiSelectOptionsOrThrow.ts
Labels: -PR: awaiting author

#14219 Create PageLayout resolver and controller
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756816245841-createPartialIndexForPageLayout.ts
  packages/twenty-server/src/engine/core-modules/page-layout/controllers/page-layout.controller.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/create-page-layout.input.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/update-page-layout.input.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/page-layout-tab.dto.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/page-layout.dto.ts
  packages/twenty-server/src/engine/core-modules/page-layout/entities/page-layout.entity.ts
  packages/twenty-server/src/engine/core-modules/page-layout/exceptions/page-layout.exception.ts
  packages/twenty-server/src/engine/core-modules/page-layout/filters/page-layout-rest-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/page-layout/page-layout.module.ts
  packages/twenty-server/src/engine/core-modules/page-layout/resolvers/page-layout.resolver.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/page-layout-tab.service.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/page-layout.service.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/tests/page-layout-tab.service.spec.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/tests/page-layout.service.spec.ts
  packages/twenty-server/src/engine/core-modules/page-layout/utils/page-layout-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/page-layout/utils/page-layout-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view.controller.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view.resolver.ts
  packages/twenty-server/test/integration/constants/page-layout-gql-fields.constants.ts
  packages/twenty-server/test/integration/constants/test-page-layout-ids.constants.ts
  packages/twenty-server/test/integration/graphql/suites/page-layout/page-layout-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/create-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/delete-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/find-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/find-page-layouts-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/page-layout-graphql.util.ts
  packages/twenty-server/test/integration/graphql/utils/restore-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/update-page-layout-operation-factory.util.ts
  packages/twenty-server/test/integration/rest/suites/page-layout.integration-spec.ts
  packages/twenty-server/test/integration/rest/utils/page-layout-rest-api.util.ts
  packages/twenty-server/test/integration/utils/page-layout-test.util.ts
Labels: -PR: awaiting review

#14261 Clean step and edge errors
  packages/twenty-server/src/engine/core-modules/workflow/filters/workflow-version-edge-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/workflow/filters/workflow-version-step-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-edge.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/modules/workflow/common/exceptions/workflow-version-edge.exception.ts
  packages/twenty-server/src/modules/workflow/common/exceptions/workflow-version-step.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version-step/workflow-version-step.workspace-service.ts
Labels: -PR: awaiting review

#14253 Failing morph relation creation v2 integration testing & fixes
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/attachment-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/company-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/favorite-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/favorite-folder-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/get-morph-or-relation-target-flat-field-metadata-mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/note-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/notetarget-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/opportunity-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/person-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/pet-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/rocket-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/task-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/tasktarget-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/timelineactivity-flat-fields.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/compute-flat-field-metadata-related-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-flat-field-metadatas-related-to-morph-relation-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-relation-flat-field-metadatas-target-flat-field-metadata-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-morph-relation-create-field-input-to-flat-field-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-composite-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-enum-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-flat-field-metadata-jsonb-property.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-flat-field-metadata-of-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-flat-field-metadata-of-types.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-morph-or-relation-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-flat-field-metadata-name-availability.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/utils/validate-morph-relation-creation-payload.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/__tests__/utils/expect-flat-field-metadata-to-be-in-flat-object-metadata-maps.util.test.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata-maps/utils/add-flat-field-metadata-to-flat-object-metadata-with-flat-field-maps-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-cached-field-metadata-entity-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-delete-object-input-to-flat-field-metadatas-to-delete.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/get-flat-object-metadata-many-to-one-target-morph-relation-flat-field-metadatas-or-throw.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/__snapshots__/workspace-migration-builder.spec.ts.snap
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-field-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/utils/generate-column-definitions.util.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/__snapshots__/failing-create-one-field-metadata-morph-relation-v2.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/failing-create-one-field-metadata-morph-relation-v2.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/successful-create-one-field-metadata-morph-relation-v2.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/successful-update-one-field-metadata-morph-relation-v2.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/failing-create-one-object-metadata-v2.integration-spec.ts
  packages/twenty-server/test/utils/extract-record-ids-and-dates-as-expect-any.ts
Labels: -PR: awaiting review

#14277 Fix - ChipField display in settings data model
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreviewWidget.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelLabelIdentifierPreviewContextWrapper.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelSetLabelIdentifierRecordEffect.tsx
Labels: -PR: awaiting review

#14251 [Dashboards] - add iframe widget
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuPagesConfig.tsx
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutIframeConfig.tsx
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutWidgetTypeSelect.tsx
  packages/twenty-front/src/modules/command-menu/types/CommandMenuPages.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetBarChart.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetLegend.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetNumberChart.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetPieChart.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/GraphWidgetTooltip.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetBarChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetGaugeChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetLegend.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetNumberChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetPieChart.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/components/__stories__/GraphWidgetTooltip.stories.tsx
  packages/twenty-front/src/modules/dashboards/widgets/graph/types/GraphColor.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/types/GraphColorRegistry.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/types/GraphColorScheme.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/calculateAngularGradient.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/createGradientDef.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/createGraphColorRegistry.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/getColorScheme.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/getColorSchemeByIndex.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/getColorSchemeByName.ts
  packages/twenty-front/src/modules/dashboards/widgets/graph/utils/graphFormatters.ts
  packages/twenty-front/src/modules/dashboards/widgets/iframe/components/IframeWidget.tsx
  packages/twenty-front/src/modules/settings/page-layout/components/PageLayoutWidgetPlaceholder.tsx
  packages/twenty-front/src/modules/settings/page-layout/components/__stories__/PageLayoutWidgetPlaceholder.stories.tsx
  packages/twenty-front/src/modules/settings/page-layout/hooks/useCreatePageLayoutIframeWidget.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutWidgetUpdate.ts
  packages/twenty-front/src/modules/settings/page-layout/mocks/mockWidgets.ts
  packages/twenty-front/src/modules/settings/page-layout/states/pageLayoutEditingWidgetIdState.ts
  packages/twenty-front/src/modules/settings/page-layout/states/savedPageLayoutsState.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/graphRegistry.tsx
  packages/twenty-front/src/modules/settings/page-layout/utils/widgetRegistry.tsx
  packages/twenty-front/src/pages/settings/page-layout/SettingsPageLayoutEdit.tsx
Labels: -PR: awaiting review

#14287 Adapt field permissions to label identifier
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTable.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableRow.tsx
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.service.ts
Labels: -PR: ready to merge

#14315 Create PageLayoutWidget resolver and controller
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-server/src/engine/core-modules/page-layout/controllers/page-layout-widget.controller.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/create-page-layout-widget.input.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/grid-position.input.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/update-page-layout-widget.input.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/page-layout-tab.dto.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/page-layout-widget.dto.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/page-layout.dto.ts
  packages/twenty-server/src/engine/core-modules/page-layout/exceptions/page-layout-widget.exception.ts
  packages/twenty-server/src/engine/core-modules/page-layout/filters/page-layout-widget-rest-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/page-layout/page-layout.module.ts
  packages/twenty-server/src/engine/core-modules/page-layout/resolvers/page-layout-widget.resolver.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/page-layout-tab.service.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/page-layout-widget.service.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/tests/page-layout-tab.service.spec.ts
  packages/twenty-server/src/engine/core-modules/page-layout/services/tests/page-layout-widget.service.spec.ts
  packages/twenty-server/src/engine/core-modules/page-layout/utils/page-layout-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/page-layout/utils/page-layout-graphql-api-exception.filter.ts
  packages/twenty-server/test/integration/constants/page-layout-gql-fields.constants.ts
  packages/twenty-server/test/integration/constants/test-page-layout-widget-ids.constants.ts
  packages/twenty-server/test/integration/graphql/suites/page-layout/page-layout-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/page-layout/page-layout-tab-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/page-layout/page-layout-widget-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/create-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/delete-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/destroy-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/find-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/find-page-layout-widgets-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/graphql-test-assertions.util.ts
  packages/twenty-server/test/integration/graphql/utils/page-layout-widget-graphql.util.ts
  packages/twenty-server/test/integration/graphql/utils/restore-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/graphql/utils/update-page-layout-widget-operation-factory.util.ts
  packages/twenty-server/test/integration/rest/suites/page-layout-widget.integration-spec.ts
  packages/twenty-server/test/integration/rest/utils/page-layout-widget-rest-api.util.ts
  packages/twenty-server/test/integration/utils/page-layout-test.util.ts
  packages/twenty-server/test/integration/utils/page-layout-widget-test.util.ts
Labels: -PR: ready to merge

#14318 [Page Layouts] - Add tabs
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutIframeConfig.tsx
  packages/twenty-front/src/modules/settings/page-layout/components/PageLayoutInitializationEffect.tsx
  packages/twenty-front/src/modules/settings/page-layout/hooks/__tests__/usePageLayoutDraftState.test.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/__tests__/usePageLayoutHandleLayoutChange.test.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/__tests__/usePageLayoutTabCreate.test.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/__tests__/usePageLayoutWidgetCreate.test.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/useCreatePageLayoutIframeWidget.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutDraftState.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutHandleLayoutChange.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutSaveHandler.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutTabCreate.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutWidgetCreate.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutWidgetDelete.ts
  packages/twenty-front/src/modules/settings/page-layout/hooks/usePageLayoutWidgetUpdate.ts
  packages/twenty-front/src/modules/settings/page-layout/mocks/mockWidgets.ts
  packages/twenty-front/src/modules/settings/page-layout/states/pageLayoutCurrentLayoutsState.ts
  packages/twenty-front/src/modules/settings/page-layout/states/pageLayoutCurrentTabIdForCreation.ts
  packages/twenty-front/src/modules/settings/page-layout/states/pageLayoutDraftState.ts
  packages/twenty-front/src/modules/settings/page-layout/states/pageLayoutWidgetsState.ts
  packages/twenty-front/src/modules/settings/page-layout/states/savedPageLayoutsState.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/addWidgetToTab.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/convertLayoutsToWidgets.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/createEmptyTabLayout.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/createUpdatedTabLayouts.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/removeWidgetFromTab.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/__tests__/removeWidgetLayoutFromTab.test.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/addWidgetToTab.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/convertLayoutsToWidgets.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/createEmptyTabLayout.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/createUpdatedTabLayouts.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/graphRegistry.tsx
  packages/twenty-front/src/modules/settings/page-layout/utils/removeWidgetFromTab.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/removeWidgetLayoutFromTab.ts
  packages/twenty-front/src/modules/settings/page-layout/utils/widgetRegistry.tsx
  packages/twenty-front/src/modules/ui/layout/tab-list/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/tab-list/types/TabListProps.ts
  packages/twenty-front/src/modules/ui/layout/tab-list/utils/calculateVisibleTabCount.ts
  packages/twenty-front/src/pages/settings/page-layout/SettingsPageLayoutEdit.tsx
  packages/twenty-front/src/pages/settings/page-layout/SettingsPageLayouts.tsx
Labels: -PR: awaiting review

#14346 Refactored table body and footer with divs
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableStickyBottomEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableStickyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableStyles.tsx
  packages/twenty-front/src/modules/object-record/record-table/constants/TableZIndex.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDroppable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableNoRecordGroupBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooterCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderAddColumnButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCheckboxColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderDragDropColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableTr.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-shared/src/utils/array/filterOutByProperty.ts
  packages/twenty-shared/src/utils/array/findByProperty.ts
  packages/twenty-shared/src/utils/array/sumByProperty.ts
  packages/twenty-shared/src/utils/index.ts
Labels: -PR: awaiting author

#14355 Update open api with page layout
  packages/twenty-server/src/engine/core-modules/open-api/open-api.service.ts
Labels: -PR: awaiting review

#14299 Refactor morph field name and morph data loader
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapObjectMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/hooks/useAttachMorphRelatedRecordFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDetachMorphRelatedRecordFromRecord.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordTableRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/record-store/states/selectors/recordStoreMorphManyToOneValueWithObjectNameFamilySelector.ts
  packages/twenty-front/src/modules/object-record/record-store/states/selectors/recordStoreMorphOneToManyValueWithObjectNameFamilySelector.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelRelationFieldPreview.tsx
  packages/twenty-server/src/database/typeorm/core/migrations/common/1756976545860-unique-field-metadata-name-for-workspace-object-metadata.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-selected-fields/graphql-selected-fields.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/object-records-to-graphql-connection.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/build-columns-to-select.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/get-field-metadata-from-graphql-field.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/extend-object-type-definition-v2.factory.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.interface.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.service.ts
  packages/twenty-server/src/engine/dataloaders/utils/filter-morph-relation-duplicate-fields.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-morph-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/are-field-metadatas-of-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/are-field-metadatas-type-relation-or-morph-relation.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/compute-morph-or-relation-field-join-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/compute-morph-relation-field-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/resolve-field-metadata-standard-override.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__tests__/__snapshots__/morph-relation-from-create-field-input-to-flat-field-metadatas-to-create.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-all-others-morph-relation-flat-field-metadatas-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/find-flat-field-metadatas-related-to-morph-relation-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-flat-field-metadata-to-field-metadata-dto.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-morph-or-relation-flat-field-metadata-to-relation-dto.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-morph-relation-create-field-input-to-flat-field-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-relation-create-field-input-to-flat-field-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/generate-morph-or-relation-flat-field-metadata-pair.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-flat-object-metadata-to-object-metadata-dto.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-update-object-input-to-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/get-flat-object-metadata-many-to-one-target-morph-relation-flat-field-metadatas-or-throw.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/rename-flat-object-metadata-morph-relation-flat-field-metadatas-settings-join-column-name.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/rename-related-morph-field-on-object-names-update.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-field-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-version/services/workspace-metadata-version.service.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-relation.factory.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/metadata/custom-fields/constants/pet-custom-relation-field-seeds.constant.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/create-one-field-metadata-morph-relation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/create-one-field-metadata-relation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/morph-relation/rename-object-metadata-with-morph-relation-v2.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/create-morph-relation-between-objects.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/force-create-one-object-metadata.util.ts
  packages/twenty-shared/src/utils/fieldMetadata/compute-morph-relation-field-join-column-name.util.ts
  packages/twenty-shared/src/utils/fieldMetadata/compute-morph-relation-field-name.util.ts
  packages/twenty-shared/src/utils/index.ts
Labels: -PR: awaiting CI

#14357 Remove is branch enabled feature flag
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/trigger-type/components/CommandMenuWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowRunOpeningInCommandMenuSideEffects.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/transformFilterNodesAsEdges.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowVersionDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/transformFilterNodesAsEdges.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-edges/components/WorkflowDiagramDefaultEdgeEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-edges/components/WorkflowDiagramFilterEdgeEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-nodes/components/WorkflowDiagramHandleSource.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getTriggerDefaultDefinition.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerDefaultDefinition.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/constants/public-feature-flag.const.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.spec.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/core/utils/seed-feature-flags.util.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/utils/__tests__/get-root-steps.utils.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/utils/get-root-steps.utils.ts
  packages/twenty-website/public/images/lab/is-workflow-branch-enabled.png
  packages/twenty-website/public/images/lab/is-workflow-enabled.png
Labels: -PR: awaiting author

#14050 fix: removes re-triggering of OTP provisioning
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/object-metadata/components/ObjectMetadataItemsLoadEffect.tsx
  packages/twenty-front/src/modules/settings/two-factor-authentication/components/TwoFactorAuthenticationSetupForSettingsEffect.tsx
Labels: -PR: awaiting review

#14334 Added articles (pricing, onboarding, OS licence) and updated icons
  packages/twenty-website/src/app/_components/ui/layout/articles/ArticleContent.tsx
  packages/twenty-website/src/content/user-guide/collaboration.mdx
  packages/twenty-website/src/content/user-guide/constants/UserGuideIndex.ts
  packages/twenty-website/src/content/user-guide/data-model/creating-records.mdx
  packages/twenty-website/src/content/user-guide/data-model/customize-your-data-model.mdx
  packages/twenty-website/src/content/user-guide/data-model/fields.mdx
  packages/twenty-website/src/content/user-guide/data-model/standard-objects.mdx
  packages/twenty-website/src/content/user-guide/getting-started/configure-workspace-in-three-steps.mdx
  packages/twenty-website/src/content/user-guide/getting-started/create-workspace.mdx
  packages/twenty-website/src/content/user-guide/getting-started/getting-around-twenty.mdx
  packages/twenty-website/src/content/user-guide/getting-started/implementation-services.mdx
  packages/twenty-website/src/content/user-guide/getting-started/what-is-twenty.mdx
  packages/twenty-website/src/content/user-guide/integrations.mdx
  packages/twenty-website/src/content/user-guide/integrations/api-webhooks.mdx
  packages/twenty-website/src/content/user-guide/integrations/emails.mdx
  packages/twenty-website/src/content/user-guide/integrations/getting-started-workflows.mdx
  packages/twenty-website/src/content/user-guide/integrations/import-export-data.mdx
  packages/twenty-website/src/content/user-guide/integrations/integrations.mdx
  packages/twenty-website/src/content/user-guide/integrations/workflows.mdx
  packages/twenty-website/src/content/user-guide/other.mdx
  packages/twenty-website/src/content/user-guide/other/github.mdx
  packages/twenty-website/src/content/user-guide/other/glossary.mdx
  packages/twenty-website/src/content/user-guide/other/tips.mdx
  packages/twenty-website/src/content/user-guide/pricing.mdx
  packages/twenty-website/src/content/user-guide/pricing/billing-and-pricing-faq.mdx
  packages/twenty-website/src/content/user-guide/settings.mdx
  packages/twenty-website/src/content/user-guide/settings/permissions.mdx
  packages/twenty-website/src/content/user-guide/settings/settings-faq.mdx
  packages/twenty-website/src/content/user-guide/views/kanban-views.mdx
  packages/twenty-website/src/content/user-guide/views/views-sort-filter.mdx
Labels: -PR: awaiting review

#14385 Remove Add New button when softDelete filter is present
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultRecordActionsConfig.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/components/HideDeletedRecordsNoSelectionRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/types/ShouldBeRegisteredFunctionParams.ts
  packages/twenty-front/src/modules/action-menu/hooks/useShouldActionBeRegisteredParams.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnNewRecordButton.tsx
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/states/hasAnySoftDeleteFilterOnView.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/getRecordFilterFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordFilterAboutSoftDelete.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableAddNew.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateSoftDelete.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLabelIdentifierCell.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
Labels: -PR: awaiting author

#14454 Lazy load Nivo
  packages/twenty-front/src/modules/page-layout/components/__stories__/PageLayoutRenderer.stories.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/ChartSkeletonLoader.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetRenderer.tsx
  packages/twenty-front/src/modules/page-layout/widgets/iframe/components/IframeWidget.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerQueueMetricsSection.tsx
Labels: -PR: awaiting review

#14507 [Dashboards] - refactor - line chart
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetChartContainer.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetLineChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetPieChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetRenderer.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/__stories__/GraphWidgetLineChart.stories.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetBarChart/components/GraphWidgetBarChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/components/GraphWidgetLineChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/hooks/__tests__/useLineChartData.test.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/hooks/useLineChartData.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/hooks/useLineChartTheme.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/hooks/useLineChartTooltip.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/types/LineChartDataPoint.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/types/LineChartEnrichedSeries.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/types/LineChartSeries.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/utils/getLineChartAxisBottomConfig.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/utils/getLineChartAxisLeftConfig.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetLineChart/utils/handleLineChartPointClick.ts
Labels: -PR: awaiting review

#14527 Add compact view to calendar
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useObjectOptionsForBoard.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/states/isRecordBoardCompactModeActiveComponentState.ts
  packages/twenty-front/src/modules/object-record/record-calendar/month/components/RecordCalendarMonthBodyDay.tsx
  packages/twenty-front/src/modules/object-record/record-calendar/record-calendar-card/components/RecordCalendarCard.tsx
  packages/twenty-front/src/modules/object-record/record-calendar/record-calendar-card/components/RecordCalendarCardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardDataLoaderEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexIsCompactModeActiveState.ts
  packages/twenty-front/src/modules/views/utils/convertUpdateViewInputToCore.ts
Labels: -PR: awaiting review

#14561 [Dashboards] - Add scroll wrapper
  packages/twenty-front/src/modules/page-layout/components/PageLayoutGridLayout.tsx
  packages/twenty-front/src/modules/page-layout/components/PageLayoutRendererContent.tsx
Labels: -PR: awaiting review

#14550 [Dashboards] - refactor - gauge and number chart
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetRenderer.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/__stories__/GraphWidgetGaugeChart.stories.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/__stories__/GraphWidgetNumberChart.stories.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/components/GaugeChartEndLine.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/components/GraphWidgetGaugeChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/hooks/__tests__/useGaugeChartData.test.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/hooks/useGaugeChartData.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/hooks/useGaugeChartHandlers.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/hooks/useGaugeChartTooltip.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/types/GaugeChartData.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/utils/__tests__/calculateGaugeChartEndLineCoordinates.test.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetGaugeChart/utils/calculateGaugeChartEndLineCoordinates.ts
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetNumberChart/components/GraphWidgetNumberChart.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/graphWidgetNumberChart/utils/formatNumberChartTrend.ts
Labels: -PR: awaiting review

#14422 remove singleton usage of i18n
  packages/twenty-emails/src/components/BaseEmail.tsx
  packages/twenty-emails/src/components/Footer.tsx
  packages/twenty-emails/src/components/WhatIsTwenty.tsx
  packages/twenty-emails/src/emails/clean-suspended-workspace.email.tsx
  packages/twenty-emails/src/emails/password-reset-link.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/src/emails/send-email-verification-link.email.tsx
  packages/twenty-emails/src/emails/send-invite-link.email.tsx
  packages/twenty-emails/src/emails/test.email.tsx
  packages/twenty-emails/src/emails/validate-approved-access-domain.email.tsx
  packages/twenty-emails/src/emails/warn-suspended-workspace.email.tsx
  packages/twenty-emails/src/utils/i18n.utils.ts
  packages/twenty-server/src/engine/core-modules/approved-access-domain/services/approved-access-domain.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/reset-password.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/reset-password.service.ts
  packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
  packages/twenty-server/src/engine/core-modules/i18n/i18n.middleware.ts
  packages/twenty-server/src/engine/core-modules/i18n/i18n.module.ts
  packages/twenty-server/src/engine/core-modules/i18n/i18n.service.ts
  packages/twenty-server/src/engine/core-modules/view/controllers/view.controller.ts
  packages/twenty-server/src/engine/core-modules/view/resolvers/view.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/__tests__/before-update-one-field.hook.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/before-update-one-field.hook.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/resolve-field-metadata-standard-override.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/hooks/__tests__/before-update-one-object.hook.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/hooks/before-update-one-object.hook.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/resolve-object-metadata-standard-override.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/resolve-object-metadata-standard-override.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: awaiting review

#14588 Table small fixes
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useLeaveTableFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTableMoveFocusedCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellArrowKeysEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditModePortal.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFirstRowFirstColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFocusedPortalContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellHotkeysEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellPortals.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useCurrentlyFocusedRecordTableCellFocusId.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useFocusRecordTableCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useUnfocusRecordTableCell.ts
  packages/twenty-front/src/modules/object-record/record-table/states/recordTableFocusPositionComponentState.ts
  packages/twenty-front/src/modules/views/components/AnyFieldSearchChip.tsx
Labels: -PR: awaiting review

#14614 Setup 1.6 commands
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
Labels: -PR: awaiting review

#14603 Support loops in workflow versions
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-edges/components/WorkflowDiagramDefaultEdgeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-nodes/components/WorkflowDiagramStepNodeReadonly.tsx
Labels: -PR: awaiting review

#14613 Refactored table width and height constants
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableScrollToFocusedCellEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableScrollToFocusedRowEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableStyleWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/constants/RecordTableColumnCheckboxWidth.ts
  packages/twenty-front/src/modules/object-record/record-table/constants/RecordTableColumnDragAndDropWidth.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyLoading.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckbox.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellDragAndDrop.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFocusedPortalContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellHoveredPortalContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableDragAndDropPlaceholderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/__tests__/useSetIsRecordTableFocusActive.test.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useFocusRecordTableCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useSetIsRecordTableCellFocusActive.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooterCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValueCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCheckboxColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderDragDropColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastEmptyColumn.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/OverridableCheckbox.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/StyledDropdownButtonContainer.tsx
  packages/twenty-front/src/modules/ui/layout/top-bar/components/TopBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
Labels: -PR: awaiting review

#14665 Create save dashboard record action
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DashboardActionsConfig.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/dashboard-actions/components/SaveDashboardSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/dashboard-actions/types/DashboardSingleRecordActionKeys.ts
  packages/twenty-front/src/modules/action-menu/actions/states/forceRegisteredActionsMapComponentState.ts
  packages/twenty-front/src/modules/action-menu/hooks/useShouldActionBeRegisteredParams.ts
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutGraphTypeSelect.tsx
  packages/twenty-front/src/modules/dashboards/components/DashboardContentRenderer.tsx
  packages/twenty-front/src/modules/dashboards/hooks/useSetDashboardInEditMode.ts
  packages/twenty-front/src/modules/page-layout/components/PageLayoutInitializationQueryEffect.tsx
  packages/twenty-front/src/modules/page-layout/components/PageLayoutRenderer.tsx
  packages/twenty-front/src/modules/page-layout/components/__stories__/PageLayoutRenderer.stories.tsx
  packages/twenty-front/src/modules/page-layout/graphql/mutations/updatePageLayoutWithTabsAndWidgets.ts
  packages/twenty-front/src/modules/page-layout/hooks/__tests__/useCreatePageLayoutGraphWidget.test.tsx
  packages/twenty-front/src/modules/page-layout/hooks/__tests__/usePageLayoutDraftState.test.tsx
  packages/twenty-front/src/modules/page-layout/hooks/useCreatePageLayoutGraphWidget.ts
  packages/twenty-front/src/modules/page-layout/hooks/useCreatePageLayoutIframeWidget.ts
  packages/twenty-front/src/modules/page-layout/hooks/useCreatePageLayoutTab.ts
  packages/twenty-front/src/modules/page-layout/hooks/usePageLayoutHandleLayoutChange.ts
  packages/twenty-front/src/modules/page-layout/hooks/useSavePageLayout.ts
  packages/twenty-front/src/modules/page-layout/hooks/useUpdatePageLayoutWidget.ts
  packages/twenty-front/src/modules/page-layout/mocks/mockWidgets.ts
  packages/twenty-front/src/modules/page-layout/states/pageLayoutPersistedComponentState.ts
  packages/twenty-front/src/modules/page-layout/states/savedPageLayoutsComponentState.ts
  packages/twenty-front/src/modules/page-layout/types/draft-page-layout.ts
  packages/twenty-front/src/modules/page-layout/types/pageLayoutTypes.ts
  packages/twenty-front/src/modules/page-layout/utils/__tests__/addWidgetToTab.test.ts
  packages/twenty-front/src/modules/page-layout/utils/__tests__/convertLayoutsToWidgets.test.ts
  packages/twenty-front/src/modules/page-layout/utils/__tests__/convertPageLayoutToTabLayouts.test.ts
  packages/twenty-front/src/modules/page-layout/utils/__tests__/removeWidgetFromTab.test.ts
  packages/twenty-front/src/modules/page-layout/utils/addWidgetToTab.ts
  packages/twenty-front/src/modules/page-layout/utils/convertLayoutsToWidgets.ts
  packages/twenty-front/src/modules/page-layout/utils/convertPageLayoutDraftToUpdateInput.ts
  packages/twenty-front/src/modules/page-layout/utils/convertPageLayoutToTabLayouts.ts
  packages/twenty-front/src/modules/page-layout/utils/isPageLayoutEmpty.ts
  packages/twenty-front/src/modules/page-layout/utils/removeWidgetFromTab.ts
  packages/twenty-front/src/modules/page-layout/widgets/components/__stories__/WidgetRenderer.stories.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/components/GraphWidgetRenderer.tsx
  packages/twenty-front/src/modules/page-layout/widgets/graph/types/GraphWidget.ts
  packages/twenty-front/src/modules/page-layout/widgets/iframe/types/IframeWidget.ts
  packages/twenty-server/src/engine/core-modules/page-layout/dtos/inputs/update-page-layout-with-tabs.input.ts
Labels: -PR: awaiting review

#14681 Create MenuPicker
  packages/twenty-ui/src/navigation/index.ts
  packages/twenty-ui/src/navigation/menu/components/MenuPicker.tsx
  packages/twenty-ui/src/navigation/menu/components/__stories__/MenuPicker.stories.tsx
  packages/twenty-ui/src/navigation/menu/components/index.ts
  packages/twenty-ui/src/navigation/menu/index.ts
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItem.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemAvatar.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemCommand.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemCommandHotKeys.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemMultiSelect.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemMultiSelectAvatar.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemMultiSelectTag.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemNavigate.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSelect.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSelectAvatar.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSelectColor.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSelectTag.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSuggestion.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemToggle.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItem.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemDraggable.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemMultiSelect.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemMultiSelectAvatar.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemNavigate.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemSelect.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemSelectAvatar.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemSelectColor.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemSelectTag.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemToggle.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/index.ts
  packages/twenty-ui/src/navigation/menu/menu-item/index.ts
  packages/twenty-ui/src/navigation/menu/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/internals/components/StyledMenuItemBase.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/types/MenuItemAccent.ts
Labels: -PR: awaiting review

#14685 Add FK creation in migration v2
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-default-relation-flat-field-metadatas-for-custom-object.util.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/services/workspace-schema-foreign-key-manager.service.ts
  packages/twenty-server/src/engine/twenty-orm/workspace-schema-manager/types/workspace-schema-foreign-key-definition.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/action-handlers/field/services/create-field-action-handler.service.ts
Labels: -PR: awaiting review

#14680 Add basic support for iterators in workflow runs
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-edges/components/WorkflowDiagramDefaultEdgeRun.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-edges/components/WorkflowRunDiagramBaseEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-nodes/components/WorkflowRunDiagramStepNode.tsx
Labels: -PR: awaiting review

#14703 Fix flaky test on page layout widget
  packages/twenty-server/test/integration/graphql/suites/page-layout/page-layout-widget-resolver.integration-spec.ts
Labels: -PR: awaiting review

#14707 Fix calendar booking step in onboarding when env var is not configured
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-server/src/engine/core-modules/client-config/services/client-config.service.ts
  packages/twenty-server/src/engine/core-modules/onboarding/onboarding.service.ts
Labels: -PR: awaiting review

#14724 Update menu items across the app
  packages/twenty-front/src/modules/command-menu/components/CommandMenuItem.tsx
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutGraphTypeSelect.tsx
  packages/twenty-front/src/modules/command-menu/pages/page-layout/components/CommandMenuPageLayoutWidgetTypeSelect.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/WorkflowActionMenuItems.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/trigger-type/components/CommandMenuWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownCustomView.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownDefaultView.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupsContent.tsx
  packages/twenty-ui/src/navigation/index.ts
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItem.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemCommand.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemDraggable.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemHotKeys.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemMultiSelect.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemNavigate.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSelect.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemSuggestion.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/MenuItemToggle.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItem.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemCommand.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemDraggable.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemMultiSelect.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemNavigate.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemSelect.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/__stories__/MenuItemToggle.stories.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/components/index.ts
  packages/twenty-ui/src/navigation/menu/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-ui/src/navigation/menu/menu-item/internals/components/StyledMenuItemBase.tsx
Labels: -PR: awaiting review

#14784 Visualize workflow run step input
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/types/WorkflowRunStepContext.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepContext.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepContext.ts
Labels: -PR: awaiting review
