Repository twentyhq/twenty, pull requests merged in 2025-02, with the labels that each got.

#9962 323 add object name inside the search
  packages/twenty-front/src/modules/command-menu/components/CommandMenuItem.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuList.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useSearchRecords.tsx
  packages/twenty-front/src/modules/command-menu/types/Command.ts
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemCommand.tsx
  packages/twenty-ui/src/navigation/menu-item/components/__stories__/MenuItemCommand.stories.tsx
Labels: -PR: awaiting review

#9806 setup localization for twenty-emails
  package.json
  packages/twenty-emails/.swcrc
  packages/twenty-emails/lingui.config.js
  packages/twenty-emails/package.json
  packages/twenty-emails/project.json
  packages/twenty-emails/src/components/BaseEmail.tsx
  packages/twenty-emails/src/emails/clean-suspended-workspace.email.tsx
  packages/twenty-emails/src/emails/password-reset-link.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/src/emails/send-email-verification-link.email.tsx
  packages/twenty-emails/src/emails/send-invite-link.email.tsx
  packages/twenty-emails/src/emails/warn-suspended-workspace.email.tsx
  packages/twenty-emails/src/locales/de.po
  packages/twenty-emails/src/locales/en.po
  packages/twenty-emails/src/locales/es.po
  packages/twenty-emails/src/locales/fr.po
  packages/twenty-emails/src/locales/generated/de.ts
  packages/twenty-emails/src/locales/generated/en.ts
  packages/twenty-emails/src/locales/generated/es.ts
  packages/twenty-emails/src/locales/generated/fr.ts
  packages/twenty-emails/src/locales/generated/it.ts
  packages/twenty-emails/src/locales/generated/ja.ts
  packages/twenty-emails/src/locales/generated/ko.ts
  packages/twenty-emails/src/locales/generated/pseudo-en.ts
  packages/twenty-emails/src/locales/generated/pt-BR.ts
  packages/twenty-emails/src/locales/generated/pt-PT.ts
  packages/twenty-emails/src/locales/generated/zh-Hans.ts
  packages/twenty-emails/src/locales/generated/zh-Hant.ts
  packages/twenty-emails/src/locales/it.po
  packages/twenty-emails/src/locales/ja.po
  packages/twenty-emails/src/locales/ko.po
  packages/twenty-emails/src/locales/pseudo-en.po
  packages/twenty-emails/src/locales/pt-BR.po
  packages/twenty-emails/src/locales/pt-PT.po
  packages/twenty-emails/src/locales/zh-Hans.po
  packages/twenty-emails/src/locales/zh-Hant.po
  packages/twenty-emails/tsconfig.json
  packages/twenty-emails/tsconfig.lib.json
  packages/twenty-emails/vite.config.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/LocalePicker.tsx
  packages/twenty-front/src/utils/i18n/dynamicActivate.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/reset-password.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/reset-password.service.ts
  packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
  packages/twenty-server/src/engine/core-modules/email/email-sender.job.ts
  packages/twenty-server/src/engine/core-modules/email/email.service.ts
  packages/twenty-server/src/engine/core-modules/i18n/i18n.service.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
  yarn.lock
Labels: -PR: wip, -PR: awaiting author

#9973 Sort active workspaces
  packages/twenty-server/src/database/commands/active-workspaces.command.ts
Labels: scope: backend, -PR: awaiting review

#9943 Environment variables in admin panel (read only) - backend
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getEnvironmentVariablesGrouped.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variable.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variables-group.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variables-subgroup.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variables.output.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/__tests__/environment-variables-group-position.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-group-position.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-hidden-groups.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-masking-config.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-metadata-decorator-key.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-metadata-decorator-names-key.ts
  packages/twenty-server/src/engine/core-modules/environment/decorators/environment-variables-metadata.decorator.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-group.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-masking-strategies.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-sub-group.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/environment/environment.service.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/environment.service.ts
  packages/twenty-server/src/engine/core-modules/environment/utils/__tests__/environment-variable-mask-sensitive-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/utils/environment-variable-mask-sensitive-data.util.ts
  packages/twenty-server/src/utils/typed-reflect.ts
Labels: -PR: awaiting review

#9963 feat(sso): fix saml + allow to use public invite with sso + fix invite page with multiple sso provider
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/hooks/useCreateAppRouter.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSSO.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useWorkspaceFromInviteHash.ts
  packages/twenty-front/src/pages/auth/Invite.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUpWithInvite.stories.tsx
  packages/twenty-server/src/engine/core-modules/auth/controllers/sso-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/oidc.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/saml.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/sso/dtos/get-authorization-url.input.ts
  packages/twenty-server/src/engine/core-modules/sso/services/sso.service.ts
  packages/twenty-server/src/engine/core-modules/sso/sso.resolver.ts
Labels: -PR: awaiting review

#9982 allow people to connect their mailbox
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsListCard.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
Labels: prio: high

#9981 hotfix for lab
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/lab/graphql/mutations/updateLabPublicFeatureFlag.ts
  packages/twenty-front/src/modules/settings/lab/hooks/useLabPublicFeatureFlags.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.resolver.ts
  packages/twenty-server/src/engine/core-modules/lab/services/lab.service.ts
Labels: -PR: awaiting review

#9996 Fix-issue-370
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/isGoogleCalendarEnabledState.ts
  packages/twenty-front/src/modules/client-config/states/isGoogleMessagingEnabledState.ts
  packages/twenty-front/src/modules/client-config/states/isMicrosoftCalendarEnabledState.ts
  packages/twenty-front/src/modules/client-config/states/isMicrosoftMessagingEnabledState.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/microsoft-apis.service.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#9995 361 create a navigation stack for the command menu
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/hooks/useSearchRecordsRecordAgnosticAction.ts
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuNavigationStackState.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/hooks/useRightDrawer.ts
Labels: -PR: awaiting review, run-e2e

#9999 Update cleaning suspended workspace job
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
Labels: -PR: awaiting review

#9840 Fix:Empty link in record details isn't deleted by default
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
Labels: -PR: awaiting author, -PR: awaiting review

#10006 Create variants for workflow visualizer nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditableContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagramNodeVariant.ts
  packages/twenty-front/src/testing/decorators/ReactflowDecorator.tsx
  packages/twenty-ui/src/theme/constants/AdaptiveColorsDark.ts
  packages/twenty-ui/src/theme/constants/AdaptiveColorsLight.ts
  packages/twenty-ui/src/theme/constants/ThemeDark.ts
  packages/twenty-ui/src/theme/constants/ThemeLight.ts
  packages/twenty-ui/src/theme/index.ts
Labels: -PR: awaiting review, -PR: awaiting CI, run-e2e

#10014 [BUG][PROD] Fix `ViewGroup` creation optimistic cache
  packages/twenty-front/src/modules/object-record/constants/ObjectRecordTypename.ts
  packages/twenty-front/src/modules/object-record/types/BaseObjectRecord.ts
  packages/twenty-front/src/modules/object-record/types/ObjectRecord.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
Labels: -PR: awaiting author

#10001 Fetch roles in roles settings page
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/roles/graphql/queries/getRolesQuery.ts
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/role/dtos/role.dto.ts
Labels: -PR: awaiting author

#10021 Post #10014 merged nitpicks followup
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
  packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts
  packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewGroups.ts
Labels: -PR: awaiting review

#10024 `BaseObjectRecord` and`__typename` naming updates
  packages/twenty-front/src/modules/object-record/constants/GraphqlTypenameKey.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts
Labels: -PR: awaiting review

#10028 [FEAT] Destroy many Workflow actions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.ts
Labels: -PR: awaiting review

#10042 Simplify the component layers for workflow nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditableContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeIcon.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
Labels: -PR: awaiting review

#10041 [permissions] Avoid N+1 on roles
  packages/twenty-server/src/engine/core-modules/user/dtos/workspace-member.dto.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/user-role/user-role.service.ts
Labels: -PR: awaiting author

#10008 signup sync with microsoft
  packages/twenty-front/src/pages/onboarding/SyncEmails.tsx
Labels: scope: front, -PR: awaiting review

#10011 Environment variables in admin panel (read only) - front
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesRow.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTabContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminWorkspaceContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminFeatureFlagsTabs.ts
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminTabs.ts
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminTabsId.ts
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminUserLookupWorkspaceTabsId.ts
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getEnvironmentVariablesGrouped.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useFeatureFlag.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useUserLookup.ts
  packages/twenty-front/src/modules/settings/admin-panel/states/adminPanelErrorState.ts
  packages/twenty-front/src/modules/settings/admin-panel/states/userLookupResultState.ts
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/services/data-seed-demo-workspace.service.ts
  packages/twenty-server/src/database/typeorm-seeds/core/users.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variables-group.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/environment-variables-subgroup.dto.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/__tests__/environment-variables-group-metadata.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/__tests__/environment-variables-group-position.spec.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-group-metadata.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-hidden-groups.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-sub-group-metadata.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-group.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-sub-group.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/environment/environment.service.spec.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/resolvers/file-upload.resolver.ts
  packages/twenty-server/src/engine/core-modules/message-queue/drivers/bullmq.driver.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/guards/demo.env.guard.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting author

#10059 Make the e2e ci pass
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
Labels: -PR: awaiting review, -PR: awaiting CI, run-e2e

#9990 fix(auth): reset signInUp state when email change
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpEmailField.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWithCredentials.tsx
Labels: -PR: awaiting review

#10067 Lingui working with NODE ENV=production again
  package.json
  packages/twenty-docker/k8s/terraform/deployment-server.tf
  packages/twenty-server/.env.example
  packages/twenty-server/.env.test
  packages/twenty-server/.swcrc
  packages/twenty-server/jest.config.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/engine/api/graphql/metadata.module-factory.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/exception-handler.module-factory.ts
  packages/twenty-server/src/engine/core-modules/graphql/utils/generate-graphql-error-from-error.util.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/utils/global-exception-handler.util.ts
  packages/twenty-server/src/instrument.ts
  packages/twenty-server/src/main.ts
  packages/twenty-website/src/app/_server-utils/get-posts.tsx
  packages/twenty-website/src/app/releases/utils/get-releases.tsx
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
  yarn.lock
Labels: run-e2e

#10057 Remove the source handle for leaf nodes
  package.json
  packages/twenty-e2e-testing/tests/demo/demo_basic.spec.ts
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditableContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramEmptyTrigger.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/markLeafNodes.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/mergeWorkflowDiagrams.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/isCreateStepNode.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/markLeafNodes.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateStep.ts
  packages/twenty-front/src/testing/utils/getUuidV4Mock.ts
  yarn.lock
Labels: -PR: awaiting review, -PR: awaiting CI, run-e2e

#10069 [BUG] Avoid backfilling record position on update one
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
Labels: -PR: wip, -PR: awaiting author

#10063 [permissions] Add SettingsPermissionGuard on data model and roles features
  packages/twenty-server/src/engine/guards/settings-permissions.guard.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/utils/permissions-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.module.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.resolver.ts
Labels: -PR: awaiting author

#10075 Command menu list design updates
  packages/twenty-front/src/modules/command-menu/components/CommandGroup.tsx
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemCommand.tsx
Labels: -PR: awaiting review

#10080 Updates in the workflow actions config
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.ts
  packages/twenty-server/src/engine/core-modules/i18n/locales/de.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/es.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/fr.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/it.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ja.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ko.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-br.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-pt.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/zh-Hans.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/zh-Hant.po
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#10076 Reset search bar when clicking on search action
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/hooks/useSearchRecordsRecordAgnosticAction.ts
Labels: -PR: awaiting review

#10082 Focus on the input on command menu page change
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBarInputFocusEffect.tsx
Labels: -PR: awaiting review

#10029 add invalid captcha and messageChannel sync status health monitoring
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/cache-storage/types/cache-storage-namespace.enum.ts
  packages/twenty-server/src/engine/core-modules/captcha/captcha.guard.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/health/health-cache.service.ts
  packages/twenty-server/src/engine/core-modules/health/health.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/health.controller.ts
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/types/health-counter-cache-keys.type.ts
  packages/twenty-server/src/engine/core-modules/health/types/health-metrics.types.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
Labels: -PR: awaiting review

#10113 fix log + add 3 indexes on fielMetadata and indexFieldMetadata
  packages/twenty-server/src/database/typeorm/metadata/migrations/1739203246456-addIndexesOnFieldMetadataAndIndexFieldMetadata.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-field-metadata.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: awaiting review

#10083 RICH_TEXT_V2 frontend
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useActivityTargetObjectRecords.test.tsx
  packages/twenty-front/src/modules/activities/notes/components/NoteCard.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/activities/tasks/hooks/__tests__/useCompleteTask.test.tsx
  packages/twenty-front/src/modules/activities/types/Activity.ts
  packages/twenty-front/src/modules/command-menu/hooks/useSearchRecords.tsx
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RichTextV2FieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRichTextV2Field.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRichTextV2FieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/assertFieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRichTextV2.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRichTextValue.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldRichTextValueV2.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingRichTextV2Filter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/types/AvailableFieldForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsObjectNewFieldSelector.tsx
  packages/twenty-front/src/modules/settings/data-model/types/CompositeFieldType.ts
  packages/twenty-front/src/modules/settings/data-model/types/SettingsCompositeFieldType.ts
  packages/twenty-front/src/modules/settings/data-model/types/SettingsExcludedFieldType.ts
  packages/twenty-front/src/modules/settings/data-model/types/SettingsNonCompositeFieldType.ts
  packages/twenty-front/src/modules/spreadsheet-import/__mocks__/mockRsiValues.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/TemplateColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/types/index.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/dataMutations.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/findMatch.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/findUnmatchedRequiredFields.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/generateExampleRow.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/getFieldOptions.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/getMatchedColumns.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/normalizeTableData.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/setColumn.test.ts
  packages/twenty-front/src/modules/ui/input/editor/utils/getFirstNonEmptyLineOfRichText.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldSelect.tsx
  packages/twenty-front/src/testing/mock-data/notes.ts
  packages/twenty-front/src/testing/mock-data/tasks.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/activity-query-result-getter.handler.ts
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-BR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-PT.po
Labels: -PR: awaiting review

#10120 Add workflow success edge
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCustomMarkers.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramDefaultEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramSuccessEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramCustomMarkers.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeGrayCircleMarkedId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeGreenCircleMarkedId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeGreenRoundedArrowMarkerId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeGreenRoundedArrowMarkerWidthPx.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeRoundedArrowMarkerId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeDefaultConfiguration.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeSuccessConfiguration.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
Labels: -PR: awaiting review, run-e2e

#10115 add role assignment page
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/AppRouter.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/app/hooks/useCreateAppRouter.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/settings/roles/graphql/fragments/roleFragment.ts
  packages/twenty-front/src/modules/settings/roles/graphql/mutations/updateWorkspaceMemberRoleMutation.ts
  packages/twenty-front/src/modules/settings/roles/graphql/queries/getRolesQuery.ts
  packages/twenty-front/src/modules/workspace-member/graphql/fragments/workspaceMemberQueryFragment.ts
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleAssignment.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleAssignmentConfirmationModal.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleAssignmentConfirmationModalSubtitle.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleAssignmentTableHeader.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleAssignmentTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleSettings.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/pages/settings/roles/components/RoleWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/pages/settings/roles/types/RoleAssignmentConfirmationModalMode.ts
  packages/twenty-front/src/pages/settings/roles/types/RoleAssignmentConfirmationModalSelectedWorkspaceMember.ts
  packages/twenty-front/src/testing/mock-data/timeline-activities.ts
  packages/twenty-server/src/engine/core-modules/user/dtos/workspace-member.dto.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/utils/permissions-graphql-api-exception.filter.ts
  packages/twenty-ui/src/input/button/components/Button.tsx
Labels: -PR: awaiting author

#10079 [REFACTOR][BUG] Dynamically compute field to write in cache `UPDATE` & `DELETE`
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDestroyMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/information-banner/components/deleted-record/InformationBannerDeletedRecord.tsx
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/objectMetadataItemSchema.test.ts
  packages/twenty-front/src/modules/object-record/cache/utils/getRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/cache/utils/updateRecordFromCache.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/generateDepthOneRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useDestroyManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDestroyOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useRestoreManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFieldRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterGroupRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewSortRecords.ts
  packages/twenty-front/src/modules/workflow/hooks/useDeleteOneWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useDeleteWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useUpdateWorkflowVersionStep.ts
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksWrapper.tsx
  packages/twenty-front/src/testing/mock-data/companies.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-front/src/utils/array/__tests__/buildRecordFromKeysWithSameValue.test.ts
  packages/twenty-front/src/utils/array/buildRecordFromKeysWithSameValue.ts
Labels: run-e2e, -PR: ready to merge

#10061 fix: many fields in an object
  packages/twenty-front/jest.config.ts
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/hooks/__tests__/useCreateActivityInDB.test.tsx
  packages/twenty-front/src/modules/activities/tasks/hooks/__tests__/useCompleteTask.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-metadata/graphql/queries.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFindManyObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFindManyObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useRefreshObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/types/ObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/personFragments.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/testing/mock-data/favorite.ts
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-limit-amount-of-view-field.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.module.ts
  packages/twenty-server/src/engine/constants/settings/index.ts
  packages/twenty-server/src/engine/constants/settings/interfaces/settings.interface.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.interface.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/attachments.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/favorites.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/note-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/rockets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-attachments.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-favorites.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-note-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-rockets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-task-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-timeline-activities.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/task-targets.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/timeline-activities.integration-spec.ts
Labels: -PR: awaiting author

#10081 folders
  packages/twenty-server/src/engine/core-modules/auth/services/microsoft-apis.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/mocks/microsoft-api-examples.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/types/folders.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/exceptions/message-import.exception.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-cursor.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
Labels: -PR: awaiting author

#10119 Admin panel refactor
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminWorkspaceContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useFeatureFlag.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useFeatureFlagState.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonate.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonationAuth.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonationRedirect.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useUserLookup.ts
  packages/twenty-front/src/modules/settings/admin-panel/states/adminPanelErrorState.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-group-metadata.ts
Labels: -PR: awaiting review

#10094 RICH_TEXT_V2 upgrade command
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useExportNoteAction.ts
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/activities/graphql/operation-signatures/factories/findActivitiesOperationSignatureFactory.ts
  packages/twenty-front/src/modules/activities/hooks/useActivities.ts
  packages/twenty-front/src/modules/activities/hooks/usePrepareFindManyActivitiesQuery.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-fix-body-v2-view-field-position.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-migrate-rich-text-field.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/opportunities.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-shared/src/types/FieldMetadataType.ts
Labels: -PR: awaiting review

#10170 Feature flag IS_MICROSOFT_SYNC_ENABLED removal
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: scope: back+front, -PR: awaiting review, size: short, prio: med

#10161 withDelete option to TypeOrm
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
Labels: -PR: awaiting review

#10138 feat(cloudflare): add webhook support for custom hostname updates
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/workspace/graphql/queries/checkCustomDomainValidRecords.ts
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomain.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainEffect.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainRecords.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainRecordsStatus.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsSubdomain.tsx
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/controllers/cloudflare.controller.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/controllers/cloudflare.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/domain-manager.exception.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/domain-manager.module.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/dtos/custom-domain-valid-records.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/guards/cloudflare-secret.guard.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/guards/cloudflare-secret.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/custom-domain.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/custom-domain.service.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting author

#10114 feat(workspace): add support for custom domain status toggle
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/workspace/graphql/queries/checkCustomDomainValidRecords.ts
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomain.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainEffect.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainRecords.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainRecordsStatus.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsSubdomain.tsx
  packages/twenty-front/src/pages/settings/workspace/states/customDomainRecordsState.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/database/typeorm/core/migrations/common/1739203087254-add-is-custom-domain-enable.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/sso-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-oauth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/oidc-auth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/oidc-auth.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/controllers/cloudflare.controller.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/controllers/cloudflare.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/domain-manager.exception.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/domain-manager.module.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/domain-manager.type.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/dtos/custom-domain-valid-records.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/guards/cloudflare-secret.guard.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/guards/cloudflare-secret.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/custom-domain.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/custom-domain.service.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts
  packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting review

#10169 [settings/security] Prevent toggle if only 1 authentication option
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/utils/workspace-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.exception.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting author, prio: high

#10130 [REFACTOR][BUG] Dynamically compute field to write in cache CREATE
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/mapFieldMetadataToGraphQLQuery.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/checkObjectMetadataItemHasFieldCreatedBy.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapFieldMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapObjectMetadataToGraphQLQuery.ts
  packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFieldsDeprecated.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationGqlRecordFields.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/generateDepthOneRecordGqlFields.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/isRecordGraphlFieldsNode.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/__tests__/useCombinedFindManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/__tests__/useCombinedFindManyRecordsQueryVariables.test.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useClearField.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerTitleRecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
  packages/twenty-front/src/modules/object-record/utils/buildOptimisticActorFieldValueFromCurrentWorkspaceMember.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts
  packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/object-record/utils/prefillRecord.ts
  packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts
  packages/twenty-front/src/testing/jest/generateEmptyJestRecordNode.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-front/src/testing/mock-data/workspace-members.ts
Labels: -PR: awaiting review

#10198 Fix bug with table aggregate footer when switching object
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
Labels: -PR: awaiting review

#10146 Add workflow run visualizer
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVersionVisualizer.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizer.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizerContent.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/FirstNodePosition.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/VerticalDistanceBetweenTwoNodes.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowDiagramEmptyTriggerNodeDefinition.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowDiagramSuccessEdgeType.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeSuccessConfiguration.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowDiagramTriggerNode.ts
Labels: -PR: awaiting review

#10193 refactor(server): rename PORT to NODE_PORT
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/main.ts
Labels: -PR: awaiting review

#10201 refactor(ui/settings): update styles and improve structure
  packages/twenty-front/src/modules/settings/components/SettingsRadioCard.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersForm.tsx
  packages/twenty-ui/src/display/text/components/HorizontalSeparator.tsx
Labels: -PR: awaiting review

#10194 refactor(domain-manager): simplify frontend URL configuration
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-server.yaml
  packages/twenty-docker/k8s/terraform/deployment-server.tf
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review

#10216 fix(auth): Invite with public url and social sso.
  packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts
Labels: -PR: awaiting review

#10215 [NITPICK] From args list to record args `RecordPositionFactory`
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/record-position.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/record-position.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/services/record-position-backfill-service.ts
Labels: -PR: awaiting review

#10195 Update suspended cleaning command
  packages/twenty-emails/src/emails/clean-suspended-workspace.email.tsx
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/clean-suspended-workspaces.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#10223 Fixing unhandled exception for microsoft driver
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/message-import-exception-handler.service.ts
Labels: -PR: awaiting review, size: long, prio: CRITICAL 🚨

#10231 [WEBSITE] Upgrade guide 0.41.0 -> 0.42.0
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review

#10224 Fix autogrowing input glitch
  packages/twenty-front/src/modules/ui/input/components/EntityTitleDoubleTextInput.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/tsup.ui.index.tsx
  packages/twenty-ui/src/utilities/dimensions/components/AutogrowWrapper.tsx
  packages/twenty-ui/src/utilities/dimensions/components/ComputeNodeDimensions.tsx
  packages/twenty-ui/src/utilities/index.ts
  packages/twenty-website/src/content/twenty-ui/input/text.mdx
Labels: -PR: awaiting review

#10248 Fix command menu selection
  packages/twenty-front/src/modules/command-menu/components/CommandMenuDefaultSelectionEffect.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuList.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/states/hasUserSelectedCommandState.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableList.tsx
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/internal/useSelectableListHotKeys.ts
Labels: -PR: awaiting review

#10254 [NITPICK] call `closeDropdown` before `openModal` import spreadsheet
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
Labels: -PR: awaiting review, type: chore

#10267 Fix command menu context chip display on show page
  packages/twenty-front/src/modules/activities/hooks/useOpenActivityRightDrawer.ts
  packages/twenty-front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipGroupsWithRecordSelection.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useCreateNewTableRecords.ts
  packages/twenty-server/src/engine/core-modules/i18n/locales/af-ZA.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ar-SA.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ca-ES.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/cs-CZ.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/da-DK.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/de-DE.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/el-GR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/es-ES.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/fi-FI.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/fr-FR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/he-IL.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/hu-HU.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/it-IT.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ja-JP.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ko-KR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/nl-NL.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/no-NO.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pl-PL.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-BR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/pt-PT.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ro-RO.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/ru-RU.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/sr-Cyrl.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/sv-SE.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/tr-TR.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/uk-UA.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/vi-VN.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/zh-CN.po
  packages/twenty-server/src/engine/core-modules/i18n/locales/zh-TW.po
Labels: -PR: awaiting review

#10289 Fix e2e tests
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/tests/demo/demo_basic.spec.ts
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
Labels: -PR: awaiting review, run-e2e

#10261 Fix featureFlag N+1 queries
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-duplicates-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-search-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
Labels: -PR: awaiting review

#10186 Health monitor status for admin panel
  package.json
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthMessageSyncCountersTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthStatusRightContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminQueueExpandableContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminQueueHealthButtons.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTabContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsHealthStatusListCard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminTabs.ts
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getIndicatorHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getSystemHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useGetUptoDateHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/AdminHealthService.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/SettingsWorkspace.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminIndicatorHealthStatus.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel-health.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel-health.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.module.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-health-service-data.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-indicator-health-status.input.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-worker-queue-health.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/system-health.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/enums/admin-panel-health-service-status.enum.ts
  packages/twenty-server/src/engine/core-modules/health/constants/health-error-messages.constants.ts
  packages/twenty-server/src/engine/core-modules/health/constants/health-indicators-timeout.conts.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/health.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/metrics.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/health.controller.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/metrics.controller.ts
  packages/twenty-server/src/engine/core-modules/health/enums/health-service-name.enum.ts
  packages/twenty-server/src/engine/core-modules/health/health-cache.service.ts
  packages/twenty-server/src/engine/core-modules/health/health.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/database.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/message-sync.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/redis.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/worker.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/database.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/message-sync.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/redis.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/worker.health.ts
  packages/twenty-server/src/engine/core-modules/health/types/health-metrics.types.ts
  packages/twenty-server/src/engine/core-modules/health/types/message-sync-metrics.types.ts
  packages/twenty-server/src/engine/core-modules/health/types/worker-queue-health.type.ts
  packages/twenty-server/src/engine/core-modules/health/types/worker-queue-metrics.type.ts
  packages/twenty-server/src/engine/core-modules/health/utils/health-check-timeout.util.ts
  yarn.lock
Labels: -PR: awaiting review

#10305 406 animate the command menu button
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuRouter.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/ui/layout/page-header/components/PageHeaderOpenCommandMenuButton.tsx
  packages/twenty-ui/src/input/button/components/AnimatedButton.tsx
  packages/twenty-ui/src/input/index.ts
Labels: -PR: awaiting review

#10303 Update searchVector on new richTextV2 note and task entities + migration command
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-search-vector-on-note-and-task-entities.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.module.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
Labels: -PR: awaiting review

#10294 Bring back raw workflow run output visualizer
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts
  packages/twenty-front/src/modules/workflow/components/WorkflowRunOutputVisualizer.tsx
Labels: -PR: awaiting author, run-e2e

#10297 feedback from Thomas
  packages/twenty-ui/src/display/chip/components/AvatarChip.tsx
Labels: scope: front, -PR: awaiting author, prio: med

#10269 [BUGFIX] Reply button opens google
  packages/twenty-front/src/modules/accounts/types/MessageChannel.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
Labels: -PR: awaiting review

#10325 fixing test mainly by @charlesBochet
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDeleteMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDestroyMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useExportMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useAddToFavoritesSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useDeleteSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useRemoveFromFavoritesSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useDeactivateWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useDiscardDraftWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenuContextRecordChip.stories.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/__tests__/useFavorites.test.tsx
  packages/twenty-front/src/modules/favorites/hooks/__tests__/useHandleFavoriteDragAndDrop.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useColumnDefinitionsFromFieldMetadata.test.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyFetchAllRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/__tests__/useObjectOptionsForBoard.test.tsx
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/__tests__/useExportFetchRecords.test.ts
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/testing/jest/JestContextStoreSetter.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksAndActionMenuWrapper.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksWrapper.tsx
  packages/twenty-front/src/testing/mock-data/views.ts
Labels: -PR: awaiting review, prio: high

#10327 typo
  packages/twenty-front/src/testing/mock-data/views.ts
Labels: -PR: awaiting review, prio: high

#10302 Fix workflow run ouput format
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
Labels: -PR: awaiting review, run-e2e

#10333 following emails logic with intertnal conversaiotn
  packages/twenty-website/src/content/user-guide/functions/emails.mdx
Labels: -PR: awaiting review

#10344 Role permissions tab should display object permissions from API result
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/roles/graphql/fragments/roleFragment.ts
  packages/twenty-front/src/pages/settings/roles/components/RolePermissions.tsx
Labels: -PR: awaiting review

#10339 add not found redirection logic if object in url param not exists
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
Labels: -PR: awaiting review

#10324 [BUGFIX][PROD] RICH_TEXT_V2 command handle `{}` body col value
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-migrate-rich-text-field.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.command.ts
Labels: -PR: awaiting review

#10222 Add files deletion when destroying attachment, workspace or workspaceMember
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-server/src/engine/core-modules/file/file.module.ts
  packages/twenty-server/src/engine/core-modules/file/jobs/file-deletion.job.ts
  packages/twenty-server/src/engine/core-modules/file/jobs/file-workspace-folder-deletion.job.ts
  packages/twenty-server/src/engine/core-modules/file/listeners/file-attachment.listener.ts
  packages/twenty-server/src/engine/core-modules/file/listeners/file-workspace-member.listener.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
Labels: -PR: awaiting review

#10232 [BUG] Refactor actor composite type
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts
  packages/twenty-server/jest.config.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-standardization-of-actor-composite-context-type.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.module.ts
  packages/twenty-server/src/engine/core-modules/actor/actor.module.ts
  packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-many.pre-query-hook.ts
  packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-one.pre-query-hook.ts
  packages/twenty-server/src/engine/core-modules/actor/services/__tests__/created-by-from-auth-context.service.spec.ts
  packages/twenty-server/src/engine/core-modules/actor/services/created-by-from-auth-context.service.ts
  packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-api-key.util.ts
  packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-full-name-metadata.util.ts
  packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-workspace-member.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/actor.composite-type.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/jobs/workflow-trigger.job.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
Labels: -PR: wip, -PR: awaiting author

#10353 move deletion limit on hard deletion
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: awaiting review

#10355 Deduplicate-emails
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/__tests__/query-runner.util.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/query-runner-links.util.ts
  packages/twenty-server/src/modules/contact-creation-manager/utils/__tests__/get-unique-contacts-and-handles.spec.ts
  packages/twenty-server/src/modules/contact-creation-manager/utils/get-unique-contacts-and-handles.util.ts
Labels: scope: backend, -PR: awaiting review, prio: high

#10360 replyto-microsoft-fix
  packages/twenty-front/src/modules/activities/emails/right-drawer/components/RightDrawerEmailThread.tsx
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
  packages/twenty-front/src/modules/activities/emails/types/MessageChannelMessageAssociation.ts
Labels: -PR: awaiting review, prio: high

#10361 Deduplicate-emails
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
Labels: -PR: awaiting review

#10365 fix deleteCurrentWorkspace resolver output
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
Labels: -PR: awaiting review

#10352 Store the current flow definition in a state to not depend on a specific workflow version
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizerContent.tsx
  packages/twenty-front/src/modules/workflow/hooks/useFlowOrThrow.ts
  packages/twenty-front/src/modules/workflow/states/flowState.ts
  packages/twenty-front/src/modules/workflow/states/workflowVersionIdState.ts
  packages/twenty-front/src/modules/workflow/utils/getStepDefinitionOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowEditStepContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowViewStepContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/hooks/useAvailableVariablesInWorkflowStep.ts
Labels: -PR: awaiting review, run-e2e

#10371 Fix N+1 featureFlags
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.ts
Labels: -PR: awaiting review

#10314 refactor + new account sync metrics + isolating health status inside folder admin-panel > health-status
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthMessageSyncCountersTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminHealthStatusRightContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTabContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsHealthStatusListCard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getSystemHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/ConnectedAccountHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/DatabaseAndRedisHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthAccountSyncCountersTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthStatusRightContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminIndicatorHealthStatusContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminQueueExpandableContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminQueueHealthButtons.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsHealthStatusListCard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/contexts/SettingsAdminIndicatorHealthContext.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/graphql/queries/getIndicatorHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/health-status/graphql/queries/getSystemHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useGetUptoDateHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/AdminHealthService.ts
  packages/twenty-front/src/modules/settings/components/SettingsCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListCard.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListItemCardContent.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminIndicatorHealthStatus.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel-health.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel-health.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/constants/health-indicators.constants.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-health-indicator.input.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-health-service-data.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-indicator-health-status.input.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-worker-queue-health.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/system-health.dto.ts
  packages/twenty-server/src/engine/core-modules/health/constants/health-error-messages.constants.ts
  packages/twenty-server/src/engine/core-modules/health/constants/metrics-failure-rate-threshold.const.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/health.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/metrics.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/health.controller.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/metrics.controller.ts
  packages/twenty-server/src/engine/core-modules/health/enums/health-indicator-id.enum.ts
  packages/twenty-server/src/engine/core-modules/health/enums/health-service-name.enum.ts
  packages/twenty-server/src/engine/core-modules/health/health-cache.service.ts
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/connected-account.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/message-sync.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/connected-account.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/message-sync.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/worker.health.ts
  packages/twenty-server/src/engine/core-modules/health/types/account-sync-metrics.types.ts
  packages/twenty-server/src/engine/core-modules/health/types/health-counter-cache-keys.type.ts
  packages/twenty-server/src/engine/core-modules/health/types/worker-queue-health.type.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/common/calendar-common.module.ts
  packages/twenty-server/src/modules/calendar/common/services/calendar-channel-sync-status.service.ts
Labels: -PR: awaiting review

#10378 Enhance ActiveWorkspaceCommand to order, limit and startFrom workspaceId
  packages/twenty-server/src/database/commands/active-workspaces.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-migrate-rich-text-field.command.ts
Labels: -PR: awaiting review

#10383 Fix open record in setting for command menu v1
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownViewSettingsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-index/states/selectors/recordIndexOpenRecordInSelector.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
Labels: -PR: awaiting review

#10382 [FE] Improve Read-only field behavior
  packages/twenty-front/src/modules/activities/notes/components/Notes.tsx
  packages/twenty-front/src/modules/activities/tasks/components/AddTaskButton.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx
  packages/twenty-front/src/modules/settings/roles/hooks/useHasObjectReadOnlyPermission.ts
Labels: -PR: awaiting review

#10380 cleaning workspace job - fix on soft delete condition
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: awaiting review

#10384 Only display record actions inside the RecordIndexActionMenuDropdown
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuDropdown.tsx
Labels: -PR: awaiting review

#10388 Fix autogrow input whitespace bug
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChip.tsx
  packages/twenty-ui/src/utilities/dimensions/components/AutogrowWrapper.tsx
Labels: -PR: awaiting review

#10392 Fix command menu selectable items ordering
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
Labels: -PR: awaiting review

#10368 Removed sort definitions
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useColumnDefinitionsFromFieldMetadata.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useColumnDefinitionsFromFieldMetadata.ts
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsSortDefinitions.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/states/availableSortDefinitionsComponentState.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/types/SortDefinition.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useSetRecordIdsForColumn.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexViewBarEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useFindManyRecordIndexTableParams.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleColumnSort.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts
  packages/twenty-front/src/modules/object-record/record-sort/hooks/useSortableFieldMetadataItemsInRecordIndexContext.ts
  packages/twenty-front/src/modules/object-record/record-sort/types/RecordSort.ts
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/constants/SignInBackgroundMockSortDefinitions.ts
  packages/twenty-front/src/modules/views/components/EditableSortChip.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/components/ViewBarRecordSortEffect.tsx
  packages/twenty-front/src/modules/views/components/ViewBarSortEffect.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewSortsToCurrentRecordSorts.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyViewSortsToCurrentRecordSorts.test.tsx
  packages/twenty-front/src/modules/views/hooks/useApplyCurrentViewSortsToCurrentRecordSorts.ts
  packages/twenty-front/src/modules/views/hooks/useApplyViewSortsToCurrentRecordSorts.ts
  packages/twenty-front/src/modules/views/hooks/useInitViewBar.ts
  packages/twenty-front/src/modules/views/hooks/useUpsertCombinedViewSorts.ts
  packages/twenty-front/src/modules/views/states/availableSortDefinitionsComponentState.ts
  packages/twenty-front/src/modules/views/utils/__tests__/viewMapFunctions.test.ts
  packages/twenty-front/src/modules/views/utils/getQueryVariablesFromView.ts
  packages/twenty-front/src/modules/views/utils/mapViewSortsToSorts.ts
Labels: -PR: awaiting review

#10395 Email translation and snackbar translation
  packages/twenty-emails/src/emails/clean-suspended-workspace.email.tsx
  packages/twenty-emails/src/emails/password-reset-link.email.tsx
  packages/twenty-emails/src/emails/password-update-notify.email.tsx
  packages/twenty-emails/src/emails/send-email-verification-link.email.tsx
  packages/twenty-emails/src/emails/send-invite-link.email.tsx
  packages/twenty-emails/src/emails/warn-suspended-workspace.email.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
  packages/twenty-front/src/modules/auth/hooks/__tests__/useVerifyLogin.test.ts
  packages/twenty-front/src/modules/auth/hooks/useVerifyLogin.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useHandleResetPassword.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResendEmailVerificationToken.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResetPassword.ts
  packages/twenty-front/src/modules/object-record/record-field/components/LightCopyIconButton.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/PhonesFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/PhonesFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminWorkspaceContent.tsx
  packages/twenty-front/src/modules/settings/developers/components/ApiKeyInput.tsx
  packages/twenty-front/src/modules/settings/developers/components/__stories__/ApiKeyInput.stories.tsx
  packages/twenty-front/src/modules/settings/security/components/SSO/SettingsSSOOIDCForm.tsx
  packages/twenty-front/src/modules/settings/security/components/SSO/SettingsSSOSAMLForm.tsx
  packages/twenty-front/src/modules/settings/security/components/SSO/SettingsSecuritySSORowDropdownMenu.tsx
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowVersion.tsx
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
  packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainRecords.tsx
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/reset-password.service.ts
  packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
  packages/twenty-server/src/engine/core-modules/email-verification/services/email-verification.service.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: wip

#10343 Add error management to the Billing Package
  packages/twenty-server/src/database/typeorm/core/migrations/billing/1739981257356-addOnUpdateInEntitlements.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-entitlement.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
Labels: -PR: ready to merge

#10430 [permissions] Move SettingsPermissions from twenty-shared to twenty-server
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/settings/hooks/__tests__/useSettingsNavigationItems.test.tsx
  packages/twenty-front/src/modules/settings/hooks/useSettingsNavigationItems.tsx
  packages/twenty-front/src/modules/settings/roles/hooks/useHasSettingsPermission.ts
  packages/twenty-front/src/modules/settings/roles/hooks/useSettingsPermissionMap.ts
  packages/twenty-front/src/pages/settings/roles/components/RolePermissions.tsx
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/constants/system-objects-permissions-requirements.constant.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.resolver.ts
  packages/twenty-server/src/engine/core-modules/sso/sso.resolver.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/workspace-invitation.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/guards/settings-permissions.guard.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/constants/settings-permissions.constants.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.resolver.ts
  packages/twenty-shared/src/constants/index.ts
Labels: -PR: awaiting author

#10439 Data changes to prepare for workspaceMember page
  packages/twenty-front/src/modules/activities/tasks/hooks/__tests__/useCompleteTask.test.tsx
  packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPickerEffect.tsx
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/useCreateFavorite.ts
  packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts
  packages/twenty-front/src/modules/favorites/hooks/useFavoritesMetadata.ts
  packages/twenty-front/src/modules/favorites/hooks/usePrefetchedFavoritesData.ts
  packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts
  packages/twenty-front/src/modules/favorites/types/Favorite.ts
  packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/personFragments.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useToggleEditOnlyInput.test.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/search/hooks/__mocks__/useFilteredSearchRecordQuery.ts
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerOptionDropdown.tsx
  packages/twenty-front/src/testing/mock-data/favorite.ts
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/modules/favorite/standard-objects/favorite.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/favorites.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/search-favorites.integration-spec.ts
Labels: -PR: awaiting review

#10444 Add default role to workspace
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/states/currentWorkspaceState.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFieldMetadataItem.test.tsx
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/workspace/graphql/mutations/updateWorkspace.ts
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-front/src/pages/settings/roles/components/RolePermissionsObjectsTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/components/Roles.tsx
  packages/twenty-front/src/pages/settings/roles/components/RolesDefaultRole.tsx
  packages/twenty-front/src/pages/settings/roles/components/RolesTableHeader.tsx
  packages/twenty-front/src/pages/settings/roles/components/RolesTableRow.tsx
  packages/twenty-server/src/database/typeorm/core/migrations/common/1740390801418-addDefaultRoleToWorkspace.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/dtos/update-workspace-input.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.module.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/input/components/Checkbox.tsx
Labels: -PR: awaiting review

#10456 322 compact command chips dropdown
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipGroups.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipGroupsWithRecordSelection.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuContextChipGroupsDropdownId.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-ui/src/navigation/menu-item/components/MenuItem.tsx
  packages/twenty-ui/src/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
Labels: run-e2e, -PR: ready to merge

#10482 Remove current workspace member from role assignment picker
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateReadOnly.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentConfirmationModal.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentConfirmationModalSubtitle.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentTableHeader.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/pages/settings/roles/role-assignment/types/RoleAssignmentConfirmationModalSelectedWorkspaceMember.ts
  packages/twenty-front/src/pages/settings/roles/role-permissions/components/RolePermissions.tsx
  packages/twenty-front/src/pages/settings/roles/role-permissions/components/RolePermissionsObjectsTableHeader.tsx
  packages/twenty-front/src/pages/settings/roles/role-permissions/components/RolePermissionsObjectsTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/role-permissions/components/RolePermissionsSettingsTableHeader.tsx
  packages/twenty-front/src/pages/settings/roles/role-permissions/components/RolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/role-settings/components/RoleSettings.tsx
Labels: -PR: awaiting review

#10485 Fix thread pagination
  packages/twenty-server/src/engine/core-modules/messaging/services/timeline-messaging.service.ts
Labels: -PR: awaiting review

#10493 [BUGFIX] Create optimistic cache generate `recordGqlFields` from prefilled record
  packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
Labels: -PR: awaiting review

#10499 [Refactor] `generateDepthOneRecordGqlFieldsFromRecord`
  packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/computeDepthOneRecordGqlFieldsFromRecord.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/generateDepthOneRecordGqlFields.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/computeDepthOneRecordGqlFieldsFromRecord.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/generateDepthOneRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useAttachRelatedRecordFromRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
Labels: -PR: awaiting review

#10508 Fix record page context store instance id
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuComponentInstanceId.ts
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuPreviousComponentInstanceId.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHotKeys.ts
  packages/twenty-front/src/modules/command-menu/hooks/useResetPreviousCommandMenuContext.ts
  packages/twenty-front/src/modules/context-store/components/MainContextStoreProvider.tsx
  packages/twenty-front/src/modules/context-store/components/MainContextStoreProviderEffect.tsx
  packages/twenty-front/src/modules/context-store/constants/MainContextStoreInstanceId.tsx
  packages/twenty-front/src/modules/context-store/states/mainContextStoreComponentInstanceId.ts
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx
  packages/twenty-front/src/modules/object-record/record-group/hooks/useSetRecordGroup.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerGater.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/testing/decorators/ContextStoreDecorator.tsx
Labels: -PR: awaiting review

#10366 Create a right drawer for viewing steps in workflow runs
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuPagesConfig.tsx
  packages/twenty-front/src/modules/command-menu/types/CommandMenuPages.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerRouter.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageIcons.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/constants/RightDrawerPageTitles.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/ComponentByRightDrawerPage.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/types/RightDrawerPages.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/utils/mapRightDrawerPageToCommandMenuPage.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainerTabListContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/tab/hooks/useTabList.ts
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizerContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useWorkflowSelectedNodeOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowEditStepContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepBody.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepHeader.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/constants/WorkflowRunStepSidePanelTabListComponentId.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunctionFields.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowReadonlyActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/hooks/useAvailableVariablesInWorkflowStep.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review, run-e2e

#10497 Fix command menu closing and opening
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/states/isCommandMenuClosingState.ts
Labels: -PR: awaiting review

#10510 [FIX] Optimistically compute `position` only for `objectMetadataItem` that has the field
  packages/twenty-front/src/modules/object-metadata/utils/hasObjectMetadataItemFieldCreatedBy.ts
  packages/twenty-front/src/modules/object-metadata/utils/hasObjectMetadataItemPositionField.ts
  packages/twenty-front/src/modules/object-metadata/utils/hasPositionField.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordBoardRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticCreateRecordBaseRecordInput.ts
  packages/twenty-front/src/types/EachTestingContext.ts
  packages/twenty-front/src/utils/array/__tests__/buildRecordFromKeysWithSameValue.test.ts
Labels: -PR: awaiting review

#10503 add stories to roles components
  packages/twenty-front/src/modules/activities/emails/utils/__tests__/getDisplayNameFromParticipant.test.ts
  packages/twenty-front/src/modules/apollo/services/__tests__/apollo.factory.test.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecords.test.tsx
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchRecordQuery.test.tsx
  packages/twenty-front/src/modules/settings/roles/components/Roles.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesDefaultRole.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/components/__stories__/Roles.stories.tsx
  packages/twenty-front/src/modules/settings/roles/components/__stories__/RolesDefaultRole.stories.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentConfirmationModal.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentConfirmationModalSubtitle.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/types/RoleAssignmentConfirmationModalSelectedWorkspaceMember.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissions.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsObjectsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsObjectsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-settings/components/RoleSettings.tsx
  packages/twenty-front/src/modules/settings/roles/types/RolePermissionsObjectPermission.ts
  packages/twenty-front/src/modules/settings/roles/types/RolePermissionsSettingPermission.ts
  packages/twenty-front/src/modules/ui/theme/hooks/__tests__/useColorScheme.test.tsx
  packages/twenty-front/src/modules/workspace-member/types/WorkspaceMember.ts
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-front/src/pages/settings/roles/__stories__/SettingsRoleEdit.stories.tsx
  packages/twenty-front/src/pages/settings/roles/__stories__/SettingsRoles.stories.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/roles.ts
Labels: -PR: awaiting review

#10517 Remove export action from the view options menu
  packages/twenty-e2e-testing/lib/pom/mainPage.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
Labels: -PR: awaiting review, run-e2e

#10519 [REFACTOR] remove `isRemote` assertion from `hasFieldPosition` util
  packages/twenty-front/src/modules/object-metadata/utils/hasObjectMetadataItemPositionField.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/turnSortsIntoOrderBy.ts
Labels: -PR: awaiting review

#10505 RecordPicker refactoring part 3: remove effects
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditMode.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditModeMultiRecordsEffect.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditModeMultiRecordsSearchFilterEffect.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/activities/inline-cell/components/MultipleObjectRecordOnClickOutsideEffect.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/__tests__/useMultiObjectRecordsQueryResultFormattedAsObjectRecordForSelectArray.test.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/__tests__/useMultiObjectSearchQueryResultFormattedAsObjectRecordsMap.test.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useMultiObjectRecordsQueryResultFormattedAsObjectRecordForSelectArray.ts
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useMultiObjectSearch.ts
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useMultiObjectSearchQueryResultFormattedAsObjectRecordsMap.ts
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useMultiObjectSearchSelectedItemsQuery.ts
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useOpenActivityTargetInlineCellEditMode.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useCombinedFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useCombinedGetTotalCount.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/types/MultiObjectRecordQueryResult.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/formatMultiObjectRecordSearchResults.ts
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldContext.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationFromManyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationPicker.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationPickerInitialValueEffect.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContext.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/hooks/useInlineCell.ts
  packages/twenty-front/src/modules/object-record/record-picker-morph-legacy/components/ActivityTargetInlineCellEditModeMultiRecordsSearchFilterEffect.tsx
  packages/twenty-front/src/modules/object-record/record-picker/components/MultipleRecordPicker.tsx
  packages/twenty-front/src/modules/object-record/record-picker/components/__stories__/SingleRecordPicker.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx
  packages/twenty-front/src/testing/decorators/RecordPickerDecorator.tsx
Labels: -PR: wip, -PR: awaiting author

#10523 Move workflow versions and steps building to workflow-builder folder
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-builder.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/workflow-api.module.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.entity.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.module.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/types/input-schema.type.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/types/output-schema.type.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-object-record-event.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-object-record.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/should-generate-field-fake-value.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/workflow-schema.module.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/workflow-schema.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version/workflow-step/workflow-version-step.module.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version/workflow-version.module.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version/workflow-version.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/types/workflow-action-settings.type.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/types/workflow-trigger.type.ts
Labels: -PR: awaiting review, run-e2e

#10540 Fix contact creation
  packages/twenty-server/src/modules/contact-creation-manager/utils/filter-out-contacts-from-company-or-workspace.util.ts
Labels: -PR: awaiting review

#10507 add new @WorkspaceIsSearchable decorator + updates services + add migration command
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useMultiObjectSearch.ts
  packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts
  packages/twenty-front/src/modules/object-metadata/graphql/queries.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useDeleteOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useLimitPerMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useAggregateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/buildRecordGqlFieldsAggregateForView.test.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/generateAggregateQuery.test.ts
  packages/twenty-front/src/modules/object-record/utils/isObjectMetadataItemSearchable.ts
  packages/twenty-front/src/modules/object-record/utils/isObjectMetadataItemSearchableInCombinedRequest.ts
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-server/src/database/commands/migration-command/batch-maintained-workspaces-migration-command.runner.ts
  packages/twenty-server/src/database/commands/migration-command/maintained-workspaces-migration-command.runner.ts
  packages/twenty-server/src/database/commands/migration-command/migration-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-fix-body-v2-view-field-position.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-limit-amount-of-view-field.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-migrate-rich-text-field.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-standardization-of-actor-composite-context-type.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-add-tasks-assigned-to-me-view.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-is-searchable-for-custom-object-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-search-vector-on-note-and-task-entities.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-update-default-view-record-opening-on-workflow-objects.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1740478150675-addIsSearchableColumnInObjectMetadataTable.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/__mocks__/mockPersonObjectMetadata.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver-builder.service.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-customer-data.command.ts
  packages/twenty-server/src/engine/core-modules/event-emitter/utils/__tests__/object-record-changed-values.spec.ts
  packages/twenty-server/src/engine/core-modules/global-search/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts
  packages/twenty-server/src/engine/core-modules/global-search/__tests__/global-search.service.spec.ts
  packages/twenty-server/src/engine/core-modules/global-search/services/global-search.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/object-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/object-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-entity.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-is-searchable.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/workspace-entity-metadata-args.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
  packages/twenty-server/src/utils/typed-reflect.ts
Labels: -PR: awaiting review

#10542 [ENHC] Create `Yarn` constraints to validate `node` version
  .yarnrc.yml
  package.json
  yarn.config.cjs
  yarn.lock
Labels: -PR: awaiting review, run-e2e

#10555 Prevent command menu backspace shortcut on V1
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHotKeys.ts
Labels: -PR: awaiting review

#10557 [REG/FEAT] Sync metadata after upgrade
  packages/twenty-server/src/database/commands/migration-command/create-upgrade-all-command.factory.ts
  packages/twenty-server/src/database/commands/migration-command/migration-command.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/services/sync-workspace-logger.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/services/sync-workspace-logger.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/workspace-sync-metadata-commands.module.ts
Labels: -PR: wip, -PR: awaiting author

#10573 add missed search decorator
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#10576 Add PageHeaderOpenCommandMenuButton on Record index page header for command menu v1
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/ui/layout/page-header/components/PageHeaderOpenCommandMenuButton.tsx
Labels: -PR: awaiting review

#10583 add sentry monitoring + update cron pattern to each hour
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.cron.pattern.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.job.ts
Labels: -PR: awaiting review

#10582 migrate rich text v1 workspace + move relation migration to 0.44
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-rich-text-content-patch.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-44/0-44-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-44/0-44-upgrade-version.module.ts
Labels: -PR: awaiting review

#10592 Refactor upgrade commands
  packages/twenty-server/src/database/commands/command-runners/active-or-suspended-workspaces-migration.command-runner.ts
  packages/twenty-server/src/database/commands/command-runners/migration.command-runner.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/data-seed-demo-workspace-cron-pattern.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/start-data-seed-demo-workspace.cron.command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/crons/stop-data-seed-demo-workspace.cron.command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/data-seed-demo-workspace-command.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/jobs/data-seed-demo-workspace.job.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/migration-command/batch-maintained-workspaces-migration-command.runner.ts
  packages/twenty-server/src/database/commands/migration-command/create-upgrade-all-command.factory.ts
  packages/twenty-server/src/database/commands/migration-command/decorators/migration-command.decorator.ts
  packages/twenty-server/src/database/commands/migration-command/interfaces/migration-command.interface.ts
  packages/twenty-server/src/database/commands/migration-command/migration-command.constants.ts
  packages/twenty-server/src/database/commands/migration-command/migration-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-add-tasks-assigned-to-me-view.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-migrate-is-searchable-for-custom-object-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-migrate-rich-text-content-patch.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-migrate-search-vector-on-note-and-task-entities.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-update-default-view-record-opening-on-workflow-objects.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-44/0-44-initialize-permissions.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-44/0-44-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-44/0-44-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-fix-body-v2-view-field-position.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-limit-amount-of-view-field.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-migrate-rich-text-field.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-standardization-of-actor-composite-context-type.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-migrate-is-searchable-for-custom-object-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-43/0-43-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-44/0-44-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-44/0-44-upgrade-version.module.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-customer-data.command.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-plans-data.command.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-cache/services/workspace-metadata-cache.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-version/services/workspace-metadata-version.service.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/clean-suspended-workspaces.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/commands/sync-workspace-metadata.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.module.ts
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review
