Repository twentyhq/twenty, pull requests merged in 2025-07, with the labels that each got.

#12968 Fix Raw Json Null Error
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
Labels: -PR: awaiting review

#12963 Fix bug date picker month and year dropdown not clickable
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateTimeFieldInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/AbsoluteDatePickerHeader.tsx
Labels: -PR: awaiting review

#12990 Scaffold filters creation and deletion
  packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramDefaultEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEdgeV2.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEdgeV2Content.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramEdgeV2Content.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/transformFilterNodesAsEdges.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/addEdgeOptions.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowVersionDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/transformFilterNodesAsEdges.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepNodeDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/__tests__/useCreateStep.test.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/__tests__/useWorkflowActionHeader.test.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionHeaderTypeOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionIconColorOrThrow.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
Labels: -PR: awaiting review

#12998 Dates beyond 2030 and autoscroll in select
  packages/twenty-front/src/modules/settings/components/SettingsOptions/__stories__/SettingsOptionCardContentSelect.stories.tsx
  packages/twenty-front/src/modules/ui/input/components/Select.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/date/components/AbsoluteDatePickerHeader.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/select/types.ts
Labels: -PR: ready to merge

#12904 fix: update customize fields navigation to go directly to object detail page
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderPlusButtonContent.tsx
Labels: -PR: awaiting review

#13004 feat(ai): add mcp integration
  packages/twenty-front/public/images/integrations/mcp.svg
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationComponent.tsx
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationMcp.ts
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationWindmill.ts
  packages/twenty-front/src/modules/settings/integrations/hooks/useSettingsIntegrationCategories.ts
  packages/twenty-front/src/modules/settings/integrations/types/SettingsIntegration.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/hooks/useAgentUpdateFormState.ts
  packages/twenty-server/src/engine/core-modules/ai/ai.module.ts
  packages/twenty-server/src/engine/core-modules/ai/constants/mcp.const.ts
  packages/twenty-server/src/engine/core-modules/ai/controllers/ai.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/controllers/ai.controller.ts
  packages/twenty-server/src/engine/core-modules/ai/controllers/mcp.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/controllers/mcp.controller.ts
  packages/twenty-server/src/engine/core-modules/ai/decorators/string-or-number.ts
  packages/twenty-server/src/engine/core-modules/ai/dtos/json-rpc.ts
  packages/twenty-server/src/engine/core-modules/ai/services/ai.service.ts
  packages/twenty-server/src/engine/core-modules/ai/services/mcp.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/mcp.service.ts
  packages/twenty-server/src/engine/core-modules/ai/services/tool.service.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/wrap-jsonrpc-response.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-tool.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.exception.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.resolver.ts
  packages/twenty-server/test/integration/graphql/suites/agent/agent.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/update-feature-flag-factory.util.ts
  packages/twenty-server/test/integration/metadata/suites/agent/agent-tool.service.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/agent/utils/agent-tool-test-utils.ts
  packages/twenty-shared/src/types/ObjectRecordsPermissionsByRoleId.ts
  packages/twenty-ui/src/display/icon/providers/internal/AllIcons.ts
  packages/twenty-website/src/content/user-guide/functions/integrations.mdx
Labels: -PR: awaiting review

#13045 Prevent testing malformed workflows and allow testing workflows with cron trigger
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.tsx
Labels: -PR: awaiting review

#12901 Import - Improve phone validation
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/__tests__/buildRecordFromImportedStructuredRow.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSpreadSheetFieldValidationDefinitions.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/transform-phones-value.util.ts
  packages/twenty-shared/package.json
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/utils/validation/phones-value/getCountryCodesForCallingCode.ts
  packages/twenty-shared/src/utils/validation/phones-value/index.ts
  packages/twenty-shared/src/utils/validation/phones-value/isValidCountryCode.ts
  yarn.lock
Labels: -PR: awaiting review

#13026 [POC] Workspace migration builder v2
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-object-input.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/deleted-created-updated-matrix-dispatcher.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/get-workspace-migration-v2-field-actions.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/get-workspace-migration-v2-object-actions.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-field-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-object-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-metadata-migration-runner/workspace-metadata-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-migration-runner-v2.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-schema-migration-runner/workspace-schema-migration-runner.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-v2.module.ts
Labels: -PR: awaiting author

#13068 fix: blockquote icon in slash menu
  packages/twenty-front/src/modules/activities/blocks/utils/getSlashMenu.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/index.ts
Labels: -PR: awaiting review

#13076 Migration builder v2 handle `RELATION` through `fields` actions
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/from-to.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-action-common-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-field-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-field-input.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-index-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-object-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-object-input.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-uniqueness-action-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/workspace-migration-v2.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-relations-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/compute-updated-object-metadata-deleted-created-updated-field-matrix.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/deleted-created-updated-matrix-dispatcher.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/get-workspace-migration-v2-field-actions.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/get-workspace-migration-v2-object-actions.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/workspace-migration-field-metadata-input-comparator.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/utils/workspace-migration-object-metadata-input-comparator.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-field-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-object-actions-builder.ts
Labels: -PR: awaiting review

#12734 fix: prevent LinkAvatarChip from triggering page reload when table cells or inline cells are in edit mode
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPicker.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/MultiSelectInput.tsx
  packages/twenty-front/src/modules/ui/input/components/SelectInput.tsx
Labels: -PR: awaiting review

#13021 fieldmetadatatype + featurelfag creation
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsObjectNewFieldSelector.tsx
  packages/twenty-front/src/pages/settings/data-model/constants/DefaultIconsByFieldType.ts
  packages/twenty-server/src/database/typeorm/core/migrations/common/1751558024634-morph-index-update.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/extend-object-type-definition-v2.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/relation-type-v2.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/services/type-mapper.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/generate-fields.utils.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/__tests__/map-field-metadata-to-graphql-query.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/utils/map-field-metadata-to-graphql-query.utils.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/generate-random-field-value.util.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/create-field.input.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/__tests__/before-update-one-field.hook.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/before-update-one-field.hook.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/relation/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-morph-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/field-metadata-validation.service.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/build-updatable-standard-field-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/prepare-custom-field-metadata-for-options.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/prepare-field-metadata-for-creation.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/resolve-overridable-string.util.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-table/remote-table.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/factories.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/morph-relation-column-action.factory.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-column.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/entity-schema-relation.factory.ts
  packages/twenty-server/src/engine/twenty-orm/utils/determine-schema-relation-details.util.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/core/utils/seed-feature-flags.util.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/metadata/services/dev-seeder-metadata.service.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/create-one-field-metadata.integration-spec.ts
  packages/twenty-shared/src/types/FieldMetadataType.ts
Labels: -PR: awaiting review

#13092 Update yarn and remove explicit hardened mode
  .github/workflows/actions/yarn-install/action.yaml
  .yarn/releases/yarn-4.4.0.cjs
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  package.json
  packages/twenty-server/src/engine/core-modules/serverless/drivers/layers/engine/.yarn/releases/yarn-4.4.0.cjs
  packages/twenty-server/src/engine/core-modules/serverless/drivers/layers/engine/.yarn/releases/yarn-4.9.2.cjs
  packages/twenty-server/src/engine/core-modules/serverless/drivers/layers/engine/.yarnrc.yml
Labels: -PR: awaiting review

#13106 Replace hotkey scopes by focus stack (Part 5 - Form field Inputs, Pages, Dialog ...)
  packages/twenty-front/src/hooks/useHotkeyScopeOnMount.ts
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenuOpenContent.tsx
  packages/twenty-front/src/modules/keyboard-shortcut-menu/hooks/__tests__/useKeyboardShortcutMenu.test.tsx
  packages/twenty-front/src/modules/keyboard-shortcut-menu/hooks/useKeyboardShortcutMenu.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnDropdownMenu.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownOptionsContent.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormBooleanFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateTimeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormFieldInputInnerContainer.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormMultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormNumberFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormRawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSingleRecordPicker.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormUuidFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-index/constants/RecordIndexFocusId.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useResetFocusStackToRecordIndex.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyEscapeHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFocusKeyboardEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateDropdownSubmenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterMenuContent.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionSettingsTab.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTab.tsx
  packages/twenty-front/src/modules/types/PageFocusId.ts
  packages/twenty-front/src/modules/ui/feedback/dialog-manager/components/Dialog.tsx
  packages/twenty-front/src/modules/ui/feedback/dialog-manager/components/DialogManagerEffect.tsx
  packages/twenty-front/src/modules/ui/feedback/dialog-manager/constants/DialogFocusId.ts
  packages/twenty-front/src/modules/ui/feedback/dialog-manager/hooks/useDialogManager.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerInput.tsx
  packages/twenty-front/src/modules/ui/utilities/focus/types/FocusComponentType.ts
  packages/twenty-front/src/modules/ui/utilities/hotkey/constants/DebugHotkeyScope.ts
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/__tests__/useScopedHotKeys.test.tsx
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useScopedHotkeyCallback.ts
  packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useScopedHotkeys.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/hooks/useAgentChat.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowEditActionFormBuilder.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowFormEmptyMessage.tsx
  packages/twenty-front/src/pages/onboarding/CreateProfile.tsx
  packages/twenty-front/src/pages/onboarding/InviteTeam.tsx
  packages/twenty-front/src/pages/onboarding/SyncEmails.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionsNew.tsx
  packages/twenty-front/src/testing/decorators/RootDecorator.tsx
Labels: -PR: awaiting review

#13099 Prevent relation update from settings
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/__tests__/before-update-one-field.hook.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/before-update-one-field.hook.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/__tests__/resolve-overridable-string.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/resolve-overridable-string.util.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/__snapshots__/failing-field-metadata-relation-creation.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/__snapshots__/failing-field-metadata-relation-update.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/failing-field-metadata-relation-creation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/failing-field-metadata-relation-update.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata.integration-spec.ts
Labels: -PR: awaiting review

#13078 Connect logic in Workspace Entity Manager
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/workspace-query-runner-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/input-type-definition.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/relation-connect-input-type-definition.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/interfaces/workspace-build-schema-optionts.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/type-definitions.generator.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/generate-fields.utils.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema.factory.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/types/query-deep-partial-entity-with-relation-connect.type.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/types/relation-connect-query-config.type.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.ts
  packages/twenty-server/src/engine/twenty-orm/exceptions/twenty-orm.exception.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/engine/twenty-orm/utils/__tests__/compute-relation-connect-query-configs.util.spec.ts
  packages/twenty-server/src/engine/twenty-orm/utils/__tests__/create-sql-where-tuple-in-clause.util.spec.ts
  packages/twenty-server/src/engine/twenty-orm/utils/__tests__/get-record-to-connect-fields.util.spec.ts
  packages/twenty-server/src/engine/twenty-orm/utils/compute-relation-connect-query-configs.util.ts
  packages/twenty-server/src/engine/twenty-orm/utils/create-sql-where-tuple-in-clause.utils.ts
  packages/twenty-server/src/engine/twenty-orm/utils/format-data.util.ts
  packages/twenty-server/src/engine/twenty-orm/utils/get-associated-relation-field-name.util.ts
  packages/twenty-server/src/engine/twenty-orm/utils/get-object-metadata-from-entity-target.util.ts
  packages/twenty-server/src/engine/twenty-orm/utils/get-record-to-connect-fields.util.ts
  packages/twenty-server/src/engine/twenty-orm/utils/twenty-orm-graphql-api-exception-handler.util.ts
  packages/twenty-server/test/integration/constants/test-company-ids.constants.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/relation-connect.integration-spec.ts
Labels: -PR: awaiting review

#13048 feat: add auto-scroll to selected menu items in CustomSlashMenu
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItems.tsx
  packages/twenty-front/src/modules/ui/input/constants/SlashMenuListId.ts
  packages/twenty-front/src/modules/ui/input/editor/components/CustomSlashMenu.tsx
  packages/twenty-front/src/modules/ui/input/editor/components/CustomSlashMenuListItem.tsx
  packages/twenty-front/src/modules/ui/input/editor/components/types.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/components/SelectableListItem.tsx
Labels: -PR: awaiting author

#13149 Fix record table click outside
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFocusClickOutsideEffect.tsx
  packages/twenty-front/src/modules/ui/utilities/focus/states/currentFocusedItemSelector.ts
Labels: -PR: awaiting review

#13113 relation-integration-tests
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-migration.service.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/__snapshots__/failing-field-metadata-relation-creation.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/create-one-field-metadata.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/enum/create-one-field-metadata-enum.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/__snapshots__/failing-field-metadata-morph-relation-creation.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/create-one-field-metadata-morph-relation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/morph-relation/failing-field-metadata-morph-relation-creation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/__snapshots__/failing-field-metadata-relation-creation.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/__snapshots__/failing-field-metadata-relation-update.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/create-one-field-metadata-relation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/failing-field-metadata-relation-creation.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/failing-field-metadata-relation-update.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/utils/create-one-field-metadata.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/create-morph-relation-between-objects.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/create-relation-between-objects.util.ts
Labels: -PR: awaiting author

#13171 Refresh AI model setup
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/hooks/useAgentChat.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/ai-agent-action/utils/parseAgentStreamingChunk.ts
  packages/twenty-server/src/engine/core-modules/ai/ai.constants.ts
  packages/twenty-server/src/engine/core-modules/ai/ai.module-factory.ts
  packages/twenty-server/src/engine/core-modules/ai/ai.module.ts
  packages/twenty-server/src/engine/core-modules/ai/constants/ai-models.const.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/constants/ai-models.const.ts
  packages/twenty-server/src/engine/core-modules/ai/drivers/interfaces/ai-driver.interface.ts
  packages/twenty-server/src/engine/core-modules/ai/drivers/openai.driver.ts
  packages/twenty-server/src/engine/core-modules/ai/interfaces/ai.interface.ts
  packages/twenty-server/src/engine/core-modules/ai/services/ai-billing.service.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/services/ai-billing.service.ts
  packages/twenty-server/src/engine/core-modules/ai/services/ai-model-registry.service.ts
  packages/twenty-server/src/engine/core-modules/ai/services/ai.service.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-ai-model-by-id.util.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-ai-models-with-auto.util.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-ai-models-with-auto.util.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-default-model-config.util.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-default-model-config.util.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-effective-model-config.util.spec.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/get-effective-model-config.util.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/token/token.module.ts
  packages/twenty-server/src/engine/core-modules/client-config/services/client-config.service.spec.ts
  packages/twenty-server/src/engine/core-modules/client-config/services/client-config.service.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-execution.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent-streaming.service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/ai-agent/ai-agent-action.module.ts
Labels: -PR: wip, -PR: awaiting author

#13136 Workspace migration v2 testing
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/__tests__/get-flat-field-metadata.mock.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/__tests__/get-flat-index-field-metadata.mock.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/__tests__/get-flat-index-metadata.mock.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/__tests__/get-flat-object-metadata.mock.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/extract-record-typeorm-relation-properties.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-field-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-index-field-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-index-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/flat-object-metadata.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/types/metadata-entities-relation-targets.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/utils/flat-field-metadata-comparator.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/__snapshots__/workspace-migration-builder.spec.ts.snap
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-field-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-index-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/common/workspace-migration-builder-object-test-case.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/types/workspace-migration-builder-test-case.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-indexes-builder.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/workspace-migration-v2-relations-builder.spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/relation/failing-field-metadata-relation-creation.integration-spec.ts
  packages/twenty-server/test/utils/extract-record-ids-and-dates-as-expect-any.ts
  packages/twenty-shared/src/testing/EachTestingContextFilter.ts
  packages/twenty-shared/src/testing/index.ts
  packages/twenty-shared/src/testing/types/EachTestingContext.type.ts
Labels: -PR: awaiting review

#13181 22 branches 3
  packages/twenty-front/src/modules/command-menu/hooks/useWorkflowCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStepContent.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getIsInputTabDisabled.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getIsOutputTabDisabled.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getShouldFocusNodeTab.ts
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/subscription/components/ListenRecordUpdatesEffect.tsx
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowRunOpeningInCommandMenuSideEffects.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useSetInitialWorkflowRunRightDrawerTab.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getNodeVariantFromStepRunStatus.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepNodeDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useUpdateWorkflowRunStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepContext.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepExecutionStatus.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepContext.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepExecutionStatus.ts
  packages/twenty-front/src/testing/mock-data/workflow-run.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/1-1/1-1-migrate-workflow-run-state.command.ts
  packages/twenty-server/src/engine/core-modules/cache-lock/with-lock.decorator.ts
  packages/twenty-server/src/engine/core-modules/message-queue/decorators/process.decorator.ts
  packages/twenty-server/src/engine/core-modules/message-queue/decorators/processor.decorator.ts
  packages/twenty-server/src/engine/core-modules/message-queue/message-queue.constants.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/utils/__tests__/can-execute-step.util.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/utils/can-execute-step.util.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/__tests__/workflow-executor.workspace-service.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.workspace-service.ts
  packages/twenty-shared/package.json
  packages/twenty-shared/project.json
  packages/twenty-shared/src/workflow/index.ts
  packages/twenty-shared/src/workflow/types/WorkflowRunStateStepInfos.ts
  packages/twenty-shared/src/workflow/utils/__tests__/getWorkflowRunContext.test.ts
  packages/twenty-shared/src/workflow/utils/getWorkflowRunContext.ts
  packages/twenty-shared/workflow/package.json
Labels: -PR: awaiting author

#13150 feat(ai): add mcp-metadata
  packages/twenty-front/public/images/integrations/integration-mcp-cover-dark.svg
  packages/twenty-front/public/images/integrations/integration-mcp-cover-light.svg
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/captcha/hooks/__tests__/useRequestFreshCaptchaToken.test.tsx
  packages/twenty-front/src/modules/settings/integrations/components/SettingsIntegrationMCP.tsx
  packages/twenty-front/src/modules/settings/integrations/constants/SettingsIntegrationMcp.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/integrations/SettingsIntegrationMCPPage.tsx
  packages/twenty-server/package.json
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/engine/api/mcp/controllers/mcp-metadata.controller.ts
  packages/twenty-server/src/engine/api/mcp/mcp.module.ts
  packages/twenty-server/src/engine/api/mcp/services/mcp-metadata.service.ts
  packages/twenty-server/src/engine/api/mcp/services/tools/create.tools.service.ts
  packages/twenty-server/src/engine/api/mcp/services/tools/delete.tools.service.ts
  packages/twenty-server/src/engine/api/mcp/services/tools/get.tools.service.ts
  packages/twenty-server/src/engine/api/mcp/services/tools/mcp-metadata-tools.service.ts
  packages/twenty-server/src/engine/api/mcp/services/tools/update.tools.service.ts
  packages/twenty-server/src/engine/api/mcp/utils/get-json-schema.ts
  packages/twenty-server/src/engine/api/rest/input-factories/ending-before-input.factory.ts
  packages/twenty-server/src/engine/api/rest/input-factories/limit-input.factory.ts
  packages/twenty-server/src/engine/api/rest/input-factories/starting-after-input.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/create-metadata-query.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/delete-metadata-query.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/find-many-metadata-query.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/find-one-metadata-query.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/get-metadata-variables.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/factories/update-metadata-query.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/metadata-query-builder.factory.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/utils/__tests__/parse-metadata-path.utils.spec.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/utils/fetch-metadata-fields.utils.ts
  packages/twenty-server/src/engine/api/rest/metadata/query-builder/utils/parse-metadata-path.utils.ts
  packages/twenty-server/src/engine/api/rest/metadata/types/metadata-entity.type.ts
  packages/twenty-server/src/engine/api/rest/metadata/types/metadata-query.type.ts
  packages/twenty-server/src/engine/api/rest/rest-api.module.ts
  packages/twenty-server/src/engine/api/rest/rest-api.service.ts
  packages/twenty-server/src/engine/api/rest/types/RequestContext.ts
  packages/twenty-server/src/engine/core-modules/ai/constants/mcp.const.ts
  packages/twenty-server/src/engine/core-modules/ai/dtos/json-rpc.ts
  packages/twenty-server/src/engine/core-modules/ai/services/mcp.service.ts
  packages/twenty-server/src/engine/core-modules/ai/utils/wrap-jsonrpc-response.util.ts
  packages/twenty-server/src/engine/core-modules/metrics/types/metrics-keys.type.ts
  packages/twenty-server/src/engine/core-modules/open-api/open-api.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/delete-field.input.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/delete-object.input.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache-storage.service.ts
  packages/twenty-server/src/utils/get-server-url.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/index.ts
  yarn.lock
Labels: -PR: awaiting author

#13246 Restrict queried columns to graphql-requested fields
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations-v2.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-duplicates-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/__tests__/build-columns-to-select.spec.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/build-columns-to-return.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/build-columns-to-select.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-select-query-builder.ts
Labels: -PR: awaiting author

#13270 Fix workspace folder deletion error
  packages/twenty-server/src/engine/core-modules/file-storage/drivers/interfaces/storage-driver.interface.ts
  packages/twenty-server/src/engine/core-modules/file-storage/drivers/local.driver.ts
  packages/twenty-server/src/engine/core-modules/file-storage/drivers/s3.driver.ts
  packages/twenty-server/src/engine/core-modules/file-storage/file-storage.service.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
Labels: -PR: awaiting review

#13095 Add Create related records to Record standard actions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/components/CreateRelatedRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/hooks/__tests__/useRelatedRecordActions.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/hooks/useRelatedRecordActions.ts
  packages/twenty-front/src/modules/action-menu/actions/types/ActionScope.ts
  packages/twenty-front/src/modules/action-menu/actions/types/ShouldBeRegisteredFunctionParams.ts
  packages/twenty-front/src/modules/action-menu/actions/utils/getActionConfig.ts
  packages/twenty-front/src/modules/action-menu/hooks/useRegisteredActions.ts
  packages/twenty-front/src/modules/action-menu/hooks/useShouldActionBeRegisteredParams.ts
  packages/twenty-front/src/modules/auth/states/objectPermissionsFamilySelector.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuActions.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useMatchingCommandMenuActions.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getObjectMetadataItemBySingularName.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectMetadataItemBySingularName.ts
  packages/twenty-server/src/engine/twenty-orm/custom.workspace-entity.ts
  packages/twenty-server/src/modules/company/standard-objects/company.workspace-entity.ts
  packages/twenty-server/src/modules/note/standard-objects/note.workspace-entity.ts
  packages/twenty-server/src/modules/opportunity/standard-objects/opportunity.workspace-entity.ts
  packages/twenty-server/src/modules/person/standard-objects/person.workspace-entity.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#13274 Workflow V1 Documentation (w/o video)
  packages/twenty-website/public/images/user-guide/workflows/workflow.png
  packages/twenty-website/src/content/user-guide/functions/workflows.mdx
Labels: -PR: awaiting author

#13282 Fix most e2e tests
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
  packages/twenty-e2e-testing/tests/workflow-visualizer.spec.ts
Labels: run-e2e

#13367 fix(approved-access-domain): Improve ux
  packages/twenty-emails/src/constants/DefaultWorkspaceLogo.ts
  packages/twenty-emails/src/emails/validate-approved-access-domain.email.tsx
  packages/twenty-front/src/modules/settings/security/components/approvedAccessDomains/SettingsSecurityApprovedAccessDomainValidationEffect.tsx
Labels: -PR: awaiting review

#13336 Add any field filter requests
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/components/DeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/components/DestroyMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/components/RestoreMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useSetGlobalCommandMenuContext.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCopyContextStoreAndActionMenuStates.ts
  packages/twenty-front/src/modules/command-menu/hooks/useResetContextStoreStates.ts
  packages/twenty-front/src/modules/command-menu/hooks/useSetGlobalCommandMenuContext.ts
  packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts
  packages/twenty-front/src/modules/context-store/states/contextStoreAnyFieldFilterValueComponentState.ts
  packages/twenty-front/src/modules/context-store/utils/__tests__/computeContextStoreFilters.test.ts
  packages/twenty-front/src/modules/context-store/utils/computeContextStoreFilters.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownAnyFieldSearchInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useActorFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-filter/states/anyFieldFilterValueComponentState.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/turnAnyFieldFilterIntoRecordGqlFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/compute-record-gql-operation-filter/turnRecordFilterIntoGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/createAnyFieldRecordFilterBaseProperties.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/filterSelectOptionsOfFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/turnAnyFieldFilterIntoRecordGqlFilter.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerContextStoreNumberOfSelectedRecordsEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexFiltersToContextStoreEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/useRecordIndexLazyFetchRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useFindManyRecordIndexTableParams.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useAggregateRecordsForHeader.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/views/components/AnyFieldSearchChip.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useGetRecordIndexTotalCount.ts
  packages/twenty-front/src/modules/views/hooks/useOpenAnyFieldSearchFilterFromViewBar.ts
  packages/twenty-front/src/modules/views/states/viewAnyFieldSearchValueComponentState.ts
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
Labels: -PR: awaiting review

#13356 Create view migration script
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/views-migration/migrate-views-to-core.command.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.spec.ts
Labels: -PR: awaiting review

#13318 fix: migrate webhook and API key REST endpoints to core schema
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/core-query-builder.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/core-query-builder.module.ts
  packages/twenty-server/src/engine/core-modules/api-key/api-key.module.ts
  packages/twenty-server/src/engine/core-modules/api-key/controllers/api-key.controller.ts
  packages/twenty-server/src/engine/core-modules/open-api/open-api.module.ts
  packages/twenty-server/src/engine/core-modules/open-api/open-api.service.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/open-api.service.ts
  packages/twenty-server/src/engine/core-modules/webhook/controllers/webhook.controller.ts
  packages/twenty-server/src/engine/core-modules/webhook/webhook.module.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-gate.decorator.ts
  packages/twenty-server/src/engine/twenty-orm/interfaces/gate.interface.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/is-gate-and-not-enabled.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/should-exclude-from-workspace-api.util.ts
  packages/twenty-server/src/modules/api-key/standard-objects/api-key.workspace-entity.ts
  packages/twenty-server/src/modules/webhook/standard-objects/webhook.workspace-entity.ts
Labels: -PR: awaiting review, -PR: ready to merge

#13348 fix: normalize version number using semver.coerce in admin panel version info
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
Labels: -PR: awaiting CI, -PR: ready to merge

#13385 Workspace Folder Deletion Error - add logs for investigation
  packages/twenty-server/src/engine/core-modules/file-storage/drivers/s3.driver.ts
  packages/twenty-server/src/engine/core-modules/file/jobs/file-workspace-folder-deletion.job.ts
Labels: -PR: awaiting review

#13461 Synchronization between Core Views and Workspace Views
  packages/twenty-server/src/database/commands/views-migration/migrate-views-to-core.command.ts
  packages/twenty-server/src/engine/metadata-modules/view/types/view-filter-value.type.ts
  packages/twenty-server/src/engine/metadata-modules/view/view-filter.entity.ts
  packages/twenty-server/src/modules/view/listeners/base-view-sync.listener.ts
  packages/twenty-server/src/modules/view/listeners/view-field.listener.ts
  packages/twenty-server/src/modules/view/listeners/view-filter-group.listener.ts
  packages/twenty-server/src/modules/view/listeners/view-filter.listener.ts
  packages/twenty-server/src/modules/view/listeners/view-group.listener.ts
  packages/twenty-server/src/modules/view/listeners/view-sort.listener.ts
  packages/twenty-server/src/modules/view/listeners/view.listener.ts
  packages/twenty-server/src/modules/view/services/view-field-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-filter-group-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-filter-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-group-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-sort-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-sync.service.ts
  packages/twenty-server/src/modules/view/utils/transform-view-filter-workspace-value-to-core-value.ts
  packages/twenty-server/src/modules/view/view.module.ts
  packages/twenty-server/src/modules/view/views.exception.ts
Labels: -PR: awaiting review

#13435 Cleanup remaining old component states
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/action-menu/states/recordIndexActionMenuDropdownPositionComponentState.ts
  packages/twenty-front/src/modules/activities/states/objectRecordsIdsMultiSelectComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/states/recordBoardObjectSingularNameComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useTriggerActionMenuDropdown.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useNavigationSection.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/states/isNavigationSectionOpenComponentState.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/states/isNavigationSectionOpenFamilyState.ts
  packages/twenty-front/src/modules/ui/utilities/state/utils/createFamilyState.ts
Labels: -PR: awaiting review

#13447 add command to destroy workspaces
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/destroy-workspace.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/workspace-cleaner.module.ts
Labels: -PR: awaiting review

#13474 Improve core view migration
  packages/twenty-server/src/database/commands/views-migration/migrate-views-to-core.command.ts
  packages/twenty-server/src/modules/view/services/view-filter-sync.service.ts
  packages/twenty-server/src/modules/view/services/view-sync.service.ts
Labels: -PR: awaiting review

#13402 feat(ai): add markdown in ai chat
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/ai/components/AIChatMessage.tsx
  packages/twenty-front/src/modules/ai/components/LazyMarkdownRenderer.tsx
  packages/twenty-server/src/engine/metadata-modules/agent/agent-execution.service.ts
  packages/twenty-server/src/engine/metadata-modules/agent/agent.module.ts
  packages/twenty-server/src/engine/metadata-modules/agent/constants/agent-system-prompts.const.ts
  yarn.lock
Labels: -PR: awaiting author

#13493 `CreateFieldInput` transpilation to `FlatFieldMetadata`, `FlatFieldMetadata` validation
  packages/twenty-server/src/engine/core-modules/error/aggregate-error.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/field-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/validate-relation-creation-payload.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/__mocks__/get-flat-field-metadata.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/failed-flat-field-metadata-validation.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-create-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-field-metadata-entity-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/from-relation-create-field-input-to-flat-field-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/get-default-flat-field-metadata-from-create-field-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-flat-field-metadata-name-availability.validator.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/__mocks__/get-flat-object-metadata.mock.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/types/flat-object-metadata.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/compare-two-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/from-create-object-input-to-flat-object-metadata.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-object-metadata/utils/merge-two-flat-object-metadatas.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/create-object.input.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata-v2.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/build-default-fields-for-custom-object.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-field-name-availability.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-field-name-availability.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-name-and-label-are-sync-or-throw.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/__tests__/__snapshots__/workspace-migration-builder.spec.ts.snap
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-builder-v2.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-field-actions-builder.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-builder-v2/workspace-migration-v2-index-actions-builder.ts
  packages/twenty-shared/src/utils/__tests__/sanitizeObjectStringFields.test.ts
  packages/twenty-shared/src/utils/__tests__/trim-and-remove-duplicated-whitespaces-from-object-string-properties.test.ts
  packages/twenty-shared/src/utils/assertUnreachable.ts
  packages/twenty-shared/src/utils/from-array-to-unique-key-record.util.ts
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/utils/sanitizeObjectStringFields.ts
  packages/twenty-shared/src/utils/trim-and-remove-duplicated-whitespaces-from-object-string-properties.ts
Labels: -PR: awaiting review

#13502 `FlatFieldMetadataType` hashmap arch and enum validation
  packages/twenty-server/src/engine/core-modules/error/multiple-metadata-validation-errors.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-enum-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service-v2.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/flat-field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-type-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/services/flat-field-metadata-validator.service.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/failed-flat-field-metadata-validation.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata-type-validator.type.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/get-default-flat-field-metadata-from-create-field-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/utils/is-enum-validate-one-field-metadata-args.util.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-enum-flat-field-metadata.validator.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-flat-field-metadata-name-availability.validator.ts
  packages/twenty-server/src/engine/metadata-modules/flat-field-metadata/validators/validate-relation-flat-field-metadata.validator.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/enum-column-action.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-v2/workspace-migration-runner-v2/workspace-metadata-migration-runner/workspace-metadata-object-action-runner.service.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts
  packages/twenty-shared/src/constants/QuotedStringRegex.ts
  packages/twenty-shared/src/constants/index.ts
  packages/twenty-shared/src/types/EnumFieldMetadataType.ts
  packages/twenty-shared/src/types/NonNullableRequired.ts
  packages/twenty-shared/src/types/NullablePartial.ts
  packages/twenty-shared/src/types/index.ts
  packages/twenty-shared/src/utils/__tests__/deepMerge.test.ts
  packages/twenty-shared/src/utils/__tests__/sanitizeObjectStringFields.test.ts
  packages/twenty-shared/src/utils/deepMerge.ts
  packages/twenty-shared/src/utils/extractAndSanitizeObjectStringFields.ts
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/utils/validation/isDefined.ts
Labels: -PR: awaiting review
