Repository twentyhq/twenty, pull requests merged in 2025-03, with the labels that each got.

#10238 [TEST] Covering `useDeleteOne` relations optimistic cache behavior
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDeleteMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDestroyMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useExportMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useAddToFavoritesSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useDeleteSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/__tests__/useRemoveFromFavoritesSingleRecordAction.test.tsx
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useDefaultHomePagePath.test.ts
  packages/twenty-front/src/modules/object-record/cache/utils/__tests__/getRecordNodeFromRecord.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/computeDepthOneRecordGqlFieldsFromRecord.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/generateDepthOneRecordGqlFields.test.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/__mocks__/useFindDuplicateRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/__snapshots__/useDeleteOneRecord.test.tsx.snap
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteOneRecord.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/record-picker/components/__stories__/SingleRecordPicker.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/__stories__/RecordDetailRelationSection.stories.tsx
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFormDeleteRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFormUpdateRecord.stories.tsx
  packages/twenty-front/src/pages/object-record/__stories__/RecordShowPage.stories.tsx
  packages/twenty-front/src/testing/cache/inMemoryTestingCacheInstance.ts
  packages/twenty-front/src/testing/decorators/ContextStoreDecorator.tsx
  packages/twenty-front/src/testing/decorators/getFieldDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/companies.ts
  packages/twenty-front/src/testing/mock-data/companiesWithRelations.ts
  packages/twenty-front/src/testing/mock-data/people.ts
Labels: -PR: wip, -PR: awaiting author

#10424 Fix: Prevent Multiple Search Icons in Command Menu
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
Labels: -PR: awaiting author

#10624 Create import csv action
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultActionsConfigV1.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultActionsConfigV2.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowRunsActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowVersionsActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useImportRecordsNoSelectionRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/types/NoSelectionRecordActionsKey.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/types/SingleRecordActionsKey.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/__tests__/useOpenObjectRecordsSpreadsheetImportDialog.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
Labels: -PR: awaiting review

#10442 Health status worker metrics improvements
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTabSkeletonLoader.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/DatabaseAndRedisHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminQueueExpandableContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminQueueHealthButtons.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerMetricsGraph.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerQueueMetricsSection.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/contexts/SettingsAdminIndicatorHealthContext.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/graphql/queries/getIndicatorHealthStatus.ts
  packages/twenty-front/src/modules/settings/admin-panel/health-status/graphql/queries/getQueueMetrics.ts
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminIndicatorHealthStatus.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel-health.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel-health.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-worker-queue-health.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/queue-metrics-data-point.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/queue-metrics-data.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/queue-metrics-series.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/enums/queue-metrics-time-range.enum.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/worker.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/worker.health.ts
  packages/twenty-server/src/engine/core-modules/health/types/worker-queue-health.type.ts
  packages/twenty-server/src/engine/core-modules/health/types/worker-queue-metrics.type.ts
  packages/twenty-server/src/engine/core-modules/message-queue/drivers/bullmq.driver.ts
Labels: -PR: awaiting review

#10634 [ENH] Do not fail on missed cache within server commands
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-migrate-rich-text-content-patch.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-update-default-view-record-opening-on-workflow-objects.command.ts
Labels: -PR: awaiting review

#10628 Fix: security and developers path should not be accessible to non-admin users
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
Labels: -PR: awaiting review

#10626 [BUGFIX] Dynamic default body background depending on device preferences
  packages/twenty-front/index.html
  packages/twenty-front/src/renderBodyOptimisticBackgroundBeforeAppBootstrap.ts
Labels: -PR: awaiting review

#10646 [BUG] Object Settings Model tabs list heigh value `0`
  packages/twenty-front/src/modules/settings/components/SettingsPageContainer.tsx
Labels: -PR: awaiting review

#10654 Various frontend fixes for roles pages
  packages/twenty-front/src/modules/settings/hooks/useSettingsNavigationItems.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentConfirmationModal.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentConfirmationModalSubtitle.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/types/RoleAssignmentConfirmationModalSelectedWorkspaceMember.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissions.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-settings/components/RoleSettings.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-ui/src/input/components/Checkbox.tsx
Labels: -PR: awaiting review

#10659 496 add open in full page button on command menu record page
  .nvmrc
  package.json
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/action-menu/components/__stories__/RightDrawerActionMenuDropdown.stories.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerRecord.tsx
  packages/twenty-front/src/modules/object-record/record-right-drawer/constants/RightDrawerRecordInstanceId.ts
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-ui/src/display/icon/components/IconMicrosoft.tsx
  packages/twenty-ui/src/display/icon/components/IconMicrosoftCalendar.tsx
  packages/twenty-ui/src/display/icon/components/IconMicrosoftOutlook.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/icon/providers/internal/AllIcons.ts
  packages/twenty-ui/src/display/icon/types/IconComponent.ts
  packages/twenty-ui/src/feedback/progress-bar/components/CircularProgressBar.tsx
  packages/twenty-ui/src/input/button/components/MainButton.tsx
  packages/twenty-website/src/app/_components/ui/icons/index.ts
  yarn.lock
Labels: -PR: awaiting review

#10666 [Fix] Read only users should not be able to open a Relation picker
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx
  packages/twenty-front/src/modules/activities/notes/components/NoteCard.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/__tests__/useIsFieldValueReadOnly.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldValueReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/__tests__/isFieldValueReadOnly.test.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
  packages/twenty-front/src/modules/object-record/record-show/components/SummaryCard.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/__stories__/RecordDetailRelationSection.stories.tsx
Labels: -PR: awaiting review

#10397 deprocate getProductPrices query in front end
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/billing/graphql/billingBaseProductPrices.ts
  packages/twenty-front/src/modules/billing/graphql/getProductPrices.ts
  packages/twenty-front/src/modules/billing/utils/isBillingPriceLicensed.ts
  packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx
  packages/twenty-front/src/pages/onboarding/__stories__/ChooseYourPlan.stories.tsx
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-price-licensed.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-price-metered.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-price-union.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-product.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/outputs/billing-product-prices.output.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/format-database-product-to-graphql-dto.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/format-database-product-to-graphql-dto.util.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/get-plan-key-from-subscription.util.ts
Labels: -PR: ready to merge

#10381 microsoft sync failed
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-access-token-manager/refresh-access-token-manager.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-access-token-manager/services/refresh-access-token.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/connected-account-refresh-tokens-manager.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/google/google-api-refresh-access-token.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/google/services/google-api-refresh-access-token.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/microsoft/microsoft-api-refresh-access-token.module.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/drivers/microsoft/services/microsoft-api-refresh-tokens.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/exceptions/connected-account-refresh-tokens.exception.ts
  packages/twenty-server/src/modules/connected-account/refresh-tokens-manager/services/connected-account-refresh-tokens.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-import-exception-handler.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
  packages/twenty-shared/src/utils/assertUnreachable.ts
  packages/twenty-shared/src/utils/index.ts
Labels: -PR: wip

#10657 Save the trigger's default name
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getTriggerDefaultDefinition.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerDefaultDefinition.ts
Labels: -PR: awaiting review

#10680 update globalSearch resolver
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/src/engine/core-modules/global-search/__tests__/global-search.service.spec.ts
  packages/twenty-server/src/engine/core-modules/global-search/dtos/global-search-args.ts
  packages/twenty-server/src/engine/core-modules/global-search/dtos/object-record-filter-input.ts
  packages/twenty-server/src/engine/core-modules/global-search/global-search.module.ts
  packages/twenty-server/src/engine/core-modules/global-search/global-search.resolver.ts
  packages/twenty-server/src/engine/core-modules/global-search/services/global-search.service.ts
Labels: -PR: awaiting author

#10691 send email refacto
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-send-message.service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/mail-sender/send-email-action.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/mail-sender/send-email.workflow-action.ts
Labels: -PR: awaiting review

#10700 491 save the page component instance id for side panel navigation
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerActionMenu.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/calendar/components/EventCardCalendarEvent.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/EventCardMessage.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipGroups.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordsChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuRouter.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/components/ResetContextToSelectionCommandButton.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenuContextRecordChip.stories.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuPagesConfig.tsx
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.tsx
  packages/twenty-front/src/modules/command-menu/pages/calendar-event/components/CommandMenuCalendarEventPage.tsx
  packages/twenty-front/src/modules/command-menu/pages/message-thread/components/CommandMenuMessageThreadIntermediaryMessages.tsx
  packages/twenty-front/src/modules/command-menu/pages/message-thread/components/CommandMenuMessageThreadPage.tsx
  packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/useEmailThreadInCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/pages/message-thread/states/messageThreadComponentState.ts
  packages/twenty-front/src/modules/command-menu/pages/record-page/components/CommandMenuRecordPage.tsx
  packages/twenty-front/src/modules/command-menu/pages/record-page/states/isNewViewableRecordLoadingComponentState.ts
  packages/twenty-front/src/modules/command-menu/pages/record-page/states/viewableRecordIdComponentState.ts
  packages/twenty-front/src/modules/command-menu/pages/record-page/states/viewableRecordNameSingularComponentState.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuNavigationStackState.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuPageInfoState.ts
  packages/twenty-front/src/modules/command-menu/states/contexts/CommandMenuPageComponentInstanceContext.tsx
  packages/twenty-front/src/modules/object-record/record-right-drawer/states/viewableRecordNameSingularState.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
Labels: -PR: awaiting review

#10677 Visualize workflow run step input
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizerContent.tsx
  packages/twenty-front/src/modules/workflow/components/json-visualizer/components/JsonArrayNode.tsx
  packages/twenty-front/src/modules/workflow/components/json-visualizer/components/JsonNestedNode.tsx
  packages/twenty-front/src/modules/workflow/components/json-visualizer/components/JsonObjectNode.tsx
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowRunIdOrThrow.ts
  packages/twenty-front/src/modules/workflow/states/workflowRunIdState.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/__stories__/RightDrawerWorkflowRunViewStep.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/types/WorkflowRunTabId.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepContext.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepExecutionStatus.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepContext.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepExecutionStatus.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/RightDrawerWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/workflow-run.ts
Labels: -PR: awaiting review

#10546 Admin panel: App health check
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesRow.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/ConnectedAccountHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/DatabaseAndRedisHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/JsonDataIndicatorHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminIndicatorHealthStatusContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsHealthStatusListCard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/contexts/SettingsAdminIndicatorHealthContext.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/graphql/queries/getIndicatorHealthStatus.ts
  packages/twenty-front/src/modules/settings/hooks/useSettingsNavigationItems.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdmin.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminIndicatorHealthStatus.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel-health.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel-health.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/constants/health-indicators.constants.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/admin-panel-health-service-data.dto.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/enums/admin-panel-health-service-status.enum.ts
  packages/twenty-server/src/engine/core-modules/health/constants/health-error-messages.constants.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/health.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/health.controller.ts
  packages/twenty-server/src/engine/core-modules/health/enums/health-indicator-id.enum.ts
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/app.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/database.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/redis.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/app.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/database.health.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/redis.health.ts
  packages/twenty-server/src/engine/core-modules/health/utils/health-state-manager.util.ts
Labels: -PR: awaiting review

#10703 send email for outlook
  packages/twenty-server/src/engine/core-modules/auth/utils/get-microsoft-apis-oauth-scopes.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-send-message.service.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#10678 eliminate IS_BILLING_PLANS_ENABLED feature flag
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-product-price.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-usage.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-checkout.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-price.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
  packages/twenty-server/src/engine/core-modules/billing/types/billing-portal-checkout-session-parameters.type.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting review

#10725 Bettertyping
  packages/twenty-front/src/modules/accounts/constants/MicrosoftSendScope.ts
  packages/twenty-front/src/modules/accounts/types/ConnectedAccount.ts
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
  packages/twenty-front/src/modules/settings/accounts/hooks/useTriggerApiOAuth.ts
  packages/twenty-front/src/modules/settings/security/components/SettingsSecurityAuthProvidersOptionsList.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-get-events.service.ts
  packages/twenty-server/src/modules/connected-account/email-alias-manager/services/email-alias-manager.service.ts
  packages/twenty-server/src/modules/connected-account/oauth2-client-manager/services/oauth2-client-manager.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-cursor.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-messages.service.ts
Labels: scope: back+front, prio: med

#10717 fix redis concurrency issue in health metrics + remove ongoing status count
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthAccountSyncCountersTable.tsx
  packages/twenty-server/src/engine/core-modules/cache-storage/services/cache-storage.service.ts
  packages/twenty-server/src/engine/core-modules/captcha/captcha.guard.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/metrics.controller.ts
  packages/twenty-server/src/engine/core-modules/health/health-cache.service.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/connected-account.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/connected-account.health.ts
  packages/twenty-server/src/engine/core-modules/health/types/account-sync-metrics.types.ts
  packages/twenty-server/src/modules/calendar/common/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
Labels: -PR: awaiting review

#10730 Visualize workflow run step output
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizer.tsx
  packages/twenty-front/src/modules/workflow/components/WorkflowRunVisualizerContent.tsx
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionStatusTag.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramCustomMarkers.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowVersionStatusTag.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowRunStatusTagProps.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowVersionStatusTagProps.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepHeader.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/__stories__/RightDrawerWorkflowRunViewStep.stories.tsx
Labels: -PR: awaiting review

#10729 send email
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
Labels: -PR: awaiting review

#10758 Fix permissions front followup
  packages/twenty-front/src/modules/settings/roles/components/Roles.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-front/vite.config.ts
Labels: -PR: awaiting review

#10699 [BUGFIX] ObjectMetadata item server validation
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts
  packages/twenty-front/src/modules/settings/data-model/validation-schemas/__tests__/settingsDataModelObjectAboutFormSchema.test.ts
  packages/twenty-front/src/utils/array/__tests__/buildRecordFromKeysWithSameValue.test.ts
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/jest.config.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/__snapshots__/validate-object-metadata-input.util.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/__tests__/validate-object-metadata-input.util.spec.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/__snapshots__/validate-field-name-availability.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/__snapshots__/validate-metadata-name.spec.ts.snap
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-field-name-availability.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name-validity.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/__tests__/validate-metadata-name.spec.ts
  packages/twenty-server/src/engine/metadata-modules/utils/constants/identifier-min-char-length.constants.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/invalid-metadata-name.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/invalid-string.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/name-not-available.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/name-too-long.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-database-identifier-length.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-field-name-availability.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-is-camel-case.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-is-not-reserved-keyword.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-is-not-too-long.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-is-not-too-short.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-start-with-lowercase-letter-and-contain-digits-nor-letters.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-validity.utils.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name.utils.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/__snapshots__/failing-create-one-object-metadata.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/object-metadata/failing-create-one-object-metadata.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/successful-create-one-object-metadata.integration-spec.ts
  packages/twenty-server/test/integration/utils/object-metadata/generate-mock-create-object-metadata-input.ts
  packages/twenty-server/test/integration/utils/object-metadata/perform-failing-object-metadata-creation.ts
  packages/twenty-server/test/integration/utils/object-metadata/perform-object-metadata-creation.ts
  packages/twenty-shared/src/index.ts
  packages/twenty-shared/src/testing/index.ts
  packages/twenty-shared/src/testing/types/EachTestingContext.type.ts
  packages/twenty-shared/src/types/index.ts
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/utils/validation/__tests__/isValideLocale.test.ts
Labels: -PR: awaiting author

#10760 Delete view & copy link
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-server/src/modules/view/pre-hooks.ts/view-delete-many.pre-query.hook.ts
  packages/twenty-server/src/modules/view/pre-hooks.ts/view-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/view/view.module.ts
  packages/twenty-server/src/modules/view/views.exception.ts
Labels: -PR: awaiting author

#10783 Fix Keystatic configuration
  packages/twenty-website/.env.example
  packages/twenty-website/keystatic.config.ts
Labels: -PR: awaiting review

#10789 Fix fieldMetadata sync validation exceptions caught in exception handler
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/field-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/object-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/utils/relation-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/compute-metadata-name-from-label.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/exceptions/invalid-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/utils/validate-name-and-label-are-sync-or-throw.util.ts
Labels: -PR: awaiting review

#10802 Settings counter alignment fix
  packages/twenty-front/src/modules/settings/components/SettingsCounter.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentSelect.tsx
Labels: -PR: awaiting review

#10787 545 replace objects icons and names with records avatars and labelidentifiers in command menu context chips
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipGroupsWithRecordSelection.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipRecordSetterEffect.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChipAvatars.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuRouter.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuContextChips.tsx
  packages/twenty-front/src/modules/command-menu/states/commandMenuNavigationMorphItemsState.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuNavigationRecordsState.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuNavigationStackState.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useLimitPerMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useGetStandardObjectIcon.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useLimitPerMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/getIconColorForObjectType.ts
  packages/twenty-front/src/modules/object-metadata/utils/getIconForObjectType.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useCombinedFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/usePerformCombinedFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/types/MorphItem.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/__tests__/generateCombinedFindManyRecordsQueryVariables.test.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/generateCombinedFindManyRecordsQueryVariables.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/getLimitPerMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/hooks/useMultipleRecordPickerPerformSearch.ts
Labels: -PR: awaiting review

#10781 renaming layout and changing icons
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutOpenInContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/__stories__/ObjectOptionsDropdownContent.stories.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/types/ObjectOptionsContentId.ts
Labels: -PR: awaiting review

#10792 Admin panel fixes
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvCopyableText.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariables.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesRow.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminEnvVariablesTable.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTableCard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminVersionContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminWorkspaceContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/ConnectedAccountHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/JsonDataIndicatorHealthStatus.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerMetricsGraph.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerMetricsTooltip.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerQueueMetricsSection.tsx
  packages/twenty-front/src/modules/settings/components/SettingsListItemCardContent.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminIndicatorHealthStatus.tsx
  packages/twenty-front/src/pages/settings/admin-panel/SettingsAdminSecondaryEnvVariables.tsx
  packages/twenty-server/src/engine/core-modules/admin-panel/constants/health-indicators.constants.ts
  packages/twenty-server/src/engine/guards/impersonate-guard.spec.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/typography/components/H2Title.tsx
Labels: -PR: awaiting review

#10832 Tablist regression fix
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
Labels: -PR: wip, -PR: awaiting author

#10842 Add Icon to roles
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/roles/components/RolesTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/graphql/fragments/roleFragment.ts
  packages/twenty-front/src/modules/settings/roles/role-settings/components/RoleSettings.tsx
  packages/twenty-server/src/database/typeorm/metadata/migrations/1741859116265-addIconToRole.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/role/dtos/role.dto.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.entity.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.service.ts
Labels: -PR: awaiting review

#10845 Add permissions v1 to lab
  packages/twenty-server/src/engine/core-modules/feature-flag/constants/public-feature-flag.const.ts
  packages/twenty-website/public/images/lab/is-permissions-enabled.png
Labels: -PR: awaiting review

#10825 Fix wrong font in chips and tabs
  packages/twenty-chrome-extension/src/options/modules/ui/input/components/TextInput.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChip.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/Tab.tsx
Labels: -PR: awaiting review

#10751 [FEAT] New `APP_VERSION` env var inferred from tag & refactor upgrade-command to integrate versioning
  packages/twenty-docker/twenty/Dockerfile
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-server/src/database/commands/command-runners/__tests__/__snapshots__/upgrade.command-runner.spec.ts.snap
  packages/twenty-server/src/database/commands/command-runners/__tests__/upgrade.command-runner.spec.ts
  packages/twenty-server/src/database/commands/command-runners/active-or-suspended-workspaces-migration.command-runner.ts
  packages/twenty-server/src/database/commands/command-runners/upgrade.command-runner.ts
  packages/twenty-server/src/database/commands/data-seed-demo-workspace/services/data-seed-demo-workspace.service.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-add-tasks-assigned-to-me-view.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/utils/version/__tests__/__snapshots__/compare-version-minor-and-major.spec.ts.snap
  packages/twenty-server/src/utils/version/__tests__/compare-version-minor-and-major.spec.ts
  packages/twenty-server/src/utils/version/compare-version-minor-and-major.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#10857 Create a running variant for workflow diagram nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagramNodeVariant.ts
  packages/twenty-ui/src/feedback/loader/components/Loader.tsx
  packages/twenty-ui/src/theme/constants/AdaptiveColorsDark.ts
  packages/twenty-ui/src/theme/constants/AdaptiveColorsLight.ts
Labels: -PR: awaiting review

#10862 Fix keystatic github redirect_uri by relying on x-forwarded-* headers
  packages/twenty-website/src/app/api/keystatic/[...params]/route.ts
Labels: -PR: awaiting author

#10864 [FIX] Omition on previous integ of upgrade command compare version based on integer result
  packages/twenty-server/src/database/commands/command-runners/upgrade.command-runner.ts
  packages/twenty-server/src/utils/version/__tests__/compare-version-minor-and-major.spec.ts
  packages/twenty-server/src/utils/version/compare-version-minor-and-major.ts
Labels: -PR: awaiting review

#10880 [ENH] `APP_VERSION`documentation
  packages/twenty-server/src/database/commands/command-runners/__tests__/__snapshots__/upgrade.command-runner.spec.ts.snap
  packages/twenty-server/src/database/commands/command-runners/upgrade.command-runner.ts
Labels: -PR: awaiting review

#10879 Fix update of aggregate operation not reflected in kanban header without refresh
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/states/aggregateDropdownState.ts
  packages/twenty-front/src/modules/views/hooks/useUpdateViewAggregate.ts
Labels: -PR: awaiting review

#10885 Fix activity target creation
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useUpdateActivityTargetFromInlineCell.ts
Labels: -PR: awaiting review

#10887 fix public feature flag update
  packages/twenty-server/src/engine/core-modules/feature-flag/services/__tests__/feature-flag.service.spec.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/services/feature-flag.service.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/workspace.integration-spec.ts
Labels: -PR: awaiting review

#10898 Fix kanban view picker total count
  packages/twenty-front/src/modules/object-record/hooks/useAggregateRecords.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useSetRecordIndexEntityCount.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexEntityCountNoGroupComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-index/states/selectors/recordIndexEntityCountComponentSelector.ts
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainerEffect.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useGetRecordIndexTotalCount.ts
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx
Labels: -PR: awaiting review

#10844 Advanced toggle alignment
  packages/twenty-front/src/modules/settings/components/AdvancedSettingsWrapper.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItem.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-ui/src/navigation/link/components/AdvancedSettingsToggle.tsx
Labels: -PR: awaiting review

#10901 Remove dead code about workflow leaf nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditableContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramCustomMarkers.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramEmptyTrigger.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowDiagramEmptyTriggerNodeDefinition.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/markLeafNodes.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/mergeWorkflowDiagrams.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowDiagramTriggerNode.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/markLeafNodes.ts
Labels: -PR: awaiting review

#10918 fix workflow view not visible
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
Labels: -PR: awaiting review

#10642 feat(twenty-front/workspace-menu): improve workspace menu
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/signUpInNewWorkspace.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirect.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts
  packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInAppNavigationDrawerMock.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuHeader/DropdownMenuHeader.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useDropdown.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownClickableComponent.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownDefaultComponents.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownThemesComponents.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownWorkspacesListComponents.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspacesDropdownStyles.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdownButton.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/constants/MultiWorkspaceDropdownId.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/states/multiWorkspaceDropdownState.ts
  packages/twenty-front/src/modules/ui/theme/hooks/useColorScheme.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
Labels: -PR: awaiting review

#10959 [fix] Users with readOnly permissions should not be able to edit richtext fields
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageActivityContainer.tsx
Labels: -PR: awaiting review

#10889 Configure Keystatic for release images
  packages/twenty-website/keystatic.config.ts
  packages/twenty-website/public/images/releases/0.43.0/email-privacy.png
  packages/twenty-website/public/images/releases/0.43.0/search-upgrade.png
  packages/twenty-website/src/content/releases/0.43.0.mdx
Labels: -PR: awaiting review

#10987 Fix permissionAssignment dropdownMenu max height
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdown.tsx
Labels: -PR: awaiting review

#10989 Fix workflow id not being set
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizerEffect.tsx
Labels: -PR: awaiting review

#10997 Update 'Settings Permissions' Layout
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissions.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsObjectsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/RolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/types/RolePermissionsSettingPermission.ts
  packages/twenty-ui/src/input/components/Checkbox.tsx
Labels: -PR: awaiting review

#10999 Creating records in side panel not working
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/hooks/useRegisterInputEvents.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCell.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldInput.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
Labels: -PR: awaiting review

#11002 Limit nodes opened by default in the JSON Tree component
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/JsonDataIndicatorHealthStatus.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowPreviousStep.ts
  packages/twenty-ui/src/json-visualizer/__stories__/JsonTree.stories.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonNestedNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonTree.tsx
  packages/twenty-ui/src/json-visualizer/contexts/JsonTreeContext.tsx
  packages/twenty-ui/src/json-visualizer/index.ts
  packages/twenty-ui/src/json-visualizer/utils/isTwoFirstDepths.ts
Labels: -PR: ready to merge

#11022 [CHORE] Prepare `twenty-server`for `twenty-shared` multi barrel refactor
  packages/twenty-server/src/modules/view/pre-hooks/view-delete-many.pre-query.hook.ts
  packages/twenty-server/src/modules/view/pre-hooks/view-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/view/view.module.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/__tests__/generate-fake-field.spec.ts
Labels: -PR: awaiting review

#11008 584 Refactor Tabs
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx
  packages/twenty-front/src/modules/activities/tasks/components/TaskGroups.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuCloseAnimationCompleteCleanup.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHistory.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsCalendarChannelsContainer.tsx
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsMessageChannelsContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminTabContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminGeneralTabsId.ts
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionCodeEditorTab.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageSubContainer.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/constants/ShowPageTabListComponentId.ts
  packages/twenty-front/src/modules/ui/layout/show-page/utils/getShowPageTabListComponentId.ts
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/TabListFromUrlOptionalEffect.tsx
  packages/twenty-front/src/modules/ui/layout/tab/components/__stories__/Tablist.stories.tsx
  packages/twenty-front/src/modules/ui/layout/tab/hooks/__tests__/useTabList.test.tsx
  packages/twenty-front/src/modules/ui/layout/tab/hooks/internal/useTabListStates.ts
  packages/twenty-front/src/modules/ui/layout/tab/hooks/useTabList.ts
  packages/twenty-front/src/modules/ui/layout/tab/states/activeTabIdComponentState.ts
  packages/twenty-front/src/modules/ui/layout/tab/states/contexts/TabListComponentInstanceContext.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowEditStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowEditStepContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/RightDrawerWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/__stories__/RightDrawerWorkflowRunViewStep.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/types/WorkflowRunTabId.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/RightDrawerWorkflowSelectAction.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/RightDrawerWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/types/WorkflowServerlessFunctionTabId.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/components/WorkflowVariablesDropdownFieldItems.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPage.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
Labels: -PR: awaiting review

#11043 Update CommandMenuContextChipRecordSetterEffect to use the cache
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChipRecordSetterEffect.tsx
Labels: -PR: awaiting review

#11042 contact creation was recreating a primaryemail du to casing
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-contact.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.ts
Labels: -PR: awaiting review, size: long, prio: high

#11035 Form action field base settings
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/TextVariableEditor.tsx
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowEditActionForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowEditActionFormFieldSettings.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowFormFieldSettingsByType.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowFormFieldSettingsNumber.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowFormFieldSettingsText.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/__stories__/WorkflowEditActionForm.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/__stories__/WorkflowEditActionFormFieldSettings.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/utils/getDefaultFormFieldSettings.ts
Labels: -PR: awaiting author

#11044 Fix minor bugs on advanced filters
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRootLevelViewFilterGroup.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useChildRecordFiltersAndRecordFilterGroups.ts
  packages/twenty-front/src/modules/object-record/advanced-filter/states/rootLevelRecordFilterGroupComponentSelector.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOperandDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-filter-group/hooks/useRemoveRootRecordFilterGroupIfEmpty.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuHeader/DropdownMenuHeader.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/__stories__/DropdownMenuHeader.stories.tsx
  packages/twenty-front/src/modules/views/components/AdvancedFilterChip.tsx
  packages/twenty-front/src/modules/views/components/AdvancedFilterDropdownButton.tsx
Labels: -PR: awaiting review

#11074 Fix role edit page tab instance id
  packages/twenty-front/src/modules/workflow/workflow-variables/components/WorkflowVariablesDropdownFieldItems.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
Labels: -PR: awaiting review

#11071 [BUGFIX] `GenerateDefaultRecordChipData` returns `RecordChipData`
  packages/twenty-front/src/modules/object-metadata/contexts/PreComputedChipGeneratorsContext.ts
  packages/twenty-front/src/modules/object-metadata/utils/generateDefaultRecordChipData.ts
  packages/twenty-front/src/modules/object-record/hooks/useRecordChipData.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationFromManyFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationToOneFieldDisplay.ts
Labels: -PR: awaiting review

#11081 Fix option text deletion in select fields by removing error for empty values
  packages/twenty-front/src/modules/settings/components/AdvancedSettingsWrapper.tsx
  packages/twenty-front/src/pages/settings/data-model/utils/compute-option-value-from-label.utils.ts
Labels: -PR: awaiting review

#11080 Fix overscroll behavior on dev environment
  packages/twenty-front/src/index.css
Labels: -PR: awaiting review

#10288 Error invalid link
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventDetails.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardBody.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemBaseInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/states/recordFieldInputIsFieldInErrorComponentState.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContextWrapper.tsx
  packages/twenty-front/src/modules/ui/layout/overlay/components/OverlayContainer.tsx
Labels: -PR: awaiting review

#11084 Reorder commands
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
Labels: -PR: awaiting review

#11087 Fixes on rich text editor
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditor.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageActivityContainer.tsx
Labels: -PR: awaiting review

#11088 Fix currency update
  packages/twenty-front/src/modules/ui/input/components/internal/currency/components/CurrencyPickerDropdownButton.tsx
Labels: -PR: awaiting review

#11093 Update timeline empty state in the side panel
  packages/twenty-front/src/modules/activities/timeline-activities/components/TimelineActivities.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
Labels: -PR: awaiting review

#11089 Reorganized components in advanced filter dropdown
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterDropdownRow.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterFieldSelectDrodownButton.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterFieldSelectDrodownContent.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterFieldSelectSearchInput.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupChildOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupChildren.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupRow.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterOperandSelect.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterRow.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRootLevelViewFilterGroup.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRootRecordFilterGroup.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterValueInputDropdownButton.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterViewFilter.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelectCompositeFieldSubMenu.tsx
  packages/twenty-front/src/modules/views/components/AdvancedFilterDropdownButton.tsx
Labels: -PR: awaiting author

#11049 App health check: Optimize pending migration query
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/app.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/app.health.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.service.ts
Labels: -PR: awaiting review

#11086 replace search resolvers by global search in front
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useUpdateActivityTargetFromInlineCell.ts
  packages/twenty-front/src/modules/command-menu/constants/MaxSearchResults.ts
  packages/twenty-front/src/modules/command-menu/graphql/queries/globalSearch.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuSearchRecords.tsx
  packages/twenty-front/src/modules/command-menu/pages/search/components/CommandMenuSearchRecordsPage.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatGlobalSearchRecordAsSingleRecordPickerRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordSearchRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useSearchRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/multiple-objects/utils/generateCombinedSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RelationToOneFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-picker/hooks/useRecordPickerGetRecordAndObjectMetadataItemFromRecordId.ts
  packages/twenty-front/src/modules/object-record/record-picker/hooks/useRecordPickerGetSearchRecordAndObjectMetadataItemFromRecordId.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItemContent.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/hooks/useMultipleRecordPickerPerformSearch.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/states/searchRecordStoreComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx
  packages/twenty-front/src/modules/object-record/utils/generateSearchRecordsQuery.ts
  packages/twenty-front/src/modules/object-record/utils/getSearchRecordsQueryResponseField.ts
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchRecordQuery.ts
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
Labels: -PR: awaiting review

#11100 Add enterprise plan in cloud onboarding
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/billing/graphql/billingBaseProductPrices.ts
  packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
Labels: -PR: awaiting review

#11115 logging ids to import
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
Labels: -PR: ready to merge

#11114 clean searchResolvers in server
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/graphql/queries/search.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuSearchRecords.tsx
  packages/twenty-front/src/modules/object-metadata/utils/formatSearchRecordAsSingleRecordPickerRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordSearchRecords.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItemContent.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/hooks/useMultipleRecordPickerPerformSearch.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/states/searchRecordStoreComponentFamilyState.ts
  packages/twenty-front/src/modules/search/hooks/useFilteredSearchRecordQuery.ts
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/RoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-migrate-search-vector-on-note-and-task-entities.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-upgrade-version-command.module.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.module.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-search-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/types/workspace-query-hook.type.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/constants/resolver-method-names.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/factories.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/search-resolver-factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/interfaces/workspace-resolvers-builder.interface.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver-builder.service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/factories/root-type.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-resolver-args.util.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/search/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts
  packages/twenty-server/src/engine/core-modules/search/__tests__/search.service.spec.ts
  packages/twenty-server/src/engine/core-modules/search/constants/results-limit-by-object-without-search-terms.ts
  packages/twenty-server/src/engine/core-modules/search/constants/standard-objects-by-priority-rank.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/object-record-filter-input.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-args.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-record-dto.ts
  packages/twenty-server/src/engine/core-modules/search/exceptions/search.exception.ts
  packages/twenty-server/src/engine/core-modules/search/filters/search-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/search/search.module.ts
  packages/twenty-server/src/engine/core-modules/search/search.resolver.ts
  packages/twenty-server/src/engine/core-modules/search/services/search.service.ts
  packages/twenty-server/src/engine/core-modules/search/types/records-with-object-metadata-item.ts
  packages/twenty-server/src/engine/core-modules/search/utils/__tests__/format-search-terms.spec.ts
  packages/twenty-server/src/engine/core-modules/search/utils/format-search-terms.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/search-vector/search-vector.module.ts
  packages/twenty-server/src/engine/metadata-modules/search-vector/search-vector.service.ts
  packages/twenty-server/src/engine/utils/get-resolver-name.util.ts
  packages/twenty-server/test/integration/graphql/suites/search/search-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/search-factory.util.ts
Labels: -PR: awaiting review

#11110 [FEAT] Generate barrel export named modules and types
  packages/twenty-shared/scripts/generateBarrels.ts
  packages/twenty-shared/src/constants/index.ts
  packages/twenty-shared/src/testing/index.ts
  packages/twenty-shared/src/translations/index.ts
  packages/twenty-shared/src/types/index.ts
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/workspace/index.ts
Labels: -PR: awaiting review

#11131 Add see runs and see workflows actions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowRunsActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowVersionsActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useSeeRunsNoSelectionRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useSeeWorkflowsNoSelectionRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/types/NoSelectionRecordActionsKey.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-run-actions/hooks/useSeeVersionWorkflowRunSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-run-actions/hooks/useSeeWorkflowWorkflowRunSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-run-actions/types/WorkflowRunSingleRecordActionsKeys.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useSeeWorkflowWorkflowVersionSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/types/WorkflowVersionSingleRecordActionsKeys.ts
  packages/twenty-front/src/modules/action-menu/types/ActionMenuEntry.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuCommands.tsx
Labels: -PR: awaiting review

#11132 Update delete record message
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDeleteSingleRecordAction.tsx
Labels: -PR: awaiting review

#11130 [FIX] `twenty-shared` build on window even `wsl`
  packages/twenty-shared/package.json
  packages/twenty-shared/scripts/generateBarrels.ts
  yarn.lock
Labels: -PR: wip, -PR: awaiting author

#11145 Fix record page title focus
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCell.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/hooks/useRecordTitleCell.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/utils/getRecordTitleCellId.ts
Labels: -PR: awaiting review

#11116 Option-menu-v2-input
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutOpenInContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuViewName.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useObjectOptions.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useUpdateObjectViewOptions.ts
  packages/twenty-front/src/modules/object-record/record-show/components/ObjectRecordShowPageBreadcrumb.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCell.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleDoubleTextInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldInput.tsx
  packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentEditMode.tsx
Labels: -PR: awaiting author

#11164 fixed workspace tabs not working in admin panel
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminGeneral.tsx
  packages/twenty-front/src/modules/settings/admin-panel/constants/SettingsAdminGeneralTabsId.ts
Labels: -PR: awaiting review

#11171 Allow empty string for primary link
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinksValue.ts
Labels: -PR: awaiting review

#11192 New TitleInput UI component for side panel
  packages/twenty-front/src/modules/command-menu/hooks/__tests__/useUpdateCommandMenuPageInfo.test.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useUpdateCommandMenuPageInfo.ts
  packages/twenty-front/src/modules/ui/input/components/TitleInput.tsx
  packages/twenty-front/src/modules/ui/input/components/__stories__/TitleInput.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepHeader.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/__stories__/WorkflowStepHeader.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionCreateRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionDeleteRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFindRecords.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionUpdateRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/__stories__/WorkflowEditActionFormBuilder.stories.tsx
Labels: -PR: awaiting review

#11210 Feature/add flexibility to docker image makefile
  packages/twenty-docker/Makefile
Labels: -PR: awaiting author

#11167 Option-menu-switch-table-kanban
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuViewName.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupsContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useObjectOptionsForLayout.ts
Labels: -PR: awaiting review

#11221 Design fixes on show page
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx
Labels: -PR: awaiting review

#11153 [CHORE] Remove `preconstruct` local patch
  packages/twenty-docker/twenty/Dockerfile
  packages/twenty-shared/package.json
  packages/twenty-shared/patches/@preconstruct-cli-npm-2.8.11-030abfa6ae.patch
  packages/twenty-shared/scripts/generateBarrels.ts
  yarn.lock
Labels: -PR: awaiting review

#11249 Generate more random subdomains
  packages/twenty-server/src/engine/core-modules/domain-manager/utils/__test__/generate-random-subdomain.spec.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/utils/generate-random-subdomain.ts
Labels: -PR: awaiting review

#11236 set up metrics collecting with open telemetry
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/SettingsAdminHealthAccountSyncCountersTable.tsx
  packages/twenty-server/.env.example
  packages/twenty-server/package.json
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/captcha/captcha.guard.ts
  packages/twenty-server/src/engine/core-modules/environment/constants/environment-variables-group-metadata.ts
  packages/twenty-server/src/engine/core-modules/environment/decorators/cast-to-meter-driver.decorator.ts
  packages/twenty-server/src/engine/core-modules/environment/enums/environment-variables-group.enum.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/__tests__/metrics.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/health/controllers/metrics.controller.ts
  packages/twenty-server/src/engine/core-modules/health/health-cache.service.ts
  packages/twenty-server/src/engine/core-modules/health/health.module.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/__tests__/connected-account.health.spec.ts
  packages/twenty-server/src/engine/core-modules/health/indicators/connected-account.health.ts
  packages/twenty-server/src/engine/core-modules/health/types/health-counter-cache-keys.type.ts
  packages/twenty-server/src/engine/core-modules/metrics/constants/account-sync-metrics-by-status.constant.ts
  packages/twenty-server/src/engine/core-modules/metrics/metrics-cache.service.ts
  packages/twenty-server/src/engine/core-modules/metrics/metrics.module.ts
  packages/twenty-server/src/engine/core-modules/metrics/metrics.service.ts
  packages/twenty-server/src/engine/core-modules/metrics/types/meter-driver.type.ts
  packages/twenty-server/src/engine/core-modules/metrics/types/metrics-keys.type.ts
  packages/twenty-server/src/instrument.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/calendar/common/calendar-common.module.ts
  packages/twenty-server/src/modules/calendar/common/services/calendar-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/common/messaging-common.module.ts
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
  packages/twenty-server/src/queue-worker/queue-worker.ts
  packages/twenty-server/src/utils/parse-array-env-var.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
  yarn.lock
Labels: -PR: awaiting review

#11206 reset main context store viewId and current view type on settings page
  packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx
  packages/twenty-front/src/modules/context-store/components/MainContextStoreProvider.tsx
  packages/twenty-front/src/modules/context-store/components/MainContextStoreProviderEffect.tsx
Labels: -PR: awaiting review

#11243 Display a tooltip for actions without short labels
  packages/twenty-front/src/modules/action-menu/components/PageHeaderActionMenuButtons.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuButtons.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx
  packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenuButtons.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/ui/layout/page-header/components/PageHeaderToggleCommandMenuButton.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageBaseHeader.tsx
  packages/twenty-ui/src/display/tooltip/AppTooltip.tsx
Labels: -PR: awaiting author

#11257 fix no billing subscription error
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
Labels: -PR: awaiting review

#11252 Feature: Update record right click menu
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuDropdown.tsx
Labels: -PR: awaiting CI

#11266 Microsoft Throtling error and wrongly types on our side
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/exceptions/microsoft-import-driver.exception.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-import-exception-handler.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
Labels: -PR: awaiting review, size: long, prio: CRITICAL 🚨

#11256 test(user-workspace): add unit tests for UserWorkspaceService + review #11239
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
Labels: -PR: awaiting review

#11304 [CHORE] Update browserslist
  yarn.lock
Labels: -PR: awaiting review, run-e2e
