Repository twentyhq/twenty, pull requests merged in 2025-05, with the labels that each got.

#11829 Standardize `isDefined` usage for metadata version assertions
  packages/twenty-server/src/engine/metadata-modules/field-metadata/relation/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/relation-metadata/relation-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-cache/services/workspace-metadata-cache.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-metadata-version/services/workspace-metadata-version.service.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
Labels: -PR: awaiting review

#11835 fix: do not report EmailNotVerifiedError to Sentry (#11753)
  packages/twenty-server/src/engine/core-modules/graphql/utils/should-capture-exception.util.ts
Labels: -PR: awaiting review

#11836 Redis max memory limit and eviction policy
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/k8s/manifests/deployment-redis.yaml
  packages/twenty-docker/podman/podman-compose.yml
Labels: -PR: awaiting review

#11840 Fix calendar events & messages fetching + fix timeline design
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventNotSharedContent.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventParticipantsAvatarGroup.tsx
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
  packages/twenty-front/src/modules/activities/calendar/types/guards/IsTimelineCalendarEventParticipant.ts
  packages/twenty-front/src/modules/activities/timeline-activities/rows/calendar/components/EventCardCalendarEvent.tsx
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.resolver.ts
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.spec.ts
  packages/twenty-server/src/engine/core-modules/calendar/timeline-calendar-event.service.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-many.post-query.hook.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-many.pre-query.hook.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-one.post-query.hook.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-one.pre-query-hook.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/apply-calendar-events-visibility-restrictions.service.spec.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/apply-calendar-events-visibility-restrictions.service.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-access-calendar-events.service.ts
  packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-query-hook.module.ts
  packages/twenty-shared/src/constants/FieldRestrictedAdditionalPermissionsRequired.ts
  packages/twenty-shared/src/constants/index.ts
  packages/twenty-ui/src/display/avatar/components/AvatarGroup.tsx
Labels: -PR: awaiting author

#11817 Fix form record picker field
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSingleRecordFieldChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSingleRecordPicker.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormSingleRecordPicker.stories.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-server/src/modules/workflow/common/exceptions/workflow-version-step.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/delete-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/update-record.workflow-action.ts
Labels: -PR: awaiting author

#11871 Modify Decimal Fields to be treated as `number` in OpenAPI schema.
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/__snapshots__/components.utils.spec.ts.snap
  packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/components.utils.spec.ts
  packages/twenty-server/src/engine/core-modules/open-api/utils/components.utils.ts
Labels: preview-app

#11823 Blocknote editor fix
  packages/twenty-front/src/modules/command-menu/pages/rich-text-page/components/CommandMenuEditRichTextPage.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RichTextFieldInput.tsx
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditor.tsx
  packages/twenty-front/src/modules/ui/layout/show-page/components/ShowPageActivityContainer.tsx
Labels: -PR: awaiting review

#11885 Critical email sync bug
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
Labels: -PR: awaiting review

#11827 Allow moving columns left/right in Kanban view
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupReorderConfirmationModal.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useReorderRecordGroups.ts
  packages/twenty-front/src/modules/object-record/record-group/types/RecordGroupActions.ts
Labels: -PR: awaiting review

#11872 Fix: Twenty-website docs same TOC ids #11865
  packages/twenty-website/src/app/(public)/user-guide/hooks/useHeadsObserver.tsx
  packages/twenty-website/src/app/_components/docs/TableContent.tsx
  packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx
Labels: -PR: awaiting review

#11886 chunk csv file before preview
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventNotSharedContent.tsx
  packages/twenty-front/src/modules/activities/files/components/DocumentViewer.tsx
  packages/twenty-front/src/modules/activities/files/utils/fetchCsvPreview.ts
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/EventCardMessage.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/EventCardMessageBodyNotShared.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/EventCardMessageForbidden.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/__stories__/EventCardMessage.stories.tsx
Labels: -PR: awaiting review

#11897 Fix input width
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
Labels: -PR: awaiting review

#11881 Upgrade infer commands from APP_VERSION
  packages/twenty-server/src/database/commands/command-runners/__tests__/__snapshots__/upgrade.command-runner.spec.ts.snap
  packages/twenty-server/src/database/commands/command-runners/__tests__/upgrade.command-runner.spec.ts
  packages/twenty-server/src/database/commands/command-runners/upgrade.command-runner.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/utils/version/__tests__/__snapshots__/compare-version-minor-and-major.spec.ts.snap
  packages/twenty-server/src/utils/version/__tests__/compare-version-minor-and-major.spec.ts
  packages/twenty-server/src/utils/version/__tests__/extract-version-major-minor-patch.spec.ts
  packages/twenty-server/src/utils/version/__tests__/get-previous-version.spec.ts
  packages/twenty-server/src/utils/version/get-previous-version.ts
Labels: -PR: awaiting review

#11903 Fix duplicated workspace id in activeOrSuspendedCommandRunner options
  packages/twenty-server/src/database/commands/command-runners/active-or-suspended-workspaces-migration.command-runner.ts
Labels: -PR: awaiting review

#11926 fix on field relation preview
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationFromManyFieldDisplay.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
Labels: -PR: awaiting review

#11932 Note link's color contrast fixed in dark mode
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditor.tsx
Labels: preview-app

#11349 Revert "Revert "[4/n]: migrate the RESTAPI GET /rest/* to use TwentyORM direc…"
  Makefile
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/engine/api/graphql/__tests__/workspace.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-filter/graphql-query-filter-field.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-order/graphql-query-order.parser.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query.parser.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema.factory.ts
  packages/twenty-server/src/engine/api/rest/core/controllers/rest-api-core.controller.ts
  packages/twenty-server/src/engine/api/rest/core/handlers/rest-api-create-one.handler.ts
  packages/twenty-server/src/engine/api/rest/core/handlers/rest-api-delete-one.handler.ts
  packages/twenty-server/src/engine/api/rest/core/handlers/rest-api-get-many.handler.ts
  packages/twenty-server/src/engine/api/rest/core/handlers/rest-api-get-one.handler.ts
  packages/twenty-server/src/engine/api/rest/core/handlers/rest-api-update-one.handler.ts
  packages/twenty-server/src/engine/api/rest/core/interfaces/rest-api-base.handler.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/core-query-builder.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/create-one-query.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/delete-query.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/delete-variables.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/factories.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/find-many-query.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/find-one-query.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/get-variables.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/update-query.factory.ts
  packages/twenty-server/src/engine/api/rest/core/query-builder/factories/update-variables.factory.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core-v2.service.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core.module.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core.service.ts
  packages/twenty-server/src/engine/api/rest/core/types/query-variables.type.ts
  packages/twenty-server/src/engine/api/rest/input-factories/depth-input.factory.ts
  packages/twenty-server/src/engine/api/rest/input-factories/factories.ts
  packages/twenty-server/src/engine/api/rest/rest-api.module.ts
  packages/twenty-server/src/engine/core-modules/cache-storage/services/cache-storage.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.service.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/test/integration/constants/initial-person-data.constants.ts
  packages/twenty-server/test/integration/constants/mock-person-ids.constants.ts
  packages/twenty-server/test/integration/constants/test-company-ids.constants.ts
  packages/twenty-server/test/integration/constants/test-person-ids.constants.ts
  packages/twenty-server/test/integration/constants/test-primary-link-url.constant.ts
  packages/twenty-server/test/integration/graphql/suites/all-people-resolvers.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/auth.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/data-model.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-create-one.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-delete.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-find-many.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-find-one.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-update.integration-spec.ts
  packages/twenty-server/test/integration/utils/delete-all-records.ts
  packages/twenty-server/test/integration/utils/setup-test.ts
  packages/twenty-server/test/integration/utils/teardown-test.ts
Labels: -PR: wip, -PR: awaiting author

#11955 fixes on search
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableContent.tsx
  packages/twenty-server/src/database/commands/upgrade-version-command/0-53/0-53-upgrade-search-vector-on-person-entity.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-53/0-53-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/engine/core-modules/search/services/search.service.ts
  packages/twenty-server/src/engine/core-modules/search/utils/format-search-terms.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/__tests__/get-ts-vectors-column-expression.utils.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/utils/get-ts-vector-column-expression.util.ts
Labels: -PR: awaiting review

#11970 calendar sync failed
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/format-google-calendar-event.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/microsoft-calendar/utils/__tests__/format-microsoft-calendar-event.util.spec.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/microsoft-calendar/utils/format-microsoft-calendar-event.util.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts
Labels: -PR: awaiting author

#11930 Keyboard Navigation and Shortcuts Implementation on the board
  packages/twenty-front/src/modules/action-menu/actions/components/ActionModal.tsx
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useNavigateCommandMenu.ts
  packages/twenty-front/src/modules/keyboard-shortcut-menu/hooks/__tests__/useKeyboardShortcutMenu.test.tsx
  packages/twenty-front/src/modules/keyboard-shortcut-menu/hooks/useKeyboardShortcutMenu.ts
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardBodyEscapeHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardScrollToFocusedCardEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/useActiveRecordBoardCard.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useFocusedRecordBoardCard.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardCardNavigation.ts
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardSelection.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardDraggableContainer.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardFocusHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardDeactivateBoardCardEffect.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/contexts/RecordBoardCardContext.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumn.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsMemo.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/contexts/RecordBoardColumnContext.ts
  packages/twenty-front/src/modules/object-record/record-board/states/activeRecordBoardCardIndexesComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/focusedRecordBoardCardIndexesComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/isRecordBoardCardActiveComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/isRecordBoardCardFocusActiveComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/states/isRecordBoardCardFocusedComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-board/types/BoardCardIndexes.ts
  packages/twenty-front/src/modules/object-record/record-board/types/BoardHotkeyScope.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexBoardContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/types/RecordIndexHotkeyScope.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableWithWrappers.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useLeaveTableFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyEscapeHotkeyEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFocusKeyboardEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useMoveHoverToCurrentCell.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableTr.tsx
  packages/twenty-front/src/modules/object-record/record-table/types/TableHotkeyScope.ts
Labels: -PR: awaiting review, preview-app

#11972 Twenty config integration tests + conversion refactor
  packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/conversion/__tests__/config-value-converter.service.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/conversion/config-value-converter.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/filters/config-variable-graphql-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/storage/config-storage.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/twenty-config.module.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/twenty-config.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/__tests__/apply-basic-validators.util.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/__tests__/type-transformers.registry.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/apply-basic-validators.util.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/type-transformers.registry.ts
  packages/twenty-server/test/integration/twenty-config/constants/config-test-keys.constants.ts
  packages/twenty-server/test/integration/twenty-config/twenty-config.integration-spec.ts
  packages/twenty-server/test/integration/twenty-config/types/perform-twenty-config-query.type.ts
  packages/twenty-server/test/integration/twenty-config/utils/create-config-variable.query-factory.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/create-config-variable.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/delete-config-variable.query-factory.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/delete-config-variable.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/get-config-variable.query-factory.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/get-config-variable.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/get-config-variables-grouped.query-factory.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/get-config-variables-grouped.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/make-admin-panel-api-request.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/make-unauthenticated-api-request.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/update-config-variable.query-factory.util.ts
  packages/twenty-server/test/integration/twenty-config/utils/update-config-variable.util.ts
Labels: -PR: awaiting review

#12005 adapt billing banners according to user's permissions
  packages/twenty-front/src/modules/information-banner/components/billing/InformationBannerBillingSubscriptionPaused.tsx
  packages/twenty-front/src/modules/information-banner/components/billing/InformationBannerEndTrialPeriod.tsx
  packages/twenty-front/src/modules/information-banner/components/billing/InformationBannerFailPaymentInfo.tsx
  packages/twenty-front/src/modules/information-banner/components/billing/InformationBannerNoBillingSubscription.tsx
Labels: -PR: awaiting review

#12008 Fix relation deletion
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
Labels: -PR: awaiting review

#12011 Fix side panel click outside
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFocusClickOutsideEffect.tsx
Labels: -PR: awaiting review

#11998 Remove duplicated position for task's status field
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-fix-standard-select-fields-position.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/modules/task/standard-objects/task.workspace-entity.ts
Labels: -PR: awaiting review

#11952 delete attachment when file is removed from activity body
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/activities/hooks/useReplaceActivityBlockEditorContent.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/filterAttachmentsToRestore.test.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/getActivityAttachmentIdsToDelete.test.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/getActivityAttachmentPaths.test.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/getActivityAttachmentPathsToRestore.test.ts
  packages/twenty-front/src/modules/activities/utils/__tests__/getAttachmentPath.test.ts
  packages/twenty-front/src/modules/activities/utils/filterAttachmentsToRestore.ts
  packages/twenty-front/src/modules/activities/utils/getActivityAttachmentIdsToDelete.ts
  packages/twenty-front/src/modules/activities/utils/getActivityAttachmentPaths.ts
  packages/twenty-front/src/modules/activities/utils/getActivityAttachmentPathsToRestore.ts
  packages/twenty-front/src/modules/activities/utils/getAttachmentPath.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/services/record-input-transformer.service.ts
Labels: -PR: awaiting review

#12020 [DRAFT]: Add full Dev Workspace seeding to Preview Env Keep-Alive workflow
  .github/workflows/preview-env-keepalive.yaml
Labels: preview-app

#12013 Fix UI not being refreshed after grouping by None in the table
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts
Labels: -PR: awaiting review

#12023 Make the default view names consistent (#12022)
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/seed-view-with-demo-data.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/companies-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/opportunities-all.view.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/views/people-all.view.ts
Labels: blocked: product specs needed

#12038 Fix table click outside
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFocusClickOutsideEffect.tsx
Labels: -PR: awaiting review

#12046 Fix infinite loop critical bug
  packages/twenty-front/src/modules/object-record/record-store/components/RecordValueSetterEffect.tsx
Labels: preview-app

#12041 Messaging issues
  packages/twenty-server/src/engine/core-modules/exception-handler/drivers/sentry.driver.ts
  packages/twenty-server/src/engine/core-modules/exception-handler/interfaces/exception-handler-options.interface.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/utils/__tests__/is-temporary-error.utils.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/utils/is-temporary-error.utils.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-import-exception-handler.service.ts
Labels: -PR: awaiting author

#12072 Fixes infinite loop on record data update in command menu
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx
  packages/twenty-front/src/modules/activities/inline-cell/hooks/useUpdateActivityTargetFromCell.ts
  packages/twenty-front/src/modules/command-menu/pages/record-page/components/CommandMenuRecordPage.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowEffect.tsx
  packages/twenty-front/src/modules/object-record/record-store/components/RecordValueSetterEffect.tsx
  packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
Labels: -PR: awaiting review

#12054 QRQC #2 - Fix
  packages/twenty-server/src/database/typeorm-seeds/workspace/calendar-events.ts
  packages/twenty-server/test/integration/constants/calendar-event-gql-fields.constants.ts
  packages/twenty-server/test/integration/constants/message-gql-fields.constants.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/__snapshots__/calendar-events.integration-spec.ts.snap
  packages/twenty-server/test/integration/graphql/suites/object-generated/__snapshots__/messages.integration-spec.ts.snap
  packages/twenty-server/test/integration/graphql/suites/object-generated/calendar-events.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-generated/messages.integration-spec.ts
Labels: -PR: awaiting review

#12079 Add placeholder to signinup modal's secondary logo
  packages/twenty-front/src/modules/auth/components/Logo.tsx
  packages/twenty-front/src/modules/auth/components/__stories__/Logo.stories.tsx
  packages/twenty-front/src/modules/auth/components/__stories__/VerifyEmailEffect.stories.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/__stories__/EmailVerificationSent.stories.tsx
  packages/twenty-front/src/pages/auth/PasswordReset.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
Labels: -PR: ready to merge

#12081 Patch pg pool
  packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/database-config.driver.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/pg-shared-pool/__tests__/pg-shared-pool.service.spec.ts
  packages/twenty-server/src/engine/twenty-orm/pg-shared-pool/pg-shared-pool.module.ts
  packages/twenty-server/src/engine/twenty-orm/pg-shared-pool/pg-shared-pool.service.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.module.ts
Labels: -PR: awaiting author

#12101 Removed value setter effect completely
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventDetailsEffect.tsx
  packages/twenty-front/src/modules/command-menu/pages/calendar-event/components/CommandMenuCalendarEventPage.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItemEffect.tsx
  packages/twenty-front/src/modules/object-record/record-store/components/RecordValueSetterEffect.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/useRecordTable.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRow.tsx
Labels: preview-app

#12116 fix billingCustomer stripeId fetching
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-entitlement.service.ts
Labels: -PR: awaiting review

#12094 add command to clean not found files
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-clean-not-found-files.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-upgrade-version-command.module.ts
Labels: -PR: awaiting review

#12120 Fix modal click outside
  packages/twenty-front/src/modules/ui/layout/modal/components/ModalHotkeysAndClickOutsideEffect.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/__stories__/ConfirmationModal.stories.tsx
Labels: -PR: awaiting review

#12122 Fix Identifier chips in Timeline Activities are broken
  packages/twenty-front/src/modules/activities/timeline-activities/rows/main-object/components/EventFieldDiffValue.tsx
Labels: -PR: awaiting review

#12103 Fix/record board keyboard navigation empty columns
  packages/twenty-front/src/modules/object-record/record-board/hooks/useRecordBoardCardNavigation.ts
Labels: -PR: awaiting review

#11610 Support Full Name as Record Text Identifier
  packages/twenty-front/src/modules/object-metadata/constants/LabelIdentifierFieldMetadataTypes.ts
  packages/twenty-front/src/modules/object-metadata/utils/getLabelIdentifierFieldValue.ts
  packages/twenty-front/src/modules/object-record/hooks/useRecordChipData.ts
  packages/twenty-front/src/modules/object-record/utils/getRecordChipGenerators.ts
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx
  packages/twenty-server/src/engine/metadata-modules/utils/validate-metadata-name-is-not-reserved-keyword.ts
Labels: -PR: awaiting author

#11405 Refactor: Improve Docker volume permission handling and remove run-once service
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/twenty/Dockerfile
Labels: -PR: awaiting author

#11392 Fix #10941: Make sure content adjusts itself when resizing cell
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useChipFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContextLabelIdentifier.tsx
  packages/twenty-ui/src/components/chip/LinkChip.tsx
Labels: -PR: awaiting review

#12137 Fix: Deleting an opportunity from the relation detail section deletes a person
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItem.tsx
Labels: -PR: awaiting review

#12138 Fix: Editing a task assignee relation from the list opens both the command menu and the multi item picker
  packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx
Labels: -PR: awaiting review

#12139 Removed use-context-selector completely
  package.json
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventDetailsEffect.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/main-object/components/EventFieldDiff.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/main-object/components/EventFieldDiffValueEffect.tsx
  packages/twenty-front/src/modules/command-menu/pages/calendar-event/components/CommandMenuCalendarEventPage.tsx
  packages/twenty-front/src/modules/command-menu/pages/record-page/components/CommandMenuRecordPage.tsx
  packages/twenty-front/src/modules/object-record/record-field/hooks/useClearField.ts
  packages/twenty-front/src/modules/object-record/record-field/hooks/useIsFieldEmpty.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/RelationFromManyFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useChipFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-show/components/RecordShowEffect.tsx
  packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationRecordsListItemEffect.tsx
  packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/__stories__/perf/RecordTableCell.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldDisplay.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelSetFieldValueEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelSetRecordEffect.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/tabs/ObjectSettings.tsx
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldSelect.tsx
  packages/twenty-front/src/testing/decorators/RecordTableDecorator.tsx
  packages/twenty-front/src/testing/decorators/getFieldDecorator.tsx
  yarn.lock
Labels: -PR: ready to merge

#12136 better logging errors in messages
  packages/twenty-server/src/modules/calendar/blocklist-manager/jobs/blocklist-item-delete-calendar-events.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-cleaner/jobs/delete-connected-account-associated-calendar-data.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-ongoing-stale.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/jobs/calendar-ongoing-stale.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/jobs/calendar-create-company-and-contact-after-sync.job.ts
  packages/twenty-server/src/modules/messaging/blocklist-manager/jobs/messaging-blocklist-item-delete-messages.job.ts
  packages/twenty-server/src/modules/messaging/message-cleaner/jobs/messaging-connected-account-deletion-cleanup.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/utils/is-temporary-error.utils.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-clean-cache.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-partial-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.job.ts
Labels: -PR: awaiting author

#12143 Catching "no licence" microsoft account
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/parse-gaxios-error.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/exceptions/message-network.exception.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/utils/parse-gaxios-error.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/utils/parse-microsoft-messages-import.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-import-exception-handler.service.ts
Labels: -PR: awaiting author

#12130 lowercase user and invitation emails
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/workspace/components/WorkspaceInviteTeam.tsx
  packages/twenty-front/src/modules/workspace/utils/__tests__/sanitizeEmailList.test.ts
  packages/twenty-front/src/modules/workspace/utils/sanitizeEmailList.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-lowercase-user-and-invitation-emails.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-upgrade-version-command.module.ts
  packages/twenty-server/src/engine/core-modules/app-token/app-token.entity.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
Labels: -PR: awaiting review

#12113 Consider `null` values as empty values for link fields
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/hooks/useTextVariableEditor.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/__tests__/getFieldLinkDefinedLinks.test.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/getFieldLinkDefinedLinks.ts
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinksValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts
  packages/twenty-front/src/modules/object-record/utils/generateEmptyFieldValue.ts
  packages/twenty-front/src/modules/object-record/utils/prefillRecord.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts
  packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/LinksDisplay.stories.tsx
Labels: -PR: awaiting review

#12150 followup #12033
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffectsProvider.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/trigger-type/components/CommandMenuWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts
  packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerOpenedSection.tsx
  packages/twenty-front/src/modules/object-metadata/components/RemoteNavigationDrawerSection.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/hooks/useNonSystemActiveObjectMetadataItems.ts
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewEffect.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelObjectPickerDropdownContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionCreateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionDeleteRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFindRecords.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionUpdateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowFormFieldSettingsRecordPicker.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerManualForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getManualTriggerDefaultSettings.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getTriggerDefaultDefinition.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getManualTriggerDefaultSettings.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerDefaultDefinition.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
Labels: -PR: awaiting review

#12100 Move defaultAvatarUrl on userWorkspace + migration command
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-migrate-default-avatar-url-to-user-workspace.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-upgrade-version-command.module.ts
  packages/twenty-server/src/database/typeorm/core/migrations/common/1747401483135-addDefaultAvatarUrlColumnInUserWorkspaceTable.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/file-upload.module.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/services/file-upload.service.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.spec.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.module.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
Labels: -PR: ready to merge

#12173 Use `null` as the default value for link fields when persisting
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/LinksFieldInput.stories.tsx
Labels: -PR: awaiting review

#12169 Fix workflow sub objects updates validation
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-run-update-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-validation.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
Labels: -PR: awaiting author

#12199 add cursor rule for nx
  .cursor/rules/nx-rules.mdc
Labels: -PR: awaiting review

#12196 Fix "PageChangeEffect does not run when changing view on the same object"
  packages/twenty-front/src/hooks/__tests__/useIsMatchingLocation.test.tsx
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/useIsMatchingLocation.ts
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProvider.tsx
  packages/twenty-front/src/modules/context-store/components/MainContextStoreProvider.tsx
  packages/twenty-front/src/modules/ui/layout/fullscreen/hooks/useShowFullscreen.ts
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts
  packages/twenty-front/src/modules/users/components/UserProvider.tsx
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/utils/__tests__/isMatchingLocation.test.tsx
  packages/twenty-front/src/utils/isMatchingLocation.ts
Labels: -PR: awaiting review

#12195 captcha - keep consistency with token send to validation
  packages/twenty-server/src/engine/core-modules/captcha/captcha.guard.ts
Labels: -PR: awaiting review

#12147 Fix timezone display + translate dates
  packages/twenty-front/src/localization/states/dateLocaleState.ts
  packages/twenty-front/src/modules/localization/utils/__tests__/formatDateISOStringToCustomUnicodeFormat.test.js
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToCustomUnicodeFormat.ts
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToDate.ts
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToDateTime.ts
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToRelativeDate.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/DateFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/__stories__/perf/DateTimeFieldDisplay.perf.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateRemote.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useAggregateRecordsForHeader.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateTimeDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/DateDisplay.stories.tsx
  packages/twenty-front/src/modules/ui/field/display/utils/getDateFnsLocale.util.ts
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerEditButton.tsx
  packages/twenty-front/src/modules/workflow/components/OverrideWorkflowDraftConfirmationModal.tsx
  packages/twenty-front/src/pages/settings/profile/appearance/components/LocalePicker.tsx
  packages/twenty-front/src/utils/string/__tests__/formatDateString.test.ts
  packages/twenty-front/src/utils/string/__tests__/formatDateTimeString.test.ts
  packages/twenty-front/src/utils/string/formatDateString.ts
  packages/twenty-front/src/utils/string/formatDateTimeString.ts
Labels: -PR: awaiting author

#12186 Improve lazy loading
  package.json
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/utils/exportBlockNoteEditorToPdf.ts
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/files/components/DocumentViewer.tsx
  packages/twenty-front/src/modules/activities/files/const/previewable-extensions.const.ts
  packages/twenty-front/src/modules/error-handler/components/AppErrorBoundary.tsx
  packages/twenty-front/src/modules/error-handler/components/SentryInitEffect.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerMetricsTooltip.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/mapWorkbook.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/mapWorkbook.ts
  packages/twenty-front/src/modules/ui/input/components/internal/hooks/useCountries.ts
  packages/twenty-front/src/modules/ui/input/components/internal/types/Country.ts
  packages/twenty-front/src/modules/ui/layout/tab/components/TabList.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/hooks/useAvailableVariablesInWorkflowStep.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/__tests__/parseEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/getInitialEditorContent.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/parseEditorContent.ts
  packages/twenty-front/vite.config.ts
  packages/twenty-ui/src/testing/decorators/CatalogDecorator.tsx
  packages/twenty-ui/vite.config.ts
  yarn.lock
Labels: -PR: wip, -PR: awaiting author

#12219 add more logs to cleaning command
  packages/twenty-server/src/database/commands/upgrade-version-command/0-54/0-54-clean-not-found-files.command.ts
Labels: -PR: awaiting review

#12221 Fix + column header in tables
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderLastColumn.tsx
Labels: -PR: awaiting review

#12121 FieldMetadata ENUM `CREATE` `UPDATE` server validation and integration tests
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-enum-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-valid-graphql-enum-name.validator.ts
  packages/twenty-server/src/engine/seeder/data-seeds/pets-data-seeds.ts
  packages/twenty-server/src/engine/seeder/metadata-seeds/pets-metadata-seeds.ts
  packages/twenty-server/src/utils/__test__/is-snake-case-string.spec.ts
  packages/twenty-server/src/utils/__test__/trim-and-remove-duplicated-whitespaces-from-object-string-properties.spec.ts
  packages/twenty-server/src/utils/is-snake-case-string.ts
  packages/twenty-server/src/utils/trim-and-remove-duplicated-whitespaces-from-object-string-properties.ts
  packages/twenty-server/test/integration/graphql/suites/search/search-resolver.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/__snapshots__/create-one-field-metadata-select.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/__snapshots__/update-one-field-metadata-select.integration-spec.ts.snap
  packages/twenty-server/test/integration/metadata/suites/field-metadata/create-one-field-metadata-select.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-create-one-field-metadata-select-tests-cases.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-select.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata.integration-spec.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/utils/find-many-fields-metadata-query-factory.util.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/utils/find-many-fields-metadata.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/find-many-object-metadata.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/utils/force-create-one-object-metadata.util.ts
Labels: -PR: awaiting author

#12243 Fix/exit settings link stuck 12235
  packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffectsProvider.tsx
Labels: -PR: awaiting review

#12236 feat(settings): replace TextInputV2 with TextInput and update hotkey …
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/pages/settings/security/SettingsSecurityApprovedAccessDomain.tsx
Labels: -PR: awaiting review

#12234 Fixed dropdown flip and resize edge cases
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/constants/DropdownResizeMinHeight.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/constants/DropdownResizeMinWidth.ts
Labels: -PR: awaiting review

#12188 Discard empty and `null` links in Links fields
  packages/twenty-front/src/modules/object-record/record-field/__mocks__/fieldDefinitions.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/LinksFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/__tests__/getFieldLinkDefinedLinks.test.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/utils/getFieldLinkDefinedLinks.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldLinksValue.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/__tests__/isFieldValueEmpty.test.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueEmpty.ts
  packages/twenty-front/src/modules/ui/field/display/components/__stories__/LinksDisplay.stories.tsx
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/workspace-query-runner-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/record-transformer.exception.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/services/record-input-transformer.service.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/__tests__/remove-empty-links.spec.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/record-transformer-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/remove-empty-links.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/links.composite-type.ts
  packages/twenty-server/test/integration/constants/test-primary-link-url.constant.ts
  packages/twenty-shared/src/utils/url/__tests__/isValidUrl.test.ts
Labels: -PR: awaiting author, -PR: awaiting CI

#12191 patch messages in thread
  packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts
  packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx
  packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/useEmailThreadInCommandMenu.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/find-records.workflow-action.ts
  packages/twenty-shared/src/constants/QueryMaxRecords.ts
  packages/twenty-shared/src/constants/index.ts
Labels: -PR: awaiting review

#12246 Display "Untitled" in MultipleRecordPicker
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItemContent.tsx
Labels: -PR: awaiting review

#12225 Empty Gmail box bug
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-message-list.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-message-list.service.ts
Labels: -PR: awaiting review

#12051 Infinite scrolling in relation picker menu
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/command-menu/graphql/queries/search.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuSearchRecords.tsx
  packages/twenty-front/src/modules/object-record/hooks/useObjectRecordSearchRecords.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPicker.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerFetchMoreLoader.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerItemsDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerMenuItems.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/components/MultipleRecordPickerSearchInput.tsx
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/hooks/useMultipleRecordPickerPerformSearch.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/states/multipleRecordPickerPaginationState.ts
  packages/twenty-front/src/modules/object-record/record-picker/multiple-record-picker/states/selectors/multipleRecordPickerPaginationSelector.ts
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/cursors.util.ts
  packages/twenty-server/src/engine/core-modules/search/__tests__/search.service.spec.ts
  packages/twenty-server/src/engine/core-modules/search/constants/results-limit-by-object-without-search-terms.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-args.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-record.dto.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-result-connection.dto.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-result-edge.dto.ts
  packages/twenty-server/src/engine/core-modules/search/dtos/search-result-page-info.dto.ts
  packages/twenty-server/src/engine/core-modules/search/search.resolver.ts
  packages/twenty-server/src/engine/core-modules/search/services/search.service.ts
  packages/twenty-server/src/engine/seeder/seeder.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-manager.service.ts
  packages/twenty-server/test/integration/constants/test-api-key-ids.constant.ts
  packages/twenty-server/test/integration/constants/test-pet-ids.constants.ts
  packages/twenty-server/test/integration/graphql/suites/search/search-resolver.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/search-factory.util.ts
  packages/twenty-server/test/integration/metadata/suites/object-metadata/constants/test-object-names.constant.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-update.integration-spec.ts
  packages/twenty-server/test/integration/utils/clean-test-database.ts
  packages/twenty-server/test/integration/utils/create-app.ts
  packages/twenty-server/test/integration/utils/setup-test.ts
Labels: -PR: awaiting author

#12261 fix(auth): prevent unexpected form effect trigger
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeFormEffect.tsx
Labels: -PR: awaiting review

#12245 fix(): remove originHeader decorator
  packages/twenty-front/codegen-metadata.cjs
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/getAuthTokensFromLoginToken.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/getLoginTokenFromCredentials.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/getLoginTokenFromEmailVerificationToken.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/resendEmailVerificationToken.ts
  packages/twenty-front/src/modules/auth/graphql/queries/getPublicWorkspaceDataByDomain.ts
  packages/twenty-front/src/modules/auth/hooks/__mocks__/useAuth.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useHandleResendEmailVerificationToken.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useGetPublicWorkspaceDataByDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useOrigin.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/email-verification/email-verification.resolver.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/decorators/auth/origin-header.decorator.ts
  packages/twenty-server/test/integration/graphql/suites/auth.integration-spec.ts
Labels: -PR: awaiting review

#12250 fix(email-verification): prevent double email validation
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/getLoginTokenFromEmailVerificationToken.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/get-login-token-from-email-verification-token.input.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/email-verification-token.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/email-verification-token.service.ts
  packages/twenty-server/src/engine/core-modules/email-verification/email-verification-exception-filter.util.ts
  packages/twenty-server/src/engine/core-modules/email-verification/email-verification.exception.ts
  packages/twenty-server/src/engine/core-modules/email-verification/email-verification.module.ts
  packages/twenty-server/src/engine/core-modules/graphql/utils/graphql-errors.util.ts
Labels: -PR: awaiting review

#12181 Changed the auto matching of columns in import
  package.json
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSpreadSheetFieldValidationDefinitions.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UnmatchColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/utils/getMatchedColumnsWithFuse.ts
  yarn.lock
Labels: -PR: awaiting review

#12266 Prevent setting primary link as primary link
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/ArrayFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldMenuItem.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/ArrayFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailsFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/LinksFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhonesFieldInput.stories.tsx
Labels: -PR: awaiting review

#12276 fix/replace-set-primary-with-bookmark-12268
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailsFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhonesFieldInput.stories.tsx
Labels: -PR: wip, -PR: awaiting author

#12310 Commit `index.ts` twenty-ui
  packages/twenty-ui/src/utilities/index.ts
Labels: -PR: awaiting CI

#12321 Add mcp.json to gitignore
  .gitignore
Labels: -PR: awaiting review

#12293 feat: trim empty space
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/ArrayFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/EmailsFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/LinksFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/PhonesFieldInput.stories.tsx
Labels: -PR: awaiting review

#11820 Add relations in database event trigger output data
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/engine/core-modules/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts
  packages/twenty-server/src/engine/core-modules/search/__tests__/search.service.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/object-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/utils/remove-field-maps-from-object-metadata.util.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/__tests__/generate-fake-form-response.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/__tests__/generate-fake-object-record-event.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/__tests__/generate-fake-object-record.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/__tests__/generate-object-record-fields.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-field.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-form-response.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-object-record-event.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-fake-object-record.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/generate-object-record-fields.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/utils/should-generate-field-fake-value.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/workflow-schema.module.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-schema/workflow-schema.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/automated-trigger/automated-trigger.module.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/automated-trigger/listeners/database-event-trigger.listener.ts
Labels: -PR: ready to merge

#12308 Fix Client Config async loading
  packages/twenty-front/src/loading/components/__stories__/UserOrMetadataLoader.stories.tsx
  packages/twenty-front/src/modules/activities/files/utils/__tests__/downloadFile.test.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProvider.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/hooks/useClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/clientConfigApiStatusState.ts
  packages/twenty-front/src/modules/client-config/utils/__tests__/clientConfigUtils.test.ts
  packages/twenty-front/src/modules/client-config/utils/getClientConfig.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useGetPublicWorkspaceDataByDomain.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useReadDefaultDomainFromConfiguration.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToDefaultDomain.ts
  packages/twenty-front/src/modules/settings/admin-panel/config-variables/hooks/useConfigVariableActions.ts
  packages/twenty-front/src/pages/auth/Authorize.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/src/engine/core-modules/captcha/interfaces/captcha.interface.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.controller.spec.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.controller.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.module.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.spec.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/core-modules/client-config/services/client-config.service.spec.ts
  packages/twenty-server/src/engine/core-modules/client-config/services/client-config.service.ts
Labels: -PR: awaiting author

#12298 Fix members table column alignment
  packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx
Labels: -PR: awaiting author
