Repository twentyhq/twenty, pull requests merged in 2025-01, with the labels that each got.

#9301 fix "Relations" not displayed on kanban views
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordBoardRecordGqlFields.ts
Labels: type: chore, -PR: awaiting CI, prio: CRITICAL 🚨

#9309 Add E2E tests
  .github/workflows/ci-e2e.yml
  .github/workflows/ci-e2e.yml.bak
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/twenty.code-workspace
  packages/twenty-e2e-testing/.env.example
  packages/twenty-e2e-testing/playwright.config.ts
  packages/twenty-e2e-testing/tests/all/companies.e2e-spec.ts
  packages/twenty-e2e-testing/tests/all/workspaces.e2e-spec.ts
  packages/twenty-e2e-testing/tests/all/workspaces.spec.ts
  packages/twenty-e2e-testing/tests/authentication/login.spec.ts
  packages/twenty-e2e-testing/tests/demo/demo_basic.e2e-spec.ts
  packages/twenty-e2e-testing/tests/login.setup.ts
  packages/twenty-front/package.json
Labels: run-e2e

#9307 Fix frontend bug when filtering with special character
  package.json
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts
  yarn.lock
Labels: -PR: awaiting author

#9321 Fix user deletion when workspace is deleted
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
Labels: -PR: awaiting review

#9319 Deprecate share email thread
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useRightDrawerEmailThread.ts
  packages/twenty-front/src/modules/activities/right-drawer/components/MessageThreadSubscribersTopBar.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerTopBar.tsx
  packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawerTopBarDropdownButton.tsx
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-thread-subscriber.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-thread.workspace-entity.ts
  packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts
Labels: -PR: awaiting review

#9162 fix: view group followup
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerAttachRelationOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdown.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownHiddenRecordGroupsContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupSortContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/hooks/useSetRecordBoardRecordIds.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnDropdownMenu.tsx
  packages/twenty-front/src/modules/object-record/record-group/components/RecordGroupReorderConfirmationModal.tsx
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupReorder.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupReorderConfirmationModal.ts
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupVisibility.ts
  packages/twenty-front/src/modules/object-record/record-group/states/isRecordGroupReorderConfirmationModalVisibleState.ts
  packages/twenty-front/src/modules/object-record/record-group/states/recordGroupPendingDragEndReorderState.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/availableRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/visibleRecordGroupIdsComponentFamilySelector.ts
  packages/twenty-front/src/modules/object-record/record-group/states/selectors/visibleRecordGroupIdsComponentSelector.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexAddRecordInGroupDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageKanbanAddButton.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageTableAddButton.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexRecordGroupHideComponentFamilyState.ts
  packages/twenty-front/src/modules/object-record/record-index/states/recordIndexRecordGroupHideComponentState.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyState.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateByGroupNoRecordAtAll.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateNoGroupNoRecordAtAll.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateNoRecordFoundForFilter.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateRemote.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateSoftDelete.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/__stories__/RecordTableEmptyStateNoGroupNoRecordAtAll.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupEmptyRow.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
  packages/twenty-front/src/modules/object-record/record-table/states/selectors/hasPendingRecordComponentSelector.ts
  packages/twenty-front/src/modules/settings/utils/getSettingsPagePath.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/hooks/useSetFocusedDropdownIdAndMemorizePrevious.ts
  packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/modules/ui/utilities/state/component-state/utils/createComponentFamilyStateV2.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting review

#9304 Aggregate count variations
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useAggregateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/getAggregateOperationLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/getAggregateOperationLabel.ts
  packages/twenty-front/src/modules/object-record/record-board/types/RecordBoardColumnHeaderAggregateContentId.ts
  packages/twenty-front/src/modules/object-record/record-table/constants/AggregateOperations.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateDropdownSubmenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterAggregateOperationMenuItems.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownMoreOptionsContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/constants/countAggregateOperationOptions.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/constants/percentAggregateOperationOption.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/constants/standardAggregateOperationOptions.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/types/RecordTableFooterAggregateContentId.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/utils/getAvailableAggregateOperationsForFieldMetadataType.ts
  packages/twenty-front/src/modules/object-record/types/AggregateOperationsOmittingCount.ts
  packages/twenty-front/src/modules/object-record/types/AggregateOperationsOmittingStandardOperations.ts
  packages/twenty-front/src/modules/object-record/types/AvailableFieldsForAggregateOperation.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/getAvailableFieldsIdsForAggregationFromObjectFields.test.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/initializeAvailableFieldsForAggregateOperationMap.test.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/isFieldTypeValidForAggregateOperation.test.ts
  packages/twenty-front/src/modules/object-record/utils/getAvailableAggregationsFromObjectFields.ts
  packages/twenty-front/src/modules/object-record/utils/getAvailableFieldsIdsForAggregationFromObjectFields.ts
  packages/twenty-front/src/modules/object-record/utils/isFieldTypeValidForAggregateOperation.ts
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/constants/aggregate-operations.constant.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-aggregate.helper.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-available-aggregations-from-object-fields.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/constants/fieldMetadataTypesToTextColumnType.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/utils/field-metadata-type-to-column-type.util.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/utils/is-text-column-type.util.ts
  packages/twenty-server/src/modules/view/standard-objects/view-field.workspace-entity.ts
  packages/twenty-server/src/modules/view/standard-objects/view.workspace-entity.ts
  packages/twenty-shared/src/index.ts
  packages/twenty-shared/src/types/FieldMetadataType.ts
  packages/twenty-shared/src/utils/aggregateOperations/getColumnNameForAggregateOperation.util.ts
  packages/twenty-shared/src/utils/aggregateOperations/getSubFieldForAggregateOperation.util.ts
  packages/twenty-shared/src/utils/aggregateOperations/index.ts
  packages/twenty-shared/src/utils/aggregateOperations/isCompositeFieldMetadataType.util.ts
  packages/twenty-shared/src/utils/strings/capitalize.ts
Labels: -PR: awaiting author

#9326 Creating a new task is not very smooth
  packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts
Labels: -PR: awaiting review, prio: high

#9330 Fixed import modal content scroll bug
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
Labels: prio: CRITICAL 🚨

#9335 Fix access to workflow version
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useSeeVersionsWorkflowVersionSingleRecordAction.ts
Labels: -PR: awaiting review

#9343 tiny margin error
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerIconAndNameContainer.tsx
Labels: -PR: awaiting review, prio: low

#9339 adding some delay for tooltip
  packages/twenty-front/src/modules/ui/field/display/components/TextDisplay.tsx
  packages/twenty-front/src/modules/views/components/ViewFieldsVisibilityDropdownSection.tsx
  packages/twenty-ui/src/display/tooltip/AppTooltip.tsx
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
  packages/twenty-ui/src/display/tooltip/__stories__/Tooltip.stories.tsx
Labels: -PR: awaiting author, prio: med

#9328 Move the workflow draft version overriding to the backend
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useUseAsDraftWorkflowVersionSingleRecordAction.tsx
  packages/twenty-front/src/modules/workflow/components/OverrideWorkflowDraftConfirmationModal.tsx
  packages/twenty-front/src/modules/workflow/components/RecordShowPageWorkflowVersionHeader.tsx
  packages/twenty-front/src/modules/workflow/graphql/mutations/overrideWorkflowDraftVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useCreateDraftFromWorkflowVersion.ts
  packages/twenty-server/src/engine/core-modules/serverless/utils/serverless-get-folder.utils.ts
  packages/twenty-server/src/engine/core-modules/workflow/dtos/create-draft-from-workflow-version-input.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/engine/twenty-orm/utils/format-data.util.ts
  packages/twenty-server/src/modules/workflow/common/utils/assert-workflow-version-has-steps.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
Labels: -PR: awaiting review

#9420 Remove buggy refetch query
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
Labels: -PR: awaiting review

#9434 Refactor activate workflow actions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/WorkflowActionsConfig.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateDraftWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateLastPublishedVersionWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/__tests__/useActivateWorkflowSingleRecordAction.test.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useActivateDraftWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/hooks/useActivateWorkflowSingleRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/types/WorkflowSingleRecordActionsKeys.ts
Labels: -PR: awaiting review

#9403 fix: avoid clipping by aggregate footer
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellEditMode.tsx
Labels: -PR: awaiting review

#9441 [REFACTOR][FRONT]: Remove objectMetadata and fieldMetadata sluggification
  packages/twenty-front/src/modules/navigation/hooks/useLastVisitedObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useFilteredObjectMetadataItems.test.tsx
  packages/twenty-front/src/modules/object-metadata/hooks/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getFieldSlug.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/getObjectSlug.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/getFieldSlug.ts
  packages/twenty-front/src/modules/object-metadata/utils/getObjectSlug.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownHiddenFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownHiddenRecordGroupsContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderPlusButtonContent.tsx
  packages/twenty-front/src/modules/settings/data-model/components/SettingsDataModelNewFieldBreadcrumbDropDown.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsObjectNewFieldSelector.tsx
  packages/twenty-front/src/modules/settings/data-model/graph-overview/components/SettingsDataModelOverviewObject.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx
  packages/twenty-front/src/modules/settings/data-model/object-details/components/tabs/ObjectSettings.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/modules/views/view-picker/hooks/useGetAvailableFieldsForKanban.ts
  packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetailPage.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldSelect.tsx
  packages/twenty-front/src/pages/settings/data-model/SettingsObjects.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectDetail.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectFieldEdit.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldConfigure.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/__stories__/SettingsObjectNewField/SettingsObjectNewFieldSelect.stories.tsx
  packages/twenty-front/src/pages/settings/data-model/states/updatedObjectNamePluralState.ts
  packages/twenty-front/src/pages/settings/data-model/states/updatedObjectSlugState.ts
Labels: -PR: awaiting author

#9453 Multi item input hotkeys fixes
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/ui/field/input/components/DateInput.tsx
Labels: -PR: awaiting author

#9141 Navigation drawer scroll padding fix
  packages/twenty-front/src/modules/navigation/components/MainNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooter.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawer.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: -PR: awaiting CI

#9287 Animated the Sidebar Objects Tree view opening/closing
  packages/twenty-front/src/modules/favorites/components/CurrentWorkspaceMemberFavorites.tsx
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx
  packages/twenty-front/src/modules/settings/components/AdvancedSettingsWrapper.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/hooks/useExpandedAnimation.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UnmatchColumn.tsx
  packages/twenty-ui/src/layout/animated-expandable-container/__stories__/AnimatedExpandableContainer.stories.tsx
  packages/twenty-ui/src/layout/animated-expandable-container/components/AnimatedExpandableContainer.tsx
  packages/twenty-ui/src/layout/animated-expandable-container/types/AnimationDimension.ts
  packages/twenty-ui/src/layout/animated-expandable-container/types/AnimationDurationObject.ts
  packages/twenty-ui/src/layout/animated-expandable-container/types/AnimationDurations.ts
  packages/twenty-ui/src/layout/animated-expandable-container/types/AnimationMode.ts
  packages/twenty-ui/src/layout/animated-expandable-container/types/AnimationSize.ts
  packages/twenty-ui/src/layout/animated-expandable-container/utils/getCommonStyles.ts
  packages/twenty-ui/src/layout/animated-expandable-container/utils/getExpandableAnimationConfig.ts
  packages/twenty-ui/src/layout/animated-expandable-container/utils/getTransitionValues.ts
  packages/twenty-ui/src/layout/expandableContainer/components/ExpandableContainer.tsx
  packages/twenty-ui/src/layout/expandableContainer/components/__stories__/ExpandableContainer.stories.tsx
  packages/twenty-ui/src/layout/index.ts
Labels: -PR: awaiting review

#9450 Remove identifierFieldMetadataId from createObjectInput
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/dtos/create-object.input.ts
Labels: -PR: awaiting author

#9439 Fix dropdown input design
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemBaseInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/MultiItemBaseInput.stories.tsx
  packages/twenty-front/src/modules/ui/field/input/components/PhoneInput.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/currency/components/CurrencyPickerDropdownButton.tsx
  packages/twenty-front/src/modules/ui/input/components/internal/phone/components/PhoneCountryPickerDropdownButton.tsx
Labels: -PR: awaiting author

#9444 Implement aggregate operations on dates
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownFieldsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownOptionsContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAggregateRecordsForRecordBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/states/aggregateOperationComponentState.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/getAggregateOperationLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/getAggregateOperationLabel.ts
  packages/twenty-front/src/modules/object-record/record-table/constants/FieldTypesAvailableForNonStandardAggregateOperation.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterAggregateOperationMenuItems.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValue.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterValueCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterWithDropdown.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/types/ExtendedAggregateOperations.ts
  packages/twenty-front/src/modules/object-record/types/AvailableFieldsForAggregateOperation.ts
  packages/twenty-front/src/modules/object-record/utils/convertAggregateOperationToExtendedAggregateOperation.ts
  packages/twenty-front/src/modules/object-record/utils/convertExtendedAggregateOperationToAggregateOperation.ts
  packages/twenty-front/src/modules/object-record/utils/getAvailableAggregationsFromObjectFields.ts
  packages/twenty-front/src/modules/object-record/utils/getAvailableFieldsIdsForAggregationFromObjectFields.ts
  packages/twenty-front/src/modules/object-record/utils/initializeAvailableFieldsForAggregateOperationMap.ts
  packages/twenty-front/src/modules/ui/field/display/components/DateTimeDisplay.tsx
  packages/twenty-front/src/utils/string/__tests__/formatDateString.test.ts
  packages/twenty-front/src/utils/string/formatDateString.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/utils/get-available-aggregations-from-object-fields.util.ts
Labels: -PR: awaiting author

#9043 Fix : #8825 If attachment token expires, it throws a 500 error instead of Unauthenticated
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts
  packages/twenty-server/src/engine/core-modules/file/file.exception.ts
  packages/twenty-server/src/engine/core-modules/file/filters/file-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts
  packages/twenty-server/src/engine/core-modules/file/services/file.service.ts
  packages/twenty-ui/src/layout/index.ts
Labels: -PR: awaiting review

#9465 Fix scalar throwing 500
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/cursor.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/position.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/raw-json.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/time.scalar.ts
  packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-types/scalars/uuid.scalar.ts
Labels: -PR: awaiting CI

#9472 Navigation drawer sibling gap fix
  packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx
Labels: -PR: awaiting review

#9474 fix: add logo url response status check when creating workspace
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
Labels: -PR: awaiting review

#9317 Add Integration and unit tests on Billing
  .eslintrc.cjs
  .github/workflows/ci-server.yaml
  .vscode/settings.json
  nx.json
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-customer-data.command.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-sync-plans-data.command.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/billing/jobs/update-subscription-quantity.job.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-entitlement.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-price.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-billing-meter.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-billing-portal.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-checkout.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-customer.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-price.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-webhook.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe-sdk/mocks/stripe-sdk-mock.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe-sdk/mocks/stripe-sdk.mock.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe-sdk/services/stripe-sdk.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe-sdk/stripe-sdk.module.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.module.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.service.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/is-stripe-valid-product-metadata.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-entitlement-updated-event-to-entitlement-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-meter-data-to-meter-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-price-data-to-price-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-price-event-to-price-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-product-data-to-product-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-product-event-to-product-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-subscription-event-to-customer-repository-data.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/transform-stripe-subscription-event-to-subscription-repository-data.util.spec.ts
  packages/twenty-server/test/integration/billing/suites/billing-controller.integration-spec.ts
  packages/twenty-server/test/integration/billing/utils/create-mock-stripe-entitlement-updated-data.util.ts
  packages/twenty-server/test/integration/billing/utils/create-mock-stripe-price-created-data.util.ts
  packages/twenty-server/test/integration/billing/utils/create-mock-stripe-product-updated-data.util.ts
  packages/twenty-server/test/integration/billing/utils/create-mock-stripe-subscription-created-data.util.ts
  packages/twenty-server/test/integration/utils/create-app.ts
Labels: -PR: wip, -PR: awaiting review

#9516 chore: update returned attachement fullPath
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
  packages/twenty-front/src/modules/activities/files/components/AttachmentRow.tsx
  packages/twenty-front/src/modules/activities/files/hooks/useUploadAttachmentFile.tsx
  packages/twenty-front/src/modules/activities/files/utils/__tests__/downloadFile.test.ts
  packages/twenty-front/src/modules/activities/files/utils/downloadFile.ts
  packages/twenty-front/src/utils/file/__tests__/getFileAbsoluteURI.test.ts
  packages/twenty-front/src/utils/file/getFileAbsoluteURI.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/attachment-query-result-getter.handler.ts
Labels: -PR: awaiting review

#9481 Feature flags env variable gating
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
  packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/canManageFeatureFlagsState.ts
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminContent.tsx
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonate.ts
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
Labels: -PR: awaiting CI

#9489 Add error marker when invalid main function
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/__tests__/getWrongExportedFunctionMarkers.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getWrongExportedFunctionMarkers.ts
  packages/twenty-ui/src/input/code-editor/components/CodeEditor.tsx
Labels: -PR: awaiting author

#9462 [refactor]: Remove isSSOEnabled logic throughout the codebase
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/AppRouter.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/app/hooks/useCreateAppRouter.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/isSSOEnabledState.ts
  packages/twenty-front/src/pages/settings/security/SettingsSecurity.tsx
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/.env.example
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/core-modules/sso/services/sso.service.ts
  packages/twenty-server/src/main.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: ready to merge

#9437 Add suggested values for variable dropdown
  packages/twenty-e2e-testing/package.json
  packages/twenty-emails/package.json
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/workflow/states/serverlessFunctionTestDataFamilyState.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/components/WorkflowVariablesDropdownFieldItems.tsx
  packages/twenty-server/package.json
  packages/twenty-server/src/engine/utils/generate-fake-value.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/utils/generate-fake-object-record.ts
  packages/twenty-ui/package.json
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemSelect.tsx
  packages/twenty-ui/src/navigation/menu-item/internals/components/MenuItemLeftContent.tsx
  packages/twenty-website/package.json
Labels: -PR: awaiting author

#9548 refactor(admin-panel): standardize FeatureFlagKey usage
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useFeatureFlagsManagement.ts
  packages/twenty-front/src/modules/settings/admin-panel/types/FeatureFlag.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.spec.ts
Labels: -PR: ready to merge

#9448 [CI][FRONT] Storybook tests sharding and build optimization
  .github/workflows/ci-front.yaml
  nx.json
  packages/twenty-front/.storybook/main.ts
Labels: -PR: wip, -PR: awaiting author

#9140 fix: reset table selection when navigating away from index page
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: -PR: ready to merge

#9332 Playwright E2E test - sign up with invite link via email
  .github/workflows/ci-e2e.yml
  packages/twenty-e2e-testing/.env.example
  packages/twenty-e2e-testing/playwright.config.ts
  packages/twenty-e2e-testing/tests/all/companies.e2e-spec.ts
  packages/twenty-e2e-testing/tests/all/workspaces.e2e-spec.ts
  packages/twenty-e2e-testing/tests/authentication/fixture.ts
  packages/twenty-e2e-testing/tests/authentication/signup_invite_email.e2e-spec.ts
  packages/twenty-e2e-testing/tests/login.setup.ts
Labels: -PR: awaiting author, run-e2e

#9544 [Microsoft integration] getFullMessageList
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/commands/calendar-event-list-fetch.cron.command.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/messaging-microsoft-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/providers/microsoft-client.provider.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-message-list.service.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting review

#9571 fix: error thrown when switching between table with/without record group
  packages/twenty-front/src/modules/object-record/record-index/hooks/useSetRecordIndexEntityCount.ts
Labels: -PR: awaiting CI

#9466 Fixing phone search functionality
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/constants/NumberFilterTypes.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/constants/TextFilterTypes.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/computeViewRecordGqlOperationFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/getEmptyRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
Labels: -PR: awaiting author

#9559 Aggregate footer should have pseudo element only if there is horizontal scroll
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooter.tsx
Labels: -PR: awaiting review

#9535 Remove serverless functions on version archivation
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/computeViewRecordGqlOperationFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/serverless-functions/hooks/useTestServerlessFunction.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/__tests__/useServerlessFunctionUpdateFormState.test.ts
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useServerlessFunctionUpdateFormState.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/pages/settings/serverless-functions/SettingsServerlessFunctionDetail.tsx
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-step.workspace-service.ts
Labels: -PR: wip, -PR: awaiting author

#9575 fix: drop record group feature flag
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownRecordGroupsContent.tsx
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting author

#9577 Refech code after code update
  packages/twenty-front/src/modules/settings/serverless-functions/hooks/useUpdateOneServerlessFunction.ts
Labels: -PR: awaiting review

#9515 9426 migrate workflow pages to command menu
  packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuPages.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuRouter.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuAnimationVariants.ts
  packages/twenty-front/src/modules/command-menu/constants/CommandMenuPagesConfig.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHotKeys.ts
  packages/twenty-front/src/modules/command-menu/types/CommandMenuAnimationVariant.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/utils/mapRightDrawerPageToCommandMenuPage.ts
  packages/twenty-front/src/modules/ui/layout/selectable-list/hooks/useSelectableList.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonly.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonlyEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVersionVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useRightDrawerState.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/__tests__/useDeleteStep.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useDeleteStep.ts
Labels: -PR: awaiting author, -PR: awaiting CI

#9581 Aggregate queries follow up
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useRefetchAggregateQueries.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useRefetchAggregateQueries.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumn.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/contexts/RecordBoardColumnContext.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/hooks/useAggregateRecordsForRecordBoardColumn.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/computeAggregateValueAndLabel.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/getAggregateOperationShortLabel.ts
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableRecordGroupsBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableAggregateFooterCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/hooks/useAggregateRecordsForRecordTableColumnFooter.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableTr.tsx
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting review

#9585 Fix featureFlag not matching gql type
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.entity.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/services/feature-flag.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/workspace-sync-metadata.service.ts
Labels: -PR: awaiting review

#9590 Support old relation filter value format
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordSelect.tsx
  packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/views/components/ViewBarFilterEffect.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewFromQueryParams.ts
  packages/twenty-front/src/modules/views/view-filter-value/types/RelationFilterValue.ts
  packages/twenty-front/src/modules/views/view-filter-value/validation-schemas/jsonRelationFilterValueSchema.ts
  packages/twenty-front/src/modules/views/view-filter-value/validation-schemas/simpleRelationFilterValueSchema.ts
Labels: -PR: wip

#9582 Add readonly mode to form fields - 2nd part
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormCountryCodeSelectInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormCountrySelectInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormCurrencyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormPhoneFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormRawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormUuidFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormAddressFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormEmailsFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormFullNameFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormLinksFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormPhoneFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRawJsonFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormUuidFieldInput.stories.tsx
  packages/twenty-front/src/modules/ui/field/display/components/SelectDisplay.tsx
Labels: -PR: awaiting review

#9583 [CI] Refactor composite action task-cache
  .github/workflows/actions/restore-cache/action.yml
  .github/workflows/actions/save-cache/action.yml
  .github/workflows/actions/task-cache/action.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
Labels: -PR: awaiting review

#9596 [CI][NITPICK] Remove input `types` invalid syntax
  .github/workflows/actions/nx-affected/action.yaml
  .github/workflows/actions/restore-cache/action.yml
  .github/workflows/actions/save-cache/action.yml
Labels: -PR: awaiting review

#9600 Fix form date time field right border when variable picker is provided and field is readonly
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateTimeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateTimeFieldInput.stories.tsx
Labels: -PR: awaiting review

#9606 Fix error when deleting the trigger of an activated workflow version
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useDeleteStep.ts
Labels: -PR: awaiting review

#9610 Add command to tag workspace as suspended or as deleted
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/logger.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-backfill-view-groups.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-copy-webhook-operation-into-operations-command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-simplify-search-vector-expression.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-32/0-32-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-delete-view-fields-without-views.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-enforce-unique-constraints.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-set-missing-label-identifier-to-custom-objects.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-update-rich-text-search-vector-expression.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-33/0-33-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-34/0-34-generate-subdomain.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-34/0-34-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-34/0-34-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-phone-calling-code-create-column.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-phone-calling-code-migrate-data.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-record-position-backfill.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-upgrade-version.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-35/0-35-view-group-no-value-backfill.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-update-inactive-workspace-status.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-40/0-40-upgrade-version.module.ts
  packages/twenty-server/src/engine/core-modules/user/user.entity.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
Labels: -PR: awaiting review

#9619 Improve workflow arrows' design
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCustomMarkers.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/EdgeRoundedArrowMarkerId.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeDefaultConfiguration.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/addCreateStepNodes.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
Labels: -PR: awaiting review

#9612 [Outlook integration] part 2 : GetMessages
  packages/twenty-server/src/modules/connected-account/email-alias-manager/services/email-alias-manager.service.ts
  packages/twenty-server/src/modules/connected-account/refresh-access-token-manager/services/refresh-access-token.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/messaging-microsoft-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/mocks/microsoft-api-examples.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-fetch-by-batch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.interface.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-handle-error.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-messages.service.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
  packages/twenty-website/src/content/developers/self-hosting/troubleshooting.mdx
Labels: -PR: awaiting author

#9630 Fix delete workspace-member avatar
  packages/twenty-front/src/modules/settings/profile/components/ProfilePictureUploader.tsx
  packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx
Labels: -PR: awaiting review

#9632 Ensure users can set the empty value for the FormPhoneFieldInput
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormCountryCodeSelectInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormPhoneFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormPhoneFieldInput.stories.tsx
Labels: -PR: awaiting CI

#9598 77 create new record action and remove old behavior
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultActionsConfigV2.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/hooks/useCreateNewTableRecordNoSelectionRecordAction.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/types/NoSelectionRecordActionsKey.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/types/SingleRecordActionsKey.ts
  packages/twenty-front/src/modules/action-menu/components/RecordIndexActionMenuButtons.tsx
  packages/twenty-front/src/modules/action-menu/components/RightDrawerActionMenuDropdown.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageHeader.tsx
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexPageTableAddButtonNoGroup.tsx
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerRecord.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateNoGroupNoRecordAtAll.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateNoRecordFoundForFilter.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useCreateNewTableRecords.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSectionAddNew.tsx
  packages/twenty-front/src/modules/object-record/utils/getRecordIndexIdFromObjectNamePlural.ts
Labels: -PR: awaiting review

#9635 [CI] Always save cache agnostically of the actions/restore cache-hit output
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
Labels: -PR: wip, -PR: awaiting author

#9572 fix(auth): handle missing invitation during sign-up
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/signUp.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/sso-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/sign-up.input.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/sign-in-up.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/social-sso.service.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/google.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/microsoft.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/types/signInUp.type.ts
  packages/twenty-server/src/engine/core-modules/domain-manager/service/domain-manager.service.ts
  packages/twenty-server/src/engine/core-modules/workspace/types/workspace.type.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.validate.ts
Labels: -PR: awaiting review

#9638 Make calendar event details readonly
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
Labels: -PR: awaiting review

#9613 [CI] Refactor yarn-install composite action
  .github/workflows/actions/yarn-install/action.yaml
Labels: -PR: awaiting review

#9629 Fix race condition on stripe subscription
  packages/twenty-front/src/hooks/__tests__/usePageChangeEffectNavigateLocation.test.ts
  packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts
  packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx
Labels: -PR: awaiting author

#9644 Aggregate queries - Fix empty / not empty operations on composite fields and array fields
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-aggregate.helper.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/constants/fieldMetadataTypesToTextColumnType.ts
  packages/twenty-server/src/engine/twenty-orm/utils/get-subfields-for-aggregate-operation.util.ts
Labels: -PR: awaiting author, -PR: awaiting review

#9631 Outlook integration
  packages/twenty-server/src/database/typeorm-seeds/workspace/message-channels.ts
  packages/twenty-server/src/engine/core-modules/auth/services/microsoft-apis.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/exceptions/message-import-driver.exception.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/services/gmail-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/message-import-exception-handler.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
  packages/twenty-ui/src/display/icon/assets/microsoft-outlook.svg
  packages/twenty-ui/src/display/icon/components/IconMicrosoftOutlook.tsx
  packages/twenty-ui/src/display/index.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: wip, -PR: awaiting author

#9661 fix: record group chevron alignment
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-section/components/RecordTableRecordGroupSection.tsx
Labels: -PR: awaiting review

#9664 [CI][NITPICK] `.yml` to `yaml` github workflows
  .github/workflows/actions/restore-cache/action.yaml
  .github/workflows/actions/save-cache/action.yaml
  .github/workflows/ci-e2e.yaml
Labels: -PR: awaiting review

#9637 bugfix: fix navigation between onboarding screens
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useBuildWorkspaceUrl.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts
  packages/twenty-front/src/modules/onboarding/hooks/useSetNextOnboardingStatus.ts
  packages/twenty-front/src/pages/onboarding/CreateWorkspace.tsx
Labels: -PR: awaiting review

#9670 [CI][NITPICK]: Rename `prerequisites` jobs to `changed-files-check`
  .github/workflows/ci-chrome-extension.yaml
  .github/workflows/ci-e2e.yaml
  .github/workflows/ci-front.yaml
  .github/workflows/ci-server.yaml
  .github/workflows/ci-shared.yaml
  .github/workflows/ci-test-docker-compose.yaml
  .github/workflows/ci-website.yaml
Labels: -PR: awaiting review

#9695 Upgrade to 0.40 guide
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting review

#9647 Add viewId to recordIndexId
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/__stories__/AppRouter.stories.tsx
  packages/twenty-front/src/modules/app/components/AppRouterProviders.tsx
  packages/twenty-front/src/modules/context-store/components/ContextStoreViewIdEffect.tsx
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
Labels: -PR: awaiting author

#9672 [CI] `ci-server` reorder `twenty-shared` build after cache restoration
  .github/workflows/ci-server.yaml
Labels: -PR: awaiting review

#9696 [Microsoft Outlook] fix + error handling
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-handle-error.service.ts
Labels: scope: backend, -PR: awaiting review, prio: med

#9689 Serverless function timeout concerns
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/graphql/fragments/serverlessFunctionFragment.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1737047131108-addTimeoutSecondsColumnToServerless.ts
  packages/twenty-server/src/engine/core-modules/serverless/drivers/lambda.driver.ts
  packages/twenty-server/src/engine/core-modules/serverless/drivers/local.driver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/create-serverless-function.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/serverless-function.dto.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/dtos/update-serverless-function.input.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.entity.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
Labels: -PR: awaiting author

#9727 Create many steps in a row
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEffect.tsx
Labels: -PR: awaiting review, -PR: awaiting CI

#9713 Workflow e2e tests – 1st batch
  .github/workflows/ci-e2e.yaml
  packages/twenty-e2e-testing/.env.example
  packages/twenty-e2e-testing/config/customreporter.ts
  packages/twenty-e2e-testing/drivers/env_variables.ts
  packages/twenty-e2e-testing/drivers/shell_driver.ts
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/lib/pom/loginPage.ts
  packages/twenty-e2e-testing/lib/requests/backend.ts
  packages/twenty-e2e-testing/lib/requests/create-workflow.ts
  packages/twenty-e2e-testing/lib/requests/delete-workflow.ts
  packages/twenty-e2e-testing/lib/requests/destroy-workflow.ts
  packages/twenty-e2e-testing/lib/utils/getAuthToken.ts
  packages/twenty-e2e-testing/playwright.config.ts
  packages/twenty-e2e-testing/project.json
  packages/twenty-e2e-testing/tests/authentication/signup_invite_email.e2e-spec.ts
  packages/twenty-e2e-testing/tests/authentication/signup_invite_email.spec.ts
  packages/twenty-e2e-testing/tests/demo/demo_basic.spec.ts
  packages/twenty-e2e-testing/tests/login.setup.ts
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-e2e-testing/tests/workflow-visualizer.spec.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
Labels: -PR: awaiting review, run-e2e

#9739 adding the microsoft publisher domain
  packages/twenty-website/public/.well-known/microsoft-identity-association.json
Labels: scope: front, size: short

#9741 fix: soft delete user when removing last userWorkspace
  packages/twenty-server/src/engine/core-modules/workspace/services/workspace.service.ts
Labels: -PR: awaiting review

#9747 Workflow E2E tests – batch 2
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/lib/types/workflows.ts
  packages/twenty-e2e-testing/tests/workflow-visualizer.spec.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
Labels: -PR: awaiting review, run-e2e

#9766 Fix API key not displayed
  packages/twenty-front/src/hooks/useCleanRecoilState.ts
  packages/twenty-front/src/locales/de.po
  packages/twenty-front/src/locales/en.po
  packages/twenty-front/src/locales/es.po
  packages/twenty-front/src/locales/fr.po
  packages/twenty-front/src/locales/generated/de.ts
  packages/twenty-front/src/locales/generated/en.ts
  packages/twenty-front/src/locales/generated/es.ts
  packages/twenty-front/src/locales/generated/fr.ts
  packages/twenty-front/src/locales/generated/it.ts
  packages/twenty-front/src/locales/generated/pseudo-en.ts
  packages/twenty-front/src/locales/generated/pt.ts
  packages/twenty-front/src/locales/generated/zh-Hans.ts
  packages/twenty-front/src/locales/generated/zh-Hant.ts
  packages/twenty-front/src/locales/it.po
  packages/twenty-front/src/locales/pseudo-en.po
  packages/twenty-front/src/locales/pt.po
  packages/twenty-front/src/locales/zh-Hans.po
  packages/twenty-front/src/locales/zh-Hant.po
  packages/twenty-front/src/modules/activities/states/activityTitleHasBeenSetFamilyState.ts
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/settings/developers/states/apiKeyTokenFamilyState.ts
  packages/twenty-front/src/modules/settings/developers/states/generatedApiKeyTokenState.ts
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeyDetail.tsx
  packages/twenty-front/src/pages/settings/developers/api-keys/SettingsDevelopersApiKeysNew.tsx
Labels: -PR: awaiting author, -PR: ready to merge

#9667 Lab
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/client-config/components/ClientConfigProviderEffect.tsx
  packages/twenty-front/src/modules/client-config/graphql/queries/getClientConfig.ts
  packages/twenty-front/src/modules/client-config/states/labPublicFeatureFlagsState.ts
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentToggle.tsx
  packages/twenty-front/src/modules/settings/lab/components/SettingsLabContent.tsx
  packages/twenty-front/src/modules/settings/lab/graphql/mutations/updateLabPublicFeatureFlag.ts
  packages/twenty-front/src/modules/settings/lab/hooks/useLabPublicFeatureFlags.ts
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/lab/SettingsLab.tsx
  packages/twenty-front/src/testing/mock-data/config.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.entity.ts
  packages/twenty-server/src/engine/core-modules/client-config/client-config.resolver.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/constants/public-feature-flag.const.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.exception.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/validates/feature-flag.validate.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/validates/is-public-feature-flag.validate.spec.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/validates/is-public-feature-flag.validate.ts
  packages/twenty-server/src/engine/core-modules/lab/dtos/update-lab-public-feature-flag.input.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.module.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.resolver.ts
  packages/twenty-server/src/engine/core-modules/lab/services/lab.service.ts
  packages/twenty-server/src/engine/core-modules/lab/utils/is-public-feature-flag.util.spec.ts
  packages/twenty-server/src/engine/core-modules/lab/utils/is-public-feature-flag.util.ts
  packages/twenty-server/src/engine/twenty-orm/decorators/workspace-gate.decorator.ts
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-website/public/images/lab/is-workflow-enabled.png
Labels: -PR: awaiting review

#9657 Document Google OAuth scopes required
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting author

#9767 fix: handle billingSubscriptions gql field if billing is disabled
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting review

#9764 fix(recaptcha|sso): recaptcha not generated issue
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeFormEffect.tsx
  packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCard.tsx
Labels: -PR: awaiting author

#9776 Align the workflow visualizer's nodes on the left
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getOrganizedDiagram.ts
Labels: -PR: awaiting CI, run-e2e, -PR: ready to merge

#9785 Seed workflow views and favorites in upgrade to 0.41
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-seed-workflow-views.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-upgrade-version.module.ts
  packages/twenty-server/src/modules/workflow/common/commands/seed-workflow-views.command.ts
  packages/twenty-server/src/modules/workflow/common/commands/workflow-command.module.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.module.ts
Labels: run-e2e

#9714 Open showpage on workflow creation
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-front/src/modules/favorites/components/FavoritesFolders.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/ObjectRecordShowPageBreadcrumb.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/useCreateNewTableRecords.ts
  packages/twenty-front/src/modules/object-record/states/isUpdatingRecordEditableName.ts
  packages/twenty-front/src/modules/object-record/utils/shouldRedirectToShowPageOnCreation.ts
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/ui/input/components/__stories__/TextInputV2.stories.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/PageHeader.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/EditableBreadcrumbItem.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/__stories__/EditableBreadcrumbItem.stories.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/hooks/useOpenEditableBreadCrumbItem.ts
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/types/EditableBreadcrumbItemHotkeyScope.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerInput.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerItemInput.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPageHeader.tsx
Labels: -PR: awaiting author, run-e2e

#9762 [BUG] Record settings not saved
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSignInWithGoogle.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSignInWithMicrosoft.test.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useCreateOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useDeleteOneObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFilteredObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/types/ObjectMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/__tests__/isLabelIdentifierField.test.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/__tests__/objectMetadataItemSchema.test.ts
  packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useAggregateRecordsQuery.test.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/__tests__/buildRecordGqlFieldsAggregateForView.test.ts
  packages/twenty-front/src/modules/object-record/relation-picker/hooks/__tests__/useLimitPerMetadataItem.test.tsx
  packages/twenty-front/src/modules/object-record/utils/__tests__/generateAggregateQuery.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/object-details/components/tabs/ObjectSettings.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectSettingsFormCard.tsx
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts
Labels: -PR: awaiting author

#9770 [MISC] Twenty-emails as package
  packages/twenty-server/tsconfig.json
Labels: -PR: awaiting review, run-e2e

#9793 feat: add targetFieldMetadataId and migration script for relations
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-upgrade-version.command.ts
  packages/twenty-server/src/database/commands/upgrade-version/0-41/0-41-upgrade-version.module.ts
  packages/twenty-server/src/database/typeorm/metadata/migrations/1737561084251-addRelationTargetFieldAndObjectToFieldMetadata.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.entity.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/relation-on-delete-action.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/relation-type.interface.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.entity.ts
Labels: -PR: awaiting review

#9652 Refactored table filters to consume new currentRecordFilters component state
  packages/twenty-front/src/modules/action-menu/components/__stories__/RecordIndexActionMenuBar.stories.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContainer.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/favorites/hooks/useDeleteFavoriteFolder.ts
  packages/twenty-front/src/modules/favorites/hooks/usePrefetchedFavoritesData.ts
  packages/twenty-front/src/modules/favorites/hooks/usePrefetchedFavoritesFoldersData.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/__stories__/MultipleFiltersDropdownButton.stories.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/states/availableFilterDefinitionsComponentState.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/__stories__/ObjectOptionsDropdownContent.stories.tsx
  packages/twenty-front/src/modules/object-record/record-filter/hooks/__tests__/useRemoveRecordFilter.test.tsx
  packages/twenty-front/src/modules/object-record/record-filter/hooks/__tests__/useUpsertRecordFilter.test.tsx
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useApplyRecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useRemoveRecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useUpsertRecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/states/context/RecordFiltersComponentInstanceContext.ts
  packages/twenty-front/src/modules/object-record/record-filter/states/currentRecordFiltersComponentState.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/isMatchingArrayFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useFindManyRecordIndexTableParams.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleColumnFilter.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleTrashColumnFilter.ts
  packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerRecord.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateSoftDelete.tsx
  packages/twenty-front/src/modules/prefetch/components/PrefetchRunQueriesEffect.tsx
  packages/twenty-front/src/modules/prefetch/hooks/internal/useUpsertRecordsInCacheForPrefetchKey.ts
  packages/twenty-front/src/modules/sign-in-background-mock/components/SignInBackgroundMockContainer.tsx
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
  packages/twenty-front/src/modules/views/components/QueryParamsFiltersEffect.tsx
  packages/twenty-front/src/modules/views/components/VariantFilterChip.tsx
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarDetails.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterEffect.tsx
  packages/twenty-front/src/modules/views/components/ViewBarRecordFilterEffect.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyCurrentViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useApplyViewFiltersToCurrentRecordFilters.test.tsx
  packages/twenty-front/src/modules/views/hooks/useApplyCurrentViewFiltersToCurrentRecordFilters.ts
  packages/twenty-front/src/modules/views/hooks/useApplyViewFiltersToCurrentRecordFilters.ts
  packages/twenty-front/src/pages/object-record/RecordIndexPage.tsx
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
  packages/twenty-front/src/testing/decorators/PageDecorator.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksAndContextStoreWrapper.tsx
  packages/twenty-front/src/testing/jest/getJestMetadataAndApolloMocksWrapper.tsx
Labels: -PR: awaiting author

#9801 Microsoft-multi-tenant
  packages/twenty-server/.env.example
  packages/twenty-server/src/engine/core-modules/auth/auth.exception.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/microsoft-apis-oauth-common.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/strategies/microsoft.auth.strategy.ts
  packages/twenty-server/src/engine/core-modules/auth/utils/get-microsoft-apis-oauth-scopes.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/modules/connected-account/oauth2-client-manager/drivers/microsoft/microsoft-oauth2-client-manager.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/utils/filter-out-contacts-from-company-or-workspace.util.ts
  packages/twenty-server/src/utils/is-work-email.ts
  packages/twenty-website/src/content/developers/self-hosting/setup.mdx
Labels: -PR: awaiting author

#9812 isMicrosoftAuthEnabled = true
  packages/twenty-server/src/database/typeorm/core/migrations/common/1737630672873-workspace-entity-default-microsoft-auth-enabled.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.entity.ts
Labels: -PR: awaiting review

#9809 251 create top bar chips inside the command menu
  packages/twenty-front/src/modules/activities/calendar/right-drawer/hooks/useOpenCalendarEventRightDrawer.ts
  packages/twenty-front/src/modules/activities/copilot/right-drawer/hooks/useOpenCopilotRightDrawer.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/__tests__/useOpenEmailThreadRightDrawer.test.ts
  packages/twenty-front/src/modules/activities/emails/right-drawer/hooks/useOpenEmailThreadRightDrawer.ts
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChipAvatars.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenuContextChip.stories.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenuContextRecordChip.stories.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/states/commandMenuPageTitle.ts
  packages/twenty-front/src/modules/ui/layout/right-drawer/hooks/useRightDrawer.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonlyEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useStartNodeCreation.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowNodeIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/__tests__/useCreateStep.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/RightDrawerWorkflowSelectTriggerTypeContent.tsx
Labels: -PR: awaiting review

#9810 Improve the design of workflow nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditable.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeEditableContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramCreateStepNode.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramEmptyTrigger.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeBorderWidth.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeHandleHeightPx.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeHandleWidthPx.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeIconLeftMargin.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeIconWidth.ts
  packages/twenty-ui/src/testing/decorators/CatalogDecorator.tsx
Labels: -PR: awaiting author, run-e2e

#9719 bugfix: escape destroyed objects on workers
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/event-emitter/types/object-record-event.event.ts
  packages/twenty-server/src/engine/core-modules/event-emitter/types/object-record-non-destructive-event.ts
  packages/twenty-server/src/engine/core-modules/event-emitter/types/object-record-restore.event.ts
  packages/twenty-server/src/engine/core-modules/event-emitter/types/object-record-update.event.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/listeners/message-participant-person.listener.ts
  packages/twenty-server/src/modules/timeline/jobs/create-audit-log-from-internal-event.ts
  packages/twenty-server/src/modules/timeline/jobs/upsert-timeline-activity-from-internal-event.job.ts
  packages/twenty-server/src/modules/timeline/services/timeline-activity.service.ts
  packages/twenty-server/src/modules/webhook/jobs/call-webhook-jobs.job.ts
Labels: -PR: awaiting author

#9753 fix: scrolling inside the table with scrollbar
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: -PR: awaiting review

#9818 fix: board hide button not working
  packages/twenty-front/src/modules/object-record/record-group/hooks/useRecordGroupActions.ts
Labels: -PR: awaiting CI

#9820 Normalize the spacing between nodes
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
Labels: -PR: awaiting review

#9823 fixed ellipsis for calendar events
  packages/twenty-front/src/modules/activities/calendar/components/CalendarEventRow.tsx
Labels: -PR: awaiting author

#9794 feat: new relation resolver
  packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.interface.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.module.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/dtos/relation.dto.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.exception.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata.interface.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/relation/field-metadata-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/utils/field-metadata-graphql-api-exception-handler.util.ts
  packages/twenty-server/src/engine/metadata-modules/utils/clean-object-metadata.util.ts
Labels: -PR: awaiting review

#9825 Fix missing events during account connection
  packages/twenty-server/src/engine/core-modules/auth/auth.module.ts
  packages/twenty-server/src/engine/core-modules/auth/services/google-apis.service.ts
  packages/twenty-server/src/engine/core-modules/auth/services/microsoft-apis.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/user.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/listeners/calendar-event-participant.listener.ts
  packages/twenty-server/src/modules/connected-account/query-hooks/connected-account-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-many.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-create-one.post-query.hook.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
Labels: -PR: awaiting author

#9808 feat: add clean suspended workspaces command
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/clean-suspended-workspaces.cron.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/constants/user-workspace-deletion-warning-sent-key.constant.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.cron.pattern.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/jobs/clean-workspace-deletion-warning-user-vars.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/workspace-cleaner.module.ts
Labels: -PR: awaiting review

#9814 Fix icon matching + small other fixes on workflows
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasEditableEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasReadonlyEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramEmptyTrigger.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/getWorkflowVersionDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowNodeIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowNodeIconKey.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepBody.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/RightDrawerWorkflowSelectActionContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormCreateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormDeleteRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormSendEmail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormServerlessFunction.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormUpdateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/OtherActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/RecordActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/RightDrawerWorkflowSelectTriggerTypeContent.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerDatabaseEventForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerManualForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/constants/DatabaseTriggerDefaultLabel.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/constants/DatabaseTriggerEvents.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/constants/DatabaseTriggerTypes.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/constants/OtherTriggerTypes.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/__tests__/getTriggerDefaultDefinition.test.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerDefaultDefinition.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerLabel.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/getTriggerStepName.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/utils/generate-fake-object-record-event.ts
Labels: -PR: awaiting author, run-e2e

#9781 Improve Docker-Compose Install Experience
  .github/workflows/ci-test-docker-compose.yaml
  packages/twenty-docker/.env.example
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/scripts/install.sh
  packages/twenty-website/src/content/developers/self-hosting/docker-compose.mdx
Labels: -PR: awaiting author

#9815 Refactor `triggerUpdateRelationsOptimisticEffect` to compute relationship from Metadatas
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRelationsOptimisticEffect.ts
  packages/twenty-front/src/modules/object-record/cache/utils/__tests__/isObjectRecordConnection.test.ts
  packages/twenty-front/src/modules/object-record/cache/utils/isObjectRecordConnection.ts
Labels: -PR: awaiting review

#9838 [MISC] Twenty-shared build `declaration` and `declarationMap` tsconfig
  packages/twenty-shared/tsconfig.lib.json
Labels: -PR: awaiting review

#9822 update subscription interval and quantity for hybrid susbscription
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/jobs/update-subscription-quantity.job.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription.service.ts
Labels: -PR: ready to merge

#9634 Feat/2fa
  packages/twenty-server/package.json
  packages/twenty-server/src/database/typeorm/core/migrations/common/1737033794408-two-factor-method.ts
  packages/twenty-server/src/database/typeorm/typeorm.service.ts
  packages/twenty-server/src/engine/core-modules/two-factor-method/two-factor-method.entity.ts
  packages/twenty-server/src/engine/core-modules/two-factor-method/two-factor-method.module.ts
  packages/twenty-server/src/engine/core-modules/two-factor-method/two-factor-method.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.entity.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.module.ts
  yarn.lock
Labels: -PR: wip, -PR: awaiting author

#9834 add new emails in suspended workspace cleaning job
  packages/twenty-emails/src/emails/clean-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/clean-suspended-workspace.email.tsx
  packages/twenty-emails/src/emails/delete-inactive-workspaces.email.tsx
  packages/twenty-emails/src/emails/warn-suspended-workspace.email.tsx
  packages/twenty-emails/src/index.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/clean-inactive-workspaces.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/start-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/stop-clean-inactive-workspaces.cron.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-inactive-workspace.cron.pattern.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-inactive-workspace.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/workspace-cleaner.module.ts
Labels: -PR: ready to merge

#9845 Add e2e tests for the Use as Draft feature
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
Labels: -PR: awaiting review, run-e2e

#9706 Rename Unintuitive Function Names in Authentication Flow
  packages/twenty-front/codegen.cjs
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEffect.tsx
  packages/twenty-front/src/modules/auth/graphql/mutations/challenge.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/getAuthTokensFromLoginToken.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/getLoginTokenFromCredentials.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/verify.ts
  packages/twenty-front/src/modules/auth/hooks/__mocks__/useAuth.ts
  packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonate.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/get-auth-tokens-from-login-token.input.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/get-login-token-from-credentials.input.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.spec.ts
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
  packages/twenty-server/src/engine/middlewares/graphql-hydrate-request-from-token.middleware.ts
  packages/twenty-server/test/integration/graphql/suites/auth.integration-spec.ts
Labels: -PR: awaiting author

#9833 Create a reusable Label component
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-ui/src/display/index.ts
  packages/twenty-ui/src/display/typography/components/Label.tsx
  packages/twenty-ui/src/display/typography/components/__stories__/Label.stories.tsx
Labels: -PR: awaiting review, -PR: awaiting CI, run-e2e

#9851 bug fix urgent
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
Labels: prio: CRITICAL 🚨

#9854 decoupling isMicrosoftAuthEnabled and IsMicrosoftSyncEnabled (which has no reason to be used here)
  packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsListEmptyStateCard.tsx
Labels: -PR: awaiting review, prio: high

#9863 Bug fix microsoft require approval
  packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis-oauth-request-code.auth.strategy.ts
Labels: scope: backend, prio: CRITICAL 🚨

#9868 updating SettingsAccountsListEmptyStateCard
  packages/twenty-front/src/locales/de.po
  packages/twenty-front/src/locales/en.po
  packages/twenty-front/src/locales/es.po
  packages/twenty-front/src/locales/fr.po
  packages/twenty-front/src/locales/it.po
  packages/twenty-front/src/locales/pseudo-en.po
  packages/twenty-front/src/locales/pt.po
  packages/twenty-front/src/locales/zh-Hans.po
  packages/twenty-front/src/locales/zh-Hant.po
  packages/twenty-front/src/modules/settings/accounts/components/SettingsNewAccountSection.tsx
Labels: size: short, -PR: awaiting CI, prio: low

#9832 feat(auth): centralize SSO error handling logic
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-apis-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/microsoft-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/controllers/sso-auth.controller.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/enterprise-features-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/google-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-exchange-code-for-token.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-request-code.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-oauth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-provider-enabled.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/oidc-auth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts
  packages/twenty-server/src/engine/core-modules/auth/services/social-sso.spec.ts
  packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts
  packages/twenty-server/src/engine/core-modules/sso/services/sso.service.ts
Labels: -PR: awaiting review

#9880 Fix Messaging sync upsert in messageChannel association
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
Labels: -PR: awaiting review

#9871 Fix the design of the Variable chip
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormBooleanFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormDateTimeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormMultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormNumberFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormSelectFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormUuidFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/VariableChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/VariableChipStandalone.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRawJsonFieldInput.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowSingleRecordFieldChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/components/WorkflowTextEditorVariableChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/variableTag.ts
Labels: -PR: awaiting review

#9890 fix link validation and matching during csv import
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSpreadSheetFieldValidationDefinitions.ts
Labels: -PR: awaiting review

#9891 adding the predicate in the UPSERT function
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-message.service.ts
Labels: prio: CRITICAL 🚨

#9862 Aggregates - Update Date label
  packages/twenty-front/src/locales/de.po
  packages/twenty-front/src/locales/en.po
  packages/twenty-front/src/locales/es.po
  packages/twenty-front/src/locales/fr.po
  packages/twenty-front/src/locales/generated/de.ts
  packages/twenty-front/src/locales/generated/en.ts
  packages/twenty-front/src/locales/generated/es.ts
  packages/twenty-front/src/locales/generated/fr.ts
  packages/twenty-front/src/locales/generated/it.ts
  packages/twenty-front/src/locales/generated/pseudo-en.ts
  packages/twenty-front/src/locales/generated/pt.ts
  packages/twenty-front/src/locales/generated/zh-Hans.ts
  packages/twenty-front/src/locales/generated/zh-Hant.ts
  packages/twenty-front/src/locales/it.po
  packages/twenty-front/src/locales/pseudo-en.po
  packages/twenty-front/src/locales/pt.po
  packages/twenty-front/src/locales/zh-Hans.po
  packages/twenty-front/src/locales/zh-Hant.po
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeaderAggregateDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterDropdownContent.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-footer/components/RecordTableColumnAggregateFooterMenuContent.tsx
Labels: -PR: awaiting author

#9889 Add history (undo/redo) to text variable editors
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRawJsonFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormTextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/hooks/useTextVariableEditor.ts
  yarn.lock
Labels: -PR: awaiting author

#9897 Disable variables for the country code in the form phone field
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormPhoneFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormPhoneFieldInput.stories.tsx
Labels: -PR: awaiting review

#9915 Improve command menu chip design
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextRecordChipAvatars.tsx
  packages/twenty-front/src/modules/command-menu/components/ResetContextToSelectionCommandButton.tsx
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenuContextChip.stories.tsx
  packages/twenty-front/src/modules/object-metadata/utils/getAvatarType.ts
Labels: -PR: awaiting review

#9917 Fix workflow edges color
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCustomMarkers.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/WorkflowVisualizerEdgeDefaultConfiguration.ts
Labels: -PR: awaiting review

#9918 Prevent all workflow node and edge deletions made through the UI
  packages/twenty-e2e-testing/tests/workflow-visualizer.spec.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
Labels: -PR: awaiting review

#9858 feat(auth): enhance SSO handling and workspace auth logic
  packages/twenty-front/src/modules/auth/hooks/__tests__/useAuth.test.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWithSSO.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeForm.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpWorkspaceScopeFormEffect.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSSO.test.ts
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/__tests__/useSSO.test.tsx
  packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSSO.ts
  packages/twenty-front/src/modules/workspace/components/WorkspaceProviderEffect.tsx
  packages/twenty-front/src/modules/workspace/states/workspaceAuthProvidersState.ts
  packages/twenty-server/src/engine/core-modules/workspace/utils/__tests__/get-auth-providers-by-workspace.util.spec.ts
  packages/twenty-server/src/engine/core-modules/workspace/utils/get-auth-providers-by-workspace.util.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
Labels: -PR: awaiting review

#9895 add command to run cleaning suspended workspaces job
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/commands/clean-suspended-workspaces.command.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/crons/clean-suspended-workspaces.job.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/exceptions/workspace-cleaner.exception.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/workspace-cleaner.module.ts
Labels: -PR: awaiting review

#9865 Add billing meter event service
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/constants/billing-execute-billed-function.constant.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-meter-event-names.ts
  packages/twenty-server/src/engine/core-modules/billing/listeners/billing-execute-billed-function.listener.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-usage.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-billing-meter-event.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/stripe.module.ts
  packages/twenty-server/src/engine/core-modules/billing/types/billing-usage-event.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts
Labels: -PR: awaiting review

#9902 Fix - Input box shadow, left icon focus and new size variant
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
  packages/twenty-front/src/modules/ui/navigation/bread-crumb/components/EditableBreadcrumbItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerInput.tsx
Labels: -PR: awaiting review

#9919 Fix E2E tests
  .github/workflows/ci-e2e.yaml
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
Labels: run-e2e

#9914 [BUG] Handle optimistic cache deletion operation
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/__tests__/useDeleteMultipleRecordsAction.test.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/multiple-records/hooks/useDeleteMultipleRecordsAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/hooks/useDestroySingleRecordAction.tsx
  packages/twenty-front/src/modules/activities/hooks/useOpenCreateActivityDrawer.ts
  packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetInlineCellEditMode.tsx
  packages/twenty-front/src/modules/apollo/optimistic-effect/utils/triggerUpdateRelationsOptimisticEffect.ts
  packages/twenty-front/src/modules/favorites/hooks/useCreateFavoriteFolder.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useDeleteManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useDeleteOneRecord.ts
  packages/twenty-front/src/modules/object-record/hooks/useUpdateOneRecord.ts
  packages/twenty-front/src/modules/object-record/utils/__tests__/computeOptimisticRecordFromInput.test.ts
  packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
Labels: -PR: wip, -PR: awaiting author

#9926 quick fix for microsoft : removing feature flag for microsoft
  packages/twenty-server/src/engine/core-modules/auth/guards/microsoft-apis-oauth-request-code.guard.ts
Labels: -PR: awaiting review, prio: high

#9933 creating the messagefolder entity
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-field-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-icons.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/constants/standard-object-ids.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/standard-objects/index.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-channel.workspace-entity.ts
  packages/twenty-server/src/modules/messaging/common/standard-objects/message-folder.workspace-entity.ts
Labels: -PR: awaiting review

#9940 Add settings roles page
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/locales/de.po
  packages/twenty-front/src/locales/en.po
  packages/twenty-front/src/locales/es.po
  packages/twenty-front/src/locales/fr.po
  packages/twenty-front/src/locales/generated/de.ts
  packages/twenty-front/src/locales/generated/en.ts
  packages/twenty-front/src/locales/generated/es.ts
  packages/twenty-front/src/locales/generated/fr.ts
  packages/twenty-front/src/locales/generated/it.ts
  packages/twenty-front/src/locales/generated/pseudo-en.ts
  packages/twenty-front/src/locales/generated/pt.ts
  packages/twenty-front/src/locales/generated/zh-Hans.ts
  packages/twenty-front/src/locales/generated/zh-Hant.ts
  packages/twenty-front/src/locales/generated/zh.ts
  packages/twenty-front/src/locales/it.po
  packages/twenty-front/src/locales/pseudo-en.po
  packages/twenty-front/src/locales/pt.po
  packages/twenty-front/src/locales/zh-Hans.po
  packages/twenty-front/src/locales/zh-Hant.po
  packages/twenty-front/src/locales/zh.po
  packages/twenty-front/src/modules/app/components/SettingsRoutes.tsx
  packages/twenty-front/src/modules/settings/components/SettingsNavigationDrawerItems.tsx
  packages/twenty-front/src/modules/types/SettingsPath.ts
  packages/twenty-front/src/pages/settings/roles/SettingsRoles.tsx
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting review

#9939 Disable the fields of all CRUD workflow actions on readonly mode
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormMultiSelectFieldInput.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepHeader.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/__stories__/WorkflowStepHeader.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormCreateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormDeleteRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFormUpdateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowSingleRecordFieldChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowSingleRecordPicker.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFormCreateRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFormDeleteRecord.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionFormUpdateRecord.stories.tsx
  packages/twenty-front/src/testing/decorators/WorkflowStepActionDrawerDecorator.tsx
  packages/twenty-front/src/testing/decorators/WorkflowStepDecorator.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/people.ts
  packages/twenty-front/src/testing/mock-data/workflow.ts
Labels: -PR: awaiting review, run-e2e

#9950 Make variable nodes undeletable in a readonly tiptap editor
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/VariableChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRawJsonFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormTextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/hooks/useTextVariableEditor.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/components/WorkflowTextEditorVariableChip.tsx
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/__tests__/getInitialEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/__tests__/initializeEditorContent.test.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/getInitialEditorContent.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/initializeEditorContent.ts
Labels: -PR: awaiting review, run-e2e
