Repository twentyhq/twenty, pull requests merged in 2025-04, with the labels that each got.

#11309 Option-menu-imporovements
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuViewName.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/hooks/useSetViewTypeFromLayoutOptionsMenu.ts
  packages/twenty-front/src/modules/views/types/ViewType.ts
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentCreateMode.tsx
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentEffect.tsx
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemSelect.tsx
Labels: -PR: awaiting review

#11285 Fix field metadata creation page
  packages/twenty-front/src/modules/settings/components/AdvancedSettingsContentWrapperWithDot.tsx
  packages/twenty-front/src/modules/settings/components/AdvancedSettingsWrapper.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx
  packages/twenty-front/src/modules/ui/input/components/InputErrorHelper.tsx
  packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx
Labels: -PR: awaiting review

#11319 update subscription with metered products at trial ending
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/enums/feature-flag-key.enum.ts
Labels: -PR: awaiting review

#11306 Fix object metadata collection not found
  packages/twenty-server/src/engine/core-modules/cache-storage/services/cache-storage.service.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/storage/__tests__/promise-memoizer.storage.spec.ts
  packages/twenty-server/src/engine/twenty-orm/storage/cache-manager.storage.ts
  packages/twenty-server/src/engine/twenty-orm/storage/promise-memoizer.storage.ts
  packages/twenty-server/src/engine/workspace-cache-storage/workspace-cache-storage.service.ts
Labels: -PR: awaiting review

#10663 Fix mobile table styling outside record table (#10407)
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/components/FieldContextProvider.tsx
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldContext.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useChipFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBody.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContext.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContextWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellSoftFocusMode.tsx
  packages/twenty-ui/src/display/avatar-chip/components/LinkAvatarChip.tsx
  packages/twenty-ui/src/display/chip/components/Chip.tsx
  packages/twenty-ui/src/display/chip/components/LinkChip.tsx
Labels: -PR: wip

#11288 Fix: Timeline responsiveness
  packages/twenty-front/src/modules/activities/timeline-activities/components/EventRow.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/activity/components/EventRowActivity.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/components/EventCard.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/components/EventRowDynamicComponent.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/main-object/components/EventRowMainObject.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/main-object/components/EventRowMainObjectUpdated.tsx
Labels: -PR: awaiting author

#11338 Auto-run migration script on docker entrypoint
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx
Labels: -PR: awaiting author

#11341 [FIX] `Out of memory` while running app localy
  .eslintrc.global.cjs
  .eslintrc.react.cjs
  packages/twenty-chrome-extension/.eslintrc.cjs
  packages/twenty-emails/.eslintrc.cjs
  packages/twenty-front/.eslintrc.cjs
  packages/twenty-front/package.json
  packages/twenty-front/project.json
  packages/twenty-front/setupTests.ts
  packages/twenty-front/tsconfig.spec.json
  packages/twenty-front/vite.config.ts
  packages/twenty-server/.eslintrc.cjs
  packages/twenty-shared/.eslintrc.cjs
  packages/twenty-ui/.eslintrc.cjs
  packages/twenty-website/.eslintrc.js
  yarn.lock
Labels: -PR: awaiting author

#11358 Set failed node's output as red
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-ui/src/json-visualizer/__stories__/JsonTree.stories.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonTree.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonValueNode.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeLabel.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeValue.tsx
  packages/twenty-ui/src/json-visualizer/contexts/JsonTreeContext.tsx
  packages/twenty-ui/src/json-visualizer/index.ts
  packages/twenty-ui/src/json-visualizer/types/GetJsonNodeHighlighting.ts
  packages/twenty-ui/src/json-visualizer/types/JsonNodeHighlighting.ts
Labels: -PR: awaiting review

#11350 Phone-onclickoutside
  packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/AddressFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/ArrayFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/BooleanFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/CurrencyFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateTimeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/EmailsFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/FullNameFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemBaseInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/MultiItemFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/NumberFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/PhonesFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RatingFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RelationToOneFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RichTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/TextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldInputEvent.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCell.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldInput.tsx
Labels: -PR: awaiting review

#11359 Introduce hooks to retrieve directly the registered actions without using actionMenuEntriesComponentState
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RegisterRecordActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RegisterRecordActionEffects.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/components/RecordAgnosticActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/components/RegisterAgnosticActionEffect.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/components/RunWorkflowRecordAgnosticActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/hooks/useRegisteredRecordActions.ts
  packages/twenty-front/src/modules/action-menu/hooks/useRegisteredRecordAgnosticActions.ts
Labels: -PR: awaiting review

#11373 JSON visualizer: Highlight the parent nodes of in-use nodes
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-ui/src/json-visualizer/__stories__/JsonTree.stories.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonArrayNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonNestedNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonNode.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonObjectNode.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonArrow.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeValue.tsx
  packages/twenty-ui/src/json-visualizer/types/JsonNodeHighlighting.ts
Labels: -PR: awaiting CI, -PR: ready to merge

#11330 add stripe alert listening and cap on subscriptionItems
  packages/twenty-front/src/modules/information-banner/components/InformationBannerWrapper.tsx
  packages/twenty-server/src/database/typeorm/core/migrations/billing/1743577268972-addHasReachedCurrentPeriodCapColumnInBillingSubscriptionItemTable.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-subscription-status.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-checkout.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-alert.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-invoice.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-subscription.service.ts
Labels: -PR: awaiting review

#11374 disable workflow execution if billing issue
  packages/twenty-server/src/engine/core-modules/billing/constants/billing-workflow-execution-error-message.constant.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-product-key.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing.service.ts
  packages/twenty-server/src/engine/core-modules/billing/types/billing-product-metadata.type.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/is-stripe-valid-product-metadata.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-executor.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/__tests__/workflow-executor.workspace-service.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
  packages/twenty-server/test/integration/billing/utils/create-mock-stripe-product-updated-data.util.ts
Labels: -PR: awaiting review

#11382 Copy JSON values on click
  packages/twenty-front/src/hooks/useCopyToClipboard.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/JsonDataIndicatorHealthStatus.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-ui/src/display/icon/components/TablerIcons.ts
  packages/twenty-ui/src/display/index.ts
  packages/twenty-ui/src/json-visualizer/__stories__/JsonTree.stories.tsx
  packages/twenty-ui/src/json-visualizer/components/JsonTree.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeValue.tsx
  packages/twenty-ui/src/json-visualizer/contexts/JsonTreeContext.tsx
Labels: -PR: awaiting review

#11388 Fix error when workflows aren't enabled
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RegisterRecordActionEffects.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RegisterWorkflowRecordActionEffects.tsx
  packages/twenty-front/src/modules/action-menu/hooks/useRegisteredRecordActions.ts
  packages/twenty-front/src/modules/action-menu/hooks/useShouldActionBeRegisteredParams.ts
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowWithCurrentVersion.ts
Labels: -PR: awaiting review

#11407 fix: Use namePlural instead of labelPlural for favorite view URLs
  packages/twenty-front/src/modules/favorites/utils/getObjectMetadataNamePluralFromViewId.ts
  packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts
Labels: -PR: awaiting review

#11389 add trial period ending banner + server logic
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/billing/graphql/endSubscriptionTrialPeriod.ts
  packages/twenty-front/src/modules/billing/hooks/useEndSubscriptionTrialPeriod.ts
  packages/twenty-front/src/modules/information-banner/components/InformationBannerWrapper.tsx
  packages/twenty-front/src/modules/information-banner/components/billing/InformationBannerEndTrialPeriod.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/workspace/hooks/useIsSomeMeteredProductCapReached.ts
  packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/billing-product.dto.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/outputs/billing-end-trial-period.output.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/outputs/billing-subscription-item.output.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription-item.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-product-key.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-usage-type.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-customer.service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/types/billing-product-metadata.type.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/__tests__/format-database-product-to-graphql-dto.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/utils/format-database-product-to-graphql-dto.util.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/utils/transform-stripe-subscription-event-to-database-subscription.util.ts
Labels: -PR: awaiting author

#11396 Switching plan overflows
  packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx
Labels: prio: med

#11424 Fix-messaging-calendar-issues
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-events-import.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
Labels: scope: backend

#11429 Fix permission check during onboarding
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.module.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
Labels: -PR: awaiting review

#10912 Share RICH_TEXT_V2 field value override between REST and GraphQL APIs
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/__tests__/query-runner-args.factory.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/factories/query-runner-args.factory.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-runner.module.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core-v2.service.ts
  packages/twenty-server/src/engine/api/rest/rest-api.module.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/record-transformer.module.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/services/record-input-transformer.service.ts
Labels: -PR: awaiting author

#11362 fetch latest version tag from docker hub
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminVersionContainer.tsx
  packages/twenty-front/src/modules/settings/admin-panel/components/SettingsAdminVersionDisplay.tsx
  packages/twenty-front/src/modules/settings/admin-panel/graphql/queries/getVersionInfo.ts
  packages/twenty-front/src/modules/settings/admin-panel/utils/checkTwentyVersionExists.ts
  packages/twenty-front/src/modules/settings/admin-panel/utils/fetchLatestTwentyRelease.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/__tests__/admin-panel.service.spec.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.resolver.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/admin-panel.service.ts
  packages/twenty-server/src/engine/core-modules/admin-panel/dtos/version-info.dto.ts
  packages/twenty-shared/src/constants/index.ts
Labels: -PR: awaiting review

#11456 remove default meter driver
  packages/twenty-server/src/engine/core-modules/environment/environment-variables.ts
  packages/twenty-server/src/instrument.ts
Labels: -PR: awaiting review

#11428 Use JSON visualizer for JSON fields
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useJsonField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/usePrecomputedJsonDraftValue.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
  packages/twenty-front/src/modules/serverless-functions/components/ServerlessFunctionExecutionResult.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/SettingsServerlessFunctionCodeEditor.tsx
  packages/twenty-front/src/modules/settings/serverless-functions/components/tabs/SettingsServerlessFunctionTestTab.tsx
  packages/twenty-ui/src/input/code-editor/components/CodeEditor.tsx
  packages/twenty-ui/src/input/code-editor/constants/BaseCodeEditorThemeId.ts
  packages/twenty-ui/src/input/code-editor/index.ts
  packages/twenty-ui/src/input/code-editor/theme/utils/getBaseCodeEditorTheme.ts
  packages/twenty-ui/src/input/index.ts
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeLabel.tsx
Labels: -PR: awaiting review

#11444 datasource TTL fix
  packages/twenty-server/src/engine/twenty-orm/storage/promise-memoizer.storage.ts
Labels: scope: backend

#11467 Messaging-unit-tests
  packages/twenty-server/src/modules/messaging/message-import-manager/jobs/messaging-message-list-fetch.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-full-message-list-fetch.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-messages-import.service.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-save-messages-and-enqueue-contact-creation.service.spec.ts
Labels: scope: backend

#11496 Fix PageHeaderToggleCommandMenuButton
  packages/twenty-front/src/modules/ui/layout/page-header/components/PageHeaderToggleCommandMenuButton.tsx
Labels: -PR: awaiting review

#11481 Create open side panel page action
  packages/twenty-front/src/modules/action-menu/actions/components/ActionOpenSidePanelPage.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/components/SearchRecordsRecordAgnosticAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/constants/RecordAgnosticActionsConfig.tsx
Labels: -PR: awaiting review

#11464 fix settings container vertical scroll position
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
Labels: run-chromatic, -PR: awaiting review

#11510 fix chromatic 1
  packages/twenty-front/src/pages/onboarding/__stories__/CreateWorkspace.stories.tsx
Labels: run-chromatic

#11345 wip: api playground fixes
  packages/twenty-front/src/modules/settings/playground/components/GraphQLPlayground.tsx
  packages/twenty-front/src/modules/settings/playground/components/RestPlayground.tsx
  packages/twenty-front/src/modules/ui/layout/fullscreen/components/FullScreenContainer.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/PageHeader.tsx
Labels: -PR: awaiting review

#11483 Remove onboarding flashes + close all dropdowns on CommandMenu close
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenu.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/onboarding/hooks/useSetNextOnboardingStatus.ts
  packages/twenty-front/src/modules/prefetch/components/PrefetchRunFavoriteQueriesEffect.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/__tests__/useShowAuthModal.test.tsx
  packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts
  packages/twenty-front/src/pages/onboarding/CreateProfile.tsx
  packages/twenty-front/src/pages/onboarding/CreateWorkspace.tsx
  packages/twenty-front/src/pages/onboarding/InviteTeam.tsx
  packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx
  packages/twenty-front/src/pages/onboarding/SyncEmails.tsx
Labels: -PR: awaiting review

#11530 Fix title input hotkey scope
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/hooks/useRecordTitleCell.tsx
  packages/twenty-front/src/modules/ui/input/types/TitleInputHotkeyScope.ts
Labels: -PR: awaiting review

#11520 Only display Flow for Workflow Runs and display Output tab for triggers
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuCloseAnimationCompleteCleanup.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getIsInputTabDisabled.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getIsOutputTabDisabled.ts
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts
  packages/twenty-front/src/modules/workflow/hooks/useStepsOutputSchema.ts
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunOutputVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/types/WorkflowDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowDiagramTriggerNode.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepOutputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepExecutionStatus.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerCronForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerDatabaseEventForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerManualForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerWebhookForm.tsx
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerHeaderType.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerIcon.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerIconColor.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/utils/getTriggerLabel.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/getTriggerStepName.ts
Labels: -PR: awaiting review

#11535 JSON Visualizer: ensure labels are 24px tall as all other elements
  packages/twenty-ui/src/json-visualizer/components/JsonNestedNode.tsx
  packages/twenty-ui/src/json-visualizer/components/internal/JsonNodeValue.tsx
Labels: -PR: awaiting review

#11497 Use transformer in workflows
  packages/twenty-server/src/modules/workflow/common/exceptions/workflow-common.exception.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-query-hook.module.ts
  packages/twenty-server/src/modules/workflow/common/workflow-common.module.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/create-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/find-records.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/record-crud-action.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/update-record.workflow-action.ts
Labels: -PR: awaiting author

#11541 create workflow subscription item addition command
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-add-workflow-subscription-item.command.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
Labels: -PR: awaiting review

#11544 Fix workflow with manual triggers and no selection not appearing in the command menu
  packages/twenty-front/src/modules/action-menu/actions/components/Action.tsx
  packages/twenty-front/src/modules/action-menu/actions/components/ActionLink.tsx
  packages/twenty-front/src/modules/action-menu/actions/components/ActionModal.tsx
  packages/twenty-front/src/modules/action-menu/actions/components/ActionOpenSidePanelPage.tsx
  packages/twenty-front/src/modules/action-menu/actions/display/components/ActionDisplay.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/run-workflow-actions/hooks/useRunWorkflowRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/components/SeeActiveVersionWorkflowSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/run-workflow-actions/hooks/useRunWorkflowRecordAgnosticActions.tsx
  packages/twenty-front/src/modules/action-menu/contexts/ActionMenuContextProvider.tsx
  packages/twenty-front/src/modules/action-menu/contexts/ActionMenuContextProviderWorkflowObjects.tsx
  packages/twenty-front/src/modules/action-menu/contexts/ActionMenuContextProviderWorkflowsEnabled.tsx
  packages/twenty-front/src/modules/workflow/hooks/useActiveWorkflowVersion.ts
  packages/twenty-front/src/modules/workflow/hooks/useActiveWorkflowVersionsWithManualTrigger.ts
Labels: -PR: awaiting review

#11556 Read feature flags from cache
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/settings/lab/graphql/mutations/updateLabPublicFeatureFlag.ts
  packages/twenty-front/src/modules/settings/lab/hooks/useLabPublicFeatureFlags.ts
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/dtos/feature-flag-dto.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/feature-flag.module.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/services/__tests__/feature-flag.service.spec.ts
  packages/twenty-server/src/engine/core-modules/feature-flag/services/feature-flag.service.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.module.ts
  packages/twenty-server/src/engine/core-modules/lab/lab.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace/workspace.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-feature-flag-map-cache.service.ts/workspace-feature-flag-map-cache.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-feature-flag-map-cache.service.ts/workspace-roles-feature-flag-map-cache.module.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-feature-flags-map-cache/workspace-feature-flags-map-cache.module.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-feature-flags-map-cache/workspace-feature-flags-map-cache.service.ts
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.module.ts
  packages/twenty-server/src/engine/utils/get-data-from-cache-with-recompute.util.ts
  packages/twenty-server/src/engine/workspace-cache-storage/workspace-cache-storage.service.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/workspace.integration-spec.ts
Labels: -PR: awaiting author

#11498 chip untitled modification
  packages/twenty-front/src/modules/command-menu/components/CommandMenuContextChip.tsx
  packages/twenty-front/src/modules/command-menu/components/CommandMenuTopBar.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx
  packages/twenty-ui/src/components/chip/Chip.tsx
  packages/twenty-ui/src/components/chip/__stories__/EntityChip.stories.tsx
  packages/twenty-ui/src/display/avatar/components/Avatar.tsx
Labels: -PR: awaiting review

#11565 Fix e2e tests
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/lib/pom/settingsPage.ts
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepHeader.tsx
Labels: -PR: awaiting review, run-e2e

#11474 Create FormRichTextField
  packages/twenty-front/src/modules/object-record/record-field/components/FormFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormRichTextV2FieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormRichTextV2FieldInput.stories.tsx
Labels: -PR: awaiting review

#11547 Create stories for action display components
  packages/twenty-front/src/modules/action-menu/actions/display/components/__stories__/ActionButton.stories.tsx
  packages/twenty-front/src/modules/action-menu/actions/display/components/__stories__/ActionComponent.stories.tsx
  packages/twenty-front/src/modules/action-menu/actions/display/components/__stories__/ActionDisplay.stories.tsx
  packages/twenty-front/src/modules/action-menu/actions/display/components/__stories__/ActionDropdownItem.stories.tsx
  packages/twenty-front/src/modules/action-menu/actions/display/components/__stories__/ActionListItem.stories.tsx
  packages/twenty-front/src/modules/action-menu/mock/action-menu-actions.mock.tsx
Labels: -PR: awaiting author

#11575 fix - remove isMeteredProductBillingEnabled
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-subscription.service.ts
Labels: -PR: awaiting CI

#11577 Fix e2e tests
  packages/twenty-e2e-testing/tests/workflow-creation.spec.ts
  packages/twenty-ui/src/display/tooltip/OverflowingTextWithTooltip.tsx
Labels: -PR: awaiting review, run-e2e

#11569 Remove recoil sync
  packages/twenty-front/package.json
  packages/twenty-front/src/modules/app/components/App.tsx
  packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx
  packages/twenty-front/src/modules/app/hooks/useInitializeQueryParamState.ts
  packages/twenty-front/src/modules/app/states/isQueryParamInitializedState.ts
  packages/twenty-front/src/modules/auth/components/AuthModal.tsx
  packages/twenty-front/src/modules/auth/components/VerifyEmailEffect.tsx
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/states/animateModalState.ts
  packages/twenty-front/src/modules/auth/states/billingCheckoutSessionState.ts
  packages/twenty-front/src/modules/domain-manager/hooks/useBuildSearchParamsFromUrlSyncedStates.ts
  packages/twenty-front/src/modules/settings/admin-panel/hooks/useImpersonationRedirect.ts
  packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx
  packages/twenty-front/src/modules/ui/layout/page/components/DefaultLayout.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownDefaultComponents.tsx
  packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx
  yarn.lock
Labels: -PR: awaiting review

#11576 Possiblity to reconnect on Failed unkown
  packages/twenty-server/src/modules/messaging/common/services/message-channel-sync-status.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-import-exception-handler.service.ts
Labels: -PR: awaiting review

#11553 Fix inline field height #11442
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
Labels: -PR: awaiting review

#11525 Fix a bug that overwrites currentRecordFilters when using URL filtered view
  packages/twenty-front/src/modules/views/components/QueryParamsFiltersEffect.tsx
  packages/twenty-front/src/modules/views/hooks/internal/useViewFromQueryParams.ts
Labels: -PR: awaiting author

#11585 Fix stories
  packages/twenty-front/src/loading/components/__stories__/PrefetchLoading.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RichTextFieldInput.stories.tsx
  packages/twenty-front/src/testing/decorators/PrefetchLoadingDecorator.tsx
Labels: -PR: awaiting review

#11584 removing RecordTableEmptyStateByGroupNoRecordAtAll
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyState.tsx
  packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateByGroupNoRecordAtAll.tsx
Labels: scope: front

#11578 create stripe customer before checking out + update on command
  packages/twenty-server/src/engine/core-modules/billing/billing.controller.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-add-workflow-subscription-item.command.ts
  packages/twenty-server/src/engine/core-modules/billing/enums/billing-webhook-events.enum.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-portal.workspace-service.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-checkout.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-customer.service.ts
Labels: -PR: awaiting review

#11400 Moved Select Options to External Files
  nx
  packages/twenty-docker/scripts/install.sh
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-front/scripts/inject-runtime-env.sh
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/AddressFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/NumberFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/RichTextFieldInput.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/TextFieldInput.stories.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/components/WorkerQueueMetricsSection.tsx
  packages/twenty-front/src/modules/settings/admin-panel/health-status/constants/WorkerQueueMetricsSelectOptions.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/components/SettingsDataModelFieldBooleanForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/boolean/constants/BooleanDataModelSelectOptions.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/SettingsDataModelFieldTextForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/components/text/constants/TextDataModelSelectOptions.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/components/SettingsDataModelFieldNumberForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/number/constants/NumberDataModelSelectOptions.ts
  packages/twenty-front/src/modules/settings/playground/components/PlaygroundSetupForm.tsx
  packages/twenty-front/src/modules/settings/playground/constants/PlaygroundSetupSelectOptions.ts
  packages/twenty-front/src/modules/views/view-picker/components/ViewPickerContentCreateMode.tsx
  packages/twenty-front/src/modules/views/view-picker/constants/ViewPickerTypeSelectOptions.ts
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/scripts/render-worker.sh
  packages/twenty-server/scripts/ssl-generation/script.sh
Labels: -PR: awaiting review

#11590 fix query param init before workspace redirection
  packages/twenty-front/src/modules/workspace/components/WorkspaceProviderEffect.tsx
Labels: -PR: awaiting review

#11603 more logging to look at calendar errors
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/services/google-calendar-get-events.service.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/services/calendar-fetch-events.service.ts
Labels: -PR: awaiting review

#11604 Fix execution permissions
  nx
  packages/twenty-docker/scripts/install.sh
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-front/scripts/inject-runtime-env.sh
  packages/twenty-server/scripts/render-run.sh
  packages/twenty-server/scripts/render-worker.sh
  packages/twenty-server/scripts/ssl-generation/script.sh
Labels: -PR: awaiting review

#11587 [permissions] Improve performances using a cache for userWorkspaces roles
  packages/twenty-server/src/engine/metadata-modules/object-permission/object-permission.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-permission/object-permission.service.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.module.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.module.ts
  packages/twenty-server/src/engine/metadata-modules/role/role.service.ts
  packages/twenty-server/src/engine/metadata-modules/user-role/user-role.module.ts
  packages/twenty-server/src/engine/metadata-modules/user-role/user-role.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-feature-flags-map-cache/workspace-feature-flags-map-cache.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/types/user-workspace-role-map.type.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache-storage.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.module.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-roles-permissions-cache/workspace-roles-permissions-cache.module.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-roles-permissions-cache/workspace-roles-permissions-cache.service.ts
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/exceptions/twenty-orm.exception.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.module.ts
  packages/twenty-server/src/engine/workspace-cache-storage/workspace-cache-storage.service.ts
Labels: -PR: awaiting review

#11608 Fix-inline-height
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/FullNameFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/NumberFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/TextFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleCellTextFieldDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/CurrencyDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/EllipsisDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/TextDisplay.tsx
  packages/twenty-front/vite.config.ts
Labels: -PR: awaiting review

#11609 Capitalize labels objectmetadata
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-checkout.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
Labels: -PR: awaiting author

#11614 better handling the function argument without touching it
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
Labels: -PR: awaiting author

#11581 Improve from in send email action
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/messaging-gmail-driver.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/gmail/providers/oauth2-client.provider.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/services/messaging-send-message.service.ts
Labels: -PR: ready to merge

#11616 fix: re-init subscription items when user ends his trial period
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
Labels: -PR: awaiting review

#11293 Ws poc
  package.json
  packages/twenty-front/codegen.cjs
  packages/twenty-front/jest.config.ts
  packages/twenty-front/nyc.config.cjs
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/apollo/services/apollo.factory.ts
  packages/twenty-front/src/modules/apollo/utils/getTokenPair.ts
  packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx
  packages/twenty-front/src/modules/subscription/components/ListenUpdatesEffect.tsx
  packages/twenty-front/src/modules/subscription/graphql/subscriptions/onDbEvent.ts
  packages/twenty-front/src/modules/subscription/hooks/useOnDbEvent.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/listeners/entity-events-to-db.listener.ts
  packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver-builder.module.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/message-queue/jobs.module.ts
  packages/twenty-server/src/engine/core-modules/message-queue/message-queue.constants.ts
  packages/twenty-server/src/engine/subscriptions/dtos/on-db-event.dto.ts
  packages/twenty-server/src/engine/subscriptions/dtos/on-db-event.input.ts
  packages/twenty-server/src/engine/subscriptions/subscriptions.job.ts
  packages/twenty-server/src/engine/subscriptions/subscriptions.module.ts
  packages/twenty-server/src/engine/subscriptions/subscriptions.resolver.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/exceptions/workflow-run.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.workspace-service.ts
  yarn.lock
Labels: -PR: ready to merge

#11630 fix(integration-tests): auth with multiworkspace and skip clickhouse …
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/test/integration/analytics/suites/clickhouse-event-registration.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/auth.integration-spec.ts
Labels: -PR: awaiting author

#11626 Set the page hotkey scope only once
  packages/twenty-front/src/hooks/useIsMatchingLocation.ts
Labels: -PR: awaiting review, run-e2e

#11634 Fix mismatching stripe subscription metadata plan/planKey
  packages/twenty-server/src/engine/core-modules/billing/utils/get-plan-key-from-subscription.util.ts
Labels: -PR: awaiting review

#11622 Fix select default value not in options
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata-validation.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/__tests__/before-update-one-field.hook.spec.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/hooks/before-update-one-field.hook.ts
  packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata.integration-spec.ts
Labels: -PR: awaiting review

#11635 Fix logs in integration tests for unhandled exceptions without removing logger
  packages/twenty-server/src/engine/core-modules/exception-handler/mocks/mock-unhandled-exception.filter.ts
  packages/twenty-server/test/integration/utils/create-app.ts
Labels: -PR: awaiting review

#11384 Date field format display
  packages/twenty-front/src/modules/apollo/utils/loggerLink.ts
  packages/twenty-front/src/modules/localization/utils/__tests__/formatDateISOStringToCustomUnicodeFormat.test.js
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToCustomUnicodeFormat.ts
  packages/twenty-front/src/modules/localization/utils/formatDateISOStringToDate.ts
  packages/twenty-front/src/modules/localization/utils/validateCustomDateFormat.ts
  packages/twenty-front/src/modules/object-metadata/types/FieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/utils/computeAggregateValueAndLabel.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/DateFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/DateTimeFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts
  packages/twenty-front/src/modules/object-record/record-field/types/guards/isDateFIeldCustomDisplayFormat.ts
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/__tests__/useExportFetchRecords.test.ts
  packages/twenty-front/src/modules/settings/components/SettingsOptions/SettingsOptionCardContentSelect.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/components/SettingsDataModelFieldDateForm.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/components/SettingsDataModelFieldDateSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/hooks/useDateSettingsFormInitialValues.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/utils/getDisplayFormatLabel.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/date/utils/getDisplayFormatSelectDescription.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateDisplay.tsx
  packages/twenty-front/src/modules/ui/field/display/components/DateTimeDisplay.tsx
  packages/twenty-front/src/testing/mock-data/generated/mock-metadata-query-result.ts
  packages/twenty-front/src/testing/mock-data/workflow-run.ts
  packages/twenty-front/src/testing/mock-data/workflow.ts
  packages/twenty-front/src/utils/string/__tests__/formatDateString.test.ts
  packages/twenty-front/src/utils/string/__tests__/formatDateTimeString.test.ts
  packages/twenty-front/src/utils/string/formatDateString.ts
  packages/twenty-front/src/utils/string/formatDateTimeString.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-52/0-52-upgrade-settings-field.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-52/0-52-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/interfaces/field-metadata-settings.interface.ts
  packages/twenty-server/src/engine/twenty-orm/base.workspace-entity.ts
  tools/eslint-rules/rules/no-hardcoded-colors.ts
Labels: -PR: awaiting review

#11645 Fix rest api integration tests
  packages/twenty-server/@types/jest.d.ts
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core-v2.service.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.ts
  packages/twenty-server/test/integration/constants/mock-person-ids.constants.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-authentication.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-create-one.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-delete.integration-spec.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-update.integration-spec.ts
  packages/twenty-server/test/integration/rest/utils/make-rest-api-request.util.ts
Labels: -PR: ready to merge

#11644 refacto clickoutside componentv2
  packages/twenty-front/src/modules/action-menu/actions/display/components/ActionButton.tsx
  packages/twenty-front/src/modules/captcha/hooks/useRequestFreshCaptchaToken.ts
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuContent.tsx
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownMenuViewName.tsx
  packages/twenty-front/src/modules/object-record/record-board/components/RecordBoard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/__stories__/RecordTable.stories.tsx
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTable.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/internal/useCloseRecordTableCellInGroup.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/internal/useCloseRecordTableCellNoGroup.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
  packages/twenty-front/src/modules/ui/input/editor/components/BlockEditor.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/__tests__/useClickOutsideListener.test.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useClickOustideListenerStates.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useClickOutsideListener.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerCallbacksComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerIsActivatedComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerIsMouseDownInsideComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/clickOutsideListenerMouseDownHappenedComponentState.ts
  packages/twenty-front/src/modules/ui/utilities/pointer-event/states/contexts/ClickOutsideListenerComponentInstanceContext.ts
  packages/twenty-front/src/testing/decorators/RecordTableDecorator.tsx
  tools/eslint-rules/jest.config.ts
  tools/eslint-rules/rules/no-hardcoded-colors.spec.ts
  tools/eslint-rules/rules/no-hardcoded-colors.ts
Labels: scope: front

#11656 Fix e2e tests
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
Labels: -PR: awaiting review, run-e2e

#11653 Update workflow statuses in real time
  packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRow.tsx
  packages/twenty-front/src/modules/subscription/components/ListenUpdatesEffect.tsx
  packages/twenty-front/src/modules/subscription/utils/getDefaultRecordFieldsToListen.util.ts
  packages/twenty-server/src/engine/subscriptions/subscriptions.job.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/__tests__/workflow-statuses-update.job.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/workflow-statuses-update.job.ts
  packages/twenty-server/src/modules/workflow/workflow-status/workflow-status.module.ts
Labels: -PR: awaiting review

#11654 838 design adjustments on table kanban and inline fields
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableTd.tsx
Labels: -PR: awaiting review

#11648 fix subscription item update
  packages/twenty-front/src/modules/billing/hooks/useGetWorkflowNodeExecutionUsage.ts
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-usage.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/__mocks__/stripe-subscription-updated-events.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/services/billing-webhook-subscription.service.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/utils/__tests__/get-deleted-stripe-subscription-item-ids-from-stripe-subscription-event.util.spec.ts
  packages/twenty-server/src/engine/core-modules/billing/webhooks/utils/get-deleted-stripe-subscription-item-ids-from-stripe-subscription-event.util.ts
Labels: -PR: awaiting review

#11650 Get all first depth fields in the table and the board
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/__tests__/generateDepthOneWithoutRelationsRecordGqlFields.test.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/generateDepthOneRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/graphql/utils/generateDepthOneWithoutRelationsRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useLazyLoadRecordIndexTable.test.tsx
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordBoardRecordGqlFields.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useRecordTableRecordGqlFields.ts
Labels: -PR: awaiting review, run-e2e

#11686 Fix inline cell interactions
  packages/twenty-front/src/modules/object-record/record-field/hooks/useOpenFieldInputEditMode.ts
  packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx
  packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx
  packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx
  packages/twenty-front/src/modules/ui/input/types/TitleInputHotkeyScope.ts
Labels: run-chromatic, -PR: awaiting review

#11694 Improve storybook stories
  packages/twenty-front/src/modules/activities/tasks/components/TaskList.tsx
  packages/twenty-front/src/modules/activities/tasks/components/__stories__/TaskGroups.stories.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/__stories__/EventCardMessage.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/SettingsAccountsBlocklistTableRow.stories.tsx
  packages/twenty-front/src/modules/settings/accounts/components/__stories__/mockedBlocklist.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/__stories__/WorkflowEditActionUpdateRecord.stories.tsx
  packages/twenty-front/src/testing/mock-data/tasks.ts
Labels: run-chromatic, -PR: awaiting review

#11702 Fix click outside dropdown content confirmation modal
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownContent.tsx
Labels: -PR: awaiting review

#11477 Permission checks on twentyORM global manager
  packages/twenty-server/@types/jest.d.ts
  packages/twenty-server/jest-integration.config.ts
  packages/twenty-server/src/database/commands/data-seed-dev-workspace.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-add-tasks-assigned-to-me-view.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/0-43/0-43-update-default-view-record-opening-on-workflow-objects.command.ts
  packages/twenty-server/src/database/typeorm-seeds/workspace/api-key.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations-v2.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/engine/api/rest/core/rest-api-core-v2.service.ts
  packages/twenty-server/src/engine/api/rest/rest-api.module.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/object-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.service.ts
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/entity.manager.ts
  packages/twenty-server/src/engine/twenty-orm/factories/scoped-workspace-context.factory.ts
  packages/twenty-server/src/engine/twenty-orm/factories/workspace-datasource.factory.ts
  packages/twenty-server/src/engine/twenty-orm/repository/permissions.util.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-query-builder.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-select-query-builder.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-update-query-builder.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace.repository.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm-global.manager.ts
  packages/twenty-server/src/engine/twenty-orm/twenty-orm.manager.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-event-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/crons/jobs/calendar-events-import.cron.job.ts
  packages/twenty-server/src/modules/connected-account/listeners/connected-account.listener.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company-and-contact.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company.service.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-contact.service.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-message-list-fetch.cron.job.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/crons/jobs/messaging-messages-import.cron.job.ts
  packages/twenty-server/src/modules/messaging/monitoring/crons/jobs/messaging-message-channel-sync-status-monitoring.cron.job.ts
  packages/twenty-server/src/modules/view/pre-hooks/view-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/mail-sender/send-email.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/database-event-trigger/listeners/database-event-trigger.listener.ts
  packages/twenty-server/test/integration/graphql/suites/object-records-permissions/update-one-object-records-permissions.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/make-graphql-api-request-with-api-key.util.ts
Labels: -PR: wip, -PR: awaiting author

#11698 update price on subscription - command
  packages/twenty-server/src/engine/core-modules/billing/billing.module.ts
  packages/twenty-server/src/engine/core-modules/billing/commands/billing-update-subscription-price.command.ts
  packages/twenty-server/src/engine/core-modules/billing/stripe/services/stripe-subscription-item.service.ts
Labels: -PR: awaiting review

#11708 Fix object model settings label synchronization
  packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectAboutForm.tsx
Labels: -PR: awaiting review

#11669 Workflow runs in side panel
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/lib/types/workflows.ts
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuCloseAnimationCompleteCleanup.ts
  packages/twenty-front/src/modules/command-menu/hooks/useOpenRecordInCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useWorkflowCommandMenu.ts
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStep.tsx
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowRunOpeningInCommandMenuSideEffects.ts
  packages/twenty-front/src/modules/workflow/hooks/useWorkflowRun.ts
  packages/twenty-front/src/modules/workflow/states/workflowRunIdState.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCanvasBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvas.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunDiagramCanvasEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizer.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowRunVisualizerEffect.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useHandleWorkflowRunDiagramCanvasInit.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/hooks/useSetInitialWorkflowRunRightDrawerTab.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/states/workflowDiagramStatusState.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/states/workflowRunStepToOpenByDefaultState.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/states/workflowSelectedNodeState.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/generateWorkflowRunDiagram.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/__tests__/selectWorkflowDiagramNode.test.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/generateWorkflowRunDiagram.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/selectWorkflowDiagramNode.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/constants/WorkflowRunStepSidePanelTabListComponentId.ts
Labels: -PR: awaiting review, run-e2e

#11713 Hide toggle isSyncLabelName for standardObject field edition
  packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx
Labels: -PR: awaiting review

#11715 Stop persisting JSON fields in workflow runs
  packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/RawJsonFieldInput.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/utils/isWorkflowRunJsonField.ts
  packages/twenty-front/src/modules/object-record/record-field/utils/isFieldValueReadOnly.ts
Labels: -PR: awaiting review

#11711 Refactor new relation sync
  packages/twenty-server/src/database/commands/upgrade-version-command/0-52/0-52-migrate-relations-to-field-metadata.command.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/access-token.service.ts
  packages/twenty-server/src/engine/metadata-modules/field-metadata/field-metadata.service.ts
  packages/twenty-server/src/engine/metadata-modules/object-metadata/services/object-metadata-field-relation.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/factories/relation-column-action.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-field-relation.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/services/workspace-sync-field-metadata-relation.service.ts
Labels: -PR: wip

#11737 Table hover and click outside fixes
  packages/twenty-front/src/modules/object-record/record-table/components/RecordTableBodyEffectsWrapper.tsx
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useLeaveTableFocus.ts
  packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useSetRecordTableData.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyDroppable.tsx
Labels: -PR: awaiting review, preview-app

#11745 fix relation fields preview in settings
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationToOneFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useChipFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useRelationFromManyFieldDisplay.ts
  packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/components/SettingsDataModelFieldPreview.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/__tests__/useFieldPreviewValue.test.tsx
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/usePreviewRecord.ts
  packages/twenty-ui/src/components/avatar-chip/AvatarChip.tsx
  packages/twenty-ui/src/components/avatar-chip/LinkAvatarChip.tsx
  packages/twenty-ui/src/components/avatar-chip/types/AvatarChipsCommonProps.type.ts
  packages/twenty-ui/src/components/chip/Chip.tsx
Labels: -PR: awaiting review

#11595 Twenty config core implementation
  packages/twenty-server/.env.example
  packages/twenty-server/package.json
  packages/twenty-server/src/database/typeorm/typeorm.module.ts
  packages/twenty-server/src/engine/core-modules/core-engine.module.ts
  packages/twenty-server/src/engine/core-modules/file/file-upload/file-upload.module.ts
  packages/twenty-server/src/engine/core-modules/file/file.module.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/cache/__tests__/config-cache.service.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/cache/config-cache.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/cache/interfaces/config-cache-entry.interface.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/constants/config-variables-instance-tokens.constants.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/constants/config-variables-refresh-cron-interval.constants.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/conversion/__tests__/config-value-converter.service.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/conversion/config-value-converter.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/decorators/cast-to-boolean.decorator.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/decorators/cast-to-string-array.decorator.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/decorators/config-variables-metadata.decorator.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/__tests__/database-config.driver.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/__tests__/environment-config.driver.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/database-config.driver.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/database-config.module.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/environment-config.driver.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/drivers/interfaces/database-config-driver.interface.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/enums/config-source.enum.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/storage/__tests__/config-storage.service.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/storage/config-storage.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/storage/interfaces/config-storage.interface.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/twenty-config.module.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/twenty-config.service.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/twenty-config.service.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/types/config-variable-options.type.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/types/config-variable-type.type.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/__tests__/apply-basic-validators.util.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/__tests__/config-transformers.util.spec.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/apply-basic-validators.util.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/config-transformers.util.ts
  packages/twenty-server/src/engine/core-modules/twenty-config/utils/is-env-only-config-var.util.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-message-list.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.dev.spec.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/drivers/microsoft/services/microsoft-get-messages.service.spec.ts
  yarn.lock
Labels: -PR: awaiting review, -PR: ready to merge, preview-app

#11772 Fix open record in menu
  packages/twenty-front/src/modules/object-record/object-options-dropdown/components/ObjectOptionsDropdownLayoutContent.tsx
Labels: -PR: awaiting review

#11792 Fix e2e tests
  packages/twenty-e2e-testing/lib/fixtures/blank-workflow.ts
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-e2e-testing/tests/workflow-use-as-draft.spec.ts
Labels: -PR: awaiting review, run-e2e

#11683 Start using next step ids
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/workflow/graphql/mutations/createWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/graphql/mutations/deleteWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/graphql/mutations/updateWorkflowRunStep.ts
  packages/twenty-front/src/modules/workflow/graphql/mutations/updateWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/hooks/useDeleteWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepInputDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateWorkflowVersionStep.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowPreviousSteps.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/__tests__/getWorkflowRunStepContext.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowPreviousStepId.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowPreviousSteps.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/utils/getWorkflowRunStepContext.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/hooks/useAvailableVariablesInWorkflowStep.ts
  packages/twenty-server/src/engine/core-modules/workflow/dtos/workflow-step.dto.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/exceptions/workflow-step-executor.exception.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/types/workflow-executor-input.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/code/code.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/form/form.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/mail-sender/send-email.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/create-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/delete-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/find-records.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/update-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/__tests__/workflow-executor.workspace-service.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
Labels: -PR: awaiting review, run-e2e

#11821 fix rich text focus
  packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx
Labels: -PR: awaiting review
