Repository twentyhq/twenty, pull requests merged in 2025-06, with the labels that each got.

#12407 Fix auth modal closing hotkey scopes
  packages/twenty-front/src/modules/auth/components/AuthModalMountEffect.tsx
Labels: -PR: awaiting review

#12410 Fix edge x position
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramBaseHandle.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramCreateStepNode.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramDefaultEdge.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeBase.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/CreateStepNodeWidth.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeIconLeftMargin.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/constants/NodeIconWidth.ts
Labels: -PR: awaiting review

#12412 Fix stories chromatic
  packages/twenty-front/src/modules/client-config/hooks/useClientConfig.ts
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateFieldInput.stories.tsx
  packages/twenty-front/src/pages/auth/__stories__/SignInUp.stories.tsx
  packages/twenty-front/src/pages/settings/roles/__stories__/SettingsRoles.stories.tsx
Labels: run-chromatic

#12403 Add tests on granular settings permissions
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/granular-settings-permissions.ts
Labels: -PR: awaiting review

#12415 [permissions] Override workspaceDatasource.createQueryBuilder
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations-v2.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/helpers/process-nested-relations.helper.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-create-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-delete-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-destroy-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-find-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-restore-one-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-many-resolver.service.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts
  packages/twenty-server/src/engine/api/rest/core/interfaces/rest-api-base.handler.ts
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-select-query-builder.ts
Labels: -PR: awaiting author, -PR: awaiting CI

#12416 Role page various fixes 2
  packages/twenty-front/src/modules/settings/roles/components/SettingsRolesQueryEffect.tsx
  packages/twenty-front/src/modules/settings/roles/components/SettingsRolesTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignment.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentConfirmationModalSubtitle.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/types/SettingsRoleAssignmentConfirmationModalSelectedWorkspaceMember.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/settings-permissions/components/SettingsRolePermissionsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRole.tsx
  packages/twenty-server/src/engine/metadata-modules/role/role.resolver.ts
Labels: -PR: awaiting review

#12442 Fix dropdown z index
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnToFieldSelect.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/SubMatchingSelectRowRightDropdown.tsx
  packages/twenty-front/src/modules/ui/layout/constants/RootStackingContextZIndices.ts
  packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/__stories__/Dropdown.stories.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/__stories__/ConfirmationModal.stories.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/__stories__/Modal.stories.tsx
Labels: -PR: awaiting review

#12392 feat: implement TS vector search filter
  packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemsAsFilterDefinitions.ts
  packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getInitialFilterValue.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useRemoveRecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/types/FilterableFieldType.ts
  packages/twenty-front/src/modules/object-record/record-filter/types/RecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/isMatchingTSVectorFilter.test.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/compute-record-gql-operation-filter/checkIfShouldComputeEmptinessFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/compute-record-gql-operation-filter/turnRecordFilterIntoGqlOperationFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/getRecordFilterOperands.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingTSVectorFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts
  packages/twenty-front/src/modules/object-record/record-table/utils/buildRecordInputFromFilter.ts
  packages/twenty-front/src/modules/object-record/utils/isSystemSearchVectorField.ts
  packages/twenty-front/src/modules/object-record/utils/sanitizeRecordInput.ts
  packages/twenty-front/src/modules/views/components/ViewBar.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdown.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownAdvancedFilterButton.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownBottomMenu.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownFieldSelectMenu.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownVectorSearchButton.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownVectorSearchInput.tsx
  packages/twenty-front/src/modules/views/components/ViewBarRecordFilterEffect.tsx
  packages/twenty-front/src/modules/views/constants/ViewBarFilterBottomMenuItemIds.ts
  packages/twenty-front/src/modules/views/constants/ViewFieldConstants.ts
  packages/twenty-front/src/modules/views/hooks/useApplyCurrentViewFiltersToCurrentRecordFilters.ts
  packages/twenty-front/src/modules/views/hooks/useApplyViewFiltersToCurrentRecordFilters.ts
  packages/twenty-front/src/modules/views/hooks/useMapViewFiltersToFilters.ts
  packages/twenty-front/src/modules/views/hooks/useOpenVectorSearchFilter.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromActiveFieldsOfViewOrDefaultView.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromView.ts
  packages/twenty-front/src/modules/views/hooks/useSetEditableFilterChipDropdownStates.ts
  packages/twenty-front/src/modules/views/hooks/useSetVectorSearchInputValueFromExistingFilter.ts
  packages/twenty-front/src/modules/views/hooks/useVectorSearchFieldInRecordIndexContextOrThrow.ts
  packages/twenty-front/src/modules/views/hooks/useVectorSearchFilterActions.ts
  packages/twenty-front/src/modules/views/hooks/useVectorSearchFilterState.ts
  packages/twenty-front/src/modules/views/states/vectorSearchInputComponentState.ts
  packages/twenty-front/src/modules/views/types/ViewFilterOperand.ts
  packages/twenty-front/src/modules/views/utils/getFilterableFieldsWithVectorSearch.ts
  packages/twenty-front/src/modules/views/utils/isVectorSearchFilter.ts
  packages/twenty-front/src/modules/views/utils/mapViewFiltersToFilters.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/utils/compute-where-condition-parts.ts
Labels: -PR: awaiting author

#12444 add field validation + add other subfields import
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/__tests__/buildRecordFromImportedStructuredRow.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSpreadSheetFieldValidationDefinitions.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/components/columns.tsx
Labels: -PR: awaiting review

#12390 fix(frontend): prevent command menu reopening when clicking the same field
  packages/twenty-front/src/modules/command-menu/components/CommandMenuOpenContainer.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useOpenRecordInCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-table/constants/RecordChipClickOutsideId.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx
  packages/twenty-front/src/modules/ui/utilities/pointer-event/hooks/useListenClickOutside.ts
Labels: -PR: awaiting author

#12453 Implemented dropdown menu section label in filter and sort
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterDropdownFieldSelectMenu.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterDropdownFieldSelectMenuItem.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterDropdownSubFieldSelectMenu.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterFieldSelectMenu.tsx
  packages/twenty-front/src/modules/object-record/object-sort-dropdown/components/ObjectSortDropdownButton.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuItemsContainer.tsx
  packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSectionLabel.tsx
  packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownFieldSelectMenu.tsx
Labels: -PR: awaiting review

#12459 Update billing page ctas
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/billing/components/SettingsBillingMonthlyCreditsSection.tsx
  packages/twenty-front/src/modules/billing/components/SettingsBillingSubscriptionInfo.tsx
  packages/twenty-front/src/modules/billing/components/SubscriptionInfoContainer.tsx
  packages/twenty-front/src/modules/billing/components/SubscriptionInfoRowContainer.tsx
  packages/twenty-front/src/modules/billing/graphql/mutations/checkoutSession.ts
  packages/twenty-front/src/modules/billing/graphql/mutations/endSubscriptionTrialPeriod.ts
  packages/twenty-front/src/modules/billing/graphql/mutations/switchSubscriptionToEnterprisePlan.ts
  packages/twenty-front/src/modules/billing/graphql/mutations/switchSubscriptionToYearlyInterval.ts
  packages/twenty-front/src/modules/billing/graphql/queries/billingBaseProductPrices.ts
  packages/twenty-front/src/modules/billing/graphql/queries/billingPortalSession.ts
  packages/twenty-front/src/modules/billing/graphql/queries/getMeteredProductsUsage.ts
  packages/twenty-front/src/modules/billing/utils/formatMonthlyPrices.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__tests__/useColumnDefinitionsFromFieldMetadata.test.ts
  packages/twenty-front/src/modules/onboarding/hooks/__tests__/useSetNextOnboardingStatus.test.ts
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/workspace/hooks/__tests__/useSubscriptionStatus.test.ts
  packages/twenty-front/src/pages/onboarding/__stories__/ChooseYourPlan.stories.tsx
  packages/twenty-front/src/pages/settings/SettingsBilling.tsx
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.exception.ts
  packages/twenty-server/src/engine/core-modules/billing/billing.resolver.ts
  packages/twenty-server/src/engine/core-modules/billing/dtos/outputs/billing-subscription-item.output.ts
  packages/twenty-server/src/engine/core-modules/billing/entities/billing-subscription.entity.ts
  packages/twenty-server/src/engine/core-modules/billing/filters/billing-api-exception.filter.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-plan.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-product.service.ts
  packages/twenty-server/src/engine/core-modules/billing/services/billing-subscription.service.ts
Labels: -PR: awaiting author

#12481 Add filters to search record action
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupChildren.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterGroupRow.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRecordFilterRow.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterRootRecordFilterGroup.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterValueFormCompositeFieldInput.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterValueFormInput.tsx
  packages/twenty-front/src/modules/object-record/advanced-filter/states/context/AdvancedFilterContext.ts
  packages/twenty-front/src/modules/object-record/record-filter-group/hooks/useRemoveRecordFilterGroup.ts
  packages/twenty-front/src/modules/object-record/record-filter-group/hooks/useUpsertRecordFilterGroup.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useRemoveRecordFilter.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useUpsertRecordFilter.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionFindRecords.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowFindRecordFilters.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowFindRecordFiltersEffect.tsx
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/find-records.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/types/workflow-record-crud-action-input.type.ts
Labels: -PR: awaiting review

#12461 fix: trigger onClickOutside when click escape for closing the model a…
  packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx
Labels: -PR: awaiting author

#10413 Website changes docs playground
  packages/twenty-website/public/images/docs/getting-started/api.png
  packages/twenty-website/public/images/docs/getting-started/webhooks.png
  packages/twenty-website/src/app/(public)/developers/graphql/core/page.tsx
  packages/twenty-website/src/app/(public)/developers/graphql/metadata/page.tsx
  packages/twenty-website/src/app/(public)/developers/rest-api/core/page.tsx
  packages/twenty-website/src/app/(public)/developers/rest-api/metadata/page.tsx
  packages/twenty-website/src/app/_components/playground/graphql-playground.tsx
  packages/twenty-website/src/app/_components/playground/playground.tsx
  packages/twenty-website/src/app/_components/playground/rest-api-wrapper.tsx
  packages/twenty-website/src/app/_components/playground/token-form.css
  packages/twenty-website/src/app/_components/playground/token-form.tsx
  packages/twenty-website/src/content/developers/api-and-webhooks/api.mdx
  packages/twenty-website/src/content/developers/api-and-webhooks/webhooks.mdx
  packages/twenty-website/src/content/developers/constants/DocsIndex.ts
  packages/twenty-website/src/content/developers/graphql-apis/core-api-graphql.mdx
  packages/twenty-website/src/content/developers/graphql-apis/metadata-api-graphql.mdx
  packages/twenty-website/src/content/developers/rest-apis/core-api-rest.mdx
  packages/twenty-website/src/content/developers/rest-apis/metadata-api-rest.mdx
Labels: blocked: conflict/dependency

#12450 [permissions V2] Add integration tests on relations and objectRecord permissions
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/test/integration/graphql/suites/object-records-permissions/granular-object-records-permissions.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/object-records-permissions/permissions-on-relations.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/granular-settings-permissions.ts
  packages/twenty-server/test/integration/graphql/utils/create-custom-role-with-object-permissions.util.ts
  packages/twenty-server/test/integration/graphql/utils/delete-one-role.util.ts
  packages/twenty-server/test/integration/graphql/utils/update-workspace-member-role.util.ts
Labels: -PR: awaiting author

#12463 update import steps design
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnToFieldSelect.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/SpreadSheetImportModalWrapper.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/SpreadsheetImportTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/StepNavigationButton.tsx
  packages/twenty-front/src/modules/spreadsheet-import/hooks/__tests__/useSpreadsheetImportInitialStep.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useSpreadsheetImportInitialStep.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/ColumnGrid.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UserTableColumn.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SpreadsheetImportStepperContainer.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/components/columns.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/Steps.stories.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx
  packages/twenty-front/src/modules/ui/navigation/step-bar/components/Step.tsx
  packages/twenty-front/src/modules/ui/navigation/step-bar/components/StepBar.tsx
  packages/twenty-ui/src/theme/constants/Modal.ts
Labels: -PR: awaiting review

#12531 Fix workflow run tab not displaying when navigating from side panel to full page
  packages/twenty-front/src/modules/ui/layout/tab-list/components/TabList.tsx
Labels: -PR: awaiting review

#12471 Add missing overrides on entityManager
  packages/twenty-server/src/engine/twenty-orm/datasource/workspace.datasource.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.spec.ts
  packages/twenty-server/src/engine/twenty-orm/entity-manager/workspace-entity-manager.ts
  packages/twenty-server/src/engine/twenty-orm/repository/workspace-select-query-builder.ts
  packages/twenty-server/src/modules/match-participant/match-participant.service.spec.ts
  packages/twenty-server/src/modules/match-participant/match-participant.service.ts
Labels: -PR: awaiting review

#12536 Fix e2e tests and "Use as Draft"
  packages/twenty-e2e-testing/tests/workflow-run.spec.ts
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/components/UseAsDraftWorkflowVersionSingleRecordAction.tsx
  packages/twenty-front/src/modules/workflow/components/OverrideWorkflowDraftConfirmationModal.tsx
  packages/twenty-front/src/modules/workflow/constants/OverrideWorkflowDraftConfirmationModalId.ts
  packages/twenty-front/src/modules/workflow/states/openOverrideWorkflowDraftConfirmationModalState.ts
Labels: -PR: awaiting review, run-e2e

#12467 Fix cursor-based pagination with lexicographic ordering for composite fields
  packages/twenty-server/src/engine/api/graphql/workspace-query-builder/interfaces/object-record.interface.ts
  packages/twenty-server/src/engine/api/utils/__tests__/__snapshots__/build-cursor-composite-field-where-condition.utils.spec.ts.snap
  packages/twenty-server/src/engine/api/utils/__tests__/build-cursor-composite-field-where-condition.utils.spec.ts
  packages/twenty-server/src/engine/api/utils/__tests__/compute-cursor-arg-filter.utils.spec.ts
  packages/twenty-server/src/engine/api/utils/build-cursor-composite-field-where-condition.utils.ts
  packages/twenty-server/src/engine/api/utils/build-cursor-cumulative-where-conditions.utils.ts
  packages/twenty-server/src/engine/api/utils/build-cursor-where-condition.utils.ts
  packages/twenty-server/src/engine/api/utils/compute-cursor-arg-filter.utils.ts
  packages/twenty-server/src/engine/api/utils/compute-operator.utils.ts
  packages/twenty-server/src/engine/api/utils/is-ascending-order.utils.ts
  packages/twenty-server/src/engine/api/utils/validate-and-get-order-by.utils.ts
  packages/twenty-server/test/integration/constants/test-person-ids.constants.ts
  packages/twenty-server/test/integration/graphql/suites/composite-field-pagination.integration-spec.ts
  packages/twenty-server/test/integration/graphql/utils/find-many-operation-factory.util.ts
  packages/twenty-server/test/integration/rest/suites/rest-api-core-find-many.integration-spec.ts
Labels: -PR: awaiting review

#12017 fix: remove pointer cursor and hover effects from readonly form field…
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/form-action/components/WorkflowEditActionFormBuilder.tsx
Labels: -PR: awaiting review

#12460 Make filters and sorts work on record page pagination
  packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx
  packages/twenty-front/src/modules/context-store/states/contextStoreRecordShowParentViewComponentState.ts
  packages/twenty-front/src/modules/object-record/components/RecordChip.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCard.tsx
  packages/twenty-front/src/modules/object-record/record-board/record-board-card/components/RecordBoardCardHeader.tsx
  packages/twenty-front/src/modules/object-record/record-field/contexts/FieldContext.ts
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ChipFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useChipFieldDisplay.ts
  packages/twenty-front/src/modules/object-record/record-index/hooks/useOpenRecordFromIndexView.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts
  packages/twenty-front/src/modules/object-record/record-show/utils/computeRecordShowComponentInstanceId.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellFieldContextLabelIdentifier.tsx
  packages/twenty-front/src/modules/object-record/record-table/record-table-cell/hooks/useOpenRecordTableCellV2.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromActiveFieldsOfViewOrDefaultView.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromParentView.ts
  packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromView.ts
  packages/twenty-front/src/modules/views/utils/getQueryVariablesFromFiltersAndSorts.ts
  packages/twenty-front/src/pages/object-record/RecordShowPage.tsx
Labels: -PR: awaiting review

#12523 Fix unable to reopen record after going back in side panel
  packages/twenty-front/src/modules/command-menu/hooks/useOpenRecordInCommandMenu.ts
  packages/twenty-front/src/modules/object-record/record-right-drawer/states/viewableRecordIdState.ts
Labels: -PR: awaiting review

#12525 Close command menu after destroy
  packages/twenty-front/src/modules/action-menu/actions/components/Action.tsx
  packages/twenty-front/src/modules/action-menu/actions/components/ActionModal.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/no-selection/components/CreateNewTableRecordNoSelectionRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/components/DestroySingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/hooks/useCloseActionMenu.ts
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuSearchRecords.tsx
Labels: -PR: awaiting review

#12436 [permissions] permissions and workflows
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/constants/objects-with-settings-permissions-requirements.ts
  packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/workspace-query-hook/workspace-query-hook.explorer.ts
  packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-builder.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-step.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-trigger.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version.resolver.ts
  packages/twenty-server/src/engine/core-modules/workflow/workflow-api.module.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/constants/setting-permission-type.constants.ts
  packages/twenty-server/src/engine/metadata-modules/remote-server/remote-server.service.ts
  packages/twenty-server/src/engine/metadata-modules/workspace-permissions-cache/workspace-permissions-cache.service.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-version-delete-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/query-hooks/workflow-version-update-one.pre-query.hook.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-common.workspace-service.ts
  packages/twenty-server/src/modules/workflow/common/workspace-services/workflow-version-validation.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-version/workflow-version.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/create-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/delete-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/find-records.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/record-crud/update-record.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/__tests__/workflow-executor.workspace-service.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/__tests__/workflow-statuses-update.job.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-status/jobs/workflow-statuses-update.job.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/automated-trigger/listeners/database-event-trigger.listener.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/jobs/workflow-trigger.job.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
  packages/twenty-server/test/integration/constants/workflow-gql-fields.constants.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/granular-settings-permissions.integration-spec.ts
  packages/twenty-server/test/integration/graphql/suites/settings-permissions/workflows.integration-spec.ts
Labels: -PR: awaiting author

#12551 Fix chromatic tests
  packages/twenty-front/src/modules/activities/tasks/components/__stories__/TaskList.stories.tsx
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/__stories__/FormDateTimeFieldInput.stories.tsx
  packages/twenty-front/src/testing/decorators/RightDrawerDecorator.tsx
Labels: run-chromatic, -PR: awaiting review

#12560 Prevent empty form steps
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/__tests__/assert-form-step-is-valid.util.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-form-step-is-valid.util.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-version-can-be-activated.util.ts
Labels: -PR: awaiting author

#12365 fix(workspace): simplify hostname matching logic in WorkspaceProvider…
  packages/twenty-front/src/modules/workspace/components/WorkspaceProviderEffect.tsx
Labels: -PR: awaiting review

#12306 feat(workspace-selector): (2) add approval domain and invitations workspa…
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts
  packages/twenty-front/src/modules/auth/graphql/fragments/authFragments.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/getLoginTokenFromEmailVerificationToken.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/impersonate.ts
  packages/twenty-front/src/modules/auth/graphql/mutations/signUpInNewWorkspace.ts
  packages/twenty-front/src/modules/auth/graphql/queries/getPublicWorkspaceDataByDomain.ts
  packages/twenty-front/src/modules/auth/hooks/__mocks__/useAuth.ts
  packages/twenty-front/src/modules/auth/hooks/useAuth.ts
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/modules/auth/states/workspaces.ts
  packages/twenty-front/src/modules/auth/utils/availableWorkspacesUtils.ts
  packages/twenty-front/src/modules/object-metadata/hooks/__mocks__/useFieldMetadataItem.ts
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownDefaultComponents.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/MultiWorkspaceDropdownWorkspacesListComponents.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/components/AvailableWorkspaceItem.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/components/WorkspacesForSignIn.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/MultiWorkspaceDropdown/internal/components/WorkspacesForSignUp.tsx
  packages/twenty-front/src/modules/ui/navigation/navigation-drawer/hooks/useFilteredAvailableWorkspaces.ts
  packages/twenty-front/src/modules/users/components/UserProviderEffect.tsx
  packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts
  packages/twenty-front/src/modules/users/graphql/fragments/workspaceUrlsFragment.ts
  packages/twenty-front/src/pages/settings/security/SettingsSecurityApprovedAccessDomain.tsx
  packages/twenty-front/src/testing/graphqlMocks.ts
  packages/twenty-front/src/testing/mock-data/publicWorkspaceDataBySubdomain.ts
  packages/twenty-front/src/testing/mock-data/users.ts
  packages/twenty-server/src/engine/core-modules/auth/auth.resolver.ts
  packages/twenty-server/src/engine/core-modules/auth/dto/available-workspaces.output.ts
  packages/twenty-server/src/engine/core-modules/auth/token/services/login-token.service.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.spec.ts
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/core-modules/workspace-invitation/services/workspace-invitation.service.ts
Labels: -PR: awaiting author

#12572 Add workflow seed
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/constants/workflow-data-seeds.constants.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/services/dev-seeder-data.service.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/prefill-workflows.ts
  packages/twenty-server/src/engine/workspace-manager/standard-objects-prefill-data/standard-objects-prefill-data.ts
Labels: -PR: awaiting author

#12110 Refactor `WorkspaceMemberDto` transpilation
  packages/twenty-server/src/engine/core-modules/user/services/deleted-workspace-member-transpiler.service.ts
  packages/twenty-server/src/engine/core-modules/user/services/workspace-member-transpiler.service.ts
  packages/twenty-server/src/engine/core-modules/user/user.module.ts
  packages/twenty-server/src/engine/core-modules/user/user.resolver.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/permissions.service.ts
  packages/twenty-server/src/engine/metadata-modules/permissions/types/user-workspace-permissions.ts
  packages/twenty-server/src/engine/metadata-modules/role/dtos/user-workspace-permissions.dto.ts
  packages/twenty-server/src/engine/metadata-modules/role/utils/fromRoleEntityToRoleDto.util.ts
  packages/twenty-server/src/engine/metadata-modules/role/utils/fromUserWorkspacePermissionsToUserWorkspacePermissionsDto.ts
  packages/twenty-shared/src/types/ObjectRecordsPermissions.ts
  packages/twenty-shared/src/types/ObjectRecordsPermissionsByRoleId.ts
Labels: -PR: awaiting review

#12590 Fix side panel closing after workflow execution
  packages/twenty-front/src/modules/action-menu/actions/record-actions/run-workflow-actions/hooks/useRunWorkflowRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/run-workflow-actions/hooks/useRunWorkflowRecordAgnosticActions.tsx
Labels: -PR: awaiting review

#12509 Feature - HTTP request node
  packages/twenty-front/src/modules/workflow/types/Workflow.ts
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeIcon.tsx
  packages/twenty-front/src/modules/workflow/workflow-diagram/components/__stories__/WorkflowDiagramStepNodeEditableContent.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowRunStepNodeDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/components/WorkflowStepDetail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionCreateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionDeleteRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionSendEmail.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/components/WorkflowEditActionUpdateRecord.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/constants/OtherActions.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/find-records-action/components/WorkflowEditActionFindRecords.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/__tests__/useWorkflowActionHeader.test.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/useWorkflowActionHeader.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/BodyInput.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/KeyValuePairInput.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/WorkflowEditActionHttpRequest.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/__stories__/WorkflowEditActionHttpRequest.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/constants/HttpRequest.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/hooks/__tests__/useHttpRequestForm.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/hooks/useHttpRequestForm.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/hooks/useHttpRequestOutputSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/__tests__/convertOutputSchemaToJson.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/__tests__/getHttpRequestOutputSchema.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/__tests__/hasNonStringValues.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/__tests__/isMethodWithBody.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/convertOutputSchemaToJson.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/getHttpRequestOutputSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/hasNonStringValues.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/isMethodWithBody.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/__tests__/getActionHeaderTypeOrThrow.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/__tests__/getActionIcon.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionHeaderTypeOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/utils/getActionIconColorOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-trigger/constants/WebhookTriggerHttpMethodOptions.ts
  packages/twenty-server/src/modules/workflow/workflow-builder/workflow-step/workflow-version-step.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/factories/workflow-executor.factory.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/utils/variable-resolver.util.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/guards/is-workflow-http-request-action.guard.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/http-request-action.module.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/http-request.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/types/workflow-http-request-action-input.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/types/workflow-http-request-action-settings.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/types/workflow-action-settings.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/types/workflow-action.type.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-executor.module.ts
Labels: -PR: awaiting author

#12593 Remove shouldCloseCommandMenuOnClick
  packages/twenty-front/src/modules/command-menu/components/CommandMenuItem.tsx
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuSearchRecords.tsx
  packages/twenty-front/src/modules/command-menu/types/Command.ts
Labels: -PR: awaiting CI

#12599 803 timebox improve the ux when creating a new step
  packages/twenty-front/src/modules/workflow/workflow-steps/hooks/useCreateStep.ts
  packages/twenty-server/src/engine/metadata-modules/serverless-function/serverless-function.service.ts
Labels: -PR: awaiting author

#12596 Improved date filter input behavior
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useApplyObjectFilterDropdownFilterValue.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useUpsertObjectFilterDropdownCurrentFilter.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getInitialFilterValue.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useCreateEmptyRecordFilterFromFieldMetadataItem.ts
  packages/twenty-front/src/modules/object-record/record-filter/hooks/useCreateRecordFilterFromObjectFilterDropdownCurrentStates.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/__tests__/getDateFilterDisplayValue.spec.ts
  packages/twenty-front/src/modules/object-record/record-filter/utils/getDateFilterDisplayValue.ts
  packages/twenty-front/src/modules/views/components/ViewBarFilterDropdownFieldSelectMenuItem.tsx
  packages/twenty-front/src/modules/views/hooks/__tests__/useInitializeFilterOnFieldMetadataItemFromViewBarFilterDropdown.test.test.tsx
  packages/twenty-front/src/modules/views/hooks/useInitializeFilterOnFieldMetadataItemFromViewBarFilterDropdown.ts
Labels: -PR: awaiting review

#12489 download record sample - Import
  packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterSubFieldSelectMenu.tsx
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/getCompositeSubFieldLabel.ts
  packages/twenty-front/src/modules/object-record/object-filter-dropdown/utils/isExpectedSubFieldName.ts
  packages/twenty-front/src/modules/object-record/record-index/export/hooks/useExportRecords.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/constants/CompositeFieldImportLabels.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useBuildAvailableFieldsForImport.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSpreadSheetFieldValidationDefinitions.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/getSubFieldOptionKey.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/spreadsheetImportFilterAvailableFieldMetadataItems.ts.ts
  packages/twenty-front/src/modules/settings/data-model/constants/AllSubFields.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/__tests__/getFieldPreviewValue.test.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getAddressFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getCurrencyFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getPhonesFieldPreviewValue.ts
  packages/twenty-front/src/modules/settings/data-model/utils/isValidSubFieldName.ts
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelectSubFieldSelectDropdownContent.tsx
  packages/twenty-front/src/modules/spreadsheet-import/constants/SpreadsheetMaxRecordImportCapacity.ts
  packages/twenty-front/src/modules/spreadsheet-import/provider/components/SpreadsheetImport.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/ExampleTable.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/Steps.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/Upload.stories.tsx
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/escapeCSVValue.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/__tests__/generateExampleRow.test.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/escapeCSVValue.ts
  packages/twenty-front/src/modules/spreadsheet-import/utils/generateExampleRow.ts
Labels: -PR: awaiting review

#12641 Fix typos in website README
  packages/twenty-website/README.md
Labels: codex

#12639 Improve sync performances
  packages/twenty-server/src/engine/metadata-modules/workspace-migration/workspace-migration.entity.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-field-relation.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/services/workspace-migration-column.service.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/types/postgres-query-runner.type.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/compute-postgres-enum-name.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/internal/typeorm-build-create-column-sql.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/utils/remove-sql-injection.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.module.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-runner/workspace-migration-runner.service.ts
Labels: -PR: awaiting CI

#12640 Fix path typo for timeline repositories
  packages/twenty-server/src/engine/object-metadata-repository/metadata-to-repository.mapping.ts
  packages/twenty-server/src/modules/calendar/calendar-event-participant-manager/listeners/calendar-event-participant.listener.ts
  packages/twenty-server/src/modules/messaging/message-participant-manager/listeners/message-participant.listener.ts
  packages/twenty-server/src/modules/timeline/repositories/timeline-activity.repository.ts
  packages/twenty-server/src/modules/timeline/services/timeline-activity.service.ts
Labels: codex

#12634 Set hotkey scope when navigating in side panel's history
  packages/twenty-front/src/modules/command-menu/hooks/useCommandMenuHistory.ts
Labels: -PR: awaiting review

#12602 fixing index on relations
  packages/twenty-server/src/engine/utils/compute-object-target-table.util.ts
  packages/twenty-server/src/engine/utils/is-field-metadata-of-type.util.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/utils/__tests__/workspace-migration-index.factory.util.spec.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/utils/workspace-migration-index.factory.utils.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-migration-builder/factories/workspace-migration-index.factory.ts
  packages/twenty-server/src/engine/workspace-manager/workspace-sync-metadata/factories/standard-index.factory.ts
Labels: scope: backend, -PR: awaiting author

#12683 Fix banner z-index
  packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx
Labels: -PR: awaiting author

#12627 Import - Increase record import limit
  packages/twenty-front/src/modules/activities/hooks/useCreateActivityInDB.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useCreateManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/hooks/useBatchCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/spreadsheet-import/components/StepNavigationButton.tsx
  packages/twenty-front/src/modules/spreadsheet-import/constants/SpreadsheetImportCreateRecordsBatchSize.ts
  packages/twenty-front/src/modules/spreadsheet-import/constants/SpreadsheetMaxRecordImportCapacity.ts
  packages/twenty-front/src/modules/spreadsheet-import/hooks/__tests__/useSpreadsheetImport.test.tsx
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useHideStepBar.ts
  packages/twenty-front/src/modules/spreadsheet-import/hooks/useOpenSpreadsheetImportDialog.ts
  packages/twenty-front/src/modules/spreadsheet-import/provider/components/SpreadsheetImportProvider.tsx
  packages/twenty-front/src/modules/spreadsheet-import/states/spreadsheetImportCreatedRecordsProgressState.ts
  packages/twenty-front/src/modules/spreadsheet-import/states/spreadsheetImportDialogState.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ImportDataStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/SelectHeaderStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectSheetStep/SelectSheetStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SpreadsheetImportStepper.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/SpreadsheetImportStepperContainer.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/components/DropZone.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/ValidationStep/ValidationStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/types/SpreadsheetImportStep.ts
  packages/twenty-front/src/modules/spreadsheet-import/steps/types/SpreadsheetImportStepType.ts
  packages/twenty-front/src/modules/spreadsheet-import/types/SpreadsheetImportDialogOptions.ts
  packages/twenty-front/src/modules/views/hooks/internal/usePersistViewGroupRecords.ts
Labels: -PR: awaiting author

#12699 fix missing trash x off icon
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/constants/settingsRoleObjectPermissionIconConfig.ts
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRole.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRoleCreateEffect.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRoleLabelContainer.tsx
  packages/twenty-ui/src/assets/icons/trash-x-off.svg
  packages/twenty-ui/src/display/icon/components/IconTrashXOff.tsx
  packages/twenty-ui/src/display/index.ts
Labels: -PR: awaiting review

#12702 Fix table fetchMore flakyness
  packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts
  packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyFetchMoreLoader.tsx
Labels: -PR: awaiting review

#12689 [permissions] Adapt defaultPath to permissions
  packages/twenty-front/src/modules/navigation/hooks/__tests__/useDefaultHomePagePath.test.ts
  packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts
  packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerGater.tsx
  packages/twenty-front/src/testing/mock-data/users.ts
Labels: -PR: awaiting author

#12657 [permissions] Filter tabs + registered actions according to permissions
  packages/twenty-front/src/modules/action-menu/actions/record-actions/constants/DefaultRecordActionsConfig.tsx
  packages/twenty-front/src/modules/action-menu/actions/types/ShouldBeRegisteredFunctionParams.ts
  packages/twenty-front/src/modules/action-menu/actions/utils/getActionConfig.ts
  packages/twenty-front/src/modules/action-menu/hooks/useRegisteredActions.ts
  packages/twenty-front/src/modules/action-menu/hooks/useShouldActionBeRegisteredParams.ts
  packages/twenty-front/src/modules/auth/states/objectPermissionsFamilySelector.ts
  packages/twenty-front/src/modules/command-menu/components/__stories__/CommandMenu.stories.tsx
  packages/twenty-front/src/modules/object-record/record-show/constants/BaseRecordLayout.ts
  packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts
  packages/twenty-front/src/modules/ui/layout/tab-list/types/RecordLayoutTab.ts
  packages/twenty-front/src/modules/ui/layout/tab-list/types/TabVisibilityConfig.ts
  packages/twenty-front/src/testing/mock-data/users.ts
Labels: -PR: awaiting author

#12692 Improve seeds for timeline activities
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/services/dev-seeder-data.service.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/data/services/timeline-activity-seeder.service.ts
  packages/twenty-server/src/engine/workspace-manager/dev-seeder/dev-seeder.module.ts
Labels: -PR: awaiting author

#12695 Use optimistic rendering when executing a workflow with manual trigger
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/run-workflow-actions/hooks/useRunWorkflowRecordActions.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-actions/components/TestWorkflowSingleRecordAction.tsx
  packages/twenty-front/src/modules/action-menu/actions/record-agnostic-actions/run-workflow-actions/hooks/useRunWorkflowRecordAgnosticActions.tsx
  packages/twenty-front/src/modules/object-record/cache/hooks/useUpsertFindOneRecordQueryInCache.ts
  packages/twenty-front/src/modules/subscription/components/ListenUpdatesEffect.tsx
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowRunOpeningInCommandMenuSideEffects.ts
  packages/twenty-front/src/modules/workflow/hooks/useRunWorkflowVersion.tsx
  packages/twenty-server/src/engine/core-modules/workflow/dtos/run-workflow-version-input.dto.ts
  packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-trigger.resolver.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/workspace-services/workflow-trigger.workspace-service.ts
Labels: -PR: awaiting author

#12746 fix(auth): handle availableWorkspacesCount correctly when listing wor…
  packages/twenty-server/src/engine/core-modules/auth/services/auth.service.ts
Labels: -PR: awaiting review

#12737 [permissions][FE] followup design fixes 4
  packages/twenty-front/src/modules/settings/roles/components/SettingsRolesContainer.tsx
  packages/twenty-front/src/modules/settings/roles/components/SettingsRolesDefaultRole.tsx
  packages/twenty-front/src/modules/settings/roles/components/SettingsRolesList.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelObjectPicker.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelOverrideCell.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelOverrideCellContainer.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/SettingsRolePermissionsObjectLevelObjectFormObjectLevel.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/object-form/components/SettingsRolePermissionsObjectLevelObjectFormObjectLevelTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/utils/objectPermissionKeyToHumanReadableText.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/components/SettingsRolePermissionsObjectsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/objects-permissions/types/SettingsRolePermissionsObjectPermission.ts
  packages/twenty-front/src/modules/settings/roles/role-permissions/settings-permissions/components/SettingsRolePermissionsSettingsSection.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/settings-permissions/components/SettingsRolePermissionsSettingsTableHeader.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/settings-permissions/components/SettingsRolePermissionsSettingsTableRow.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRole.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRoleCreateEffect.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRoleEditEffect.tsx
  packages/twenty-front/src/modules/settings/roles/role/constants/SettingsRoleDetailTabs.ts
Labels: -PR: awaiting review

#12761 fix confirm close dialog + add restart confirm dialog
  packages/twenty-front/src/modules/spreadsheet-import/components/SpreadSheetImportModalCloseButton.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/SpreadSheetImportModalWrapper.tsx
  packages/twenty-front/src/modules/spreadsheet-import/provider/components/SpreadsheetImport.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx
  packages/twenty-front/src/modules/spreadsheet-import/steps/components/__stories__/SelectHeader.stories.tsx
  packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx
Labels: -PR: awaiting review

#12769 Hide tab system for pending form nodes
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/components/CommandMenuWorkflowRunViewStepContent.tsx
  packages/twenty-front/src/modules/command-menu/pages/workflow/step/view-run/utils/getShouldFocusNodeTab.ts
Labels: -PR: awaiting review

#12802 Set error message not absolute
  packages/twenty-front/src/modules/object-record/record-field/form-types/components/FormNumberFieldInput.tsx
  packages/twenty-front/src/modules/ui/input/components/InputHint.tsx
Labels: -PR: awaiting review

#12793 [Permissions][FE] Design followup 5
  packages/twenty-front/src/modules/apollo/services/__tests__/apollo.factory.test.ts
  packages/twenty-front/src/modules/auth/states/currentWorkspaceMemberState.ts
  packages/twenty-front/src/modules/favorites/hooks/__mocks__/useFavorites.ts
  packages/twenty-front/src/modules/object-record/hooks/__tests__/useFindManyRecords.test.tsx
  packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/ForbiddenFieldDisplay.tsx
  packages/twenty-front/src/modules/object-record/record-table/utils/buildRecordInputFromFilter.spec.ts
  packages/twenty-front/src/modules/search/hooks/__tests__/useFilteredSearchRecordQuery.test.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentWorkspaceMemberPickerDropdown.tsx
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/SettingsRoleAssignmentWorkspaceMemberPickerDropdownContent.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelectFieldSelectDropdownContent.tsx
  packages/twenty-front/src/modules/spreadsheet-import/components/MatchColumnSelectSubFieldSelectDropdownContent.tsx
  packages/twenty-front/src/modules/ui/theme/hooks/__tests__/useColorScheme.test.tsx
  packages/twenty-front/src/testing/mock-data/workspace-members.ts
  packages/twenty-server/src/engine/core-modules/user/services/workspace-member-transpiler.service.ts
  packages/twenty-ui/src/input/button/components/Button/Button.tsx
  packages/twenty-ui/src/navigation/menu-item/components/MenuItemAvatar.tsx
Labels: -PR: awaiting review

#12791 register all cron jobs in entrypoint
  .dockerignore
  packages/twenty-docker/docker-compose.yml
  packages/twenty-docker/twenty/entrypoint.sh
  packages/twenty-server/src/database/commands/cron-register-all.command.ts
  packages/twenty-server/src/database/commands/database-command.module.ts
  packages/twenty-server/src/modules/calendar/calendar-event-import-manager/calendar-event-import-manager.module.ts
  packages/twenty-server/src/modules/messaging/message-import-manager/messaging-import-manager.module.ts
  packages/twenty-server/src/modules/workflow/workflow-trigger/automated-trigger/automated-trigger.module.ts
Labels: -PR: awaiting review

#12805 Fix CombinedFindManyRecords with permissions
  packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts
Labels: -PR: awaiting review

#12826 Add object level form to role creation
  packages/twenty-front/src/modules/settings/roles/role-assignment/components/stories/SettingsRoleAssignment.stories.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/SettingsRolePermissions.tsx
  packages/twenty-front/src/modules/settings/roles/role-permissions/components/stories/SettingsRolePermissions.stories.tsx
  packages/twenty-front/src/modules/settings/roles/role-settings/components/stories/SettingsRoleSettings.stories.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRole.tsx
  packages/twenty-front/src/modules/settings/roles/role/components/SettingsRoleCreateEffect.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleCreate.tsx
  packages/twenty-front/src/pages/settings/roles/SettingsRoleEdit.tsx
  packages/twenty-server/src/engine/metadata-modules/role/role.service.ts
Labels: -PR: awaiting review

#12833 Add graphql queries error codes metrics
  packages/twenty-server/src/app.module.ts
  packages/twenty-server/src/engine/api/graphql/graphql-config/graphql-config.service.ts
  packages/twenty-server/src/engine/api/graphql/metadata-graphql-api.module.ts
  packages/twenty-server/src/engine/api/graphql/metadata.module-factory.ts
  packages/twenty-server/src/engine/core-modules/graphql/hooks/use-graphql-error-handler.hook.ts
  packages/twenty-server/src/engine/core-modules/metrics/metrics.service.ts
  packages/twenty-server/src/engine/core-modules/metrics/types/metrics-keys.type.ts
Labels: -PR: awaiting review

#12845 fix confirmation modal on subdomain settings
  packages/twenty-front/src/pages/settings/workspace/SettingsDomain.tsx
Labels: -PR: awaiting review

#12794 onboarding - signout button on `Choose your workspaces` modal
  packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx
  packages/twenty-front/src/pages/auth/SignInUp.tsx
Labels: -PR: awaiting review

#12873 Enable the opening of email threads and calendar events from the timeline
  packages/twenty-front/src/modules/activities/timeline-activities/rows/calendar/components/EventCardCalendarEvent.tsx
  packages/twenty-front/src/modules/activities/timeline-activities/rows/message/components/EventCardMessage.tsx
Labels: -PR: awaiting review

#12886 fix IndexFieldMetadata availability in IndexMetadata/ObjectMetadata in front
  packages/twenty-front/src/generated-metadata/gql.ts
  packages/twenty-front/src/generated-metadata/graphql.ts
  packages/twenty-front/src/generated/graphql.tsx
  packages/twenty-front/src/modules/object-metadata/graphql/queries.ts
  packages/twenty-front/src/modules/object-metadata/types/IndexMetadataItem.ts
  packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/__tests__/spreadsheetImportGetUnicityRowHook.test.ts
  packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/spreadsheetImportGetUnicityRowHook.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/__tests__/query-runner.util.spec.ts
  packages/twenty-server/src/engine/api/graphql/workspace-query-runner/utils/query-runner-links.util.ts
  packages/twenty-server/src/engine/core-modules/record-transformer/utils/transform-links-value.util.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.interface.ts
  packages/twenty-server/src/engine/dataloaders/dataloader.service.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/dtos/index-metadata.dto.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.module.ts
  packages/twenty-server/src/engine/metadata-modules/index-metadata/index-metadata.resolver.ts
  packages/twenty-server/src/modules/contact-creation-manager/services/create-company.service.ts
  packages/twenty-shared/src/utils/index.ts
  packages/twenty-shared/src/utils/url/__tests__/lowercaseUrlAndRemoveTrailingSlash.test.ts
  packages/twenty-shared/src/utils/url/lowercaseUrlAndRemoveTrailingSlash.ts
Labels: -PR: awaiting review

#12920 Workspace creation - fix not found file during avatar picture copy
  packages/twenty-server/src/engine/core-modules/user-workspace/user-workspace.service.ts
Labels: -PR: awaiting review

#12966 Fix server integration tests due to expired token
  packages/twenty-server/jest-integration.config.ts
Labels: -PR: awaiting review

#12908 Add a limit to workflow queue per workspace
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-diagram/utils/getWorkflowRunStatusTagProps.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/1-2/1-2-add-enqueued-status-to-workflow-run.command.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/1-2/1-2-upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade-version-command.module.ts
  packages/twenty-server/src/database/commands/upgrade-version-command/upgrade.command.ts
  packages/twenty-server/src/engine/core-modules/cache-storage/types/cache-storage-namespace.enum.ts
  packages/twenty-server/src/engine/core-modules/metrics/types/metrics-keys.type.ts
  packages/twenty-server/src/engine/core-modules/throttler/throttler.exception.ts
  packages/twenty-server/src/engine/core-modules/throttler/throttler.service.ts
  packages/twenty-server/src/modules/workflow/common/standard-objects/workflow-run.workspace-entity.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/jobs/run-workflow.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/utils/__tests__/get-root-steps.utils.spec.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/utils/get-root-steps.utils.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/cron/command/cron-workflow-run-enqueue.cron.command.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/cron/jobs/workflow-run-enqueue.cron.job.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/utils/get-cache-workflow-run-count-key.util.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workflow-run-queue.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-queue.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run/workflow-run.workspace-service.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workflow-runner.module.ts
  packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts
Labels: -PR: awaiting author

#12931 Store HTTP request json body as a string
  packages/twenty-front/src/modules/workflow/validation-schemas/workflowSchema.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/BodyInput.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/KeyValuePairInput.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/__stories__/WorkflowEditActionHttpRequest.stories.tsx
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/constants/HttpRequest.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/__tests__/hasNonStringValues.test.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/hasNonStringValues.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/parseHttpJsonBodyWithoutVariablesOrThrow.ts
  packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/utils/shouldDisplayRawJsonByDefault.ts
  packages/twenty-front/src/modules/workflow/workflow-variables/utils/removeVariablesFromJson.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/http-request.workflow-action.ts
  packages/twenty-server/src/modules/workflow/workflow-executor/workflow-actions/http-request/types/workflow-http-request-action-input.type.ts
Labels: -PR: awaiting review
